[#concurrent_node_map]
== Class Template concurrent_node_map

:idprefix: concurrent_node_map_

`boost::concurrent_node_map` — A node-based hash table that associates unique keys with another value and allows for concurrent element insertion, erasure, lookup and access without external synchronization mechanisms.

Even though it acts as a container, `boost::concurrent_node_map` does not model the standard C++ https://en.cppreference.com/w/cpp/named_req/Container[Container^] concept. In particular, iterators and associated operations (`begin`, `end`, etc.) are not provided. Element access and modification are done through user-provided _visitation functions_ that are passed to `concurrent_node_map` operations where they are executed internally in a controlled fashion. Such visitation-based API allows for low-contention concurrent usage scenarios.

The internal data structure of `boost::concurrent_node_map` is similar to that of `boost::unordered_node_map`. Unlike `boost::concurrent_flat_map`, pointer stability and node handling functionalities are provided, at the expense of potentially lower performance.

=== 概要

[listing, subs="+macros,+quotes"]
-----
// #include xref:reference/header_concurrent_node_map.adoc[`<boost/unordered/concurrent_node_map.hpp>`]

namespace boost {
namespace unordered {

  template<class Key,
           class T,
           class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<std::pair<const Key, T>>>
  class concurrent_node_map {
  public:
    // types
    using key_type             = Key;
    using mapped_type          = T;
    using value_type           = std::pair<const Key, T>;
    using init_type            = std::pair<
                                   typename std::remove_const<Key>::type,
                                   typename std::remove_const<T>::type
                                 >;
    using hasher               = Hash;
    using key_equal            = Pred;
    using allocator_type       = Allocator;
    using pointer              = typename std::allocator_traits<Allocator>::pointer;
    using const_pointer        = typename std::allocator_traits<Allocator>::const_pointer;
    using reference            = value_type&;
    using const_reference      = const value_type&;
    using size_type            = std::size_t;
    using difference_type      = std::ptrdiff_t;

    using node_type            = _implementation-defined_;
    using insert_return_type   = _implementation-defined_;

    using stats                = xref:reference/stats.adoc#stats_stats_type[__stats-type__]; // if statistics are xref:concurrent_node_map_boost_unordered_enable_stats[enabled]

    // constants
    static constexpr size_type xref:#concurrent_node_map_constants[bulk_visit_size] = _implementation-defined_;

    // construct/copy/destroy
    xref:#concurrent_node_map_default_constructor[concurrent_node_map]();
    explicit xref:#concurrent_node_map_bucket_count_constructor[concurrent_node_map](size_type n,
                                 const hasher& hf = hasher(),
                                 const key_equal& eql = key_equal(),
                                 const allocator_type& a = allocator_type());
    template<class InputIterator>
      xref:#concurrent_node_map_iterator_range_constructor[concurrent_node_map](InputIterator f, InputIterator l,
                          size_type n = _implementation-defined_,
                          const hasher& hf = hasher(),
                          const key_equal& eql = key_equal(),
                          const allocator_type& a = allocator_type());
    xref:#concurrent_node_map_copy_constructor[concurrent_node_map](const concurrent_node_map& other);
    xref:#concurrent_node_map_move_constructor[concurrent_node_map](concurrent_node_map&& other);
    template<class InputIterator>
      xref:#concurrent_node_map_iterator_range_constructor_with_allocator[concurrent_node_map](InputIterator f, InputIterator l,const allocator_type& a);
    explicit xref:#concurrent_node_map_allocator_constructor[concurrent_node_map](const Allocator& a);
    xref:#concurrent_node_map_copy_constructor_with_allocator[concurrent_node_map](const concurrent_node_map& other, const Allocator& a);
    xref:#concurrent_node_map_move_constructor_with_allocator[concurrent_node_map](concurrent_node_map&& other, const Allocator& a);
    xref:#concurrent_node_map_move_constructor_from_unordered_node_map[concurrent_node_map](unordered_node_map<Key, T, Hash, Pred, Allocator>&& other);
    xref:#concurrent_node_map_initializer_list_constructor[concurrent_node_map](std::initializer_list<value_type> il,
                        size_type n = _implementation-defined_
                        const hasher& hf = hasher(),
                        const key_equal& eql = key_equal(),
                        const allocator_type& a = allocator_type());
    xref:#concurrent_node_map_bucket_count_constructor_with_allocator[concurrent_node_map](size_type n, const allocator_type& a);
    xref:#concurrent_node_map_bucket_count_constructor_with_hasher_and_allocator[concurrent_node_map](size_type n, const hasher& hf, const allocator_type& a);
    template<class InputIterator>
      xref:#concurrent_node_map_iterator_range_constructor_with_bucket_count_and_allocator[concurrent_node_map](InputIterator f, InputIterator l, size_type n,
                          const allocator_type& a);
    template<class InputIterator>
      xref:#concurrent_node_map_iterator_range_constructor_with_bucket_count_and_hasher[concurrent_node_map](InputIterator f, InputIterator l, size_type n, const hasher& hf,
                          const allocator_type& a);
    xref:#concurrent_node_map_initializer_list_constructor_with_allocator[concurrent_node_map](std::initializer_list<value_type> il, const allocator_type& a);
    xref:#concurrent_node_map_initializer_list_constructor_with_bucket_count_and_allocator[concurrent_node_map](std::initializer_list<value_type> il, size_type n,
                        const allocator_type& a);
    xref:#concurrent_node_map_initializer_list_constructor_with_bucket_count_and_hasher_and_allocator[concurrent_node_map](std::initializer_list<value_type> il, size_type n, const hasher& hf,
                        const allocator_type& a);
    xref:#concurrent_node_map_destructor[~concurrent_node_map]();
    concurrent_node_map& xref:#concurrent_node_map_copy_assignment[operator++=++](const concurrent_node_map& other);
    concurrent_node_map& xref:#concurrent_node_map_move_assignment[operator++=++](concurrent_node_map&& other) ++noexcept(
      (boost::allocator_traits<Allocator>::is_always_equal::value ||
       boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value) &&
       std::is_same<pointer, value_type*>::value);++
    concurrent_node_map& xref:#concurrent_node_map_initializer_list_assignment[operator++=++](std::initializer_list<value_type>);
    allocator_type xref:#concurrent_node_map_get_allocator[get_allocator]() const noexcept;


    // visitation
    template<class F> size_t xref:#concurrent_node_map_cvisit[visit](const key_type& k, F f);
    template<class F> size_t xref:#concurrent_node_map_cvisit[visit](const key_type& k, F f) const;
    template<class F> size_t xref:#concurrent_node_map_cvisit[cvisit](const key_type& k, F f) const;
    template<class K, class F> size_t xref:#concurrent_node_map_cvisit[visit](const K& k, F f);
    template<class K, class F> size_t xref:#concurrent_node_map_cvisit[visit](const K& k, F f) const;
    template<class K, class F> size_t xref:#concurrent_node_map_cvisit[cvisit](const K& k, F f) const;

    template<class FwdIterator, class F>
      size_t xref:concurrent_node_map_bulk_visit[visit](FwdIterator first, FwdIterator last, F f);
    template<class FwdIterator, class F>
      size_t xref:concurrent_node_map_bulk_visit[visit](FwdIterator first, FwdIterator last, F f) const;
    template<class FwdIterator, class F>
      size_t xref:concurrent_node_map_bulk_visit[cvisit](FwdIterator first, FwdIterator last, F f) const;

    template<class F> size_t xref:#concurrent_node_map_cvisit_all[visit_all](F f);
    template<class F> size_t xref:#concurrent_node_map_cvisit_all[visit_all](F f) const;
    template<class F> size_t xref:#concurrent_node_map_cvisit_all[cvisit_all](F f) const;
    template<class ExecutionPolicy, class F>
      void xref:#concurrent_node_map_parallel_cvisit_all[visit_all](ExecutionPolicy&& policy, F f);
    template<class ExecutionPolicy, class F>
      void xref:#concurrent_node_map_parallel_cvisit_all[visit_all](ExecutionPolicy&& policy, F f) const;
    template<class ExecutionPolicy, class F>
      void xref:#concurrent_node_map_parallel_cvisit_all[cvisit_all](ExecutionPolicy&& policy, F f) const;

    template<class F> bool xref:#concurrent_node_map_cvisit_while[visit_while](F f);
    template<class F> bool xref:#concurrent_node_map_cvisit_while[visit_while](F f) const;
    template<class F> bool xref:#concurrent_node_map_cvisit_while[cvisit_while](F f) const;
    template<class ExecutionPolicy, class F>
      bool xref:#concurrent_node_map_parallel_cvisit_while[visit_while](ExecutionPolicy&& policy, F f);
    template<class ExecutionPolicy, class F>
      bool xref:#concurrent_node_map_parallel_cvisit_while[visit_while](ExecutionPolicy&& policy, F f) const;
    template<class ExecutionPolicy, class F>
      bool xref:#concurrent_node_map_parallel_cvisit_while[cvisit_while](ExecutionPolicy&& policy, F f) const;

    // capacity
    ++[[nodiscard]]++ bool xref:#concurrent_node_map_empty[empty]() const noexcept;
    size_type xref:#concurrent_node_map_size[size]() const noexcept;
    size_type xref:#concurrent_node_map_max_size[max_size]() const noexcept;

    // modifiers
    template<class... Args> bool xref:#concurrent_node_map_emplace[emplace](Args&&... args);
    bool xref:#concurrent_node_map_copy_insert[insert](const value_type& obj);
    bool xref:#concurrent_node_map_copy_insert[insert](const init_type& obj);
    bool xref:#concurrent_node_map_move_insert[insert](value_type&& obj);
    bool xref:#concurrent_node_map_move_insert[insert](init_type&& obj);
    template<class InputIterator> size_type xref:#concurrent_node_map_insert_iterator_range[insert](InputIterator first, InputIterator last);
    size_type xref:#concurrent_node_map_insert_initializer_list[insert](std::initializer_list<value_type> il);
    insert_return_type xref:#concurrent_node_map_insert_node[insert](node_type&& nh);

    template<class... Args, class F> bool xref:#concurrent_node_map_emplace_or_cvisit[emplace_or_visit](Args&&... args, F&& f);
    template<class... Args, class F> bool xref:#concurrent_node_map_emplace_or_cvisit[emplace_or_cvisit](Args&&... args, F&& f);
    template<class F> bool xref:#concurrent_node_map_copy_insert_or_cvisit[insert_or_visit](const value_type& obj, F f);
    template<class F> bool xref:#concurrent_node_map_copy_insert_or_cvisit[insert_or_cvisit](const value_type& obj, F f);
    template<class F> bool xref:#concurrent_node_map_copy_insert_or_cvisit[insert_or_visit](const init_type& obj, F f);
    template<class F> bool xref:#concurrent_node_map_copy_insert_or_cvisit[insert_or_cvisit](const init_type& obj, F f);
    template<class F> bool xref:#concurrent_node_map_move_insert_or_cvisit[insert_or_visit](value_type&& obj, F f);
    template<class F> bool xref:#concurrent_node_map_move_insert_or_cvisit[insert_or_cvisit](value_type&& obj, F f);
    template<class F> bool xref:#concurrent_node_map_move_insert_or_cvisit[insert_or_visit](init_type&& obj, F f);
    template<class F> bool xref:#concurrent_node_map_move_insert_or_cvisit[insert_or_cvisit](init_type&& obj, F f);
    template<class InputIterator,class F>
      size_type xref:#concurrent_node_map_insert_iterator_range_or_visit[insert_or_visit](InputIterator first, InputIterator last, F f);
    template<class InputIterator,class F>
      size_type xref:#concurrent_node_map_insert_iterator_range_or_visit[insert_or_cvisit](InputIterator first, InputIterator last, F f);
    template<class F> size_type xref:#concurrent_node_map_insert_initializer_list_or_visit[insert_or_visit](std::initializer_list<value_type> il, F f);
    template<class F> size_type xref:#concurrent_node_map_insert_initializer_list_or_visit[insert_or_cvisit](std::initializer_list<value_type> il, F f);
    template<class F> insert_return_type xref:#concurrent_node_map_insert_node_or_visit[insert_or_visit](node_type&& nh, F f);
    template<class F> insert_return_type xref:#concurrent_node_map_insert_node_or_visit[insert_or_cvisit](node_type&& nh, F f);

    template<class... Args, class F1, class F2>
      bool xref:#concurrent_node_map_emplace_and_cvisit[emplace_and_visit](Args&&... args, F1&& f1, F2&& f2);
    template<class... Args, class F1, class F2>
      bool xref:#concurrent_node_map_emplace_and_cvisit[emplace_and_cvisit](Args&&... args, F1&& f1, F2&& f2);
    template<class F1, class F2> bool xref:#concurrent_node_map_copy_insert_and_cvisit[insert_and_visit](const value_type& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool xref:#concurrent_node_map_copy_insert_and_cvisit[insert_and_cvisit](const value_type& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool xref:#concurrent_node_map_copy_insert_and_cvisit[insert_and_visit](const init_type& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool xref:#concurrent_node_map_copy_insert_and_cvisit[insert_and_cvisit](const init_type& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool xref:#concurrent_node_map_move_insert_and_cvisit[insert_and_visit](value_type&& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool xref:#concurrent_node_map_move_insert_and_cvisit[insert_and_cvisit](value_type&& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool xref:#concurrent_node_map_move_insert_and_cvisit[insert_and_visit](init_type&& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool xref:#concurrent_node_map_move_insert_and_cvisit[insert_and_cvisit](init_type&& obj, F1 f1, F2 f2);
    template<class InputIterator,class F1, class F2>
      size_type xref:#concurrent_node_map_insert_iterator_range_and_visit[insert_and_visit](InputIterator first, InputIterator last, F1 f1, F2 f2);
    template<class InputIterator,class F1, class F2>
      size_type xref:#concurrent_node_map_insert_iterator_range_and_visit[insert_and_cvisit](InputIterator first, InputIterator last, F1 f1, F2 f2);
    template<class F1, class F2>
      size_type xref:#concurrent_node_map_insert_initializer_list_and_visit[insert_and_visit](std::initializer_list<value_type> il, F1 f1, F2 f2);
    template<class F1, class F2>
      size_type xref:#concurrent_node_map_insert_initializer_list_and_visit[insert_and_cvisit](std::initializer_list<value_type> il, F1 f1, F2 f2);
    template<class F1, class F2>
      insert_return_type xref:#concurrent_node_map_insert_node_and_visit[insert_and_visit](node_type&& nh, F1 f1, F2 f2);
    template<class F1, class F2>
      insert_return_type xref:#concurrent_node_map_insert_node_and_visit[insert_and_cvisit](node_type&& nh, F1 f1, F2 f2);

    template<class... Args> bool xref:#concurrent_node_map_try_emplace[try_emplace](const key_type& k, Args&&... args);
    template<class... Args> bool xref:#concurrent_node_map_try_emplace[try_emplace](key_type&& k, Args&&... args);
    template<class K, class... Args> bool xref:#concurrent_node_map_try_emplace[try_emplace](K&& k, Args&&... args);

    template<class... Args, class F>
      bool xref:#concurrent_node_map_try_emplace_or_cvisit[try_emplace_or_visit](const key_type& k, Args&&... args, F&& f);
    template<class... Args, class F>
      bool xref:#concurrent_node_map_try_emplace_or_cvisit[try_emplace_or_cvisit](const key_type& k, Args&&... args, F&& f);
    template<class... Args, class F>
      bool xref:#concurrent_node_map_try_emplace_or_cvisit[try_emplace_or_visit](key_type&& k, Args&&... args, F&& f);
    template<class... Args, class F>
      bool xref:#concurrent_node_map_try_emplace_or_cvisit[try_emplace_or_cvisit](key_type&& k, Args&&... args, F&& f);
    template<class K, class... Args, class F>
      bool xref:#concurrent_node_map_try_emplace_or_cvisit[try_emplace_or_visit](K&& k, Args&&... args, F&& f);
    template<class K, class... Args, class F>
      bool xref:#concurrent_node_map_try_emplace_or_cvisit[try_emplace_or_cvisit](K&& k, Args&&... args, F&& f);

    template<class... Args, class F1, class F2>
      bool xref:#concurrent_node_map_try_emplace_and_cvisit[try_emplace_and_visit](const key_type& k, Args&&... args, F1&& f1, F2&& f2);
    template<class... Args, class F1, class F2>
      bool xref:#concurrent_node_map_try_emplace_and_cvisit[try_emplace_and_cvisit](const key_type& k, Args&&... args, F1&& f1, F2&& f2);
    template<class... Args, class F1, class F2>
      bool xref:#concurrent_node_map_try_emplace_and_cvisit[try_emplace_and_visit](key_type&& k, Args&&... args, F1&& f1, F2&& f2);
    template<class... Args, class F1, class F2>
      bool xref:#concurrent_node_map_try_emplace_and_cvisit[try_emplace_and_cvisit](key_type&& k, Args&&... args, F1&& f1, F2&& f2);
    template<class K, class... Args, class F1, class F2>
      bool xref:#concurrent_node_map_try_emplace_and_cvisit[try_emplace_and_visit](K&& k, Args&&... args, F1&& f1, F2&& f2);
    template<class K, class... Args, class F1, class F2>
      bool xref:#concurrent_node_map_try_emplace_and_cvisit[try_emplace_and_cvisit](K&& k, Args&&... args, F1&& f1, F2&& f2);


    template<class M> bool xref:#concurrent_node_map_insert_or_assign[insert_or_assign](const key_type& k, M&& obj);
    template<class M> bool xref:#concurrent_node_map_insert_or_assign[insert_or_assign](key_type&& k, M&& obj);
    template<class K, class M> bool xref:#concurrent_node_map_insert_or_assign[insert_or_assign](K&& k, M&& obj);

    size_type xref:#concurrent_node_map_erase[erase](const key_type& k);
    template<class K> size_type xref:#concurrent_node_map_erase[erase](const K& k);

    template<class F> size_type xref:#concurrent_node_map_erase_if_by_key[erase_if](const key_type& k, F f);
    template<class K, class F> size_type xref:#concurrent_node_map_erase_if_by_key[erase_if](const K& k, F f);
    template<class F> size_type xref:#concurrent_node_map_erase_if[erase_if](F f);
    template<class ExecutionPolicy, class  F> void xref:#concurrent_node_map_parallel_erase_if[erase_if](ExecutionPolicy&& policy, F f);

    void      xref:#concurrent_node_map_swap[swap](concurrent_node_map& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
               boost::allocator_traits<Allocator>::propagate_on_container_swap::value);

    node_type xref:#concurrent_node_map_extract[extract](const key_type& k);
    template<class K> node_type xref:#concurrent_node_map_extract[extract](const K& k);

    template<class F> node_type xref:#concurrent_node_map_extract_if[extract_if](const key_type& k, F f);
    template<class K, class F> node_type xref:#concurrent_node_map_extract[extract_if](const K& k, F f);

    void      xref:#concurrent_node_map_clear[clear]() noexcept;

    template<class H2, class P2>
      size_type xref:#concurrent_node_map_merge[merge](concurrent_node_map<Key, T, H2, P2, Allocator>& source);
    template<class H2, class P2>
      size_type xref:#concurrent_node_map_merge[merge](concurrent_node_map<Key, T, H2, P2, Allocator>&& source);

    // observers
    hasher xref:#concurrent_node_map_hash_function[hash_function]() const;
    key_equal xref:#concurrent_node_map_key_eq[key_eq]() const;

    // map operations
    size_type        xref:#concurrent_node_map_count[count](const key_type& k) const;
    template<class K>
      size_type      xref:#concurrent_node_map_count[count](const K& k) const;
    bool             xref:#concurrent_node_map_contains[contains](const key_type& k) const;
    template<class K>
      bool           xref:#concurrent_node_map_contains[contains](const K& k) const;

    // bucket interface
    size_type xref:#concurrent_node_map_bucket_count[bucket_count]() const noexcept;

    // hash policy
    float xref:#concurrent_node_map_load_factor[load_factor]() const noexcept;
    float xref:#concurrent_node_map_max_load_factor[max_load_factor]() const noexcept;
    void xref:#concurrent_node_map_set_max_load_factor[max_load_factor](float z);
    size_type xref:#concurrent_node_map_max_load[max_load]() const noexcept;
    void xref:#concurrent_node_map_rehash[rehash](size_type n);
    void xref:#concurrent_node_map_reserve[reserve](size_type n);

    // statistics (if xref:concurrent_node_map_boost_unordered_enable_stats[enabled])
    stats xref:#concurrent_node_map_get_stats[get_stats]() const;
    void xref:#concurrent_node_map_reset_stats[reset_stats]() noexcept;
  };

  // Deduction Guides
  template<class InputIterator,
           class Hash = boost::hash<xref:#concurrent_node_map_iter_key_type[__iter-key-type__]<InputIterator>>,
           class Pred = std::equal_to<xref:#concurrent_node_map_iter_key_type[__iter-key-type__]<InputIterator>>,
           class Allocator = std::allocator<xref:#concurrent_node_map_iter_to_alloc_type[__iter-to-alloc-type__]<InputIterator>>>
    concurrent_node_map(InputIterator, InputIterator, typename xref:#concurrent_node_map_deduction_guides[__see below__]::size_type = xref:#concurrent_node_map_deduction_guides[__see below__],
                        Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> concurrent_node_map<xref:#concurrent_node_map_iter_key_type[__iter-key-type__]<InputIterator>, xref:#concurrent_node_map_iter_mapped_type[__iter-mapped-type__]<InputIterator>, Hash,
                             Pred, Allocator>;

  template<class Key, class T, class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<std::pair<const Key, T>>>
    concurrent_node_map(std::initializer_list<std::pair<Key, T>>,
                        typename xref:#concurrent_node_map_deduction_guides[__see below__]::size_type = xref:#concurrent_node_map_deduction_guides[__see below__], Hash = Hash(),
                        Pred = Pred(), Allocator = Allocator())
      -> concurrent_node_map<Key, T, Hash, Pred, Allocator>;

  template<class InputIterator, class Allocator>
    concurrent_node_map(InputIterator, InputIterator, typename xref:#concurrent_node_map_deduction_guides[__see below__]::size_type, Allocator)
      -> concurrent_node_map<xref:#concurrent_node_map_iter_key_type[__iter-key-type__]<InputIterator>, xref:#concurrent_node_map_iter_mapped_type[__iter-mapped-type__]<InputIterator>,
                             boost::hash<xref:#concurrent_node_map_iter_key_type[__iter-key-type__]<InputIterator>>,
                             std::equal_to<xref:#concurrent_node_map_iter_key_type[__iter-key-type__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Allocator>
    concurrent_node_map(InputIterator, InputIterator, Allocator)
      -> concurrent_node_map<xref:#concurrent_node_map_iter_key_type[__iter-key-type__]<InputIterator>, xref:#concurrent_node_map_iter_mapped_type[__iter-mapped-type__]<InputIterator>,
                             boost::hash<xref:#concurrent_node_map_iter_key_type[__iter-key-type__]<InputIterator>>,
                             std::equal_to<xref:#concurrent_node_map_iter_key_type[__iter-key-type__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Hash, class Allocator>
    concurrent_node_map(InputIterator, InputIterator, typename xref:#concurrent_node_map_deduction_guides[__see below__]::size_type, Hash,
                        Allocator)
      -> concurrent_node_map<xref:#concurrent_node_map_iter_key_type[__iter-key-type__]<InputIterator>, xref:#concurrent_node_map_iter_mapped_type[__iter-mapped-type__]<InputIterator>, Hash,
                             std::equal_to<xref:#concurrent_node_map_iter_key_type[__iter-key-type__]<InputIterator>>, Allocator>;

  template<class Key, class T, class Allocator>
    concurrent_node_map(std::initializer_list<std::pair<Key, T>>, typename xref:#concurrent_node_map_deduction_guides[__see below__]::size_type,
                        Allocator)
      -> concurrent_node_map<Key, T, boost::hash<Key>, std::equal_to<Key>, Allocator>;

  template<class Key, class T, class Allocator>
    concurrent_node_map(std::initializer_list<std::pair<Key, T>>, Allocator)
      -> concurrent_node_map<Key, T, boost::hash<Key>, std::equal_to<Key>, Allocator>;

  template<class Key, class T, class Hash, class Allocator>
    concurrent_node_map(std::initializer_list<std::pair<Key, T>>, typename xref:#concurrent_node_map_deduction_guides[__see below__]::size_type,
                        Hash, Allocator)
      -> concurrent_node_map<Key, T, Hash, std::equal_to<Key>, Allocator>;

} // namespace unordered
} // namespace boost
-----

---

=== 描述

*模板参数*

[cols="1,1"]
|===

|_Key_
.2+|`std::pair<const Key, T>` must be https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible^]
into the table from any `std::pair` object convertible to it, and it also must be
https://en.cppreference.com/w/cpp/named_req/Erasable[Erasable^] from the table.

|_T_

|_Hash_
|一元函数对象类型，用作 `Key` 的哈希函数。它接受一个类型为 `Key` 的参数，并返回一个 `std::size_t` 类型的值。

|_Pred_
|二元函数对象，用于在 `Key` 类型的值上建立等价关系。它接受两个 `极速Key` 类型的参数，并返回一个 `bool` 类型的值。

|_Allocator_
|An allocator whose value type is the same as the table's value type.
Allocators using https://en.cppreference.com/w/cpp/named_req/Allocator#Fancy_pointers[fancy pointers] are supported.

|===

The element nodes of the table are held into an internal _bucket array_. An node is inserted into a bucket determined by the hash code of its element, but if the bucket is already occupied (a _collision_), an available one in the vicinity of the original position is used.

桶数组的大小可通过调用 `insert`/`emplace` 自动增加，或通过调用 `rehash`/`reserve` 来调整。表的 _负载因子_（元素数量除以桶数量）永远不会大于 `max_load_factor()`，除非在小型表中实现可能允许更高的负载。

若 `link:../../../../../container_hash/doc/html/hash.html#ref_hash_is_avalanchinghash[hash_is_avalanching]<Hash>::value` 为 `true`，则直接使用哈希函数；否则将添加位混合后处理阶段以提高哈希质量，但会牺牲额外的计算成本。

---

=== 并发要求与保证

要求在同一 `Hash` 或 `Pred` 的常量实例上并发调用 `operator()` 不会引入数据竞争。对于 `Alloc`（即 `Allocator` 或从 `Allocator` 重新绑定的任何分配器类型），要求在同一 `Alloc` 实例 `al` 上并发调用以下操作不会引入数据竞争：

* 从 `Alloc` 重新绑定的分配器复制构造 `al`
* `std::allocator_traits<Alloc>::allocate`
* `极速std::allocator_traits<Alloc>::deallocate`
* `std::allocator_traits<Alloc>::construct`
* `std::allocator_traits<Alloc>::destroy`

通常，若这些类型无状态或操作仅涉及对内部数据成员的常量访问，则满足对 `Hash`、`Pred` 和 `Allocator` 的这些要求。

With the exception of destruction, concurrent invocations of any operation on the same instance of a `concurrent_node_map` do not introduce data races — that is, they are thread-safe.

If an operation *op* is explicitly designated as _blocking on_ `x`, where `x` is an instance of a `boost::concurrent_node_map`, prior blocking operations on `x` synchronize with *op*. So, blocking operations on the same `concurrent_node_map` execute sequentially in a multithreaded scenario.

若操作仅在内部触发重哈希时阻塞于 `x`，则称该操作 _阻塞于重哈希_ ``__x__``。

When executed internally by a `boost::concurrent_node_map`, the following operations by a user-provided visitation function on the element passed do not introduce data races:

* 对元素的读取访问。
* 对元素的非可变修改。
* 对元素的可变修改：
  ** 在接受两个访问函数的容器函数中，始终适用于第一个函数。
  ** 在名称不包含 `cvisit` 的非 const 容器函数中，适用于最后一个（或唯一）访问函数。

Any `boost::concurrent_node_map operation` that inserts or modifies an element `e` synchronizes with the internal invocation of a visitation function on `e`.

Visitation functions executed by a `boost::concurrent_node_map` `x` are not allowed to invoke any operation on `x`; invoking operations on a different `boost::concurrent_node_map` instance `y` is allowed only if concurrent outstanding operations on `y` do not access `x` directly or indirectly.

---

=== 配置宏

==== `BOOST_UNORDERED_DISABLE_REENTRANCY_CHECK`

在调试构建中（更准确地说，当未定义 link:../../../../../assert/doc/html/assert.html#boost_assert_is_void[`BOOST_ASSERT_IS_VOID`^] 时），会检测 __容器重入__（在访问 `m` 元素的函数内部非法调用 `m` 的操作）并通过 `BOOST_ASSERT_MSG` 发出信号。若关注运行时速度，可通过全局定义此宏禁用该功能。

---

==== `BOOST_UNORDERED_ENABLE_STATS`

全局定义此宏以启用表的 xref:reference/stats.adoc#stats[统计计算]。注意此选项会降低许多操作的总体性能。

---

=== Typedefs

[source, c++, subs=+quotes]
----
typedef _implementation-defined_ node_type;
----

A class for holding extracted table elements, modelling https://en.cppreference.com/w/cpp/container/node_handle[NodeHandle].

---

[source, c++, subs=+quotes]
----
typedef _implementation-defined_ insert_return_type;
----

A specialization of an internal class template:

[source, c++, subs=+quotes]
----
template<class NodeType>
struct _insert_return_type_ // name is exposition only
{
  bool     inserted;
  NodeType node;
};
----

with `NodeType` = `node_type`.

---

=== 常量

```cpp

static constexpr size_type bulk_visit_size;

```

Chunk size internally used in xref:concurrent_node_map_bulk_visit[bulk visit] operations.

---

=== 构造函数

==== 默认构造函数
```c++

concurrent_node_map();

```

使用 `hasher()` 作为哈希函数、`key_equal()` 作为键相等谓词、`allocator_type()` 作为分配器构造空表。

[horizontal]
后置条件：;; `size() == 0`
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 桶数量构造函数
```c++

explicit concurrent_node_map(size_type n,
                             const hasher& hf = hasher(),
                             const key_equal& eql = key_equal(),
                             const allocator_type& a = allocator_type());

```

构造具有至少 `n` 个桶的空表，使用 `hf` 作为哈希函数、`eql` 作为键相等谓词、`a` 作为分配器。

[horizontal]
后置条件：;; `size() == 0`
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  concurrent_node_map(InputIterator f, InputIterator l,
                      size_type n = _implementation-defined_,
                      const hasher& hf = hasher(),
                      const key_equal& eql = key_equal(),
                      const allocator_type& a = allocator_type());
----

构造具有至少 `n` 个桶的空表，使用 `hf` 作为哈希函数、`eql` 作为键相等谓词、`a` 作为分配器，并将 `[f, l)` 中的元素插入其中。

[horizontal]
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 复制构造函数
```c++

concurrent_node_map(concurrent_node_map const& other);

```

复制构造函数。复制所含元素、哈希函数、谓词和分配器。

若 `Allocator::select_on_container_copy_construction` 存在且签名正确，则分配器将根据其结果构造。

[horizontal]
要求：;; `value_type` 可复制构造
并发性：;; 阻塞于 `other`。

---

==== 移动构造函数
```c++

concurrent_node_map(concurrent_node_map&& other);

```

The move constructor. The internal bucket array of `other` is transferred directly to the new table. The hash function, predicate and allocator are moved-constructed from `other`. If statistics are xref:concurrent_node_map_boost_unordered_enable_stats[enabled], transfers the internal statistical information from `other` and calls `other.reset_stats()`.

[horizontal]
并发性：;; 阻塞于 `other`。

---

==== 带分配器的迭代器范围构造函数
```c++

template<class InputIterator>
  concurrent_node_map(InputIterator f, InputIterator l, const allocator_type& a);

```

使用 `a` 作为分配器构造空表，采用默认哈希函数和键相等谓词，并将 `[f, l)` 中的元素插入其中。

[horizontal]
要求：;; `hasher`、`key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 分配器构造函数
```c++

explicit concurrent_node_map(Allocator const& a);

```

使用分配器 `a` 构造空表。

---

==== 带分配器的复制构造函数
```c++

concurrent_node_map(concurrent_node_map const& other, Allocator const& a);

```

构造表，复制 ``other`` 所含元素、哈希函数和谓词，但使用分配器 `a`。

[horizontal]
并发性：;; 阻塞于 `other`。

---

==== 带分配器的移动构造函数
```c++

concurrent_node_map(concurrent_node_map&& other, Allocator const& a);

```

If `a == other.get_allocator()`, the elements of `other` are transferred directly to the new table; otherwise, elements are moved-constructed from those of `other`. The hash function and predicate are moved-constructed from `other`, and the allocator is copy-constructed from `a`. If statistics are xref:concurrent_node_map_boost_unordered_enable_stats[enabled], transfers the internal statistical information from `other` iff `a == other.get_allocator()`, and always calls `other.reset_stats()`.

[horizontal]
并发性：;; 阻塞于 `other`。

---

==== Move Constructor from unordered_node_map

```c++

concurrent_node_map(unordered_node_map<Key, T, Hash, Pred, Allocator>&& other);

```

Move construction from a xref:#unordered_node_map[`unordered_node_map`]. The internal bucket array of `other` is transferred directly to the new container. The hash function, predicate and allocator are moved-constructed from `other`. If statistics are xref:concurrent_node_map_boost_unordered_enable_stats[enabled], transfers the internal statistical information from `other` and calls `other.reset_stats()`.

[horizontal]
复杂度：;; O(`bucket_count()`)

---

==== 初始化列表构造函数
[source, c++, subs="+quotes"]
----
concurrent_node_map(std::initializer_list<value_type> il,
                    size_type n = _implementation-defined_
                    const hasher& hf = hasher(),
                    const key_equal& eql = key_equal(),
                    const allocator_type& a = allocator_type());
----

构造具有至少 `n` 个桶的空表，使用 `hf` 作为哈希函数、`eql` 作为键相等谓词、`a` 作为分配器，并将 `il` 中的元素插入其中。

[horizontal]
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 带分配器的桶数量构造函数
```c++

concurrent_node_map(size_type n, allocator_type const& a);

```

构造具有至少 `n` 个桶的空表，使用默认哈希函数和键相等谓词，以及 `a` 作为分配器。

[horizontal]
后置条件：;; `size() == 0`
要求：;; `hasher` 和 `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 带哈希器和分配器的桶数量构造函数
```c++

concurrent_node_map(size_type n, hasher const& hf, allocator_type const& a);

```

构造具有至少 `n` 个桶的空表，使用 `hf` 作为哈希函数、默认键相等谓词和 `a` 作为分配器。

[horizontal]
后置条件：;; `size() == 0`
要求：;; `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 带桶数量和分配器的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  concurrent_node_map(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
----

构造具有至少 `n` 个桶的空表，使用 `a` 作为分配器及默认哈希函数和键相等谓词，并将 `[f, l)` 中的元素插入其中。

[horizontal]
要求：;; `hasher`、`key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 带桶数量和哈希器的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
    template<class InputIterator>
      concurrent_node_map(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                          const allocator_type& a);
----

构造具有至少 `n` 个桶的空表，使用 `hf` 作为哈希函数、`a` 作为分配器及默认键相等谓词，并将 `[f, l)` 中的元素插入其中。

[horizontal]
要求：;; `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 带分配器的初始化列表构造函数

```c++

concurrent_node_map(std::initializer_list<value_type> il, const allocator_type& a);

```

使用 `a` 及默认哈希函数和键相等谓词构造空表，并将 `il` 中的元素插入其中。

[horizontal]
要求：;; `hasher` 和 `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 带桶数量和分配器的初始化列表构造函数

```c++

concurrent_node_map(std::initializer_list<value_type> il, size_type n, const allocator_type& a);

```

构造具有至少 `n` 个桶的空表，使用 `a` 及默认哈希函数和键相等谓词，并将 `il` 中的元素插入其中。

[horizontal]
要求：;; `hasher` 和 `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 带桶数量、哈希器和分配器的初始化列表构造函数

```c++

concurrent_node_map(std::initializer_list<value_type> il, size_type n, const hasher& hf,
                    const allocator_type& a);

```

构造具有至少 `n` 个桶的空表，使用 `hf` 作为哈希函数、`a` 作为分配器及默认键相等谓词，并将 `il` 中的元素插入其中。

[horizontal]
要求：;; `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

=== 析构函数

```c++

~concurrent_node_map();

```

[horizontal]
注意：;; 析构函数会应用于每个元素，并释放所有内存

---

=== 赋值操作

==== 复制赋值

```c++

concurrent_node_map& operator=(concurrent_node_map const& other);

```

赋值运算符。销毁先前存在的元素，从 `other` 复制赋值哈希函数和谓词，若 `Alloc::propagate_on_container_copy_assignment` 存在且 `Alloc::propag极速ate_on_container_copy_assignment::value` 为 `true` 则从 `other` 复制赋值分配器，最后插入 `other` 元素的副本。

[horizontal]
要求：;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入^]
并发性：;; 阻塞于 `*this` 和 `other`。

---

==== 移动赋值
```c++

concurrent_node_map& operator=(concurrent_node_map&& other)
  noexcept((boost::allocator_traits<Allocator>::is_always_equal::value ||
            boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value) &&
            std::is_same<pointer, value_type*>::value);

```
The move assignment operator. Destroys previously existing elements, swaps the hash function and predicate from `other`,
and move-assigns the allocator from `other` if `Alloc::propagate_on_container_move_assignment` exists and `Alloc::propagate_on_container_move_assignment::value` is `true`.
If at this point the allocator is equal to `other.get_allocator()`, the internal bucket array of `other` is transferred directly to `*this`;
otherwise, inserts move-constructed copies of the elements of `other`.
If statistics are xref:concurrent_node_map_boost_unordered_enable_stats[enabled],
transfers the internal statistical information from `other` iff the final allocator is equal to `other.get_allocator()`,
and always calls `other.reset_stats()`.

[horizontal]
并发性：;; 阻塞于 `*this` 和 `other`。

---

==== 初始化列表赋值
```c++

concurrent_node_map& operator=(std::initializer_list<value_type> il);

```

从初始化列表中的值赋值。销毁所有先前存在的元素。

[horizontal]
要求：;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入^]
并发性：;; 阻塞于 `*this`。

---

=== 访问

==== [c]visit

```c++

template<class F> size_t visit(const key_type& k, F f); template<class F> size_t visit(const key_type& k, F f) const; template<class F> size_t cvisit(const key_type& k, F f) const; template<class K, class F> size_t visit(const K& k, F f); template<class K, class F> size_t visit(const K& k, F f) const; template<class K, class F> size_t cvisit(const K& k, F f) const;

```

If an element `x` exists with key equivalent to `k`, invokes `f` with a reference to `x`. Such reference is const iff `*this` is const.

[horizontal]
返回：;; 访问的元素数量（0 或 1）。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K, class F>` 重载才参与重载解析。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的成本。

---

==== 批量访问

```c++

template<class FwdIterator, class F>
  size_t visit(FwdIterator first, FwdIterator last, F f);
template<class FwdIterator, class F>
  size_t visit(FwdIterator first, FwdIterator last, F f) const;
template<class FwdIterator, class F>
  size_t cvisit(FwdIterator first, FwdIterator last, F f) const;

```

For each element `k` in the range [`first`, `last`), if there is an element `x` in the container with key equivalent to `k`, invokes `f` with a reference to `x`. Such reference is const iff `*this` is const.

Although functionally equivalent to individually invoking xref:concurrent_node_map_cvisit[`[c\]visit`] for each key, bulk visitation performs generally faster due to internal streamlining optimizations. It is advisable that `std::distance(first,last)` be at least xref:#concurrent_node_map_constants[`bulk_visit_size`] to enjoy a performance gain: beyond this size, performance is not expected to increase further.

[horizontal]
要求：;; `FwdIterator` 需满足 https://en.cppreference.com/w/cpp/named_req/ForwardIterator[前向迭代器^]（C++11 至 C++17），或满足 https://en.cppreference.com/w/cpp/iterator/forward_iterator[std::forward_iterator^]（C++20 及更高版本）。对于 `K` = `std::iterator_traits<FwdIterator>::value_type`，`K` 需为 `key_type` 或 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义。后者情况下，库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的成本。
返回：;; 访问的元素数量。

---

==== [c]visit_all

```c++

template<class F> size_t visit_all(F f); template<class F> size_t visit_all(F f) const; template<class F> size_t cvisit_all(F f) const;

```

Successively invokes `f` with references to each of the elements in the table. Such references are const iff `*this` is const.

[horizontal]
返回：;; 访问的元素数量。

---

==== 并行 [c]visit_all

```c++

template<class ExecutionPolicy, class F> void visit_all(ExecutionPolicy&& policy, F f); template<class ExecutionPolicy, class F> void visit_all(ExecutionPolicy&& policy, F f) const; template<class ExecutionPolicy, class极速 F> void cvisit_all(ExecutionPolicy&& policy, F f) const;

```

Invokes `f` with references to each of the elements in the table. Such references are const iff `*this` is const. Execution is parallelized according to the semantics of the execution policy specified.

[horizontal]
抛出：;; 根据所用执行策略的异常处理机制，若 `f` 内抛出异常，可能调用 `std::terminate`。
注意：;; 仅在支持 C++17 并行算法的编译器中可用。+
+
仅当 `std::is_execution_policy_v<std::remove_cvref_t<ExecutionPolicy>>` 为 `true` 时，这些重载才参与重载解析。+
+
不允许非顺序执行策略。

---

==== [c]visit_while

```c++

template<class F> bool visit_while(F f); template<class F> bool visit_while(F f) const; template<class F> bool cvisit_while(F f) const;

```

Successively invokes `f` with references to each of the elements in the table until `f` returns `false` or all the elements are visited. Such references to the elements are const iff `*this` is const.

[horizontal]
返回：;; 若 `f` 曾返回 `false` 则为 `false`，否则为 `true`。

---

==== 并行 [c]visit_while

```c++

template<class ExecutionPolicy, class F> bool visit_while(ExecutionPolicy&& policy, F f); template<class ExecutionPolicy, class F> bool visit_while(ExecutionPolicy&& policy, F f) const; template<class ExecutionPolicy, class F> bool cvisit_while(ExecutionPolicy&& policy, F f) const;

```

Invokes `f` with references to each of the elements in the table until `f` returns `false` or all the elements are visited. Such references to the elements are const iff `*this` is const. Execution is parallelized according to the semantics of the execution policy specified.

[horizontal]
返回：;; 若 `f` 曾返回 `false` 则为 `false`，否则为 `true`。
抛出：;; 根据所用执行策略的异常处理机制，若 `f` 内抛出异常，可能调用 `std::terminate`。
注意：;; 仅在支持 C++17 并行算法的编译器中可用。+
+
仅当 `std::is_execution_policy_v<std::remove_cvref_t<ExecutionPolicy>>` 为 `true` 时，这些重载才参与重载解析。+
+
不允许非顺序执行策略。+
+
并行化意味着执行不必然在 `f` 返回 `false` 时立即结束，因此 `f` 可能继续被调用，即使对后续元素返回值也为 `false`。

---

=== 大小与容量

==== empty

```c++

[[nodiscard]] bool empty() const noexcept;

```

[horizontal]
返回：;; `size() == 0`

---

==== size

```c++

size_type size() const noexcept;

```

[horizontal]
返回：;; 表中的元素数量。

[horizontal]
注意：;; 在并发插入操作存在时，返回值可能无法准确反映执行后表的真实大小。

---

==== max_size

```c++

size_type max_size() const noexcept;

```

[horizontal]
返回：;; 最大可能表的 `size()`。

---

=== 修改器

==== emplace
```c++

template<class... Args> bool emplace(Args&&... args);

```

当且仅当表中不存在等价键的元素时，插入一个由参数 `args` 构造的对象。

[horizontal]
要求：;; `value_type` 可由 `args` 构造。
返回：;; 若发生插入则返回 `true`。
并发性：;; 阻塞于 `*this` 的重哈希过程。
注意：;; If `args...` is of the form `k,v`, it delays constructing the whole object until it is certain that an element should be inserted, using only the `k` argument to check.

---

==== 复制插入
```c++

bool insert(const value_type& obj); bool insert(const init_type& obj);

```

当且仅当表中不存在等价键的元素时，插入 `obj`。

[horizontal]
要求：;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入^]。
返回：;; 若发生插入则返回 `true`。+
并发性：;; 阻塞于 `*this` 的重哈希过程。
注意：;; A call of the form `insert(x)`, where `x` is equally convertible to both `const value_type&` and `const init_type&`, is not ambiguous and selects the `init_type` overload.

---

==== 移动插入
```c++

bool insert(value_type&& obj); bool insert(init_type&& obj);

```

当且仅当表中不存在等价键的元素时，插入 `obj`。

[horizontal]
要求：;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入^]。
返回：;; 若发生插入则返回 `true`。
并发性：;; 阻塞于 `*this` 的重哈希过程。
注意：;; A call of the form `insert(x)`, where `x` is equally convertible to both `value_type&&` and `init_type&&`, is not ambiguous and selects the `init_type` overload.

---

==== 插入迭代器范围
```c++

template<class InputIterator> size_type insert(InputIterator first, InputIterator last);

```

等效于
[listing, subs="+macros,+quotes"]
-----
  while(first != last) this->xref:#concurrent_node_map_emplace[emplace](*first++);
-----

[horizontal]
返回：;; 插入的元素数量。

---

==== 插入初始化列表
```c++

size_type insert(std::initializer_list<value_type> il);

```

等效于
[listing, subs="+macros,+quotes"]
-----
  this->xref:#concurrent_node_map_insert_iterator_range[insert](il.begin(), il.end());
-----

[horizontal]
返回：;; 插入的元素数量。

---

==== Insert Node
```c++

insert_return_type insert(node_type&& nh);

```

If `nh` is not empty, inserts the associated element in the table if and only if there is no element in the table with a key equivalent to `nh.key()`. `nh` is empty when the function returns.

[horizontal]
返回：;; An `insert_return_type` object constructed from `inserted` and `node`: +
* If `nh` is empty, `inserted` is `false` and `node` is empty.
* Otherwise if the insertion took place, `inserted` is true and `node` is empty.
* If the insertion failed, `inserted` is false and `node` has the previous value of `nh`.
抛出：;; If an exception is thrown by an operation other than a call to `hasher` the function has no effect.
并发性：;; 阻塞于 `*this` 的重哈希过程。
注意：;; Behavior is undefined if `nh` is not empty and the allocators of `nh` and the container are not equal.

---

==== emplace_or_[c]visit
```c++

template<class... Args, class F> bool emplace_or_visit(Args&&... args, F&& f); template<class... Args, class F> bool emplace_or_cvisit(Args&&... args, F&& f);

```

Inserts an object, constructed with the arguments `args`, in the table if there is no element in the table with an equivalent key. Otherwise, invokes `f` with a reference to the equivalent element; such reference is const iff `emplace_or_cvisit` is used.

[horizontal]
要求：;; `value_type` 可由 `args` 构造。
返回：;; 若发生插入则返回 `true`。
并发性：;; 阻塞于 `*this` 的重哈希过程。
注意：;; 该接口仅为示意，因 C++ 不允许在可变参数包后声明参数 `f`。

---

==== 复制 insert_or_[c]visit
```c++

template<class F> bool insert_or_visit(const value_type& obj, F f); template<class F> bool insert_or_cvisit(const value_type& obj, F f); template<class F> bool insert_or_visit(const init_type& obj, F f); template<class F> bool insert_or_cvisit(const init_type& obj, F f);

```

Inserts `obj` in the table if and only if there is no element in the table with an equivalent key. Otherwise, invokes `f` with a reference to the equivalent element; such reference is const iff a `*_cvisit` overload is used.

[horizontal]
要求：;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入^]。
返回：;; 若发生插入则返回 `true`。+
并发性：;; 阻塞于 `*this` 的重哈希过程。
注意：;; In a call of the form `insert_or_[c]visit(obj, f)`, the overloads accepting a `const value_type&` argument participate in overload resolution only if `std::remove_cv<std::remove_reference<decltype(obj)>::type>::type` is `value_type`.

---

==== 移动 insert_or_[c]visit
```c++

template<class F> bool insert_or_visit(value_type&& obj, F f); template<class F> bool insert_or_cvisit(value_type&& obj, F f); template<class F> bool insert_or_visit(init_type&& obj, F f); template<class F> bool insert_or_cvisit(init_type&& obj, F f);

```

Inserts `obj` in the table if and only if there is no element in the table with an equivalent key. Otherwise, invokes `f` with a reference to the equivalent element; such reference is const iff a `*_cvisit` overload is used.

[horizontal]
要求：;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入^]。
返回：;; 若发生插入则返回 `true`。+
并发性：;; 阻塞于 `*this` 的重哈希过程。
注意：;; In a call of the form `insert_or_[c]visit(obj, f)`, the overloads accepting a `value_type&&` argument participate in overload resolution only if `std::remove_reference<decltype(obj)>::type` is `value_type`.

---

==== 插入迭代器范围或访问
```c++

template<class InputIterator,class F>
    size_type insert_or_visit(InputIterator first, InputIterator last, F f);
template<class InputIterator,class极速 F>
    size_type insert_or_cvisit(InputIterator first, InputIterator last, F f);

```

等效于
[listing, subs="+macros,+quotes"]
-----
  while(first != last) this->xref:#concurrent_node_map_emplace_or_cvisit[emplace_or_[c\]visit](*first++, f);
-----

[horizontal]
返回：;; 插入的元素数量。

---

==== 插入初始化列表或访问
```c++

template<class F> size_type insert_or_visit(std::initializer_list<value_type> il, F f); template<class F> size_type insert_or_cvisit(std::initializer_list<value_type> il, F f);

```

等效于
[listing, subs="+macros,+quotes"]
-----
  this->xref:#concurrent_node_map_insert_iterator_range_or_visit[insert_or_[c\]visit](il.begin(), il.end(), std::ref(f));
-----

[horizontal]
返回：;; 插入的元素数量。

---

==== Insert Node or Visit
```c++

template<class F> insert_return_type insert_or_visit(node_type&& nh, F f); template<class F> insert_return_type insert_or_cvisit(node_type&& nh, F f);

```

If `nh` is empty, does nothing. Otherwise, inserts the associated element in the table if and only if there is no element in the table with a key equivalent to `nh.key()`. Otherwise, invokes `f` with a reference to the equivalent element; such reference is const iff `insert_or_cvisit` is used.

[horizontal]
返回：;; An `insert_return_type` object constructed from `inserted` and `node`: +
* If `nh` is empty, `inserted` is `false` and `node` is empty.
* Otherwise if the insertion took place, `inserted` is true and `node` is empty.
* If the insertion failed, `inserted` is false and `node` has the previous value of `nh`.
抛出：;; If an exception is thrown by an operation other than a call to `hasher` or call to `f`, the function has no effect.
并发性：;; 阻塞于 `*this` 的重哈希过程。
注意：;; Behavior is undefined if `nh` is not empty and the allocators of `nh` and the container are not equal.

---

==== emplace_and_[c]visit
```c++

template<class... Args, class F1, class F2>
  bool emplace_and_visit(Args&&... args, F1&& f1, F2&& f2);
template<class... Args, class F1, class F2>
  bool emplace_and_cvisit(Args&&... args, F1&& f1, F2&& f2);

```

Inserts an object, constructed with the arguments `args`, in the table if there is no element in the table with an equivalent key, and then invokes `f1` with a non-const reference to the newly created element. Otherwise, invokes `f2` with a reference to the equivalent element; such reference is const iff `emplace_and_cvisit` is used.

[horizontal]
要求：;; `value_type` 可由 `args` 构造。
返回：;; 若发生插入则返回 `true`。
并发性：;; 阻塞于 `*this` 的重哈希过程。
注意：;; 该接口仅为示意，因 C++ 不允许在可变参数包后声明参数 `f1` 和 `f2`。

---

==== 复制 insert_and_[c]visit
```c++

template<class F1, class F2> bool insert_and_visit(const value_type& obj, F1 f1, F2 f2); template<class F1, class F2> bool insert_and_cvisit(const value_type& obj, F1 f1, F2 f2); template<class F1, class F2> bool insert_and_visit(const init_type& obj, F1 f1, F2 f2); template<class F1, class F2> bool insert_and_cvisit(const init_type& obj, F1 f1, F2 f2);

```

Inserts `obj` in the table if and only if there is no element in the table with an equivalent key, and then invokes `f1` with a non-const reference to the newly created element. Otherwise, invokes `f2` with a reference to the equivalent element; such reference is const iff a `*_cvisit` overload is used.

[horizontal]
要求：;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入^]。
返回：;; 若发生插入则返回 `true`。+
并发性：;; 阻塞于 `*this` 的重哈希过程。
注意：;; In a call of the form `insert_and_[c]visit(obj, f1, f2)`, the overloads accepting a `const value_type&` argument participate in overload resolution only if `std::remove_cv<std::remove_reference<decltype(obj)>::type>::type` is `value_type`.

---

==== 移动 insert_and_[c]visit
```c++

template<class F1, class F2> bool insert_and_visit(value_type&& obj, F1 f1, F2 f2); template<class F1, class F2> bool insert_and_cvisit(value_type&& obj, F1 f1, F2 f2); template<class F1, class F2> bool insert_and_visit(init_type&& obj, F1 f1, F2 f2); template<class F1, class F2> bool insert_and_cvisit(init_type&& obj, F1 f1, F2 f2);

```

Inserts `obj` in the table if and only if there is no element in the table with an equivalent key, and then invokes `f1` with a non-const reference to the newly created element. Otherwise, invokes `f2` with a reference to the equivalent element; such reference is const iff a `*_cvisit` overload is used.

[horizontal]
要求：;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入^]。
返回：;; 若发生插入则返回 `true`。+
并发性：;; 阻塞于 `*this` 的重哈希过程。
注意：;; In a call of the form `insert_and_[c]visit(obj, f1, f2)`, the overloads accepting a `value_type&&` argument participate in overload resolution only if `std::remove_reference<decltype(obj)>::type` is `value_type`.

---

==== 插入迭代器范围并访问
```c++

template<class InputIterator, class F1, class F2>
    size_type insert_or_visit(InputIterator first, InputIterator last, F1 f1, F2 f2);
template<class InputIterator, class F1, class F2>
    size_type insert_or_cvisit(InputIterator first, InputIterator last, F1 f2, F2 f2);

```

等效于
[listing, subs="+macros,+quotes"]
-----
  while(first != last) this->xref:#concurrent_node_map_emplace_and_cvisit[emplace_and_[c\]visit](*first++, f1, f2);
-----

[horizontal]
返回：;; 插入的元素数量。

---

==== 插入初始化列表并访问
```c++

template<class F1, class F2>
  size_type insert_and_visit(std::initializer_list<value_type> il, F1 f1, F2 f2);
template<class F1, class F2>
  size_type insert_and_cvisit(std::initializer_list<value_type> il, F1 f1, F2 f2);

```

等效于
[listing, subs="+macros,+quotes"]
-----
  this->xref:#concurrent_node_map_insert_iterator_range_and_visit[insert_and_[c\]visit](il.begin(), il.end(), std::ref(f1), std::ref(f2));
-----

[horizontal]
返回：;; 插入的元素数量。

---

==== Insert Node and Visit
```c++

template<class F1, class F2>
  insert_return_type insert_and_visit(node_type&& nh, F1 f1, F2 f2);
template<class F1, class F2>
  insert_return_type insert_and_cvisit(node_type&& nh, F1 f1, F2 f2);

```

If `nh` is empty, does nothing. Otherwise, inserts the associated element in the table if and only if there is no element in the table with a key equivalent to `nh.key()`, and then invokes `f1` with a non-const reference to the newly inserted element. Otherwise, invokes `f2` with a reference to the equivalent element; such reference is const iff `insert_or_cvisit` is used.

[horizontal]
返回：;; An `insert_return_type` object constructed from `inserted` and `node`: +
* If `nh` is empty, `inserted` is `false` and `node` is empty.
* Otherwise if the insertion took place, `inserted` is true and `node` is empty.
* If the insertion failed, `inserted` is false and `node` has the previous value of `nh`.
抛出：;; If an exception is thrown by an operation other than a call to `hasher` or call to `f1` or `f2`, the function has no effect.
并发性：;; 阻塞于 `*this` 的重哈希过程。
注意：;; Behavior is undefined if `nh` is not empty and the allocators of `nh` and the container are not equal.

---

==== try_emplace
```c++

template<class... Args> bool try_emplace(const key_type& k, Args&&... args); template<class... Args> bool try_emplace(key_type&& k, Args&&... args); template<class K, class... Args> bool try_emplace(K&& k, Args&&... args);

```

Inserts an element constructed from `k` and `args` into the table if there is no existing element with key `k` contained within it.

[horizontal]
返回：;; 若发生插入则返回 `true`。+
并发性：;; 阻塞于 `*this` 的重哈希过程。
注意：;; This function is similiar to xref:#concurrent_node_map_emplace[emplace], with the difference that no `value_type` is constructed if there is an element with an equivalent key; otherwise, the construction is of the form: +
+
--
```c++

// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

```

unlike xref:#concurrent_node_map_emplace[emplace], which simply forwards all arguments to ``value_type``'s constructor.

The `template<class K, class\... Args>` overload only participates in overload resolution if `Hash::is_transparent` and `Pred::is_transparent` are valid member typedefs. The library assumes that `Hash` is callable with both `K` and `Key` and that `Pred` is transparent. This enables heterogeneous lookup which avoids the cost of instantiating an instance of the `Key` type.

--

---

==== try_emplace_or_[c]visit
```c++

template<class... Args, class F>
  bool try_emplace_or_visit(const key_type& k, Args&&... args, F&& f);
template<class... Args, class F>
  bool try_emplace_or_cvisit(const key_type& k, Args&&... args, F&& f);
template<class... Args, class F>
  bool try_emplace_or_visit(key_type&& k, Args&&... args, F&& f);
template<class... Args, class F>
  bool try_emplace_or_cvisit(key_type&& k, Args&&... args, F&& f);
template<class K, class... Args, class F>
  bool try_emplace_or_visit(K&& k, Args&&... args, F&& f);
template<class K, class... Args, class F>
  bool try_emplace_or_cvisit(K&& k, Args&&... args, F&& f);

```

Inserts an element constructed from `k` and `args` into the table if there is no existing element with key `k` contained within it. Otherwise, invokes `f` with a reference to the equivalent element; such reference is const iff a `*_cvisit` overload is used.

[horizontal]
返回：;; 若发生插入则返回 `true`。+
并发性：;; 阻塞于 `*this` 的重哈希过程。
注意：;; No `value_type` is constructed if there is an element with an equivalent key; otherwise, the construction is of the form: +
+
--
```c++

// first four overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

// last two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

```

该接口仅为示意，因 C++ 不允许在可变参数包后声明参数 `f`。

The `template<class K, class\... Args, class F>` overloads only participate in overload resolution if `Hash::is_transparent` and `Pred::is_transparent` are valid member typedefs. The library assumes that `Hash` is callable with both `K` and `Key` and that `Pred` is transparent. This enables heterogeneous lookup which avoids the cost of instantiating an instance of the `Key` type.

--

---

==== try_emplace_and_[c]visit
```c++

template<class... Args, class F1, class F2>
  bool try_emplace_and_visit(const key_type& k, Args&&... args, F1&& f1, F2&& f2);
template<class... Args, class F1, class F2>
  bool try_emplace_and_cvisit(const key_type& k, Args&&... args, F1&& f1, F2&& f2);
template<class... Args, class F1, class F2>
  bool try_emplace_and_visit(key_type&& k, Args&&... args, F1&& f1, F2&& f2);
template<class... Args, class F1, class F2>
  bool try_emplace_and_cvisit(key_type&& k, Args&&... args, F1&& f1, F2&& f2);
template<class K, class... Args, class F1, class F2>
  bool try_emplace_and_visit(K&& k, Args&&... args, F1&& f1, F2&& f2);
template<class K, class... Args, class F1, class F2>
  bool try_emplace_and_cvisit(K&& k, Args&&... args, F1&& f1, F2&& f2);

```

Inserts an element constructed from `k` and `args` into the table if there is no existing element with key `k` contained within it, and then invokes `f1` with a non-const reference to the newly created element. Otherwise, invokes `f2` with a reference to the equivalent element; such reference is const iff a `*_cvisit` overload is used.

[horizontal]
返回：;; 若发生插入则返回 `true`。+
并发性：;; 阻塞于 `*this` 的重哈希过程。
注意：;; No `value_type` is constructed if there is an element with an equivalent key; otherwise, the construction is of the form: +
+
--
```c++

// first four overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

// last two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

```

The interface is exposition only, as C++ does not allow to declare parameter `f1` and `f2` after a variadic parameter pack.

The `template<class K, class\... Args, class F1, class F2>` overloads only participate in overload resolution if `Hash::is_transparent` and `Pred::is_transparent` are valid member typedefs. The library assumes that `Hash` is callable with both `K` and `Key` and that `Pred` is transparent. This enables heterogeneous lookup which avoids the cost of instantiating an instance of the `Key` type.

--

---

==== insert_or_assign
```c++

template<class M> bool insert_or_assign(const key_type& k, M&& obj); template<class M> bool insert_or_assign(key_type&& k, M&& obj); template<class K, class M> bool insert_or_assign(K&& k, M&& obj);

```

Inserts a new element into the table or updates an existing one by assigning to the contained value.

If there is an element with key `k`, then it is updated by assigning `std::forward<M>(obj)`.

If there is no such element, it is added to the table as: ```c++

// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))

```

[horizontal]
返回：;; 若发生插入则返回 `true`。
并发性：;; 阻塞于 `*this` 的重哈希过程。
注意：;; The `template<class K, class M>` only participates in overload resolution if `Hash::is_transparent` and `Pred::is_transparent` are valid member typedefs. The library assumes that `Hash` is callable with both `K` and `Key` and that `Pred` is transparent. This enables heterogeneous lookup which avoids the cost of instantiating an instance of the `Key` type.

---

==== erase
```c++

size_type erase(const key_type& k); template<class K> size_type erase(const K& k);

```

若存在键等于 `k` 的元素，则擦除该元素。

[horizontal]
返回：;; 擦除的元素数量（0 或 1）。
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才会抛出异常。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载解析。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的成本。

---

==== 按键条件擦除
```c++

template<class F> size_type erase_if(const key_type& k, F f); template<class K, class F> size_type erase_if(const K& k, F f);

```

若存在键等于 `k` 的元素 `x` 且 `f(x)` 为 `true`，则擦除 `x`。

[horizontal]
返回：;; 擦除的元素数量（0 或 1）。
抛出：;; 仅当 `hasher`、`key_equal` 或 `f` 抛出异常时才会抛出异常。
注意：;; `f` is passed a non-const reference to `x`. +
+
仅当 `std::is_execution_policy_v<std::remove_cvref_t<ExecutionPolicy>>` 为 `false` 时，`template<class K, class F>` 重载才参与重载解析。+
+
仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K, class F>` 重载才参与重载解析。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的成本。

---

==== 条件擦除
```c++

template<class F> size_type erase_if(F f);

```

Successively invokes `f` with non-const references to each of the elements in the table, and erases those for which `f` returns `true`.

[horizontal]
返回：;; 擦除的元素数量。
抛出：;; 仅当 `f` 抛出异常时才会抛出异常。

---

==== 并行条件擦除
```c++

template<class ExecutionPolicy, class F> void erase_if(ExecutionPolicy&& policy, F f);

```

Invokes `f` with non-const references to each of the elements in the table, and erases those for which `f` returns `true`. Execution is parallelized according to the semantics of the execution policy specified.

[horizontal]
抛出：;; 根据所用执行策略的异常处理机制，若 `f` 内抛出异常，可能调用 `std::terminate`。
注意：;; 仅在支持 C++17 并行算法的编译器中可用。+
+
仅当 `std::is_execution_policy_v<std::remove_cvref_t<ExecutionPolicy>>` 为 `true` 时，此重载才参与重载解析。+
+
不允许非顺序执行策略。

---

==== swap
```c++

void swap(concurrent_node_map& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
           boost::allocator_traits<Allocator>::propagate_on_container_swap::value);

```

交换表的内容与参数。

若声明了 `Allocator::propagate_on_container_swap` 且 `Allocator::propagate_on_container_swap::value` 为 `true`，则交换表的分配器；否则，与分配器不等的表交换会导致未定义行为。

[horizontal]
抛出：;; 除非 `key_equal` 或 `hasher` 在交换时抛出异常，否则不抛出。
并发性：;; 阻塞于 `*this` 和 `other`。

---

==== extract
```c++

node_type extract(const key_type& k); template<class K> node_type extract(K&& k);

```

Extracts the element with key equivalent to `k`, if it exists.

[horizontal]
返回：;; A `node_type` object holding the extracted element, or empty if no element was extracted.
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才会抛出异常。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载解析。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的成本。

---

==== extract_if
```c++

template<class F> node_type extract_if(const key_type& k, F f); template<class K, class F> node_type extract_if(K&& k, F f);

```

Extracts the element `x` with key equivalent to `k`, if it exists and `f(x)` is `true`.

[horizontal]
返回：;; A `node_type` object holding the extracted element, or empty if no element was extracted.
抛出：;; Only throws an exception if it is thrown by `hasher` or `key_equal` or `f`.
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载解析。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的成本。

---

==== clear
```c++

void clear() noexcept;

```

擦除表中所有元素。

[horizontal]
后置条件：;; `size() == 0`, `max_load() >= max_load_factor() * bucket_count()`
并发性：;; 阻塞于 `*this`。

---

==== merge
```c++

template<class H2, class P2>
  size_type merge(concurrent_node_map<Key, T, H2, P2, Allocator>& source);
template<class H2, class P2>
  size_type merge(concurrent_node_map<Key, T, H2, P2, Allocator>&& source);

```

将 `source` 中键尚未存在于 `*this` 的所有元素移动插入，并从 `source` 中擦除这些元素。

[horizontal]
返回：;; 插入的元素数量。
并发性：;; 阻塞于 `*this` 和 `source`。

---

=== 观察器

==== get_allocator
```

allocator_type get极速_allocator() const noexcept;

```

[horizontal]
返回：;; 表的分配器。

---

==== hash_function
```

hasher hash_function() const;

```

[horizontal]
返回：;; 表的哈希函数。

---

==== key_eq
```

key_equal key_eq() const;

```

[horizontal]
返回：;; 表的键相等谓词。

---

=== Map Operations

==== count
```c++

size_type        count(const key_type& k) const;
template<class K>
  size_type      count(const K& k) const;

```

[horizontal]
返回：;; 键等于 `k` 的元素数量（0 或 1）。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载解析。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的成本。+
+
在并发插入操作存在时，返回值可能无法准确反映执行后表的真实状态。

---

==== contains
```c++

bool             contains(const key_type& k) const;
template<class K>
  bool           contains(const K& k) const;

```

[horizontal]
返回：;; 布尔值，指示表中是否存在键等于 `k` 的元素。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载解析。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的成本。+
+
在并发插入操作存在时，返回值可能无法准确反映执行后表的真实状态。

---
=== 桶接口

==== bucket_count
```c++

size_type bucket_count() const noexcept;

```

[horizontal]
返回：;; 桶数组的大小。

---

=== 哈希策略

==== load_factor
```c++

float load_factor() const noexcept;

```

[horizontal]
返回：;; `static_cast<float>(size())/static_cast<float>(bucket_count())`，若 `bucket_count() == 0` 则为 `0`。

---

==== max_load_factor

```c++

float max_load_factor() const noexcept;

```

[horizontal]
返回：;; 返回表的最大负载因子。

---

==== 设置最大负载因子
```c++

void max_load_factor(float z);

```

[horizontal]
效果：;; Does nothing, as the user is not allowed to change this parameter. Kept for compatibility with `boost::unordered_map`.

---


==== max_load

```c++

size_type max_load() const noexcept;

```

[horizontal]
返回：;; 表在不触发重哈希的情况下可容纳的最大元素数（假设无后续元素被擦除）。
注意：;; 构造、重哈希或清除后，表的最大负载至少为 `max_load_factor() * bucket_count()`。在高负载条件下擦除元素时，此数值可能减少。+
+
在并发插入操作存在时，返回值可能无法准确反映执行后表的真实状态。

---

==== rehash
```c++

void rehash(size_type n);

```

必要时更改桶数组的大小，使桶数量至少为 `n`，且负载因子小于或等于最大负载因子。适用时，此操作将增加或减少与表关联的 `bucket_count()`。

当 `size() == 0` 时，`rehash(0)` 将释放底层桶数组。

[horizontal]
抛出：;; 若抛出异常，则该函数无效果，除非异常由表的哈希函数或比较函数抛出。
并发性：;; 阻塞于 `*this`。
---

==== reserve
```c++

void reserve(size_type n);

```

等效于 `a.rehash(ceil(n / a.max_load_factor()))`。

与 `rehash` 类似，此函数可用于增加或减少表中的桶数量。

[horizontal]
抛出：;; 若抛出异常，则该函数无效果，除非异常由表的哈希函数或比较函数抛出。
并发性：;; 阻塞于 `*this`。

---

=== 统计信息

==== get_stats
```c++

stats get_stats() const;

```

[horizontal]
返回：;; 对表迄今为止执行的插入和查找操作的统计描述。
注意：;; Only available if xref:reference/stats.adoc#stats[statistics calculation] is xref:concurrent_node_map_boost_unordered_enable_stats[enabled].

---

==== reset_stats
```c++

void reset_stats() noexcept;

```

[horizontal]
效果：;; 将表保存的内部统计信息重置为零。
注意：;; Only available if xref:reference/stats.adoc#stats[statistics calculation] is xref:concurrent_node_map_boost_unordered_enable_stats[enabled].

---

=== 推导指南
若以下任一条件为真，则推导指南不参与重载解析：

  - 具有 `InputIterator` 模板参数，且为该参数推导出的类型不符合输入迭代器要求。
  - 具有 `Allocator` 模板参数，且为该参数推导出的类型不符合分配器要求。
  - 具有 `Hash` 模板参数，且为该参数推导出整型或符合分配器要求的类型。
  - 具有 `Pred` 模板参数，且为该参数推导出符合分配器要求的类型。

A `size_­type` parameter type in a deduction guide refers to the `size_­type` member type of the table type deduced by the deduction guide. Its default value coincides with the default value of the constructor selected.

==== __迭代器值类型__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-value-type__ =
    typename std::iterator_traits<InputIterator>::value_type; // 仅示意
-----

==== __iter-key-type__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-key-type__ = std::remove_const_t<
    std::tuple_element_t<0, xref:#concurrent_node_map_iter_value_type[__iter-value-type__]<InputIterator>>>; // exposition only
-----

==== __iter-mapped-type__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-mapped-type__ =
    std::tuple_element_t<1, xref:#concurrent_node_map_iter_value_type[__iter-value-type__]<InputIterator>>;  // exposition only
-----

==== __iter-to-alloc-type__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-to-alloc-type__ = std::pair<
    std::add_const_t<std::tuple_element_t<0, xref:#concurrent_node_map_iter_value_type[__iter-value-type__]<InputIterator>>>,
    std::tuple_element_t<1, xref:#concurrent_node_map_iter_value_type[__iter-value-type__]<InputIterator>>>; // exposition only
-----

=== 相等比较

==== operator==
```c++

template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator==(const concurrent_node_map<Key, T, Hash, Pred, Alloc>& x,
                  const concurrent_node_map<Key, T, Hash, Pred, Alloc>& y);

```

若 `x.size() == y.size()` 且对于 `x` 中的每个元素，`y` 中均存在具有相同键且值相等的元素（使用 `operator==` 比较值类型），则返回 `true`。

[horizontal]
并发性：;; 阻塞于 `x` 和 `y`。
注意：;; 若两表的相等谓词不等效，则行为未定义。

---

==== operator!=
```c++

template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator!=(const concurrent_node_map<Key, T, Hash, Pred, Alloc>& x,
                  const concurrent_node_map<Key, T, Hash, Pred, Alloc>& y);

```

若 `x.size() == y.size()` 且对于 `x` 中的每个元素，`y` 中均存在具有相同键且值相等的元素（使用 `operator==` 比较值类型），则返回 `false`。

[horizontal]
并发性：;; 阻塞于 `x` 和 `y`。
注意：;; 若两表的相等谓词不等效，则行为未定义。

---

=== Swap
```c++

template<class Key, class T, class Hash, class Pred, class Alloc>
  void swap(concurrent_node_map<Key, T, Hash, Pred, Alloc>& x,
            concurrent_node_map<Key, T, Hash, Pred, Alloc>& y)
    noexcept(noexcept(x.swap(y)));

```

等效于
[listing, subs="+macros,+quotes"]
-----
x.xref:#concurrent_node_map_swap[swap](y);
-----

---

=== 条件擦除
```c++

template<class K, class T, class H, class P, class A, class Predicate>
  typename concurrent_node_map<K, T, H, P, A>::size_type
    erase_if(concurrent_node_map<K, T, H, P, A>& c, Predicate pred);

```

等效于
[listing, subs="+macros,+quotes"]
-----
c.xref:#concurrent_node_map_erase_if[erase_if](pred);
-----

=== 序列化

``concurrent_node_map``s can be archived/retrieved by means of link:../../../../../serialization/index.html[Boost.Serialization^] using the API provided by this library. Both regular and XML archives are supported.

==== Saving an concurrent_node_map to an archive

Saves all the elements of a `concurrent_node_map` `x` to an archive (XML archive) `ar`.

[horizontal]
要求：;; `std::remove_const<key_type>::type` and `std::remove_const<mapped_type>::type` are serializable (XML serializable), and they do support Boost.Serialization `save_construct_data`/`load_construct_data` protocol (automatically suported by https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible^] types).
并发性：;; 阻塞于 `x`。

---

==== Loading an concurrent_node_map from an archive

Deletes all preexisting elements of a `concurrent_node_map` `x` and inserts from an archive (XML archive) `ar` restored copies of the elements of the original `concurrent_node_map` `other` saved to the storage read by `ar`.

[horizontal]
要求：;; `x.key_equal()` 在功能上等效于 `other.key_equal()`。
并发性：;; 阻塞于 `x`。
