[[header]]

[[content]]
[[concurrent_flat_set]]
== 类模板 concurrent_flat_set

`boost::concurrent_flat_set` ——
一种存储唯一值的哈希表，它支持并发的元素插入、删除、查找及访问操作，且无需外部同步机制。

尽管 `boost::concurrent_flat_set` 具备容器特性，但它并不符合 C++标准中的
https://en.cppreference.com/w/cpp/named_req/Container[容器]概念。具体而言，该容器未提供迭代器及相关操作（如`begin`、`end`
等）。元素访问通过用户提供的__访问函数__实现，这些函数被传递至
`concurrent_flat_set`
操作中，并在其内部以受控方式执行。这种基于访问机制的 API
设计能够有效支持低争用的并发应用场景。

`boost::concurrent_flat_set` 的内部数据结构类似于
`boost::unordered_flat_set`。由于其采用开放寻址技术，`value_type`
必须满足可移动构造要求，且在重哈希过程中无法保持指针稳定性。

[[concurrent_flat_set_synopsis]]
=== 概要

....
// #include <boost/unordered/concurrent_flat_set.hpp>

namespace boost {
namespace unordered {

  template<class Key,
           class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<Key>>
  class concurrent_flat_set {
  public:
    // 类型
    using key_type             = Key;
    using value_type           = Key;
    using init_type            = Key;
    using hasher               = Hash;
    using key_equal            = Pred;
    using allocator_type       = Allocator;
    using pointer              = typename std::allocator_traits<Allocator>::pointer;
    using const_pointer        = typename std::allocator_traits<Allocator>::const_pointer;
    using reference            = value_type&;
    using const_reference      = const value_type&;
    using size_type            = std::size_t;
    using difference_type      = std::ptrdiff_t;

    using stats                = 统计类型; // 若统计功能启用

    // 常量
    static constexpr size_type bulk_visit_size = 实现定义;

    // 构造/复制/销毁
    concurrent_flat_set();
    explicit concurrent_flat_set(size_type n,
                                 const hasher& hf = hasher(),
                                 const key_equal& eql = key_equal(),
                                 const allocator_type& a = allocator_type());
    template<class InputIterator>
      concurrent_flat_set(InputIterator f, InputIterator l,
                          size_type n = 实现定义,
                          const hasher& hf = hasher(),
                          const key_equal& eql = key_equal(),
                          const allocator_type& a = allocator_type());
    concurrent_flat_set(const concurrent_flat_set& other);
    concurrent_flat_set(concurrent_flat_set&& other);
    template<class InputIterator>
      concurrent_flat_set(InputIterator f, InputIterator l,const allocator_type& a);
    explicit concurrent_flat_set(const Allocator& a);
    concurrent_flat_set(const concurrent_flat_set& other, const Allocator& a);
    concurrent_flat_set(concurrent_flat_set&& other, const Allocator& a);
    concurrent_flat_set(unordered_flat_set<Key, Hash, Pred, Allocator>&& other);
    concurrent_flat_set(std::initializer_list<value_type> il,
                        size_type n = 实现定义
                        const hasher& hf = hasher(),
                        const key_equal& eql = key_equal(),
                        const allocator_type& a = allocator_type());
    concurrent_flat_set(size_type n, const allocator_type& a);
    concurrent_flat_set(size_type n, const hasher& hf, const allocator_type& a);
    template<class InputIterator>
      concurrent_flat_set(InputIterator f, InputIterator l, size_type n,
                          const allocator_type& a);
    template<class InputIterator>
      concurrent_flat_set(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                          const allocator_type& a);
    concurrent_flat_set(std::initializer_list<value_type> il, const allocator_type& a);
    concurrent_flat_set(std::initializer_list<value_type> il, size_type n,
                        const allocator_type& a);
    concurrent_flat_set(std::initializer_list<value_type> il, size_type n, const hasher& hf,
                        const allocator_type& a);
    ~concurrent_flat_set();
    concurrent_flat_set& operator=(const concurrent_flat_set& other);
    concurrent_flat_set& operator=(concurrent_flat_set&& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
              boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value);
    concurrent_flat_set& operator=(std::initializer_list<value_type>);
    allocator_type get_allocator() const noexcept;


    // 访问
    template<class F> size_t visit(const key_type& k, F f);
    template<class F> size_t visit(const key_type& k, F f) const;
    template<class F> size_t cvisit(const key_type& k, F f) const;
    template<class K, class F> size_t visit(const K& k, F f);
    template<class K, class F> size_t visit(const K& k, F f) const;
    template<class K, class F> size_t cvisit(const K& k, F f) const;

    template<class FwdIterator, class F>
      size_t visit(FwdIterator first, FwdIterator last, F f);
    template<class FwdIterator, class F>
      size_t visit(FwdIterator first, FwdIterator last, F f) const;
    template<class FwdIterator, class F>
      size_t cvisit(FwdIterator first, FwdIterator last, F f) const;

    template<class F> size_t visit_all(F f);
    template<class F> size_t visit_all(F f) const;
    template<class F> size_t cvisit_all(F f) const;
    template<class ExecutionPolicy, class F>
      void visit_all(ExecutionPolicy&& policy, F f);
    template<class ExecutionPolicy, class F>
      void visit_all(ExecutionPolicy&& policy, F f) const;
    template<class ExecutionPolicy, class F>
      void cvisit_all(ExecutionPolicy&& policy, F f) const;

    template<class F> bool visit_while(F f);
    template<class F> bool visit_while(F f) const;
    template<class F> bool cvisit_while(F f) const;
    template<class ExecutionPolicy, class F>
      bool visit_while(ExecutionPolicy&& policy, F f);
    template<class ExecutionPolicy, class F>
      bool visit_while(ExecutionPolicy&& policy, F f) const;
    template<class ExecutionPolicy, class F>
      bool cvisit_while(ExecutionPolicy&& policy, F f) const;

    // 容量
    [[nodiscard]] bool empty() const noexcept;
    size_type size() const noexcept;
    size_type max_size() const noexcept;

    // 修改器
    template<class... Args> bool emplace(Args&&... args);
    bool insert(const value_type& obj);
    bool insert(value_type&& obj);
    template<class K> bool insert(K&& k);
    template<class InputIterator> size_type insert(InputIterator first, InputIterator last);
    size_type insert(std::initializer_list<value_type> il);

    template<class... Args, class F> bool emplace_or_visit(Args&&... args, F&& f);
    template<class... Args, class F> bool emplace_or_cvisit(Args&&... args, F&& f);
    template<class F> bool insert_or_visit(const value_type& obj, F f);
    template<class F> bool insert_or_cvisit(const value_type& obj, F f);
    template<class F> bool insert_or_visit(value_type&& obj, F f);
    template<class F> bool insert_or_cvisit(value_type&& obj, F f);
    template<class K, class F> bool insert_or_visit(K&& k, F f);
    template<class K, class F> bool insert_or_cvisit(K&& k, F f);
    template<class InputIterator,class F>
      size_type insert_or_visit(InputIterator first, InputIterator last, F f);
    template<class InputIterator,class F>
      size_type insert_or_cvisit(InputIterator first, InputIterator last, F f);
    template<class F> size_type insert_or_visit(std::initializer_list<value_type> il, F f);
    template<class F> size_type insert_or_cvisit(std::initializer_list<value_type> il, F f);

    template<class... Args, class F1, class F2>
      bool emplace_and_visit(Args&&... args, F1&& f1, F2&& f2);
    template<class... Args, class F1, class F2>
      bool emplace_and_cvisit(Args&&... args, F1&& f1, F2&& f2);
    template<class F1, class F2> bool insert_and_visit(const value_type& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool insert_and_cvisit(const value_type& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool insert_and_visit(value_type&& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool insert_and_cvisit(value_type&& obj, F1 f1, F2 f2);
    template<class K, class F1, class F2> bool insert_and_visit(K&& k, F1 f1, F2 f2);
    template<class K, class F1, class F2> bool insert_and_cvisit(K&& k, F1 f1, F2 f2);
    template<class InputIterator,class F1, class F2>
      size_type insert_and_visit(InputIterator first, InputIterator last, F1 f1, F2 f2);
    template<class InputIterator,class F1, class F2>
      size_type insert_and_cvisit(InputIterator first, InputIterator last, F1 f1, F2 f2);
    template<class F1, class F2>
      size_type insert_and_visit(std::initializer_list<value_type> il, F1 f1, F2 f2);
    template<class F1, class F2>
      size_type insert_and_cvisit(std::initializer_list<value_type> il, F1 f1, F2 f2);

    size_type erase(const key_type& k);
    template<class K> size_type erase(const K& k);

    template<class F> size_type erase_if(const key_type& k, F f);
    template<class K, class F> size_type erase_if(const K& k, F f);
    template<class F> size_type erase_if(F f);
    template<class ExecutionPolicy, class  F> void erase_if(ExecutionPolicy&& policy, F f);

    void      swap(concurrent_flat_set& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
               boost::allocator_traits<Allocator>::propagate_on_container_swap::value);
    void      clear() noexcept;

    template<class H2, class P2>
      size_type merge(concurrent_flat_set<Key, H2, P2, Allocator>& source);
    template<class H2, class P2>
      size_type merge(concurrent_flat_set<Key, H2, P2, Allocator>&& source);

    // 观察器
    hasher hash_function() const;
    key_equal key_eq() const;

    // 集合操作
    size_type        count(const key_type& k) const;
    template<class K>
      size_type      count(const K& k) const;
    bool             contains(const key_type& k) const;
    template<class K>
      bool           contains(const K& k) const;

    // 桶接口
    size_type bucket_count() const noexcept;

    // 哈希策略
    float load_factor() const noexcept;
    float max_load_factor() const noexcept;
    void max_load_factor(float z);
    size_type max_load() const noexcept;
    void rehash(size_type n);
    void reserve(size_type n);

    // 统计（若启用）
    stats get_stats() const;
    void reset_stats() noexcept;
  };

  // 推导指引
  template<class InputIterator,
           class Hash = boost::hash<迭代器值类型<InputIterator>>,
           class Pred = std::equal_to<迭代器值类型<InputIterator>>,
           class Allocator = std::allocator<迭代器值类型<InputIterator>>>
    concurrent_flat_set(InputIterator, InputIterator, typename 见下文::size_type = 见下文,
                        Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> concurrent_flat_set<迭代器值类型<InputIterator>, Hash, Pred, Allocator>;

  template<class T, class Hash = boost::hash<T>, class Pred = std::equal_to<T>,
           class Allocator = std::allocator<T>>
    concurrent_flat_set(std::initializer_list<T>, typename 见下文::size_type = 见下文,
                        Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> concurrent_flat_set<T, Hash, Pred, Allocator>;

  template<class InputIterator, class Allocator>
    concurrent_flat_set(InputIterator, InputIterator, typename 见下文::size_type, Allocator)
      -> concurrent_flat_set<迭代器值类型<InputIterator>,
                             boost::hash<迭代器值类型<InputIterator>>,
                             std::equal_to<迭代器值类型<InputIterator>>, Allocator>;

  template<class InputIterator, class Allocator>
    concurrent_flat_set(InputIterator, InputIterator, Allocator)
      -> concurrent_flat_set<迭代器值类型<InputIterator>,
                             boost::hash<迭代器值类型<InputIterator>>,
                             std::equal_to<迭代器值类型<InputIterator>>, Allocator>;

  template<class InputIterator, class Hash, class Allocator>
    concurrent_flat_set(InputIterator, InputIterator, typename 见下文::size_type, Hash,
                        Allocator)
      -> concurrent_flat_set<迭代器值类型<InputIterator>, Hash,
                             std::equal_to<迭代器值类型<InputIterator>>, Allocator>;

  template<class T, class Allocator>
    concurrent_flat_set(std::initializer_list<T>, typename 见下文::size_type, Allocator)
      -> concurrent_flat_set<T, boost::hash<T>, std::equal_to<T>, Allocator>;

  template<class T, class Allocator>
    concurrent_flat_set(std::initializer_list<T>, Allocator)
      -> concurrent_flat_set<T, boost::hash<T>, std::equal_to<T>, Allocator>;

  template<class T, class Hash, class Allocator>
    concurrent_flat_set(std::initializer_list<T>, typename 见下文::size_type, Hash, Allocator)
      -> concurrent_flat_set<T, Hash, std::equal_to<T>, Allocator>;

} // namespace unordered
} // namespace boost
....

'''''

[[concurrent_flat_set_description]]
=== 描述

*模板参数*

[width="100%",cols="50%,50%",]
|===
|_键_ |`Key`
必须满足https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入]到容器的要求，并且满足可从容器中https://en.cppreference.com/w/cpp/named_req/Erasable[擦除]的要求。

|_哈希_ |一种一元函数对象类型，用作 `Key` 的哈希函数。它接受一个 `Key`
类型的参数，并返回 `std::size_t` 类型的值。

|_谓词_ |一种二元函数对象，用于在 `Key`
类型的值上建立等价关系。它接受两个类型为`Key`的参数，并返回一个类型为`bool`的值。

|_Allocator_
|一种值类型与容器的值类型相同的分配器。`std::allocator_traits<Allocator>::pointer`
和 `std::allocator_traits<Allocator>::const_pointer` 必须可分别转换为
`value_type*` 和 `const value_type*`。
|===

容器的元素存储在内部的__桶数组__中。元素根据其哈希码被插入到对应的桶中，但如果该桶已被占用（即发生__冲突__），则会使用原始位置附近可用的桶。

桶数组的大小可通过调用 `insert`/`emplace`操作来自动增加，也可通过调用
`rehash`/`reserve`
操作来调整。容器的__负载因子__（元素数量与桶数量的比值）始终不会超过
`max_load_factor()`，但在小规模数据情况下，实现可能允许更高的负载因子。

如果link:../../../../../container_hash/doc/html/hash.html#ref_hash_is_avalanchinghash[`hash_is_avalanching`]`<Hash>::value`为`true`，则直接使用哈希函数；否则，会添加一个位混合后处理阶段以提高哈希质量，但会增加额外的计算成本。

'''''

[[concurrent_flat_set_concurrency_requirements_and_guarantees]]
=== 并发要求与保证

要求在对同一个 `Hash` 或 `Pred` 的常量实例上并发调用 `operator()`
时不得引入数据竞争。对于 `Alloc`（即 `Allocator`
或其重绑定后的任意分配器类型），在同一实例 `al`
上并发调用以下操作时不得引入数据竞争：

* 从 `Alloc` 重绑定的分配器从 `al` 进行复制构造。
* `std::allocator_traits<Alloc>::allocate`
* `std::allocator_traits<Alloc>::deallocate`
* `std::allocator_traits<Alloc>::construct`
* `std::allocator_traits<Alloc>::destroy`

通常，如果`Hash`、`Pred`和`Allocator`这些类型是无状态的，或者操作仅涉及对内部数据成员的常量访问，即可满足上述要求。

除析构操作外，对同一个 `concurrent_flat_set`
实例并发调用任何操作都不会引发数据竞争——即这些操作是线程安全的。

若操作 *op* 显式指定为__阻塞于__ 容器`x`（其中 `x` 是
`boost::concurrent_flat_set` 的实例），则先前对 `x` 的阻塞操作将与 *op*
同步。因此，在多线程场景下，对同一 `concurrent_flat_set`
的阻塞操作将按顺序执行。

若某个操作仅在触发内部重新哈希时才会阻塞于 `x`，则称该操作__阻塞于 _`x`_
的重哈希__。

当由 `boost::concurrent_flat_set`
内部执行时，用户提供的访问函数对传入元素的以下操作不会引发数据竞争：

* 对元素的读取访问。
* 对元素的非可变修改。
* 对元素的可变修改：
+
** 在容器接受两个访问函数的操作中，此条件始终适用于第一个访问函数。
** 在名称不包含 `cvisit`
的非常量容器函数中，此条件适用于最后一个（或唯一一个）访问函数。

任何插入或修改元素 `e` 的 `boost::concurrent_flat_set` 操作都会与在 `e`
的内部调用的访问函数同步。

由 `boost::concurrent_flat_set` `x` 执行的访问函数不允许调用 `x`
上的任何操作；若并发未完成操作不直接或间接访问 `x`，则允许调用不同
`boost::concurrent_flat_set` 实例 `y` 上的操作。

'''''

[[concurrent_flat_set_configuration_macros]]
=== 配置宏

[[concurrent_flat_set_boost_unordered_disable_reentrancy_check]]
==== `BOOST_UNORDERED_DISABLE_REENTRANCY_CHECK`

在调试版本中（更准确地说，当link:../../../../../assert/doc/html/assert.html#boost_assert_is_void[`BOOST_ASSERT_IS_VOID`]未定义时），会检测__容器重入__（即在访问`m`元素的函数内部非法调用`m`的操作），并通过`BOOST_ASSERT_MSG`发出信号。若需关注运行时速度，可通过全局定义此宏来禁用该功能。

'''''

[[concurrent_flat_set_boost_unordered_enable_stats]]
==== `BOOST_UNORDERED_ENABLE_STATS`

全局定义此宏以启用表的link:reference/stats.html#stats[统计计算]功能。请注意，此选项会降低许多操作的总体性能。

'''''

[[concurrent_flat_set_constants]]
=== 常量

[source,highlight]
----
static constexpr size_type bulk_visit_size;
----

在link:#concurrent_flat_set_bulk_visit[批量访问]操作中内部使用的块大小。

[[concurrent_flat_set_constructors]]
=== 构造函数

[[concurrent_flat_set_default_constructor]]
==== 默认构造函数

[source,highlight]
----
concurrent_flat_set();
----

构造一个空容器，使用`hasher()`作为哈希函数、`key_equal()`作为键相等性谓词、`allocator_type()`作为分配器。

[cols=",",]
|===
|后置条件： |`size() == 0`

|要求： |若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_flat_set_bucket_count_constructor]]
==== 桶数量构造函数

[source,highlight]
----
explicit concurrent_flat_set(size_type n,
                             const hasher& hf = hasher(),
                             const key_equal& eql = key_equal(),
                             const allocator_type& a = allocator_type());
----

构造一个至少包含`n`个桶的空容器，使用`hf`作为哈希函数、`eql`作为键相等性谓词、以及`a`作为分配器。

[cols=",",]
|===
|后置条件： |`size() == 0`

|要求： |若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_flat_set_iterator_range_constructor]]
==== 迭代器范围构造函数

[source,highlight]
----
template<class InputIterator>
  concurrent_flat_set(InputIterator f, InputIterator l,
                      size_type n = 实现定义,
                      const hasher& hf = hasher(),
                      const key_equal& eql = key_equal(),
                      const allocator_type& a = allocator_type());
----

构造一个至少包含`n`个桶的空容器，使用`hf`作为哈希函数、`eql`作为键相等性谓词、以及`a`作为分配器，并将`[f, l)`中的元素插入其中。

[cols=",",]
|===
|要求： |若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_flat_set_copy_constructor]]
==== 复制构造函数

[source,highlight]
----
concurrent_flat_set(concurrent_flat_set const& other);
----

复制构造函数。复制所包含的元素、哈希函数、谓词和分配器。

如果 `Allocator::select_on_container_copy_construction`
存在且签名正确，则将根据其结果来构造分配器。

[cols=",",]
|===
|要求： |`value_type`必须满足可复制构造要求。
|并发性： |阻塞于 `other`。
|===

'''''

[[concurrent_flat_set_move_constructor]]
==== 移动构造函数

[source,highlight]
----
concurrent_flat_set(concurrent_flat_set&& other);
----

移动构造函数。该操作将`other`
的内部桶数组直接转移至新容器，其哈希函数、相等性谓词以及分配器均通过移动构造方式从
`other`
转移而来。若统计功能link:#concurrent_flat_set_boost_unordered_enable_stats[启用]，则同时转移
`other` 的内部统计信息并调用 `other.reset_stats()`。

[cols=",",]
|===
|并发性： |阻塞于 `other`。
|===

'''''

[[concurrent_flat_set_iterator_range_constructor_with_allocator]]
==== 带分配器的迭代器范围构造函数

[source,highlight]
----
template<class InputIterator>
  concurrent_flat_set(InputIterator f, InputIterator l, const allocator_type& a);
----

构造一个空容器，使用 `a`
作为分配器以及默认的哈希函数和键相等性谓词，并将区间 `[f, l)`
中的元素插入其中。

[cols=",",]
|===
|要求： |`hasher` 和 `key_equal`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_flat_set_allocator_constructor]]
==== 分配器构造函数

[source,highlight]
----
explicit concurrent_flat_set(Allocator const& a);
----

使用分配器`a`构造一个空容器。

'''''

[[concurrent_flat_set_copy_constructor_with_allocator]]
==== 带分配器的复制构造函数

[source,highlight]
----
concurrent_flat_set(concurrent_flat_set const& other, Allocator const& a);
----

构造一个容器，复制 `other`
中的元素、哈希函数及键相等性谓词，但使用分配器 `a`。

[cols=",",]
|===
|并发性： |阻塞于 `other`。
|===

'''''

[[concurrent_flat_set_move_constructor_with_allocator]]
==== 带分配器的移动构造函数

[source,highlight]
----
concurrent_flat_set(concurrent_flat_set&& other, Allocator const& a);
----

若 `a == other.get_allocator()`，则 `other`
中的元素直接转移至新的容器；否则，元素从 `other`
移动构造。哈希函数和相等性谓词从 `other` 移动构造，分配器从 `a`
复制构造。若统计功能link:#concurrent_flat_set_boost_unordered_enable_stats[启用]，当且仅当
`a == other.get_allocator()` 时，同步转移`other`
的内部统计信息，并始终调用 `other.reset_stats()`。

[cols=",",]
|===
|并发性： |阻塞于 `other`。
|===

'''''

[[concurrent_flat_set_move_constructor_from_unordered_flat_set]]
==== 从 unordered_flat_set 的移动构造函数

[source,highlight]
----
concurrent_flat_set(unordered_flat_set<Key, Hash, Pred, Allocator>&& other);
----

从 link:#unordered_flat_set[`unordered_flat_set`] 进行移动构造。`other`
的内部桶数组直接转移至新容器。其哈希函数、相等性谓词和分配器从 `other`
移动构造。若统计功能link:#concurrent_flat_set_boost_unordered_enable_stats[启用]，则转移`other`
的内部统计信息，并调用 `other.reset_stats()`。

[cols=",",]
|===
|复杂度： |O(`bucket_count()`)
|===

'''''

[[concurrent_flat_set_initializer_list_constructor]]
==== 初始化列表构造函数

[source,highlight]
----
concurrent_flat_set(std::initializer_list<value_type> il,
                    size_type n = 实现定义
                    const hasher& hf = hasher(),
                    const key_equal& eql = key_equal(),
                    const allocator_type& a = allocator_type());
----

构造一个至少包含`n`个桶的空容器，使用`hf`作为哈希函数、`eql`作为键相等性谓词、`a`作为分配器，并将`il`中的元素插入其中。

[cols=",",]
|===
|要求： |若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_flat_set_bucket_count_constructor_with_allocator]]
==== 带分配器的桶数量构造函数

[source,highlight]
----
concurrent_flat_set(size_type n, allocator_type const& a);
----

构造一个至少包含`n`个桶的空容器、使用默认哈希函数和键相等性谓词、以及`a`作为分配器。

[cols=",",]
|===
|后置条件： |`size() == 0`

|要求： |`hasher` 和 `key_equal`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_flat_set_bucket_count_constructor_with_hasher_and_allocator]]
==== 带哈希函数与分配器的桶数量构造函数

[source,highlight]
----
concurrent_flat_set(size_type n, hasher const& hf, allocator_type const& a);
----

构造一个至少包含`n`个桶的空容器，使用`hf`作为哈希函数、默认键相等性谓词、以及`a`作为分配器。

[cols=",",]
|===
|后置条件： |`size() == 0`

|要求： |`key_equal`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_flat_set_iterator_range_constructor_with_bucket_count_and_allocator]]
==== 带桶数量和分配器的迭代器范围构造函数

[source,highlight]
----
template<class InputIterator>
  concurrent_flat_set(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
----

构造一个至少包含`n`个桶的空容器，使用`a`作为分配器、默认哈希函数和键相等性谓词，并将`[f, l)`中的元素插入其中。

[cols=",",]
|===
|要求： |`hasher` 和 `key_equal`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_flat_set_iterator_range_constructor_with_bucket_count_and_hasher]]
==== 带桶数与哈希函数的迭代器范围构造函数

[source,highlight]
----
    template<class InputIterator>
      concurrent_flat_set(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                          const allocator_type& a);
----

构造一个至少包含`n`个桶的空容器，使用`hf`作为哈希函数、`a`作为分配器、默认键相等性谓词，并将`[f, l)`中的元素插入其中。

[cols=",",]
|===
|要求： |`key_equal`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_flat_set_initializer_list_constructor_with_allocator]]
==== 带分配器的初始化列表构造函数

[source,highlight]
----
concurrent_flat_set(std::initializer_list<value_type> il, const allocator_type& a);
----

构造一个空容器，使用 `a`
作为分配器以及默认的哈希函数和键相等性谓词，并将 `il` 中的元素插入其中。

[cols=",",]
|===
|要求： |`hasher` 和 `key_equal`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_flat_set_initializer_list_constructor_with_bucket_count_and_allocator]]
==== 带桶数量和分配器的初始化列表构造函数

[source,highlight]
----
concurrent_flat_set(std::initializer_list<value_type> il, size_type n, const allocator_type& a);
----

构造一个至少包含`n`个桶的空容器，使用`a`和默认哈希函数及键相等性谓词，并将`il`中的元素插入其中。

[cols=",",]
|===
|要求： |`hasher` 和 `key_equal`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_flat_set_initializer_list_constructor_with_bucket_count_and_hasher_and_allocator]]
==== 带桶数量、哈希函数与分配器的初始化列表构造函数

[source,highlight]
----
concurrent_flat_set(std::initializer_list<value_type> il, size_type n, const hasher& hf,
                    const allocator_type& a);
----

构造一个至少包含`n`个桶的空容器，使用`hf`作为哈希函数、`a`作为分配器以及默认键相等性谓词，并将`il`中的元素插入其中。

[cols=",",]
|===
|要求： |`key_equal`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_flat_set_destructor]]
=== 析构函数

[source,highlight]
----
~concurrent_flat_set();
----

[cols=",",]
|===
|注意： |析构函数会作用于每个元素，并释放所有内存。
|===

'''''

[[concurrent_flat_set_assignment]]
=== 赋值

[[concurrent_flat_set_copy_assignment]]
==== 复制赋值

[source,highlight]
----
concurrent_flat_set& operator=(concurrent_flat_set const& other);
----

赋值操作符。该操作会销毁容器中原有的元素，并从 `other`
复制赋值哈希函数与键相等性谓词。若
`Alloc::propagate_on_container_copy_assignment` 存在且
`Alloc::propagate_on_container_copy_assignment::value` 为 `true`，则从
`other` 复制赋值分配器，最后插入 `other` 中所有元素的副本。

[cols=",",]
|===
|要求： |`value_type`
需满足https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入]要求。

|并发性： |阻塞于 `*this` 和 `other`。
|===

'''''

[[concurrent_flat_set_move_assignment]]
==== 移动赋值

[source,highlight]
----
concurrent_flat_set& operator=(concurrent_flat_set&& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
           boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value);
----

移动赋值运算符。该操作会销毁容器中先前存在的元素，交换 `other`
的哈希函数和谓词，若 `Alloc::propagate_on_container_move_assignment`
存在且 `Alloc::propagate_on_container_move_assignment::value` 为
`true`，则从 `other` 移动赋值分配器。若此时分配器与
`other.get_allocator()`相等，则将 `other` 的内部桶数组直接转移至
`*this`；否则插入 `other`
元素的移动构造副本。若统计功能link:#concurrent_flat_set_boost_unordered_enable_stats[启用]，当且仅当最终分配器与
`other.get_allocator()`相等时，转移内部统计信息，并始终调用
`other.reset_stats()`。

[cols=",",]
|===
|并发性： |阻塞于 `*this` 和 `other`。
|===

'''''

[[concurrent_flat_set_initializer_list_assignment]]
==== 初始化列表赋值

[source,highlight]
----
concurrent_flat_set& operator=(std::initializer_list<value_type> il);
----

将初始化列表中的值赋给容器，该操作会销毁所有已存在的元素。

[cols=",",]
|===
|要求： |`value_type`
需满足https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入]要求。

|并发性： |阻塞于 `*this`。
|===

'''''

[[concurrent_flat_set_visitation]]
=== 访问

[[concurrent_flat_set_cvisit]]
==== [c]visit

[source,highlight]
----
template<class F> size_t visit(const key_type& k, F f);
template<class F> size_t visit(const key_type& k, F f) const;
template<class F> size_t cvisit(const key_type& k, F f) const;
template<class K, class F> size_t visit(const K& k, F f);
template<class K, class F> size_t visit(const K& k, F f) const;
template<class K, class F> size_t cvisit(const K& k, F f) const;
----

若存在键等价于 `k` 的元素 `x`，则以 `x` 的常量引用作为参数调用函数 `f`。

[cols=",",]
|===
|返回： |被访问的元素数量（0或1）。

|注意：
|仅当`Hash::is_transparent`和`Pred::is_transparent`均为有效的成员类型别名时，`template<class K, class F>`重载才会参与重载决议。标准库假设`Hash`可同时被`K`和`Key`
类型调用，且`Pred`为透明的。该机制支持异构查找，从而避免实例化 `Key`
类型对象所需的开销。
|===

'''''

[[concurrent_flat_set_bulk_visit]]
==== 批量访问

[source,highlight]
----
template<class FwdIterator, class F>
  size_t visit(FwdIterator first, FwdIterator last, F f);
template<class FwdIterator, class F>
  size_t visit(FwdIterator first, FwdIterator last, F f) const;
template<class FwdIterator, class F>
  size_t cvisit(FwdIterator first, FwdIterator last, F f) const;
----

对于范围 [`first`, `last`) 内的每个元素 `k`，若容器中存在键等价于 `k`
的元素 `x`，则以`x`的常量引用为参数调用函数 `f`。

尽管在功能上等同于对每个键单独调用
link:#concurrent_flat_set_cvisit[`[c]visit`]，但批量访问因内部流线优化而通常具有更快的执行速度。建议
`std::distance(first,last)` 至少达到
link:#concurrent_flat_set_constants[`bulk_visit_size`]
以获得性能提升：超过此大小后，性能预计不再提升。

[cols=",",]
|===
|要求：
|`FwdIterator`需满去https://en.cppreference.com/w/cpp/named_req/ForwardIterator[LegacyForwardIterator]要求（C++11
到
C++17），或符合https://en.cppreference.com/w/cpp/iterator/forward_iterator[std::forward_iterator]（规范C++20
及更高版本）。对于`K` =
`std::iterator_traits<FwdIterator>::value_type`，需满足以下条件之一：`K`
与 `key_type` 类型相同，或 `Hash::is_transparent` 与
`Pred::is_transparent`
均为有效的成员类型别名。对于后一种情况，标准库假定 `Hash` 可同时被 `K`
和 `Key` 调用，且 `Pred`
为透明的。该机制支持异构查找，从而避免实例化`Key` 类型对象所需的开销。

|返回： |被访问的元素数量。
|===

'''''

[[concurrent_flat_set_cvisit_all]]
==== [c]visit_all

[source,highlight]
----
template<class F> size_t visit_all(F f);
template<class F> size_t visit_all(F f) const;
template<class F> size_t cvisit_all(F f) const;
----

依次以常量引用为参数调用 `f` 来访问容器中的每个元素。

[cols=",",]
|===
|返回： |被访问的元素数量。
|===

'''''

[[concurrent_flat_set_parallel_cvisit_all]]
==== 并行 [c]visit_all

[source,highlight]
----
template<class ExecutionPolicy, class F> void visit_all(ExecutionPolicy&& policy, F f);
template<class ExecutionPolicy, class F> void visit_all(ExecutionPolicy&& policy, F f) const;
template<class ExecutionPolicy, class F> void cvisit_all(ExecutionPolicy&& policy, F f) const;
----

以常量引用为参数调用 `f`
来访问容器中的每个元素，该执行为根据指定执行策略的语义并行化的。

[width="100%",cols="50%,50%",]
|===
|抛出： |根据所用执行策略的异常处理机制，若在函数 `f`
内部抛出异常，则可能调用 `std::terminate`。

|注意： a|
仅在支持 C++17 并行算法的编译器中可用。 +

仅当 `std::is_execution_policy_v<std::remove_cvref_t<ExecutionPolicy>>`
为 `true` 时，这些重载才会参与重载决议。 +

不允许使用无序执行策略。

|===

'''''

[[concurrent_flat_set_cvisit_while]]
==== [c]visit_while

[source,highlight]
----
template<class F> bool visit_while(F f);
template<class F> bool visit_while(F f) const;
template<class F> bool cvisit_while(F f) const;
----

依次以常量引用为参数调用 `f` 来访问容器中的每个元素，直到 `f` 返回
`false` 或所有元素均被访问完毕。

[cols=",",]
|===
|返回： |当且仅当 `f` 曾返回 `false` 时，才返回 `false`。
|===

'''''

[[concurrent_flat_set_parallel_cvisit_while]]
==== 并行 [c]visit_while

[source,highlight]
----
template<class ExecutionPolicy, class F> bool visit_while(ExecutionPolicy&& policy, F f);
template<class ExecutionPolicy, class F> bool visit_while(ExecutionPolicy&& policy, F f) const;
template<class ExecutionPolicy, class F> bool cvisit_while(ExecutionPolicy&& policy, F f) const;
----

根据指定的执行策略语义，以容器中每个元素的常量引用为参数并行调用函数
`f`，直到 `f` 返回 `false` 或所有元素均被访问完毕。

[width="100%",cols="50%,50%",]
|===
|返回： |当且仅当 `f` 曾返回 `false` 时，才返回 `false`。

|抛出： |根据所用执行策略的异常处理机制，若在函数 `f`
内部抛出异常，则可能调用 `std::terminate`。

|注意： a|
仅在支持 C++17 并行算法的编译器中可用。 +

仅当 `std::is_execution_policy_v<std::remove_cvref_t<ExecutionPolicy>>`
为 `true` 时，这些重载才会参与重载决议。 +

不允许使用无序执行策略。 +

并行化意味着执行不一定会因 `f` 返回 `false`
而立即结束，因此`f`可能会被其他元素进一步调用（即使其返回值同样为
`false`）。

|===

'''''

[[concurrent_flat_set_size_and_capacity]]
=== 大小与容量

[[concurrent_flat_set_empty]]
==== 空

[source,highlight]
----
[[nodiscard]] bool empty() const noexcept;
----

[cols=",",]
|===
|返回： |`size() == 0`
|===

'''''

[[concurrent_flat_set_size]]
==== 大小

[source,highlight]
----
size_type size() const noexcept;
----

[cols=",",]
|===
|返回： |容器中的元素数量。
|===

[cols=",",]
|===
|注意：
|在存在并发插入操作的情况下，返回值可能无法准确反映执行完成后容器的真实大小。
|===

'''''

[[concurrent_flat_set_max_size]]
==== max_size

[source,highlight]
----
size_type max_size() const noexcept;
----

[cols=",",]
|===
|返回： |返回该容器可能包含的最大元素数量`size()` 。
|===

'''''

[[concurrent_flat_set_modifiers]]
=== 修改器

[[concurrent_flat_set_emplace]]
==== emplace

[source,highlight]
----
template<class... Args> bool emplace(Args&&... args);
----

当且仅当容器中不存在等价键的元素时，插入一个用参数`args`构造的对象。

[cols=",",]
|===
|要求： |`value_type` 必须能够从 `args` 参数构造。
|返回： |若发生插入，则返回 `true`。
|并发性： |阻塞于 `*this` 的重哈希。
|注意： |若触发重哈希操作，则使指向元素的指针和引用失效。
|===

'''''

[[concurrent_flat_set_copy_insert]]
==== 复制插入

[source,highlight]
----
bool insert(const value_type& obj);
----

当且仅当容器中不存在等价键的元素时，将 `obj` 对象插入到容器。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type`
需满足https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入]要求。

|返回： |若发生插入，则返回 `true`。 +

|并发性： |阻塞于 `*this` 的重哈希。

|注意： |若触发重哈希操作，则使指向元素的指针和引用失效。
|===

'''''

[[concurrent_flat_set_move_insert]]
==== 移动插入

[source,highlight]
----
bool insert(value_type&& obj);
----

当且仅当容器中不存在等价键的元素时，将 `obj` 对象插入到容器。

[cols=",",]
|===
|要求： |`value_type`
需满足https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入]要求。

|返回： |若发生插入，则返回 `true`。

|并发性： |阻塞于 `*this` 的重哈希。

|注意： |若触发重哈希操作，则使指向元素的指针和引用失效。
|===

'''''

[[concurrent_flat_set_transparent_insert]]
==== 透明插入

[source,highlight]
----
template<class K> bool insert(K&& k);
----

当且仅当容器中不存在等价键的元素时，插入一个由 `std::forward<K>(k)`
构造的元素。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type` 需满足从 `k`参数
https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原地构造]的要求。

|返回： |若发生插入，则返回 `true`。

|并发性： |阻塞于 `*this` 的重哈希。

|注意： a|
若触发重哈希操作，则使指向元素的指针和引用失效。 +

仅当 `Hash::is_transparent` 和 `Pred::is_transparent`
均为有效的成员类型别名时，此重载才会参与重载决议。标准库假设 `Hash`
可同时被 `K` 和 `Key` 类型调用，且 `Pred`
为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

|===

'''''

[[concurrent_flat_set_insert_iterator_range]]
==== 插入迭代器范围

[source,highlight]
----
template<class InputIterator> size_type insert(InputIterator first, InputIterator last);
----

等价于

....
  while(first != last) this->emplace(*first++);
....

[cols=",",]
|===
|返回： |插入的元素数量。
|===

'''''

[[concurrent_flat_set_insert_initializer_list]]
==== 插入初始化列表

[source,highlight]
----
size_type insert(std::initializer_list<value_type> il);
----

等价于

....
  this->insert(il.begin(), il.end());
....

[cols=",",]
|===
|返回： |插入的元素数量。
|===

'''''

[[concurrent_flat_set_emplace_or_cvisit]]
==== emplace_or_[c]visit

[source,highlight]
----
template<class... Args, class F> bool emplace_or_visit(Args&&... args, F&& f);
template<class... Args, class F> bool emplace_or_cvisit(Args&&... args, F&& f);
----

若容器中不存在等价键的元素，则用参数 `args`
构造对象并插入到容器中；否则，以该等价元素的常量引用为参数调用函数 `f`
。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type` 必须能够从 `args` 参数构造。
|返回： |若发生插入，则返回 `true`。
|并发性： |阻塞于 `*this` 的重哈希。
|注意： a|
若触发重哈希操作，则使指向元素的指针和引用失效。 +

该接口仅为示意，因 C++ 不允许在可变参数包后声明参数 `f`。

|===

'''''

[[concurrent_flat_set_copy_insert_or_cvisit]]
==== 复制 insert_or_[c]visit

[source,highlight]
----
template<class F> bool insert_or_visit(const value_type& obj, F f);
template<class F> bool insert_or_cvisit(const value_type& obj, F f);
----

当且仅当容器中不存在等价键的元素时，将
`obj`插入到容器中；否则，以该等价元素的常量引用为参数调用函数 `f` 。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type`
需满足https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入]要求。

|返回： |若发生插入，则返回 `true`。 +

|并发性： |阻塞于 `*this` 的重哈希。

|注意： |若触发重哈希操作，则使指向元素的指针和引用失效。
|===

'''''

[[concurrent_flat_set_move_insert_or_cvisit]]
==== 移动 insert_or_[c]visit

[source,highlight]
----
template<class F> bool insert_or_visit(value_type&& obj, F f);
template<class F> bool insert_or_cvisit(value_type&& obj, F f);
----

当且仅当容器中不存在等价键的元素时，将
`obj`插入到容器中；否则，以该等价元素的常量引用为参数调用函数 `f` 。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type`
需满足https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入]要求。

|返回： |若发生插入，则返回 `true`。 +

|并发性： |阻塞于 `*this` 的重哈希。

|注意： |若触发重哈希操作，则使指向元素的指针和引用失效。
|===

'''''

[[concurrent_flat_set_transparent_insert_or_cvisit]]
==== 透明 insert_or_[c]visit

[source,highlight]
----
template<class K, class F> bool insert_or_visit(K&& k, F f);
template<class K, class F> bool insert_or_cvisit(K&& k, F f);
----

当且仅当容器中不存在等价键的元素时，插入由 `std::forward<K>(k)`
构造的元素；否则，以该等价元素的常量引用为参数调用函数 `f` 。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type` 需满足从 `k`参数
https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原地构造]的要求。

|返回： |若发生插入，则返回 `true`。

|并发性： |阻塞于 `*this` 的重哈希。

|注意： a|
若触发重哈希操作，则使指向元素的指针和引用失效。 +

仅当 `Hash::is_transparent` 和 `Pred::is_transparent`
均为有效的成员类型别名时，这些重载才会参与重载决议。标准库假设 `Hash`
可同时被 `K` 和 `Key` 类型调用，且 `Pred`
为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

|===

'''''

[[concurrent_flat_set_insert_iterator_range_or_visit]]
==== 插入迭代器范围或访问

[source,highlight]
----
template<class InputIterator,class F>
    size_type insert_or_visit(InputIterator first, InputIterator last, F f);
template<class InputIterator,class F>
    size_type insert_or_cvisit(InputIterator first, InputIterator last, F f);
----

等价于

....
  while(first != last) this->emplace_or_[c]visit(*first++, f);
....

[cols=",",]
|===
|返回： |插入的元素数量。
|===

'''''

[[concurrent_flat_set_insert_initializer_list_or_visit]]
==== 插入初始化列表或访问

[source,highlight]
----
template<class F> size_type insert_or_visit(std::initializer_list<value_type> il, F f);
template<class F> size_type insert_or_cvisit(std::initializer_list<value_type> il, F f);
----

等价于

....
  this->insert_or_[c]visit(il.begin(), il.end(), std::ref(f));
....

[cols=",",]
|===
|返回： |插入的元素数量。
|===

'''''

[[concurrent_flat_set_emplace_and_cvisit]]
==== emplace_and_[c]visit

[source,highlight]
----
template<class... Args, class F1, class F2>
  bool emplace_and_visit(Args&>... args, F1&& f1, F2&> f2);
template<class... Args, class F1, class F2>
  bool emplace_and_cvisit(Args&>... args, F1&> f1, F2&> f2);
----

若容器中不存在等价键的元素，则插入由参数 `args`
构造的对象，并以新元素的常量引用为参数调用函数
`f1`；否则，以该等价元素的常量引用为参数调用函数 `f2`。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type` 必须能够从 `args` 参数构造。
|返回： |若发生插入，则返回 `true`。
|并发性： |阻塞于 `*this` 的重哈希。
|注意： a|
若触发重哈希操作，则使指向元素的指针和引用失效。 +

该接口仅为示意，因 C++ 不允许在可变参数包后声明参数 `f1` 和 `f2`。

|===

'''''

[[concurrent_flat_set_copy_insert_and_cvisit]]
==== 复制 insert_and_[c]visit

[source,highlight]
----
template<class F1, class F2> bool insert_and_visit(const value_type& obj, F1 f1, F2 f2);
template<class F1, class F2> bool insert_and_cvisit(const value_type& obj, F1 f1, F2 f2);
----

当且仅当容器中不存在等价键的元素时，将
`obj`对象插入到容器中，并以新元素的常量引用为参数调用函数
`f1`；否则，以该等价元素的常量引用为参数调用函数 `f2`。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type`
需满足https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入]要求。

|返回： |若发生插入，则返回 `true`。 +

|并发性： |阻塞于 `*this` 的重哈希。

|注意： |若触发重哈希操作，则使指向元素的指针和引用失效。
|===

'''''

[[concurrent_flat_set_move_insert_and_cvisit]]
==== 移动 insert_and_[c]visit

[source,highlight]
----
template<class F1, class F2> bool insert_and_visit(value_type&& obj, F1 f1, F2 f2);
template<class F1, class F2> bool insert_and_cvisit(value_type&& obj, F1 f1, F2 f2);
----

当且仅当容器中不存在等价键的元素时，将
`obj`对象插入到容器中，并以新元素的常量引用为参数调用函数
`f1`；否则，以该等价元素的常量引用为参数调用函数 `f2`。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type`
需满足https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入]要求。

|返回： |若发生插入，则返回 `true`。 +

|并发性： |阻塞于 `*this` 的重哈希。

|注意： |若触发重哈希操作，则使指向元素的指针和引用失效。
|===

'''''

[[concurrent_flat_set_transparent_insert_and_cvisit]]
==== 透明 insert_and_[c]visit

[source,highlight]
----
template<class K, class F1, class F2> bool insert_and_visit(K&> k, F1 f1, F2 f2);
template<class K, class F1, class F2> bool insert_and_cvisit(K&> k, F1 f1, F2 f2);
----

当且仅当容器中不存在等价键的元素时，插入由 `std::forward<K>(k)`
构造的元素，并以新元素的常量引用为参数调用函数
`f1`；否则，以该等价元素的常量引用为参数调用函数 `f2`。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type` 需满足从 `k`参数
https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原地构造]的要求。

|返回： |若发生插入，则返回 `true`。

|并发性： |阻塞于 `*this` 的重哈希。

|注意： a|
若触发重哈希操作，则使指向元素的指针和引用失效。 +

仅当 `Hash::is_transparent` 和 `Pred::is_transparent`
均为有效的成员类型别名时，这些重载才会参与重载决议。标准库假设 `Hash`
可同时被 `K` 和 `Key` 类型调用，且 `Pred`
为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

|===

'''''

[[concurrent_flat_set_insert_iterator_range_and_visit]]
==== 插入迭代器范围并访问

[source,highlight]
----
template<class InputIterator,class F1, class F2>
    size_type insert_and_visit(InputIterator first, InputIterator last, F1 f1, F2 f2);
template<class InputIterator,class F1, class F2>
    size_type insert_and_cvisit(InputIterator first, InputIterator last, F1 f1, F2 f2);
----

等价于

....
  while(first != last) this->emplace_and_[c]visit(*first++, f1, f2);
....

[cols=",",]
|===
|返回： |插入的元素数量。
|===

'''''

[[concurrent_flat_set_insert_initializer_list_and_visit]]
==== 插入初始化列表并访问

[source,highlight]
----
template<class F1, class F2>
  size_type insert_and_visit(std::initializer_list<value_type> il, F1 f1, F2 f2);
template<class F1, class F2>
  size_type insert_and_cvisit(std::initializer_list<value_type> il, F1 f1, F2 f2);
----

等价于

....
  this->insert_and_[c]visit(il.begin(), il.end(), std::ref(f1), std::ref(f2));
....

[cols=",",]
|===
|返回： |插入的元素数量。
|===

'''''

[[concurrent_flat_set_erase]]
==== 擦除

[source,highlight]
----
size_type erase(const key_type& k);
template<class K> size_type erase(const K& k);
----

若存在键等价于 `k` 的元素，则将其擦除。

[cols=",",]
|===
|返回： |插入的元素数量（0 或 1）。

|抛出： |仅当异常由 `hasher` 或 `key_equal` 抛出时，本函数才会抛出异常。

|注意： |仅当 `Hash::is_transparent` 与 `Pred::is_transparent`
均为有效的成员类型别名时，`template<class K>`
重载才会参与重载决议。标准库假设 `Hash` 可同时被 `K` 与 `Key`
类型调用，且 `Pred`
为透明的。这支持异构查找，该机制支持异构查找，从而避免实例化 `Key`
类型的开销。
|===

'''''

[[concurrent_flat_set_erase_if_by_key]]
==== 按键 erase_if

[source,highlight]
----
template<class F> size_type erase_if(const key_type& k, F f);
template<class K, class F> size_type erase_if(const K& k, F f);
----

若存在键等价于 `k` 的元素 `x` 且 `f(x)` 为 `true`，则擦除该元素。

[width="100%",cols="50%,50%",]
|===
|返回： |插入的元素数量（0 或 1）。

|抛出： |仅当 `hasher`、`key_equal` 或 `f` 抛出异常时，才会抛出异常。

|注意： a|
仅当 `std::is_execution_policy_v<std::remove_cvref_t<ExecutionPolicy>>`
为 `false` 时，`template<class K, class F>` 重载才会参与重载决议。 +

仅当 `Hash::is_transparent` 与 `Pred::is_transparent`
均为有效的成员类型别名时，`template<class K, class F>`
重载才会参与重载决议。标准库假设 `Hash` 可同时被 `K` 与 `Key`
类型调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key`
类型的开销。

|===

'''''

[[concurrent_flat_set_erase_if]]
==== erase_if

[source,highlight]
----
template<class F> size_type erase_if(F f);
----

依次以容器中每个元素的引用为参数调用函数 `f`，并擦除所有使 `f` 返回
`true` 的元素。

[cols=",",]
|===
|返回： |被擦除的元素数量。
|抛出： |仅当 `f` 抛出异常时，才会抛出异常。
|===

'''''

[[concurrent_flat_set_parallel_erase_if]]
==== 并行 erase_if

[source,highlight]
----
template<class ExecutionPolicy, class  F> void erase_if(ExecutionPolicy&& policy, F f);
----

根据指定的执行策略语义，以容器中每个元素的引用为参数并行调用函数
`f`，并擦除所有使 `f` 返回 `true` 的元素。

[width="100%",cols="50%,50%",]
|===
|抛出： |根据所用执行策略的异常处理机制，若在函数 `f`
内部抛出异常，则可能调用 `std::terminate`。

|注意： a|
仅在支持 C++17 并行算法的编译器中可用。 +

仅当 `std::is_execution_policy_v<std::remove_cvref_t<ExecutionPolicy>>`
为 `true` 时，此重载才会参与重载决议。 +

不允许使用无序执行策略。

|===

'''''

[[concurrent_flat_set_swap]]
==== 交换

[source,highlight]
----
void swap(concurrent_flat_set& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
           boost::allocator_traits<Allocator>::propagate_on_container_swap::value);
----

交换容器与参数对象的内容。

若 `Allocator::propagate_on_container_swap`已定义且
`Allocator::propagate_on_container_swap::value` 为
`true`，则交换容器的分配器；否则，在分配器不相等的情况下进行交换将导致未定义行为。

[cols=",",]
|===
|抛出： |除非交换操作导致 `key_equal` 或 `hasher`
抛出异常，否则本操作不会抛出任何异常。

|并发性： |阻塞于 `*this` 和 `other`。
|===

'''''

[[concurrent_flat_set_clear]]
==== 清空

[source,highlight]
----
void clear() noexcept;
----

擦除容器中的所有元素。

[cols=",",]
|===
|后置条件： |`size() == 0`,
`max_load() >= max_load_factor() * bucket_count()`

|并发性： |阻塞于 `*this`。
|===

'''''

[[concurrent_flat_set_merge]]
==== 合并

[source,highlight]
----
template<class H2, class P2>
  size_type merge(concurrent_flat_set<Key, H2, P2, Allocator>& source);
template<class H2, class P2>
  size_type merge(concurrent_flat_set<Key, H2, P2, Allocator>&& source);
----

将 `source` 中键尚未存在于 `*this`
的所有元素移动插入当前容器，并将这些元素从 `source` 中元素。

[cols=",",]
|===
|返回： |插入的元素数量。
|并发性： |阻塞于 `*this` 和 `source`。
|===

'''''

[[concurrent_flat_set_observers]]
=== 观察器

[[concurrent_flat_set_get_allocator]]
==== get_allocator

[source,highlight]
----
allocator_type get_allocator() const noexcept;
----

[cols=",",]
|===
|返回： |返回容器的分配器。
|===

'''''

[[concurrent_flat_set_hash_function]]
==== hash_function

[source,highlight]
----
hasher hash_function() const;
----

[cols=",",]
|===
|返回： |返回容器的哈希函数。
|===

'''''

[[concurrent_flat_set_key_eq]]
==== key_eq

[source,highlight]
----
key_equal key_eq() const;
----

[cols=",",]
|===
|返回： |返回容器的键相等性谓词。
|===

'''''

[[concurrent_flat_set_set_operations]]
=== 集合操作

[[concurrent_flat_set_count]]
==== count

[source,highlight]
----
size_type        count(const key_type& k) const;
template<class K>
  size_type      count(const K& k) const;
----

[width="100%",cols="50%,50%",]
|===
|返回： |返回键等价于 `k` 的元素数量（0 或 1）。

|注意： a|
仅当 `Hash::is_transparent` 与 `Pred::is_transparent`
均为有效的成员类型别名时，`template<class K>`
重载才会参与重载决议。标准库假设 `Hash` 可同时被 `K` 与 `Key`
类型调用，且 `Pred`
为透明的。这支持异构查找，该机制支持异构查找，从而避免实例化 `Key`
类型的开销。 +

在存在并发插入操作的情况下，返回值可能无法准确反映函数执行完成后容器的真实状态。

|===

'''''

[[concurrent_flat_set_contains]]
==== 包含

[source,highlight]
----
bool             contains(const key_type& k) const;
template<class K>
  bool           contains(const K& k) const;
----

[width="100%",cols="50%,50%",]
|===
|返回： |返回布尔值表示容器中是否存在键等于 `k` 的元素。

|注意： a|
仅当 `Hash::is_transparent` 与 `Pred::is_transparent`
均为有效的成员类型别名时，`template<class K>`
重载才会参与重载决议。标准库假设 `Hash` 可同时被 `K` 与 `Key`
类型调用，且 `Pred`
为透明的。这支持异构查找，该机制支持异构查找，从而避免实例化 `Key`
类型的开销。 +

在存在并发插入操作的情况下，返回值可能无法准确反映函数执行完成后容器的真实状态。

|===

'''''

[[concurrent_flat_set_bucket_interface]]
=== 桶接口

[[concurrent_flat_set_bucket_count]]
==== bucket_count

[source,highlight]
----
size_type bucket_count() const noexcept;
----

[cols=",",]
|===
|返回： |返回桶数组的大小。
|===

'''''

[[concurrent_flat_set_hash_policy]]
=== 哈希策略

[[concurrent_flat_set_load_factor]]
==== load_factor

[source,highlight]
----
float load_factor() const noexcept;
----

[cols=",",]
|===
|返回：
|返回`static_cast<float>(size())/static_cast<float>(bucket_count())`的结果，若
`bucket_count() == 0` 则返回 `0`。
|===

'''''

[[concurrent_flat_set_max_load_factor]]
==== max_load_factor

[source,highlight]
----
float max_load_factor() const noexcept;
----

[cols=",",]
|===
|返回： |返回容器的最大负载因子。
|===

'''''

[[concurrent_flat_set_set_max_load_factor]]
==== 设置最大负载因子

[source,highlight]
----
void max_load_factor(float z);
----

[cols=",",]
|===
|效果： |不执行任何功能，因为不允许用户更改此参数。保留此接口是为了与
`boost::unordered_set` 保持兼容性。
|===

'''''

[[concurrent_flat_set_max_load]]
==== max_load

[source,highlight]
----
size_type max_load() const noexcept;
----

[width="100%",cols="50%,50%",]
|===
|返回：
|返回容器在不重哈希的情况下可容纳的最大元素数（假设不再擦除任何元素）。

|注意： a|
在构造、重哈希或清空操作后，容器的最大负载至少为
`max_load_factor() * bucket_count()`。该数值在高负载条件下执行擦除操作时可能减少。 +

在存在并发插入操作的情况下，返回值可能无法准确反映函数执行完成后容器的真实状态。

|===

'''''

[[concurrent_flat_set_rehash]]
==== 重哈希

[source,highlight]
----
void rehash(size_type n);
----

必要时调整桶数组的大小，使其至少包含
`n`个桶，并确保负载因子小于或等于最大负载因子。该操作会根据实际情况扩容或缩容容器的
`bucket_count()`。

当 `size() == 0` 时，`rehash(0)` 将释放底层桶数组。

使指向元素的指针和引用失效，并改变元素的顺序。

[width="100%",cols="50%,50%",]
|===
|抛出：
|若抛出异常（除非异常由容器的哈希函数或比较函数抛出），则该函数不产生任何效果。

|并发性： a|
阻塞于 `*this`。

'''''

|===

[[concurrent_flat_set_reserve]]
==== 保留

[source,highlight]
----
void reserve(size_type n);
----

等价于 `a.rehash(ceil(n / a.max_load_factor()))`。

与 `rehash` 类似，此函数可用于增加或减少容器中的桶数量。

使指向元素的指针和引用失效，并改变元素的顺序。

[cols=",",]
|===
|抛出：
|若抛出异常（除非异常由容器的哈希函数或比较函数抛出），则该函数不产生任何效果。

|并发性： |阻塞于 `*this`。
|===

'''''

[[concurrent_flat_set_statistics]]
=== 统计信息

[[concurrent_flat_set_get_stats]]
==== get_stats

[source,highlight]
----
stats get_stats() const;
----

[cols=",",]
|===
|返回： |容器自创建以来所执行的插入与查找操作的统计描述。

|注意：
|仅当link:reference/stats.html#stats[统计计算]被link:#concurrent_flat_set_boost_unordered_enable_stats[启用]时可用。
|===

'''''

[[concurrent_flat_set_reset_stats]]
==== reset_stats

[source,highlight]
----
void reset_stats() noexcept;
----

[cols=",",]
|===
|效果： |将容器维护的内部统计数据重置为零。

|注意：
|仅当link:reference/stats.html#stats[统计计算]被link:#concurrent_flat_set_boost_unordered_enable_stats[启用]时可用。
|===

'''''

[[concurrent_flat_set_deduction_guides]]
=== 推导指引

如果以下任何一项为真，则推导指引将不参与重载决议：

* 该推导指引包含 `InputIterator`
模板参数，且为此参数推导出的类型不符合输入迭代器的要求。
* 该推导指引包含 `Allocator`
模板参数，且为该参数推导出的类型不符合分配器要求。
* 该推导指引包含 `Hash`
模板参数，且为该参数推导出的是整数类型或符合分配器要求的类型。
* 该推导指引包含 `Pred`
模板参数，且为该参数推导出的是符合分配器要求的类型。

推导指引中的 `size_type` 参数类型，指向由该推导指引所推导容器类型的
`size_type` 成员类型。其默认值与所选构造函数的默认值一致。

[[concurrent_flat_set_iter_value_type]]
==== _iter-value-type_

....
template<class InputIterator>
  using iter-value-type =
    typename std::iterator_traits<InputIterator>::value_type; // 仅用于说明
....

[[concurrent_flat_set_equality_comparisons]]
=== 相等性比较

[[concurrent_flat_set_operator]]
==== operator==

[source,highlight]
----
template<class Key, class Hash, class Pred, class Alloc>
  bool operator==(const concurrent_flat_set<Key, Hash, Pred, Alloc>& x,
                  const concurrent_flat_set<Key, Hash, Pred, Alloc>& y);
----

当且仅当满足以下条件时返回 `true`：`x.size() == y.size()`，且对于 `x`
中的每个元素，`y` 中均存在相同键的元素，且其值相等（使用 `operator==`
比较值类型）。

[cols=",",]
|===
|并发性： |阻塞于 `x` 和 `y`。
|注意： |若两个容器的相等性谓词不等价，则行为未定义。
|===

'''''

[[concurrent_flat_set_operator_2]]
==== operator!=

[source,highlight]
----
template<class Key, class Hash, class Pred, class Alloc>
  bool operator!=(const concurrent_flat_set<Key, Hash, Pred, Alloc>& x,
                  const concurrent_flat_set<Key, Hash, Pred, Alloc>& y);
----

当且仅当满足以下条件时返回 `true`：`x.size() == y.size()`，且对于 `x`
中的每个元素，`y` 中均存在相同键的元素，且其值相等（使用 `operator==`
比较值类型）。

[cols=",",]
|===
|并发性： |阻塞于 `x` 和 `y`。
|注意： |若两个容器的相等性谓词不等价，则行为未定义。
|===

'''''

[[concurrent_flat_set_swap_2]]
=== 交换

[source,highlight]
----
template<class Key, class Hash, class Pred, class Alloc>
  void swap(concurrent_flat_set<Key, Hash, Pred, Alloc>& x,
            concurrent_flat_set<Key, Hash, Pred, Alloc>& y)
    noexcept(noexcept(x.swap(y)));
----

等价于

....
x.swap(y);
....

'''''

[[concurrent_flat_set_erase_if_2]]
=== erase_if

[source,highlight]
----
template<class K, class H, class P, class A, class Predicate>
  typename concurrent_flat_set<K, H, P, A>::size_type
    erase_if(concurrent_flat_set<K, H, P, A>& c, Predicate pred);
----

等价于

....
c.erase_if(pred);
....

[[concurrent_flat_set_serialization]]
=== 序列化

可通过本库提供的 API ，借助
link:../../../../../serialization/index.html[Boost.Serialization]
实现档归档/检索 `concurrent_flat_set`。同时支持常规格式与 XML
格式的归档文件。

[[concurrent_flat_set_saving_an_concurrent_flat_set_to_an_archive]]
==== 将 concurrent_flat_set 保存到归档

将 `concurrent_flat_set` 容器`x` 的所有元素保存到归档（XML
归档）`ar`中。

[cols=",",]
|===
|要求： |`value_type` 必须支持序列化（XML 可序列化），且需兼容
Boost.Serialization 的 `save_construct_data`/`load_construct_data`
协议（该协议由https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]类型自动支持）。

|并发性： |阻塞于 `x`。
|===

'''''

[[concurrent_flat_set_loading_an_concurrent_flat_set_from_an_archive]]
==== 从归档加载 concurrent_flat_set

删除 `concurrent_flat_set` 容器 `x` 中的所有现有元素，并从归档
`ar`（XML格式归档）中读取原始 `concurrent_flat_set` 容器 `other`
保存的元素副本并插入到 `x`。

[cols=",",]
|===
|要求： |`x.key_equal()` 在功能上等价于 `other.key_equal()`。
|并发性： |阻塞于 `x`。
|===

[[footer]]
[[footer-text]]
最后更新于 2025年10月31日 21:33:36 UTC
