[#concurrent_node_set]
== Class Template concurrent_node_set

:idprefix: concurrent_node_set_

`boost::concurrent_node_set` — A node-based hash table that stores unique values and allows for concurrent element insertion, erasure, lookup and access without external synchronization mechanisms.

Even though it acts as a container, `boost::concurrent_node_set` does not model the standard C++ https://en.cppreference.com/w/cpp/named_req/Container[Container^] concept. In particular, iterators and associated operations (`begin`, `end`, etc.) are not provided. Element access is done through user-provided _visitation functions_ that are passed to `concurrent_node_set` operations where they are executed internally in a controlled fashion. Such visitation-based API allows for low-contention concurrent usage scenarios.

The internal data structure of `boost::concurrent_node_set` is similar to that of `boost::unordered_node_set`. Unlike `boost::concurrent_flat_set`, pointer stability and node handling functionalities are provided, at the expense of potentially lower performance.

=== 概要

[listing, subs="+macros,+quotes"]
-----
// #include xref:reference/header_concurrent_node_set.adoc[`<boost/unordered/concurrent_node_set.hpp>`]

namespace boost {
namespace unordered {

  template<class Key,
           class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<Key>>
  class concurrent_node_set {
  public:
    // types
    using key_type             = Key;
    using value_type           = Key;
    using init_type            = Key;
    using hasher               = Hash;
    using key_equal            = Pred;
    using allocator_type       = Allocator;
    using pointer              = typename std::allocator_traits<Allocator>::pointer;
    using const_pointer        = typename std::allocator_traits<Allocator>::const_pointer;
    using reference            = value_type&;
    using const_reference      = const value_type&;
    using size_type            = std::size_t;
    using difference_type      = std::ptrdiff_t;

    using node_type            = _实现定义_;
    using insert_return_type   = _实现定义_;

    using stats                = xref:reference/stats.adoc#stats_stats_type[__stats-type__]; // if statistics are xref:concurrent_node_set_boost_unordered_enable_stats[enabled]

    // constants
    static constexpr size_type xref:#concurrent_node_set_constants[bulk_visit_size] = _implementation-defined_;

    // construct/copy/destroy
    xref:#concurrent_node_set_default_constructor[concurrent_node_set]();
    explicit xref:#concurrent_node_set_bucket_count_constructor[concurrent_node_set](size_type n,
                                 const hasher& hf = hasher(),
                                 const key_equal& eql = key_equal(),
                                 const allocator_type& a = allocator_type());
    template<class InputIterator>
      xref:#concurrent_node_set_iterator_range_constructor[concurrent_node_set](InputIterator f, InputIterator l,
                          size_type n = _implementation-defined_,
                          const hasher& hf = hasher(),
                          const key_equal& eql = key_equal(),
                          const allocator_type& a = allocator_type());
    xref:#concurrent_node_set_copy_constructor[concurrent_node_set](const concurrent_node_set& other);
    xref:#concurrent_node_set_move_constructor[concurrent_node_set](concurrent_node_set&& other);
    template<class InputIterator>
      xref:#concurrent_node_set_iterator_range_constructor_with_allocator[concurrent_node_set](InputIterator f, InputIterator l,const allocator_type& a);
    explicit xref:#concurrent_node_set_allocator_constructor[concurrent_node_set](const Allocator& a);
    xref:#concurrent_node_set_copy_constructor_with_allocator[concurrent_node_set](const concurrent_node_set& other, const Allocator& a);
    xref:#concurrent_node_set_move_constructor_with_allocator[concurrent_node_set](concurrent_node_set&& other, const Allocator& a);
    xref:#concurrent_node_set_move_constructor_from_unordered_node_set[concurrent_node_set](unordered_node_set<Key, Hash, Pred, Allocator>&& other);
    xref:#concurrent_node_set_initializer_list_constructor[concurrent_node_set](std::initializer_list<value_type> il,
                        size_type n = _implementation-defined_
                        const hasher& hf = hasher(),
                        const key_equal& eql = key_equal(),
                        const allocator_type& a = allocator_type());
    xref:#concurrent_node_set_bucket_count_constructor_with_allocator[concurrent_node_set](size_type n, const allocator_type& a);
    xref:#concurrent_node_set_bucket_count_constructor_with_hasher_and_allocator[concurrent_node_set](size_type n, const hasher& hf, const allocator_type& a);
    template<class InputIterator>
      xref:#concurrent_node_set_iterator_range_constructor_with_bucket_count_and_allocator[concurrent_node_set](InputIterator f, InputIterator l, size_type n,
                          const allocator_type& a);
    template<class InputIterator>
      xref:#concurrent_node_set_iterator_range_constructor_with_bucket_count_and_hasher[concurrent_node_set](InputIterator f, InputIterator l, size_type n, const hasher& hf,
                          const allocator_type& a);
    xref:#concurrent_node_set_initializer_list_constructor_with_allocator[concurrent_node_set](std::initializer_list<value_type> il, const allocator_type& a);
    xref:#concurrent_node_set_initializer_list_constructor_with_bucket_count_and_allocator[concurrent_node_set](std::initializer_list<value_type> il, size_type n,
                        const allocator_type& a);
    xref:#concurrent_node_set_initializer_list_constructor_with_bucket_count_and_hasher_and_allocator[concurrent_node_set](std::initializer_list<value_type> il, size_type n, const hasher& hf,
                        const allocator_type& a);
    xref:#concurrent_node_set_destructor[~concurrent_node_set]();
    concurrent_node_set& xref:#concurrent_node_set_copy_assignment[operator++=++](const concurrent_node_set& other);
    concurrent_node_set& xref:#concurrent_node_set_move_assignment[operator++=++](concurrent_node_set&& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
              boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value);
    concurrent_node_set& xref:#concurrent_node_set_initializer_list_assignment[operator++=++](std::initializer_list<value_type>);
    allocator_type xref:#concurrent_node_set_get_allocator[get_allocator]() const noexcept;


    // visitation
    template<class F> size_t xref:#concurrent_node_set_cvisit[visit](const key_type& k, F f);
    template<class F> size_t xref:#concurrent_node_set_cvisit[visit](const key_type& k, F f) const;
    template<class F> size_t xref:#concurrent_node_set_cvisit[cvisit](const key_type& k, F f) const;
    template<class K, class F> size_t xref:#concurrent_node_set_cvisit[visit](const K& k, F f);
    template<class K, class F> size_t xref:#concurrent_node_set_cvisit[visit](const K& k, F f) const;
    template<class K, class F> size_t xref:#concurrent_node_set_cvisit[cvisit](const K& k, F f) const;

    template<class FwdIterator, class F>
      size_t xref:concurrent_node_set_bulk_visit[visit](FwdIterator first, FwdIterator last, F f);
    template<class FwdIterator, class F>
      size_t xref:concurrent_node_set_bulk_visit[visit](FwdIterator first, FwdIterator last, F f) const;
    template<class FwdIterator, class F>
      size_t xref:concurrent_node_set_bulk_visit[cvisit](FwdIterator first, FwdIterator last, F f) const;

    template<class F> size_t xref:#concurrent_node_set_cvisit_all[visit_all](F f);
    template<class F> size_t xref:#concurrent_node_set_cvisit_all[visit_all](F f) const;
    template<class F> size_t xref:#concurrent_node_set_cvisit_all[cvisit_all](F f) const;
    template<class ExecutionPolicy, class F>
      void xref:#concurrent_node_set_parallel_cvisit_all[visit_all](ExecutionPolicy&& policy, F f);
    template<class ExecutionPolicy, class F>
      void xref:#concurrent_node_set_parallel_cvisit_all[visit_all](ExecutionPolicy&& policy, F f) const;
    template<class ExecutionPolicy, class F>
      void xref:#concurrent_node_set_parallel_cvisit_all[cvisit_all](ExecutionPolicy&& policy, F f) const;

    template<class F> bool xref:#concurrent_node_set_cvisit_while[visit_while](F f);
    template<class F> bool xref:#concurrent_node_set_cvisit_while[visit_while](F f) const;
    template<class F> bool xref:#concurrent_node_set_cvisit_while[cvisit_while](F f) const;
    template<class ExecutionPolicy, class F>
      bool xref:#concurrent_node_set_parallel_cvisit_while[visit_while](ExecutionPolicy&& policy, F f);
    template<class ExecutionPolicy, class F>
      bool xref:#concurrent_node_set_parallel_cvisit_while[visit_while](ExecutionPolicy&& policy, F f) const;
    template<class ExecutionPolicy, class F>
      bool xref:#concurrent_node_set_parallel_cvisit_while[cvisit_while](ExecutionPolicy&& policy, F f) const;

    // capacity
    ++[[nodiscard]]++ bool xref:#concurrent_node_set_empty[empty]() const noexcept;
    size_type xref:#concurrent_node_set_size[size]() const noexcept;
    size_type xref:#concurrent_node_set_max_size[max_size]() const noexcept;

    // modifiers
    template<class... Args> bool xref:#concurrent_node_set_emplace[emplace](Args&&... args);
    bool xref:#concurrent_node_set_copy_insert[insert](const value_type& obj);
    bool xref:#concurrent_node_set_move_insert[insert](value_type&& obj);
    template<class K> bool xref:#concurrent_node_set_transparent_insert[insert](K&& k);
    template<class InputIterator> size_type xref:#concurrent_node_set_insert_iterator_range[insert](InputIterator first, InputIterator last);
    size_type xref:#concurrent_node_set_insert_initializer_list[insert](std::initializer_list<value_type> il);
    insert_return_type xref:#concurrent_node_set_insert_node[insert](node_type&& nh);

    template<class... Args, class F> bool xref:#concurrent_node_set_emplace_or_cvisit[emplace_or_visit](Args&&... args, F&& f);
    template<class... Args, class F> bool xref:#concurrent_node_set_emplace_or_cvisit[emplace_or_cvisit](Args&&... args, F&& f);
    template<class F> bool xref:#concurrent_node_set_copy_insert_or_cvisit[insert_or_visit](const value_type& obj, F f);
    template<class F> bool xref:#concurrent_node_set_copy_insert_or_cvisit[insert_or_cvisit](const value_type& obj, F f);
    template<class F> bool xref:#concurrent_node_set_move_insert_or_cvisit[insert_or_visit](value_type&& obj, F f);
    template<class F> bool xref:#concurrent_node_set_move_insert_or_cvisit[insert_or_cvisit](value_type&& obj, F f);
    template<class K, class F> bool xref:#concurrent_node_set_transparent_insert_or_cvisit[insert_or_visit](K&& k, F f);
    template<class K, class F> bool xref:#concurrent_node_set_transparent_insert_or_cvisit[insert_or_cvisit](K&& k, F f);
    template<class InputIterator,class F>
      size_type xref:#concurrent_node_set_insert_iterator_range_or_visit[insert_or_visit](InputIterator first, InputIterator last, F f);
    template<class InputIterator,class F>
      size_type xref:#concurrent_node_set_insert_iterator_range_or_visit[insert_or_cvisit](InputIterator first, InputIterator last, F f);
    template<class F> size_type xref:#concurrent_node_set_insert_initializer_list_or_visit[insert_or_visit](std::initializer_list<value_type> il, F f);
    template<class F> size_type xref:#concurrent_node_set_insert_initializer_list_or_visit[insert_or_cvisit](std::initializer_list<value_type> il, F f);
    template<class F> insert_return_type xref:#concurrent_node_set_insert_node_or_visit[insert_or_visit](node_type&& nh, F f);
    template<class F> insert_return_type xref:#concurrent_node_set_insert_node_or_visit[insert_or_cvisit](node_type&& nh, F f);

    template<class... Args, class F1, class F2>
      bool xref:#concurrent_node_set_emplace_and_cvisit[emplace_and_visit](Args&&... args, F1&& f1, F2&& f2);
    template<class... Args, class F1, class F2>
      bool xref:#concurrent_node_set_emplace_and_cvisit[emplace_and_cvisit](Args&&... args, F1&& f1, F2&& f2);
    template<class F1, class F2> bool xref:#concurrent_node_set_copy_insert_and_cvisit[insert_and_visit](const value_type& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool xref:#concurrent_node_set_copy_insert_and_cvisit[insert_and_cvisit](const value_type& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool xref:#concurrent_node_set_move_insert_and_cvisit[insert_and_visit](value_type&& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool xref:#concurrent_node_set_move_insert_and_cvisit[insert_and_cvisit](value_type&& obj, F1 f1, F2 f2);
    template<class K, class F1, class F2> bool xref:#concurrent_node_set_transparent_insert_and_cvisit[insert_and_visit](K&& k, F1 f1, F2 f2);
    template<class K, class F1, class F2> bool xref:#concurrent_node_set_transparent_insert_and_cvisit[insert_and_cvisit](K&& k, F1 f1, F2 f2);
    template<class InputIterator,class F1, class F2>
      size_type xref:#concurrent_node_set_insert_iterator_range_and_visit[insert_and_visit](InputIterator first, InputIterator last, F1 f1, F2 f2);
    template<class InputIterator,class F1, class F2>
      size_type xref:#concurrent_node_set_insert_iterator_range_and_visit[insert_and_cvisit](InputIterator first, InputIterator last, F1 f1, F2 f2);
    template<class F1, class F2>
      size_type xref:#concurrent_node_set_insert_initializer_list_and_visit[insert_and_visit](std::initializer_list<value_type> il, F1 f1, F2 f2);
    template<class F1, class F2>
      size_type xref:#concurrent_node_set_insert_initializer_list_and_visit[insert_and_cvisit](std::initializer_list<value_type> il, F1 f1, F2 f2);
    template<class F1, class F2>
      insert_return_type xref:#concurrent_node_set_insert_node_and_visit[insert_and_visit](node_type&& nh, F1 f1, F2 f2);
    template<class F1, class F2>
      insert_return_type xref:#concurrent_node_set_insert_node_and_visit[insert_and_cvisit](node_type&& nh, F1 f1, F2 f2);

    size_type xref:#concurrent_node_set_erase[erase](const key_type& k);
    template<class K> size_type xref:#concurrent_node_set_erase[erase](const K& k);

    template<class F> size_type xref:#concurrent_node_set_erase_if_by_key[erase_if](const key_type& k, F f);
    template<class K, class F> size_type xref:#concurrent_node_set_erase_if_by_key[erase_if](const K& k, F f);
    template<class F> size_type xref:#concurrent_node_set_erase_if[erase_if](F f);
    template<class ExecutionPolicy, class  F> void xref:#concurrent_node_set_parallel_erase_if[erase_if](ExecutionPolicy&& policy, F f);

    void      xref:#concurrent_node_set_swap[swap](concurrent_node_set& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
               boost::allocator_traits<Allocator>::propagate_on_container_swap::value);

    node_type xref:#concurrent_node_set_extract[extract](const key_type& k);
    template<class K> node_type xref:#concurrent_node_set_extract[extract](const K& k);

    template<class F> node_type xref:#concurrent_node_set_extract_if[extract_if](const key_type& k, F f);
    template<class K, class F> node_type xref:#concurrent_node_set_extract[extract_if](const K& k, F f);

    void      xref:#concurrent_node_set_clear[clear]() noexcept;

    template<class H2, class P2>
      size_type xref:#concurrent_node_set_merge[merge](concurrent_node_set<Key, H2, P2, Allocator>& source);
    template<class H2, class P2>
      size_type xref:#concurrent_node_set_merge[merge](concurrent_node_set<Key, H2, P2, Allocator>&& source);

    // observers
    hasher xref:#concurrent_node_set_hash_function[hash_function]() const;
    key_equal xref:#concurrent_node_set_key_eq[key_eq]() const;

    // set operations
    size_type        xref:#concurrent_node_set_count[count](const key_type& k) const;
    template<class K>
      size_type      xref:#concurrent_node_set_count[count](const K& k) const;
    bool             xref:#concurrent_node_set_contains[contains](const key_type& k) const;
    template<class K>
      bool           xref:#concurrent_node_set_contains[contains](const K& k) const;

    // bucket interface
    size_type xref:#concurrent_node_set_bucket_count[bucket_count]() const noexcept;

    // hash policy
    float xref:#concurrent_node_set_load_factor[load_factor]() const noexcept;
    float xref:#concurrent_node_set_max_load_factor[max_load_factor]() const noexcept;
    void xref:#concurrent_node_set_set_max_load_factor[max_load_factor](float z);
    size_type xref:#concurrent_node_set_max_load[max_load]() const noexcept;
    void xref:#concurrent_node_set_rehash[rehash](size_type n);
    void xref:#concurrent_node_set_reserve[reserve](size_type n);

    // statistics (if xref:concurrent_node_set_boost_unordered_enable_stats[enabled])
    stats xref:#concurrent_node_set_get_stats[get_stats]() const;
    void xref:#concurrent_node_set_reset_stats[reset_stats]() noexcept;
  };

  // Deduction Guides
  template<class InputIterator,
           class Hash = boost::hash<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>>,
           class Pred = std::equal_to<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>>,
           class Allocator = std::allocator<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>>>
    concurrent_node_set(InputIterator, InputIterator, typename xref:#concurrent_node_set_deduction_guides[__see below__]::size_type = xref:#concurrent_node_set_deduction_guides[__see below__],
                        Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> concurrent_node_set<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>, Hash, Pred, Allocator>;

  template<class T, class Hash = boost::hash<T>, class Pred = std::equal_to<T>,
           class Allocator = std::allocator<T>>
    concurrent_node_set(std::initializer_list<T>, typename xref:#concurrent_node_set_deduction_guides[__see below__]::size_type = xref:#concurrent_node_set_deduction_guides[__see below__],
                        Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> concurrent_node_set<T, Hash, Pred, Allocator>;

  template<class InputIterator, class Allocator>
    concurrent_node_set(InputIterator, InputIterator, typename xref:#concurrent_node_set_deduction_guides[__see below__]::size_type, Allocator)
      -> concurrent_node_set<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>,
                             boost::hash<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>>,
                             std::equal_to<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Allocator>
    concurrent_node_set(InputIterator, InputIterator, Allocator)
      -> concurrent_node_set<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>,
                             boost::hash<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>>,
                             std::equal_to<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Hash, class Allocator>
    concurrent_node_set(InputIterator, InputIterator, typename xref:#concurrent_node_set_deduction_guides[__see below__]::size_type, Hash,
                        Allocator)
      -> concurrent_node_set<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>, Hash,
                             std::equal_to<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>>, Allocator>;

  template<class T, class Allocator>
    concurrent_node_set(std::initializer_list<T>, typename xref:#concurrent_node_set_deduction_guides[__see below__]::size_type, Allocator)
      -> concurrent_node_set<T, boost::hash<T>, std::equal_to<T>, Allocator>;

  template<class T, class Allocator>
    concurrent_node_set(std::initializer_list<T>, Allocator)
      -> concurrent_node_set<T, boost::hash<T>, std::equal_to<T>, Allocator>;

  template<class T, class Hash, class Allocator>
    concurrent_node_set(std::initializer_list<T>, typename xref:#concurrent_node_set_deduction_guides[__see below__]::size_type, Hash, Allocator)
      -> concurrent_node_set<T, Hash, std::equal_to<T>, Allocator>;

} // namespace unordered
} // namespace boost
-----

---

=== 描述

*模板参数*

[cols="1,1"]
|===

|_键类型（Key）_
|`Key` must be https://en.cppreference.com/w/cpp/named_req/MoveInsertable[MoveInsertable^] into the container
and https://en.cppreference.com/w/cpp/named_req/Erasable[Erasable^] from the container.

|_Hash_
|一个一元函数对象类型，用作 `Key` 的哈希函数。它接受一个类型为 `Key` 的参数，并返回一个类型为 `std::size_t` 的值。

|_Pred_
|一个二元函数对象，用于在类型为 `Key` 的值上诱导等价关系。它接受两个类型为 `Key` 的参数，并返回一个类型为 `bool` 的值。

|_Allocator_
|An allocator whose value type is the same as the table's value type.
`std::allocator_traits<Allocator>::pointer` and `std::allocator_traits<Allocator>::const_pointer`
must be convertible to/from `value_type*` and `const value_type*`, respectively.

|===

表的元素节点保存在内部的_桶数组_中。节点根据其元素的哈希码插入到确定的桶中，但如果桶已被占用（发生_冲突_），则使用原始位置附近的可用桶。

桶数组的大小可通过调用 `insert`/`emplace` 自动增加，或通过调用 `rehash`/`reserve` 来调整。表的_负载因子_（元素数量除以桶数量）永远不会超过 `max_load_factor()`，除非在较小规模时实现可能允许更高的负载。

如果 `link:../../../../../container_hash/doc/html/hash.html#ref_hash_is_avalanchinghash[hash_is_avalanching]<Hash>::value` 为 `true`，则直接使用哈希函数；否则，会添加一个位混合后处理阶段以提高哈希质量，但会带来额外的计算开销。

---

=== 并发要求与保证

要求在同一个 `Hash` 或 `Pred` 的常量实例上并发调用 `operator()` 不会引入数据竞争。对于 `Alloc`（即 `Allocator` 或从 `Allocator` 重新绑定的任何分配器类型），要求在同一个 `Alloc` 实例 `al` 上并发调用以下操作不会引入数据竞争：

* 从 `al` 复制构造一个从 `Alloc` 重新绑定的分配器
* `std::allocator_traits<Alloc>::allocate`
* `std::allocator_traits<Alloc>::deallocate`
* `std::allocator_traits<Alloc>::construct`
* `std::allocator_traits<Alloc>::destroy`

通常，如果这些类型是无状态的，或者操作仅涉及对内部数据成员的常量访问，则满足对 `Hash`、`Pred` 和 `Allocator` 的这些要求。

With the exception of destruction, concurrent invocations of any operation on the same instance of a `concurrent_node_set` do not introduce data races — that is, they are thread-safe.

If an operation *op* is explicitly designated as _blocking on_ `x`, where `x` is an instance of a `boost::concurrent_node_set`, prior blocking operations on `x` synchronize with *op*. So, blocking operations on the same `concurrent_node_set` execute sequentially in a multithreaded scenario.

如果一个操作仅在发生内部重哈希时阻塞于 `x`，则称该操作_阻塞于 ``__x__`` 的重哈希_。

When executed internally by a `boost::concurrent_node_set`, the following operations by a user-provided visitation function on the element passed do not introduce data races:

* 对元素的读取访问。
* 对元素的不可变修改。
* 对元素的可变修改：
  ** 在接收两个访问函数的容器函数中，始终针对第一个函数。
  ** 在名称不包含 `cvisit` 的非常量容器函数中，针对最后一个（或唯一）访问函数。

Any `boost::concurrent_node_set operation` that inserts or modifies an element `e` synchronizes with the internal invocation of a visitation function on `e`.

Visitation functions executed by a `boost::concurrent_node_set` `x` are not allowed to invoke any operation on `x`; invoking operations on a different `boost::concurrent_node_set` instance `y` is allowed only if concurrent outstanding operations on `y` do not access `x` directly or indirectly.

---

=== 配置宏

==== `BOOST_UNORDERED_DISABLE_REENTRANCY_CHECK`

在调试版本中（更准确地说，当 link:../../../../../assert/doc/html/assert.html#boost_assert_is_void[`BOOST_ASSERT_IS_VOID`^] 未定义时），__容器重入__（在访问 `m` 元素的函数内部非法调用 `m` 的操作）会被检测并通过 `BOOST_ASSERT_MSG` 发出信号。当运行时速度成为关注点时，可通过全局定义此宏来禁用该功能。

---

==== `BOOST_UNORDERED_ENABLE_STATS`

全局定义此宏以启用表的 xref:reference/stats.adoc#stats[统计计算]。请注意，此选项会降低许多操作的总体性能。

---

=== 类型定义

[source, c++, subs=+quotes]
----
typedef _实现定义_ node_type;
----

一个用于保存提取的表元素的类，建模 https://en.cppreference.com/w/cpp/container/node_handle[NodeHandle]。

---

[source, c++, subs=+quotes]
----
typedef _实现定义_ insert_return_type;
----

一个内部类模板的特化：

[source, c++, subs=+quotes]
----
template<class NodeType>
struct _insert_return_type_ // 名称仅用于说明
{
  bool     inserted;
  NodeType node;
};
----

其中 `NodeType` = `node_type`。

---

=== 常量

```cpp

static constexpr size_type bulk_visit_size;

```

Chunk size internally used in xref:concurrent_node_set_bulk_visit[bulk visit] operations.

=== 构造函数

==== 默认构造函数
```c++

concurrent_node_set();

```

使用 `hasher()` 作为哈希函数、`key_equal()` 作为键相等谓词、`allocator_type()` 作为分配器构造一个空表。

[horizontal]
后置条件：;; `size() == 0`
要求：;; 如果使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 必须是 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^] 的。

---

==== 桶数量构造函数
```c++

explicit concurrent_node_set(size_type n,
                             const hasher& hf = hasher(),
                             const key_equal& eql = key_equal(),
                             const allocator_type& a = allocator_type());

```

构造一个至少包含 `n` 个桶的空表，使用 `hf` 作为哈希函数，`eql` 作为键相等谓词，`a` 作为分配器。

[horizontal]
后置条件：;; `size() == 0`
要求：;; 如果使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 必须是 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^] 的。

---

==== 迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  concurrent_node_set(InputIterator f, InputIterator l,
                      size_type n = _implementation-defined_,
                      const hasher& hf = hasher(),
                      const key_equal& eql = key_equal(),
                      const allocator_type& a = allocator_type());
----

构造一个至少包含 `n` 个桶的空表，使用 `hf` 作为哈希函数，`eql` 作为键相等谓词，`a` 作为分配器，并将 `[f, l)` 范围内的元素插入其中。

[horizontal]
要求：;; 如果使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 必须是 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^] 的。

---

==== 复制构造函数
```c++

concurrent_node_set(concurrent_node_set const& other);

```

复制构造函数。复制包含的元素、哈希函数、谓词和分配器。

如果 `Allocator::select_on_container_copy_construction` 存在且签名正确，则分配器将根据其结果构造。

[horizontal]
要求：;; `value_type` 必须是可复制构造的
并发性：;; 阻塞于 `other`。

---

==== 移动构造函数
```c++

concurrent_node_set(concurrent_node_set&& other);

```

The move constructor. The internal bucket array of `other` is transferred directly to the new table. The hash function, predicate and allocator are moved-constructed from `other`. If statistics are xref:concurrent_node_set_boost_unordered_enable_stats[enabled], transfers the internal statistical information from `other` and calls `other.reset_stats()`.

[horizontal]
并发性：;; 阻塞于 `other`。

---

==== 带分配器的迭代器范围构造函数
```c++

template<class InputIterator>
  concurrent_node_set(InputIterator f, InputIterator l, const allocator_type& a);

```

使用 `a` 作为分配器构造一个空表，使用默认的哈希函数和键相等谓词，并将 `[f, l)` 范围内的元素插入其中。

[horizontal]
要求：;; `hasher` 和 `key_equal` 必须是 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^] 的。

---

==== 分配器构造函数
```c++

explicit concurrent_node_set(Allocator const& a);

```

使用分配器 `a` 构造一个空表。

---

==== 带分配器的复制构造函数
```c++

concurrent_node_set(concurrent_node_set const& other, Allocator const& a);

```

构造一个表，复制 ``other`` 包含的元素、哈希函数和谓词，但使用分配器 `a`。

[horizontal]
并发性：;; 阻塞于 `other`。

---

==== 带分配器的移动构造函数
```c++

concurrent_node_set(concurrent_node_set&& other, Allocator const& a);

```

If `a == other.get_allocator()`, the elements of `other` are transferred directly to the new table; otherwise, elements are moved-constructed from those of `other`. The hash function and predicate are moved-constructed from `other`, and the allocator is copy-constructed from `a`. If statistics are xref:concurrent_node_set_boost_unordered_enable_stats[enabled], transfers the internal statistical information from `other` iff `a == other.get_allocator()`, and always calls `other.reset_stats()`.

[horizontal]
并发性：;; 阻塞于 `other`。

---

==== Move Constructor from unordered_node_set

```c++

concurrent_node_set(unordered_node_set<Key, Hash, Pred, Allocator>&& other);

```

Move construction from a xref:#unordered_node_set[`unordered_node_set`]. The internal bucket array of `other` is transferred directly to the new container. The hash function, predicate and allocator are moved-constructed from `other`. If statistics are xref:concurrent_node_set_boost_unordered_enable_stats[enabled], transfers the internal statistical information from `other` and calls `other.reset_stats()`.

[horizontal]
复杂度：;; O(`bucket_count()`)

---

==== 初始化列表构造函数
[source, c++, subs="+quotes"]
----
concurrent_node_set(std::initializer_list<value_type> il,
                    size_type n = _implementation-defined_
                    const hasher& hf = hasher(),
                    const key_equal& eql = key_equal(),
                    const allocator_type& a = allocator_type());
----

构造一个至少包含 `n` 个桶的空表，使用 `hf` 作为哈希函数，`eql` 作为键相等谓词，`a` 作为分配器，并将 `il` 中的元素插入其中。

[horizontal]
要求：;; 如果使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 必须是 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^] 的。

---

==== 带分配器的桶数量构造函数
```c++

concurrent_node_set(size_type n, allocator_type const& a);

```

构造一个至少包含 `n` 个桶的空表，使用 `hf` 作为哈希函数（默认哈希函数）、默认键相等谓词和 `a` 作为分配器。

[horizontal]
后置条件：;; `size() == 0`
要求：;; `hasher` 和 `key_equal` 必须是 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^] 的。

---

==== 带哈希函数和分配器的桶数量构造函数
```c++

concurrent_node_set(size_type n, hasher const& hf, allocator_type const& a);

```

构造一个至少包含 `n` 个桶的空表，使用 `hf` 作为哈希函数、默认键相等谓词和 `a` 作为分配器。

[horizontal]
后置条件：;; `size() == 0`
要求：;; `key_equal` 必须是 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^] 的。

---

==== 带桶数量和分配器的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  concurrent_node_set(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空表，使用 `a` 作为分配器、默认哈希函数和键相等谓词，并将 `[f, l)` 范围内的元素插入其中。

[horizontal]
要求：;; `hasher` 和 `key_equal` 必须是 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^] 的。

---

==== 带桶数量和哈希函数的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
    template<class InputIterator>
      concurrent_node_set(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                          const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空表，使用 `hf` 作为哈希函数、`a` 作为分配器、默认键相等谓词，并将 `[f, l)` 范围内的元素插入其中。

[horizontal]
要求：;; `key_equal` 必须是 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^] 的。

---

==== 带分配器的初始化列表构造函数

```c++

concurrent_node_set(std::initializer_list<value_type> il, const allocator_type& a);

```

使用 `a` 作为分配器、默认哈希函数和键相等谓词构造一个空表，并将 `il` 中的元素插入其中。

[horizontal]
要求：;; `hasher` 和 `key_equal` 必须是 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^] 的。

---

==== 带桶数量和分配器的初始化列表构造函数

```c++

concurrent_node_set(std::initializer_list<value_type> il, size_type n, const allocator_type& a);

```

构造一个至少包含 `n` 个桶的空表，使用 `a` 作为分配器、默认哈希函数和键相等谓词，并将 `il` 中的元素插入其中。

[horizontal]
要求：;; `hasher` 和 `key_equal` 必须是 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^] 的。

---

==== 带桶数量、哈希函数和分配器的初始化列表构造函数

```c++

concurrent_node_set(std::initializer_list<value_type> il, size_type n, const hasher& hf,
                    const allocator_type& a);

```

构造一个至少包含 `n` 个桶的空表，使用 `hf` 作为哈希函数、`a` 作为分配器、默认键相等谓词，并将 `il` 中的元素插入其中。

[horizontal]
要求：;; `key_equal` 必须是 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^] 的。

---

=== 析构函数

```c++

~concurrent_node_set();

```

[horizontal]
注意：;; 析构函数会应用于每个元素，并释放所有内存

---

=== 赋值操作

==== 复制赋值

```c++

concurrent_node_set& operator=(concurrent_node_set const& other);

```

赋值运算符。销毁先前存在的元素，从 `other` 复制赋值哈希函数和谓词，如果 `Alloc::propagate_on_container_copy_assignment` 存在且 `Alloc::propagate_on_container_copy_assignment::value` 为 `true`，则从 `other` 复制赋值分配器，最后插入 `other` 元素的副本。

[horizontal]
要求：;; `value_type` 必须是 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入^] 的
并发性：;; 阻塞于 `*this` 和 `other`。

---

==== 移动赋值
```c++

concurrent_node_set& operator=(concurrent_node_set&& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
           boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value);

```
The move assignment operator. Destroys previously existing elements, swaps the hash function and predicate from `other`,
and move-assigns the allocator from `other` if `Alloc::propagate_on_container_move_assignment` exists and `Alloc::propagate_on_container_move_assignment::value` is `true`.
If at this point the allocator is equal to `other.get_allocator()`, the internal bucket array of `other` is transferred directly to `*this`;
otherwise, inserts move-constructed copies of the elements of `other`.
If statistics are xref:concurrent_node_set_boost_unordered_enable_stats[enabled],
transfers the internal statistical information from `other` iff the final allocator is equal to `other.get_allocator()`,
and always calls `other.reset_stats()`.

[horizontal]
并发性：;; 阻塞于 `*this` 和 `other`。

---

==== 初始化列表赋值
```c++

concurrent_node_set& operator=(std::initializer_list<value_type> il);

```

从初始化列表中的值赋值。销毁所有先前存在的元素。

[horizontal]
要求：;; `value_type` 必须是 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入^] 的
并发性：;; 阻塞于 `*this`。

---

=== 访问操作

==== [c]visit（[常]访问）

```c++

template<class F> size_t visit(const key_type& k, F f); template<class F> size_t visit(const key_type& k, F f) const; template<class F> size_t cvisit(const key_type& k, F f) const; template<class K, class F> size_t visit(const K& k, F f); template<class K, class F> size_t visit(const K& k, F f) const; template<class K, class F> size_t cvisit(const K& k, F f) const;

```

If an element `x` exists with key equivalent to `k`, invokes `f` with a const reference to `x`.

[horizontal]
返回：;; 被访问的元素数量（0 或 1）。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K, class F>` 重载才会参与重载解析。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== 批量访问（Bulk visit）

```c++

template<class FwdIterator, class F>
  size_t visit(FwdIterator first, FwdIterator last, F f);
template<class FwdIterator, class F>
  size_t visit(FwdIterator first, FwdIterator last, F f) const;
template<class FwdIterator, class F>
  size_t cvisit(FwdIterator first, FwdIterator last, F f) const;

```

For each element `k` in the range [`first`, `last`), if there is an element `x` in the container with key equivalent to `k`, invokes `f` with a const reference to `x`.

Although functionally equivalent to individually invoking xref:concurrent_node_set_cvisit[`[c\]visit`] for each key, bulk visitation performs generally faster due to internal streamlining optimizations. It is advisable that `std::distance(first,last)` be at least xref:#concurrent_node_set_constants[`bulk_visit_size`] to enjoy a performance gain: beyond this size, performance is not expected to increase further.

[horizontal]
要求：;; `FwdIterator` 是 https://en.cppreference.com/w/cpp/named_req/ForwardIterator[前向迭代器^]（C++11 至 C++17），或满足 https://en.cppreference.com/w/cpp/iterator/forward_iterator[std::forward_iterator^]（C++20 及更高版本）。对于 `K` = `std::iterator_traits<FwdIterator>::value_type`，`K` 要么是 `key_type`，要么 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义。在后一种情况下，库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。
返回：;; 被访问的元素数量。

---

==== [c]visit_all（[常]访问全部）

```c++

template<class F> size_t visit_all(F f); template<class F> size_t visit_all(F f) const; template<class F> size_t cvisit_all(F f) const;

```

Successively invokes `f` with const references to each of the elements in the table.

[horizontal]
返回：;; 被访问的元素数量。

---

==== 并行 [c]visit_all（并行[常]访问全部）

```c++

template<class ExecutionPolicy, class F> void visit_all(ExecutionPolicy&& policy, F f); template<class ExecutionPolicy, class F> void visit_all(ExecutionPolicy&& policy, F f) const; template<class ExecutionPolicy, class F> void cvisit_all(ExecutionPolicy&& policy, F f) const;

```

Invokes `f` with const references to each of the elements in the table. Execution is parallelized according to the semantics of the execution policy specified.

[horizontal]
抛出：;; 根据所用执行策略的异常处理机制，如果在 `f` 内抛出异常，可能调用 `std::terminate`。
注意：;; 仅在支持 C++17 并行算法的编译器中可用。+
+
仅当 `std::is_execution_policy_v<std::remove_cvref_t<ExecutionPolicy>>` 为 `true` 时，这些重载才会参与重载解析。+
+
不允许使用无序执行策略。

---

==== [c]visit_while（[常]条件访问）

```c++

template<class F> bool visit_while(F f); template<class F> bool visit_while(F f) const; template<class F> bool cvisit_while(F f) const;

```

Successively invokes `f` with const references to each of the elements in the table until `f` returns `false` or all the elements are visited.

[horizontal]
返回：;; 如果 `f` 曾返回 `false` 则为 `false`。

---

==== 并行 [c]visit_while（并行[常]条件访问）

```c++

template<class ExecutionPolicy, class F> bool visit_while(ExecutionPolicy&& policy, F f); template<class ExecutionPolicy, class F> bool visit_while(ExecutionPolicy&& policy, F f) const; template<class ExecutionPolicy, class F> bool cvisit_while(ExecutionPolicy&& policy, F f) const;

```

Invokes `f` with const references to each of the elements in the table until `f` returns `false` or all the elements are visited. Execution is parallelized according to the semantics of the execution policy specified.

[horizontal]
返回：;; 如果 `f` 曾返回 `false` 则为 `false`。
抛出：;; 根据所用执行策略的异常处理机制，如果在 `f` 内抛出异常，可能调用 `std::terminate`。
注意：;; 仅在支持 C++17 并行算法的编译器中可用。+
+
仅当 `std::is_execution_policy_v<std::remove_cvref_t<ExecutionPolicy>>` 为 `true` 时，这些重载才会参与重载解析。+
+
不允许使用无序执行策略。+
+
并行化意味着执行不一定会因 `f` 返回 `false` 而立即结束，因此 `f` 可能会被继续调用并返回 `false`。

---

=== 大小与容量

==== empty（判空）

```c++

[[nodiscard]] bool empty() const noexcept;

```

[horizontal]
返回：;; `size() == 0`

---

==== size（大小）

```c++

size_type size() const noexcept;

```

[horizontal]
返回：;; 表中的元素数量。

[horizontal]
注意：;; 在存在并发插入操作的情况下，返回值可能无法准确反映执行后表的实际大小。

---

==== max_size（最大容量）

```c++

size_type max_size() const noexcept;

```

[horizontal]
返回：;; 最大可能表的 `size()`。

---

=== 修改器

==== emplace（原位构造）
```c++

template<class... Args> bool emplace(Args&&... args);

```

当且仅当表中不存在具有等价键的元素时，插入一个由参数 `args` 构造的对象。

[horizontal]
要求：;; `value_type` 必须可从 `args` 构造。
返回：;; 如果插入发生则返回 `true`。
并发性：;; 阻塞于 `*this` 的重哈希。

---

==== 复制插入（Copy Insert）
```c++

bool insert(const value_type& obj);

```

当且仅当表中不存在具有等价键的元素时，插入 `obj`。

[horizontal]
要求：;; `value_type` 必须是 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入^] 的。
返回：;; 如果插入发生则返回 `true`。+
并发性：;; 阻塞于 `*this` 的重哈希。

---

==== 移动插入（Move Insert）
```c++

bool insert(value_type&& obj);

```

当且仅当表中不存在具有等价键的元素时，插入 `obj`。

[horizontal]
要求：;; `value_type` 必须是 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入^] 的。
返回：;; 如果插入发生则返回 `true`。
并发性：;; 阻塞于 `*this` 的重哈希。

---

==== Transparent Insert
```c++

template<class K> bool insert(K&& k);

```

Inserts an element constructed from `std::forward<K>(k)` in the container if and only if there is no element in the container with an equivalent key.

[horizontal]
要求：;; `value_type` is https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible^] from `k`.
返回：;; 如果插入发生则返回 `true`。
并发性：;; 阻塞于 `*this` 的重哈希。
注意：;; This overload only participates in overload resolution if `Hash::is_transparent` and `Pred::is_transparent` are valid member typedefs. The library assumes that `Hash` is callable with both `K` and `Key` and that `Pred` is transparent. This enables heterogeneous lookup which avoids the cost of instantiating an instance of the `Key` type.

---

==== 插入迭代器范围（Insert Iterator Range）
```c++

template<class InputIterator> size_type insert(InputIterator first, InputIterator last);

```

等效于
[listing, subs="+macros,+quotes"]
-----
  while(first != last) this->xref:#concurrent_node_set_emplace[emplace](*first++);
-----

[horizontal]
返回：;; 插入的元素数量。

---

==== 插入初始化列表（Insert Initializer List）
```c++

size_type insert(std::initializer_list<value_type> il);

```

等效于
[listing, subs="+macros,+quotes"]
-----
  this->xref:#concurrent_node_set_insert_iterator_range[insert](il.begin(), il.end());
-----

[horizontal]
返回：;; 插入的元素数量。

---

==== 插入节点（Insert Node）
```c++

insert_return_type insert(node_type&& nh);

```

If `nh` is not empty, inserts the associated element in the table if and only if there is no element in the table with a key equivalent to `nh.value()`. `nh` is empty when the function returns.

[horizontal]
返回：;; 一个从 `inserted` 和 `node` 构造的 `insert_return_type` 对象：+
* 如果 `nh` 为空，则 `inserted` 为 `false` 且 `node` 为空。
* 否则，如果插入发生，则 `inserted` 为 true 且 `node` 为空。
* 如果插入失败，则 `inserted` 为 false 且 `node` 保留 `nh` 的先前值。
抛出：;; 如果由调用 `hasher` 以外的操作引发异常，则函数无效果。
并发性：;; 阻塞于 `*this` 的重哈希。
注意：;; 如果 `nh` 非空且 `nh` 的分配器与容器分配器不相等，则行为未定义。

---

==== emplace_or_[c]visit（原位构造或[常]访问）
```c++

template<class... Args, class F> bool emplace_or_visit(Args&&... args, F&& f); template<class... Args, class F> bool emplace_or_cvisit(Args&&... args, F&& f);

```

Inserts an object, constructed with the arguments `args`, in the table if there is no element in the table with an equivalent key. Otherwise, invokes `f` with a const reference to the equivalent element.

[horizontal]
要求：;; `value_type` 必须可从 `args` 构造。
返回：;; 如果插入发生则返回 `true`。
并发性：;; 阻塞于 `*this` 的重哈希。
注意：;; 该接口仅为说明，因为 C++ 不允许在可变参数包后声明参数 `f`。

---

==== 复制插入或[常]访问（Copy insert_or_[c]visit）
```c++

template<class F> bool insert_or_visit(const value_type& obj, F f); template<class F> bool insert_or_cvisit(const value_type& obj, F f);

```

Inserts `obj` in the table if and only if there is no element in the table with an equivalent key. Otherwise, invokes `f` with a const reference to the equivalent element.

[horizontal]
要求：;; `value_type` 必须是 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入^] 的。
返回：;; 如果插入发生则返回 `true`。+
并发性：;; 阻塞于 `*this` 的重哈希。

---

==== 移动插入或[常]访问（Move insert_or_[c]visit）
```c++

template<class F> bool insert_or_visit(value_type&& obj, F f); template<class F> bool insert_or_cvisit(value_type&& obj, F f);

```

Inserts `obj` in the table if and only if there is no element in the table with an equivalent key. Otherwise, invokes `f` with a const reference to the equivalent element.

[horizontal]
要求：;; `value_type` 必须是 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入^] 的。
返回：;; 如果插入发生则返回 `true`。+
并发性：;; 阻塞于 `*this` 的重哈希。

---

==== Transparent insert_or_[c]visit
```c++

template<class K, class F> bool insert_or_visit(K&& k, F f); template<class K, class F> bool insert_or_cvisit(K&& k, F f);

```

Inserts an element constructed from `std::forward<K>(k)` in the container if and only if there is no element in the container with an equivalent key. Otherwise, invokes `f` with a const reference to the equivalent element.

[horizontal]
要求：;; `value_type` is https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible^] from `k`.
返回：;; 如果插入发生则返回 `true`。
并发性：;; 阻塞于 `*this` 的重哈希。
注意：;; These overloads only participate in overload resolution if `Hash::is_transparent` and `Pred::is_transparent` are valid member typedefs. The library assumes that `Hash` is callable with both `K` and `Key` and that `Pred` is transparent. This enables heterogeneous lookup which avoids the cost of instantiating an instance of the `Key` type.

---

==== 插入迭代器范围或访问（Insert Iterator Range or Visit）
```c++

template<class InputIterator,class F>
    size_type insert_or_visit(InputIterator first, InputIterator last, F f);
template<class InputIterator,class F>
    size_type insert_or_cvisit(InputIterator first, InputIterator last, F f);

```

等效于
[listing, subs="+macros,+quotes"]
-----
  while(first != last) this->xref:#concurrent_node_set_emplace_or_cvisit[emplace_or_[c\]visit](*first++, f);
-----

[horizontal]
返回：;; 插入的元素数量。

---

==== 插入初始化列表或访问（Insert Initializer List or Visit）
```c++

template<class F> size_type insert_or_visit(std::initializer_list<value_type> il, F f); template<class F> size_type insert_or_cvisit(std::initializer_list<value_type> il, F f);

```

等效于
[listing, subs="+macros,+quotes"]
-----
  this->xref:#concurrent_node_set_insert_iterator_range_or_visit[insert_or_[c\]visit](il.begin(), il.end(), std::ref(f));
-----

[horizontal]
返回：;; 插入的元素数量。

---

==== 插入节点或访问（Insert Node or Visit）
```c++

template<class F> insert_return_type insert_or_visit(node_type&& nh, F f); template<class F> insert_return_type insert_or_cvisit(node_type&& nh, F f);

```

If `nh` is empty, does nothing. Otherwise, inserts the associated element in the table if and only if there is no element in the table with a key equivalent to `nh.value()`. Otherwise, invokes `f` with a const reference to the equivalent element.

[horizontal]
返回：;; 一个从 `inserted` 和 `node` 构造的 `insert_return_type` 对象：+
* 如果 `nh` 为空，则 `inserted` 为 `false` 且 `node` 为空。
* 否则，如果插入发生，则 `inserted` 为 true 且 `node` 为空。
* 如果插入失败，则 `inserted` 为 false 且 `node` 保留 `nh` 的先前值。
抛出：;; 如果由调用 `hasher` 或调用 `f` 以外的操作引发异常，则函数无效果。
并发性：;; 阻塞于 `*this` 的重哈希。
注意：;; 如果 `nh` 非空且 `nh` 的分配器与容器分配器不相等，则行为未定义。

---

==== emplace_and_[c]visit（原位构造并[常]访问）
```c++

template<class... Args, class F1, class F2>
  bool emplace_or_visit(Args&&... args, F1&& f1, F2&& f2);
template<class... Args, class F1, class F2>
  bool emplace_or_cvisit(Args&&... args, F1&& f1, F2&& f2);

```

Inserts an object, constructed with the arguments `args`, in the table if there is no element in the table with an equivalent key, and then invokes `f1` with a const reference to the newly created element. Otherwise, invokes `f2` with a const reference to the equivalent element.

[horizontal]
要求：;; `value_type` 必须可从 `args` 构造。
返回：;; 如果插入发生则返回 `true`。
并发性：;; 阻塞于 `*this` 的重哈希。
注意：;; 该接口仅为说明，因为 C++ 不允许在可变参数包后声明参数 `f1` 和 `f2`。

---

==== 复制插入并[常]访问（Copy insert_and_[c]visit）
```c++

template<class F1, class F2> bool insert_and_visit(const value_type& obj, F1 f1, F2 f2); template<class F1, class F2> bool insert_and_cvisit(const value_type& obj, F1 f2, F2 f2);

```

Inserts `obj` in the table if and only if there is no element in the table with an equivalent key, and then invokes `f1` with a const reference to the newly created element. Otherwise, invokes `f` with a const reference to the equivalent element.

[horizontal]
要求：;; `value_type` 必须是 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入^] 的。
返回：;; 如果插入发生则返回 `true`。+
并发性：;; 阻塞于 `*this` 的重哈希。

---

==== 移动插入并[常]访问（Move insert_and_[c]visit）
```c++

template<class F1, class F2> bool insert_and_visit(value_type&& obj, F1 f1, F2 f2); template<class F1, class F2> bool insert_and_cvisit(value_type&& obj, F1 f1, F2 f2);

```

Inserts `obj` in the table if and only if there is no element in the table with an equivalent key, and then invokes `f1` with a const reference to the newly created element. Otherwise, invokes `f2` with a const reference to the equivalent element.

[horizontal]
要求：;; `value_type` 必须是 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入^] 的。
返回：;; 如果插入发生则返回 `true`。+
并发性：;; 阻塞于 `*this` 的重哈希。

---

==== Transparent insert_and_[c]visit
```c++

template<class K, class F1, class F2> bool insert_and_visit(K&& k, F1 f1, F2 f2); template<class K, class F1, class F2> bool insert_and_cvisit(K&& k, F1 f1, F2 f2);

```

Inserts an element constructed from `std::forward<K>(k)` in the container if and only if there is no element in the container with an equivalent key, and then invokes `f1` with a const reference to the newly created element. Otherwise, invokes `f2` with a const reference to the equivalent element.

[horizontal]
要求：;; `value_type` is https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible^] from `k`.
返回：;; 如果插入发生则返回 `true`。
并发性：;; 阻塞于 `*this` 的重哈希。
注意：;; These overloads only participate in overload resolution if `Hash::is_transparent` and `Pred::is_transparent` are valid member typedefs. The library assumes that `Hash` is callable with both `K` and `Key` and that `Pred` is transparent. This enables heterogeneous lookup which avoids the cost of instantiating an instance of the `Key` type.

---

==== 插入迭代器范围并访问（Insert Iterator Range and Visit）
```c++

template<class InputIterator,class F1, class F2>
    size_type insert_and_visit(InputIterator first, InputIterator last, F1 f1, F2 f2);
template<class InputIterator,class F1, class f2>
    size_type insert_and_cvisit(InputIterator first, InputIterator last, F1 f1, F2 f2);

```

等效于
[listing, subs="+macros,+quotes"]
-----
  while(first != last) this->xref:#concurrent_node_set_emplace_and_cvisit[emplace_and_[c\]visit](*first++, f1, f2);
-----

[horizontal]
返回：;; 插入的元素数量。

---

==== 插入初始化列表并访问（Insert Initializer List and Visit）
```c++

template<class F1, class F2>
  size_type insert_and_visit(std::initializer_list<value_type> il, F1 f1, F2 f2);
template<class F1, class F2>
  size_type insert_and_cvisit(std::initializer_list<value_type> il, F1 f1, F2 f2);

```

等效于
[listing, subs="+macros,+quotes"]
-----
  this->xref:#concurrent_node_set_insert_iterator_range_and_visit[insert_and_[c\]visit](il.begin(), il.end(), std::ref(f1), std::ref(f2));
-----

[horizontal]
返回：;; 插入的元素数量。

---

==== 插入节点并访问（Insert Node and Visit）
```c++

template<class F1, class F2>
  insert_return_type insert_and_visit(node_type&& nh, F1 f1, F2 f2);
template<class F1, class F2>
  insert_return_type insert_and_cvisit(node_type&& nh, F1 f1, F2 f2);

```

If `nh` is empty, does nothing. Otherwise, inserts the associated element in the table if and only if there is no element in the table with a key equivalent to `nh.value()`, and then invokes `f1` with a const reference to the newly inserted element. Otherwise, invokes `f2` with a const reference to the equivalent element.

[horizontal]
返回：;; 一个从 `inserted` 和 `node` 构造的 `insert_return_type` 对象：+
* 如果 `nh` 为空，则 `inserted` 为 `false` 且 `node` 为空。
* 否则，如果插入发生，则 `inserted` 为 true 且 `node` 为空。
* 如果插入失败，则 `inserted` 为 false 且 `node` 保留 `nh` 的先前值。
抛出：;; 如果由调用 `hasher` 或调用 `f1` 或 `f2` 以外的操作引发异常，则函数无效果。
并发性：;; 阻塞于 `*this` 的重哈希。
注意：;; 如果 `nh` 非空且 `nh` 的分配器与容器分配器不相等，则行为未定义。

---

==== erase（擦除）
```c++

size_type erase(const key_type& k); template<class K> size_type erase(const K& k);

```

如果存在键等于 `k` 的元素，则擦除该元素。

[horizontal]
返回：;; 擦除的元素数量（0 或 1）。
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才抛出异常。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才会参与重载解析。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== 按键条件擦除（erase_if by Key）
```c++

template<class F> size_type erase_if(const key_type& k, F f); template<class K, class F> size_type erase_if(const K& k, F f);

```

如果存在键等于 `k` 的元素 `x` 且 `f(x)` 为 `true`，则擦除该元素。

[horizontal]
返回：;; 擦除的元素数量（0 或 1）。
抛出：;; 仅当 `hasher`、`key_equal` 或 `f` 抛出异常时才抛出异常。
注意：;; 仅当 `std::is_execution_policy_v<std::remove_cvref_t<ExecutionPolicy>>` 为 `false` 时，`template<class K, class F>` 重载才会参与重载解析。+
+
仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K, class F>` 重载才会参与重载解析。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== 条件擦除（erase_if）
```c++

template<class F> size_type erase_if(F f);

```

Successively invokes `f` with references to each of the elements in the table, and erases those for which `f` returns `true`.

[horizontal]
返回：;; 擦除的元素数量。
抛出：;; 仅当 `f` 抛出异常时才抛出异常。

---

==== 并行条件擦除（Parallel erase_if）
```c++

template<class ExecutionPolicy, class F> void erase_if(ExecutionPolicy&& policy, F f);

```

Invokes `f` with references to each of the elements in the table, and erases those for which `f` returns `true`. Execution is parallelized according to the semantics of the execution policy specified.

[horizontal]
抛出：;; 根据所用执行策略的异常处理机制，如果在 `f` 内抛出异常，可能调用 `std::terminate`。
注意：;; 仅在支持 C++17 并行算法的编译器中可用。+
+
仅当 `std::is_execution_policy_v<std::remove_cvref_t<ExecutionPolicy>>` 为 `true` 时，此重载才会参与重载解析。+
+
不允许使用无序执行策略。

---

==== swap（交换）
```c++

void swap(concurrent_node_set& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
           boost::allocator_traits<Allocator>::propagate_on_container_swap::value);

```

将表的内容与参数交换。

如果声明了 `Allocator::propagate_on_container_swap` 且 `Allocator::propagate_on_container_swap::value` 为 `true`，则交换表的分配器。否则，使用不相等的分配器进行交换会导致未定义行为。

[horizontal]
抛出：;; 除非 `key_equal` 或 `hasher` 在交换时抛出异常，否则不抛出任何异常。
并发性：;; 阻塞于 `*this` 和 `other`。

---

==== extract（提取）
```c++

node_type extract(const key_type& k); template<class K> node_type extract(K&& k);

```

提取键等于 `k` 的元素（如果存在）。

[horizontal]
返回：;; 一个包含被提取元素的 `node_type` 对象，如果未提取任何元素则为空。
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才抛出异常。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才会参与重载解析。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== extract_if（条件提取）
```c++

template<class F> node_type extract_if(const key_type& k, F f); template<class K, class F> node_type extract_if(K&& k, F f);

```

如果存在键等于 `k` 的元素 `x` 且 `f(x)` 为 `true`，则提取该元素。

[horizontal]
返回：;; 一个包含被提取元素的 `node_type` 对象，如果未提取任何元素则为空。
抛出：;; 仅当 `hasher`、`key_equal` 或 `f` 抛出异常时才抛出异常。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才会参与重载解析。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== clear（清空）
```c++

void clear() noexcept;

```

擦除表中的所有元素。

[horizontal]
后置条件：;; `size() == 0`, `max_load() >= max_load_factor() * bucket_count()`
并发性：;; 阻塞于 `*this`。

---

==== merge（合并）
```c++

template<class H2, class P2>
  size_type merge(concurrent_node_set<Key, H2, P2, Allocator>& source);
template<class H2, class P2>
  size_type merge(concurrent_node_set<Key, H2, P2, Allocator>&& source);

```

将 `source` 中键不在 `*this` 中存在的所有元素移动插入到 `*this`，并从 `source` 中擦除这些元素。

[horizontal]
返回：;; 插入的元素数量。
并发性：;; 阻塞于 `*this` 和 `source`。

---

=== 观察器

==== get_allocator（获取分配器）
```

allocator_type get_allocator() const noexcept;

```

[horizontal]
返回：;; 表的分配器。

---

==== hash_function（哈希函数）
```

hasher hash_function() const;

```

[horizontal]
返回：;; 表的哈希函数。

---

==== key_eq（键相等谓词）
```

key_equal key_eq() const;

```

[horizontal]
返回：;; 表的键相等谓词。

---

=== Set Operations

==== count（计数）
```c++

size_type        count(const key_type& k) const;
template<class K>
  size_type      count(const K& k) const;

```

[horizontal]
返回：;; 键等于 `k` 的元素数量（0 或 1）。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才会参与重载解析。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。+
+
在存在并发插入操作的情况下，返回值可能无法准确反映执行后表的实际状态。

---

==== contains（包含）
```c++

bool             contains(const key_type& k) const;
template<class K>
  bool           contains(const K& k) const;

```

[horizontal]
返回：;; 一个布尔值，指示表中是否存在键等于 `k` 的元素。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才会参与重载解析。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。+
+
在存在并发插入操作的情况下，返回值可能无法准确反映执行后表的实际状态。

---
=== 桶接口

==== bucket_count（桶数量）
```c++

size_type bucket_count() const noexcept;

```

[horizontal]
返回：;; 桶数组的大小。

---

=== 哈希策略

==== load_factor（负载因子）
```c++

float load_factor() const noexcept;

```

[horizontal]
返回：;; `static_cast<float>(size())/static_cast<float>(bucket_count())`，如果 `bucket_count() == 0` 则为 `0`。

---

==== max_load_factor（最大负载因子）

```c++

float max_load_factor() const noexcept;

```

[horizontal]
返回：;; 返回表的最大负载因子。

---

==== 设置最大负载因子
```c++

void max_load_factor(float z);

```

[horizontal]
效果：;; Does nothing, as the user is not allowed to change this parameter. Kept for compatibility with `boost::unordered_set`.

---


==== max_load（最大负载）

```c++

size_type max_load() const noexcept;

```

[horizontal]
返回：;; 在不再擦除元素的前提下，表在不重哈希的情况下可容纳的最大元素数量。
注意：;; 构造、重哈希或清空后，表的最大负载至少为 `max_load_factor() * bucket_count()`。在高负载条件下擦除元素时，此数值可能减少。+
+
在存在并发插入操作的情况下，返回值可能无法准确反映执行后表的实际状态。

---

==== rehash（重哈希）
```c++

void rehash(size_type n);

```

必要时更改桶数组的大小，使其至少包含 `n` 个桶，且负载因子小于或等于最大负载因子。适用时，此操作将增加或减少与表关联的 `bucket_count()`。

当 `size() == 0` 时，`rehash(0)` 将释放底层桶数组。

[horizontal]
抛出：;; 如果抛出异常（除非由表的哈希函数或比较函数抛出），则函数无效果。
并发性：;; 阻塞于 `*this`。
---

==== reserve（预留）
```c++

void reserve(size_type n);

```

等效于 `a.rehash(ceil(n / a.max_load_factor()))`。

类似于 `rehash`，此函数可用于增加或减少表中的桶数量。

[horizontal]
抛出：;; 如果抛出异常（除非由表的哈希函数或比较函数抛出），则函数无效果。
并发性：;; 阻塞于 `*this`。

---

=== 统计

==== get_stats（获取统计信息）
```c++

stats get_stats() const;

```

[horizontal]
返回：;; 对表迄今为止执行的插入和查找操作的统计描述。
注意：;; Only available if xref:reference/stats.adoc#stats[statistics calculation] is xref:concurrent_node_set_boost_unordered_enable_stats[enabled].

---

==== reset_stats（重置统计信息）
```c++

void reset_stats() noexcept;

```

[horizontal]
效果：;; 将表维护的内部统计信息重置为零。
注意：;; Only available if xref:reference/stats.adoc#stats[statistics calculation] is xref:concurrent_node_set_boost_unordered_enable_stats[enabled].

---

=== 推导指引
如果以下任一条件为真，则推导指引不参与重载解析：

  - 具有 `InputIterator` 模板参数，且为该参数推导出的类型不符合输入迭代器要求。
  - 具有 `Allocator` 模板参数，且为该参数推导出的类型不符合分配器要求。
  - 具有 `Hash` 模板参数，且为该参数推导出的类型为整型或符合分配器要求。
  - 具有 `Pred` 模板参数，且为该参数推导出的类型符合分配器要求。

A `size_­type` parameter type in a deduction guide refers to the `size_­type` member type of the container type deduced by the deduction guide. Its default value coincides with the default value of the constructor selected.

==== __iter-value-type__（迭代器值类型）
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-value-type__ =
    typename std::iterator_traits<InputIterator>::value_type; // 仅用于说明
-----

=== 相等比较

==== operator==（等于运算符）
```c++

template<class Key, class Hash, class Pred, class Alloc>
  bool operator==(const concurrent_node_set<Key, Hash, Pred, Alloc>& x,
                  const concurrent_node_set<Key, Hash, Pred, Alloc>& y);

```

如果 `x.size() == y.size()` 且对于 `x` 中的每个元素，`y` 中均存在具有相同键且值相等的元素（使用 `operator==` 比较值类型），则返回 `true`。

[horizontal]
并发性：;; 阻塞于 `x` 和 `y`。
注意：;; 如果两个表不具有等价的相等谓词，则行为未定义。

---

==== operator!=（不等于运算符）
```c++

template<class Key, class Hash, class Pred, class Alloc>
  bool operator!=(const concurrent_node_set<Key, Hash, Pred, Alloc>& x,
                  const concurrent_node_set<Key, Hash, Pred, Alloc>& y);

```

如果 `x.size() == y.size()` 且对于 `x` 中的每个元素，`y` 中均存在具有相同键且值相等的元素（使用 `operator==` 比较值类型），则返回 `false`。

[horizontal]
并发性：;; 阻塞于 `x` 和 `y`。
注意：;; 如果两个表不具有等价的相等谓词，则行为未定义。

---

=== 交换
```c++

template<class Key, class Hash, class Pred, class Alloc>
  void swap(concurrent_node_set<Key, Hash, Pred, Alloc>& x,
            concurrent_node_set<Key, Hash, Pred, Alloc>& y)
    noexcept(noexcept(x.swap(y)));

```

等效于
[listing, subs="+macros,+quotes"]
-----
x.xref:#concurrent_node_set_swap[swap](y);
-----

---

=== 条件擦除（erase_if）
```c++

template<class K, class H, class P, class A, class Predicate>
  typename concurrent_node_set<K, H, P, A>::size_type
    erase_if(concurrent_node_set<K, H, P, A>& c, Predicate pred);

```

等效于
[listing, subs="+macros,+quotes"]
-----
c.xref:#concurrent_node_set_erase_if[erase_if](pred);
-----

=== 序列化

``concurrent_node_set``s can be archived/retrieved by means of link:../../../../../serialization/index.html[Boost.Serialization^] using the API provided by this library. Both regular and XML archives are supported.

==== Saving an concurrent_node_set to an archive

Saves all the elements of a `concurrent_node_set` `x` to an archive (XML archive) `ar`.

[horizontal]
要求：;; `value_type` is serializable (XML serializable), and it supports Boost.Serialization `save_construct_data`/`load_construct_data` protocol (automatically suported by https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible^] types).
并发性：;; 阻塞于 `x`。

---

==== Loading an concurrent_node_set from an archive

Deletes all preexisting elements of a `concurrent_node_set` `x` and inserts from an archive (XML archive) `ar` restored copies of the elements of the original `concurrent_node_set` `other` saved to the storage read by `ar`.

[horizontal]
要求：;; `x.key_equal()` 在功能上等价于 `other.key_equal()`。
并发性：;; 阻塞于 `x`。
