[#concurrent_node_set]
== 类模板 concurrent_node_set

:idprefix: concurrent_node_set_

`boost::concurrent_node_set` — 一个基于节点的哈希表，用于存储唯一值，并允许并发元素插入、擦除、查找和访问，而无需外部同步机制。

尽管 `boost::concurrent_node_set` 充当容器，但它并不模拟标准 C++ https://en.cppreference.com/w/cpp/named_req/Container[Container^] 概念。具体来说，它不提供迭代器及相关操作（`begin`、`end` 等）。元素访问通过用户提供的_访问函数_完成，这些函数传递给 `concurrent_node_set` 的操作，并在内部以受控方式执行。这种基于访问的 API 支持低争用的并发使用场景。

`boost::concurrent_node_set` 的内部数据结构与 `boost::unordered_node_set` 类似。与 `boost::concurrent_flat_set` 不同，它提供了指针稳定性和节点处理功能，但可能以性能降低为代价。

=== 概要

[listing, subs="+macros,+quotes"]
-----
// #include xref:reference/header_concurrent_node_set.adoc[`<boost/unordered/concurrent_node_set.hpp>`]

namespace boost {
namespace unordered {

  template<class Key,
           class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<Key>>
  class concurrent_node_set {
  public:
    // types
    using key_type             = Key;
    using value_type           = Key;
    using init_type            = Key;
    using hasher               = Hash;
    using key_equal            = Pred;
    using allocator_type       = Allocator;
    using pointer              = typename std::allocator_traits<Allocator>::pointer;
    using const_pointer        = typename std::allocator_traits<Allocator>::const_pointer;
    using reference            = value_type&;
    using const_reference      = const value_type&;
    using size_type            = std::size_t;
    using difference_type      = std::ptrdiff_t;

    using node_type            = _由实现定义_;
    using insert_return_type   = _由实现定义_;

    using stats                = xref:reference/stats.adoc#stats_stats_type[__stats-type__]; // if statistics are xref:concurrent_node_set_boost_unordered_enable_stats[enabled]

    // constants
    static constexpr size_type xref:#concurrent_node_set_constants[bulk_visit_size] = _implementation-defined_;

    // construct/copy/destroy
    xref:#concurrent_node_set_default_constructor[concurrent_node_set]();
    explicit xref:#concurrent_node_set_bucket_count_constructor[concurrent_node_set](size_type n,
                                 const hasher& hf = hasher(),
                                 const key_equal& eql = key_equal(),
                                 const allocator_type& a = allocator_type());
    template<class InputIterator>
      xref:#concurrent_node_set_iterator_range_constructor[concurrent_node_set](InputIterator f, InputIterator l,
                          size_type n = _implementation-defined_,
                          const hasher& hf = hasher(),
                          const key_equal& eql = key_equal(),
                          const allocator_type& a = allocator_type());
    xref:#concurrent_node_set_copy_constructor[concurrent_node_set](const concurrent_node_set& other);
    xref:#concurrent_node_set_move_constructor[concurrent_node_set](concurrent_node_set&& other);
    template<class InputIterator>
      xref:#concurrent_node_set_iterator_range_constructor_with_allocator[concurrent_node_set](InputIterator f, InputIterator l,const allocator_type& a);
    explicit xref:#concurrent_node_set_allocator_constructor[concurrent_node_set](const Allocator& a);
    xref:#concurrent_node_set_copy_constructor_with_allocator[concurrent_node_set](const concurrent_node_set& other, const Allocator& a);
    xref:#concurrent_node_set_move_constructor_with_allocator[concurrent_node_set](concurrent_node_set&& other, const Allocator& a);
    xref:#concurrent_node_set_move_constructor_from_unordered_node_set[concurrent_node_set](unordered_node_set<Key, Hash, Pred, Allocator>&& other);
    xref:#concurrent_node_set_initializer_list_constructor[concurrent_node_set](std::initializer_list<value_type> il,
                        size_type n = _implementation-defined_
                        const hasher& hf = hasher(),
                        const key_equal& eql = key_equal(),
                        const allocator_type& a = allocator_type());
    xref:#concurrent_node_set_bucket_count_constructor_with_allocator[concurrent_node_set](size_type n, const allocator_type& a);
    xref:#concurrent_node_set_bucket_count_constructor_with_hasher_and_allocator[concurrent_node_set](size_type n, const hasher& hf, const allocator_type& a);
    template<class InputIterator>
      xref:#concurrent_node_set_iterator_range_constructor_with_bucket_count_and_allocator[concurrent_node_set](InputIterator f, InputIterator l, size_type n,
                          const allocator_type& a);
    template<class InputIterator>
      xref:#concurrent_node_set_iterator_range_constructor_with_bucket_count_and_hasher[concurrent_node_set](InputIterator f, InputIterator l, size_type n, const hasher& hf,
                          const allocator_type& a);
    xref:#concurrent_node_set_initializer_list_constructor_with_allocator[concurrent_node_set](std::initializer_list<value_type> il, const allocator_type& a);
    xref:#concurrent_node_set_initializer_list_constructor_with_bucket_count_and_allocator[concurrent_node_set](std::initializer_list<value_type> il, size_type n,
                        const allocator_type& a);
    xref:#concurrent_node_set_initializer_list_constructor_with_bucket_count_and_hasher_and_allocator[concurrent_node_set](std::initializer_list<value_type> il, size_type n, const hasher& hf,
                        const allocator_type& a);
    xref:#concurrent_node_set_destructor[~concurrent_node_set]();
    concurrent_node_set& xref:#concurrent_node_set_copy_assignment[operator++=++](const concurrent_node_set& other);
    concurrent_node_set& xref:#concurrent_node_set_move_assignment[operator++=++](concurrent_node_set&& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
              boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value);
    concurrent_node_set& xref:#concurrent_node_set_initializer_list_assignment[operator++=++](std::initializer_list<value_type>);
    allocator_type xref:#concurrent_node_set_get_allocator[get_allocator]() const noexcept;


    // visitation
    template<class F> size_t xref:#concurrent_node_set_cvisit[visit](const key_type& k, F f);
    template<class F> size_t xref:#concurrent_node_set_cvisit[visit](const key_type& k, F f) const;
    template<class F> size_t xref:#concurrent_node_set_cvisit[cvisit](const key_type& k, F f) const;
    template<class K, class F> size_t xref:#concurrent_node_set_cvisit[visit](const K& k, F f);
    template<class K, class F> size_t xref:#concurrent_node_set_cvisit[visit](const K& k, F f) const;
    template<class K, class F> size_t xref:#concurrent_node_set_cvisit[cvisit](const K& k, F f) const;

    template<class FwdIterator, class F>
      size_t xref:concurrent_node_set_bulk_visit[visit](FwdIterator first, FwdIterator last, F f);
    template<class FwdIterator, class F>
      size_t xref:concurrent_node_set_bulk_visit[visit](FwdIterator first, FwdIterator last, F f) const;
    template<class FwdIterator, class F>
      size_t xref:concurrent_node_set_bulk_visit[cvisit](FwdIterator first, FwdIterator last, F f) const;

    template<class F> size_t xref:#concurrent_node_set_cvisit_all[visit_all](F f);
    template<class F> size_t xref:#concurrent_node_set_cvisit_all[visit_all](F f) const;
    template<class F> size_t xref:#concurrent_node_set_cvisit_all[cvisit_all](F f) const;
    template<class ExecutionPolicy, class F>
      void xref:#concurrent_node_set_parallel_cvisit_all[visit_all](ExecutionPolicy&& policy, F f);
    template<class ExecutionPolicy, class F>
      void xref:#concurrent_node_set_parallel_cvisit_all[visit_all](ExecutionPolicy&& policy, F f) const;
    template<class ExecutionPolicy, class F>
      void xref:#concurrent_node_set_parallel_cvisit_all[cvisit_all](ExecutionPolicy&& policy, F f) const;

    template<class F> bool xref:#concurrent_node_set_cvisit_while[visit_while](F f);
    template<class F> bool xref:#concurrent_node_set_cvisit_while[visit_while](F f) const;
    template<class F> bool xref:#concurrent_node_set_cvisit_while[cvisit_while](F f) const;
    template<class ExecutionPolicy, class F>
      bool xref:#concurrent_node_set_parallel_cvisit_while[visit_while](ExecutionPolicy&& policy, F f);
    template<class ExecutionPolicy, class F>
      bool xref:#concurrent_node_set_parallel_cvisit_while[visit_while](ExecutionPolicy&& policy, F f) const;
    template<class ExecutionPolicy, class F>
      bool xref:#concurrent_node_set_parallel_cvisit_while[cvisit_while](ExecutionPolicy&& policy, F f) const;

    // capacity
    ++[[nodiscard]]++ bool xref:#concurrent_node_set_empty[empty]() const noexcept;
    size_type xref:#concurrent_node_set_size[size]() const noexcept;
    size_type xref:#concurrent_node_set_max_size[max_size]() const noexcept;

    // modifiers
    template<class... Args> bool xref:#concurrent_node_set_emplace[emplace](Args&&... args);
    bool xref:#concurrent_node_set_copy_insert[insert](const value_type& obj);
    bool xref:#concurrent_node_set_move_insert[insert](value_type&& obj);
    template<class K> bool xref:#concurrent_node_set_transparent_insert[insert](K&& k);
    template<class InputIterator> size_type xref:#concurrent_node_set_insert_iterator_range[insert](InputIterator first, InputIterator last);
    size_type xref:#concurrent_node_set_insert_initializer_list[insert](std::initializer_list<value_type> il);
    insert_return_type xref:#concurrent_node_set_insert_node[insert](node_type&& nh);

    template<class... Args, class F> bool xref:#concurrent_node_set_emplace_or_cvisit[emplace_or_visit](Args&&... args, F&& f);
    template<class... Args, class F> bool xref:#concurrent_node_set_emplace_or_cvisit[emplace_or_cvisit](Args&&... args, F&& f);
    template<class F> bool xref:#concurrent_node_set_copy_insert_or_cvisit[insert_or_visit](const value_type& obj, F f);
    template<class F> bool xref:#concurrent_node_set_copy_insert_or_cvisit[insert_or_cvisit](const value_type& obj, F f);
    template<class F> bool xref:#concurrent_node_set_move_insert_or_cvisit[insert_or_visit](value_type&& obj, F f);
    template<class F> bool xref:#concurrent_node_set_move_insert_or_cvisit[insert_or_cvisit](value_type&& obj, F f);
    template<class K, class F> bool xref:#concurrent_node_set_transparent_insert_or_cvisit[insert_or_visit](K&& k, F f);
    template<class K, class F> bool xref:#concurrent_node_set_transparent_insert_or_cvisit[insert_or_cvisit](K&& k, F f);
    template<class InputIterator,class F>
      size_type xref:#concurrent_node_set_insert_iterator_range_or_visit[insert_or_visit](InputIterator first, InputIterator last, F f);
    template<class InputIterator,class F>
      size_type xref:#concurrent_node_set_insert_iterator_range_or_visit[insert_or_cvisit](InputIterator first, InputIterator last, F f);
    template<class F> size_type xref:#concurrent_node_set_insert_initializer_list_or_visit[insert_or_visit](std::initializer_list<value_type> il, F f);
    template<class F> size_type xref:#concurrent_node_set_insert_initializer_list_or_visit[insert_or_cvisit](std::initializer_list<value_type> il, F f);
    template<class F> insert_return_type xref:#concurrent_node_set_insert_node_or_visit[insert_or_visit](node_type&& nh, F f);
    template<class F> insert_return_type xref:#concurrent_node_set_insert_node_or_visit[insert_or_cvisit](node_type&& nh, F f);

    template<class... Args, class F1, class F2>
      bool xref:#concurrent_node_set_emplace_and_cvisit[emplace_and_visit](Args&&... args, F1&& f1, F2&& f2);
    template<class... Args, class F1, class F2>
      bool xref:#concurrent_node_set_emplace_and_cvisit[emplace_and_cvisit](Args&&... args, F1&& f1, F2&& f2);
    template<class F1, class F2> bool xref:#concurrent_node_set_copy_insert_and_cvisit[insert_and_visit](const value_type& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool xref:#concurrent_node_set_copy_insert_and_cvisit[insert_and_cvisit](const value_type& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool xref:#concurrent_node_set_move_insert_and_cvisit[insert_and_visit](value_type&& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool xref:#concurrent_node_set_move_insert_and_cvisit[insert_and_cvisit](value_type&& obj, F1 f1, F2 f2);
    template<class K, class F1, class F2> bool xref:#concurrent_node_set_transparent_insert_and_cvisit[insert_and_visit](K&& k, F1 f1, F2 f2);
    template<class K, class F1, class F2> bool xref:#concurrent_node_set_transparent_insert_and_cvisit[insert_and_cvisit](K&& k, F1 f1, F2 f2);
    template<class InputIterator,class F1, class F2>
      size_type xref:#concurrent_node_set_insert_iterator_range_and_visit[insert_and_visit](InputIterator first, InputIterator last, F1 f1, F2 f2);
    template<class InputIterator,class F1, class F2>
      size_type xref:#concurrent_node_set_insert_iterator_range_and_visit[insert_and_cvisit](InputIterator first, InputIterator last, F1 f1, F2 f2);
    template<class F1, class F2>
      size_type xref:#concurrent_node_set_insert_initializer_list_and_visit[insert_and_visit](std::initializer_list<value_type> il, F1 f1, F2 f2);
    template<class F1, class F2>
      size_type xref:#concurrent_node_set_insert_initializer_list_and_visit[insert_and_cvisit](std::initializer_list<value_type> il, F1 f1, F2 f2);
    template<class F1, class F2>
      insert_return_type xref:#concurrent_node_set_insert_node_and_visit[insert_and_visit](node_type&& nh, F1 f1, F2 f2);
    template<class F1, class F2>
      insert_return_type xref:#concurrent_node_set_insert_node_and_visit[insert_and_cvisit](node_type&& nh, F1 f1, F2 f2);

    size_type xref:#concurrent_node_set_erase[erase](const key_type& k);
    template<class K> size_type xref:#concurrent_node_set_erase[erase](const K& k);

    template<class F> size_type xref:#concurrent_node_set_erase_if_by_key[erase_if](const key_type& k, F f);
    template<class K, class F> size_type xref:#concurrent_node_set_erase_if_by_key[erase_if](const K& k, F f);
    template<class F> size_type xref:#concurrent_node_set_erase_if[erase_if](F f);
    template<class ExecutionPolicy, class  F> void xref:#concurrent_node_set_parallel_erase_if[erase_if](ExecutionPolicy&& policy, F f);

    void      xref:#concurrent_node_set_swap[swap](concurrent_node_set& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
               boost::allocator_traits<Allocator>::propagate_on_container_swap::value);

    node_type xref:#concurrent_node_set_extract[extract](const key_type& k);
    template<class K> node_type xref:#concurrent_node_set_extract[extract](const K& k);

    template<class F> node_type xref:#concurrent_node_set_extract_if[extract_if](const key_type& k, F f);
    template<class K, class F> node_type xref:#concurrent_node_set_extract[extract_if](const K& k, F f);

    void      xref:#concurrent_node_set_clear[clear]() noexcept;

    template<class H2, class P2>
      size_type xref:#concurrent_node_set_merge[merge](concurrent_node_set<Key, H2, P2, Allocator>& source);
    template<class H2, class P2>
      size_type xref:#concurrent_node_set_merge[merge](concurrent_node_set<Key, H2, P2, Allocator>&& source);

    // observers
    hasher xref:#concurrent_node_set_hash_function[hash_function]() const;
    key_equal xref:#concurrent_node_set_key_eq[key_eq]() const;

    // set operations
    size_type        xref:#concurrent_node_set_count[count](const key_type& k) const;
    template<class K>
      size_type      xref:#concurrent_node_set_count[count](const K& k) const;
    bool             xref:#concurrent_node_set_contains[contains](const key_type& k) const;
    template<class K>
      bool           xref:#concurrent_node_set_contains[contains](const K& k) const;

    // bucket interface
    size_type xref:#concurrent_node_set_bucket_count[bucket_count]() const noexcept;

    // hash policy
    float xref:#concurrent_node_set_load_factor[load_factor]() const noexcept;
    float xref:#concurrent_node_set_max_load_factor[max_load_factor]() const noexcept;
    void xref:#concurrent_node_set_set_max_load_factor[max_load_factor](float z);
    size_type xref:#concurrent_node_set_max_load[max_load]() const noexcept;
    void xref:#concurrent_node_set_rehash[rehash](size_type n);
    void xref:#concurrent_node_set_reserve[reserve](size_type n);

    // statistics (if xref:concurrent_node_set_boost_unordered_enable_stats[enabled])
    stats xref:#concurrent_node_set_get_stats[get_stats]() const;
    void xref:#concurrent_node_set_reset_stats[reset_stats]() noexcept;
  };

  // Deduction Guides
  template<class InputIterator,
           class Hash = boost::hash<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>>,
           class Pred = std::equal_to<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>>,
           class Allocator = std::allocator<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>>>
    concurrent_node_set(InputIterator, InputIterator, typename xref:#concurrent_node_set_deduction_guides[__see below__]::size_type = xref:#concurrent_node_set_deduction_guides[__see below__],
                        Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> concurrent_node_set<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>, Hash, Pred, Allocator>;

  template<class T, class Hash = boost::hash<T>, class Pred = std::equal_to<T>,
           class Allocator = std::allocator<T>>
    concurrent_node_set(std::initializer_list<T>, typename xref:#concurrent_node_set_deduction_guides[__see below__]::size_type = xref:#concurrent_node_set_deduction_guides[__see below__],
                        Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> concurrent_node_set<T, Hash, Pred, Allocator>;

  template<class InputIterator, class Allocator>
    concurrent_node_set(InputIterator, InputIterator, typename xref:#concurrent_node_set_deduction_guides[__see below__]::size_type, Allocator)
      -> concurrent_node_set<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>,
                             boost::hash<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>>,
                             std::equal_to<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Allocator>
    concurrent_node_set(InputIterator, InputIterator, Allocator)
      -> concurrent_node_set<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>,
                             boost::hash<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>>,
                             std::equal_to<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Hash, class Allocator>
    concurrent_node_set(InputIterator, InputIterator, typename xref:#concurrent_node_set_deduction_guides[__see below__]::size_type, Hash,
                        Allocator)
      -> concurrent_node_set<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>, Hash,
                             std::equal_to<xref:#concurrent_node_set_iter_value_type[__iter-value-type__]<InputIterator>>, Allocator>;

  template<class T, class Allocator>
    concurrent_node_set(std::initializer_list<T>, typename xref:#concurrent_node_set_deduction_guides[__see below__]::size_type, Allocator)
      -> concurrent_node_set<T, boost::hash<T>, std::equal_to<T>, Allocator>;

  template<class T, class Allocator>
    concurrent_node_set(std::initializer_list<T>, Allocator)
      -> concurrent_node_set<T, boost::hash<T>, std::equal_to<T>, Allocator>;

  template<class T, class Hash, class Allocator>
    concurrent_node_set(std::initializer_list<T>, typename xref:#concurrent_node_set_deduction_guides[__see below__]::size_type, Hash, Allocator)
      -> concurrent_node_set<T, Hash, std::equal_to<T>, Allocator>;

} // namespace unordered
} // namespace boost
-----

---

=== 描述

*模板参数*

[cols="1,1"]
|===

|_Key_
|`Key` 必须可 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[移动插入^] 到容器中
且可 https://en.cppreference.com/w/cpp/named_req/Erasable[擦除^] 出容器。

|_Hash_
|一种一元函数对象类型，用作 `Key` 的哈希函数。它接受一个 `Key` 类型的参数并返回一个 `std::size_t` 类型的值。

|_Pred_
|二元函数对象，用于在 `Key` 类型的值上建立等价关系。它接受两个类型为 `Key` 的参数，并返回一个类型为 `bool` 的值。

|_Allocator_
|一个分配器，其值类型与表的值类型相同。
`std::allocator_traits<Allocator>::pointer` 和 `std::allocator_traits<Allocator>::const_pointer`
必须能分别转换为 `value_type*` 和 `const value_type*`，或从这些类型转换而来。

|===

表的元素节点保存在内部的_桶数组_中。节点被插入到由其元素的哈希码确定的桶中，但如果该桶已被占用（发生_冲突_），则使用原始位置附近的可用桶。

桶数组的大小可通过调用 `insert`/`emplace` 自动增加，或作为调用 `rehash`/`reserve` 的结果而增加。表的_负载因子_（元素数量除以桶数量）永远不会大于 `max_load_factor()`，除非在较小规模时实现可能允许更高的负载。

如果 `link:../../../../../container_hash/doc/html/hash.html#ref_hash_is_avalanchinghash[hash_is_avalanching]<Hash>::value` 为 `true`，则直接使用哈希函数；否则，会添加一个位混合后处理阶段以提高哈希质量，但会增加额外的计算成本。

---

=== 并发要求与保证

要求对 `Hash` 或 `Pred` 的同一常量实例并发调用 `operator()` 不会引入数据竞争。对于 `Alloc`（即 `Allocator` 或从 `Allocator` 重新绑定的任何分配器类型），要求对同一 `Alloc` 实例 `al` 并发调用以下操作不会引入数据竞争：

* 从重新绑定自 `Alloc` 的分配器复制构造 `al`
* `std::allocator_traits<Alloc>::allocate`
* `std::allocator_traits<Alloc>::deallocate`
* `std::allocator_traits<Alloc>::construct`
* `std::allocator_traits<Alloc>::destroy`

通常，如果这些类型无状态或操作仅涉及对内部数据成员的常量访问，则满足对 `Hash`、`Pred` 和 `Allocator` 的这些要求。

除析构操作外，对同一 `concurrent_node_set` 实例并发调用任何操作都不会引入数据竞争——即它们是线程安全的。

如果操作 *op* 被显式指定为_阻塞于_ `x`（其中 `x` 是 `boost::concurrent_node_set` 的实例），则先前对 `x` 的阻塞操作将与 *op* 同步。因此，在同一 `concurrent_node_set` 上的阻塞操作在多线程场景中会顺序执行。

如果操作仅在内部发生重哈希时阻塞于 `x`，则称该操作_阻塞于重哈希_ ``__x__``。

当由 `boost::concurrent_node_set` 内部执行时，用户提供的访问函数对传递的元素执行以下操作不会引入数据竞争：

* 对元素的读取访问。
* 对元素的非可变修改。
* 对元素的可变修改：
  ** 在接收两个访问函数的容器函数中，始终针对第一个函数。
  ** 在名称不包含 `cvisit` 的非 const 容器函数中，针对最后一个（或唯一）访问函数。

任何插入或修改元素 `e` 的 `boost::concurrent_node_set` 操作都会与在 `e` 上内部调用的访问函数同步。

由 `boost::concurrent_node_set` `x` 执行的访问函数不允许调用 `x` 的任何操作；仅当对另一 `boost::concurrent_node_set` 实例 `y` 的并发未完成操作不直接或间接访问 `x` 时，才允许调用 `y` 的操作。

---

=== 配置宏

==== `BOOST_UNORDERED_DISABLE_REENTRANCY_CHECK`

在调试版本中（更准确地说，当未定义 link:../../../../../assert/doc/html/assert.html#boost_assert_is_void[`BOOST_ASSERT_IS_VOID`^] 时），会检测__容器重入__（在访问 `m` 元素的函数内部非法调用 `m` 的操作）并通过 `BOOST_ASSERT_MSG` 发出信号。当运行时速度成为关注点时，可通过全局定义此宏禁用该功能。

---

==== `BOOST_UNORDERED_ENABLE_STATS`

全局定义此宏以启用表的 xref:reference/stats.adoc#stats[统计计算]。请注意，此选项会降低许多操作的总体性能。

---

=== 类型定义

[source, c++, subs=+quotes]
----
typedef _由实现定义_ node_type;
----

用于保存提取的表元素的类，模拟 https://en.cppreference.com/w/cpp/container/node_handle[NodeHandle]。

---

[source, c++, subs=+quotes]
----
typedef _由实现定义_ insert_return_type;
----

一个内部类模板的特化：

[source, c++, subs=+quotes]
----
template<class NodeType>
struct _insert_return_type_ // 名称仅用于说明
{
  bool     inserted;
  NodeType node;
};
----

其中 `NodeType` = `node_type`。

---

=== 常量

```cpp

static constexpr size_type bulk_visit_size;

```

在 xref:concurrent_node_set_bulk_visit[批量访问]操作内部使用的块大小。

=== 构造函数

==== 默认构造函数
```c++

concurrent_node_set();

```

使用 `hasher()` 作为哈希函数、`key_equal()` 作为键相等谓词、`allocator_type()` 作为分配器构造一个空表。

[horizontal]
后置条件：;; `size() == 0`
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 桶数量构造函数
```c++

explicit concurrent_node_set(size_type n,
                             const hasher& hf = hasher(),
                             const key_equal& eql = key_equal(),
                             const allocator_type& a = allocator_type());

```

构造一个至少包含 `n` 个桶的空表，使用 `hf` 作为哈希函数、`eql` 作为键相等谓词、`a` 作为分配器。

[horizontal]
后置条件：;; `size() == 0`
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  concurrent_node_set(InputIterator f, InputIterator l,
                      size_type n = _implementation-defined_,
                      const hasher& hf = hasher(),
                      const key_equal& eql = key_equal(),
                      const allocator_type& a = allocator_type());
----

构造一个至少包含 `n` 个桶的空表，使用 `hf` 作为哈希函数、`eql` 作为键相等谓词、`a` 作为分配器，并将 `[f, l)` 中的元素插入其中。

[horizontal]
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 复制构造函数
```c++

concurrent_node_set(concurrent_node_set const& other);

```

复制构造函数。复制所含元素、哈希函数、谓词及分配器。

若 `Allocator::select_on_container_copy_construction` 存在且签名正确，则分配器将根据其结果构造。

[horizontal]
要求：;; `value_type` 需可复制构造
并发性：;; 在 `other` 上阻塞。

---

==== 移动构造函数
```c++

concurrent_node_set(concurrent_node_set&& other);

```

移动构造函数。`other` 的内部桶数组直接转移至新表。哈希函数、谓词和分配器从 `other` 移动构造。如果统计功能 xref:concurrent_node_set_boost_unordered_enable_stats[已启用]，则转移 `other` 的内部统计信息并调用 `other.reset_stats()`。

[horizontal]
并发性：;; 在 `other` 上阻塞。

---

==== 带分配器的迭代器范围构造函数
```c++

template<class InputIterator>
  concurrent_node_set(InputIterator f, InputIterator l, const allocator_type& a);

```

使用 `a` 作为分配器构造一个空表，采用默认哈希函数和键相等谓词，并将 `[f, l)` 中的元素插入其中。

[horizontal]
要求：;; `hasher`、`key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 分配器构造函数
```c++

explicit concurrent_node_set(Allocator const& a);

```

使用分配器 `a` 构造一个空表。

---

==== 带分配器的复制构造函数
```c++

concurrent_node_set(concurrent_node_set const& other, Allocator const& a);

```

构造一个表，复制 ``other`` 所包含的元素、哈希函数和谓词，但使用分配器 `a`。

[horizontal]
并发性：;; 在 `other` 上阻塞。

---

==== 带分配器的移动构造函数
```c++

concurrent_node_set(concurrent_node_set&& other, Allocator const& a);

```

如果 `a == other.get_allocator()`，则 `other` 的元素直接转移至新表；否则，元素从 `other` 的元素移动构造。哈希函数和谓词从 `other` 移动构造，分配器从 `a` 拷贝构造。如果统计功能 xref:concurrent_node_set_boost_unordered_enable_stats[已启用]，当且仅当 `a == other.get_allocator()` 时转移 `other` 的内部统计信息，并始终调用 `other.reset_stats()`。

[horizontal]
并发性：;; 在 `other` 上阻塞。

---

==== 从 unordered_node_set 的移动构造函数

```c++

concurrent_node_set(unordered_node_set<Key, Hash, Pred, Allocator>&& other);

```

从 xref:#unordered_node_set[`unordered_node_set`] 移动构造。`other` 的内部桶数组直接转移至新容器。哈希函数、谓词和分配器从 `other` 移动构造。如果统计功能 xref:concurrent_node_set_boost_unordered_enable_stats[已启用]，则转移 `other` 的内部统计信息并调用 `other.reset_stats()`。

[horizontal]
复杂度：;; O(`bucket_count()`)

---

==== 初始化列表构造函数
[source, c++, subs="+quotes"]
----
concurrent_node_set(std::initializer_list<value_type> il,
                    size_type n = _implementation-defined_
                    const hasher& hf = hasher(),
                    const key_equal& eql = key_equal(),
                    const allocator_type& a = allocator_type());
----

构造一个至少包含 `n` 个桶的空表，使用 `hf` 作为哈希函数、`eql` 作为键相等谓词、`a` 作为分配器，并将 `il` 中的元素插入其中。

[horizontal]
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带分配器的桶数量构造函数
```c++

concurrent_node_set(size_type n, allocator_type const& a);

```

构造一个至少包含 `n` 个桶的空表，使用 `hf` 作为哈希函数、默认哈希函数和键相等谓词，以及 `a` 作为分配器。

[horizontal]
后置条件：;; `size() == 0`
要求：;; `hasher` 和 `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带哈希函数和分配器的桶数量构造函数
```c++

concurrent_node_set(size_type n, hasher const& hf, allocator_type const& a);

```

构造一个至少包含 `n` 个桶的空表，使用 `hf` 作为哈希函数、默认键相等谓词和 `a` 作为分配器。

[horizontal]
后置条件：;; `size() == 0`
要求：;; `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带桶计数和分配器的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  concurrent_node_set(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空表，使用 `a` 作为分配器、默认哈希函数和键相等谓词，并将 `[f, l)` 中的元素插入其中。

[horizontal]
要求：;; `hasher`、`key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带桶计数和哈希函数的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
    template<class InputIterator>
      concurrent_node_set(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                          const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空表，使用 `hf` 作为哈希函数、`a` 作为分配器、默认键相等谓词，并将 `[f, l)` 中的元素插入其中。

[horizontal]
要求：;; `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带分配器的初始化列表构造函数

```c++

concurrent_node_set(std::initializer_list<value_type> il, const allocator_type& a);

```

使用 `a` 以及默认哈希函数和键相等谓词构造一个空表，并将 `il` 中的元素插入其中。

[horizontal]
要求：;; `hasher` 和 `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带桶计数和分配器的初始化列表构造函数

```c++

concurrent_node_set(std::initializer_list<value_type> il, size_type n, const allocator_type& a);

```

构造一个至少包含 `n` 个桶的空表，使用 `a` 以及默认哈希函数和键相等谓词，并将 `il` 中的元素插入其中。

[horizontal]
要求：;; `hasher` 和 `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带桶计数、哈希函数和分配器的初始化列表构造函数

```c++

concurrent_node_set(std::initializer_list<value_type> il, size_type n, const hasher& hf,
                    const allocator_type& a);

```

构造一个至少包含 `n` 个桶的空表，使用 `hf` 作为哈希函数、`a` 作为分配器、默认键相等谓词，并将 `il` 中的元素插入其中。

[horizontal]
要求：;; `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

=== 析构函数

```c++

~concurrent_node_set();

```

[horizontal]
注意：;; 析构函数会应用于每个元素，并释放所有内存。

---

=== 赋值

==== 复制赋值

```c++

concurrent_node_set& operator=(concurrent_node_set const& other);

```

赋值运算符。销毁先前存在的元素，从 `other` 复制赋值哈希函数和谓词，若 `Alloc::propagate_on_container_copy_assignment` 存在且 `Alloc::propagate_on_container_copy_assignment::value` 为 `true`，则从 `other` 复制赋值分配器，最后插入 `other` 元素的副本。

[horizontal]
要求：;; `value_type` 需满足可复制插入（CopyInsertable）要求
并发性：;; 阻塞于 `*this` 和 `other`。

---

==== 移动赋值
```c++

concurrent_node_set& operator=(concurrent_node_set&& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
           boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value);

```
移动赋值运算符。销毁先前存在的元素，交换 `other` 的哈希函数和谓词，
如果 `Alloc::propagate_on_container_move_assignment` 存在且 `Alloc::propagate_on_container_move_assignment::value` 为 `true`，则从 `other` 移动赋值分配器。
如果此时分配器等于 `other.get_allocator()`，则 `other` 的内部桶数组直接转移至 `*this`；
否则，插入 `other` 元素的移动构造副本。
如果统计功能 xref:concurrent_node_set_boost_unordered_enable_stats[已启用]，
当且仅当最终分配器等于 `other.get_allocator()` 时转移 `other` 的内部统计信息，
并始终调用 `other.reset_stats()`。

[horizontal]
并发性：;; 阻塞于 `*this` 和 `other`。

---

==== 初始化列表赋值
```c++

concurrent_node_set& operator=(std::initializer_list<value_type> il);

```

从初始化列表中的值赋值。销毁所有先前存在的元素。

[horizontal]
要求：;; `value_type` 需满足可复制插入（CopyInsertable）要求
并发性：;; 阻塞于 `*this`。

---

=== 访问操作

==== [c]visit

```c++

template<class F> size_t visit(const key_type& k, F f); template<class F> size_t visit(const key_type& k, F f) const; template<class F> size_t cvisit(const key_type& k, F f) const; template<class K, class F> size_t visit(const K& k, F f); template<class K, class F> size_t visit(const K& k, F f) const; template<class K, class F> size_t cvisit(const K& k, F f) const;

```

如果存在键等于 `k` 的元素 `x`，则使用 `x` 的常量引用调用 `f`。

[horizontal]
返回：;; 被访问的元素数量（0 或 1）。
备注：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K, class F>` 重载才会参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== 批量访问

```c++

template<class FwdIterator, class F>
  size_t visit(FwdIterator first, FwdIterator last, F f);
template<class FwdIterator, class F>
  size_t visit(FwdIterator first, FwdIterator last, F f) const;
template<class FwdIterator, class F>
  size_t cvisit(FwdIterator first, FwdIterator last, F f) const;

```

对于范围 [`first`, `last`) 中的每个元素 `k`，如果容器中存在键等于 `k` 的元素 `x`，则使用 `x` 的常量引用调用 `f`。

尽管在功能上等同于为每个键单独调用 xref:concurrent_node_set_cvisit[`[c\]visit`]，但批量访问由于内部流线优化通常性能更高。建议 `std::distance(first,last)` 至少为 xref:#concurrent_node_set_constants[`bulk_visit_size`] 以获得性能提升：超过此大小后，性能预计不会进一步提升。

[horizontal]
要求：;; `FwdIterator` 是 https://en.cppreference.com/w/cpp/named_req/ForwardIterator[前向迭代器^]（C++11 至 C++17），或满足 https://en.cppreference.com/w/cpp/iterator/forward_iterator[std::forward_iterator^]（C++20 及更高版本）。对于 `K` = `std::iterator_traits<FwdIterator>::value_type`，`K` 要么是 `key_type`，要么 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义。在后一种情况下，库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。
返回：;; 被访问的元素数量。

---

==== [c]visit_all

```c++

template<class F> size_t visit_all(F f); template<class F> size_t visit_all(F f) const; template<class F> size_t cvisit_all(F f) const;

```

依次使用表中每个元素的常量引用调用 `f`。

[horizontal]
返回：;; 被访问的元素数量。

---

==== 并行 [c]visit_all

```c++

template<class ExecutionPolicy, class F> void visit_all(ExecutionPolicy&& policy, F f); template<class ExecutionPolicy, class F> void visit_all(ExecutionPolicy&& policy, F f) const; template<class ExecutionPolicy, class F> void cvisit_all(ExecutionPolicy&& policy, F f) const;

```

使用表中每个元素的常量引用调用 `f`。执行根据指定的执行策略语义并行化。

[horizontal]
抛出：;; 根据所用执行策略的异常处理机制，如果在 `f` 内抛出异常，可能调用 `std::terminate`。
备注：;; 仅在支持 C++17 并行算法的编译器中可用。+
+
仅当 `std::is_execution_policy_v<std::remove_cvref_t<ExecutionPolicy>>` 为 `true` 时，这些重载才会参与重载决议。+
+
不允许非顺序执行策略。

---

==== [c]visit_while

```c++

template<class F> bool visit_while(F f); template<class F> bool visit_while(F f) const; template<class F> bool cvisit_while(F f) const;

```

依次使用表中每个元素的常量引用调用 `f`，直到 `f` 返回 `false` 或所有元素均被访问完毕。

[horizontal]
返回：;; 当且仅当 `f` 曾返回 `false` 时为 `false`。

---

==== 并行 [c]visit_while

```c++

template<class ExecutionPolicy, class F> bool visit_while(ExecutionPolicy&& policy, F f); template<class ExecutionPolicy, class F> bool visit_while(ExecutionPolicy&& policy, F f) const; template<class ExecutionPolicy, class F> bool cvisit_while(ExecutionPolicy&& policy, F f) const;

```

使用表中每个元素的常量引用调用 `f`，直到 `f` 返回 `false` 或所有元素均被访问完毕。执行根据指定的执行策略语义并行化。

[horizontal]
返回：;; 当且仅当 `f` 曾返回 `false` 时为 `false`。
抛出：;; 根据所用执行策略的异常处理机制，如果在 `f` 内抛出异常，可能调用 `std::terminate`。
备注：;; 仅在支持 C++17 并行算法的编译器中可用。+
+
仅当 `std::is_execution_policy_v<std::remove_cvref_t<ExecutionPolicy>>` 为 `true` 时，这些重载才会参与重载决议。+
+
不允许非顺序执行策略。+
+
并行化意味着执行不一定会因 `f` 返回 `false` 而立即结束，因此 `f` 可能会被继续调用以处理更多元素，即使返回值也为 `false`。

---

=== 大小与容量

==== empty

```c++

[[nodiscard]] bool empty() const noexcept;

```

[horizontal]
返回：;; `size() == 0`

---

==== size

```c++

size_type size() const noexcept;

```

[horizontal]
返回：;; 表中的元素数量。

[horizontal]
备注：;; 在存在并发插入操作的情况下，返回值可能无法准确反映执行后表的实际大小。

---

==== max_size

```c++

size_type max_size() const noexcept;

```

[horizontal]
返回：;; 最大可能表的 `size()`。

---

=== 修改器

==== emplace
```c++

template<class... Args> bool emplace(Args&&... args);

```

当且仅当表中不存在具有等效键的元素时，插入一个由参数 `args` 构造的对象。

[horizontal]
要求：;; `value_type` 需可从 `args` 构造。
返回：;; 若插入发生则为 `true`。
并发性：;; 阻塞于 `*this` 的重哈希。

---

==== 复制插入
```c++

bool insert(const value_type& obj);

```

当且仅当表中不存在具有等效键的元素时，插入 `obj`。

[horizontal]
要求：;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入] 要求。
返回：;; 若插入发生则为 `true`。+
并发性：;; 阻塞于 `*this` 的重哈希。

---

==== 移动插入
```c++

bool insert(value_type&& obj);

```

当且仅当表中不存在具有等效键的元素时，插入 `obj`。

[horizontal]
要求：;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入] 要求。
返回：;; 若插入发生则为 `true`。
并发性：;; 阻塞于 `*this` 的重哈希。

---

==== 透明插入
```c++

template<class K> bool insert(K&& k);

```

当且仅当容器中不存在等价键的元素时，插入一个由 `std::forward<K>(k)` 构造的元素。

[horizontal]
要求：;; `value_type` 需满足从 `k` 的 https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原位构造] 要求。
返回：;; 若插入发生则为 `true`。
并发性：;; 阻塞于 `*this` 的重哈希。
备注：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，此重载才会参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== 插入迭代器范围
```c++

template<class InputIterator> size_type insert(InputIterator first, InputIterator last);

```

等效于
[listing, subs="+macros,+quotes"]
-----
  while(first != last) this->xref:#concurrent_node_set_emplace[emplace](*first++);
-----

[horizontal]
返回：;; 插入的元素数量。

---

==== 插入初始化列表
```c++

size_type insert(std::initializer_list<value_type> il);

```

等效于
[listing, subs="+macros,+quotes"]
-----
  this->xref:#concurrent_node_set_insert_iterator_range[insert](il.begin(), il.end());
-----

[horizontal]
返回：;; 插入的元素数量。

---

==== 插入节点
```c++

insert_return_type insert(node_type&& nh);

```

若 `nh` 非空，则当且仅当表中不存在键等于 `nh.value()` 的元素时，插入关联元素。函数返回时 `nh` 为空。

[horizontal]
返回：;; 从 `inserted` 和 `node` 构造的 `insert_return_type` 对象：+
* 若 `nh` 为空，则 `inserted` 为 `false` 且 `node` 为空。
* 否则，若插入发生，则 `inserted` 为 true 且 `node` 为空。
* 若插入失败，则 `inserted` 为 false 且 `node` 保留 `nh` 的先前值。
抛出：;; 若异常由调用 `hasher` 之外的操作引发，则该函数无任何效果。
并发性：;; 阻塞于 `*this` 的重哈希。
备注：;; 若 `nh` 非空且其分配器与容器分配器不同，则行为未定义。

---

==== emplace_or_[c]visit
```c++

template<class... Args, class F> bool emplace_or_visit(Args&&... args, F&& f); template<class... Args, class F> bool emplace_or_cvisit(Args&&... args, F&& f);

```

当表中不存在具有等效键的元素时，插入一个由参数 `args` 构造的对象；否则，使用等效元素的常量引用调用 `f`。

[horizontal]
要求：;; `value_type` 需可从 `args` 构造。
返回：;; 若插入发生则为 `true`。
并发性：;; 阻塞于 `*this` 的重哈希。
备注：;; 此接口仅为说明性，因为 C++ 不允许在可变参数包后声明参数 `f`。

---

==== 拷贝 insert_or_[c]visit
```c++

template<class F> bool insert_or_visit(const value_type& obj, F f); template<class F> bool insert_or_cvisit(const value_type& obj, F f);

```

当且仅当表中不存在具有等效键的元素时，插入 `obj`；否则，使用等效元素的常量引用调用 `f`。

[horizontal]
要求：;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入] 要求。
返回：;; 若插入发生则为 `true`。+
并发性：;; 阻塞于 `*this` 的重哈希。

---

==== 移动 insert_or_[c]visit
```c++

template<class F> bool insert_or_visit(value_type&& obj, F f); template<class F> bool insert_or_cvisit(value_type&& obj, F f);

```

当且仅当表中不存在具有等效键的元素时，插入 `obj`；否则，使用等效元素的常量引用调用 `f`。

[horizontal]
要求：;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入] 要求。
返回：;; 若插入发生则为 `true`。+
并发性：;; 阻塞于 `*this` 的重哈希。

---

==== 透明 insert_or_[c]visit
```c++

template<class K, class F> bool insert_or_visit(K&& k, F f); template<class K, class F> bool insert_or_cvisit(K&& k, F f);

```

当且仅当容器中不存在具有等效键的元素时，插入一个由 `std::forward<K>(k)` 构造的元素；否则，使用等效元素的常量引用调用 `f`。

[horizontal]
要求：;; `value_type` 需满足从 `k` 的 https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原位构造] 要求。
返回：;; 若插入发生则为 `true`。
并发性：;; 阻塞于 `*this` 的重哈希。
备注：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，这些重载才会参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== 插入迭代器范围或访问
```c++

template<class InputIterator,class F>
    size_type insert_or_visit(InputIterator first, InputIterator last, F f);
template<class InputIterator,class F>
    size_type insert_or_cvisit(InputIterator first, InputIterator last, F f);

```

等效于
[listing, subs="+macros,+quotes"]
-----
  while(first != last) this->xref:#concurrent_node_set_emplace_or_cvisit[emplace_or_[c\]visit](*first++, f);
-----

[horizontal]
返回：;; 插入的元素数量。

---

==== 插入初始化列表或访问
```c++

template<class F> size_type insert_or_visit(std::initializer_list<value_type> il, F f); template<class F> size_type insert_or_cvisit(std::initializer_list<value_type> il, F f);

```

等效于
[listing, subs="+macros,+quotes"]
-----
  this->xref:#concurrent_node_set_insert_iterator_range_or_visit[insert_or_[c\]visit](il.begin(), il.end(), std::ref(f));
-----

[horizontal]
返回：;; 插入的元素数量。

---

==== 插入节点或访问
```c++

template<class F> insert_return_type insert_or_visit(node_type&& nh, F f); template<class F> insert_return_type insert_or_cvisit(node_type&& nh, F f);

```

若 `nh` 为空，则不执行任何操作。否则，当且仅当表中不存在键等于 `nh.value()` 的元素时，插入关联元素；否则，使用等效元素的常量引用调用 `f`。

[horizontal]
返回：;; 从 `inserted` 和 `node` 构造的 `insert_return_type` 对象：+
* 若 `nh` 为空，则 `inserted` 为 `false` 且 `node` 为空。
* 否则，若插入发生，则 `inserted` 为 true 且 `node` 为空。
* 若插入失败，则 `inserted` 为 false 且 `node` 保留 `nh` 的先前值。
抛出：;; 若由调用 `hasher` 或 `f` 以外的操作引发异常，则函数无效果。
并发性：;; 阻塞于 `*this` 的重哈希。
备注：;; 若 `nh` 非空且其分配器与容器分配器不同，则行为未定义。

---

==== emplace_and_[c]visit
```c++

template<class... Args, class F1, class F2>
  bool emplace_or_visit(Args&&... args, F1&& f1, F2&& f2);
template<class... Args, class F1, class F2>
  bool emplace_or_cvisit(Args&&... args, F1&& f1, F2&& f2);

```

当表中不存在具有等效键的元素时，插入一个由参数 `args` 构造的对象，然后使用新创建元素的常量引用调用 `f1`；否则，使用等效元素的常量引用调用 `f2`。

[horizontal]
要求：;; `value_type` 需可从 `args` 构造。
返回：;; 若插入发生则为 `true`。
并发性：;; 阻塞于 `*this` 的重哈希。
备注：;; 此接口仅为说明性，因为 C++ 不允许在可变参数包后声明参数 `f1` 和 `f2`。

---

==== 拷贝 insert_and_[c]visit
```c++

template<class F1, class F2> bool insert_and_visit(const value_type& obj, F1 f1, F2 f2); template<class F1, class F2> bool insert_and_cvisit(const value_type& obj, F1 f2, F2 f2);

```

当且仅当表中不存在具有等效键的元素时，插入 `obj`，然后使用新创建元素的常量引用调用 `f1`；否则，使用等效元素的常量引用调用 `f`。

[horizontal]
要求：;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入] 要求。
返回：;; 若插入发生则为 `true`。+
并发性：;; 阻塞于 `*this` 的重哈希。

---

==== 移动 insert_and_[c]visit
```c++

template<class F1, class F2> bool insert_and_visit(value_type&& obj, F1 f1, F2 f2); template<class F1, class F2> bool insert_and_cvisit(value_type&& obj, F1 f1, F2 f2);

```

当且仅当表中不存在具有等效键的元素时，插入 `obj`，然后使用新创建元素的常量引用调用 `f1`；否则，使用等效元素的常量引用调用 `f2`。

[horizontal]
要求：;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入] 要求。
返回：;; 若插入发生则为 `true`。+
并发性：;; 阻塞于 `*this` 的重哈希。

---

==== 透明 insert_and_[c]visit
```c++

template<class K, class F1, class F2> bool insert_and_visit(K&& k, F1 f1, F2 f2); template<class K, class F1, class F2> bool insert_and_cvisit(K&& k, F1 f1, F2 f2);

```

当且仅当容器中不存在具有等效键的元素时，插入一个由 `std::forward<K>(k)` 构造的元素，然后使用新创建元素的常量引用调用 `f1`；否则，使用等效元素的常量引用调用 `f2`。

[horizontal]
要求：;; `value_type` 需满足从 `k` 的 https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原位构造] 要求。
返回：;; 若插入发生则为 `true`。
并发性：;; 阻塞于 `*this` 的重哈希。
备注：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，这些重载才会参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== 插入迭代器范围并访问
```c++

template<class InputIterator,class F1, class F2>
    size_type insert_and_visit(InputIterator first, InputIterator last, F1 f1, F2 f2);
template<class InputIterator,class F1, class f2>
    size_type insert_and_cvisit(InputIterator first, InputIterator last, F1 f1, F2 f2);

```

等效于
[listing, subs="+macros,+quotes"]
-----
  while(first != last) this->xref:#concurrent_node_set_emplace_and_cvisit[emplace_and_[c\]visit](*first++, f1, f2);
-----

[horizontal]
返回：;; 插入的元素数量。

---

==== 插入初始化列表并访问
```c++

template<class F1, class F2>
  size_type insert_and_visit(std::initializer_list<value_type> il, F1 f1, F2 f2);
template<class F1, class F2>
  size_type insert_and_cvisit(std::initializer_list<value_type> il, F1 f1, F2 f2);

```

等效于
[listing, subs="+macros,+quotes"]
-----
  this->xref:#concurrent_node_set_insert_iterator_range_and_visit[insert_and_[c\]visit](il.begin(), il.end(), std::ref(f1), std::ref(f2));
-----

[horizontal]
返回：;; 插入的元素数量。

---

==== 插入节点并访问
```c++

template<class F1, class F2>
  insert_return_type insert_and_visit(node_type&& nh, F1 f1, F2 f2);
template<class F1, class F2>
  insert_return_type insert_and_cvisit(node_type&& nh, F1 f1, F2 f2);

```

若 `nh` 为空，则不执行任何操作。否则，当且仅当表中不存在键等于 `nh.value()` 的元素时，插入关联元素，然后使用新插入元素的常量引用调用 `f1`；否则，使用等效元素的常量引用调用 `f2`。

[horizontal]
返回：;; 从 `inserted` 和 `node` 构造的 `insert_return_type` 对象：+
* 若 `nh` 为空，则 `inserted` 为 `false` 且 `node` 为空。
* 否则，若插入发生，则 `inserted` 为 true 且 `node` 为空。
* 若插入失败，则 `inserted` 为 false 且 `node` 保留 `nh` 的先前值。
抛出：;; 若由调用 `hasher`、`f1` 或 `f2` 以外的操作引发异常，则函数无效果。
并发性：;; 阻塞于 `*this` 的重哈希。
备注：;; 若 `nh` 非空且其分配器与容器分配器不同，则行为未定义。

---

==== erase
```c++

size_type erase(const key_type& k); template<class K> size_type erase(const K& k);

```

若存在键等于 `k` 的元素，则擦除该元素。

[horizontal]
返回：;; 擦除的元素数量（0 或 1）。
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才会抛出异常。
备注：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== 按键条件擦除
```c++

template<class F> size_type erase_if(const key_type& k, F f); template<class K, class F> size_type erase_if(const K& k, F f);

```

若存在键等于 `k` 的元素 `x` 且 `f(x)` 为 `true`，则擦除该元素。

[horizontal]
返回：;; 擦除的元素数量（0 或 1）。
抛出：;; 仅当 `hasher`、`key_equal` 或 `f` 抛出异常时才抛出异常。
备注：;; 仅当 `std::is_execution_policy_v<std::remove_cvref_t<ExecutionPolicy>>` 为 `false` 时，`template<class K, class F>` 重载才会参与重载决议。+
+
仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K, class F>` 重载才会参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== erase_if
```c++

template<class F> size_type erase_if(F f);

```

依次使用表中每个元素的引用调用 `f`，并擦除 `f` 返回 `true` 的元素。

[horizontal]
返回：;; 被擦除的元素数量。
抛出：;; 仅当 `f` 抛出异常时才抛出异常。

---

==== 并行条件擦除
```c++

template<class ExecutionPolicy, class F> void erase_if(ExecutionPolicy&& policy, F f);

```

使用表中每个元素的引用调用 `f`，并擦除 `f` 返回 `true` 的元素。执行根据指定的执行策略语义并行化。

[horizontal]
抛出：;; 根据所用执行策略的异常处理机制，如果在 `f` 内抛出异常，可能调用 `std::terminate`。
备注：;; 仅在支持 C++17 并行算法的编译器中可用。+
+
仅当 `std::is_execution_policy_v<std::remove_cvref_t<ExecutionPolicy>>` 为 `true` 时，此重载才会参与重载决议。+
+
不允许非顺序执行策略。

---

==== swap
```c++

void swap(concurrent_node_set& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
           boost::allocator_traits<Allocator>::propagate_on_container_swap::value);

```

交换表的内容与参数。

如果声明了 `Allocator::propagate_on_container_swap` 且 `Allocator::propagate_on_container_swap::value` 为 `true`，则交换表的分配器。否则，使用不相等的分配器进行交换会导致未定义行为。

[horizontal]
抛出：;; 除非 `key_equal` 或 `hasher` 在交换时抛出异常，否则不抛出异常。
并发性：;; 阻塞于 `*this` 和 `other`。

---

==== extract
```c++

node_type extract(const key_type& k); template<class K> node_type extract(K&& k);

```

提取键等价于 `k` 的元素（若存在）。

[horizontal]
返回：;; 包含被提取元素的 `node_type` 对象；若无元素被提取则为空。
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才会抛出异常。
备注：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== 条件提取
```c++

template<class F> node_type extract_if(const key_type& k, F f); template<class K, class F> node_type extract_if(K&& k, F f);

```

若存在键等于 `k` 的元素 `x` 且 `f(x)` 为 `true`，则提取该元素。

[horizontal]
返回：;; 包含被提取元素的 `node_type` 对象；若无元素被提取则为空。
抛出：;; 仅当 `hasher`、`key_equal` 或 `f` 抛出异常时才抛出异常。
备注：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== clear
```c++

void clear() noexcept;

```

擦除表中的所有元素。

[horizontal]
后置条件：;; `size() == 0`, `max_load() >= max_load_factor() * bucket_count()`
并发性：;; 阻塞于 `*this`。

---

==== merge
```c++

template<class H2, class P2>
  size_type merge(concurrent_node_set<Key, H2, P2, Allocator>& source);
template<class H2, class P2>
  size_type merge(concurrent_node_set<Key, H2, P2, Allocator>&& source);

```

将 `source` 中所有键不存在于 `*this` 的元素移动插入到 `*this`，并从 `source` 中擦除这些元素。

[horizontal]
返回：;; 插入的元素数量。
并发性：;; 阻塞于 `*this` 和 `source`。

---

=== 观察器

==== get_allocator
```

allocator_type get_allocator() const noexcept;

```

[horizontal]
返回：;; 表的分配器。

---

==== hash_function
```

hasher hash_function() const;

```

[horizontal]
返回：;; 表的哈希函数。

---

==== key_eq
```

key_equal key_eq() const;

```

[horizontal]
返回：;; 表的键相等谓词。

---

=== 集合操作

==== count
```c++

size_type        count(const key_type& k) const;
template<class K>
  size_type      count(const K& k) const;

```

[horizontal]
返回：;; 键等于 `k` 的元素数量（0 或 1）。
备注：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才会参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。+
+
在存在并发插入操作的情况下，返回值可能无法准确反映执行后表的实际状态。

---

==== contains
```c++

bool             contains(const key_type& k) const;
template<class K>
  bool           contains(const K& k) const;

```

[horizontal]
返回：;; 布尔值，指示表中是否存在键等于 `k` 的元素。
备注：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才会参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。+
+
在存在并发插入操作的情况下，返回值可能无法准确反映执行后表的实际状态。

---
=== 桶接口

==== bucket_count
```c++

size_type bucket_count() const noexcept;

```

[horizontal]
返回：;; 桶数组的大小。

---

=== 哈希策略

==== load_factor
```c++

float load_factor() const noexcept;

```

[horizontal]
返回：;; `static_cast<float>(size())/static_cast<float>(bucket_count())`，若 `bucket_count() == 0` 则为 `0`。

---

==== max_load_factor

```c++

float max_load_factor() const noexcept;

```

[horizontal]
返回：;; 返回表的最大负载因子。

---

==== Set max_load_factor
```c++

void max_load_factor(float z);

```

[horizontal]
效果：;; 无操作（因用户无权更改此参数）。保留此函数以保持与 `boost::unordered_set` 的兼容性。

---


==== max_load

```c++

size_type max_load() const noexcept;

```

[horizontal]
返回：;; 假设不再擦除元素，表在不重哈希的情况下可容纳的最大元素数量。
注意：;; 构造、重哈希或清除后，表的最大负载至少为 `max_load_factor() * bucket_count()`。在高负载条件下擦除元素时，此数值可能减少。+
+
在存在并发插入操作的情况下，返回值可能无法准确反映执行后表的实际状态。

---

==== rehash
```c++

void rehash(size_type n);

```

必要时更改桶数组的大小，使其至少包含 `n` 个桶，且负载因子小于或等于最大负载因子。适用时，此操作将增加或减少与表关联的 `bucket_count()`。

当 `size() == 0` 时，`rehash(0)` 将释放底层桶数组。

[horizontal]
抛出：;; 若引发异常（除非由表的哈希函数或比较函数引发），则函数无效果。
并发性：;; 阻塞于 `*this`。
---

==== reserve
```c++

void reserve(size_type n);

```

等价于 `a.rehash(ceil(n / a.max_load_factor()))`。

与 `rehash` 类似，此函数可用于增加或减少表中的桶数量。

[horizontal]
抛出：;; 若引发异常（除非由表的哈希函数或比较函数引发），则函数无效果。
并发性：;; 阻塞于 `*this`。

---

=== 统计

==== get_stats
```c++

stats get_stats() const;

```

[horizontal]
返回：;; 对表迄今为止执行的插入和查找操作的统计描述。
备注：;; 仅当 xref:reference/stats.adoc#stats[统计计算] xref:concurrent_node_set_boost_unordered_enable_stats[已启用] 时可用。

---

==== reset_stats
```c++

void reset_stats() noexcept;

```

[horizontal]
效果：;; 将表维护的内部统计信息重置为零。
备注：;; 仅当 xref:reference/stats.adoc#stats[统计计算] xref:concurrent_node_set_boost_unordered_enable_stats[已启用] 时可用。

---

=== 推导指引
若以下任一条件为真，则推导指引不参与重载决议：

  - 其具有一个 `InputIterator` 模板参数，且为该参数推导出的类型不符合输入迭代器要求。
  - 其具有一个 `Allocator` 模板参数，且为该参数推导出的类型不符合分配器要求。
  - 其具有一个 `Hash` 模板参数，且为该参数推导出的类型为整数类型或符合分配器要求的类型。
  - 其具有一个 `Pred` 模板参数，且为该参数推导出的类型符合分配器要求。

推导指引中的 `size_type` 参数类型指向由推导指引推导出的容器类型的 `size_type` 成员类型。其默认值与所选构造函数的默认值一致。

==== __迭代器值类型__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-value-type__ =
    typename std::iterator_traits<InputIterator>::value_type; // 仅用于说明
-----

=== 相等比较

==== operator==
```c++

template<class Key, class Hash, class Pred, class Alloc>
  bool operator==(const concurrent_node_set<Key, Hash, Pred, Alloc>& x,
                  const concurrent_node_set<Key, Hash, Pred, Alloc>& y);

```

若 `x.size() == y.size()` 且对于 `x` 中的每个元素，`y` 中均存在具有相同键且值相等（使用 `operator==` 比较值类型）的元素，则返回 `true`。

[horizontal]
并发性：;; 阻塞于 `x` 和 `y`。
备注：;; 若两个表不具有等效的相等谓词，则行为未定义。

---

==== operator!=
```c++

template<class Key, class Hash, class Pred, class Alloc>
  bool operator!=(const concurrent_node_set<Key, Hash, Pred, Alloc>& x,
                  const concurrent_node_set<Key, Hash, Pred, Alloc>& y);

```

若 `x.size() == y.size()` 且对于 `x` 中的每个元素，`y` 中均存在具有相同键且值相等（使用 `operator==` 比较值类型）的元素，则返回 `false`。

[horizontal]
并发性：;; 阻塞于 `x` 和 `y`。
备注：;; 若两个表不具有等效的相等谓词，则行为未定义。

---

=== 交换
```c++

template<class Key, class Hash, class Pred, class Alloc>
  void swap(concurrent_node_set<Key, Hash, Pred, Alloc>& x,
            concurrent_node_set<Key, Hash, Pred, Alloc>& y)
    noexcept(noexcept(x.swap(y)));

```

等效于
[listing, subs="+macros,+quotes"]
-----
x.xref:#concurrent_node_set_swap[swap](y);
-----

---

=== erase_if
```c++

template<class K, class H, class P, class A, class Predicate>
  typename concurrent_node_set<K, H, P, A>::size_type
    erase_if(concurrent_node_set<K, H, P, A>& c, Predicate pred);

```

等效于
[listing, subs="+macros,+quotes"]
-----
c.xref:#concurrent_node_set_erase_if[erase_if](pred);
-----

=== 序列化

``concurrent_node_set`` 可通过 link:../../../../../serialization/index.html[Boost.Serialization^] 使用本库提供的 API 进行归档/检索。支持常规归档和 XML 归档。

==== 将 concurrent_node_set 保存到归档

将 `concurrent_node_set` `x` 的所有元素保存到归档（XML 归档）`ar` 中。

[horizontal]
要求：;; `value_type` 可序列化（XML 可序列化），且支持 Boost.Serialization 的 `save_construct_data`/`load_construct_data` 协议（https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 类型自动支持）。
并发性：;; 阻塞于 `x`。

---

==== 从归档加载 concurrent_node_set

删除 `concurrent_node_set` `x` 的所有预先存在的元素，并从归档（XML 归档）`ar` 中插入原始 `concurrent_node_set` `other` 的元素还原副本，这些元素保存在 `ar` 读取的存储中。

[horizontal]
要求：;; `x.key_equal()` 在功能上等价于 `other.key_equal()`。
并发性：;; 阻塞于 `x`。
