[#concurrent_flat_set]
== 类模板 concurrent++_++flat++_++set

:idprefix: concurrent_flat_set_

`boost::concurrent++_++flat++_++set` —— 一种存储唯一值的哈希表，它支持并发的元素插入、删除、查找及访问操作，且无需外部同步机制。

尽管 `boost::concurrent++_++flat++_++set` 具备容器特性，但它并不符合 C{plus}{plus}标准中的 https://en.cppreference.com/w/cpp/named_req/Container[容器] 概念。具体而言，该容器未提供迭代器及相关操作（如 `begin` 、 `end` 等）。元素访问通过用户提供的__访问函数__实现，这些函数被传递至 `concurrent++_++flat++_++set` 操作中，并在其内部以受控方式执行。这种基于访问机制的 API 设计能够有效支持低争用的并发应用场景。

`boost::concurrent++_++flat++_++set` 的内部数据结构类似于 `boost::unordered++_++flat++_++set` 。由于其采用开放寻址技术， `value++_++type` 必须满足可移动构造要求，且在重哈希过程中无法保持指针稳定性。

=== 概要

[listing, subs="+macros,+quotes"]
-----
// #include xref:reference/header_concurrent_flat_set.adoc[`<boost/unordered/concurrent_flat_set.hpp>`]

namespace boost {
namespace unordered {

  template<class Key,
           class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<Key>>
  class concurrent_flat_set {
  public:
    // 类型
    using key_type             = Key;
    using value_type           = Key;
    using init_type            = Key;
    using hasher               = Hash;
    using key_equal            = Pred;
    using allocator_type       = Allocator;
    using pointer              = typename std::allocator_traits<Allocator>::pointer;
    using const_pointer        = typename std::allocator_traits<Allocator>::const_pointer;
    using reference            = value_type&;
    using const_reference      = const value_type&;
    using size_type            = std::size_t;
    using difference_type      = std::ptrdiff_t;

    using stats                = xref:reference/stats.adoc#stats_stats_type[__stats-type__]; // if statistics are xref:concurrent_flat_set_boost_unordered_enable_stats[enabled]

    // 常量
    static constexpr size_type xref:#concurrent_flat_set_constants[bulk_visit_size] = _implementation-defined_;

    // 构造/复制/销毁
    xref:#concurrent_flat_set_default_constructor[concurrent_flat_set]();
    explicit xref:#concurrent_flat_set_bucket_count_constructor[concurrent_flat_set](size_type n,
                                 const hasher& hf = hasher(),
                                 const key_equal& eql = key_equal(),
                                 const allocator_type& a = allocator_type());
    template<class InputIterator>
      xref:#concurrent_flat_set_iterator_range_constructor[concurrent_flat_set](InputIterator f, InputIterator l,
                          size_type n = _implementation-defined_,
                          const hasher& hf = hasher(),
                          const key_equal& eql = key_equal(),
                          const allocator_type& a = allocator_type());
    xref:#concurrent_flat_set_copy_constructor[concurrent_flat_set](const concurrent_flat_set& other);
    xref:#concurrent_flat_set_move_constructor[concurrent_flat_set](concurrent_flat_set&& other);
    template<class InputIterator>
      xref:#concurrent_flat_set_iterator_range_constructor_with_allocator[concurrent_flat_set](InputIterator f, InputIterator l,const allocator_type& a);
    explicit xref:#concurrent_flat_set_allocator_constructor[concurrent_flat_set](const Allocator& a);
    xref:#concurrent_flat_set_copy_constructor_with_allocator[concurrent_flat_set](const concurrent_flat_set& other, const Allocator& a);
    xref:#concurrent_flat_set_move_constructor_with_allocator[concurrent_flat_set](concurrent_flat_set&& other, const Allocator& a);
    xref:#concurrent_flat_set_move_constructor_from_unordered_flat_set[concurrent_flat_set](unordered_flat_set<Key, Hash, Pred, Allocator>&& other);
    xref:#concurrent_flat_set_initializer_list_constructor[concurrent_flat_set](std::initializer_list<value_type> il,
                        size_type n = _implementation-defined_
                        const hasher& hf = hasher(),
                        const key_equal& eql = key_equal(),
                        const allocator_type& a = allocator_type());
    xref:#concurrent_flat_set_bucket_count_constructor_with_allocator[concurrent_flat_set](size_type n, const allocator_type& a);
    xref:#concurrent_flat_set_bucket_count_constructor_with_hasher_and_allocator[concurrent_flat_set](size_type n, const hasher& hf, const allocator_type& a);
    template<class InputIterator>
      xref:#concurrent_flat_set_iterator_range_constructor_with_bucket_count_and_allocator[concurrent_flat_set](InputIterator f, InputIterator l, size_type n,
                          const allocator_type& a);
    template<class InputIterator>
      xref:#concurrent_flat_set_iterator_range_constructor_with_bucket_count_and_hasher[concurrent_flat_set](InputIterator f, InputIterator l, size_type n, const hasher& hf,
                          const allocator_type& a);
    xref:#concurrent_flat_set_initializer_list_constructor_with_allocator[concurrent_flat_set](std::initializer_list<value_type> il, const allocator_type& a);
    xref:#concurrent_flat_set_initializer_list_constructor_with_bucket_count_and_allocator[concurrent_flat_set](std::initializer_list<value_type> il, size_type n,
                        const allocator_type& a);
    xref:#concurrent_flat_set_initializer_list_constructor_with_bucket_count_and_hasher_and_allocator[concurrent_flat_set](std::initializer_list<value_type> il, size_type n, const hasher& hf,
                        const allocator_type& a);
    xref:#concurrent_flat_set_destructor[~concurrent_flat_set]();
    concurrent_flat_set& xref:#concurrent_flat_set_copy_assignment[operator++=++](const concurrent_flat_set& other);
    concurrent_flat_set& xref:#concurrent_flat_set_move_assignment[operator++=++](concurrent_flat_set&& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
              boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value);
    concurrent_flat_set& xref:#concurrent_flat_set_initializer_list_assignment[operator++=++](std::initializer_list<value_type>);
    allocator_type xref:#concurrent_flat_set_get_allocator[get_allocator]() const noexcept;


    // 访问
    template<class F> size_t xref:#concurrent_flat_set_cvisit[visit](const key_type& k, F f);
    template<class F> size_t xref:#concurrent_flat_set_cvisit[visit](const key_type& k, F f) const;
    template<class F> size_t xref:#concurrent_flat_set_cvisit[cvisit](const key_type& k, F f) const;
    template<class K, class F> size_t xref:#concurrent_flat_set_cvisit[visit](const K& k, F f);
    template<class K, class F> size_t xref:#concurrent_flat_set_cvisit[visit](const K& k, F f) const;
    template<class K, class F> size_t xref:#concurrent_flat_set_cvisit[cvisit](const K& k, F f) const;

    template<class FwdIterator, class F>
      size_t xref:concurrent_flat_set_bulk_visit[visit](FwdIterator first, FwdIterator last, F f);
    template<class FwdIterator, class F>
      size_t xref:concurrent_flat_set_bulk_visit[visit](FwdIterator first, FwdIterator last, F f) const;
    template<class FwdIterator, class F>
      size_t xref:concurrent_flat_set_bulk_visit[cvisit](FwdIterator first, FwdIterator last, F f) const;

    template<class F> size_t xref:#concurrent_flat_set_cvisit_all[visit_all](F f);
    template<class F> size_t xref:#concurrent_flat_set_cvisit_all[visit_all](F f) const;
    template<class F> size_t xref:#concurrent_flat_set_cvisit_all[cvisit_all](F f) const;
    template<class ExecutionPolicy, class F>
      void xref:#concurrent_flat_set_parallel_cvisit_all[visit_all](ExecutionPolicy&& policy, F f);
    template<class ExecutionPolicy, class F>
      void xref:#concurrent_flat_set_parallel_cvisit_all[visit_all](ExecutionPolicy&& policy, F f) const;
    template<class ExecutionPolicy, class F>
      void xref:#concurrent_flat_set_parallel_cvisit_all[cvisit_all](ExecutionPolicy&& policy, F f) const;

    template<class F> bool xref:#concurrent_flat_set_cvisit_while[visit_while](F f);
    template<class F> bool xref:#concurrent_flat_set_cvisit_while[visit_while](F f) const;
    template<class F> bool xref:#concurrent_flat_set_cvisit_while[cvisit_while](F f) const;
    template<class ExecutionPolicy, class F>
      bool xref:#concurrent_flat_set_parallel_cvisit_while[visit_while](ExecutionPolicy&& policy, F f);
    template<class ExecutionPolicy, class F>
      bool xref:#concurrent_flat_set_parallel_cvisit_while[visit_while](ExecutionPolicy&& policy, F f) const;
    template<class ExecutionPolicy, class F>
      bool xref:#concurrent_flat_set_parallel_cvisit_while[cvisit_while](ExecutionPolicy&& policy, F f) const;

    // 容量
    ++[[nodiscard]]++ bool xref:#concurrent_flat_set_empty[empty]() const noexcept;
    size_type xref:#concurrent_flat_set_size[size]() const noexcept;
    size_type xref:#concurrent_flat_set_max_size[max_size]() const noexcept;

    // 修改器
    template<class... Args> bool xref:#concurrent_flat_set_emplace[emplace](Args&&... args);
    bool xref:#concurrent_flat_set_copy_insert[insert](const value_type& obj);
    bool xref:#concurrent_flat_set_move_insert[insert](value_type&& obj);
    template<class K> bool xref:#concurrent_flat_set_transparent_insert[insert](K&& k);
    template<class InputIterator> size_type xref:#concurrent_flat_set_insert_iterator_range[insert](InputIterator first, InputIterator last);
    size_type xref:#concurrent_flat_set_insert_initializer_list[insert](std::initializer_list<value_type> il);

    template<class... Args, class F> bool xref:#concurrent_flat_set_emplace_or_cvisit[emplace_or_visit](Args&&... args, F&& f);
    template<class... Args, class F> bool xref:#concurrent_flat_set_emplace_or_cvisit[emplace_or_cvisit](Args&&... args, F&& f);
    template<class F> bool xref:#concurrent_flat_set_copy_insert_or_cvisit[insert_or_visit](const value_type& obj, F f);
    template<class F> bool xref:#concurrent_flat_set_copy_insert_or_cvisit[insert_or_cvisit](const value_type& obj, F f);
    template<class F> bool xref:#concurrent_flat_set_move_insert_or_cvisit[insert_or_visit](value_type&& obj, F f);
    template<class F> bool xref:#concurrent_flat_set_move_insert_or_cvisit[insert_or_cvisit](value_type&& obj, F f);
    template<class K, class F> bool xref:#concurrent_flat_set_transparent_insert_or_cvisit[insert_or_visit](K&& k, F f);
    template<class K, class F> bool xref:#concurrent_flat_set_transparent_insert_or_cvisit[insert_or_cvisit](K&& k, F f);
    template<class InputIterator,class F>
      size_type xref:#concurrent_flat_set_insert_iterator_range_or_visit[insert_or_visit](InputIterator first, InputIterator last, F f);
    template<class InputIterator,class F>
      size_type xref:#concurrent_flat_set_insert_iterator_range_or_visit[insert_or_cvisit](InputIterator first, InputIterator last, F f);
    template<class F> size_type xref:#concurrent_flat_set_insert_initializer_list_or_visit[insert_or_visit](std::initializer_list<value_type> il, F f);
    template<class F> size_type xref:#concurrent_flat_set_insert_initializer_list_or_visit[insert_or_cvisit](std::initializer_list<value_type> il, F f);

    template<class... Args, class F1, class F2>
      bool xref:#concurrent_flat_set_emplace_and_cvisit[emplace_and_visit](Args&&... args, F1&& f1, F2&& f2);
    template<class... Args, class F1, class F2>
      bool xref:#concurrent_flat_set_emplace_and_cvisit[emplace_and_cvisit](Args&&... args, F1&& f1, F2&& f2);
    template<class F1, class F2> bool xref:#concurrent_flat_set_copy_insert_and_cvisit[insert_and_visit](const value_type& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool xref:#concurrent_flat_set_copy_insert_and_cvisit[insert_and_cvisit](const value_type& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool xref:#concurrent_flat_set_move_insert_and_cvisit[insert_and_visit](value_type&& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool xref:#concurrent_flat_set_move_insert_and_cvisit[insert_and_cvisit](value_type&& obj, F1 f1, F2 f2);
    template<class K, class F1, class F2> bool xref:#concurrent_flat_set_transparent_insert_and_cvisit[insert_and_visit](K&& k, F1 f1, F2 f2);
    template<class K, class F1, class F2> bool xref:#concurrent_flat_set_transparent_insert_and_cvisit[insert_and_cvisit](K&& k, F1 f1, F2 f2);
    template<class InputIterator,class F1, class F2>
      size_type xref:#concurrent_flat_set_insert_iterator_range_and_visit[insert_and_visit](InputIterator first, InputIterator last, F1 f1, F2 f2);
    template<class InputIterator,class F1, class F2>
      size_type xref:#concurrent_flat_set_insert_iterator_range_and_visit[insert_and_cvisit](InputIterator first, InputIterator last, F1 f1, F2 f2);
    template<class F1, class F2>
      size_type xref:#concurrent_flat_set_insert_initializer_list_and_visit[insert_and_visit](std::initializer_list<value_type> il, F1 f1, F2 f2);
    template<class F1, class F2>
      size_type xref:#concurrent_flat_set_insert_initializer_list_and_visit[insert_and_cvisit](std::initializer_list<value_type> il, F1 f1, F2 f2);

    size_type xref:#concurrent_flat_set_erase[erase](const key_type& k);
    template<class K> size_type xref:#concurrent_flat_set_erase[erase](const K& k);

    template<class F> size_type xref:#concurrent_flat_set_erase_if_by_key[erase_if](const key_type& k, F f);
    template<class K, class F> size_type xref:#concurrent_flat_set_erase_if_by_key[erase_if](const K& k, F f);
    template<class F> size_type xref:#concurrent_flat_set_erase_if[erase_if](F f);
    template<class ExecutionPolicy, class  F> void xref:#concurrent_flat_set_parallel_erase_if[erase_if](ExecutionPolicy&& policy, F f);

    void      xref:#concurrent_flat_set_swap[swap](concurrent_flat_set& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
               boost::allocator_traits<Allocator>::propagate_on_container_swap::value);
    void      xref:#concurrent_flat_set_clear[clear]() noexcept;

    template<class H2, class P2>
      size_type xref:#concurrent_flat_set_merge[merge](concurrent_flat_set<Key, H2, P2, Allocator>& source);
    template<class H2, class P2>
      size_type xref:#concurrent_flat_set_merge[merge](concurrent_flat_set<Key, H2, P2, Allocator>&& source);

    // 观察器
    hasher xref:#concurrent_flat_set_hash_function[hash_function]() const;
    key_equal xref:#concurrent_flat_set_key_eq[key_eq]() const;

    // 集合操作
    size_type        xref:#concurrent_flat_set_count[count](const key_type& k) const;
    template<class K>
      size_type      xref:#concurrent_flat_set_count[count](const K& k) const;
    bool             xref:#concurrent_flat_set_contains[contains](const key_type& k) const;
    template<class K>
      bool           xref:#concurrent_flat_set_contains[contains](const K& k) const;

    // 桶接口
    size_type xref:#concurrent_flat_set_bucket_count[bucket_count]() const noexcept;

    // 哈希策略
    float xref:#concurrent_flat_set_load_factor[load_factor]() const noexcept;
    float xref:#concurrent_flat_set_max_load_factor[max_load_factor]() const noexcept;
    void xref:#concurrent_flat_set_set_max_load_factor[max_load_factor](float z);
    size_type xref:#concurrent_flat_set_max_load[max_load]() const noexcept;
    void xref:#concurrent_flat_set_rehash[rehash](size_type n);
    void xref:#concurrent_flat_set_reserve[reserve](size_type n);

    // 统计（若启用）
    stats xref:#concurrent_flat_set_get_stats[get_stats]() const;
    void xref:#concurrent_flat_set_reset_stats[reset_stats]() noexcept;
  };

  // 推导指引
  template<class InputIterator,
           class Hash = boost::hash<xref:#concurrent_flat_set_iter_value_type[__iter-value-type__]<InputIterator>>,
           class Pred = std::equal_to<xref:#concurrent_flat_set_iter_value_type[__iter-value-type__]<InputIterator>>,
           class Allocator = std::allocator<xref:#concurrent_flat_set_iter_value_type[__iter-value-type__]<InputIterator>>>
    concurrent_flat_set(InputIterator, InputIterator, typename xref:#concurrent_flat_set_deduction_guides[__see below__]::size_type = xref:#concurrent_flat_set_deduction_guides[__see below__],
                        Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> concurrent_flat_set<xref:#concurrent_flat_set_iter_value_type[__iter-value-type__]<InputIterator>, Hash, Pred, Allocator>;

  template<class T, class Hash = boost::hash<T>, class Pred = std::equal_to<T>,
           class Allocator = std::allocator<T>>
    concurrent_flat_set(std::initializer_list<T>, typename xref:#concurrent_flat_set_deduction_guides[__see below__]::size_type = xref:#concurrent_flat_set_deduction_guides[__see below__],
                        Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> concurrent_flat_set<T, Hash, Pred, Allocator>;

  template<class InputIterator, class Allocator>
    concurrent_flat_set(InputIterator, InputIterator, typename xref:#concurrent_flat_set_deduction_guides[__see below__]::size_type, Allocator)
      -> concurrent_flat_set<xref:#concurrent_flat_set_iter_value_type[__iter-value-type__]<InputIterator>,
                             boost::hash<xref:#concurrent_flat_set_iter_value_type[__iter-value-type__]<InputIterator>>,
                             std::equal_to<xref:#concurrent_flat_set_iter_value_type[__iter-value-type__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Allocator>
    concurrent_flat_set(InputIterator, InputIterator, Allocator)
      -> concurrent_flat_set<xref:#concurrent_flat_set_iter_value_type[__iter-value-type__]<InputIterator>,
                             boost::hash<xref:#concurrent_flat_set_iter_value_type[__iter-value-type__]<InputIterator>>,
                             std::equal_to<xref:#concurrent_flat_set_iter_value_type[__iter-value-type__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Hash, class Allocator>
    concurrent_flat_set(InputIterator, InputIterator, typename xref:#concurrent_flat_set_deduction_guides[__see below__]::size_type, Hash,
                        Allocator)
      -> concurrent_flat_set<xref:#concurrent_flat_set_iter_value_type[__iter-value-type__]<InputIterator>, Hash,
                             std::equal_to<xref:#concurrent_flat_set_iter_value_type[__iter-value-type__]<InputIterator>>, Allocator>;

  template<class T, class Allocator>
    concurrent_flat_set(std::initializer_list<T>, typename xref:#concurrent_flat_set_deduction_guides[__see below__]::size_type, Allocator)
      -> concurrent_flat_set<T, boost::hash<T>, std::equal_to<T>, Allocator>;

  template<class T, class Allocator>
    concurrent_flat_set(std::initializer_list<T>, Allocator)
      -> concurrent_flat_set<T, boost::hash<T>, std::equal_to<T>, Allocator>;

  template<class T, class Hash, class Allocator>
    concurrent_flat_set(std::initializer_list<T>, typename xref:#concurrent_flat_set_deduction_guides[__see below__]::size_type, Hash, Allocator)
      -> concurrent_flat_set<T, Hash, std::equal_to<T>, Allocator>;

} // 命名空间 unordered
} // 命名空间 boost
-----

---

=== 描述

*模板参数*

[cols="1,1"]
|===

|_键_
|`Key` 必须满足
https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入]
到容器中的要求，且需满足从容器中
https://en.cppreference.com/w/cpp/named_req/Erasable[可擦除] 的要求。

|_Hash_
|一元函数对象类型，用作 `Key` 的哈希函数。它接受一个类型为 `Key`
的参数，并返回一个 `std::size++_++t` 类型的值。

|_谓词_
|二元函数对象，用于在 `Key`
类型的值上建立等价关系。它接受两个类型为 `Key` 的参数，并返回一个 `bool`
类型的值。

|_分配器_
|一种分配器，其值类型与容器的值类型相同。 `std::allocator++_++traits++<++Allocator++>++::pointer`
和 `std::allocator++_++traits++<++Allocator++>++::const++_++pointer`
必须可分别转换为 `value++_++type++*++` 和
`const value++_++type++*++` ，且可从这些类型转换而来。

|===

容器的元素存储在内部的__桶数组__中。元素根据其哈希码被插入到对应的桶中，但如果该桶已被占用（即发生__冲突__），则会使用原始位置附近可用的桶。

桶数组的大小可通过调用 `insert` / `emplace` 自动增加，也可通过调用 `rehash` / `reserve` 进行调整。容器的__负载因子__（元素数量与桶数量的比值）永远不会超过 `max++_++load++_++factor()` ，但在小规模数据情况下，实现可能允许更高的负载因子。

若 link:../../../../../container_hash/doc/html/hash.html#ref_hash_is_avalanchinghash[`hash++_++is++_++avalanching`]`++<++Hash++>++::value` 为 `true` ，则直接使用哈希函数；否则，会添加一个位混合后处理阶段以提高哈希质量，但会牺牲额外的计算成本。

---

=== 并发要求与保证

要求对同一 `Hash` 或 `Pred` 常量实例并发调用 `operator()` 时不得引入数据竞争。对于 `Alloc` （即 `Allocator` 或其重绑定后的任意分配器类型），在同一实例 `al` 上并发调用以下操作时不得引入数据竞争：

* 从 `al` 复制构造重新绑定的分配器
* `std::allocator++_++traits++<++Alloc++>++::allocate`
* `std::allocator++_++traits++<++Alloc++>++::deallocate`
* `std::allocator++_++traits++<++Alloc++>++::construct`
* `std::allocator++_++traits++<++Alloc++>++::destroy`

通常而言，若 `Hash` 、 `Pred` 和 `Allocator` 这些类型不包含状态，或其操作仅涉及对内部数据成员的常量访问，即可满足上述要求。

除析构操作外，对同一个 `concurrent++_++flat++_++set` 实例并发调用任何操作都不会引发数据竞争——即这些操作是线程安全的。

若操作 *op* 显式指定为__阻塞于__ 容器 `x` （其中 `x` 是 `boost::concurrent++_++flat++_++set` 的实例），则先前对 `x` 的阻塞操作将与 *op* 同步。因此，在多线程场景下，对同一 `concurrent++_++flat++_++set` 的阻塞操作将按顺序执行。

若某个操作仅在触发内部重哈希时才会阻塞于 _`x`_，则称该操作__阻塞于 _`x`_ 的重哈希过程__。

当由 `boost::concurrent++_++flat++_++set` 内部执行时，用户提供的访问函数对传入元素的以下操作不会引发数据竞争：

* 对元素的读取访问。
* 对元素的非可变修改。
* 对元素的可变修改：
  ** 在容器接受两个访问函数的操作中，此条件始终适用于第一个访问函数。
  ** 在名称不包含 `cvisit` 的非常量容器函数中，此条件适用于最后一个（或唯一一个）访问函数。

任何插入或修改元素 `e` 的 `boost::concurrent++_++flat++_++set` 操作都会与在 `e` 的内部调用的访问函数同步。

由 `boost::concurrent++_++flat++_++set` `x` 执行的访问函数不允许调用 `x` 上的任何操作；若并发未完成操作不直接或间接访问 `x` ，则允许调用不同 `boost::concurrent++_++flat++_++set` 实例 `y` 上的操作。

---

=== 配置宏

==== `BOOST++_++UNORDERED++_++DISABLE++_++REENTRANCY++_++CHECK`

在调试版本中（更准确地说，当未定义 link:../../../../../assert/doc/html/assert.html#boost_assert_is_void[`BOOST++_++ASSERT++_++IS++_++VOID`] 时），系统会检测__容器重入__行为（即在访问 `m` 元素的函数内部非法调用 `m` 上的操作），并通过 `BOOST++_++ASSERT++_++MSG` 发出信号。若需关注运行时速度，可通过全局定义此宏来禁用该功能。

---

==== `BOOST++_++UNORDERED++_++ENABLE++_++STATS`

全局定义此宏以启用容器的 xref:reference/stats.adoc#stats[统计计算] 功能。请注意，此选项会降低多数操作的总体性能。

---

=== 常量

```cpp

static constexpr size_type bulk_visit_size;

```

在 xref:#concurrent_flat_set_bulk_visit[批量访问] 操作中内部使用的块大小。

=== 构造函数

==== 默认构造函数
```c++

concurrent_flat_set();

```

构造一个空容器，使用 `hasher()` 作为哈希函数， `key++_++equal()` 作为键相等性谓词， `allocator++_++type()` 作为分配器。

[horizontal]
后置条件;; `size() == 0`
要求;; 若使用默认参数，则 `hasher` 、 `key++_++equal` 和 `allocator++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 桶数构造函数
```c++

explicit concurrent_flat_set(size_type n,
                             const hasher& hf = hasher(),
                             const key_equal& eql = key_equal(),
                             const allocator_type& a = allocator_type());

```

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、 `eql` 作为键相等性谓词、 `a` 作为分配器。

[horizontal]
后置条件;; `size() == 0`
要求;; 若使用默认参数，则 `hasher` 、 `key++_++equal` 和 `allocator++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  concurrent_flat_set(InputIterator f, InputIterator l,
                      size_type n = _implementation-defined_,
                      const hasher& hf = hasher(),
                      const key_equal& eql = key_equal(),
                      const allocator_type& a = allocator_type());
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、 `eql` 作为键相等性谓词、 `a` 作为分配器，并将 `++[++f, l)` 范围内的元素插入其中。

[horizontal]
要求;; 若使用默认参数，则 `hasher` 、 `key++_++equal` 和 `allocator++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 复制构造函数
```c++

concurrent_flat_set(concurrent_flat_set const& other);

```

复制构造函数。复制其所包含的元素、哈希函数、谓词及分配器。

若 `Allocator::select++_++on++_++container++_++copy++_++construction` 存在且签名正确，则将根据其结果来构造分配器。

[horizontal]
要求;; `value++_++type` 可复制构造
并发性;; 阻塞于 `other` 。

---

==== 移动构造函数
```c++

concurrent_flat_set(concurrent_flat_set&& other);

```

移动构造函数。该操作将 `other` 的内部桶数组直接转移至新容器，其哈希函数、相等性谓词以及分配器均通过移动构造方式从 `other` 转移而来。若统计功能 xref:#concurrent_flat_set_boost_unordered_enable_stats[启用] ，则同时转移 `other` 的内部统计信息并调用 `other.reset++_++stats()` 。

[horizontal]
并发性;; 阻塞于 `other` 。

---

==== 带分配器的迭代器范围构造函数
```c++

template<class InputIterator>
  concurrent_flat_set(InputIterator f, InputIterator l, const allocator_type& a);

```

构造一个空容器，使用 `a` 作为分配器以及默认的哈希函数和键相等性谓词，并将 `++[++f, l)` 范围内的元素插入其中。

[horizontal]
要求;; `hasher` 、 `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 分配器构造函数
```c++

explicit concurrent_flat_set(Allocator const& a);

```

使用分配器 `a` 构造一个空容器。

---

==== 带分配器的复制构造函数
```c++

concurrent_flat_set(concurrent_flat_set const& other, Allocator const& a);

```

构造一个容器，复制 `other` 中的元素、哈希函数及谓词，但使用分配器 `a` 。

[horizontal]
并发性;; 阻塞于 `other` 。

---

==== 带分配器的移动构造函数
```c++

concurrent_flat_set(concurrent_flat_set&& other, Allocator const& a);

```

若 `a == other.get++_++allocator()` ，则 `other` 中的元素直接转移至新的容器；否则，元素从 `other` 移动构造。哈希函数和相等性谓词从 `other` 移动构造，分配器从 `a` 复制构造。若统计功能 xref:#concurrent_flat_set_boost_unordered_enable_stats[启用] ，当且仅当 `a == other.get++_++allocator()` 时，同步转移 `other` 的内部统计信息，并始终调用 `other.reset++_++stats()` 。

[horizontal]
并发性;; 阻塞于 `other` 。

---

==== 从 unordered++_++flat++_++set 的移动构造函数

```c++

concurrent_flat_set(unordered_flat_set<Key, Hash, Pred, Allocator>&& other);

```

从 xref:#unordered_flat_set[`unordered_flat_set`][`unordered++_++flat++_++set`] 进行移动构造。 `other` 的内部桶数组直接转移至新容器。其哈希函数、相等性谓词和分配器从 `other` 移动构造。若统计功能 xref:#concurrent_flat_set_boost_unordered_enable_stats[启用] ，则转移 `other` 的内部统计信息，并调用 `other.reset++_++stats()` 。

[horizontal]
复杂度;; O(`bucket++_++count()`)

---

==== 初始化列表构造函数
[source, c++, subs="+quotes"]
----
concurrent_flat_set(std::initializer_list<value_type> il,
                    size_type n = _implementation-defined_
                    const hasher& hf = hasher(),
                    const key_equal& eql = key_equal(),
                    const allocator_type& a = allocator_type());
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、 `eql` 作为键相等性谓词、 `a` 作为分配器，并 `il` 中的元素插入其中。

[horizontal]
要求;; 若使用默认参数，则 `hasher` 、 `key++_++equal` 和 `allocator++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带分配器的桶数构造函数
```c++

concurrent_flat_set(size_type n, allocator_type const& a);

```

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、默认的键相等性谓词以及 `a` 作为分配器。

[horizontal]
后置条件;; `size() == 0`
要求;; `hasher` 与 `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带哈希函数和分配器的桶数构造函数
```c++

concurrent_flat_set(size_type n, hasher const& hf, allocator_type const& a);

```

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、默认的键相等性谓词、以及 `a` 作为分配器。

[horizontal]
后置条件;; `size() == 0`
要求;; `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带桶数和分配器的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  concurrent_flat_set(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `a` 作为分配器以及默认的哈希函数和键相等性谓词，并将 `++[++f, l)` 范围内的元素插入其中。

[horizontal]
要求;; `hasher` 、 `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带桶数和哈希函数的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
    template<class InputIterator>
      concurrent_flat_set(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                          const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、 `a` 作为分配器以及默认的键相等性谓词，并将 `++[++f, l)` 范围内的元素插入其中。

[horizontal]
要求;; `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带分配器的初始化列表构造函数

```c++

concurrent_flat_set(std::initializer_list<value_type> il, const allocator_type& a);

```

构造一个空容器，使用 `a` 作为分配器以及默认的哈希函数和键相等性谓词，并将 `il` 中的元素插入其中。

[horizontal]
要求;; `hasher` 与 `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带桶数和分配器的初始化列表构造函数

```c++

concurrent_flat_set(std::initializer_list<value_type> il, size_type n, const allocator_type& a);

```

构造一个空容器，使用 `a` 作为分配器以及默认的哈希函数和键相等性谓词，并将 `il` 中的元素插入其中。

[horizontal]
要求;; `hasher` 与 `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带桶数、哈希函数和分配器的初始化列表构造函数

```c++

concurrent_flat_set(std::initializer_list<value_type> il, size_type n, const hasher& hf,
                    const allocator_type& a);

```

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、 `a` 作为分配器以及默认的键相等性谓词，并将 `il` 中的元素插入其中。

[horizontal]
要求;; `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

=== 析构函数

```c++

~concurrent_flat_set();

```

[horizontal]
备注;; 析构函数会作用于每个元素，并释放所有内存

---

=== 赋值操作

==== 复制赋值

```c++

concurrent_flat_set& operator=(concurrent_flat_set const& other);

```

赋值操作符。该操作会销毁容器中原有的元素，并从 `other` 复制赋值哈希函数与键相等性谓词。若 `Alloc::propagate++_++on++_++container++_++copy++_++assignment` 存在，且 `Alloc::propagate++_++on++_++container++_++copy++_++assignment::value` 为 `true` ，则从 `other` 复制赋值分配器，最后插入 `other` 中所有元素的副本。

[horizontal]
要求;; `value++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入] 要求
并发性;; 阻塞于 `++*++this` 和 `other` 。

---

==== 移动赋值
```c++

concurrent_flat_set& operator=(concurrent_flat_set&& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
           boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value);

```
移动赋值运算符。该操作会销毁容器中先前存在的元素，交换 `other`
的哈希函数和谓词，若
`Alloc::propagate++_++on++_++container++_++move++_++assignment` 存在且
`Alloc::propagate++_++on++_++container++_++move++_++assignment::value`
为 `true` ，则从 `other` 移动赋值分配器。若此时分配器与
`other.get++_++allocator()` 相等，则将 `other` 的内部桶数组直接转移至
`++*++this` ；否则插入 `other`
元素的移动构造副本。若统计功能 xref:#concurrent_flat_set_boost_unordered_enable_stats[启用] ，当且仅当最终分配器与
`other.get++_++allocator()` 相等时，转移内部统计信息，并始终调用
`other.reset++_++stats()` 。

[horizontal]
并发性;; 阻塞于 `++*++this` 和 `other` 。

---

==== 初始化列表赋值
```c++

concurrent_flat_set& operator=(std::initializer_list<value_type> il);

```

从初始化列表中的值赋值。该操作销毁所有原有元素。

[horizontal]
要求;; `value++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入] 要求
并发性;; 阻塞于 `++*++this` 。

---

=== 访问操作

==== ++[++c++]++visit（ ++[++c++]++ 访问）

```c++

template<class F> size_t visit(const key_type& k, F f); template<class F> size_t visit(const key_type& k, F f) const; template<class F> size_t cvisit(const key_type& k, F f) const; template<class K, class F> size_t visit(const K& k, F f); template<class K, class F> size_t visit(const K& k, F f) const; template<class K, class F> size_t cvisit(const K& k, F f) const;

```

若存在键等价于 `k` 的元素 `x` ，则以 `x` 的常量引用调用 `f` 。

[horizontal]
返回值;; 被访问的元素数量（0 或 1）。
备注;; 仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K, class F++>++` 重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

==== 批量访问

```c++

template<class FwdIterator, class F>
  size_t visit(FwdIterator first, FwdIterator last, F f);
template<class FwdIterator, class F>
  size_t visit(FwdIterator first, FwdIterator last, F f) const;
template<class FwdIterator, class F>
  size_t cvisit(FwdIterator first, FwdIterator last, F f) const;

```

对范围 ++[++`first`, `last`) 内的每个元素 `k` ，若容器中存在键等价于 `k` 的元素 `x` ，则使用指向 `x` 的常量引用调用 `f` 。

尽管在功能上等同于对每个键单独调用 xref:#concurrent_flat_set_cvisit[`++[++c++]++visit`] ，但批量访问因内部流线优化而通常具有更快的执行速度。建议 `std::distance(first,last)` 至少达到 xref:#concurrent_flat_set_constants[`bulk++_++visit++_++size`] 以获得性能提升：超过此大小后，性能预计不再提升。

[horizontal]
要求;; `FwdIterator` 需满足 https://en.cppreference.com/w/cpp/named_req/ForwardIterator[LegacyForwardIterator] 要求（C{plus}{plus}11 至 C{plus}{plus}17）或符合 https://en.cppreference.com/w/cpp/iterator/forward_iterator[std::forward++_++iterator] 规范（C{plus}{plus}20 及更高版本）。对于 `K` = `std::iterator++_++traits++<++FwdIterator++>++::value++_++type` ，需满足以下条件之一： `K` 与 `key++_++type` 类型相同，或 `Hash::is++_++transparent` 与 `Pred::is++_++transparent` 均为有效的成员类型别名。对于后一种情况，该库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。该机制支持异构查找，从而避免了实例化 `Key` 类型对象所需的开销。
返回值;; 被访问的元素数量。

---

==== ++[++c++]++visit++_++all

```c++

template<class F> size_t visit_all(F f); template<class F> size_t visit_all(F f) const; template<class F> size_t cvisit_all(F f) const;

```

依次使用指向容器中各元素的常量引用调用 `f` 。

[horizontal]
返回值;; 被访问的元素数量。

---

==== 并行 ++[++c++]++visit++_++all

```c++

template<class ExecutionPolicy, class F> void visit_all(ExecutionPolicy&& policy, F f); template<class ExecutionPolicy, class F> void visit_all(ExecutionPolicy&& policy, F f) const; template<class ExecutionPolicy, class F> void cvisit_all(ExecutionPolicy&& policy, F f) const;

```

根据指定的执行策略语义并行化执行操作；使用指向容器中各元素的常量引用调用 `f` 。

[horizontal]
抛出;; 根据所用执行策略的异常处理机制，若在 `f` 内抛出异常，可能会调用 `std::terminate` 。
备注;; 仅在支持 C{plus}{plus}17 并行算法的编译器中可用。 +
+
仅当 `std::is++_++execution++_++policy++_++v++<++std::remove++_++cvref++_++t++<++ExecutionPolicy++>>++` 为 `true` 时，这些重载才会参与重载决议。 +
+
不允许使用无序执行策略。

---

==== ++[++c++]++visit++_++while

```c++

template<class F> bool visit_while(F f); template<class F> bool visit_while(F f) const; template<class F> bool cvisit_while(F f) const;

```

依次使用指向容器中每个元素的常量引用调用 `f` ，直到 `f` 返回 `false` ，或所有元素均被访问。

[horizontal]
返回值;; 当且仅当 `f` 曾返回 `false` 时，本函数返回 `false` 。

---

==== 并行 ++[++c++]++visit++_++while

```c++

template<class ExecutionPolicy, class F> bool visit_while(ExecutionPolicy&& policy, F f); template<class ExecutionPolicy, class F> bool visit_while(ExecutionPolicy&& policy, F f) const; template<class ExecutionPolicy, class F> bool cvisit_while(ExecutionPolicy&& policy, F f) const;

```

根据指定的执行策略语义并行化执行操作；使用指向容器中各元素的常量引用调用 `f` ，直到 `f` 返回 `false` 或所有元素均被访问完毕。

[horizontal]
返回值;; 当且仅当 `f` 曾返回 `false` 时，本函数返回 `false` 。
抛出;; 根据所用执行策略的异常处理机制，若在 `f` 内抛出异常，可能会调用 `std::terminate` 。
备注;; 仅在支持 C{plus}{plus}17 并行算法的编译器中可用。 +
+
仅当 `std::is++_++execution++_++policy++_++v++<++std::remove++_++cvref++_++t++<++ExecutionPolicy++>>++` 为 `true` 时，这些重载才会参与重载决议。 +
+
不允许使用无序执行策略。 +
+
并行化意味着执行不一定会因 `f` 返回 `false` 而立即结束，因此系统可能继续使用其他元素调用 `f` （即使其返回值同样为 `false` ）。

---

=== 大小与容量

==== 空

```c++

[[nodiscard]] bool empty() const noexcept;

```

[horizontal]
返回值;; `size() == 0`

---

==== 大小

```c++

size_type size() const noexcept;

```

[horizontal]
返回值;; 容器中的元素数量。

[horizontal]
备注;; 在存在并发插入操作的情况下，返回值可能无法准确反映执行完成后容器的真实大小。

---

==== max++_++size

```c++

size_type max_size() const noexcept;

```

[horizontal]
返回值;; 返回该容器可能包含的最大元素数量 `size()` 。

---

=== 修改器

==== 原地构造
```c++

template<class... Args> bool emplace(Args&&... args);

```

当且仅当容器中不存在具有等效键的元素时，插入一个由参数 `args` 构造的对象。

[horizontal]
要求;; `value++_++type` 必须能够通过 `args` 构造。
返回值;; 若插入操作发生，则返回 `true` 。
并发性;; 阻塞于 `++*++this` 的重哈希。
备注;; 若触发重哈希操作，则使指向元素的指针和引用失效。

---

==== 复制插入
```c++

bool insert(const value_type& obj);

```

当且仅当表中不存在等价键的元素时，插入 `obj` 。

[horizontal]
要求;; `value++_++type` 必须满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入] 要求。
返回值;; 若插入操作发生，则返回 `true` 。 +
并发性;; 阻塞于 `++*++this` 的重哈希。
备注;; 若触发重哈希操作，则使指向元素的指针和引用失效。

---

==== 移动插入
```c++

bool insert(value_type&& obj);

```

当且仅当表中不存在等价键的元素时，插入 `obj` 。

[horizontal]
要求;; `value++_++type` 必须满足 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入] 要求。
返回值;; 若插入操作发生，则返回 `true` 。
并发性;; 阻塞于 `++*++this` 的重哈希。
备注;; 若触发重哈希操作，则使指向元素的指针和引用失效。

---

==== 透明插入
```c++

template<class K> bool insert(K&& k);

```

当且仅当容器中不存在等价键的元素时，插入一个由 `std::forward++<++K++>++(k)` 构造的元素。

[horizontal]
要求;; `value++_++type` 必须满足从 `k` 参数 https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原位构造] 的要求。
返回值;; 若插入操作发生，则返回 `true` 。
并发性;; 阻塞于 `++*++this` 的重哈希。
备注;; 若触发重哈希操作，则使指向元素的指针和引用失效。 +
+
仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent` 均为有效的成员类型别名时，此重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

==== 迭代器范围插入
```c++

template<class InputIterator> size_type insert(InputIterator first, InputIterator last);

```

等价于：
[listing, subs="+macros,+quotes"]
-----
  while(first != last) this->xref:#concurrent_flat_set_emplace[emplace](*first++);
-----

[horizontal]
返回值;; 被插入的元素数量。

---

==== 初始化列表插入
```c++

size_type insert(std::initializer_list<value_type> il);

```

等价于：
[listing, subs="+macros,+quotes"]
-----
  this->xref:#concurrent_flat_set_insert_iterator_range[insert](il.begin(), il.end());
-----

[horizontal]
返回值;; 被插入的元素数量。

---

==== emplace++_++or++_[++c++]++visit
```c++

template<class... Args, class F> bool emplace_or_visit(Args&&... args, F&& f); template<class... Args, class F> bool emplace_or_cvisit(Args&&... args, F&& f);

```

当容器中不存在具有等效键的元素时，插入一个由参数 `args` 构造的对象；否则，使用指向等效元素的常量引用调用 `f` 。

[horizontal]
要求;; `value++_++type` 必须能够通过 `args` 构造。
返回值;; 若插入操作发生，则返回 `true` 。
并发性;; 阻塞于 `++*++this` 的重哈希。
备注;; 若触发重哈希操作，则使指向元素的指针和引用失效。 +
+
此接口仅为说明，因 C{plus}{plus} 不允许在可变参数包后声明参数 `f` 。

---

==== 复制 insert++_++or++_[++c++]++visit
```c++

template<class F> bool insert_or_visit(const value_type& obj, F f); template<class F> bool insert_or_cvisit(const value_type& obj, F f);

```

当且仅当容器中不存在具有等效键的元素时，插入 `obj` ；否则，使用指向等效元素的常量引用调用 `f` 。

[horizontal]
要求;; `value++_++type` 必须满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入] 要求。
返回值;; 若插入操作发生，则返回 `true` 。 +
并发性;; 阻塞于 `++*++this` 的重哈希。
备注;; 若触发重哈希操作，则使指向元素的指针和引用失效。

---

==== 移动 insert++_++or++_[++c++]++visit
```c++

template<class F> bool insert_or_visit(value_type&& obj, F f); template<class F> bool insert_or_cvisit(value_type&& obj, F f);

```

当且仅当容器中不存在具有等效键的元素时，插入 `obj` ；否则，使用指向等效元素的常量引用调用 `f` 。

[horizontal]
要求;; `value++_++type` 必须满足 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入] 要求。
返回值;; 若插入操作发生，则返回 `true` 。 +
并发性;; 阻塞于 `++*++this` 的重哈希。
备注;; 若触发重哈希操作，则使指向元素的指针和引用失效。

---

==== 透明 insert++_++or++_[++c++]++visit
```c++

template<class K, class F> bool insert_or_visit(K&& k, F f); template<class K, class F> bool insert_or_cvisit(K&& k, F f);

```

当且仅当容器中不存在具有等效键的元素时，插入由 `std::forward++<++K++>++(k)` 构造的元素；否则，使用指向等效元素的常量引用调用 `f` 。

[horizontal]
要求;; `value++_++type` 必须满足从 `k` 参数 https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原位构造] 的要求。
返回值;; 若插入操作发生，则返回 `true` 。
并发性;; 阻塞于 `++*++this` 的重哈希。
备注;; 若触发重哈希操作，则使指向元素的指针和引用失效。 +
+
仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent` 均为有效的成员类型别名时，这些重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

==== 迭代器范围插入或访问
```c++

template<class InputIterator,class F>
    size_type insert_or_visit(InputIterator first, InputIterator last, F f);
template<class InputIterator,class F>
    size_type insert_or_cvisit(InputIterator first, InputIterator last, F f);

```

等价于：
[listing, subs="+macros,+quotes"]
-----
  while(first != last) this->xref:#concurrent_flat_set_emplace_or_cvisit[emplace_or_[c\]visit](*first++, f);
-----

[horizontal]
返回值;; 被插入的元素数量。

---

==== 初始化列表插入或访问
```c++

template<class F> size_type insert_or_visit(std::initializer_list<value_type> il, F f); template<class F> size_type insert_or_cvisit(std::initializer_list<value_type> il, F f);

```

等价于：
[listing, subs="+macros,+quotes"]
-----
  this->xref:#concurrent_flat_set_insert_iterator_range_or_visit[insert_or_[c\]visit](il.begin(), il.end(), std::ref(f));
-----

[horizontal]
返回值;; 被插入的元素数量。

---

==== emplace++_++and++_[++c++]++visit
```c++

template<class... Args, class F1, class F2>
  bool emplace_and_visit(Args&&... args, F1&& f1, F2&& f2);
template<class... Args, class F1, class F2>
  bool emplace_and_cvisit(Args&&... args, F1&& f1, F2&& f2);

```

当容器中不存在具有等效键的元素时，插入由参数 `args` 构造的对象，并使用指向新创建元素的常量引用调用 `f1` ；否则，使用指向等效元素的常量引用调用 `f2` 。

[horizontal]
要求;; `value++_++type` 必须能够通过 `args` 构造。
返回值;; 若插入操作发生，则返回 `true` 。
并发性;; 阻塞于 `++*++this` 的重哈希。
备注;; 若触发重哈希操作，则使指向元素的指针和引用失效。 +
+
此接口仅为说明，因为 C{plus}{plus} 不允许在可变参数包后声明参数 `f1` 和 `f2` 。

---

==== 复制 insert++_++and++_[++c++]++visit
```c++

template<class F1, class F2> bool insert_and_visit(const value_type& obj, F1 f1, F2 f2); template<class F1, class F2> bool insert_and_cvisit(const value_type& obj, F1 f1, F2 f2);

```

当且仅当容器中不存在具有等效键的元素时，插入 `obj` 并使用指向新创建元素的常量引用调用 `f1` ；否则，使用指向等价元素的常量引用调用 `f` 。

[horizontal]
要求;; `value++_++type` 必须满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入] 要求。
返回值;; 若插入操作发生，则返回 `true` 。 +
并发性;; 阻塞于 `++*++this` 的重哈希。
备注;; 若触发重哈希操作，则使指向元素的指针和引用失效。

---

==== 移动 insert++_++and++_[++c++]++visit
```c++

template<class F1, class F2> bool insert_and_visit(value_type&& obj, F1 f1, F2 f2); template<class F1, class F2> bool insert_and_cvisit(value_type&& obj, F1 f1, F2 f2);

```

当且仅当容器中不存在具有等效键的元素时，插入 `obj` 并使用指向新创建元素的常量引用调用 `f1` ；否则，使用指向等价元素的常量引用调用 `f` 。

[horizontal]
要求;; `value++_++type` 必须满足 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入] 要求。
返回值;; 若插入操作发生，则返回 `true` 。 +
并发性;; 阻塞于 `++*++this` 的重哈希。
备注;; 若触发重哈希操作，则使指向元素的指针和引用失效。

---

==== 透明 insert++_++and++_[++c++]++visit（透明插入并 ++[++c++]++ 访问）
```c++

template<class K, class F1, class F2> bool insert_and_visit(K&& k, F1 f1, F2 f2); template<class K, class F1, class F2> bool insert_and_cvisit(K&& k, F1 f1, F2 f2);

```

当且仅当容器中不存在具有等效键的元素时，插入由 `std::forward++<++K++>++(k)` 构造的元素，并使用指向新创建元素的常量引用调用 `f1` ；否则，使用指向等效元素的常量引用调用 `f2` 。

[horizontal]
要求;; `value++_++type` 必须满足从 `k` 参数 https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原位构造] 的要求。
返回值;; 若插入操作发生，则返回 `true` 。
并发性;; 阻塞于 `++*++this` 的重哈希。
备注;; 若触发重哈希操作，则使指向元素的指针和引用失效。 +
+
仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent` 均为有效的成员类型别名时，这些重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

==== 迭代器范围插入并访问
```c++

template<class InputIterator,class F1, class F2>
    size_type insert_and_visit(InputIterator first, InputIterator last, F1 f1, F2 f2);
template<class InputIterator,class F1, class F2>
    size_type insert_and_cvisit(InputIterator first, InputIterator last, F1 f1, F2 f2);

```

等价于：
[listing, subs="+macros,+quotes"]
-----
  while(first != last) this->xref:#concurrent_flat_set_emplace_and_cvisit[emplace_and_[c\]visit](*first++, f1, f2);
-----

[horizontal]
返回值;; 被插入的元素数量。

---

==== 初始化列表插入并访问
```c++

template<class F1, class F2>
  size_type insert_and_visit(std::initializer_list<value_type> il, F1 f1, F2 f2);
template<class F1, class F2>
  size_type insert_and_cvisit(std::initializer_list<value_type> il, F1 f1, F2 f2);

```

等价于：
[listing, subs="+macros,+quotes"]
-----
  this->xref:#concurrent_flat_set_insert_iterator_range_and_visit[insert_and_[c\]visit](il.begin(), il.end(), std::ref(f1), std::ref(f2));
-----

[horizontal]
返回值;; 被插入的元素数量。

---

==== 擦除
```c++

size_type erase(const key_type& k); template<class K> size_type erase(const K& k);

```

若存在键等价于 `k` 的元素，则擦除该元素。

[horizontal]
返回值;; 被擦除的元素数量（0 或 1）。
抛出;; 仅当 `hasher` 或 `key++_++equal` 抛出异常时，本函数才会抛出异常。
备注;; 仅当 `Hash::is++_++transparent` 与 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K++>++` 重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 类型调用，且 `Pred` 为透明谓词。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

==== 通过键进行条件擦除
```c++

template<class F> size_type erase_if(const key_type& k, F f); template<class K, class F> size_type erase_if(const K& k, F f);

```

若存在键等价于 `k` 的元素 `x` ，且 `f(x)` 为 `true` ，则擦除该元素。

[horizontal]
返回值;; 被擦除的元素数量（0 或 1）。
抛出;; 仅当 `hasher` 、 `key++_++equal` 或 `f` 抛出异常时，本函数才会抛出异常。
备注;; 仅当 `std::is++_++execution++_++policy++_++v++<++std::remove++_++cvref++_++t++<++ExecutionPolicy++>>++` 为 `false` 时， `template++<++class K, class F++>++` 重载才会参与重载决议。 +
+
仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K, class F++>++` 重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

==== 条件擦除
```c++

template<class F> size_type erase_if(F f);

```

依次使用指向容器中各元素的引用调用 `f` ，并擦除其中使 `f` 返回 `true` 的元素。

[horizontal]
返回值;; 被擦除的元素数量。
抛出;; 仅当 `f` 抛出异常时，才会抛出异常。

---

==== 并行条件擦除
```c++

template<class ExecutionPolicy, class F> void erase_if(ExecutionPolicy&& policy, F f);

```

使用指向容器中每个元素的引用调用 `f` ，并擦除其中使 `f` 返回 `true` 的元素。该执行根据指定的执行策略语义并行化。

[horizontal]
抛出;; 根据所用执行策略的异常处理机制，若在 `f` 内抛出异常，可能会调用 `std::terminate` 。
备注;; 仅在支持 C{plus}{plus}17 并行算法的编译器中可用。 +
+
仅当 `std::is++_++execution++_++policy++_++v++<++std::remove++_++cvref++_++t++<++ExecutionPolicy++>>++` 为 `true` 时，此重载才会参与重载决议。 +
+
不允许使用无序执行策略。

---

==== 交换
```c++

void swap(concurrent_flat_set& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
           boost::allocator_traits<Allocator>::propagate_on_container_swap::value);

```

交换容器与参数的内容。

若 `Allocator::propagate++_++on++_++container++_++swap` 已声明， 且其 `value` 为 `true` ，则交换容器的分配器；否则，在分配器不相等的情况下进行交换将导致未定义行为。

[horizontal]
抛出;; 除非 `key++_++equal` 或 `hasher` 在交换时抛出异常，否则不会抛出任何异常。
并发性;; 阻塞于 `++*++this` 和 `other` 。

---

==== 清空
```c++

void clear() noexcept;

```

擦除容器中所有元素。

[horizontal]
后置条件;; `size() == 0` ， `max++_++load() ++>++= max++_++load++_++factor() ++*++ bucket++_++count()`
并发性;; 阻塞于 `++*++this` 。

---

==== 合并
```c++

template<class H2, class P2>
  size_type merge(concurrent_flat_set<Key, H2, P2, Allocator>& source);
template<class H2, class P2>
  size_type merge(concurrent_flat_set<Key, H2, P2, Allocator>&& source);

```

对 `source` 中所有键不在 `++*++this` 中的元素执行移动插入操作，并将这些元素从 `source` 中擦除。

[horizontal]
返回值;; 被插入的元素数量。
并发性;; 阻塞于 `++*++this` 和 `source` 。

---

=== 观察器

==== get++_++allocator
```

allocator_type get_allocator() const noexcept;

```

[horizontal]
返回值;; 容器的分配器。

---

==== 哈希函数
```

hasher hash_function() const;

```

[horizontal]
返回值;; 容器的哈希函数。

---

==== key++_++eq
```

key_equal key_eq() const;

```

[horizontal]
返回值;; 容器的键相等性谓词。

---

=== 集合操作

==== count
```c++

size_type        count(const key_type& k) const;
template<class K>
  size_type      count(const K& k) const;

```

[horizontal]
返回值;; 键等价于 `k` 的元素数量（0 或 1）。
备注;; 仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K++>++` 重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。 +
+
在存在并发插入操作的情况下，返回值可能无法准确反映执行完成后容器的真实状态。

---

==== 包含
```c++

bool             contains(const key_type& k) const;
template<class K>
  bool           contains(const K& k) const;

```

[horizontal]
返回值;; 返回布尔值，表示容器中是否存在键等于 `k` 的元素。
备注;; 仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K++>++` 重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。 +
+
在存在并发插入操作的情况下，返回值可能无法准确反映执行完成后容器的真实状态。

---
=== 桶接口

==== bucket++_++count
```c++

size_type bucket_count() const noexcept;

```

[horizontal]
返回值;; 桶数组的大小。

---

=== 哈希策略

==== 负载因子
```c++

float load_factor() const noexcept;

```

[horizontal]
返回值;; 返回 `static++_++cast++<++float++>++(size())/static++_++cast++<++float++>++(bucket++_++count())` ，若 `bucket++_++count() == 0` ， 则返回 `0` 。

---

==== max++_++load++_++factor（最大负载因子）

```c++

float max_load_factor() const noexcept;

```

[horizontal]
返回值;; 返回容器的最大负载因子。

---

==== 设置最大负载因子
```c++

void max_load_factor(float z);

```

[horizontal]
效果;; 不执行任何操作，因为用户不允许修改此参数。保留此接口是为了与 `boost::unordered++_++set` 保持兼容。

---


==== max++_++load（最大负载）

```c++

size_type max_load() const noexcept;

```

[horizontal]
返回值;; 返回容器在无需重哈希的情况下所能容纳的最大元素数量（假设后续无元素被删除）。
备注;; 在构造、重哈希或清空操作后，容器的最大负载至少为 `max++_++load++_++factor() ++*++ bucket++_++count()` 。在高负载条件下执行擦除操作时，此数值可能会降低。 +
+
在存在并发插入操作的情况下，返回值可能无法准确反映执行完成后容器的真实状态。

---

==== 重哈希
```c++

void rehash(size_type n);

```

如有必要，将改变桶数组的大小，使其至少包含 `n` 个桶，并确保负载因子小于或等于最大负载因子。此操作将根据情况增加或减少容器的 `bucket++_++count()` 。

当 `size() == 0` 时， `rehash(0)` 将释放底层桶数组。

使指向元素的指针和引用失效，并改变元素的顺序。

[horizontal]
抛出;; 若发生异常，除非异常由容器的哈希函数或比较函数抛出，否则此函数不产生任何效果。
并发性;; 阻塞于 `++*++this` 。
---

==== 保留
```c++

void reserve(size_type n);

```

等价于 `a.rehash(ceil(n / a.max++_++load++_++factor()))` 。

与 `rehash` 类似，此函数可用于增加或减少容器中的桶数量。

使指向元素的指针和引用失效，并改变元素的顺序。

[horizontal]
抛出;; 若发生异常，除非异常由容器的哈希函数或比较函数抛出，否则此函数不产生任何效果。
并发性;; 阻塞于 `++*++this` 。

---

=== 统计信息

==== get++_++stats
```c++

stats get_stats() const;

```

[horizontal]
返回值;; 返回容器截至目前所执行的插入与查找操作的统计信息。
备注;; 仅当 xref:reference/stats.adoc#stats[统计计算] 被 xref:#concurrent_flat_set_boost_unordered_enable_stats[启用] 时可用。

---

==== reset++_++stats
```c++

void reset_stats() noexcept;

```

[horizontal]
效果;; 将容器所保存的内部统计信息重置为零。
备注;; 仅当 xref:reference/stats.adoc#stats[统计计算] 被 xref:#concurrent_flat_set_boost_unordered_enable_stats[启用] 时可用。

---

=== 推导指引
如果以下任何一条件为真，则推导指引将不参与重载决议：

  - 该推导指引包含 `InputIterator` 模板参数，且为此参数推导出的类型不符合输入迭代器的要求。
  - 该推导指引包含 `Allocator` 模板参数，且为该参数推导出的类型不符合分配器要求。
  - 该推导指引包含 `Hash` 模板参数，且为该参数推导出的类型为整型或符合分配器要求。
  - 该推导指引包含 `Pred` 模板参数，且为该参数推导出的类型符合分配器要求。

推导指引中的 `size++_++type` 参数类型，指向由该推导指引所推导容器类型的 `size++_++type` 成员类型。其默认值与所选构造函数的默认值一致。

==== _iter-value-type_
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-value-type__ =
    typename std::iterator_traits<InputIterator>::value_type; // exposition only
-----

=== 相等性比较

==== operator==
```c++

template<class Key, class Hash, class Pred, class Alloc>
  bool operator==(const concurrent_flat_set<Key, Hash, Pred, Alloc>& x,
                  const concurrent_flat_set<Key, Hash, Pred, Alloc>& y);

```

若 `x.size() == y.size()` ，且对于 `x` 中的每个元素， `y` 中均存在一个具有相同键和相等值的元素（使用 `operator==` 比较值类型），则返回 `true` 。

[horizontal]
并发性;; 阻塞于 `x` 和 `y` 。
备注;; 若两个容器的相等性谓词不等价，则行为未定义。

---

==== operator!=
```c++

template<class Key, class Hash, class Pred, class Alloc>
  bool operator!=(const concurrent_flat_set<Key, Hash, Pred, Alloc>& x,
                  const concurrent_flat_set<Key, Hash, Pred, Alloc>& y);

```

若 `x.size() == y.size()` ，并且对于 `x` 中的每个元素， `y` 中均存在一个具有相同键和相等值的元素（使用 `operator==` 比较值类型），则返回 `false` 。

[horizontal]
并发性;; 阻塞于 `x` 和 `y` 。
备注;; 若两个容器的相等性谓词不等价，则行为未定义。

---

=== 交换
```c++

template<class Key, class Hash, class Pred, class Alloc>
  void swap(concurrent_flat_set<Key, Hash, Pred, Alloc>& x,
            concurrent_flat_set<Key, Hash, Pred, Alloc>& y)
    noexcept(noexcept(x.swap(y)));

```

等价于：
[listing, subs="+macros,+quotes"]
-----
x.xref:#concurrent_flat_set_swap[swap](y);
-----

---

=== 条件擦除
```c++

template<class K, class H, class P, class A, class Predicate>
  typename concurrent_flat_set<K, H, P, A>::size_type
    erase_if(concurrent_flat_set<K, H, P, A>& c, Predicate pred);

```

等价于：
[listing, subs="+macros,+quotes"]
-----
c.xref:#concurrent_flat_set_erase_if[erase_if](pred);
-----

=== 序列化

可通过本库提供的 API ，借助 link:../../../../../serialization/index.html[Boost.Serialization] 实现档归档/检索 `concurrent++_++flat++_++set` 。同时支持常规格式与 XML 格式的归档文件。

==== 将 concurrent++_++flat++_++set 保存到归档

将 `concurrent++_++flat++_++set` 容器 `x` 的所有元素保存到归档（XML 归档） `ar` 中。

[horizontal]
要求;; `value++_++type` 必须可序列化（支持 XML 序列化），且需要支持 Boost.Serialization 的 `save++_++construct++_++data` / `load++_++construct++_++data` 协议（该协议自动支持满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求的类型）。
并发性;; 阻塞于 `x` 。

---

==== 从归档加载 concurrent++_++flat++_++set

删除 `concurrent++_++flat++_++set` 容器 `x` 中的所有现有元素，并从归档 `ar` （XML格式归档）中读取原始 `concurrent++_++flat++_++set` 容器 `other` 保存的元素副本并插入到 `x` 。

[horizontal]
要求;; `x.key++_++equal()` 需要在功能上等价于 `other.key++_++equal()` 。
并发性;; 阻塞于 `x` 。
