[#unordered_node_set]
== Class Template unordered_node_set

:idprefix: unordered_node_set_

`boost::unordered_node_set` — A node-based, open-addressing unordered associative container that stores unique values.

`boost::unordered_node_set` uses an open-addressing layout like `boost::unordered_flat_set`, but, being node-based, it provides pointer stability and node handling functionalities. Its performance lies between those of `boost::unordered_set` and `boost::unordered_flat_set`.

As a result of its using open addressing, the interface of `boost::unordered_node_set` deviates in a number of aspects from that of `boost::unordered_set`/`std::unordered_set`:

  - `begin()` is not constant-time.
  - There is no API for bucket handling (except `bucket_count`).
  - The maximum load factor of the container is managed internally and can't be set by the user.

Other than this, `boost::unordered_node_set` is mostly a drop-in replacement of standard unordered associative containers.

=== 概要

[listing, subs="+macros,+quotes"]
-----
// #include xref:reference/header_unordered_node_set.adoc[`<boost/unordered/unordered_node_set.hpp>`]

namespace boost {
namespace unordered {

  template<class Key,
           class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<Key>>
  class unordered_node_set {
  public:
    // types
    using key_type             = Key;
    using value_type           = Key;
    using init_type            = Key;
    using hasher               = Hash;
    using key_equal            = Pred;
    using allocator_type       = Allocator;
    using pointer              = typename std::allocator_traits<Allocator>::pointer;
    using const_pointer        = typename std::allocator_traits<Allocator>::const_pointer;
    using reference            = value_type&;
    using const_reference      = const value_type&;
    using size_type            = std::size_t;
    using difference_type      = std::ptrdiff_t;

    using iterator             = _implementation-defined_;
    using const_iterator       = _implementation-defined_;

    using node_type            = _implementation-defined_;
    using insert_return_type   = _implementation-defined_;

    using stats                = xref:reference/stats.adoc#stats_stats_type[__stats-type__]; // if statistics are xref:unordered_node_set_boost_unordered_enable_stats[enabled]

    // construct/copy/destroy
    xref:#unordered_node_set_default_constructor[unordered_node_set]();
    explicit xref:#unordered_node_set_bucket_count_constructor[unordered_node_set](size_type n,
                                const hasher& hf = hasher(),
                                const key_equal& eql = key_equal(),
                                const allocator_type& a = allocator_type());
    template<class InputIterator>
      xref:#unordered_node_set_iterator_range_constructor[unordered_node_set](InputIterator f, InputIterator l,
                         size_type n = _implementation-defined_,
                         const hasher& hf = hasher(),
                         const key_equal& eql = key_equal(),
                         const allocator_type& a = allocator_type());
    xref:#unordered_node_set_copy_constructor[unordered_node_set](const unordered_node_set& other);
    xref:#unordered_node_set_move_constructor[unordered_node_set](unordered_node_set&& other);
    template<class InputIterator>
      xref:#unordered_node_set_iterator_range_constructor_with_allocator[unordered_node_set](InputIterator f, InputIterator l, const allocator_type& a);
    explicit xref:#unordered_node_set_allocator_constructor[unordered_node_set](const Allocator& a);
    xref:#unordered_node_set_copy_constructor_with_allocator[unordered_node_set](const unordered_node_set& other, const Allocator& a);
    xref:#unordered_node_set_move_constructor_with_allocator[unordered_node_set](unordered_node_set&& other, const Allocator& a);
    xref:#unordered_node_set_move_constructor_from_concurrent_node_set[unordered_node_set](concurrent_node_set<Key, Hash, Pred, Allocator>&& other);
    xref:#unordered_node_set_initializer_list_constructor[unordered_node_set](std::initializer_list<value_type> il,
                       size_type n = _implementation-defined_
                       const hasher& hf = hasher(),
                       const key_equal& eql = key_equal(),
                       const allocator_type& a = allocator_type());
    xref:#unordered_node_set_bucket_count_constructor_with_allocator[unordered_node_set](size_type n, const allocator_type& a);
    xref:#unordered_node_set_bucket_count_constructor_with_hasher_and_allocator[unordered_node_set](size_type n, const hasher& hf, const allocator_type& a);
    template<class InputIterator>
      xref:#unordered_node_set_iterator_range_constructor_with_bucket_count_and_allocator[unordered_node_set](InputIterator f, InputIterator l, size_type n, const allocator_type& a);
    template<class InputIterator>
      xref:#unordered_node_set_iterator_range_constructor_with_bucket_count_and_hasher[unordered_node_set](InputIterator f, InputIterator l, size_type n, const hasher& hf,
                         const allocator_type& a);
    xref:#unordered_node_set_initializer_list_constructor_with_allocator[unordered_node_set](std::initializer_list<value_type> il, const allocator_type& a);
    xref:#unordered_node_set_initializer_list_constructor_with_bucket_count_and_allocator[unordered_node_set](std::initializer_list<value_type> il, size_type n,
                       const allocator_type& a);
    xref:#unordered_node_set_initializer_list_constructor_with_bucket_count_and_hasher_and_allocator[unordered_node_set](std::initializer_list<value_type> il, size_type n, const hasher& hf,
                       const allocator_type& a);
    xref:#unordered_node_set_destructor[~unordered_node_set]();
    unordered_node_set& xref:#unordered_node_set_copy_assignment[operator++=++](const unordered_node_set& other);
    unordered_node_set& xref:#unordered_node_set_move_assignment[operator++=++](unordered_node_set&& other) ++noexcept(
      (boost::allocator_traits<Allocator>::is_always_equal::value ||
       boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value) &&
       std::is_same<pointer, value_type*>::value);++
    unordered_node_set& xref:#unordered_node_set_initializer_list_assignment[operator++=++](std::initializer_list<value_type>);
    allocator_type xref:#unordered_node_set_get_allocator[get_allocator]() const noexcept;

    // iterators
    iterator       xref:#unordered_node_set_begin[begin]() noexcept;
    const_iterator xref:#unordered_node_set_begin[begin]() const noexcept;
    iterator       xref:#unordered_node_set_end[end]() noexcept;
    const_iterator xref:#unordered_node_set_end[end]() const noexcept;
    const_iterator xref:#unordered_node_set_cbegin[cbegin]() const noexcept;
    const_iterator xref:#unordered_node_set_cend[cend]() const noexcept;

    // capacity
    ++[[nodiscard]]++ bool xref:#unordered_node_set_empty[empty]() const noexcept;
    size_type xref:#unordered_node_set_size[size]() const noexcept;
    size_type xref:#unordered_node_set_max_size[max_size]() const noexcept;

    // modifiers
    template<class... Args> std::pair<iterator, bool> xref:#unordered_node_set_emplace[emplace](Args&&... args);
    template<class... Args> iterator xref:#unordered_node_set_emplace_hint[emplace_hint](const_iterator position, Args&&... args);
    std::pair<iterator, bool> xref:#unordered_node_set_copy_insert[insert](const value_type& obj);
    std::pair<iterator, bool> xref:#unordered_node_set_move_insert[insert](value_type&& obj);
    template<class K> std::pair<iterator, bool> xref:#unordered_node_set_transparent_insert[insert](K&& k);
    iterator xref:#unordered_node_set_copy_insert_with_hint[insert](const_iterator hint, const value_type& obj);
    iterator xref:#unordered_node_set_move_insert_with_hint[insert](const_iterator hint, value_type&& obj);
    template<class K> iterator xref:#unordered_node_set_transparent_insert_with_hint[insert](const_iterator hint, K&& k);
    template<class InputIterator> void xref:#unordered_node_set_insert_iterator_range[insert](InputIterator first, InputIterator last);
    void xref:#unordered_node_set_insert_initializer_list[insert](std::initializer_list<value_type>);
    insert_return_type xref:#unordered_node_set_insert_node[insert](node_type&& nh);
    iterator xref:#unordered_node_set_insert_node_with_hint[insert](const_iterator hint, node_type&& nh);

    _convertible-to-iterator_     xref:#unordered_node_set_erase_by_position[erase](iterator position);
    _convertible-to-iterator_     xref:#unordered_node_set_erase_by_position[erase](const_iterator position);
    size_type                   xref:#unordered_node_set_erase_by_key[erase](const key_type& k);
    template<class K> size_type xref:#unordered_node_set_erase_by_key[erase](K&& k);
    iterator  xref:#unordered_node_set_erase_range[erase](const_iterator first, const_iterator last);
    void      xref:#unordered_node_set_swap[swap](unordered_node_set& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
               boost::allocator_traits<Allocator>::propagate_on_container_swap::value);
    node_type xref:#unordered_node_set_extract_by_position[extract](const_iterator position);
    node_type xref:#unordered_node_set_extract_by_key[extract](const key_type& key);
    template<class K> node_type xref:#unordered_node_set_extract_by_key[extract](K&& key);
    init_type xref:#unordered_node_set_pull[pull](const_iterator position);
    void      xref:#unordered_node_set_clear[clear]() noexcept;

    template<class H2, class P2>
      void xref:#unordered_node_set_merge[merge](unordered_node_set<Key, T, H2, P2, Allocator>& source);
    template<class H2, class P2>
      void xref:#unordered_node_set_merge[merge](unordered_node_set<Key, T, H2, P2, Allocator>&& source);

    // observers
    hasher xref:#unordered_node_set_hash_function[hash_function]() const;
    key_equal xref:#unordered_node_set_key_eq[key_eq]() const;

    // set operations
    iterator         xref:#unordered_node_set_find[find](const key_type& k);
    const_iterator   xref:#unordered_node_set_find[find](const key_type& k) const;
    template<class K>
      iterator       xref:#unordered_node_set_find[find](const K& k);
    template<class K>
      const_iterator xref:#unordered_node_set_find[find](const K& k) const;
    size_type        xref:#unordered_node_set_count[count](const key_type& k) const;
    template<class K>
      size_type      xref:#unordered_node_set_count[count](const K& k) const;
    bool             xref:#unordered_node_set_contains[contains](const key_type& k) const;
    template<class K>
      bool           xref:#unordered_node_set_contains[contains](const K& k) const;
    std::pair<iterator, iterator>               xref:#unordered_node_set_equal_range[equal_range](const key_type& k);
    std::pair<const_iterator, const_iterator>   xref:#unordered_node_set_equal_range[equal_range](const key_type& k) const;
    template<class K>
      std::pair<iterator, iterator>             xref:#unordered_node_set_equal_range[equal_range](const K& k);
    template<class K>
      std::pair<const_iterator, const_iterator> xref:#unordered_node_set_equal_range[equal_range](const K& k) const;

    // bucket interface
    size_type xref:#unordered_node_set_bucket_count[bucket_count]() const noexcept;

    // hash policy
    float xref:#unordered_node_set_load_factor[load_factor]() const noexcept;
    float xref:#unordered_node_set_max_load_factor[max_load_factor]() const noexcept;
    void xref:#unordered_node_set_set_max_load_factor[max_load_factor](float z);
    size_type xref:#unordered_node_set_max_load[max_load]() const noexcept;
    void xref:#unordered_node_set_rehash[rehash](size_type n);
    void xref:#unordered_node_set_reserve[reserve](size_type n);

    // statistics (if xref:unordered_node_set_boost_unordered_enable_stats[enabled])
    stats xref:#unordered_node_set_get_stats[get_stats]() const;
    void xref:#unordered_node_set_reset_stats[reset_stats]() noexcept;
  };

  // Deduction Guides
  template<class InputIterator,
           class Hash = boost::hash<xref:#unordered_node_set_iter_value_type[__iter-value-type__]<InputIterator>>,
           class Pred = std::equal_to<xref:#unordered_node_set_iter_value_type[__iter-value-type__]<InputIterator>>,
           class Allocator = std::allocator<xref:#unordered_node_set_iter_value_type[__iter-value-type__]<InputIterator>>>
    unordered_node_set(InputIterator, InputIterator, typename xref:#unordered_node_set_deduction_guides[__see below__]::size_type = xref:#unordered_node_set_deduction_guides[__see below__],
                       Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> unordered_node_set<xref:#unordered_node_set_iter_value_type[__iter-value-type__]<InputIterator>, Hash, Pred, Allocator>;

  template<class T, class Hash = boost::hash<T>, class Pred = std::equal_to<T>,
           class Allocator = std::allocator<T>>
    unordered_node_set(std::initializer_list<T>, typename xref:#unordered_node_set_deduction_guides[__see below__]::size_type = xref:#unordered_node_set_deduction_guides[__see below__],
                       Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> unordered_node_set<T, Hash, Pred, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_node_set(InputIterator, InputIterator, typename xref:#unordered_node_set_deduction_guides[__see below__]::size_type, Allocator)
      -> unordered_node_set<xref:#unordered_node_set_iter_value_type[__iter-value-type__]<InputIterator>,
                            boost::hash<xref:#unordered_node_set_iter_value_type[__iter-value-type__]<InputIterator>>,
                            std::equal_to<xref:#unordered_node_set_iter_value_type[__iter-value-type__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_node_set(InputIterator, InputIterator, Allocator)
      -> unordered_node_set<xref:#unordered_node_set_iter_value_type[__iter-value-type__]<InputIterator>,
                            boost::hash<xref:#unordered_node_set_iter_value_type[__iter-value-type__]<InputIterator>>,
                            std::equal_to<xref:#unordered_node_set_iter_value_type[__iter-value-type__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Hash, class Allocator>
    unordered_node_set(InputIterator, InputIterator, typename xref:#unordered_node_set_deduction_guides[__see below__]::size_type, Hash,
                       Allocator)
      -> unordered_node_set<xref:#unordered_node_set_iter_value_type[__iter-value-type__]<InputIterator>, Hash,
                            std::equal_to<xref:#unordered_node_set_iter_value_type[__iter-value-type__]<InputIterator>>, Allocator>;

  template<class T, class Allocator>
    unordered_node_set(std::initializer_list<T>, typename xref:#unordered_node_set_deduction_guides[__see below__]::size_type, Allocator)
      -> unordered_node_set<T, boost::hash<T>, std::equal_to<T>, Allocator>;

  template<class T, class Allocator>
    unordered_node_set(std::initializer_list<T>, Allocator)
      -> unordered_node_set<T, boost::hash<T>, std::equal_to<T>, Allocator>;

  template<class T, class Hash, class Allocator>
    unordered_node_set(std::initializer_list<T>, typename xref:#unordered_node_set_deduction_guides[__see below__]::size_type, Hash, Allocator)
      -> unordered_node_set<T, Hash, std::equal_to<T>, Allocator>;

} // namespace unordered
} // namespace boost
-----

---

=== 描述

*模板参数*

[cols="1,1"]
|===

|_Key_
|`Key` must be https://en.cppreference.com/w/cpp/named_req/Erasable[Erasable^] from the container.

|_Hash_
|一种一元函数对象类型，用作 `Key` 的哈希函数。它接受一个 `Key` 类型的参数，并返回一个 `std::size_t` 类型的值。

|_Pred_
|A binary function object that induces an equivalence relation on values of type `Key`. It takes two arguments of type `Key` and returns a value of type `bool`.

|_Allocator_
|一个分配器，其值类型与容器的值类型相同。
支持使用 https://en.cppreference.com/w/cpp/named_req/Allocator#Fancy_pointers[花式指针] 的分配器。

|===

The element nodes of the container are held into an internal _bucket array_. A node is inserted into a bucket determined by the hash code of its element, but if the bucket is already occupied (a _collision_), an available one in the vicinity of the original position is used.

The size of the bucket array can be automatically increased by a call to `insert`/`emplace`, or as a result of calling `rehash`/`reserve`. The _load factor_ of the container (number of elements divided by number of buckets) is never greater than `max_load_factor()`, except possibly for small sizes where the implementation may decide to allow for higher loads.

If `link:../../../../../container_hash/doc/html/hash.html#ref_hash_is_avalanchinghash[hash_is_avalanching]<Hash>::value` is `true`, the hash function is used as-is; otherwise, a bit-mixing post-processing stage is added to increase the quality of hashing at the expense of extra computational cost.

---

=== Configuration Macros

==== `BOOST_UNORDERED_ENABLE_STATS`

Globally define this macro to enable xref:reference/stats.adoc#stats[statistics calculation] for the container. Note that this option decreases the overall performance of many operations.

---

=== 类型定义

[source, c++, subs=+quotes]
----
typedef _由实现定义_ iterator;
----

一个常量迭代器，其值类型为 `value_type`。

迭代器类别至少为前向迭代器。

可转换为 `const_iterator`。

---

[source, c++, subs=+quotes]
----
typedef _由实现定义_ const_iterator;
----

一个常量迭代器，其值类型为 `value_type`。

迭代器类别至少为前向迭代器。

---

[source, c++, subs=+quotes]
----
typedef _由实现极值类型__ node_type;
----

A class for holding extracted container elements, modelling https://en.cppreference.com/w/cpp/container/node_handle[NodeHandle].

---

[source, c++, subs=+quotes]
----
typedef _implementation-defined_ insert_return_type;
----

A specialization of an internal class template:

[source, c++, subs=+quotes]
----
template<class Iterator, class NodeType>
struct _insert_return_type_ // name is exposition only
{
  Iterator position;
  bool     inserted;
  NodeType node;
};
----

with `Iterator` = `iterator` and `NodeType` = `node_type`.

---

=== 构造函数

==== 默认构造函数
```c++

unordered_node_set();

```

Constructs an empty container using `hasher()` as the hash function, `key_equal()` as the key equality predicate and `allocator_type()` as the allocator.

[horizontal]
后置条件：;; `size() == 0`
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足 https://en.cppreference.com/w/c极值类型__/named_req/DefaultConstructible[可默认构造^]。

---

==== 桶数量构造函数
```c++

explicit unordered_node_set(size_type n,
                            const hasher& hf = hasher(),
                            const key_equal& eql = key_equal(),
                            const allocator_type& a = allocator_type());

```

Constructs an empty container with at least `n` buckets, using `hf` as the hash function, `eql` as the key equality predicate, and `a` as the allocator.

[horizontal]
后置条件：;; `size() == 0`
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足 https://en.cppreference.com/w/c极值类型__/named_req/DefaultConstructible[可默认构造^]。

---

==== 迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  unordered_node_set(InputIterator f, InputIterator l,
                     size_type n = _implementation-defined_,
                     const hasher& hf = hasher(),
                     const key_equal& eql = key_equal(),
                     const allocator_type& a = allocator_type());
----

Constructs an empty container with at least `n` buckets, using `hf` as the hash function, `eql` as the key equality predicate and `a` as the allocator, and inserts the elements from `[f, l)` into it.

[horizontal]
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足 https://en.cppreference.com/w/c极值类型__/named_req/DefaultConstructible[可默认构造^]。

---

==== 复制构造函数
```c++

unordered_node_set(unordered_node_set const& other);

```

The copy constructor. Copies the contained elements, hash function, predicate and allocator.

若 `Allocator::select_on_container_copy_construction` 存在且签名正确，则分配器将根据其结果构造。

[horizontal]
要求：;; `value_type` 需可复制构造

---

==== 移动构造函数
```c++

unordered_node_set(unordered_node_set&& other);

```

The move constructor. The internal bucket array of `other` is transferred directly to the new container. The hash function, predicate and allocator are moved-constructed from `other`. If statistics are xref:unordered_node_set_boost_unordered_enable_stats[enabled], transfers the internal statistical information from `other` and calls `other.reset_stats()`.

---

==== 带分配器的迭代器范围构造函数
```c++

template<class InputIterator>
  unordered_node_set(InputIterator f, InputIterator l, const allocator_type& a);

```

Constructs an empty container using `a` as the allocator, with the default hash function and key equality predicate and inserts the elements from `[f, l)` into it.

[horizontal]
要求：;; `hasher`、`key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 分配器构造函数
```c++

explicit unordered_node_set(Allocator const& a);

```

使用分配器 `a` 构造一个空容器。

---

==== 带分配器的复制构造函数
```c++

unordered_node_set(unordered_node_set const& other, Allocator const& a);

```

Constructs a container, copying ``other``'s contained elements, hash function, and predicate, but using allocator `a`.

---

==== 带分配器的移动构造函数
```c++

unordered_node_set(unordered_node_set&& other, Allocator const& a);

```

If `a == other.get_allocator()`, the element nodes of `other` are transferred directly to the new container; otherwise, elements are moved-constructed from those of `other`. The hash function and predicate are moved-constructed from `other`, and the allocator is copy-constructed from `a`. If statistics are xref:unordered_node_set_boost_unordered_enable_stats[enabled], transfers the internal statistical information from `other` iff `a == other.get_allocator()`, and always calls `other.reset_stats()`.

---

==== Move Constructor from concurrent_node_set

```c++

unordered_node_set(concurrent_node_set<Key, Hash, Pred, Allocator>&& other);

```

Move construction from a xref:#concurrent_node_set[`concurrent_node_set`]. The internal bucket array of `other` is transferred directly to the new container. The hash function, predicate and allocator are moved-constructed from `other`. If statistics are xref:unordered_node_set_boost_unordered_enable_stats[enabled], transfers the internal statistical information from `other` and calls `other.reset_stats()`.

[horizontal]
Complexity:;; Constant time.
Concurrency:;; Blocking on `other`.

---

==== 初始化列表构造函数
[source, c++, subs="+quotes"]
----
unordered_node_set(std::initializer_list<value_type> il,
              size_type n = _implementation-defined_
              const hasher& hf = hasher(),
              const key_equal& eql = key_equal(),
              const allocator_type& a = allocator_type());
----

Constructs an empty container with at least `n` buckets, using `hf` as the hash function, `eql` as the key equality predicate and `a`, and inserts the elements from `il` into it.

[horizontal]
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足 https://en.cppreference.com/w/c极值类型__/named_req/DefaultConstructible[可默认构造^]。

---

==== 带分配器的桶数量构造函数
```c++

unordered_node_set(size_type n, allocator_type const& a);

```

Constructs an empty container with at least `n` buckets, using `hf` as the hash function, the default hash function and key equality predicate and `a` as the allocator.

[horizontal]
后置条件：;; `size() == 0`
要求：;; `hasher` 和 `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 带哈希函数和分配器的桶数量构造函数
```c++

unordered_node_set(size_type n, hasher const& hf, allocator_type const& a);

```

Constructs an empty container with at least `n` buckets, using `hf` as the hash function, the default key equality predicate and `a` as the allocator.

[horizontal]
后置条件：;; `size() == 0`
要求：;; `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 带桶数量和分配器的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  unordered_node_set(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `a` as the allocator and default hash function and key equality predicate, and inserts the elements from `[f, l)` into it.

[horizontal]
要求：;; `hasher`、`key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 带桶数量和哈希函数的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
    template<class InputIterator>
      unordered_node_set(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                         const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `hf` as the hash function, `a` as the allocator, with the default key equality predicate, and inserts the elements from `[f, l)` into it.

[horizontal]
要求：;; `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 带分配器的初始化列表构造函数

```c++

unordered_node_set(std::initializer_list<value_type> il, const allocator_type& a);

```

Constructs an empty container using `a` and default hash function and key equality predicate, and inserts the elements from `il` into it.

[horizontal]
要求：;; `hasher` 和 `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 带桶数量和分配器的初始化列表构造函数

```c++

unordered_node_set(std::initializer_list<value_type> il, size_type n, const allocator_type& a);

```

Constructs an empty container with at least `n` buckets, using `a` and default hash function and key equality predicate, and inserts the elements from `il` into it.

[horizontal]
要求：;; `hasher` 和 `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 带桶数量、哈希函数和分配器的初始化列表构造函数

```c++

unordered_node_set(std::initializer_list<value_type> il, size_type n, const hasher& hf,
                   const allocator_type& a);

```

Constructs an empty container with at least `n` buckets, using `hf` as the hash function, `a` as the allocator and default key equality predicate,and inserts the elements from `il` into it.

[horizontal]
要求：;; `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

=== 析构函数

```c++

~unordered_node_set();

```

[horizontal]
注意：;; 析构函数会应用于每个元素，并释放所有内存

---

=== 赋值

==== 复制赋值

```c++

unordered_node_set& operator=(unordered_node_set const& other);

```

The assignment operator. Destroys previously existing elements, copy-assigns the hash function and predicate from `other`, copy-assigns the allocator from `other` if `Alloc::propagate_on_container_copy_assignment` exists and `Alloc::propagate_on_container_copy_assignment::value` is `true`, and finally inserts copies of the elements of `other`.

[horizontal]
要求：;; `value_type` is https://en.cppreference.com/w/cpp/named_req/CopyInsertable[CopyInsertable^]

---

==== 移动赋值
```c++

unordered_node_set& operator=(unordered_node_set&& other)
  noexcept((boost::allocator_traits<Allocator>::is_always_equal::value ||
            boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value) &&
            std::is_same<pointer, value_type*>::value);

```
The move assignment operator. Destroys previously existing elements, swaps the hash function and predicate from `other`,
and move-assigns the allocator from `other` if `Alloc::propagate_on_container_move_assignment` exists and `Alloc::propagate_on_container_move_assignment::value` is `true`.
If at this point the allocator is equal to `other.get_allocator()`, the internal bucket array of `other` is transferred directly to the new container;
otherwise, inserts move-constructed copies of the elements of `other`.
If statistics are xref:unordered_node_set_boost_unordered_enable_stats[enabled],
transfers the internal statistical information from `other` iff the final allocator is equal to `other.get_allocator()`,
and always calls `other.reset_stats()`.

---

==== 初始化列表赋值
```c++

unordered_node_set& operator=(std::initializer_list<value_type> il);

```

Assign from values in initializer list. All previously existing elements are destroyed.

[horizontal]
要求：;; `value_type` is https://en.cppreference.com/w/cpp/named_req/CopyInsertable[CopyInsertable^]

=== 迭代器

==== begin
```c++

iterator begin() noexcept; const_iterator begin() const noexcept;

```

[horizontal]
返回：;; 指向容器首元素的迭代器；若容器为空，则返回容器的尾后值。
Complexity:;; O(`bucket_count()`)

---

==== end
```c++

iterator end() noexcept; const_iterator end() const noexcept;

```

[horizontal]
返回：;; 指向容器尾后值的迭代器。

---

==== cbegin
```c++

const_iterator cbegin() const noexcept;

```

[horizontal]
返回：;; 指向容器首元素的 `const_iterator`；若容器为空，则返回容器的尾后值。
Complexity:;; O(`bucket_count()`)

---

==== cend
```c++

const_iterator cend() const noexcept;

```

[horizontal]
返回：;; 指向容器尾后值的 `const_iterator`。

---

=== 大小与容量

==== empty

```c++

[[nodiscard]] bool empty() const noexcept;

```

[horizontal]
返回：;; `size() == 0`

---

==== size

```c++

size_type size() const noexcept;

```

[horizontal]
返回：;; `std::distance(begin(), end())`

---

==== max_size

```c++

size_type max_size() const noexcept;

```

[horizontal]
返回：;; 最大可能容器的 `size()`。

---

=== 修改器

==== emplace
```c++

template<class... Args> std::pair<iterator, bool> emplace(Args&&... args);

```

Inserts an object, constructed with the arguments `args`, in the container if and only if there is no element in the container with an equivalent key.

[horizontal]
要求：;; `value_type` is constructible from `args`.
返回：;; The `bool` component of the return type is `true` if an insert took place. +
+
If an insert took place, then the iterator points to the newly inserted element. Otherwise, it points to the element with equivalent key.
抛出：;; 若调用 `hasher` 以外的操作抛出异常，则该函数无效果。
备注：;; Can invalidate iterators, but only if the insert causes the load to be greater than the maximum load. +

---

==== emplace_hint
```c++

template<class... Args> iterator emplace_hint(const_iterator position, Args&&... args);

```

Inserts an object, constructed with the arguments `args`, in the container if and only if there is no element in the container with an equivalent key.

`position` is a suggestion to where the element should be inserted. This implementation ignores it.

[horizontal]
要求：;; `value_type` is constructible from `args`.
返回：;; The `bool` component of the return type is `true` if an insert took place. +
+
If an insert took place, then the iterator points to the newly inserted element. Otherwise, it points to the element with equivalent key.
抛出：;; 若调用 `hasher` 以外的操作抛出异常，则该函数无效果。
备注：;; Can invalidate iterators, but only if the insert causes the load to be greater than the maximum load. +

---

==== 复制插入
```c++

std::pair<iterator, bool> insert(const value_type& obj);

```

Inserts `obj` in the container if and only if there is no element in the container with an equivalent key.

[horizontal]
要求：;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入^]。
返回：;; The `bool` component of the return type is `true` if an insert took place. +
+
If an insert took place, then the iterator points to the newly inserted element. Otherwise, it points to the element with equivalent key.
抛出：;; 若调用 `hasher` 以外的操作抛出异常，则该函数无效果。
备注：;; Can invalidate iterators, but only if the insert causes the load to be greater than the maximum load.

---

==== 移动插入
```c++

std::pair<iterator, bool> insert(value_type&& obj);

```

Inserts `obj` in the container if and only if there is no element in the container with an equivalent key.

[horizontal]
要求：;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入^]。
返回：;; The `bool` component of the return type is `true` if an insert took place. +
+
If an insert took place, then the iterator points to the newly inserted element. Otherwise, it points to the element with equivalent key.
抛出：;; 若调用 `hasher` 以外的操作抛出异常，则该函数无效果。
备注：;; Can invalidate iterators, but only if the insert causes the load to be greater than the maximum load.

---

==== Transparent Insert
```c++

template<class K> std::pair<iterator, bool> insert(K&& k);

```

Inserts an element constructed from `std::forward<K>(k)` in the container if and only if there is no element in the container with an equivalent key.

[horizontal]
要求：;; `value_type` is https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible^] from `k`.
返回：;; The bool component of the return type is true if an insert took place. +
+
If an insert took place, then the iterator points to the newly inserted element. Otherwise, it points to the element with equivalent key.
抛出：;; 若调用 `hasher` 以外的操作抛出异常，则该函数无效果。
备注：;; Can invalidate iterators, but only if the insert causes the load to be greater than the maximum load. +
+
This overload only participates in overload resolution if `Hash::is_transparent` and `Pred::is_transparent` are valid member typedefs and neither `iterator` nor `const_iterator` are implicitly convertible from `K`. The library assumes that `Hash` is callable with both `K` and `Key` and that `Pred` is transparent. This enables heterogeneous lookup which avoids the cost of instantiating an instance of the `Key` type.

---

==== 带提示的复制插入
```c++

iterator insert(const_iterator hint, const value_type& obj);

``` Inserts `obj` in the container if and only if there is no element in the container with an equivalent key.

`hint` is a suggestion to where the element should be inserted. This implementation ignores it.

[horizontal]
要求：;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入^]。
返回：;; The `bool` component of the return type is `true` if an insert took place. +
+
If an insert took place, then the iterator points to the newly inserted element. Otherwise, it points to the element with equivalent key.
抛出：;; 若调用 `hasher` 以外的操作抛出异常，则该函数无效果。
备注：;; Can invalidate iterators, but only if the insert causes the load to be greater than the maximum load.

---

==== 带提示的移动插入
```c++

iterator insert(const_iterator hint, value_type&& obj);

```

Inserts `obj` in the container if and only if there is no element in the container with an equivalent key.

`hint` is a suggestion to where the element should be inserted. This implementation ignores it.

[horizontal]
要求：;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入^]。
返回：;; The `bool` component of the return type is `true` if an insert took place. +
+
If an insert took place, then the iterator points to the newly inserted element. Otherwise, it points to the element with equivalent key.
抛出：;; 若调用 `hasher` 以外的操作抛出异常，则该函数无效果。
备注：;; Can invalidate iterators, but only if the insert causes the load to be greater than the maximum load.

---

==== Transparent Insert with Hint
```c++

template<class K> std::pair<iterator, bool> insert(const_iterator hint, K&& k);

```

Inserts an element constructed from `std::forward<K>(k)` in the container if and only if there is no element in the container with an equivalent key.

`hint` is a suggestion to where the element should be inserted. This implementation ignores it.

[horizontal]
要求：;; `value_type` is https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible^] from `k`.
返回：;; The bool component of the return type is true if an insert took place. +
+
If an insert took place, then the iterator points to the newly inserted element. Otherwise, it points to the element with equivalent key.
抛出：;; 若调用 `hasher` 以外的操作抛出异常，则该函数无效果。
备注：;; Can invalidate iterators, but only if the insert causes the load to be greater than the maximum load. +
+
This overload only participates in overload resolution if `Hash::is_transparent` and `Pred::is_transparent` are valid member typedefs and neither `iterator` nor `const_iterator` are implicitly convertible from `K`. The library assumes that `Hash` is callable with both `K` and `Key` and that `Pred` is transparent. This enables heterogeneous lookup which avoids the cost of instantiating an instance of the `Key` type.

---

==== 插入迭代器范围
```c++

template<class InputIterator> void insert(InputIterator first, InputIterator last);

```

向容器中插入一个元素范围。仅当容器中不存在等价键的元素时才插入。

[horizontal]
要求：;; `value_type` is https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible^] into the container from `*first`.
抛出：;; 当插入单个元素时，若调用 `hasher` 以外的操作抛出异常，则该函数无效果。
备注：;; Can invalidate iterators, but only if the insert causes the load to be greater than the maximum load.

---

==== 插入初始化列表
```c++

void insert(std::initializer_list<value_type>);

```

向容器中插入一个元素范围。仅当容器中不存在等价键的元素时才插入。

[horizontal]
要求：;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入^] 到容器中。
抛出：;; 当插入单个元素时，若调用 `hasher` 以外的操作抛出异常，则该函数无效果。
备注：;; Can invalidate iterators, but only if the insert causes the load to be greater than the maximum load.

---

==== Insert Node
```c++

insert_return_type insert(node_type&& nh);

```

If `nh` is not empty, inserts the associated element in the container if and only if there is no element in the container with a key equivalent to `nh.value()`. `nh` is empty when the function returns.

[horizontal]
返回：;; An `insert_return_type` object constructed from `position`, `inserted` and `node`: +
* If `nh` is empty, `inserted` is `false`, `position` is `end()`, and `node` is empty.
* Otherwise if the insertion took place, `inserted` is true, `position` points to the inserted element, and `node` is empty.
* If the insertion failed, `inserted` is false, `node` has the previous value of `nh`, and `position` points to an element with a key equivalent to `nh.value()`.
抛出：;; 若调用 `hasher` 以外的操作抛出异常，则该函数无效果。
备注：;; Behavior is undefined if `nh` is not empty and the allocators of `nh` and the container are not equal.

---

==== Insert Node with Hint
```c++

iterator insert(const_iterator hint, node_type&& nh);

```

If `nh` is not empty, inserts the associated element in the container if and only if there is no element in the container with a key equivalent to `nh.value()`. `nh` becomes empty if insertion took place, otherwise it is not changed.

`hint` is a suggestion to where the element should be inserted. This implementation ignores it.

[horizontal]
返回：;; The iterator returned is `end()` if `nh` is empty. If insertion took place, then the iterator points to the newly inserted element; otherwise, it points to the element with equivalent key.
抛出：;; 若调用 `hasher` 以外的操作抛出异常，则该函数无效果。
备注：;; Behavior is undefined if `nh` is not empty and the allocators of `nh` and the container are not equal.

---

==== 按位置擦除

[source, c++, subs=+quotes]
----
_convertible-to-iterator_ erase(iterator position);
_convertible-to-iterator_ erase(const_iterator position);
----

擦除 `position` 指向的元素。

[horizontal]
返回：;; An opaque object implicitly convertible to the `iterator` or `const_iterator` immediately following `position` prior to the erasure.
抛出：;; Nothing.
备注：;; The opaque object returned must only be discarded or immediately converted to `iterator` or `const_iterator`.

---

==== Erase by Key
```c++

size_type erase(const key_type& k); template<class K> size_type erase(K&& k);

```

擦除所有键等价于 `k` 的元素。

[horizontal]
返回：;; 擦除的元素数量。
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才会抛出异常。
备注：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义，且 `iterator` 和 `const_iterator` 均不能从 `K` 隐式转换时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免实例化 `Key` 类型的开销。

---

==== 范围擦除

```c++

iterator erase(const_iterator first, const_iterator last);

```

擦除从 `first` 到 `last` 范围内的元素。

[horizontal]
返回：;; 被擦除元素的后继迭代器——即 `last`。
抛出：;; Nothing in this implementation (neither the `hasher` nor the `key_equal` objects are called).

---

==== swap
```c++

void swap(unordered_node_set& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
           boost::allocator_traits<Allocator>::propagate_on_container_swap::value);

```

交换容器内容与参数对象。

若声明了 `Allocator::propagate_on_container_swap` 且 `Allocator::propagate_on_container_swap::value` 为 `true`，则交换容器的分配器。否则，与不等价分配器交换会导致未定义行为。

[horizontal]
抛出：;; Nothing unless `key_equal` or `hasher` throw on swapping.

---

==== Extract by Position
```c++

node_type extract(const_iterator position);

```

Extracts the element pointed to by `position`.

[horizontal]
返回：;; A `node_type` object holding the extracted element.
抛出：;; Nothing.

---

==== Extract by Key
```c++

node_type extract(const key_type&极值类型__); template<class K> node_type extract(K&& k);

```

Extracts the element with key equivalent to `k`, if it exists.

[horizontal]
返回：;; A `node_type` object holding the extracted element, or empty if no element was extracted.
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才会抛出异常。
备注：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免实例化 `Key` 类型的开销。

---

==== pull
```c++

init_type pull(const_iterator position);

```

Move-constructs an `init_value` `x` from the element pointed to by `position`, erases the element and returns `x`.

---

==== clear
```c++

void clear() noexcept;

```

擦除容器中所有元素。

[horizontal]
后置条件：;; `size() == 0`, `max_load() >= max_load_factor() * bucket_count()`

---

==== merge
```c++

template<class H2, class P2>
  void merge(unordered_node_set<Key, T, H2, P2, Allocator>& source);
template<class H2, class P2>
  void merge(unordered_node_set<Key, T, H2, P2, Allocator>&& source);

```

Transfers all the element nodes from `source` whose key is not already present in `*this`.

[horizontal]
要求：;; `this\->get_allocator() == source.get_allocator()`.
备注：;; Invalidates iterators to the elements transferred. If the resulting size of `*this` is greater than its original maximum load, invalidates all iterators associated to `*this`.

---

=== 观察器

==== get_allocator
```

allocator_type get_allocator() const noexcept;

```

[horizontal]
返回：;; The container's allocator.

---

==== hash_function
```

hasher hash_function() const;

```

[horizontal]
返回：;; 容器的哈希函数。

---

==== key_eq
```

key_equal key_eq() const;

```

[horizontal]
返回：;; 容器的键等价谓词

---

=== 查找

==== find
```c++

iterator         find(const key_type& k);
const_iterator   find(const key_type& k) const;
template<class K>
  iterator       find(const K& k);

```

[horizontal]
返回：;; An iterator pointing to an element with key equivalent to `k`, or `end()` if no such element exists.
备注：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免实例化 `Key` 类型的开销。

---

==== count
```c++

size_type        count(const key_type& k) const;
template<class K>
  size_type      count(const K& k) const;

```

[horizontal]
返回：;; 键等价于 `k` 的元素数量。
备注：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免实例化 `Key` 类型的开销。

---

==== contains
```c++

bool             contains(const key_type& k) const;
template<class K>
  bool           contains(const K& k) const;

```

[horizontal]
返回：;; 指示容器中是否存在键等于 `key` 的元素的布尔值
备注：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免实例化 `Key` 类型的开销。

---

==== equal_range
```c++

std::pair<iterator, iterator>               equal_range(const key_type& k);
std::pair<const_iterator, const_iterator>   equal_range(const key_type& k) const;
template<class K>
  std::pair<iterator, iterator>             equal_range(const K& k);
template<class K>
  std::pair<const_iterator, const_iterator> equal_range(const K& k) const;

```

[horizontal]
返回：;; 包含所有键等价于 `k` 的元素的范围。若容器不包含此类元素，则返回 `std::make_pair(b.end(), b.end())`。
备注：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免实例化 `Key` 类型的开销。

---

=== 桶接口

==== bucket_count
```c++

size_type bucket_count() const noexcept;

```

[horizontal]
返回：;; The size of the bucket array.

---

=== 哈希策略

==== load_factor
```c++

float load_factor() const noexcept;

```

[horizontal]
返回：;; `static_cast<float>(size())/static_cast<float>(bucket_count())`, or `0` if `bucket_count() == 0`.

---

==== max_load_factor

```c++

float max_load_factor() const noexcept;

```

[horizontal]
返回：;; Returns the container's maximum load factor.

---

==== 设置 max_load_factor
```c++

void max极值类型__(float z);

```

[horizontal]
效果：;; Does nothing, as the user is not allowed to change this parameter. Kept for compatibility with `boost::unordered_set`.

---


==== max_load

```c++

size_type max_load() const noexcept;

```

[horizontal]
返回：;; The maximum number of elements the container can hold without rehashing, assuming that no further elements will be erased.
注意：;; After construction, rehash or clearance, the container's maximum load is at least `max_load_factor() * bucket_count()`. This number may decrease on erasure under high-load conditions.

---

==== rehash
```c++

void rehash(size_type n);

```

Changes if necessary the size of the bucket array so that there are at least `n` buckets, and so that the load factor is less than or equal to the maximum load factor. When applicable, this will either grow or shrink the `bucket_count()` associated with the container.

When `size() == 0`, `rehash(0)` will deallocate the underlying buckets array. If the provided Allocator uses fancy pointers, a default allocation is subsequently performed.

Invalidates iterators and changes the order of elements.

[horizontal]
抛出：;; 若抛出异常（除非由容器的哈希函数或比较函数抛出），则该函数无效果。

---

==== reserve
```c++

void reserve(size_type n);

```

Equivalent to `a.rehash(ceil(n / a.max_load_factor()))`.

与 `rehash` 类似，此函数可用于增加或减少容器中的桶数量。

Invalidates iterators and changes the order of elements.

[horizontal]
抛出：;; 若抛出异常（除非由容器的哈希函数或比较函数抛出），则该函数无效果。

---

=== Statistics

==== get_stats
```c++

stats get_stats() const;

```

[horizontal]
返回：;; A statistical description of the insertion and lookup operations performed by the container so far.
备注：;; Only available if xref:reference/stats.adoc#stats[statistics calculation] is xref:unordered_node_set_boost_unordered_enable_stats[enabled].

---

==== reset_stats
```c++

void reset_stats() noexcept;

```

[horizontal]
效果：;; Sets to zero the internal statistics kept by the container.
备注：;; Only available if xref:reference/stats.adoc#stats[statistics calculation] is xref:unordered_node_set_boost_unordered_enable_stats[enabled].

---

=== 推导指引
若以下任一条件成立，则推导指引不参与重载决议：

  - 具有 `InputIterator` 模板参数，且为该参数推导的类型不符合输入迭代器要求。
  - 具有 `Allocator` 模板参数，且为该参数推导的类型不符合分配器要求。
  - 具有 `Hash` 模板参数，且为该参数推导的类型为整数类型或符合分配器要求。
  - 具有 `Pred` 模板参数，且为该参数推导的类型符合分配器要求。

推导指引中的 `size_­type` 参数类型指代由推导指引推导出的容器类型的 `size_­type` 成员类型。其默认值与所选构造函数的默认值一致。

==== __iter-value-type__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-value-type__ =
    typename std::iterator_traits<InputIterator>::value_type; // 仅用于说明
-----

=== 相等比较

==== operator==
```c++

template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator==(const unordered_node_set<Key, T, Hash, Pred, Alloc>& x,
                  const unordered_node_set<Key, T, Hash, Pred, Alloc>& y);

```

若 `x.size() == y.size()` 且对于 `x` 中的每个元素，`y` 中均存在一个具有相同键且值相等的元素（使用 `operator==` 比较值类型），则返回 `true`。

[horizontal]
备注：;; 若两个容器的等价谓词不等价，则行为未定义。

---

==== operator!=
```c++

template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator!=(const unordered_node_set<Key, T, Hash, Pred, Alloc>& x,
                  const unordered_node_set<Key, T, Hash, Pred, Alloc>& y);

```

若 `x.size() == y.size()` 且对于 `x` 中的每个元素，`y` 中均存在一个具有相同键且值相等的元素（使用 `operator==` 比较值类型），则返回 `false`。

[horizontal]
备注：;; 若两个容器的等价谓词不等价，则行为未定义。

=== Swap
```c++

template<class Key, class T, class Hash, class Pred, class Alloc>
  void swap(unordered_node_set<Key, T, Hash, Pred, Alloc>& x,
            unordered_node_set<Key, T, Hash, Pred, Alloc>& y)
    noexcept(noexcept(x.swap(y)));

```

交换 `x` 和 `y` 的内容。

若声明了 `Allocator::propagate_on_container_swap` 且 `Allocator::propagate_on_container_swap::value` 为 `true`，则交换容器的分配器。否则，与不等价分配器交换会导致未定义行为。

[horizontal]
效果：;; `x.swap(y)`
抛出：;; Nothing unless `key_equal` or `hasher` throw on swapping.

---

=== erase_if
```c++

template<class K, class T, class H, class P, class A, class Predicate>
  typename unordered_node_set<K, T, H, P, A>::size_type
    erase_if(unordered_node_set<K, T, H, P, A>& c, Predicate pred);

```

遍历容器 `c` 并移除所有满足谓词 `pred` 返回 `true` 的元素。

[horizontal]
返回：;; 被擦除的元素数量。
备注：;; 等价于：
+
```c++

auto original_size = c.size();
for (auto i = c.begin(), last = c.end(); i != last; ) {
  if (pred(*i)) {
    i = c.erase(i);
  } else {
    ++i;
  }
}
return original_size - c.size();

```

=== 序列化

``unordered_node_set``s can be archived/retrieved by means of link:../../../../../serialization/index.html[Boost.Serialization^] using the API provided by this library. Both regular and XML archives are supported.

==== Saving an unordered_node_set to an archive

Saves all the elements of an `unordered_node_set` `x` to an archive (XML archive) `ar`.

[horizontal]
要求：;; `value_type` 可序列化（XML 可序列化），且支持 Boost.Serialization 的 `save_construct_data`/`load_construct_data` 协议（https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^] 类型自动支持）。

---

==== Loading an unordered_node_set from an archive

Deletes all preexisting elements of an `unordered_node_set` `x` and inserts from an archive (XML archive) `ar` restored copies of the elements of the original `unordered_node_set` `other` saved to the storage read by `ar`.

[horizontal]
要求：;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入^]。`x.key_equal()` 在功能上等价于 `other.key_equal()`。

---

==== 将迭代器/常量迭代器保存到归档

将 `iterator`（`const_iterator`）`it` 的位置信息保存到归档（XML 归档）`ar` 中。`it` 可以是 `end()` 迭代器。

[horizontal]
要求：;; The `unordered_node_set` `x` pointed to by `it` has been previously saved to `ar`, and no modifying operations have been issued on `x` between saving of `x` and saving of `it`.

---

==== 从归档加载迭代器/常量迭代器

使 `iterator`（`const_iterator`）`it` 指向原始 `iterator`（`const_iterator`）保存到 `ar` 所读存储中的恢复位置。

[horizontal]
要求：;; If `x` is the `unordered_node_set` `it` points to, no modifying operations have been issued on `x` between loading of `x` and loading of `it`.
