[#unordered_set]
== Class Template unordered_set

:idprefix: unordered_set_

`boost::unordered_set` — An unordered associative container that stores unique values.

=== 概要

[listing, subs="+macros,+quotes"]
-----
// #include xref:reference/header_unordered_set.adoc[<boost/unordered/unordered_set.hpp>]

namespace boost {
namespace unordered {

  template<class Key,
           class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<Key>>
  class unordered_set {
  public:
    // types
    using key_type             = Key;
    using value_type           = Key;
    using hasher               = Hash;
    using key_equal            = Pred;
    using allocator_type       = Allocator;
    using pointer              = typename std::allocator_traits<Allocator>::pointer;
    using const_pointer        = typename std::allocator_traits<Allocator>::const_pointer;
    using reference            = value_type&;
    using const_reference      = const value_type&;
    using size_type            = std::size_t;
    using difference_type      = std::ptrdiff_t;

    using iterator             = _implementation-defined_;
    using const_iterator       = _implementation-defined_;
    using local_iterator       = _implementation-defined_;
    using const_local_iterator = _implementation-defined_;
    using node_type            = _implementation-defined_;
    using insert_return_type   = _implementation-defined_;

    // construct/copy/destroy
    xref:#unordered_set_default_constructor[unordered_set]();
    explicit xref:#unordered_set_bucket_count_constructor[unordered_set](size_type n,
                           const hasher& hf = hasher(),
                           const key_equal& eql = key_equal(),
                           const allocator_type& a = allocator_type());
    template<class InputIterator>
      xref:#unordered_set_iterator_range_constructor[unordered_set](InputIterator f, InputIterator l,
                    size_type n = _implementation-defined_,
                    const hasher& hf = hasher(),
                    const key_equal& eql = key_equal(),
                    const allocator_type& a = allocator_type());
    xref:#unordered_set_copy_constructor[unordered_set](const unordered_set& other);
    xref:#unordered_set_move_constructor[unordered_set](unordered_set&& other);
    template<class InputIterator>
      xref:#unordered_set_iterator_range_constructor_with_allocator[unordered_set](InputIterator f, InputIterator l, const allocator_type& a);
    explicit xref:#unordered_set_allocator_constructor[unordered_set](const Allocator& a);
    xref:#unordered_set_copy_constructor_with_allocator[unordered_set](const unordered_set& other, const Allocator& a);
    xref:#unordered_set_move_constructor_with_allocator[unordered_set](unordered_set&& other, const Allocator& a);
    xref:#unordered_set_initializer_list_constructor[unordered_set](std::initializer_list<value_type> il,
                  size_type n = _implementation-defined_,
                  const hasher& hf = hasher(),
                  const key_equal& eql = key_equal(),
                  const allocator_type& a = allocator_type());
    xref:#unordered_set_bucket_count_constructor_with_allocator[unordered_set](size_type n, const allocator_type& a);
    xref:#unordered_set_bucket_count_constructor_with_hasher_and_allocator[unordered_set](size_type n, const hasher& hf, const allocator_type& a);
    template<class InputIterator>
      xref:#unordered_set_iterator_range_constructor_with_bucket_count_and_allocator[unordered_set](InputIterator f, InputIterator l, size_type n, const allocator_type& a);
    template<class InputIterator>
      xref:#unordered_set_iterator_range_constructor_with_bucket_count_and_hasher[unordered_set](InputIterator f, InputIterator l, size_type n, const hasher& hf,
                    const allocator_type& a);
    xref:#unordered_set_initializer_list_constructor_with_allocator[unordered_set](std::initializer_list<value_type> il, const allocator_type& a);
    xref:#unordered_set_initializer_list_constructor_with_bucket_count_and_allocator[unordered_set](std::initializer_list<value_type> il, size_type n, const allocator_type& a);
    xref:#unordered_set_initializer_list_constructor_with_bucket_count_and_hasher_and_allocator[unordered_set](std::initializer_list<value_type> il, size_type n, const hasher& hf,
                  const allocator_type& a);
    xref:#unordered_set_destructor[~unordered_set]();
    unordered_set& xref:#unordered_set_copy_assignment[operator++=++](const unordered_set& other);
    unordered_set& xref:#unordered_set_move_assignment[operator++=++](unordered_set&& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
               boost::is_nothrow_move_assignable_v<Hash> &&
               boost::is_nothrow_move_assignable_v<Pred>);
    unordered_set& xref:#unordered_set_initializer_list_assignment[operator++=++](std::initializer_list<value_type> il);
    allocator_type xref:#unordered_set_get_allocator[get_allocator]() const noexcept;

    // iterators
    iterator       xref:#unordered_set_begin[begin]() noexcept;
    const_iterator xref:#unordered_set_begin[begin]() const noexcept;
    iterator       xref:#unordered_set_end[end]() noexcept;
    const_iterator xref:#unordered_set_end[end]() const noexcept;
    const_iterator xref:#unordered_set_cbegin[cbegin]() const noexcept;
    const_iterator xref:#unordered_set_cend[cend]() const noexcept;

    // capacity
    ++[[nodiscard]]++ bool xref:#unordered_set_empty[empty]() const noexcept;
    size_type xref:#unordered_set_size[size]() const noexcept;
    size_type xref:#unordered_set_max_size[max_size]() const noexcept;

    // modifiers
    template<class... Args> std::pair<iterator, bool> xref:#unordered_set_emplace[emplace](Args&&... args);
    template<class... Args> iterator xref:#unordered_set_emplace_hint[emplace_hint](const_iterator position, Args&&... args);
    std::pair<iterator, bool> xref:#unordered_set_copy_insert[insert](const value_type& obj);
    std::pair<iterator, bool> xref:#unordered_set_move_insert[insert](value_type&& obj);
    template<class K> std::pair<iterator, bool> xref:#unordered_set_transparent_insert[insert](K&& k);
    iterator xref:#unordered_set_copy_insert_with_hint[insert](const_iterator hint, const value_type& obj);
    iterator xref:#unordered_set_move_insert_with_hint[insert](const_iterator hint, value_type&& obj);
    template<class K> iterator xref:#unordered_set_transparent_insert_with_hint[insert](const_iterator hint, K&& k);
    template<class InputIterator> void xref:#unordered_set_insert_iterator_range[insert](InputIterator first, InputIterator last);
    void xref:#unordered_set_insert_initializer_list[insert](std::initializer_list<value_type>);

    node_type xref:#unordered_set_extract_by_iterator[extract](const_iterator position);
    node_type xref:#unordered_set_extract_by_value[extract](const key_type& k);
    template<class K> node_type xref:#unordered_set_extract_by_value[extract](K&& k);
    insert_return_type xref:#unordered_set_insert_with_node_handle[insert](node_type&& nh);
    iterator           xref:#unordered_set_insert_with_hint_and_node_handle[insert](const_iterator hint, node_type&& nh);

    iterator  xref:#unordered_set_erase_by_position[erase](iterator position);
    iterator  xref:#unordered_set_erase_by_position[erase](const_iterator position);
    size_type xref:#unordered_set_erase_by_value[erase](const key_type& k);
    template<class K> size_type xref:#unordered_set_erase_by_value[erase](K&& k);
    iterator  xref:#unordered_set_erase_range[erase](const_iterator first, const_iterator last);
    void      xref:#unordered_set_quick_erase[quick_erase](const_iterator position);
    void      xref:#unordered_set_erase_return_void[erase_return_void](const_iterator position);
    void      xref:#unordered_set_swap[swap](unordered_set& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
               boost::is_nothrow_swappable_v<Hash> &&
               boost::is_nothrow_swappable_v<Pred>);
    void      xref:#unordered_set_clear[clear]() noexcept;

    template<class H2, class P2>
      void xref:#unordered_set_merge[merge](unordered_set<Key, H2, P2, Allocator>& source);
    template<class H2, class P2>
      void xref:#unordered_set_merge[merge](unordered_set<Key, H2, P2, Allocator>&& source);
    template<class H2, class P2>
      void xref:#unordered_set_merge[merge](unordered_multiset<Key, H2, P2, Allocator>& source);
    template<class H2, class P2>
      void xref:#unordered_set_merge[merge](unordered_multiset<Key, H2, P2, Allocator>&& source);

    // observers
    hasher xref:#unordered_set_hash_function[hash_function]() const;
    key_equal xref:#unordered_set_key_eq[key_eq]() const;

    // set operations
    iterator         xref:#unordered_set_find[find](const key_type& k);
    const_iterator   xref:#unordered_set_find[find](const key_type& k) const;
    template<class K>
      iterator       xref:#unordered_set_find[find](const K& k);
    template<class K>
      const_iterator xref:#unordered_set_find[find](const K& k) const;
    template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
      iterator       xref:#unordered_set_find[find](CompatibleKey const& k, CompatibleHash const& hash,
                          CompatiblePredicate const& eq);
    template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
      const_iterator xref:#unordered_set_find[find](CompatibleKey const& k, CompatibleHash const& hash,
                          CompatiblePredicate const& eq) const;
    size_type        xref:#unordered_set_count[count](const key_type& k) const;
    template<class K>
      size_type      xref:#unordered_set_count[count](const K& k) const;
    bool             xref:#unordered_set_contains[contains](const key_type& k) const;
    template<class K>
      bool           xref:#unordered_set_contains[contains](const K& k) const;
    std::pair<iterator, iterator>               xref:#unordered_set_equal_range[equal_range](const key_type& k);
    std::pair<const_iterator, const_iterator>   xref:#unordered_set_equal_range[equal_range](const key_type& k) const;
    template<class K>
      std::pair<iterator, iterator>             xref:#unordered_set_equal_range[equal_range](const K& k);
    template<class K>
      std::pair<const_iterator, const_iterator> xref:#unordered_set_equal_range[equal_range](const K& k) const;

    // bucket interface
    size_type xref:#unordered_set_bucket_count[bucket_count]() const noexcept;
    size_type xref:#unordered_set_max_bucket_count[max_bucket_count]() const noexcept;
    size_type xref:#unordered_set_bucket_size[bucket_size](size_type n) const;
    size_type xref:#unordered_set_bucket[bucket](const key_type& k) const;
    template<class K> size_type xref:#unordered_set_bucket[bucket](const K& k) const;
    local_iterator xref:#unordered_set_begin_2[begin](size_type n);
    const_local_iterator xref:#unordered_set_begin_2[begin](size_type n) const;
    local_iterator xref:#unordered_set_end_2[end](size_type n);
    const_local_iterator xref:#unordered_set_end_2[end](size_type n) const;
    const_local_iterator xref:#unordered_set_cbegin_2[cbegin](size_type n) const;
    const_local_iterator xref:#unordered_set_cend_2[cend](size_type n) const;

    // hash policy
    float xref:#unordered_set_load_factor[load_factor]() const noexcept;
    float xref:#unordered_set_max_load_factor[max_load_factor]() const noexcept;
    void xref:#unordered_set_set_max_load_factor[max_load_factor](float z);
    void xref:#unordered_set_rehash[rehash](size_type n);
    void xref:#unordered_set_reserve[reserve](size_type n);
  };

  // Deduction Guides
  template<class InputIterator,
           class Hash = boost::hash<xref:#unordered_set_iter_value_type[__iter-value-type__]<InputIterator>>,
           class Pred = std::equal_to<xref:#unordered_set_iter_value_type[__iter-value-type__]<InputIterator>>,
           class Allocator = std::allocator<xref:#unordered_set_iter_value_type[__iter-value-type__]<InputIterator>>>
    unordered_set(InputIterator, InputIterator, typename xref:#unordered_set_deduction_guides[__see below__]::size_type = xref:#unordered_set_deduction_guides[__see below__],
                  Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> unordered_set<xref:#unordered_set_iter_value_type[__iter-value-type__]<InputIterator>, Hash, Pred, Allocator>;

  template<class T, class Hash = boost::hash<T>, class Pred = std::equal_to<T>,
           class Allocator = std::allocator<T>>
    unordered_set(std::initializer_list<T>, typename xref:#unordered_set_deduction_guides[__see below__]::size_type = xref:#unordered_set_deduction_guides[__see below__],
                  Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> unordered_set<T, Hash, Pred, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_set(InputIterator, InputIterator, typename xref:#unordered_set_deduction_guides[__see below__]::size_type, Allocator)
      -> unordered_set<xref:#unordered_set_iter_value_type[__iter-value-type__]<InputIterator>,
                       boost::hash<xref:#unordered_set_iter_value_type[__iter-value-type__]<InputIterator>>,
                       std::equal_to<xref:#unordered_set_iter_value_type[__iter-value-type__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_set(InputIterator, InputIterator, Allocator)
      -> unordered_set<xref:#unordered_set_iter_value_type[__iter-value-type__]<InputIterator>,
                       boost::hash<xref:#unordered_set_iter_value_type[__iter-value-type__]<InputIterator>>,
                       std::equal_to<xref:#unordered_set_iter_value_type[__iter-value-type__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Hash, class Allocator>
    unordered_set(InputIterator, InputIterator, typename xref:#unordered_set_deduction_guides[__see below__]::size_type, Hash, Allocator)
      -> unordered_set<xref:#unordered_set_iter_value_type[__iter-value-type__]<InputIterator>, Hash,
                       std::equal_to<xref:#unordered_set_iter_value_type[__iter-value-type__]<InputIterator>>, Allocator>;

  template<class T, class Allocator>
    unordered_set(std::initializer_list<T>, typename xref:#unordered_set_deduction_guides[__see below__]::size_type, Allocator)
      -> unordered_set<T, boost::hash<T>, std::equal_to<T>, Allocator>;

  template<class T, class Allocator>
    unordered_set(std::initializer_list<T>, Allocator)
      -> unordered_set<T, boost::hash<T>, std::equal_to<T>, Allocator>;

  template<class T, class Hash, class Allocator>
    unordered_set(std::initializer_list<T>, typename xref:#unordered_set_deduction_guides[__see below__]::size_type, Hash, Allocator)
      -> unordered_set<T, Hash, std::equal_to<T>, Allocator>;

} // namespace unordered
} // namespace boost
-----

---

=== 描述

*模板参数*

[cols="1,1"]
|===

|_Key_
|`Key` must be https://en.cppreference.com/w/cpp/named_req/Erasable[Erasable^] from the container (i.e. `allocator_traits` can destroy it).

|_Hash_
|一元函数对象类型，用作 `Key` 的哈希函数。它接受一个类型为 `Key` 的参数，并返回一个类型为 `std::size_t` 的值。

|_Pred_
|A binary function object that implements an equivalence relation on values of type `Key`. A binary function object that induces an equivalence relation on values of type `Key`. It takes two arguments of type `Key` and returns a value of type bool.

|_Allocator_
|分配器，其值类型与容器的值类型相同。
支持使用花式指针（fancy pointers）的分配器。

|===

The elements are organized into buckets. Keys with the same hash code are stored in the same bucket.

The number of buckets can be automatically increased by a call to insert, or as the result of calling rehash.

=== Configuration macros

==== `BOOST_UNORDERED_ENABLE_SERIALIZATION_COMPATIBILITY_V0`

Globally define this macro to support loading of ``unordered_set``s saved to a Boost.Serialization archive with a version of Boost prior to Boost 1.84.

=== 类型定义

[source, c++, subs=+quotes]
----
typedef _由实现定义_ iterator;
----

值类型为 `value_type` 的常量迭代器。

迭代器类别至少为前向迭代器。

可转换为 `const_iterator`。

---

[source, c++, subs=+quotes]
----
typedef _由实现定义_ const_iterator;
----

值类型为 `value_type` 的常量迭代器。

迭代器类别至少为前向迭代器。

---

[source, c++, subs=+quotes]
----
typedef _implementation-defined_ local_iterator;
----

An iterator with the same value type, difference type and pointer and reference type as iterator.

A `local_iterator` object can be used to iterate through a single bucket.

---

[source, c++, subs=+quotes]
----
typedef _implementation-defined_ const_local_iterator;
----

A constant iterator with the same value type, difference type and pointer and reference type as const_iterator.

A const_local_iterator object can be used to iterate through a single bucket.

---

[source, c++, subs=+quotes]
----
typedef _由实现定义_ node_type;
----

用于保存提取的容器元素的类，建模为节点句柄（NodeHandle）。

---

[source, c++, subs=+quotes]
----
typedef _由实现定义_ insert_return_type;
----

内部类模板的特化：

[source, c++, subs=+quotes]
----
template<class Iterator, class NodeType>
struct _插入返回类型_ // 名称仅用于说明
{
  Iterator position;
  bool     inserted;
  NodeType node;
};
----

其中 `Iterator` = `iterator` 且 `NodeType` = `node_type`。

---

=== 构造函数

==== 默认构造函数
```c++

unordered_set();

```

Constructs an empty container using `hasher()` as the hash function, `key_equal()` as the key equality predicate, `allocator_type()` as the allocator and a maximum load factor of `1.0`.

[horizontal]
后置条件：;; `size() == 0`
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足可默认构造（DefaultConstructible）要求。

---

==== 桶数量构造函数
```c++

explicit unordered_set(size_type n,
                       const hasher& hf = hasher(),
                       const key_equal& eql = key_equal(),
                       const allocator_type& a = allocator_type());

```

Constructs an empty container with at least `n` buckets, using `hf` as the hash function, `eql` as the key equality predicate, `a` as the allocator and a maximum load factor of `1.0`.

[horizontal]
后置条件：;; `size() == 0`
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足可默认构造（DefaultConstructible）要求。

---

==== 迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  unordered_set(InputIterator f, InputIterator l,
                size_type n = _implementation-defined_,
                const hasher& hf = hasher(),
                const key_equal& eql = key_equal(),
                const allocator_type& a = allocator_type());
----

Constructs an empty container with at least `n` buckets, using `hf` as the hash function, `eql` as the key equality predicate, `a` as the allocator and a maximum load factor of `1.0` and inserts the elements from `[f, l)` into it.

[horizontal]
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足可默认构造（DefaultConstructible）要求。

---

==== 复制构造函数
```c++

unordered_set(const unordered_set& other);

```

The copy constructor. Copies the contained elements, hash function, predicate, maximum load factor and allocator.

若 `Allocator::select_on_container_copy_construction` 存在且签名正确，则分配器将由此方法的结果构造。

[horizontal]
要求：;; `value_type` 需满足可复制构造要求

---

==== 移动构造函数
```c++

unordered_set(unordered_set&& other);

```

The move constructor.

[horizontal]
注意：;; This is implemented using Boost.Move.
要求：;; `value_type` is move-constructible.

---

==== 带分配器的迭代器范围构造函数
```c++

template<class InputIterator>
  unordered_set(InputIterator f, InputIterator l, const allocator_type& a);

```

Constructs an empty container using `a` as the allocator, with the default hash function and key equality predicate and a maximum load factor of `1.0` and inserts the elements from `[f, l)` into it.

[horizontal]
要求：;; `hasher`、`key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

==== 分配器构造函数
```c++

explicit unordered_set(const Allocator& a);

```

使用分配器 `a` 构造空容器。

---

==== 带分配器的复制构造函数
```c++

unordered_set(const unordered_set& other, const Allocator& a);

```

Constructs an container, copying ``other``'s contained elements, hash function, predicate, maximum load factor, but using allocator `a`.

---

==== 带分配器的移动构造函数
```c++

unordered_set(unordered_set&& other, const Allocator& a);

```

Construct a container moving ``other``'s contained elements, and having the hash function, predicate and maximum load factor, but using allocate `a`.

[horizontal]
注意：;; This is implemented using Boost.Move.
要求：;; `value_type` is move insertable.

---

==== 初始化列表构造函数
[source, c++, subs="+quotes"]
----
unordered_set(std::initializer_list<value_type> il,
              size_type n = _implementation-defined_,
              const hasher& hf = hasher(),
              const key_equal& eql = key_equal(),
              const allocator_type& a = allocator_type());
----

Constructs an empty container with at least `n` buckets, using `hf` as the hash function, `eql` as the key equality predicate, `a` as the allocator and a maximum load factor of `1.0` and inserts the elements from `il` into it.

[horizontal]
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足可默认构造（DefaultConstructible）要求。

---

==== 带分配器的桶数量构造函数
```c++

unordered_set(size_type n, const allocator_type& a);

```

Constructs an empty container with at least `n` buckets, using `hf` as the hash function, the default hash function and key equality predicate, `a` as the allocator and a maximum load factor of `1.0`.

[horizontal]
后置条件：;; `size() == 0`
要求：;; `hasher` 和 `key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

==== 带哈希函数和分配器的桶数量构造函数
```c++

unordered_set(size_type n, const hasher& hf, const allocator_type& a);

```

Constructs an empty container with at least `n` buckets, using `hf` as the hash function, the default key equality predicate, `a` as the allocator and a maximum load factor of `1.0`.

[horizontal]
后置条件：;; `size() == 0`
要求：;; `key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

==== 带桶数量和分配器的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  unordered_set(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `a` as the allocator, with the default hash function and key equality predicate and a maximum load factor of `1.0` and inserts the elements from `[f, l)` into it.

[horizontal]
要求：;; `hasher`、`key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

==== 带桶数量和哈希函数的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  unordered_set(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `hf` as the hash function, `a` as the allocator, with the default key equality predicate and a maximum load factor of `1.0` and inserts the elements from `[f, l)` into it.

[horizontal]
要求：;; `key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

==== 带分配器的初始化列表构造函数

```c++

unordered_set(std::initializer_list<value_type> il, const allocator_type& a);

```

Constructs an empty container using `a` as the allocator and a maximum load factor of 1.0 and inserts the elements from `il` into it.

[horizontal]
要求：;; `hasher` 和 `key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

==== 带桶数量和分配器的初始化列表构造函数

```c++

unordered_set(std::initializer_list<value_type> il, size_type n, const allocator_type& a);

```

Constructs an empty container with at least `n` buckets, using `a` as the allocator and a maximum load factor of 1.0 and inserts the elements from `il` into it.

[horizontal]
要求：;; `hasher` 和 `key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

==== 带桶数量、哈希函数和分配器的初始化列表构造函数

```c++

unordered_set(std::initializer_list<value_type> il, size_type n, const hasher& hf,
              const allocator_type& a);

```

Constructs an empty container with at least `n` buckets, using `hf` as the hash function, `a` as the allocator and a maximum load factor of 1.0 and inserts the elements from `il` into it.

[horizontal]
要求：;; `key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

=== 析构函数

```c++

~unordered_set();

```

[horizontal]
注意：;; 析构函数作用于每个元素，并释放所有内存

---

=== 赋值

==== 复制赋值

```c++

unordered_set& operator=(const unordered_set& other);

```

The assignment operator. Copies the contained elements, hash function, predicate and maximum load factor but not the allocator.

If `Alloc::propagate_on_container_copy_assignment` exists and `Alloc::propagate_on_container_copy_assignment::value` is `true`, the allocator is overwritten, if not the copied elements are created using the existing allocator.

[horizontal]
要求：;; `value_type` 需满足可复制构造要求

---

==== 移动赋值
```c++

unordered_set& operator=(unordered_set&& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
           boost::is_nothrow_move_assignable_v<Hash> &&
           boost::is_nothrow_move_assignable_v<Pred>);

```
The move assignment operator.

If `Alloc::propagate_on_container_move_assignment` exists and `Alloc::propagate_on_container_move_assignment::value` is `true`, the allocator is overwritten, if not the moved elements are created using the existing allocator.

[horizontal]
要求：;; `value_type` is move constructible.

---

==== 初始化列表赋值
```c++

unordered_set& operator=(std::initializer_list<value_type> il);

```

Assign from values in initializer list. All existing elements are either overwritten by the new elements or destroyed.

[horizontal]
要求：;; `value_type` is https://en.cppreference.com/w/cpp/named_req/CopyInsertable[CopyInsertable^] into the container and https://en.cppreference.com/w/cpp/named_req/CopyAssignable[CopyAssignable^].

---

=== 迭代器

==== begin
```c++

iterator begin() noexcept; const_iterator begin() const noexcept;

```

[horizontal]
返回：;; 一个指向容器首元素的迭代器；若容器为空，则返回容器的尾后值。

---

==== end
```c++

iterator end() noexcept; const_iterator end() const noexcept;

```

[horizontal]
返回：;; 一个指向容器尾后值的迭代器。

---

==== cbegin
```c++

const_iterator cbegin() const noexcept;

```

[horizontal]
返回：;; 一个指向容器首元素的 `const_iterator`；若容器为空，则返回容器的尾后值。

---

==== cend
```c++

const_iterator cend() const noexcept;

```

[horizontal]
返回：;; 一个指向容器尾后值的 `const_iterator`。

---

=== 大小与容量

==== empty

```c++

[[nodiscard]] bool empty() const noexcept;

```

[horizontal]
返回：;; `size() == 0`

---

==== size

```c++

size_type size() const noexcept;

```

[horizontal]
返回：;; `std::distance(begin(), end())`

---

==== max_size

```c++

size_type max_size() const noexcept;

```

[horizontal]
返回：;; 容器可能的最大 `size()`。

---

=== 修改器

==== emplace
```c++

template<class... Args> std::pair<iterator, bool> emplace(Args&&... args);

```

Inserts an object, constructed with the arguments `args`, in the container if and only if there is no element in the container with an equivalent value.

[horizontal]
要求：;; `value_type` is https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible^] into `X` from `args`.
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。
+
If an insert took place, then the iterator points to the newly inserted element. Otherwise, it points to the element with equivalent value.
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated.

---

==== emplace_hint
```c++

template<class... Args> iterator emplace_hint(const_iterator position, Args&&... args);

```

Inserts an object, constructed with the arguments `args`, in the container if and only if there is no element in the container with an equivalent value.

`position` is a suggestion to where the element should be inserted.

[horizontal]
要求：;; `value_type` is https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible^] into `X` from `args`.
返回：;; 若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; The standard is fairly vague on the meaning of the hint. But the only practical way to use it, and the only way that Boost.Unordered supports is to point to an existing element with the same key. +
+
Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated.

---

==== 复制插入
```c++

std::pair极速赛车开奖直播官网<iterator, bool> insert(const value_type& obj);

```

当且仅当容器中不存在等价键时，插入 `obj`。

[horizontal]
要求：;; `value_type` 需满足可复制插入（CopyInsertable）要求。
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated.

---

==== 移动插入
```c++

std::pair<iterator, bool> insert(value_type&& obj);

```

当且仅当容器中不存在等价键时，插入 `obj`。

[horizontal]
要求：;; `value_type` 需满足可移动插入（MoveInsertable）要求。
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated.

---

==== 透明插入
```c++

template<class K> std::pair<iterator, bool> insert(K&& k);

```

当且仅当容器中不存在等价键时，插入一个由 `std::forward<K>(k)` 构造的元素。

[horizontal]
要求：;; `value_type` 需可从 `k` 原位构造（EmplaceConstructible）。
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated. +
+
仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义，且 `iterator` 与 `const_iterator` 均不能从 `K` 隐式转换时，此重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== 带提示的复制插入
```c++

iterator insert(const_iterator hint, const value_type& obj);

``` 当且仅当容器中不存在等价键时，插入 `obj`。

`hint` is a suggestion to where the element should be inserted.

[horizontal]
要求：;; `value_type` 需满足可复制插入（CopyInsertable）要求。
返回：;; 若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; The standard is fairly vague on the meaning of the hint. But the only practical way to use it, and the only way that Boost.Unordered supports is to point to an existing element with the same key. +
+
Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated.

---

==== 带提示的移动插入
```c++

iterator insert(const_iterator hint, value_type&& obj);

```

当且仅当容器中不存在等价键时，插入 `obj`。

`hint` is a suggestion to where the element should be inserted.

[horizontal]
要求：;; `value_type` 需满足可移动插入（MoveInsertable）要求。
返回：;; 若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; The standard is fairly vague on the meaning of the hint. But the only practical way to use it, and the only way that Boost.Unordered supports is to point to an existing element with the same key. +
+
Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated.

---

==== 带提示的透明插入
```c++

template<class K> iterator insert(const_iterator hint, K&& k);

```

当且仅当容器中不存在等价键时，插入一个由 `std::forward<K>(k)` 构造的元素。

`hint` is a suggestion to where the element should be inserted.

[horizontal]
要求：;; `value_type` 需可从 `k` 原位构造（EmplaceConstructible）。
返回：;; 若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; The standard is fairly vague on the meaning of the hint. But the only practical way to use it, and the only way that Boost.Unordered supports is to point to an existing element with the same key. +
+
Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated. +
+
仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义，且 `iterator` 与 `const_iterator` 均不能从 `K` 隐式转换时，此重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== 插入迭代器范围
```c++

template<class InputIterator> void insert(InputIterator first, InputIterator last);

```

将元素范围插入容器。当且仅当容器中不存在等价键时插入元素。

[horizontal]
要求：;; `value_type` is https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible^] into `X` from `*first`.
抛出：;; 插入单个元素时，若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated.

---

==== 插入初始化列表
```c++

void insert(std::initializer_list<value_type>);

```

将元素范围插入容器。当且仅当容器中不存在等价键时插入元素。

[horizontal]
要求：;; `value_type` 需满足可复制插入（CopyInsertable）到容器的要求。
抛出：;; 插入单个元素时，若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated.

---

==== Extract by Iterator
```c++

node_type extract(const_iterator position);

```

Removes the element pointed to by `position`.

[horizontal]
返回：;; A `node_type` owning the element.
注意：;; In C++17 a node extracted using this method can be inserted into a compatible `unordered_multiset`, but that is not supported yet.

---

==== Extract by Value
```c++

node_type extract(const key_type& k); template<class K> node_type extract(K&& k);

```

Removes an element with key equivalent to `k`.

[horizontal]
返回：;; A `node_type` owning the element if found, otherwise an empty `node_type`.
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才会抛出异常。
注意：;; In C++17 a node extracted using this method can be inserted into a compatible `unordered_multiset`, but that is not supported yet. +
+
仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义，且 `iterator` 与 `const_iterator` 均不能从 `K` 隐式转换时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== Insert with `node_handle`
```c++

insert_return_type insert(node_type&& nh);

```

If `nh` is empty, has no effect.

Otherwise inserts the element owned by `nh` if and only if there is no element in the container with an equivalent key.

[horizontal]
要求：;; `nh` is empty or `nh.get_allocator()` is equal to the container's allocator.
返回：;; If `nh` was empty, returns an `insert_return_type` with: `inserted` equal to `false`, `position` equal to `end()` and `node` empty. +
+
Otherwise if there was already an element with an equivalent key, returns an `insert_return_type` with: `inserted` equal to `false`, `position` pointing to a matching element and `node` contains the node from `nh`. +
+
Otherwise if the insertion succeeded, returns an `insert_return_type` with: `inserted` equal to `true`, `position` pointing to the newly inserted element and `node` empty.
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated. +
+
In C++17 this can be used to insert a node extracted from a compatible `unordered_multiset`, but that is not supported yet.

---

==== Insert with Hint and `node_handle`
```c++

iterator insert(const_iterator hint, node_type&& nh);

```

If `nh` is empty, has no effect.

Otherwise inserts the element owned by `nh` if and only if there is no element in the container with an equivalent key.

If there is already an element in the container with an equivalent key has no effect on `nh` (i.e. `nh` still contains the node.)

`hint` is a suggestion to where the element should be inserted.

[horizontal]
要求：;; `nh` is empty or `nh.get_allocator()` is equal to the container's allocator.
返回：;; If `nh` was empty returns `end()`. +
+
If there was already an element in the container with an equivalent key returns an iterator pointing to that. +
+
Otherwise returns an iterator pointing to the newly inserted element.
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; The standard is fairly vague on the meaning of the hint. But the only practical way to use it, and the only way that Boost.Unordered supports is to point to an existing element with the same key. +
+
Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated. +
+
This can be used to insert a node extracted from a compatible `unordered_multiset`.

---

==== 按位置擦除

```c++

iterator erase(iterator position); iterator erase(const_iterator position);

```

擦除 `position` 指向的元素。

[horizontal]
返回：;; The iterator following `position` before the erasure.
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才会抛出异常。
注意：;; In older versions this could be inefficient because it had to search through several buckets to find the position of the returned iterator. The data structure has been changed so that this is no longer the case, and the alternative erase methods have been deprecated.

---

==== Erase by Value
```c++

size_type erase(const key_type& k); template<class K> size_type erase(K&& k);

```

擦除所有键等价于 `k` 的元素。

[horizontal]
返回：;; 擦除的元素数量。
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才会抛出异常。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义，且 `iterator` 与 `const_iterator` 均不能从 `K` 隐式转换时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== 范围擦除

```c++

iterator erase(const_iterator first, const_iterator last);

```

擦除从 `first` 到 `last` 范围内的元素。

[horizontal]
返回：;; 指向被擦除元素之后位置的迭代器——即 `last`。
抛出：;; Only throws an exception if it is thrown by `hasher` or `key_equal`. +
+
In this implementation, this overload doesn't call either function object's methods so it is no throw, but this might not be true in other implementations.

---

==== quick_erase
```c++

void quick_erase(const_iterator position);

```

擦除 `position` 指向的元素。

[horizontal]
抛出：;; Only throws an exception if it is thrown by `hasher` or `key_equal`. +
+
In this implementation, this overload doesn't call either function object's methods so it is no throw, but this might not be true in other implementations.
注意：;; This method was implemented because returning an iterator to the next element from erase was expensive, but the container has been redesigned so that is no longer the case. So this method is now deprecated.

---

==== erase_return_void
```c++

void erase_return_void(const_iterator position);

```

擦除 `position` 指向的元素。

[horizontal]
抛出：;; Only throws an exception if it is thrown by `hasher` or `key_equal`. +
+
In this implementation, this overload doesn't call either function object's methods so it is no throw, but this might not be true in other implementations.
注意：;; This method was implemented because returning an iterator to the next element from erase was expensive, but the container has been redesigned so that is no longer the case. So this method is now deprecated.

---

==== swap
```c++

void swap(unordered_set& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
           boost::is_nothrow_swappable_v<Hash> &&
           boost::is_nothrow_swappable_v<Pred>);

```

交换容器与参数的内容。

若声明了 `Allocator::propagate_on_container_swap` 且其值为 `true`，则交换容器的分配器；否则，与不同分配器的容器交换将导致未定义行为。

[horizontal]
抛出：;; Doesn't throw an exception unless it is thrown by the copy constructor or copy assignment operator of `key_equal` or `hasher`.
注意：;; The exception specifications aren't quite the same as the C++11 standard, as the equality predicate and hash function are swapped using their copy constructors.

---

==== clear
```c++

void clear() noexcept;

```

擦除容器中所有元素。

[horizontal]
后置条件：;; `size() == 0`
抛出：;; Never throws an exception.

---

==== merge
```c++

template<class H2, class P2>
  void merge(unordered_set<Key, H2, P2, Allocator>& source);
template<class H2, class P2>
  void merge(unordered_set<Key, H2, P2, Allocator>&& source);
template<class H2, class P2>
  void merge(unordered_multiset<Key, H2, P2, Allocator>& source);
template<class H2, class P2>
  void merge(unordered_multiset<Key, H2, P2, Allocator>&& source);

```

Attempt to "merge" two containers by iterating `source` and extracting any node in `source` that is not contained in `*this` and then inserting it into `*this`.

Because `source` can have a different hash function and key equality predicate, the key of each node in `source` is rehashed using `this\->hash_function()` and then, if required, compared using `this\->key_eq()`.

The behavior of this function is undefined if `this\->get_allocator() != source.get_allocator()`.

This function does not copy or move any elements and instead simply relocates the nodes from `source` into `*this`.

[horizontal]
注意：;;
+
--
* Pointers and references to transferred elements remain valid.
* Invalidates iterators to transferred elements.
* Invalidates iterators belonging to `*this`.
* Iterators to non-transferred elements in `source` remain valid.
--

* ---

=== 观察器

==== get_allocator
```

allocator_type get_allocator() const;

```

---

==== hash_function
```

hasher hash_function() const;

```

[horizontal]
返回：;; 容器的哈希函数。

---

==== key_eq

```

key_equal key_eq() const;

```

[horizontal]
返回：;; 容器的键相等谓词

---

=== 查找

==== find
```c++

iterator         find(const key_type& k);
const_iterator   find(const key_type& k) const;
template<class K>
  iterator       find(const K& k);
template<class K>
  const_iterator find(const K& k) const;
template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
  iterator       find(CompatibleKey const& k, CompatibleHash const& hash,
                      CompatiblePredicate const& eq);
template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
  const_iterator find(CompatibleKey const& k, CompatibleHash const& hash,
                      CompatiblePredicate const& eq) const;

```

[horizontal]
返回：;; An iterator pointing to an element with key equivalent to `k`, or `b.end()` if no such element exists.
注意：;; The templated overloads containing `CompatibleKey`, `CompatibleHash` and `CompatiblePredicate` are non-standard extensions which allow you to use a compatible hash function and equality predicate for a key of a different type in order to avoid an expensive type cast. In general, its use is not encouraged and instead the `K` member function templates should be used. +
+
仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== count
```c++

size_type        count(const key_type& k) const;
template<class K>
  size_type      count(const K&极速赛车开奖直播官网 k) const;

```

[horizontal]
返回：;; 键等价于 `k` 的元素数量。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== contains
```c++

bool             contains(const key_type& k) const;
template<class K>
  bool           contains(const K& k) const;

```

[horizontal]
返回：;; 指示容器中是否存在键等于 `key` 的元素的布尔值
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== equal_range
```c++

std::pair<iterator, iterator>               equal_range(const key_type& k);
std::pair<const_iterator, const_iterator>   equal_range(const key_type& k) const;
template<class K>
  std::pair<iterator, iterator>             equal_range(const K& k);
template<class K>
  std::pair<const_iterator, const_iterator> equal_range(const K& k) const;

```

[horizontal]
返回：;; 包含所有键等价于 `k` 的元素的范围。若容器不包含此类元素，则返回 `std::make_pair(b.end(), b.end())`。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

=== 桶接口

==== bucket_count
```c++

size_type bucket_count() const noexcept;

```

[horizontal]
返回：;; The number of buckets.

---

==== max_bucket_count
```c++

size_type max_bucket_count() const noexcept;

```

[horizontal]
返回：;; An upper bound on the number of buckets.

---

==== bucket_size
```c++

size_type bucket_size(size_type n) const;

```

[horizontal]
要求：;; `n < bucket_count()`
返回：;; The number of elements in bucket `n`.

---

==== bucket
```c++

size_type bucket(const key_type& k) const; template<class K> size_type bucket(const K& k) const;

```

[horizontal]
返回：;; The index of the bucket which would contain an element with key `k`.
后置条件：;; The return value is less than `bucket_count()`.
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== begin

```c++

local_iterator begin(size_type n); const_local_iterator begin(size_type n) const;

```

[horizontal]
要求：;; `n` shall be in the range `[0, bucket_count())`.
返回：;; A local iterator pointing the first element in the bucket with index `n`.

---

==== end
```c++

local_iterator end(size_type n); const_local_iterator end(size_type n) const;

```

[horizontal]
要求：;; `n` shall be in the range `[0, bucket_count())`.
返回：;; A local iterator pointing the 'one past the end' element in the bucket with index `n`.

---

==== cbegin
```c++

const_local_iterator cbegin(size_type n) const;

```

[horizontal]
要求：;; `n` shall be in the range `[0, bucket_count())`.
返回：;; A constant local iterator pointing the first element in the bucket with index `n`.

---

==== cend
```c++

const_local_iterator cend(size_type n) const;

```

[horizontal]
要求：;; `n` shall be in the range `[0, bucket_count())`.
返回：;; A constant local iterator pointing the 'one past the end' element in the bucket with index `n`.

---

=== 哈希策略

==== load_factor
```c++

float load_factor() const noexcept;

```

[horizontal]
返回：;; The average number of elements per bucket.

---

==== max_load_factor

```c++

float max_load_factor() const noexcept;

```

[horizontal]
返回：;; Returns the current maximum load factor.

---

==== 设置最大负载因子
```c++

void max_load_factor(float z);

```

[horizontal]
效果：;; Changes the container's maximum load factor, using `z` as a hint.

---

==== rehash
```c++

void rehash(size_type n);

```

Changes the number of buckets so that there are at least `n` buckets, and so that the load factor is less than or equal to the maximum load factor. When applicable, this will either grow or shrink the `bucket_count()` associated with the container.

When `size() == 0`, `rehash(0)` will deallocate the underlying buckets array.

Invalidates iterators, and changes the order of elements. Pointers and references to elements are not invalidated.

[horizontal]
抛出：;; 若抛出异常（除非由容器的哈希函数或比较函数抛出），则该函数无任何效果。

---

==== reserve
```c++

void reserve(size_type n);

```

Equivalent to `a.rehash(ceil(n / a.max_load_factor()))`, or `a.rehash(1)` if `n > 0` and `a.max_load_factor() == std::numeric_limits<float>::infinity()`.

与 `rehash` 类似，此函数可用于增加或减少容器中的桶数量。

Invalidates iterators, and changes the order of elements. Pointers and references to elements are not invalidated.

[horizontal]
抛出：;; 若抛出异常（除非由容器的哈希函数或比较函数抛出），则该函数无任何效果。


=== 推导指引
若满足以下任意条件，则推导指引不参与重载决议：

  - 具有 `InputIterator` 模板参数，且推导出该参数的类型不符合输入迭代器要求。
  - 具有 `Allocator` 模板参数，且推导出该参数的类型不符合分配器要求。
  - 具有 `Hash` 模板参数，且推导出该参数的类型为整型或符合分配器要求。
  - 具有 `Pred` 模板参数，且推导出该参数的类型符合分配器要求。

推导指引中的 `size_type` 参数类型指向由推导指引推导出的容器类型的 `size_type` 成员类型。其默认值与所选构造函数的默认值一致。

==== __迭代器值类型__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __迭代器值类型__ =
    typename std::iterator_traits<InputIterator>::value_type; // 仅用于说明
-----

=== 相等比较

==== operator==
```c++

template<class Key, class Hash, class Pred, class Alloc>
  bool operator==(const unordered_set<Key, Hash, Pred, Alloc>& x,
                  const unordered_set<Key, Hash, Pred, Alloc>& y);

```

若 `x.size() == y.size()` 且对于 `x` 中的每个元素，`y` 中均存在相同键的元素且值相等（使用 `operator==` 比较值类型），则返回 `true`。

[horizontal]
注意：;; 若两个容器的相等谓词不等价，则行为未定义。

---

==== operator!=
```c++

template<class Key, class Hash, class Pred, class Alloc>
  bool operator!=(const unordered_set<Key, Hash, Pred, Alloc>& x,
                  const unordered_set<Key, Hash, Pred, Alloc>& y);

```

若 `x.size() == y.size()` 且对于 `x` 中的每个元素，`y` 中均存在相同键的元素且值相等（使用 `operator==` 比较值类型），则返回 `false`。

[horizontal]
注意：;; 若两个容器的相等谓词不等价，则行为未定义。

---

=== Swap
```c++

template<class Key, class Hash, class Pred, class Alloc>
  void swap(unordered_set<Key, Hash, Pred, Alloc>& x,
            unordered_set<Key, Hash, Pred, Alloc>& y)
    noexcept(noexcept(x.swap(y)));

```

交换 `x` 和 `y` 的内容。

若声明了 `Allocator::propagate_on_container_swap` 且其值为 `true`，则交换容器的分配器；否则，与不同分配器的容器交换将导致未定义行为。

[horizontal]
效果：;; `x.swap(y)`
抛出：;; Doesn't throw an exception unless it is thrown by the copy constructor or copy assignment operator of `key_equal` or `hasher`.
注意：;; The exception specifications aren't quite the same as the C++11 standard, as the equality predicate and hash function are swapped using their copy constructors.

---

=== erase_if
```c++

template<class K, class H, class P, class A, class Predicate>
  typename unordered_set<K, H, P, A>::size_type
    erase_if(unordered_set<K, H, P, A>& c, Predicate pred);

```

遍历容器 `c` 并移除所有满足谓词 `pred` 返回 `true` 的元素。

[horizontal]
返回：;; 被擦除的元素数量。
注意：;; 等价于：
+
```c++

auto original_size = c.size();
for (auto i = c.begin(), last = c.end(); i != last; ) {
  if (pred(*i)) {
    i = c.erase(i);
  } else {
    ++i;
  }
}
return original_size - c.size();

```

=== 序列化

``unordered_set``s can be archived/retrieved by means of link:../../../../../serialization/index.html[Boost.Serialization^] using the API provided by this library. Both regular and XML archives are supported.

==== Saving an unordered_set to an archive

Saves all the elements of an `unordered_set` `x` to an archive (XML archive) `ar`.

[horizontal]
要求：;; `value_type` 需可序列化（XML 可序列化），且支持 Boost.Serialization 的 `save_construct_data`/`load_construct_data` 协议（由可默认构造类型自动支持）。

---

==== Loading an unordered_set from an archive

Deletes all preexisting elements of an `unordered_set` `x` and inserts from an archive (XML archive) `ar` restored copies of the elements of the original `unordered_set` `other` saved to the storage read by `ar`.

[horizontal]
要求：;; `value_type` 需满足可移动插入（MoveInsertable）要求。`x.key_equal()` 在功能上等价于 `other.key_equal()`。
注意：;; If the archive was saved using a release of Boost prior to Boost 1.84, the configuration macro `BOOST_UNORDERED_ENABLE_SERIALIZATION_COMPATIBILITY_V0` has to be globally defined for this operation to succeed; otherwise, an exception is thrown.

---

==== 将迭代器/常量迭代器保存到归档

将迭代器（常量迭代器）`it` 的位置信息保存到归档（XML 归档）`ar` 中。`it` 可以是 `end()` 迭代器。

[horizontal]
要求：;; The `unordered_set` `x` pointed to by `it` has been previously saved to `ar`, and no modifying operations have been issued on `x` between saving of `x` and saving of `it`.

---

==== 从归档加载迭代器/常量迭代器

使迭代器（常量迭代器）`it` 指向原始迭代器（常量迭代器）的还原位置（该位置已保存到归档（XML 归档）`ar` 读取的存储中）。

[horizontal]
要求：;; If `x` is the `unordered_set` `it` points to, no modifying operations have been issued on `x` between loading of `x` and loading of `it`.
