[[header]]

[[content]]
[[unordered_flat_set]]
== 类模板 unordered_flat_set

`boost::unordered_flat_set` ——
一种使用开放寻址法的无序关联容器，用于存储唯一值。

`boost::unordered_flat_set` 的性能远优于 `boost::unordered_set` 或其他
`std::unordered_set`
的实现。与基于节点的标准无序关联容器不同，`boost::unordered_flat_set`
的元素直接存储在桶数组中，插入到已占用桶中的元素会被重定向到原始位置附近的可用桶中。这种数据布局称为__开放寻址法__。

由于采用开放寻址法，`boost::unordered_flat_set` 的接口在多个方面与
`boost::unordered_set`/`std::unordered_set` 有所不同：

* `value_type` 必须是可移动构造的。
* 在重新哈希时不能保持指针稳定性。
* `begin()` 不是常数时间操作。
* 没有用于桶处理（除 `bucket_count` 外）或节点提取/插入的 API。
* 容器的最大负载因子由内部管理，用户无法设置。

除此之外，`boost::unordered_flat_set`
基本上是节点型标准无序关联容器的直接替代品。

[[unordered_flat_set_synopsis]]
=== 概要

....
// #include <boost/unordered/unordered_flat_set.hpp>

namespace boost {
namespace unordered {

  template<class Key,
           class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<Key>>
  class unordered_flat_set {
  public:
    // 类型
    using key_type             = Key;
    using value_type           = Key;
    using init_type            = Key;
    using hasher               = Hash;
    using key_equal            = Pred;
    using allocator_type       = Allocator;
    using pointer              = typename std::allocator_traits<Allocator>::pointer;
    using const_pointer        = typename std::allocator_traits<Allocator>::const_pointer;
    using reference            = value_type&;
    using const_reference      = const value_type&;
    using size_type            = std::size_t;
    using difference_type      = std::ptrdiff_t;

    using iterator             = 实现定义;
    using const_iterator       = 实现定义;

    using stats                = 统计类型; // 如果启用了统计功能\n
    // 构造/复制/销毁
    unordered_flat_set();
    explicit unordered_flat_set(size_type n,
                                const hasher& hf = hasher(),
                                const key_equal& eql = key_equal(),
                                const allocator_type& a = allocator_type());
    template<class InputIterator>
      unordered_flat_set(InputIterator f, InputIterator l,
                         size_type n = 实现定义,
                         const hasher& hf = hasher(),
                         const key_equal& eql = key_equal(),
                         const allocator_type& a = allocator_type());
    unordered_flat_set(const unordered_flat_set& other);
    unordered_flat_set(unordered_flat_set&& other);
    template<class InputIterator>
      unordered_flat_set(InputIterator f, InputIterator l, const allocator_type& a);
    explicit unordered_flat_set(const Allocator& a);
    unordered_flat_set(const unordered_flat_set& other, const Allocator& a);
    unordered_flat_set(concurrent_flat_set<Key, Hash, Pred, Allocator>&& other);
    unordered_flat_set(std::initializer_list<value_type> il,
                       size_type n = 实现定义,
                       const hasher& hf = hasher(),
                       const key_equal& eql = key_equal(),
                       const allocator_type& a = allocator_type());
    unordered_flat_set(size_type n, const allocator_type& a);
    unordered_flat_set(size_type n, const hasher& hf, const allocator_type& a);
    template<class InputIterator>
      unordered_flat_set(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
    template<class InputIterator>
      unordered_flat_set(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                         const allocator_type& a);
    unordered_flat_set(std::initializer_list<value_type> il, const allocator_type& a);
    unordered_flat_set(std::initializer_list<value_type> il, size_type n,
                       const allocator_type& a);
    unordered_flat_set(std::initializer_list<value_type> il, size_type n, const hasher& hf,
                       const allocator_type& a);
    ~unordered_flat_set();
    unordered_flat_set& operator=(const unordered_flat_set& other);
    unordered_flat_set& operator=(unordered_flat_set&& other) noexcept(
      (boost::allocator_traits<Allocator>::is_always_equal::value ||
       boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value) &&
       std::is_same<pointer, value_type*>::value);
    unordered_flat_set& operator=(std::initializer_list<value_type>);
    allocator_type get_allocator() const noexcept;

    // 迭代器
    iterator       begin() noexcept;
    const_iterator begin() const noexcept;
    iterator       end() noexcept;
    const_iterator end() const noexcept;
    const_iterator cbegin() const noexcept;
    const_iterator cend() const noexcept;

    // 容量
    [[nodiscard]] bool empty() const noexcept;
    size_type size() const noexcept;
    size_type max_size() const noexcept;

    // 修改器
    template<class... Args> std::pair<iterator, bool> emplace(Args&&... args);
    template<class... Args> iterator emplace_hint(const_iterator position, Args&&... args);
    std::pair<iterator, bool> insert(const value_type& obj);
    std::pair<iterator, bool> insert(value_type&& obj);
    template<class K> std::pair<iterator, bool> insert(K&& k);
    iterator insert(const_iterator hint, const value_type& obj);
    iterator insert(const_iterator hint, value_type&& obj);
    template<class K> iterator insert(const_iterator hint, K&& k);
    template<class InputIterator> void insert(InputIterator first, InputIterator last);
    void insert(std::initializer_list<value_type>);

    可转换为迭代器     erase(iterator position);
    可转换为迭代器     erase(const_iterator position);
    size_type                   erase(const key_type& k);
    template<class K> size_type erase(K&& k);
    iterator  erase(const_iterator first, const_iterator last);
    void      swap(unordered_flat_set& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
               boost::allocator_traits<Allocator>::propagate_on_container_swap::value);
    init_type pull(const_iterator position);
    void      clear() noexcept;

    template<class H2, class P2>
      void merge(unordered_flat_set<Key, T, H2, P2, Allocator>& source);
    template<class H2, class P2>
      void merge(unordered_flat_set<Key, T, H2, P2, Allocator>&& source);

    // 观察器
    hasher hash_function() const;
    key_equal key_eq() const;

    // 集合操作
    iterator         find(const key_type& k);
    const_iterator   find(const key_type& k) const;
    template<class K>
      iterator       find(const K& k);
    template<class K>
      const_iterator find(const K& k) const;
    size_type        count(const key_type& k) const;
    template<class K>
      size_type      count(const K& k) const;
    bool             contains(const key_type& k) const;
    template<class K>
      bool           contains(const K& k) const;
    std::pair<iterator, iterator>               equal_range(const key_type& k);
    std::pair<const_iterator, const_iterator>   equal_range(const key_type& k) const;
    template<class K>
      std::pair<iterator, iterator>             equal_range(const K& k);
    template<class K>
      std::pair<const_iterator, const_iterator> equal_range(const K& k) const;

    // 桶接口
    size_type bucket_count() const noexcept;

    // 哈希策略
    float load_factor() const noexcept;
    float max_load_factor() const noexcept;
    void max_load_factor(float z);
    size_type max_load() const noexcept;
    void rehash(size_type n);
    void reserve(size_type n);

    // 统计（如果启用）
    stats get_stats() const;
    void reset_stats() noexcept;
  };

  // 推导指引
  template<class InputIterator,
           class Hash = boost::hash<迭代器值类型<InputIterator>>,
           class Pred = std::equal_to<迭代器值类型<InputIterator>>,
           class Allocator = std::allocator<迭代器值类型<InputIterator>>>
    unordered_flat_set(InputIterator, InputIterator, typename 见下文::size_type = 见下文,
                       Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> unordered_flat_set<迭代器值类型<InputIterator>, Hash, Pred, Allocator>;

  template<class T, class Hash = boost::hash<T>, class Pred = std::equal_to<T>,
           class Allocator = std::allocator<T>>
    unordered_flat_set(std::initializer_list<T>, typename 见下文::size_type = 见下文,
                       Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> unordered_flat_set<T, Hash, Pred, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_flat_set(InputIterator, InputIterator, typename 见下文::size_type, Allocator)
      -> unordered_flat_set<迭代器值类型<InputIterator>,
                            boost::hash<迭代器值类型<InputIterator>>,
                            std::equal_to<迭代器值类型<InputIterator>>, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_flat_set(InputIterator, InputIterator, Allocator)
      -> unordered_flat_set<迭代器值类型<InputIterator>,
                            boost::hash<迭代器值类型<InputIterator>>,
                            std::equal_to<迭代器值类型<InputIterator>>, Allocator>;

  template<class InputIterator, class Hash, class Allocator>
    unordered_flat_set(InputIterator, InputIterator, typename 见下文::size_type, Hash,
                       Allocator)
      -> unordered_flat_set<迭代器值类型<InputIterator>, Hash,
                            std::equal_to<迭代器值类型<InputIterator>>, Allocator>;

  template<class T, class Allocator>
    unordered_flat_set(std::initializer_list<T>, typename 见下文::size_type, Allocator)
      -> unordered_flat_set<T, boost::hash<T>, std::equal_to<T>, Allocator>;

  template<class T, class Allocator>
    unordered_flat_set(std::initializer_list<T>, Allocator)
      -> unordered_flat_set<T, boost::hash<T>, std::equal_to<T>, Allocator>;

  template<class T, class Hash, class Allocator>
    unordered_flat_set(std::initializer_list<T>, typename 见下文::size_type, Hash, Allocator)
      -> unordered_flat_set<T, Hash, std::equal_to<T>, Allocator>;

} // namespace unordered
} // namespace boost
....

'''''

[[unordered_flat_set_description]]
=== 描述

*模板参数*

[width="100%",cols="50%,50%",]
|===
|_Key_ |`Key`
必须可https://en.cppreference.com/w/cpp/named_req/MoveInsertable[移动插入]到容器中，并且可https://en.cppreference.com/w/cpp/named_req/Erasable[擦除]。

|_Hash_ |一个一元函数对象类型，用作 `Key` 的哈希函数。它接受一个类型为
`Key` 的参数，并返回一个类型为 `std::size_t` 的值。

|_Pred_ |一个二元函数对象，用于在类型为 `Key`
的值上诱导等价关系。它接受两个类型为 `Key` 的参数，并返回一个类型为
`bool` 的值。

|_Allocator_
|一个分配器，其值类型与容器的值类型相同。支持使用https://en.cppreference.com/w/cpp/named_req/Allocator#Fancy_pointers[花式指针]的分配器。
|===

容器的元素保存在内部的__桶数组__中。元素根据其哈希码插入到确定的桶中，但如果桶已被占用（_冲突_），则使用原始位置附近的可用桶。

桶数组的大小可以通过调用 `insert`/`emplace` 自动增加，或者通过调用
`rehash`/`reserve`
来增加。容器的__负载因子__（元素数量除以桶数量）永远不会大于
`max_load_factor()`，除了可能在小尺寸时，实现可能允许更高的负载。

如果
link:../../../../../container_hash/doc/html/hash.html#ref_hash_is_avalanchinghash[`hash_is_avalanching`]`<Hash>::value`
为
`true`，则直接使用哈希函数；否则，会添加一个位混合后处理阶段，以增加哈希质量，但会带来额外的计算成本。

'''''

[[unordered_flat_set_configuration_macros]]
=== 配置宏

[[unordered_flat_set_boost_unordered_enable_stats]]
==== `BOOST_UNORDERED_ENABLE_STATS`

全局定义此宏以启用容器的link:reference/stats.html#stats[统计计算]。请注意，此选项会降低许多操作的总体性能。

'''''

[[unordered_flat_set_typedefs]]
=== 类型定义

[source,highlight]
----
typedef 实现定义 iterator;
----

一个常量迭代器，其值类型为 `value_type`。

迭代器类别至少是前向迭代器。

可转换为 `const_iterator`。

'''''

[source,highlight]
----
typedef 实现定义 const_iterator;
----

一个常量迭代器，其值类型为 `value_type`。

迭代器类别至少是前向迭代器。

[[unordered_flat_set_constructors]]
=== 构造函数

[[unordered_flat_set_default_constructor]]
==== 默认构造函数

[source,highlight]
----
unordered_flat_set();
----

使用 `hasher()` 作为哈希函数、`key_equal()`
作为键相等谓词、`allocator_type()` 作为分配器构造一个空容器。

[cols=",",]
|===
|后置条件： |`size() == 0`

|要求： |如果使用默认值，则 `hasher`、`key_equal` 和 `allocator_type`
需要是https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造的]。
|===

'''''

[[unordered_flat_set_bucket_count_constructor]]
==== 桶数量构造函数

[source,highlight]
----
explicit unordered_flat_set(size_type n,
                            const hasher& hf = hasher(),
                            const key_equal& eql = key_equal(),
                            const allocator_type& a = allocator_type());
----

使用 `hf` 作为哈希函数、`eql` 作为键相等谓词、`a`
作为分配器，构造一个至少包含 `n` 个桶的空容器。

[cols=",",]
|===
|后置条件： |`size() == 0`

|要求： |如果使用默认值，则 `hasher`、`key_equal` 和 `allocator_type`
需要是https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造的]。
|===

'''''

[[unordered_flat_set_iterator_range_constructor]]
==== 迭代器范围构造函数

[source,highlight]
----
template<class InputIterator>
  unordered_flat_set(InputIterator f, InputIterator l,
                     size_type n = 实现定义,
                     const hasher& hf = hasher(),
                     const key_equal& eql = key_equal(),
                     const allocator_type& a = allocator_type());
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、`eql`
作为键相等谓词、`a` 作为分配器，并将 `[f, l)` 范围内的元素插入其中。

[cols=",",]
|===
|要求： |如果使用默认值，则 `hasher`、`key_equal` 和 `allocator_type`
需要是https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造的]。
|===

'''''

[[unordered_flat_set_copy_constructor]]
==== 复制构造函数

[source,highlight]
----
unordered_flat_set(unordered_flat_set const& other);
----

复制构造函数。复制包含的元素、哈希函数、谓词和分配器。

如果 `Allocator::select_on_container_copy_construction`
存在且签名正确，则分配器将从其结果构造。

[cols=",",]
|===
|要求： |`value_type` 是可复制构造的
|===

'''''

[[unordered_flat_set_move_constructor]]
==== 移动构造函数

[source,highlight]
----
unordered_flat_set(unordered_flat_set&& other);
----

移动构造函数。`other`
的内部桶数组直接转移到新容器。哈希函数、谓词和分配器从 `other`
移动构造。如果link:#unordered_flat_set_boost_unordered_enable_stats[启用]了统计功能，则从
`other` 转移内部统计信息并调用 `other.reset_stats()`。

'''''

[[unordered_flat_set_iterator_range_constructor_with_allocator]]
==== 带分配器的迭代器范围构造函数

[source,highlight]
----
template<class InputIterator>
  unordered_flat_set(InputIterator f, InputIterator l, const allocator_type& a);
----

使用 `a` 作为分配器构造一个空容器，使用默认的哈希函数和键相等谓词，并将
`[f, l)` 范围内的元素插入其中。

[cols=",",]
|===
|要求： |`hasher` 和 `key_equal`
需要是https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造的]。
|===

'''''

[[unordered_flat_set_allocator_constructor]]
==== 分配器构造函数

[source,highlight]
----
explicit unordered_flat_set(Allocator const& a);
----

使用分配器 `a` 构造一个空容器。

'''''

[[unordered_flat_set_copy_constructor_with_allocator]]
==== 带分配器的复制构造函数

[source,highlight]
----
unordered_flat_set(unordered_flat_set const& other, Allocator const& a);
----

构造一个容器，复制 `other` 包含的元素、哈希函数和谓词，但使用分配器
`a`。

'''''

[[unordered_flat_set_move_constructor_with_allocator]]
==== 带分配器的移动构造函数

[source,highlight]
----
unordered_flat_set(unordered_flat_set&& other, Allocator const& a);
----

如果 `a == other.get_allocator()`，则 `other`
的元素直接转移到新容器；否则，元素从 `other`
的元素移动构造。哈希函数和谓词从 `other` 移动构造，分配器从 `a`
复制构造。如果link:#unordered_flat_set_boost_unordered_enable_stats[启用]了统计功能，则当
`a == other.get_allocator()` 时转移内部统计信息，并始终调用
`other.reset_stats()`。

'''''

[[unordered_flat_set_move_constructor_from_concurrent_flat_set]]
==== 从 concurrent_flat_set 的移动构造函数

[source,highlight]
----
unordered_flat_set(concurrent_flat_set<Key, Hash, Pred, Allocator>&& other);
----

从 link:#concurrent_flat_set[`concurrent_flat_set`] 移动构造。`other`
的内部桶数组直接转移到新容器。哈希函数、谓词和分配器从 `other`
移动构造。如果link:#unordered_flat_set_boost_unordered_enable_stats[启用]了统计功能，则从
`other` 转移内部统计信息并调用 `other.reset_stats()`。

[cols=",",]
|===
|复杂度： |常数时间。
|并发性： |在 `other` 上阻塞。
|===

'''''

[[unordered_flat_set_initializer_list_constructor]]
==== 初始化列表构造函数

[source,highlight]
----
unordered_flat_set(std::initializer_list<value_type> il,
              size_type n = 实现定义,
              const hasher& hf = hasher(),
              const key_equal& eql = key_equal(),
              const allocator_type& a = allocator_type());
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、`eql`
作为键相等谓词和 `a` 作为分配器，并将 `il` 中的元素插入其中。

[cols=",",]
|===
|要求： |如果使用默认值，则 `hasher`、`key_equal` 和 `allocator_type`
需要是https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造的]。
|===

'''''

[[unordered_flat_set_bucket_count_constructor_with_allocator]]
==== 带分配器的桶数量构造函数

[source,highlight]
----
unordered_flat_set(size_type n, allocator_type const& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf`
作为哈希函数（但实际使用默认哈希函数）、默认的哈希函数和键相等谓词，以及
`a` 作为分配器。

[cols=",",]
|===
|后置条件： |`size() == 0`

|要求： |`hasher` 和 `key_equal`
需要是https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造的]。
|===

'''''

[[unordered_flat_set_bucket_count_constructor_with_hasher_and_allocator]]
==== 带哈希函数与分配器的桶数量构造函数

[source,highlight]
----
unordered_flat_set(size_type n, hasher const& hf, allocator_type const& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf`
作为哈希函数、默认的键相等谓词和 `a` 作为分配器。

[cols=",",]
|===
|后置条件： |`size() == 0`

|要求： |`key_equal`
需要是https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造的]。
|===

'''''

[[unordered_flat_set_iterator_range_constructor_with_bucket_count_and_allocator]]
==== 带桶数量和分配器的迭代器范围构造函数

[source,highlight]
----
template<class InputIterator>
  unordered_flat_set(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `a`
作为分配器以及默认的哈希函数和键相等谓词，并将 `[f, l)`
范围内的元素插入其中。

[cols=",",]
|===
|要求： |`hasher` 和 `key_equal`
需要是https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造的]。
|===

'''''

[[unordered_flat_set_iterator_range_constructor_with_bucket_count_and_hasher]]
==== 带桶数量和哈希器的迭代器范围构造函数

[source,highlight]
----
    template<class InputIterator>
      unordered_flat_set(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                         const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、`a`
作为分配器以及默认的键相等谓词，并将 `[f, l)` 范围内的元素插入其中。

[cols=",",]
|===
|要求： |`key_equal`
需要是https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造的]。
|===

'''''

[[unordered_flat_set_initializer_list_constructor_with_allocator]]
==== 带分配器的初始化列表构造函数

[source,highlight]
----
unordered_flat_set(std::initializer_list<value_type> il, const allocator_type& a);
----

使用 `a` 以及默认的哈希函数和键相等谓词构造一个空容器，并将 `il`
中的元素插入其中。

[cols=",",]
|===
|要求： |`hasher` 和 `key_equal`
需要是https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造的]。
|===

'''''

[[unordered_flat_set_initializer_list_constructor_with_bucket_count_and_allocator]]
==== 带桶数量和分配器的初始化列表构造函数

[source,highlight]
----
unordered_flat_set(std::initializer_list<value_type> il, size_type n, const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `a`
以及默认的哈希函数和键相等谓词，并将 `il` 中的元素插入其中。

[cols=",",]
|===
|要求： |`hasher` 和 `key_equal`
需要是https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造的]。
|===

'''''

[[unordered_flat_set_initializer_list_constructor_with_bucket_count_and_hasher_and_allocator]]
==== 带桶数量、哈希函数与分配器的初始化列表构造函数

[source,highlight]
----
unordered_flat_set(std::initializer_list<value_type> il, size_type n, const hasher& hf,
                   const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、`a`
作为分配器以及默认的键相等谓词，并将 `il` 中的元素插入其中。

[cols=",",]
|===
|要求： |`key_equal`
需要是https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造的]。
|===

'''''

[[unordered_flat_set_destructor]]
=== 析构函数

[source,highlight]
----
~unordered_flat_set();
----

[cols=",",]
|===
|注意： |析构函数会作用于每个元素，并释放所有内存。
|===

'''''

[[unordered_flat_set_assignment]]
=== 赋值

[[unordered_flat_set_copy_assignment]]
==== 复制赋值

[source,highlight]
----
unordered_flat_set& operator=(unordered_flat_set const& other);
----

赋值运算符。销毁先前存在的元素，从 `other` 复制赋值哈希函数和谓词，如果
`Alloc::propagate_on_container_copy_assignment` 存在且
`Alloc::propagate_on_container_copy_assignment::value` 为 `true`，则从
`other` 复制赋值分配器，最后插入 `other` 元素的副本。

[cols=",",]
|===
|要求： |`value_type`
是https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入的]
|===

'''''

[[unordered_flat_set_move_assignment]]
==== 移动赋值

[source,highlight]
----
unordered_flat_set& operator=(unordered_flat_set&& other)
  noexcept((boost::allocator_traits<Allocator>::is_always_equal::value ||
            boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value) &&
            std::is_same<pointer, value_type*>::value);
----

移动赋值运算符。销毁先前存在的元素，交换 `other` 的哈希函数和谓词，如果
`Alloc::propagate_on_container_move_assignment` 存在且
`Alloc::propagate_on_container_move_assignment::value` 为 `true`，则从
`other` 移动赋值分配器。如果此时分配器等于 `other.get_allocator()`，则
`other` 的内部桶数组直接转移到新容器；否则，插入 `other`
元素的移动构造副本。如果link:#unordered_flat_set_boost_unordered_enable_stats[启用]了统计功能，则当最终分配器等于
`other.get_allocator()` 时从 `other` 转移内部统计信息，并始终调用
`other.reset_stats()`。

'''''

[[unordered_flat_set_initializer_list_assignment]]
==== 初始化列表赋值

[source,highlight]
----
unordered_flat_set& operator=(std::initializer_list<value_type> il);
----

从初始化列表中的值赋值。销毁所有先前存在的元素。

[cols=",",]
|===
|要求： |`value_type`
是https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入的]
|===

[[unordered_flat_set_iterators]]
=== 迭代器

[[unordered_flat_set_begin]]
==== begin

[source,highlight]
----
iterator begin() noexcept;
const_iterator begin() const noexcept;
----

[cols=",",]
|===
|返回：
|返回指向容器首元素的迭代器；若容器为空，则返回容器的结束迭代器。

|复杂度： |O(`bucket_count()`)
|===

'''''

[[unordered_flat_set_end]]
==== end

[source,highlight]
----
iterator end() noexcept;
const_iterator end() const noexcept;
----

[cols=",",]
|===
|返回： |返回指向容器结束位置的迭代器。
|===

'''''

[[unordered_flat_set_cbegin]]
==== cbegin

[source,highlight]
----
const_iterator cbegin() const noexcept;
----

[cols=",",]
|===
|返回：
|`const_iterator`为一种返回指向容器第一个元素的常量迭代器，如果容器为空，则返回容器的结束迭代器。

|复杂度： |O(`bucket_count()`)
|===

'''''

[[unordered_flat_set_cend]]
==== cend

[source,highlight]
----
const_iterator cend() const noexcept;
----

[cols=",",]
|===
|返回： |返回一个指向容器结束位置的 `const_iterator` 常量迭代器。
|===

'''''

[[unordered_flat_set_size_and_capacity]]
=== 大小与容量

[[unordered_flat_set_empty]]
==== empty

[source,highlight]
----
[[nodiscard]] bool empty() const noexcept;
----

[cols=",",]
|===
|返回： |`size() == 0`
|===

'''''

[[unordered_flat_set_size]]
==== 大小

[source,highlight]
----
size_type size() const noexcept;
----

[cols=",",]
|===
|返回： |`std::distance(begin(), end())`
|===

'''''

[[unordered_flat_set_max_size]]
==== max_size

[source,highlight]
----
size_type max_size() const noexcept;
----

[cols=",",]
|===
|返回： |容器最大可能的 `size()`值。
|===

'''''

[[unordered_flat_set_modifiers]]
=== 修改器

[[unordered_flat_set_emplace]]
==== emplace

[source,highlight]
----
template<class... Args> std::pair<iterator, bool> emplace(Args&&... args);
----

如果容器中没有等效键的元素，则插入一个使用参数 `args` 构造的对象。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type` 可从 `args` 构造。

|返回： a|
如果插入发生，则返回类型的 `bool` 分量为 `true`。 +

如果插入发生，则迭代器指向新插入的元素；否则，指向具有等效键的元素。

|抛出： |如果调用 `hasher` 以外的操作抛出异常，则函数无效果。

|注意：
|可能使迭代器、指针和引用失效，但仅当插入导致负载大于最大负载时。 +
|===

'''''

[[unordered_flat_set_emplace_hint]]
==== emplace_hint

[source,highlight]
----
    template<class... Args> iterator emplace_hint(const_iterator position, Args&&... args);
----

如果容器中没有等效键的元素，则插入一个使用参数 `args` 构造的对象。

`position` 是插入位置的建议。此实现忽略它。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type` 可从 `args` 构造。

|返回： a|
如果插入发生，则返回类型的 `bool` 分量为 `true`。 +

如果插入发生，则迭代器指向新插入的元素；否则，指向具有等效键的元素。

|抛出： |如果调用 `hasher` 以外的操作抛出异常，则函数无效果。

|注意：
|可能使迭代器、指针和引用失效，但仅当插入导致负载大于最大负载时。 +
|===

'''''

[[unordered_flat_set_copy_insert]]
==== 复制插入

[source,highlight]
----
std::pair<iterator, bool> insert(const value_type& obj);
----

如果容器中没有等效键的元素，则插入 `obj`。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type`
是https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入的]。

|返回： a|
如果插入发生，则返回类型的 `bool` 分量为 `true`。 +

如果插入发生，则迭代器指向新插入的元素；否则，指向具有等效键的元素。

|抛出： |如果调用 `hasher` 以外的操作抛出异常，则函数无效果。

|注意：
|可能使迭代器、指针和引用失效，但仅当插入导致负载大于最大负载时。
|===

'''''

[[unordered_flat_set_move_insert]]
==== 移动插入

[source,highlight]
----
std::pair<iterator, bool> insert(value_type&& obj);
----

如果容器中没有等效键的元素，则插入 `obj`。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type`
是https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入的]。

|返回： a|
如果插入发生，则返回类型的 `bool` 分量为 `true`。 +

如果插入发生，则迭代器指向新插入的元素；否则，指向具有等效键的元素。

|抛出： |如果调用 `hasher` 以外的操作抛出异常，则函数无效果。

|注意：
|可能使迭代器、指针和引用失效，但仅当插入导致负载大于最大负载时。
|===

'''''

[[unordered_flat_set_transparent_insert]]
==== 透明插入

[source,highlight]
----
template<class K> std::pair<iterator, bool> insert(K&& k);
----

如果容器中没有等效键的元素，则插入一个从 `std::forward<K>(k)`
构造的元素。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type` 可从 `k`
https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[就地构造]。

|返回： a|
如果插入发生，则返回类型的 `bool` 分量为 `true`。 +

如果插入发生，则迭代器指向新插入的元素；否则，指向具有等效键的元素。

|抛出： |如果调用 `hasher` 以外的操作抛出异常，则函数无效果。

|注意： a|
可能使迭代器、指针和引用失效，但仅当插入导致负载大于最大负载时。 +

仅当 `Hash::is_transparent` 和 `Pred::is_transparent`
是有效的成员类型定义，且 `iterator` 和 `const_iterator` 都不能从 `K`
隐式转换时，此重载才参与重载决议。库假定 `Hash` 可同时用 `K` 和 `Key`
调用，且 `Pred` 是透明的。这启用了异构查找，避免了实例化 `Key`
类型的成本。

|===

'''''

[[unordered_flat_set_copy_insert_with_hint]]
==== 带提示的复制插入

[source,highlight]
----
iterator insert(const_iterator hint, const value_type& obj);
----

如果容器中没有等效键的元素，则插入 `obj`。

`hint` 是插入位置的建议。此实现忽略它。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type`
是https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入的]。

|返回： a|
如果插入发生，则返回类型的 `bool` 分量为 `true`。 +

如果插入发生，则迭代器指向新插入的元素；否则，指向具有等效键的元素。

|抛出： |如果调用 `hasher` 以外的操作抛出异常，则函数无效果。

|注意：
|可能使迭代器、指针和引用失效，但仅当插入导致负载大于最大负载时。
|===

'''''

[[unordered_flat_set_move_insert_with_hint]]
==== 带提示的移动插入

[source,highlight]
----
iterator insert(const_iterator hint, value_type&& obj);
----

如果容器中没有等效键的元素，则插入 `obj`。

`hint` 是插入位置的建议。此实现忽略它。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type`
是https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入的]。

|返回： a|
如果插入发生，则返回类型的 `bool` 分量为 `true`。 +

如果插入发生，则迭代器指向新插入的元素；否则，指向具有等效键的元素。

|抛出： |如果调用 `hasher` 以外的操作抛出异常，则函数无效果。

|注意：
|可能使迭代器、指针和引用失效，但仅当插入导致负载大于最大负载时。
|===

'''''

[[unordered_flat_set_transparent_insert_with_hint]]
==== 带提示的透明插入

[source,highlight]
----
template<class K> std::pair<iterator, bool> insert(const_iterator hint, K&& k);
----

如果容器中没有等效键的元素，则插入一个从 `std::forward<K>(k)`
构造的元素。

`hint` 是插入位置的建议。此实现忽略它。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type` 可从 `k`
https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[就地构造]。

|返回： a|
如果插入发生，则返回类型的 `bool` 分量为 `true`。 +

如果插入发生，则迭代器指向新插入的元素；否则，指向具有等效键的元素。

|抛出： |如果调用 `hasher` 以外的操作抛出异常，则函数无效果。

|注意： a|
可能使迭代器、指针和引用失效，但仅当插入导致负载大于最大负载时。 +

仅当 `Hash::is_transparent` 和 `Pred::is_transparent`
是有效的成员类型定义，且 `iterator` 和 `const_iterator` 都不能从 `K`
隐式转换时，此重载才参与重载决议。库假定 `Hash` 可同时用 `K` 和 `Key`
调用，且 `Pred` 是透明的。这启用了异构查找，避免了实例化 `Key`
类型的成本。

|===

'''''

[[unordered_flat_set_insert_iterator_range]]
==== 插入迭代器范围

[source,highlight]
----
template<class InputIterator> void insert(InputIterator first, InputIterator last);
----

将一系列元素插入容器中。仅当容器中没有等效键的元素时，才会插入元素。

[cols=",",]
|===
|要求： |`value_type` 可从 `*first`
https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[就地构造]到容器中。

|抛出： |当插入单个元素时，如果调用 `hasher`
以外的操作抛出异常，则函数无效果。

|注意：
|可能使迭代器、指针和引用失效，但仅当插入导致负载大于最大负载时。
|===

'''''

[[unordered_flat_set_insert_initializer_list]]
==== 插入初始化列表

[source,highlight]
----
void insert(std::initializer_list<value_type>);
----

将一系列元素插入容器中。仅当容器中没有等效键的元素时，才会插入元素。

[cols=",",]
|===
|要求： |`value_type`
是https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入]到容器中的。

|抛出： |当插入单个元素时，如果调用 `hasher`
以外的操作抛出异常，则函数无效果。

|注意：
|可能使迭代器、指针和引用失效，但仅当插入导致负载大于最大负载时。
|===

'''''

[[unordered_flat_set_erase_by_position]]
==== 按位置擦除

[source,highlight]
----
可转换为迭代器 erase(iterator position);
可转换为迭代器 erase(const_iterator position);
----

擦除 `position` 指向的元素。

[cols=",",]
|===
|返回： |一个不透明对象，可隐式转换为擦除前 `position` 之后紧邻的
`iterator` 或 `const_iterator`。

|抛出： |无。

|注意： |返回的不透明对象必须仅被丢弃或立即转换为 `iterator` 或
`const_iterator`。
|===

'''''

[[unordered_flat_set_erase_by_key]]
==== 按键擦除

[source,highlight]
----
size_type erase(const key_type& k);
template<class K> size_type erase(K&& k);
----

擦除所有键等效于 `k` 的元素。

[cols=",",]
|===
|返回： |擦除的元素数量。

|抛出： |仅当 `hasher` 或 `key_equal` 抛出异常时抛出。

|注意： |仅当 `Hash::is_transparent` 和 `Pred::is_transparent`
是有效的成员类型定义，且 `iterator` 和 `const_iterator` 都不能从 `K`
隐式转换时，`template<class K>` 重载才参与重载决议。库假定 `Hash`
可同时用 `K` 和 `Key` 调用，且 `Pred`
是透明的。这启用了异构查找，避免了实例化 `Key` 类型的成本。
|===

'''''

[[unordered_flat_set_erase_range]]
==== 范围擦除

[source,highlight]
----
iterator erase(const_iterator first, const_iterator last);
----

擦除从 `first` 到 `last` 范围内的元素。

[cols=",",]
|===
|返回： |指向被擦除元素之后元素的迭代器——即 `last`。
|抛出： |此实现中无抛出（既不调用 `hasher` 也不调用 `key_equal` 对象）。
|===

'''''

[[unordered_flat_set_swap]]
==== swap

[source,highlight]
----
void swap(unordered_flat_set& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
           boost::allocator_traits<Allocator>::propagate_on_container_swap::value);
----

将容器的内容与参数交换。

如果声明了 `Allocator::propagate_on_container_swap` 且
`Allocator::propagate_on_container_swap::value` 为
`true`，则交换容器的分配器。否则，与不相等分配器交换会导致未定义行为。

[cols=",",]
|===
|抛出： |除非 `key_equal` 或 `hasher` 在交换时抛出，否则无抛出。
|===

'''''

[[unordered_flat_set_pull]]
==== pull

[source,highlight]
----
init_type pull(const_iterator position);
----

从 `position` 指向的元素移动构造一个 `init_value` `x`，擦除该元素并返回
`x`。

'''''

[[unordered_flat_set_clear]]
==== clear

[source,highlight]
----
void clear() noexcept;
----

擦除容器中的所有元素。

[cols=",",]
|===
|后置条件：
|`size() == 0`，`max_load() >= max_load_factor() * bucket_count()`
|===

'''''

[[unordered_flat_set_merge]]
==== merge

[source,highlight]
----
template<class H2, class P2>
  void merge(unordered_flat_set<Key, T, H2, P2, Allocator>& source);
template<class H2, class P2>
  void merge(unordered_flat_set<Key, T, H2, P2, Allocator>&& source);
----

将 `source` 中键尚未存在于 `*this` 的所有元素移动插入，并从 `source`
中擦除它们。

'''''

[[unordered_flat_set_observers]]
=== 观察器

[[unordered_flat_set_get_allocator]]
==== get_allocator

[source,highlight]
----
allocator_type get_allocator() const noexcept;
----

[cols=",",]
|===
|返回： |容器的分配器。
|===

'''''

[[unordered_flat_set_hash_function]]
==== hash_function

[source,highlight]
----
hasher hash_function() const;
----

[cols=",",]
|===
|返回： |容器的哈希函数。
|===

'''''

[[unordered_flat_set_key_eq]]
==== key_eq

[source,highlight]
----
key_equal key_eq() const;
----

[cols=",",]
|===
|返回： |容器的键相等谓词。
|===

'''''

[[unordered_flat_set_lookup]]
=== 查找

[[unordered_flat_set_find]]
==== find

[source,highlight]
----
iterator         find(const key_type& k);
const_iterator   find(const key_type& k) const;
template<class K>
  iterator       find(const K& k);
----

[cols=",",]
|===
|返回： |指向键等效于 `k` 的元素的迭代器，如果不存在则返回 `end()`。

|注意： |仅当 `Hash::is_transparent` 和 `Pred::is_transparent`
是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定
`Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred`
是透明的。这启用了异构查找，避免了实例化 `Key` 类型的成本。
|===

'''''

[[unordered_flat_set_count]]
==== count

[source,highlight]
----
size_type        count(const key_type& k) const;
template<class K>
  size_type      count(const K& k) const;
----

[cols=",",]
|===
|返回： |键等效于 `k` 的元素数量。

|注意： |仅当 `Hash::is_transparent` 和 `Pred::is_transparent`
是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定
`Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred`
是透明的。这启用了异构查找，避免了实例化 `Key` 类型的成本。
|===

'''''

[[unordered_flat_set_contains]]
==== contains

[source,highlight]
----
bool             contains(const key_type& k) const;
template<class K>
  bool           contains(const K& k) const;
----

[cols=",",]
|===
|返回： |一个布尔值，指示容器中是否存在键等于 `key` 的元素。

|注意： |仅当 `Hash::is_transparent` 和 `Pred::is_transparent`
是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定
`Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred`
是透明的。这启用了异构查找，避免了实例化 `Key` 类型的成本。
|===

'''''

[[unordered_flat_set_equal_range]]
==== equal_range

[source,highlight]
----
std::pair<iterator, iterator>               equal_range(const key_type& k);
std::pair<const_iterator, const_iterator>   equal_range(const key_type& k) const;
template<class K>
  std::pair<iterator, iterator>             equal_range(const K& k);
template<class K>
  std::pair<const_iterator, const_iterator> equal_range(const K& k) const;
----

[cols=",",]
|===
|返回： |包含所有键等效于 `k`
的元素的区间。如果容器不包含任何此类元素，则返回
`std::make_pair(b.end(), b.end())`。

|注意： |仅当 `Hash::is_transparent` 和 `Pred::is_transparent`
是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定
`Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred`
是透明的。这启用了异构查找，避免了实例化 `Key` 类型的成本。
|===

'''''

[[unordered_flat_set_bucket_interface]]
=== 桶接口

[[unordered_flat_set_bucket_count]]
==== bucket_count

[source,highlight]
----
size_type bucket_count() const noexcept;
----

[cols=",",]
|===
|返回： |桶数组的大小。
|===

'''''

[[unordered_flat_set_hash_policy]]
=== 哈希策略

[[unordered_flat_set_load_factor]]
==== load_factor

[source,highlight]
----
float load_factor() const noexcept;
----

[cols=",",]
|===
|返回：
|`static_cast<float>(size())/static_cast<float>(bucket_count())`，如果
`bucket_count() == 0` 则返回 `0`。
|===

'''''

[[unordered_flat_set_max_load_factor]]
==== max_load_factor

[source,highlight]
----
float max_load_factor() const noexcept;
----

[cols=",",]
|===
|返回： |返回容器的最大负载因子。
|===

'''''

[[unordered_flat_set_set_max_load_factor]]
==== Set max_load_factor

[source,highlight]
----
void max_load_factor(float z);
----

[cols=",",]
|===
|效果： |无操作，因为用户不允许更改此参数。保留以兼容
`boost::unordered_set`。
|===

'''''

[[unordered_flat_set_max_load]]
==== max_load

[source,highlight]
----
size_type max_load() const noexcept;
----

[cols=",",]
|===
|返回：
|容器在不重新哈希的情况下可容纳的最大元素数，假设不再有元素被擦除。

|注意： |构造、重新哈希或清空后，容器的最大负载至少为
`max_load_factor() * bucket_count()`。在高负载条件下擦除时，此数字可能减少。
|===

'''''

[[unordered_flat_set_rehash]]
==== rehash

[source,highlight]
----
void rehash(size_type n);
----

如有必要，更改桶数组的大小，使桶数至少为
`n`，且负载因子小于或等于最大负载因子。适用时，这将增加或减少与容器关联的
`bucket_count()`。

当 `size() == 0` 时，`rehash(0)`
将释放底层桶数组。如果提供的分配器使用花式指针，则随后执行默认分配。

使迭代器、指针和引用失效，并改变元素顺序。

[cols=",",]
|===
|抛出：
|如果抛出异常，则函数无效果，除非异常由容器的哈希函数或比较函数抛出。
|===

'''''

[[unordered_flat_set_reserve]]
==== reserve

[source,highlight]
----
void reserve(size_type n);
----

等效于 `a.rehash(ceil(n / a.max_load_factor()))`。

类似于 `rehash`，此函数可用于增加或减少容器中的桶数。

使迭代器、指针和引用失效，并改变元素顺序。

[cols=",",]
|===
|抛出：
|如果抛出异常，则函数无效果，除非异常由容器的哈希函数或比较函数抛出。
|===

'''''

[[unordered_flat_set_statistics]]
=== 统计

[[unordered_flat_set_get_stats]]
==== get_stats

[source,highlight]
----
stats get_stats() const;
----

[cols=",",]
|===
|返回： |容器迄今为止执行的插入和查找操作的统计描述。

|注意：
|仅当link:reference/stats.html#stats[统计计算]被link:#unordered_flat_set_boost_unordered_enable_stats[启用]时可用。
|===

'''''

[[unordered_flat_set_reset_stats]]
==== reset_stats

[source,highlight]
----
void reset_stats() noexcept;
----

[cols=",",]
|===
|效果： |将容器保存的内部统计信息重置为零。

|注意：
|仅当link:reference/stats.html#stats[统计计算]被link:#unordered_flat_set_boost_unordered_enable_stats[启用]时可用。
|===

'''''

[[unordered_flat_set_deduction_guides]]
=== 推导指引

如果以下任何一项为真，则推导指引不参与重载决议：

* 它具有 `InputIterator`
模板参数，且推导出的该参数类型不符合输入迭代器要求。
* 它具有 `Allocator` 模板参数，且推导出的该参数类型不符合分配器要求。
* 它具有 `Hash`
模板参数，且推导出的该参数类型为整数类型或符合分配器要求。
* 它具有 `Pred` 模板参数，且推导出的该参数类型符合分配器要求。

推导指引中的 `size_­type` 参数类型引用由推导指引推导出的容器类型的
`size_­type` 成员类型。其默认值与所选构造函数的默认值一致。

[[unordered_flat_set_iter_value_type]]
==== _iter-value-type_

....
template<class InputIterator>
  using iter-value-type =
    typename std::iterator_traits<InputIterator>::value_type; // 仅用于说明
....

[[unordered_flat_set_equality_comparisons]]
=== 相等比较

[[unordered_flat_set_operator]]
==== operator==

[source,highlight]
----
template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator==(const unordered_flat_set<Key, T, Hash, Pred, Alloc>& x,
                  const unordered_flat_set<Key, T, Hash, Pred, Alloc>& y);
----

如果 `x.size() == y.size()` 且对于 `x` 中的每个元素，`y`
中都有一个具有相同键且值相等的元素（使用 `operator==`
比较值类型），则返回 `true`。

[cols=",",]
|===
|注意： |如果两个容器的相等谓词不等效，则行为未定义。
|===

'''''

[[unordered_flat_set_operator_2]]
==== operator!=

[source,highlight]
----
template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator!=(const unordered_flat_set<Key, T, Hash, Pred, Alloc>& x,
                  const unordered_flat_set<Key, T, Hash, Pred, Alloc>& y);
----

如果 `x.size() == y.size()` 且对于 `x` 中的每个元素，`y`
中都有一个具有相同键且值相等的元素（使用 `operator==`
比较值类型），则返回 `false`。

[cols=",",]
|===
|注意： |如果两个容器的相等谓词不等效，则行为未定义。
|===

[[unordered_flat_set_swap_2]]
=== Swap

[source,highlight]
----
template<class Key, class T, class Hash, class Pred, class Alloc>
  void swap(unordered_flat_set<Key, T, Hash, Pred, Alloc>& x,
            unordered_flat_set<Key, T, Hash, Pred, Alloc>& y)
    noexcept(noexcept(x.swap(y)));
----

交换 `x` 和 `y` 的内容。

如果声明了 `Allocator::propagate_on_container_swap` 且
`Allocator::propagate_on_container_swap::value` 为
`true`，则交换容器的分配器。否则，与不相等分配器交换会导致未定义行为。

[cols=",",]
|===
|效果： |`x.swap(y)`
|抛出： |除非 `key_equal` 或 `hasher` 在交换时抛出，否则无抛出。
|===

'''''

[[unordered_flat_set_erase_if]]
=== erase_if

[source,highlight]
----
template<class K, class T, class H, class P, class A, class Predicate>
  typename unordered_flat_set<K, T, H, P, A>::size_type
    erase_if(unordered_flat_set<K, T, H, P, A>& c, Predicate pred);
----

遍历容器 `c` 并删除所有满足谓词 `pred` 返回 `true` 的元素。

[width="100%",cols="50%,50%",]
|===
|返回： |擦除的元素数量。
|注意： a|
等效于： +

[source,highlight]
----
auto original_size = c.size();
for (auto i = c.begin(), last = c.end(); i != last; ) {
  if (pred(*i)) {
    i = c.erase(i);
  } else {
    ++i;
  }
}
return original_size - c.size();
----

|===

[[unordered_flat_set_serialization]]
=== 序列化

`unordered_flat_set` 可以通过
link:../../../../../serialization/index.html[Boost.Serialization]
使用本库提供的 API 进行归档/检索。支持常规归档和 XML 归档。

[[unordered_flat_set_saving_an_unordered_flat_set_to_an_archive]]
==== 将 unordered_flat_set 保存到归档

将 `unordered_flat_set` `x` 的所有元素保存到归档（XML 归档）`ar`。

[cols=",",]
|===
|要求： |`value_type` 可序列化（XML 可序列化），且支持
Boost.Serialization 的 `save_construct_data`/`load_construct_data`
协议（https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]类型自动支持）。
|===

'''''

[[unordered_flat_set_loading_an_unordered_flat_set_from_an_archive]]
==== 从归档加载 unordered_flat_set

删除 `unordered_flat_set` `x` 的所有现有元素，并从归档（XML 归档）`ar`
插入原始 `unordered_flat_set` `other` 保存到 `ar`
读取的存储中的元素副本。

[cols=",",]
|===
|要求： |`x.key_equal()` 在功能上等效于 `other.key_equal()`。
|===

'''''

[[unordered_flat_set_saving_an_iteratorconst_iterator_to_an_archive]]
==== 将迭代器/常量迭代器保存到归档

将 `iterator`（`const_iterator`）`it` 的位置信息保存到归档（XML
归档）`ar`。`it` 可以是 `end()` 迭代器。

[cols=",",]
|===
|要求： |`it` 指向的 `unordered_flat_set` `x` 先前已保存到
`ar`，且在保存 `x` 和保存 `it` 之间未对 `x` 执行修改操作。
|===

'''''

[[unordered_flat_set_loading_an_iteratorconst_iterator_from_an_archive]]
==== 从归档加载迭代器/常量迭代器

使 `iterator`（`const_iterator`）`it` 指向从归档（XML 归档）`ar`
读取的存储中保存的原始 `iterator`（`const_iterator`）的恢复位置。

[cols=",",]
|===
|要求： |如果 `x` 是 `it` 指向的 `unordered_flat_set`，则在加载 `x`
和加载 `it` 之间未对 `x` 执行修改操作。
|===

[[footer]]
[[footer-text]]
最后更新于 2025-10-31 21:41:12 UTC
