[#unordered_map]
== Class Template unordered_map

:idprefix: unordered_map_

`boost::unordered_map` — An unordered associative container that associates unique keys with another value.

=== Synopsis

[listing, subs="+macros,+quotes"]
-----
// #include xref:reference/header_unordered_map.adoc[<boost/unordered/unordered_map.hpp>]

namespace boost {
namespace unordered {

  template<class Key,
           class T,
           class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<std::pair<const Key, T>>>
  class unordered_map {
  public:
    // types
    using key_type             = Key;
    using mapped_type          = T;
    using value_type           = std::pair<const Key, T>;
    using hasher               = Hash;
    using key_equal            = Pred;
    using allocator_type       = Allocator;
    using pointer              = typename std::allocator_traits<Allocator>::pointer;
    using const_pointer        = typename std::allocator_traits<Allocator>::const_pointer;
    using reference            = value_type&;
    using const_reference      = const value_type&;
    using size_type            = std::size_t;
    using difference_type      = std::ptrdiff_t;

    using iterator             = _implementation-defined_;
    using const_iterator       = _implementation-defined_;
    using local_iterator       = _implementation-defined_;
    using const_local_iterator = _implementation-defined_;
    using node_type            = _implementation-defined_;
    using insert_return_type   = _implementation-defined_;

    // construct/copy/destroy
    xref:#unordered_map_default_constructor[unordered_map]();
    explicit xref:#unordered_map_bucket_count_constructor[unordered_map](size_type n,
                           const hasher& hf = hasher(),
                           const key_equal& eql = key_equal(),
                           const allocator_type& a = allocator_type());
    template<class InputIterator>
      xref:#unordered_map_iterator_range_constructor[unordered_map](InputIterator f, InputIterator l,
                    size_type n = _implementation-defined_,
                    const hasher& hf = hasher(),
                    const key_equal& eql = key_equal(),
                    const allocator_type& a = allocator_type());
    xref:#unordered_map_copy_constructor[unordered_map](const unordered_map& other);
    xref:#unordered_map_move_constructor[unordered_map](unordered_map&& other);
    template<class InputIterator>
      xref:#unordered_map_iterator_range_constructor_with_allocator[unordered_map](InputIterator f, InputIterator l, const allocator_type& a);
    explicit xref:#unordered_map_allocator_constructor[unordered_map](const Allocator& a);
    xref:#unordered_map_copy_constructor_with_allocator[unordered_map](const unordered_map& other, const Allocator& a);
    xref:#unordered_map_move_constructor_with_allocator[unordered_map](unordered_map&& other, const Allocator& a);
    xref:#unordered_map_initializer_list_constructor[unordered_map](std::initializer_list<value_type> il,
                  size_type n = _implementation-defined_
                  const hasher& hf = hasher(),
                  const key_equal& eql = key_equal(),
                  const allocator_type& a = allocator_type());
    xref:#unordered_map_bucket_count_constructor_with_allocator[unordered_map](size_type n, const allocator_type& a);
    xref:#unordered_map_bucket_count_constructor_with_hasher_and_allocator[unordered_map](size_type n, const hasher& hf, const allocator_type& a);
    template<class InputIterator>
      xref:#unordered_map_iterator_range_constructor_with_bucket_count_and_allocator[unordered_map](InputIterator f, InputIterator l, size_type n, const allocator_type& a);
    template<class InputIterator>
      xref:#unordered_map_iterator_range_constructor_with_bucket_count_and_hasher[unordered_map](InputIterator f, InputIterator l, size_type n, const hasher& hf,
                    const allocator_type& a);
    xref:#unordered_map_initializer_list_constructor_with_allocator[unordered_map](std::initializer_list<value_type> il, const allocator_type& a);
    xref:#unordered_map_initializer_list_constructor_with_bucket_count_and_allocator[unordered_map](std::initializer_list<value_type> il, size_type n, const allocator_type& a);
    xref:#unordered_map_initializer_list_constructor_with_bucket_count_and_hasher_and_allocator[unordered_map](std::initializer_list<value_type> il, size_type n, const hasher& hf,
                  const allocator_type& a);
    xref:#unordered_map_destructor[~unordered_map]();
    unordered_map& xref:#unordered_map_copy_assignment[operator++=++](const unordered_map& other);
    unordered_map& xref:#unordered_map_move_assignment[operator++=++](unordered_map&& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
               boost::is_nothrow_move_assignable_v<Hash> &&
               boost::is_nothrow_move_assignable_v<Pred>);
    unordered_map& xref:#unordered_map_initializer_list_assignment[operator++=++](std::initializer_list<value_type>);
    allocator_type xref:#unordered_map_get_allocator[get_allocator]() const noexcept;

    // iterators
    iterator       xref:#unordered_map_begin[begin]() noexcept;
    const_iterator xref:#unordered_map_begin[begin]() const noexcept;
    iterator       xref:#unordered_map_end[end]() noexcept;
    const_iterator xref:#unordered_map_end[end]() const noexcept;
    const_iterator xref:#unordered_map_cbegin[cbegin]() const noexcept;
    const_iterator xref:#unordered_map_cend[cend]() const noexcept;

    // capacity
    ++[[nodiscard]]++ bool xref:#unordered_map_empty[empty]() const noexcept;
    size_type xref:#unordered_map_size[size]() const noexcept;
    size_type xref:#unordered_map_max_size[max_size]() const noexcept;

    // modifiers
    template<class... Args> std::pair<iterator, bool> xref:#unordered_map_emplace[emplace](Args&&... args);
    template<class... Args> iterator xref:#unordered_map_emplace_hint[emplace_hint](const_iterator position, Args&&... args);
    std::pair<iterator, bool> xref:#unordered_map_copy_insert[insert](const value_type& obj);
    std::pair<iterator, bool> xref:#unordered_map_move_insert[insert](value_type&& obj);
    template<class P> std::pair<iterator, bool> xref:#unordered_map_emplace_insert[insert](P&& obj);
    iterator       xref:#unordered_map_copy_insert_with_hint[insert](const_iterator hint, const value_type& obj);
    iterator       xref:#unordered_map_move_insert_with_hint[insert](const_iterator hint, value_type&& obj);
    template<class P> iterator xref:#unordered_map_emplace_insert_with_hint[insert](const_iterator hint, P&& obj);
    template<class InputIterator> void xref:#unordered_map_insert_iterator_range[insert](InputIterator first, InputIterator last);
    void xref:#unordered_map_insert_initializer_list[insert](std::initializer_list<value_type>);

    template<class... Args>
      std::pair<iterator, bool> xref:#unordered_map_try_emplace[try_emplace](const key_type& k, Args&&... args);
    template<class... Args>
      std::pair<iterator, bool> xref:#unordered_map_try_emplace[try_emplace](key_type&& k, Args&&... args);
    template<class K, class... Args>
      std::pair<iterator, bool> xref:#unordered_map_try_emplace[try_emplace](K&& k, Args&&... args);
    template<class... Args>
      iterator xref:#unordered_map_try_emplace_with_hint[try_emplace](const_iterator hint, const key_type& k, Args&&... args);
    template<class... Args>
      iterator xref:#unordered_map_try_emplace_with_hint[try_emplace](const_iterator hint, key_type&& k, Args&&... args);
    template<class K, class... Args>
      iterator xref:#unordered_map_try_emplace_with_hint[try_emplace](const_iterator hint, K&& k, Args&&... args);
    template<class M>
      std::pair<iterator, bool> xref:#unordered_map_insert_or_assign[insert_or_assign](const key_type& k, M&& obj);
    template<class M>
      std::pair<iterator, bool> xref:#unordered_map_insert_or_assign[insert_or_assign](key_type&& k, M&& obj);
    template<class K, class M>
      std::pair<iterator, bool> xref:#unordered_map_insert_or_assign[insert_or_assign](K&& k, M&& obj);
    template<class M>
      iterator xref:#unordered_map_insert_or_assign_with_hint[insert_or_assign](const_iterator hint, const key_type& k, M&& obj);
    template<class M>
      iterator xref:#unordered_map_insert_or_assign_with_hint[insert_or_assign](const_iterator hint, key_type&& k, M&& obj);
    template<class K, class M>
      iterator xref:#unordered_map_insert_or_assign_with_hint[insert_or_assign](const_iterator hint, K&& k, M&& obj);

    node_type xref:#unordered_map_extract_by_iterator[extract](const_iterator position);
    node_type xref:#unordered_map_extract_by_key[extract](const key_type& k);
    template<class K> node_type xref:#unordered_map_extract_by_key[extract](K&& k);
    insert_return_type xref:#unordered_map_insert_with_node_handle[insert](node_type&& nh);
    iterator           xref:#unordered_map_insert_with_hint_and_node_handle[insert](const_iterator hint, node_type&& nh);

    iterator  xref:#unordered_map_erase_by_position[erase](iterator position);
    iterator  xref:#unordered_map_erase_by_position[erase](const_iterator position);
    size_type xref:#unordered_map_erase_by_key[erase](const key_type& k);
    template<class K> size_type xref:#unordered_map_erase_by_key[erase](K&& k);
    iterator  xref:#unordered_map_erase_range[erase](const_iterator first, const_iterator last);
    void      xref:#unordered_map_quick_erase[quick_erase](const_iterator position);
    void      xref:#unordered_map_erase_return_void[erase_return_void](const_iterator position);
    void      xref:#unordered_map_swap[swap](unordered_map& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
               boost::is_nothrow_swappable_v<Hash> &&
               boost::is_nothrow_swappable_v<Pred>);
    void      xref:#unordered_map_clear[clear]() noexcept;

    template<class H2, class P2>
      void xref:#unordered_map_merge[merge](unordered_map<Key, T, H2, P2, Allocator>& source);
    template<class H2, class P2>
      void xref:#unordered_map_merge[merge](unordered_map<Key, T, H2, P2, Allocator>&& source);
    template<class H2, class P2>
      void xref:#unordered_map_merge[merge](unordered_multimap<Key, T, H2, P2, Allocator>& source);
    template<class H2, class P2>
      void xref:#unordered_map_merge[merge](unordered_multimap<Key, T, H2, P2, Allocator>&& source);

    // observers
    hasher xref:#unordered_map_hash_function[hash_function]() const;
    key_equal xref:#unordered_map_key_eq[key_eq]() const;

    // map operations
    iterator         xref:#unordered_map_find[find](const key_type& k);
    const_iterator   xref:#unordered_map_find[find](const key_type& k) const;
    template<class K>
      iterator       xref:#unordered_map_find[find](const K& k);
    template<class K>
      const_iterator xref:#unordered_map_find[find](const K& k) const;
    template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
      iterator       xref:#unordered_map_find[find](CompatibleKey const& k, CompatibleHash const& hash,
                          CompatiblePredicate const& eq);
    template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
      const_iterator xref:#unordered_map_find[find](CompatibleKey const& k, CompatibleHash const& hash,
                          CompatiblePredicate const& eq) const;
    size_type        xref:#unordered_map_count[count](const key_type& k) const;
    template<class K>
      size_type      xref:#unordered_map_count[count](const K& k) const;
    bool             xref:#unordered_map_contains[contains](const key_type& k) const;
    template<class K>
      bool           xref:#unordered_map_contains[contains](const K& k) const;
    std::pair<iterator, iterator>               xref:#unordered_map_equal_range[equal_range](const key_type& k);
    std::pair<const_iterator, const_iterator>   xref:#unordered_map_equal_range[equal_range](const key_type& k) const;
    template<class K>
      std::pair<iterator, iterator>             xref:#unordered_map_equal_range[equal_range](const K& k);
    template<class K>
      std::pair<const_iterator, const_iterator> xref:#unordered_map_equal_range[equal_range](const K& k) const;

    // element access
    mapped_type& xref:#unordered_map_operator[operator[+]+](const key_type& k);
    mapped_type& xref:#unordered_map_operator[operator[+]+](key_type&& k);
    template<class K> mapped_type& xref:#unordered_map_operator[operator[+]+](K&& k);
    mapped_type& xref:#unordered_map_at[at](const key_type& k);
    const mapped_type& xref:#unordered_map_at[at](const key_type& k) const;
    template<class K> mapped_type& xref:#unordered_map_at[at](const K& k);
    template<class K> const mapped_type& xref:#unordered_map_at[at](const K& k) const;

    // bucket interface
    size_type xref:#unordered_map_bucket_count[bucket_count]() const noexcept;
    size_type xref:#unordered_map_max_bucket_count[max_bucket_count]() const noexcept;
    size_type xref:#unordered_map_bucket_size[bucket_size](size_type n) const;
    size_type xref:#unordered_map_bucket[bucket](const key_type& k) const;
    template<class K> size_type xref:#unordered_map_bucket[bucket](const K& k) const;
    local_iterator xref:#unordered_map_begin_2[begin](size_type n);
    const_local_iterator xref:#unordered_map_begin_2[begin](size_type n) const;
    local_iterator xref:#unordered_map_end_2[end](size_type n);
    const_local_iterator xref:#unordered_map_end_2[end](size_type n) const;
    const_local_iterator xref:#unordered_map_cbegin_2[cbegin](size_type n) const;
    const_local_iterator xref:#unordered_map_cend_2[cend](size_type n) const;

    // hash policy
    float xref:#unordered_map_load_factor[load_factor]() const noexcept;
    float xref:#unordered_map_max_load_factor[max_load_factor]() const noexcept;
    void xref:#unordered_map_set_max_load_factor[max_load_factor](float z);
    void xref:#unordered_map_rehash[rehash](size_type n);
    void xref:#unordered_map_reserve[reserve](size_type n);
  };

  // Deduction Guides
  template<class InputIterator,
           class Hash = boost::hash<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>>,
           class Pred = std::equal_to<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>>,
           class Allocator = std::allocator<xref:#unordered_map_iter_to_alloc_type[__iter-to-alloc-type__]<InputIterator>>>
    unordered_map(InputIterator, InputIterator, typename xref:#unordered_map_deduction_guides[__see below__]::size_type = xref:#unordered_map_deduction_guides[__see below__],
                  Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> unordered_map<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>, xref:#unordered_map_iter_mapped_type[__iter-mapped-type__]<InputIterator>, Hash, Pred,
                       Allocator>;

  template<class Key, class T, class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<std::pair<const Key, T>>>
    unordered_map(std::initializer_list<std::pair<Key, T>>,
                  typename xref:#unordered_map_deduction_guides[__see below__]::size_type = xref:#unordered_map_deduction_guides[__see below__], Hash = Hash(),
                  Pred = Pred(), Allocator = Allocator())
      -> unordered_map<Key, T, Hash, Pred, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_map(InputIterator, InputIterator, typename xref:#unordered_map_deduction_guides[__see below__]::size_type, Allocator)
      -> unordered_map<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>, xref:#unordered_map_iter_mapped_type[__iter-mapped-type__]<InputIterator>,
                       boost::hash<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>>,
                       std::equal_to<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_map(InputIterator, InputIterator, Allocator)
      -> unordered_map<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>, xref:#unordered_map_iter_mapped_type[__iter-mapped-type__]<InputIterator>,
                       boost::hash<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>>,
                       std::equal_to<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Hash, class Allocator>
    unordered_map(InputIterator, InputIterator, typename xref:#unordered_map_deduction_guides[__see below__]::size_type, Hash, Allocator)
      -> unordered_map<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>, xref:#unordered_map_iter_mapped_type[__iter-mapped-type__]<InputIterator>, Hash,
                       std::equal_to<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>>, Allocator>;

  template<class Key, class T, class Allocator>
    unordered_map(std::initializer_list<std::pair<Key, T>>, typename xref:#unordered_map_deduction_guides[__see below__]::size_type,
                  Allocator)
      -> unordered_map<Key, T, boost::hash<Key>, std::equal_to<Key>, Allocator>;

  template<class Key, class T, class Allocator>
    unordered_map(std::initializer_list<std::pair<Key, T>>, Allocator)
      -> unordered_map<Key, T, boost::hash<Key>, std::equal_to<Key>, Allocator>;

  template<class Key, class T, class Hash, class Allocator>
    unordered_map(std::initializer_list<std::pair<Key, T>>, typename xref:#unordered_map_deduction_guides[__see below__]::size_type, Hash,
                  Allocator)
      -> unordered_map<Key, T, Hash, std::equal_to<Key>, Allocator>;

} // namespace unordered
} // namespace boost
-----

---

=== Description

*Template Parameters*

[cols="1,1"]
|===

|_Key_
|`Key` must be https://en.cppreference.com/w/cpp/named_req/Erasable[Erasable^] from the container (i.e. `allocator_traits` can destroy it).

|_T_
|`T` must be https://en.cppreference.com/w/cpp/named_req/Erasable[Erasable^] from the container (i.e. `allocator_traits` can destroy it).

|_Hash_
|A unary function object type that acts a hash function for a `Key`. It takes a single argument of type `Key` and returns a value of type `std::size_t`.

|_Pred_
|A binary function object that implements an equivalence relation on values of type `Key`. A binary function object that induces an equivalence relation on values of type `Key`. It takes two arguments of type `Key` and returns a value of type bool.

|_Allocator_
|An allocator whose value type is the same as the container's value type.
Allocators using https://en.cppreference.com/w/cpp/named_req/Allocator#Fancy_pointers[fancy pointers] are supported.

|===

The elements are organized into buckets. Keys with the same hash code are stored in the same bucket.

The number of buckets can be automatically increased by a call to insert, or as the result of calling rehash.

=== Configuration macros

==== `BOOST_UNORDERED_ENABLE_SERIALIZATION_COMPATIBILITY_V0`

Globally define this macro to support loading of ``unordered_map``s saved to a Boost.Serialization archive with a version of Boost prior to Boost 1.84.

=== Typedefs

[source, c++, subs=+quotes]
----
typedef _implementation-defined_ iterator;
----

An iterator whose value type is `value_type`.

The iterator category is at least a forward iterator.

Convertible to `const_iterator`.

---

[source, c++, subs=+quotes]
----
typedef _implementation-defined_ const_iterator;
----

A constant iterator whose value type is `value_type`.

The iterator category is at least a forward iterator.

---

[source, c++, subs=+quotes]
----
typedef _implementation-defined_ local_iterator;
----

An iterator with the same value type, difference type and pointer and reference type as iterator.

A `local_iterator` object can be used to iterate through a single bucket.

---

[source, c++, subs=+quotes]
----
typedef _implementation-defined_ const_local_iterator;
----

A constant iterator with the same value type, difference type and pointer and reference type as const_iterator.

A const_local_iterator object can be used to iterate through a single bucket.

---

[source, c++, subs=+quotes]
----
typedef _implementation-defined_ node_type;
----

A class for holding extracted container elements, modelling https://en.cppreference.com/w/cpp/container/node_handle[NodeHandle].

---

[source, c++, subs=+quotes]
----
typedef _implementation-defined_ insert_return_type;
----

A specialization of an internal class template:

[source, c++, subs=+quotes]
----
template<class Iterator, class NodeType>
struct _insert_return_type_ // name is exposition only
{
  Iterator position;
  bool     inserted;
  NodeType node;
};
----

with `Iterator` = `iterator` and `NodeType` = `node_type`.

---

=== Constructors

==== Default Constructor
```c++

unordered_map();

```

Constructs an empty container using `hasher()` as the hash function, `key_equal()` as the key equality predicate, `allocator_type()` as the allocator and a maximum load factor of `1.0`.

[horizontal]
Postconditions:;; `size() == 0`
Requires:;; If the defaults are used, `hasher`, `key_equal` and `allocator_type` need to be https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible^].

---

==== Bucket Count Constructor
```c++

explicit unordered_map(size_type n,
                       const hasher& hf = hasher(),
                       const key_equal& eql = key_equal(),
                       const allocator_type& a = allocator_type());

```

Constructs an empty container with at least `n` buckets, using `hf` as the hash function, `eql` as the key equality predicate, `a` as the allocator and a maximum load factor of `1.0`.

[horizontal]
Postconditions:;; `size() == 0`
Requires:;; If the defaults are used, `hasher`, `key_equal` and `allocator_type` need to be https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible^].

---

==== Iterator Range Constructor
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  unordered_map(InputIterator f, InputIterator l,
                size_type n = _implementation-defined_,
                const hasher& hf = hasher(),
                const key_equal& eql = key_equal(),
                const allocator_type& a = allocator_type());
----

Constructs an empty container with at least `n` buckets, using `hf` as the hash function, `eql` as the key equality predicate, `a` as the allocator and a maximum load factor of `1.0` and inserts the elements from `[f, l)` into it.

[horizontal]
Requires:;; If the defaults are used, `hasher`, `key_equal` and `allocator_type` need to be https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible^].

---

==== Copy Constructor
```c++

unordered_map(unordered_map const& other);

```

The copy constructor. Copies the contained elements, hash function, predicate, maximum load factor and allocator.

If `Allocator::select_on_container_copy_construction` exists and has the right signature, the allocator will be constructed from its result.

[horizontal]
Requires:;; `value_type` is copy constructible

---

==== Move Constructor
```c++

unordered_map(unordered_map&& other);

```

The move constructor.

[horizontal]
注意：;; This is implemented using Boost.Move.
Requires:;; `value_type` is move-constructible.

---

==== Iterator Range Constructor with Allocator
```c++

template<class InputIterator>
  unordered_map(InputIterator f, InputIterator l, const allocator_type& a);

```

Constructs an empty container using `a` as the allocator, with the default hash function and key equality predicate and a maximum load factor of `1.0` and inserts the elements from `[f, l)` into it.

[horizontal]
Requires:;; `hasher`, `key_equal` need to be https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible^].

---

==== Allocator Constructor
```c++

explicit unordered_map(Allocator const& a);

```

Constructs an empty container, using allocator `a`.

---

==== Copy Constructor with Allocator
```c++

unordered_map(unordered_map const& other, Allocator const& a);

```

Constructs an container, copying ``other``'s contained elements, hash function, predicate, maximum load factor, but using allocator `a`.

---

==== Move Constructor with Allocator
```c++

unordered_map(unordered_map&& other, Allocator const& a);

```

Construct a container moving ``other``'s contained elements, and having the hash function, predicate and maximum load factor, but using allocate `a`.

[horizontal]
注意：;; This is implemented using Boost.Move.
Requires:;; `value_type` is move insertable.

---

==== Initializer List Constructor
[source, c++, subs="+quotes"]
----
unordered_map(std::initializer_list<value_type> il,
              size_type n = _implementation-defined_
              const hasher& hf = hasher(),
              const key_equal& eql = key_equal(),
              const allocator_type& a = allocator_type());
----

Constructs an empty container with at least `n` buckets, using `hf` as the hash function, `eql` as the key equality predicate, `a` as the allocator and a maximum load factor of `1.0` and inserts the elements from `il` into it.

[horizontal]
Requires:;; If the defaults are used, `hasher`, `key_equal` and `allocator_type` need to be https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible^].

---

==== Bucket Count Constructor with Allocator
```c++

unordered_map(size_type n, allocator_type const& a);

```

Constructs an empty container with at least `n` buckets, using `hf` as the hash function, the default hash function and key equality predicate, `a` as the allocator and a maximum load factor of `1.0`.

[horizontal]
Postconditions:;; `size() == 0`
Requires:;; `hasher` 和 `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 带哈希函数和分配器的桶数量构造函数
```c++

unordered_map(size_type n, hasher const& hf, allocator_type const& a);

```

Constructs an empty container with at least `n` buckets, using `hf` as the hash function, the default key equality predicate, `a` as the allocator and a maximum load factor of `1.0`.

[horizontal]
Postconditions:;; `size() == 0`
Requires:;; `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 带桶数量和分配器的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  unordered_map(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `a` as the allocator, with the default hash function and key equality predicate and a maximum load factor of `1.0` and inserts the elements from `[f, l)` into it.

[horizontal]
Requires:;; `hasher`, `key_equal` need to be https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible^].

---

==== 带桶数量和哈希函数的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
    template<class InputIterator>
      unordered_map(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                    const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `hf` as the hash function, `a` as the allocator, with the default key equality predicate and a maximum load factor of `1.0` and inserts the elements from `[f, l)` into it.

[horizontal]
Requires:;; `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 带分配器的初始化列表构造函数

```c++

unordered_map(std::initializer_list<value_type> il, const allocator_type& a);

```

Constructs an empty container using `a` as the allocator and a maximum load factor of 1.0 and inserts the elements from `il` into it.

[horizontal]
Requires:;; `hasher` 和 `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 带桶数量和分配器的初始化列表构造函数

```c++

unordered_map(std::initializer_list<value_type> il, size_type n, const allocator_type& a);

```

Constructs an empty container with at least `n` buckets, using `a` as the allocator and a maximum load factor of 1.0 and inserts the elements from `il` into it.

[horizontal]
Requires:;; `hasher` 和 `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

==== 带桶数量、哈希函数和分配器的初始化列表构造函数

```c++

unordered_map(std::initializer_list<value_type> il, size_type n, const hasher& hf,
              const allocator_type& a);

```

Constructs an empty container with at least `n` buckets, using `hf` as the hash function, `a` as the allocator and a maximum load factor of 1.0 and inserts the elements from `il` into it.

[horizontal]
Requires:;; `key_equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]。

---

=== 析构函数

```c++

~unordered_map();

```

[horizontal]
注意：;; 析构函数会应用于每个元素，并释放所有内存

---

=== 赋值

==== 复制赋值

```c++

unordered_map& operator=(unordered_map const& other);

```

The assignment operator. Copies the contained elements, hash function, predicate and maximum load factor but not the allocator.

If `Alloc::propagate_on_container_copy_assignment` exists and `Alloc::propagate_on_container_copy_assignment::value` is `true`, the allocator is overwritten, if not the copied elements are created using the existing allocator.

[horizontal]
Requires:;; `value_type` is copy constructible

---

==== 移动赋值
```c++

unordered_map& operator=(unordered_map&& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
           boost::is_nothrow_move_assignable_v<Hash> &&
           boost::is_nothrow_move_assignable_v<Pred>);

```
The move assignment operator.

If `Alloc::propagate_on_container_move_assignment` exists and `Alloc::propagate_on_container_move_assignment::value` is `true`, the allocator is overwritten, if not the moved elements are created using the existing allocator.

[horizontal]
Requires:;; `value_type` is move constructible.

---

==== 初始化列表赋值
```c++

unordered_map& operator=(std::initializer_list<value_type> il);

```

Assign from values in initializer list. All existing elements are either overwritten by the new elements or destroyed.

[horizontal]
Requires:;; `value_type` is https://en.cppreference.com/w/cpp/named_req/CopyInsertable[CopyInsertable^] into the container and https://en.cppreference.com/w/cpp/named_req/CopyAssignable[CopyAssignable^].

=== 迭代器

==== begin
```c++

iterator begin() noexcept; const_iterator begin() const noexcept;

```

[horizontal]
返回：;; 指向容器第一个元素的迭代器，若容器为空则为容器的尾后值。

---

==== end
```c++

iterator end() noexcept; const_iterator end() const noexcept;

```

[horizontal]
返回：;; 指向容器尾后值的迭代器。

---

==== cbegin
```c++

const_iterator cbegin() const noexcept;

```

[horizontal]
返回：;; 指向容器第一个元素的 `const_iterator`，若容器为空则为容器的尾后值。

---

==== cend
```c++

const_iterator cend() const noexcept;

```

[horizontal]
返回：;; 指向容器尾后值的 `const_iterator`。

---

=== 大小与容量

==== empty

```c++

[[nodiscard]] bool empty() const noexcept;

```

[horizontal]
返回：;; `size() == 0`

---

==== size

```c++

size_type size() const noexcept;

```

[horizontal]
返回：;; `std::distance(begin(), end())`

---

==== max_size

```c++

size_type max_size() const noexcept;

```

[horizontal]
返回：;; 最大可能容器的 `size()`。

---

=== 修改器

==== emplace
```c++

template<class... Args> std::pair<iterator, bool> emplace(Args&&... args);

```

当且仅当容器中不存在等价键时，插入一个由参数 `args` 构造的对象。

[horizontal]
Requires:;; `value_type` is https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible^] into `X` from `args`.
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。+
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若除调用 `hasher` 外的操作抛出异常，则函数无效果。
注意：;; Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated. +
+
If `args...` is of the form `k,v`, it delays constructing the whole object until it is certain that an element should be inserted, using only the `k` argument to check. This optimization happens when the map's `key_type` is move constructible or when the `k` argument is a `key_type`.

---

==== emplace_hint
```c++

template<class... Args> iterator emplace_hint(const_iterator position, Args&&... args);

```

当且仅当容器中不存在等价键时，插入一个由参数 `args` 构造的对象。

`position` is a suggestion to where the element should be inserted.

[horizontal]
Requires:;; `value_type` is https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible^] into `X` from `args`.
返回：;; 若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若除调用 `hasher` 外的操作抛出异常，则函数无效果。
注意：;; The standard is fairly vague on the meaning of the hint. But the only practical way to use it, and the only way that Boost.Unordered supports is to point to an existing element with the same key. +
+
Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated. +
+
If `args...` is of the form `k,v`, it delays constructing the whole object until it is certain that an element should be inserted, using only the `k` argument to check. This optimization happens when the map's `key_type` is move constructible or when the `k` argument is a `key_type`.

---

==== 复制插入
```c++

std::pair<iterator, bool> insert(const value_type& obj);

```

当且仅当容器中不存在等价键时，插入 `obj`。

[horizontal]
Requires:;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入^]。
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。+
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若除调用 `hasher` 外的操作抛出异常，则函数无效果。
注意：;; Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated.

---

==== 移动插入
```c++

std::pair<iterator, bool> insert(value_type&& obj);

```

当且仅当容器中不存在等价键时，插入 `obj`。

[horizontal]
Requires:;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入^]。
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。+
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若除调用 `hasher` 外的操作抛出异常，则函数无效果。
注意：;; Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated.

---

==== Emplace Insert
```c++

template<class P> std::pair<iterator, bool> insert(P&& obj);

```

Inserts an element into the container by performing `emplace(std::forward<P>(value))`.

Only participates in overload resolution if `std::is_constructible<value_type, P&&>::value` is `true`.

[horizontal]
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。+
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。

---

==== 带提示的复制插入
```c++

iterator insert(const_iterator hint, const value_type& obj);

``` 当且仅当容器中不存在等价键时，插入 `obj`。

`hint` is a suggestion to where the element should be inserted.

[horizontal]
Requires:;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入^]。
返回：;; 若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若除调用 `hasher` 外的操作抛出异常，则函数无效果。
注意：;; The standard is fairly vague on the meaning of the hint. But the only practical way to use it, and the only way that Boost.Unordered supports is to point to an existing element with the same key. +
+
Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated.

---

==== 带提示的移动插入
```c++

iterator insert(const_iterator hint, value_type&& obj);

```

当且仅当容器中不存在等价键时，插入 `obj`。

`hint` is a suggestion to where the element should be inserted.

[horizontal]
Requires:;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入^]。
返回：;; 若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若除调用 `hasher` 外的操作抛出异常，则函数无效果。
注意：;; The standard is fairly vague on the meaning of the hint. But the only practical way to use it, and the only way that Boost.Unordered supports is to point to an existing element with the same key. +
+
Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated.

---

==== Emplace Insert with Hint

```c++

template<class P> iterator insert(const_iterator hint, P&& obj);

```

Inserts an element into the container by performing `emplace_hint(hint, std::forward<P>(value))`.

Only participates in overload resolution if `std::is_constructible<value_type, P&&>::value` is `true`.

`hint` is a suggestion to where the element should be inserted.

[horizontal]
返回：;; 若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
注意：;; The standard is fairly vague on the meaning of the hint. But the only practical way to use it, and the only way that Boost.Unordered supports is to point to an existing element with the same key. +
+
Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated.

---

==== 插入迭代器范围
```c++

template<class InputIterator> void insert(InputIterator first, InputIterator last);

```

将元素范围插入容器。当且仅当容器中不存在等价键时，元素才会被插入。

[horizontal]
Requires:;; `value_type` is https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible^] into `X` from `*first`.
抛出：;; 插入单个元素时，若除调用 `hasher` 外的操作抛出异常，则函数无效果。
注意：;; Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated.

---

==== 插入初始化列表
```c++

void insert(std::initializer_list<value_type>);

```

将元素范围插入容器。当且仅当容器中不存在等价键时，元素才会被插入。

[horizontal]
Requires:;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入^] 到容器中。
抛出：;; 插入单个元素时，若除调用 `hasher` 外的操作抛出异常，则函数无效果。
注意：;; Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated.

---

==== try_emplace
```c++

template<class... Args>
  std::pair<iterator, bool> try_emplace(const key_type& k, Args&&... args);
template<class... Args>
  std::pair<iterator, bool> try_emplace(key_type&& k, Args&&... args);
template<class K, class... Args>
  std::pair<iterator, bool> try_emplace(K&& k, Args&&... args)

```

Inserts a new element into the container if there is no existing element with key `k` contained within it.

If there is an existing element with key `k` this function does nothing.

[horizontal]
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。+
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若除调用 `hasher` 外的操作抛出异常，则函数无效果。
注意：;; This function is similiar to xref:#unordered_map_emplace[emplace] except the `value_type` is constructed using: +
+
--
```c++

// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

```

instead of xref:#unordered_map_emplace[emplace] which simply forwards all arguments to ``value_type``'s constructor.

Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor.

Pointers and references to elements are never invalidated.

The `template<class K, class\... Args>` overload only participates in overload resolution if `Hash::is_transparent` and `Pred::is_transparent` are valid member typedefs and neither `iterator` nor `const_iterator` are implicitly convertible from `K`. The library assumes that `Hash` is callable with both `K` and `Key` and that `Pred` is transparent. This enables heterogeneous lookup which avoids the cost of instantiating an instance of the `Key` type.
--

---

==== try_emplace with Hint
```c++

template<class... Args>
  iterator try_emplace(const_iterator hint, const key_type& k, Args&&... args);
template<class... Args>
  iterator try_emplace(const_iterator hint, key_type&& k, Args&&... args);
template<class K, class... Args>
  iterator try_emplace(const_iterator hint, K&& k, Args&&... args);

```

Inserts a new element into the container if there is no existing element with key `k` contained within it.

If there is an existing element with key `k` this function does nothing.

`hint` is a suggestion to where the element should be inserted.

[horizontal]
返回：;; 若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若除调用 `hasher` 外的操作抛出异常，则函数无效果。
注意：;; This function is similiar to xref:#unordered_map_emplace_hint[emplace_hint] except the `value_type` is constructed using: +
+
--
```c++

// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

```

instead of xref:#unordered_map_emplace_hint[emplace_hint] which simply forwards all arguments to ``value_type``'s constructor.

The standard is fairly vague on the meaning of the hint. But the only practical way to use it, and the only way that Boost.Unordered supports is to point to an existing element with the same key.

Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor.

Pointers and references to elements are never invalidated.

The `template<class K, class\... Args>` overload only participates in overload resolution if `Hash::is_transparent` and `Pred::is_transparent` are valid member typedefs and neither `iterator` nor `const_iterator` are implicitly convertible from `K`. The library assumes that `Hash` is callable with both `K` and `Key` and that `Pred` is transparent. This enables heterogeneous lookup which avoids the cost of instantiating an instance of the `Key` type.
--

---

==== insert_or_assign
```c++

template<class M>
  std::pair<iterator, bool> insert_or_assign(const key_type& k, M&& obj);
template<class M>
  std::pair<iterator, bool> insert_or_assign(key_type&& k, M&& obj);
template<class K, class M>
  std::pair<iterator, bool> insert_or_assign(K&& k, M&& obj);

```

Inserts a new element into the container or updates an existing one by assigning to the contained value.

If there is an element with key `k`, then it is updated by assigning `std::forward<M>(obj)`.

If there is no such element, it is added to the container as: ```c++

// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))

```

[horizontal]
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。+
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若除调用 `hasher` 外的操作抛出异常，则函数无效果。
注意：;; Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated. +
+
The `template<class K, class M>` only participates in overload resolution if `Hash::is_transparent` and `Pred::is_transparent` are valid member typedefs. The library assumes that `Hash` is callable with both `K` and `Key` and that `Pred` is transparent. This enables heterogeneous lookup which avoids the cost of instantiating an instance of the `Key` type.

---

==== insert_or_assign with Hint
```c++

template<class M>
  iterator insert_or_assign(const_iterator hint, const key_type& k, M&& obj);
template<class M>
  iterator insert_or_assign(const_iterator hint, key_type&& k, M&& obj);
template<class K, class M>
  iterator insert_or_assign(const_iterator hint, K&& k, M&& obj);

```

Inserts a new element into the container or updates an existing one by assigning to the contained value.

If there is an element with key `k`, then it is updated by assigning `std::forward<M>(obj)`.

If there is no such element, it is added to the container as: ```c++

// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))

```

`hint` is a suggestion to where the element should be inserted.

[horizontal]
返回：;; 若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若除调用 `hasher` 外的操作抛出异常，则函数无效果。
注意：;; The standard is fairly vague on the meaning of the hint. But the only practical way to use it, and the only way that Boost.Unordered supports is to point to an existing element with the same key. +
+
Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated. +
+
The `template<class K, class M>` only participates in overload resolution if `Hash::is_transparent` and `Pred::is_transparent` are valid member typedefs. The library assumes that `Hash` is callable with both `K` and `Key` and that `Pred` is transparent. This enables heterogeneous lookup which avoids the cost of instantiating an instance of the `Key` type.

---

==== Extract by Iterator
```c++

node_type extract(const_iterator position);

```

Removes the element pointed to by `position`.

[horizontal]
返回：;; A `node_type` owning the element.
注意：;; A node extracted using this method can be inserted into a compatible `unordered_multimap`.

---

==== Extract by Key
```c++

node_type extract(const key_type& k); template<class K> node_type extract(K&& k);

```

Removes an element with key equivalent to `k`.

[horizontal]
返回：;; A `node_type` owning the element if found, otherwise an empty `node_type`.
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才会抛出异常。
注意：;; A node extracted using this method can be inserted into a compatible `unordered_multimap`. +
+
仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义，且 `iterator` 和 `const_iterator` 均不能从 `K` 隐式转换时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这启用了异构查找，避免了实例化 `Key` 类型的开销。

---

==== Insert with `node_handle`
```c++

insert_return_type insert(node_type&& nh);

```

If `nh` is empty, has no effect.

Otherwise inserts the element owned by `nh` if and only if there is no element in the container with an equivalent key.

[horizontal]
Requires:;; `nh` is empty or `nh.get_allocator()` is equal to the container's allocator.
返回：;; If `nh` was empty, returns an `insert_return_type` with: `inserted` equal to `false`, `position` equal to `end()` and `node` empty. +
+
Otherwise if there was already an element with an equivalent key, returns an `insert_return_type` with: `inserted` equal to `false`, `position` pointing to a matching element and `node` contains the node from `nh`. +
+
Otherwise if the insertion succeeded, returns an `insert_return_type` with: `inserted` equal to `true`, `position` pointing to the newly inserted element and `node` empty.
抛出：;; 若除调用 `hasher` 外的操作抛出异常，则函数无效果。
注意：;; Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated. +
+
This can be used to insert a node extracted from a compatible `unordered_multimap`.

---

==== Insert with Hint and `node_handle`
```c++

iterator insert(const_iterator hint, node_type&& nh);

```

If `nh` is empty, has no effect.

Otherwise inserts the element owned by `nh` if and only if there is no element in the container with an equivalent key.

If there is already an element in the container with an equivalent key has no effect on `nh` (i.e. `nh` still contains the node.)

`hint` is a suggestion to where the element should be inserted.

[horizontal]
Requires:;; `nh` is empty or `nh.get_allocator()` is equal to the container's allocator.
返回：;; If `nh` was empty returns `end()`. +
+
If there was already an element in the container with an equivalent key returns an iterator pointing to that. +
+
Otherwise returns an iterator pointing to the newly inserted element.
抛出：;; If an exception is thrown by an operation other than a call to hasher the function has no effect.
注意：;; The standard is fairly vague on the meaning of the hint. But the only practical way to use it, and the only way that Boost.Unordered supports is to point to an existing element with the same key. +
+
Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated. +
+
This can be used to insert a node extracted from a compatible `unordered_multimap`.

---

==== 按位置擦除

```c++

iterator erase(iterator position); iterator erase(const_iterator position);

```

擦除 `position` 指向的元素。

[horizontal]
返回：;; The iterator following `position` before the erasure.
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才会抛出异常。
注意：;; In older versions this could be inefficient because it had to search through several buckets to find the position of the returned iterator. The data structure has been changed so that this is no longer the case, and the alternative erase methods have been deprecated.

---

==== 按键擦除
```c++

size_type erase(const key_type& k); template<class K> size_type erase(K&& k);

```

擦除所有键等价于 `k` 的元素。

[horizontal]
返回：;; 被擦除的元素数量。
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才会抛出异常。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义，且 `iterator` 和 `const_iterator` 均不能从 `K` 隐式转换时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这启用了异构查找，避免了实例化 `Key` 类型的开销。

---

==== 范围擦除

```c++

iterator erase(const_iterator first, const_iterator last);

```

擦除从 `first` 到 `last` 范围内的元素。

[horizontal]
返回：;; 被擦除元素之后的迭代器——即 `last`。
抛出：;; Only throws an exception if it is thrown by `hasher` or `key_equal`. +
+
In this implementation, this overload doesn't call either function object's methods so it is no throw, but this might not be true in other implementations.

---

==== quick_erase
```c++

void quick_erase(const_iterator position);

```

擦除 `position` 指向的元素。

[horizontal]
抛出：;; Only throws an exception if it is thrown by `hasher` or `key_equal`. +
+
In this implementation, this overload doesn't call either function object's methods so it is no throw, but this might not be true in other implementations.
注意：;; This method was implemented because returning an iterator to the next element from erase was expensive, but the container has been redesigned so that is no longer the case. So this method is now deprecated.

---

==== erase_return_void
```c++

void erase_return_void(const_iterator position);

```

擦除 `position` 指向的元素。

[horizontal]
抛出：;; Only throws an exception if it is thrown by `hasher` or `key_equal`. +
+
In this implementation, this overload doesn't call either function object's methods so it is no throw, but this might not be true in other implementations.
注意：;; This method was implemented because returning an iterator to the next element from erase was expensive, but the container has been redesigned so that is no longer the case. So this method is now deprecated.

---

==== swap
```c++

void swap(unordered_map& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
           boost::is_nothrow_swappable_v<Hash> &&
           boost::is_nothrow_swappable_v<Pred>);

```

交换容器内容与参数。

若声明了 `Allocator::propagate_on_container_swap` 且 `Allocator::propagate_on_container_swap::value` 为 `true`，则交换容器的分配器；否则，与不相等分配器交换会导致未定义行为。

[horizontal]
抛出：;; Doesn't throw an exception unless it is thrown by the copy constructor or copy assignment operator of `key_equal` or `hasher`.
注意：;; The exception specifications aren't quite the same as the C++11 standard, as the equality predicate and hash function are swapped using their copy constructors.

---

==== clear
```c++

void clear();

```

擦除容器中所有元素。

[horizontal]
Postconditions:;; `size() == 0`
抛出：;; Never throws an exception.

---

==== merge
```c++

template<class H2, class P2>
  void merge(unordered_map<Key, T, H2, P2, Allocator>& source);
template<class H2, class P2>
  void merge(unordered_map<Key, T, H2, P2, Allocator>&& source);
template<class H2, class P2>
  void merge(unordered_multimap<Key, T, H2, P2, Allocator>& source);
template<class H2, class P2>
  void merge(unordered_multimap<Key, T, H2, P2, Allocator>&& source);

```

Attempt to "merge" two containers by iterating `source` and extracting any node in `source` that is not contained in `*this` and then inserting it into `*this`.

Because `source` can have a different hash function and key equality predicate, the key of each node in `source` is rehashed using `this\->hash_function()` and then, if required, compared using `this\->key_eq()`.

The behavior of this function is undefined if `this\->get_allocator() != source.get_allocator()`.

This function does not copy or move any elements and instead simply relocates the nodes from `source` into `*this`.

[horizontal]
注意：;;
+
--
* Pointers and references to transferred elements remain valid.
* Invalidates iterators to transferred elements.
* Invalidates iterators belonging to `*this`.
* Iterators to non-transferred elements in `source` remain valid.
--

* ---

=== 观察器

==== get_allocator
```

allocator_type get_allocator() const;

```

---

==== hash_function
```

hasher hash_function() const;

```

[horizontal]
返回：;; 容器的哈希函数。

---

==== key_eq
```

key_equal key_eq() const;

```

[horizontal]
返回：;; 容器的键值相等谓词

---

=== 查找

==== find
```c++

iterator         find(const key_type& k);
const_iterator   find(const key_type& k) const;
template<class K>
  iterator       find(const K& k);
template<class K>
  const_iterator find(const K& k) const;
template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
  iterator       find(CompatibleKey const& k, CompatibleHash const& hash,
                      CompatiblePredicate const& eq);
template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
  const_iterator find(CompatibleKey const& k, CompatibleHash const& hash,
                      CompatiblePredicate const& eq) const;

```

[horizontal]
返回：;; An iterator pointing to an element with key equivalent to `k`, or `b.end()` if no such element exists.
注意：;; The templated overloads containing `CompatibleKey`, `CompatibleHash` and `CompatiblePredicate` are non-standard extensions which allow you to use a compatible hash function and equality predicate for a key of a different type in order to avoid an expensive type cast. In general, its use is not encouraged and instead the `K` member function templates should be used. +
+
仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这启用了异构查找，避免了实例化 `Key` 类型的开销。

---

==== count
```c++

size_type        count(const key_type& k) const;
template<class K>
  size_type      count(const K& k) const;

```

[horizontal]
返回：;; 键等价于 `k` 的元素数量。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这启用了异构查找，避免了实例化 `Key` 类型的开销。

---

==== contains
```c++

bool             contains(const key_type& k) const;
template<class K>
  bool           contains(const K& k) const;

```

[horizontal]
返回：;; 指示容器中是否存在键等于 `key` 的元素的布尔值
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这启用了异构查找，避免了实例化 `Key` 类型的开销。

---

==== equal_range
```c++

std::pair<iterator, iterator>               equal_range(const key_type& k);
std::pair<const_iterator, const_iterator>   equal_range(const key_type& k) const;
template<class K>
  std::pair<iterator, iterator>             equal_range(const K& k);
template<class K>
  std::pair<const_iterator, const_iterator> equal_range(const K& k) const;

```

[horizontal]
返回：;; 包含所有键等价于 `k` 的元素的范围。若容器不包含此类元素，则返回 `std::make_pair(b.end(), b.end())`。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这启用了异构查找，避免了实例化 `Key` 类型的开销。

---

==== operator++[++++]++
```c++

mapped_type& operator[](const key_type& k); mapped_type& operator[](key_type&& k); template<class K> mapped_type& operator[](K&& k);

```

[horizontal]
效果：;; If the container does not already contain an elements with a key equivalent to `k`, inserts the value `std::pair<key_type const, mapped_type>(k, mapped_type())`.
返回：;; A reference to `x.second` where `x` is the element already in the container, or the newly inserted element with a key equivalent to `k`.
抛出：;; 若除调用 `hasher` 外的操作抛出异常，则函数无效果。
注意：;; Can invalidate iterators, but only if the insert causes the load factor to be greater to or equal to the maximum load factor. +
+
Pointers and references to elements are never invalidated. +
+
仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这启用了异构查找，避免了实例化 `Key` 类型的开销。

---

==== at
```c++

mapped_type& at(const key_type& k); const mapped_type& at(const key_type& k) const; template<class K> mapped_type& at(const K& k); template<class K> const mapped_type& at(const K& k) const;

```

[horizontal]
返回：;; A reference to `x.second` where `x` is the (unique) element whose key is equivalent to `k`.
抛出：;; An exception object of type `std::out_of_range` if no such element is present.
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这启用了异构查找，避免了实例化 `Key` 类型的开销。

---

=== 桶接口

==== bucket_count
```c++

size_type bucket_count() const noexcept;

```

[horizontal]
返回：;; The number of buckets.

---

==== max_bucket_count
```c++

size_type max_bucket_count() const noexcept;

```

[horizontal]
返回：;; An upper bound on the number of buckets.

---

==== bucket_size
```c++

size_type bucket_size(size_type n) const;

```

[horizontal]
Requires:;; `n < bucket_count()`
返回：;; The number of elements in bucket `n`.

---

==== bucket
```c++

size_type bucket(const key_type& k) const; template<class K> size_type bucket(const K& k) const;

```

[horizontal]
返回：;; The index of the bucket which would contain an element with key `k`.
Postconditions:;; The return value is less than `bucket_count()`.
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时用 `K` 和 `Key` 调用，且 `Pred` 是透明的。这启用了异构查找，避免了实例化 `Key` 类型的开销。

---

==== begin

```c++

local_iterator begin(size_type n); const_local_iterator begin(size_type n) const;

```

[horizontal]
Requires:;; `n` shall be in the range `[0, bucket_count())`.
返回：;; A local iterator pointing the first element in the bucket with index `n`.

---

==== end
```c++

local_iterator end(size_type n); const_local_iterator end(size_type n) const;

```

[horizontal]
Requires:;; `n` shall be in the range `[0, bucket_count())`.
返回：;; A local iterator pointing the 'one past the end' element in the bucket with index `n`.

---

==== cbegin
```c++

const_local_iterator cbegin(size_type n) const;

```

[horizontal]
Requires:;; `n` shall be in the range `[0, bucket_count())`.
返回：;; A constant local iterator pointing the first element in the bucket with index `n`.

---

==== cend
```c++

const_local_iterator cend(size_type n) const;

```

[horizontal]
Requires:;; `n` shall be in the range `[0, bucket_count())`.
返回：;; A constant local iterator pointing the 'one past the end' element in the bucket with index `n`.

---

=== 哈希策略

==== load_factor
```c++

float load_factor() const noexcept;

```

[horizontal]
返回：;; The average number of elements per bucket.

---

==== max_load_factor

```c++

float max_load_factor() const noexcept;

```

[horizontal]
返回：;; Returns the current maximum load factor.

---

==== 设置最大负载因子
```c++

void max_load_factor(float z);

```

[horizontal]
效果：;; Changes the container's maximum load factor, using `z` as a hint.

---


==== rehash
```c++

void rehash(size_type n);

```

Changes the number of buckets so that there are at least `n` buckets, and so that the load factor is less than or equal to the maximum load factor. When applicable, this will either grow or shrink the `bucket_count()` associated with the container.

When `size() == 0`, `rehash(0)` will deallocate the underlying buckets array.

Invalidates iterators, and changes the order of elements. Pointers and references to elements are not invalidated.

[horizontal]
抛出：;; 若抛出异常（除非由容器的哈希函数或比较函数抛出），则函数无效果。

---

==== reserve
```c++

void reserve(size_type n);

```

Equivalent to `a.rehash(ceil(n / a.max_load_factor()))`, or `a.rehash(1)` if `n > 0` and `a.max_load_factor() == std::numeric_limits<float>::infinity()`.

与 `rehash` 类似，此函数可用于增加或减少容器中的桶数量。

Invalidates iterators, and changes the order of elements. Pointers and references to elements are not invalidated.

[horizontal]
抛出：;; 若抛出异常（除非由容器的哈希函数或比较函数抛出），则函数无效果。

=== 推导指引
若以下任一条件成立，则推导指引不参与重载决议：

  - 具有 `InputIterator` 模板参数，且为该参数推导的类型不符合输入迭代器要求。
  - 具有 `Allocator` 模板参数，且为该参数推导的类型不符合分配器要求。
  - 具有 `Hash` 模板参数，且为该参数推导的类型为整型或符合分配器要求。
  - 具有 `Pred` 模板参数，且为该参数推导的类型符合分配器要求。

推导指引中的 `size_­type` 参数类型引用推导指引推导出的容器类型的 `size_­type` 成员类型。其默认值与所选构造函数的默认值一致。

==== __迭代器值类型__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-value-type__ =
    typename std::iterator_traits<InputIterator>::value_type; // 仅用于说明
-----

==== __iter-key-type__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-key-type__ = std::remove_const_t<
    std::tuple_element_t<0, xref:#unordered_map_iter_value_type[__iter-value-type__]<InputIterator>>>; // exposition only
-----

==== __iter-mapped-type__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-mapped-type__ =
    std::tuple_element_t<1, xref:#unordered_map_iter_value_type[__iter-value-type__]<InputIterator>>;  // exposition only
-----

==== __iter-to-alloc-type__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-to-alloc-type__ = std::pair<
    std::add_const_t<std::tuple_element_t<0, xref:#unordered_map_iter_value_type[__iter-value-type__]<InputIterator>>>,
    std::tuple_element_t<1, xref:#unordered_map_iter_value_type[__iter-value-type__]<InputIterator>>>; // exposition only
-----

=== 相等比较

==== operator==
```c++

template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator==(const unordered_map<Key, T, Hash, Pred, Alloc>& x,
                  const unordered_map<Key, T, Hash, Pred, Alloc>& y);

```

若 `x.size() == y.size()` 且对于 `x` 中的每个元素，`y` 中均存在一个具有相同键且值相等（使用 `operator==` 比较值类型）的元素，则返回 `true`。

[horizontal]
注意：;; 若两个容器的相等谓词不等价，则行为未定义。

---

==== operator!=
```c++

template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator!=(const unordered_map<Key, T, Hash, Pred, Alloc>& x,
                  const unordered_map<Key, T, Hash, Pred, Alloc>& y);

```

若 `x.size() == y.size()` 且对于 `x` 中的每个元素，`y` 中均存在一个具有相同键且值相等（使用 `operator==` 比较值类型）的元素，则返回 `false`。

[horizontal]
注意：;; 若两个容器的相等谓词不等价，则行为未定义。

=== Swap
```c++

template<class Key, class T, class Hash, class Pred, class Alloc>
  void swap(unordered_map<Key, T, Hash, Pred, Alloc>& x,
            unordered_map<Key, T, Hash, Pred, Alloc>& y)
    noexcept(noexcept(x.swap(y)));

```

交换 `x` 和 `y` 的内容。

若声明了 `Allocator::propagate_on_container_swap` 且 `Allocator::propagate_on_container_swap::value` 为 `true`，则交换容器的分配器；否则，与不相等分配器交换会导致未定义行为。

[horizontal]
效果：;; `x.swap(y)`
抛出：;; Doesn't throw an exception unless it is thrown by the copy constructor or copy assignment operator of `key_equal` or `hasher`.
注意：;; The exception specifications aren't quite the same as the C++11 standard, as the equality predicate and hash function are swapped using their copy constructors.

---

=== erase_if
```c++

template<class K, class T, class H, class P, class A, class Predicate>
  typename unordered_map<K, T, H, P, A>::size_type
    erase_if(unordered_map<K, T, H, P, A>& c, Predicate pred);

```

遍历容器 `c` 并移除所有满足谓词 `pred` 返回 `true` 的元素。

[horizontal]
返回：;; 被擦除的元素数量。
注意：;; 等价于：+
+
```c++

auto original_size = c.size();
for (auto i = c.begin(), last = c.end(); i != last; ) {
  if (pred(*i)) {
    i = c.erase(i);
  } else {
    ++i;
  }
}
return original_size - c.size();

```
+
Note that the references passed to `pred` are non-const.

=== 序列化

``unordered_map``s can be archived/retrieved by means of link:../../../../../serialization/index.html[Boost.Serialization^] using the API provided by this library. Both regular and XML archives are supported.

==== Saving an unordered_map to an archive

Saves all the elements of an `unordered_map` `x` to an archive (XML archive) `ar`.

[horizontal]
Requires:;; `std::remove_const<key_type>::type` and `std::remove_const<mapped_type>::type` are serializable (XML serializable), and they do support Boost.Serialization `save_construct_data`/`load_construct_data` protocol (automatically suported by https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible^] types).

---

==== Loading an unordered_map from an archive

Deletes all preexisting elements of an `unordered_map` `x` and inserts from an archive (XML archive) `ar` restored copies of the elements of the original `unordered_map` `other` saved to the storage read by `ar`.

[horizontal]
Requires:;; `value_type` is https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible^] from `(std::remove_const<key_type>::type&&, std::remove_const<mapped_type>::type&&)`. `x.key_equal()` is functionally equivalent to `other.key_equal()`.
注意：;; If the archive was saved using a release of Boost prior to Boost 1.84, the configuration macro `BOOST_UNORDERED_ENABLE_SERIALIZATION_COMPATIBILITY_V0` has to be globally defined for this operation to succeed; otherwise, an exception is thrown.

---

==== 将迭代器/常量迭代器保存到归档

将 `iterator`（`const_iterator`）`it` 的位置信息保存到归档（XML 归档）`ar` 中。`it` 可以是 `end()` 迭代器。

[horizontal]
Requires:;; The `unordered_map` `x` pointed to by `it` has been previously saved to `ar`, and no modifying operations have been issued on `x` between saving of `x` and saving of `it`.

---

==== 从归档加载迭代器/常量迭代器

使 `iterator`（`const_iterator`）`it` 指向保存到归档（XML 归档）`ar` 所读存储中的原始 `iterator`（`const_iterator`）的还原位置。

[horizontal]
Requires:;; If `x` is the `unordered_map` `it` points to, no modifying operations have been issued on `x` between loading of `x` and loading of `it`.
