[#unordered_map]
== 类模板 unordered++_++map

:idprefix: unordered_map_

`boost::unordered++_++map` — 一个无序关联容器，用于将唯一的键与另一个值关联起来。

=== 概要

[listing, subs="+macros,+quotes"]
-----
// #include xref:reference/header_unordered_map.adoc[<boost/unordered/unordered_map.hpp>]

namespace boost {
namespace unordered {

  template<class Key,
           class T,
           class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<std::pair<const Key, T>>>
  class unordered_map {
  public:
    // types
    using key_type             = Key;
    using mapped_type          = T;
    using value_type           = std::pair<const Key, T>;
    using hasher               = Hash;
    using key_equal            = Pred;
    using allocator_type       = Allocator;
    using pointer              = typename std::allocator_traits<Allocator>::pointer;
    using const_pointer        = typename std::allocator_traits<Allocator>::const_pointer;
    using reference            = value_type&;
    using const_reference      = const value_type&;
    using size_type            = std::size_t;
    using difference_type      = std::ptrdiff_t;

    using iterator             = _implementation-defined_;
    using const_iterator       = _implementation-defined_;
    using local_iterator       = _implementation-defined_;
    using const_local_iterator = _implementation-defined_;
    using node_type            = _implementation-defined_;
    using insert_return_type   = _implementation-defined_;

    // construct/copy/destroy
    xref:#unordered_map_default_constructor[unordered_map]();
    explicit xref:#unordered_map_bucket_count_constructor[unordered_map](size_type n,
                           const hasher& hf = hasher(),
                           const key_equal& eql = key_equal(),
                           const allocator_type& a = allocator_type());
    template<class InputIterator>
      xref:#unordered_map_iterator_range_constructor[unordered_map](InputIterator f, InputIterator l,
                    size_type n = _implementation-defined_,
                    const hasher& hf = hasher(),
                    const key_equal& eql = key_equal(),
                    const allocator_type& a = allocator_type());
    xref:#unordered_map_copy_constructor[unordered_map](const unordered_map& other);
    xref:#unordered_map_move_constructor[unordered_map](unordered_map&& other);
    template<class InputIterator>
      xref:#unordered_map_iterator_range_constructor_with_allocator[unordered_map](InputIterator f, InputIterator l, const allocator_type& a);
    explicit xref:#unordered_map_allocator_constructor[unordered_map](const Allocator& a);
    xref:#unordered_map_copy_constructor_with_allocator[unordered_map](const unordered_map& other, const Allocator& a);
    xref:#unordered_map_move_constructor_with_allocator[unordered_map](unordered_map&& other, const Allocator& a);
    xref:#unordered_map_initializer_list_constructor[unordered_map](std::initializer_list<value_type> il,
                  size_type n = _implementation-defined_
                  const hasher& hf = hasher(),
                  const key_equal& eql = key_equal(),
                  const allocator_type& a = allocator_type());
    xref:#unordered_map_bucket_count_constructor_with_allocator[unordered_map](size_type n, const allocator_type& a);
    xref:#unordered_map_bucket_count_constructor_with_hasher_and_allocator[unordered_map](size_type n, const hasher& hf, const allocator_type& a);
    template<class InputIterator>
      xref:#unordered_map_iterator_range_constructor_with_bucket_count_and_allocator[unordered_map](InputIterator f, InputIterator l, size_type n, const allocator_type& a);
    template<class InputIterator>
      xref:#unordered_map_iterator_range_constructor_with_bucket_count_and_hasher[unordered_map](InputIterator f, InputIterator l, size_type n, const hasher& hf,
                    const allocator_type& a);
    xref:#unordered_map_initializer_list_constructor_with_allocator[unordered_map](std::initializer_list<value_type> il, const allocator_type& a);
    xref:#unordered_map_initializer_list_constructor_with_bucket_count_and_allocator[unordered_map](std::initializer_list<value_type> il, size_type n, const allocator_type& a);
    xref:#unordered_map_initializer_list_constructor_with_bucket_count_and_hasher_and_allocator[unordered_map](std::initializer_list<value_type> il, size_type n, const hasher& hf,
                  const allocator_type& a);
    xref:#unordered_map_destructor[~unordered_map]();
    unordered_map& xref:#unordered_map_copy_assignment[operator++=++](const unordered_map& other);
    unordered_map& xref:#unordered_map_move_assignment[operator++=++](unordered_map&& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
               boost::is_nothrow_move_assignable_v<Hash> &&
               boost::is_nothrow_move_assignable_v<Pred>);
    unordered_map& xref:#unordered_map_initializer_list_assignment[operator++=++](std::initializer_list<value_type>);
    allocator_type xref:#unordered_map_get_allocator[get_allocator]() const noexcept;

    // iterators
    iterator       xref:#unordered_map_begin[begin]() noexcept;
    const_iterator xref:#unordered_map_begin[begin]() const noexcept;
    iterator       xref:#unordered_map_end[end]() noexcept;
    const_iterator xref:#unordered_map_end[end]() const noexcept;
    const_iterator xref:#unordered_map_cbegin[cbegin]() const noexcept;
    const_iterator xref:#unordered_map_cend[cend]() const noexcept;

    // capacity
    ++[[nodiscard]]++ bool xref:#unordered_map_empty[empty]() const noexcept;
    size_type xref:#unordered_map_size[size]() const noexcept;
    size_type xref:#unordered_map_max_size[max_size]() const noexcept;

    // modifiers
    template<class... Args> std::pair<iterator, bool> xref:#unordered_map_emplace[emplace](Args&&... args);
    template<class... Args> iterator xref:#unordered_map_emplace_hint[emplace_hint](const_iterator position, Args&&... args);
    std::pair<iterator, bool> xref:#unordered_map_copy_insert[insert](const value_type& obj);
    std::pair<iterator, bool> xref:#unordered_map_move_insert[insert](value_type&& obj);
    template<class P> std::pair<iterator, bool> xref:#unordered_map_emplace_insert[insert](P&& obj);
    iterator       xref:#unordered_map_copy_insert_with_hint[insert](const_iterator hint, const value_type& obj);
    iterator       xref:#unordered_map_move_insert_with_hint[insert](const_iterator hint, value_type&& obj);
    template<class P> iterator xref:#unordered_map_emplace_insert_with_hint[insert](const_iterator hint, P&& obj);
    template<class InputIterator> void xref:#unordered_map_insert_iterator_range[insert](InputIterator first, InputIterator last);
    void xref:#unordered_map_insert_initializer_list[insert](std::initializer_list<value_type>);

    template<class... Args>
      std::pair<iterator, bool> xref:#unordered_map_try_emplace[try_emplace](const key_type& k, Args&&... args);
    template<class... Args>
      std::pair<iterator, bool> xref:#unordered_map_try_emplace[try_emplace](key_type&& k, Args&&... args);
    template<class K, class... Args>
      std::pair<iterator, bool> xref:#unordered_map_try_emplace[try_emplace](K&& k, Args&&... args);
    template<class... Args>
      iterator xref:#unordered_map_try_emplace_with_hint[try_emplace](const_iterator hint, const key_type& k, Args&&... args);
    template<class... Args>
      iterator xref:#unordered_map_try_emplace_with_hint[try_emplace](const_iterator hint, key_type&& k, Args&&... args);
    template<class K, class... Args>
      iterator xref:#unordered_map_try_emplace_with_hint[try_emplace](const_iterator hint, K&& k, Args&&... args);
    template<class M>
      std::pair<iterator, bool> xref:#unordered_map_insert_or_assign[insert_or_assign](const key_type& k, M&& obj);
    template<class M>
      std::pair<iterator, bool> xref:#unordered_map_insert_or_assign[insert_or_assign](key_type&& k, M&& obj);
    template<class K, class M>
      std::pair<iterator, bool> xref:#unordered_map_insert_or_assign[insert_or_assign](K&& k, M&& obj);
    template<class M>
      iterator xref:#unordered_map_insert_or_assign_with_hint[insert_or_assign](const_iterator hint, const key_type& k, M&& obj);
    template<class M>
      iterator xref:#unordered_map_insert_or_assign_with_hint[insert_or_assign](const_iterator hint, key_type&& k, M&& obj);
    template<class K, class M>
      iterator xref:#unordered_map_insert_or_assign_with_hint[insert_or_assign](const_iterator hint, K&& k, M&& obj);

    node_type xref:#unordered_map_extract_by_iterator[extract](const_iterator position);
    node_type xref:#unordered_map_extract_by_key[extract](const key_type& k);
    template<class K> node_type xref:#unordered_map_extract_by_key[extract](K&& k);
    insert_return_type xref:#unordered_map_insert_with_node_handle[insert](node_type&& nh);
    iterator           xref:#unordered_map_insert_with_hint_and_node_handle[insert](const_iterator hint, node_type&& nh);

    iterator  xref:#unordered_map_erase_by_position[erase](iterator position);
    iterator  xref:#unordered_map_erase_by_position[erase](const_iterator position);
    size_type xref:#unordered_map_erase_by_key[erase](const key_type& k);
    template<class K> size_type xref:#unordered_map_erase_by_key[erase](K&& k);
    iterator  xref:#unordered_map_erase_range[erase](const_iterator first, const_iterator last);
    void      xref:#unordered_map_quick_erase[quick_erase](const_iterator position);
    void      xref:#unordered_map_erase_return_void[erase_return_void](const_iterator position);
    void      xref:#unordered_map_swap[swap](unordered_map& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
               boost::is_nothrow_swappable_v<Hash> &&
               boost::is_nothrow_swappable_v<Pred>);
    void      xref:#unordered_map_clear[clear]() noexcept;

    template<class H2, class P2>
      void xref:#unordered_map_merge[merge](unordered_map<Key, T, H2, P2, Allocator>& source);
    template<class H2, class P2>
      void xref:#unordered_map_merge[merge](unordered_map<Key, T, H2, P2, Allocator>&& source);
    template<class H2, class P2>
      void xref:#unordered_map_merge[merge](unordered_multimap<Key, T, H2, P2, Allocator>& source);
    template<class H2, class P2>
      void xref:#unordered_map_merge[merge](unordered_multimap<Key, T, H2, P2, Allocator>&& source);

    // observers
    hasher xref:#unordered_map_hash_function[hash_function]() const;
    key_equal xref:#unordered_map_key_eq[key_eq]() const;

    // map operations
    iterator         xref:#unordered_map_find[find](const key_type& k);
    const_iterator   xref:#unordered_map_find[find](const key_type& k) const;
    template<class K>
      iterator       xref:#unordered_map_find[find](const K& k);
    template<class K>
      const_iterator xref:#unordered_map_find[find](const K& k) const;
    template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
      iterator       xref:#unordered_map_find[find](CompatibleKey const& k, CompatibleHash const& hash,
                          CompatiblePredicate const& eq);
    template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
      const_iterator xref:#unordered_map_find[find](CompatibleKey const& k, CompatibleHash const& hash,
                          CompatiblePredicate const& eq) const;
    size_type        xref:#unordered_map_count[count](const key_type& k) const;
    template<class K>
      size_type      xref:#unordered_map_count[count](const K& k) const;
    bool             xref:#unordered_map_contains[contains](const key_type& k) const;
    template<class K>
      bool           xref:#unordered_map_contains[contains](const K& k) const;
    std::pair<iterator, iterator>               xref:#unordered_map_equal_range[equal_range](const key_type& k);
    std::pair<const_iterator, const_iterator>   xref:#unordered_map_equal_range[equal_range](const key_type& k) const;
    template<class K>
      std::pair<iterator, iterator>             xref:#unordered_map_equal_range[equal_range](const K& k);
    template<class K>
      std::pair<const_iterator, const_iterator> xref:#unordered_map_equal_range[equal_range](const K& k) const;

    // element access
    mapped_type& xref:#unordered_map_operator[operator[+]+](const key_type& k);
    mapped_type& xref:#unordered_map_operator[operator[+]+](key_type&& k);
    template<class K> mapped_type& xref:#unordered_map_operator[operator[+]+](K&& k);
    mapped_type& xref:#unordered_map_at[at](const key_type& k);
    const mapped_type& xref:#unordered_map_at[at](const key_type& k) const;
    template<class K> mapped_type& xref:#unordered_map_at[at](const K& k);
    template<class K> const mapped_type& xref:#unordered_map_at[at](const K& k) const;

    // bucket interface
    size_type xref:#unordered_map_bucket_count[bucket_count]() const noexcept;
    size_type xref:#unordered_map_max_bucket_count[max_bucket_count]() const noexcept;
    size_type xref:#unordered_map_bucket_size[bucket_size](size_type n) const;
    size_type xref:#unordered_map_bucket[bucket](const key_type& k) const;
    template<class K> size_type xref:#unordered_map_bucket[bucket](const K& k) const;
    local_iterator xref:#unordered_map_begin_2[begin](size_type n);
    const_local_iterator xref:#unordered_map_begin_2[begin](size_type n) const;
    local_iterator xref:#unordered_map_end_2[end](size_type n);
    const_local_iterator xref:#unordered_map_end_2[end](size_type n) const;
    const_local_iterator xref:#unordered_map_cbegin_2[cbegin](size_type n) const;
    const_local_iterator xref:#unordered_map_cend_2[cend](size_type n) const;

    // hash policy
    float xref:#unordered_map_load_factor[load_factor]() const noexcept;
    float xref:#unordered_map_max_load_factor[max_load_factor]() const noexcept;
    void xref:#unordered_map_set_max_load_factor[max_load_factor](float z);
    void xref:#unordered_map_rehash[rehash](size_type n);
    void xref:#unordered_map_reserve[reserve](size_type n);
  };

  // Deduction Guides
  template<class InputIterator,
           class Hash = boost::hash<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>>,
           class Pred = std::equal_to<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>>,
           class Allocator = std::allocator<xref:#unordered_map_iter_to_alloc_type[__iter-to-alloc-type__]<InputIterator>>>
    unordered_map(InputIterator, InputIterator, typename xref:#unordered_map_deduction_guides[__see below__]::size_type = xref:#unordered_map_deduction_guides[__see below__],
                  Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> unordered_map<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>, xref:#unordered_map_iter_mapped_type[__iter-mapped-type__]<InputIterator>, Hash, Pred,
                       Allocator>;

  template<class Key, class T, class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<std::pair<const Key, T>>>
    unordered_map(std::initializer_list<std::pair<Key, T>>,
                  typename xref:#unordered_map_deduction_guides[__see below__]::size_type = xref:#unordered_map_deduction_guides[__see below__], Hash = Hash(),
                  Pred = Pred(), Allocator = Allocator())
      -> unordered_map<Key, T, Hash, Pred, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_map(InputIterator, InputIterator, typename xref:#unordered_map_deduction_guides[__see below__]::size_type, Allocator)
      -> unordered_map<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>, xref:#unordered_map_iter_mapped_type[__iter-mapped-type__]<InputIterator>,
                       boost::hash<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>>,
                       std::equal_to<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_map(InputIterator, InputIterator, Allocator)
      -> unordered_map<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>, xref:#unordered_map_iter_mapped_type[__iter-mapped-type__]<InputIterator>,
                       boost::hash<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>>,
                       std::equal_to<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Hash, class Allocator>
    unordered_map(InputIterator, InputIterator, typename xref:#unordered_map_deduction_guides[__see below__]::size_type, Hash, Allocator)
      -> unordered_map<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>, xref:#unordered_map_iter_mapped_type[__iter-mapped-type__]<InputIterator>, Hash,
                       std::equal_to<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>>, Allocator>;

  template<class Key, class T, class Allocator>
    unordered_map(std::initializer_list<std::pair<Key, T>>, typename xref:#unordered_map_deduction_guides[__see below__]::size_type,
                  Allocator)
      -> unordered_map<Key, T, boost::hash<Key>, std::equal_to<Key>, Allocator>;

  template<class Key, class T, class Allocator>
    unordered_map(std::initializer_list<std::pair<Key, T>>, Allocator)
      -> unordered_map<Key, T, boost::hash<Key>, std::equal_to<Key>, Allocator>;

  template<class Key, class T, class Hash, class Allocator>
    unordered_map(std::initializer_list<std::pair<Key, T>>, typename xref:#unordered_map_deduction_guides[__see below__]::size_type, Hash,
                  Allocator)
      -> unordered_map<Key, T, Hash, std::equal_to<Key>, Allocator>;

} // 命名空间 unordered
} // 命名空间 boost
-----

---

=== 描述

*模板参数*

[cols="1,1"]
|===

|_键_
|`Key`
需满足从容器中 https://en.cppreference.com/w/cpp/named_req/Erasable[可擦除] 的要求（即
`allocator++_++traits` 能够销毁该对象）。

|_T_
|`T`
需满足从容器 https://en.cppreference.com/w/cpp/named_req/Erasable[可擦除]
的要求（即 `allocator++_++traits` 能够销毁该对象）。

|_Hash_
|一元函数对象类型，用作 `Key` 的哈希函数。它接受一个类型为 `Key`
的参数，并返回一个 `std::size++_++t` 类型的值。

|_谓词_
|一种二元函数对象，用于在 `Key`
类型的值上建立等价关系。它接受两个类型为 `Key`
的参数，并返回一个布尔类型的值。

|_分配器_
|一种分配器，其值类型与容器的值类型相同，是一种支持使用 https://en.cppreference.com/w/cpp/named_req/Allocator#Fancy_pointers[花式指针] 的分配器。

|===

元素被组织到多个桶中。具有相同哈希码的键存储在同一个桶内。

桶的数量可通过调用插入操作来自动增加，也可通过调用重哈希操作来调整。

=== 配置宏

==== `BOOST++_++UNORDERED++_++ENABLE++_++SERIALIZATION++_++COMPATIBILITY++_++V0`

全局定义此宏，以支持加载在 Boost.Serialization 归档中保存的 `unordered++_++map` 容器，这些归档是保存在 Boost 1.84 之前的版本中。

=== 类型定义

[source, c++, subs=+quotes]
----
typedef _implementation-defined_ iterator;
----

一种迭代器，其值类型为 `value++_++type` 。

迭代器类别至少为前向迭代器。

可转换为 `const++_++iterator` 。

---

[source, c++, subs=+quotes]
----
typedef _implementation-defined_ const_iterator;
----

一个常量迭代器，其值类型为 `value++_++type` 。

迭代器类别至少为前向迭代器。

---

[source, c++, subs=+quotes]
----
typedef _implementation-defined_ local_iterator;
----

一种迭代器，其值类型、差值类型以及指针和引用类型均与 iterator 相同。

`local++_++iterator` 对象可用于遍历单个桶内的元素。

---

[source, c++, subs=+quotes]
----
typedef _implementation-defined_ const_local_iterator;
----

一种常量迭代器，其值类型、差值类型以及指针和引用类型均与 const++_++iterator 相同。

const++_++local++_++iterator 对象可用于遍历单个桶内的元素。

---

[source, c++, subs=+quotes]
----
typedef _implementation-defined_ node_type;
----

用于保存已提取容器元素的类，其建模自 https://en.cppreference.com/w/cpp/container/node_handle[NodeHandle] 。

---

[source, c++, subs=+quotes]
----
typedef _implementation-defined_ insert_return_type;
----

内部类模板的特化：

[source, c++, subs=+quotes]
----
template<class Iterator, class NodeType>
struct _insert_return_type_ // name is exposition only
{
  Iterator position;
  bool     inserted;
  NodeType node;
};
----

其中 `Iterator` = `iterator` ，且 `NodeType` = `node++_++type` 。

---

=== 构造函数

==== 默认构造函数
```c++

unordered_map();

```

构造一个空容器，使用 `hasher()` 作为哈希函数、 `key++_++equal()` 作为键相等性谓词、 `allocator++_++type()` 作为分配器，并将最大负载因子设为 `1.0` 。

[horizontal]
后置条件;; `size() == 0`
要求;; 若使用默认值，则 `hasher` 、 `key++_++equal` 和 `allocator++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 桶数构造函数
```c++

explicit unordered_map(size_type n,
                       const hasher& hf = hasher(),
                       const key_equal& eql = key_equal(),
                       const allocator_type& a = allocator_type());

```

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数， `eql` 作为键相等性谓词， `a` 作为分配器，并将最大负载因子设为 `1.0` 。

[horizontal]
后置条件;; `size() == 0`
要求;; 若使用默认值，则 `hasher` 、 `key++_++equal` 和 `allocator++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  unordered_map(InputIterator f, InputIterator l,
                size_type n = _implementation-defined_,
                const hasher& hf = hasher(),
                const key_equal& eql = key_equal(),
                const allocator_type& a = allocator_type());
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、 `eql` 作为键相等性谓词、 `a` 作为分配器，将最大负载因子设为 `1.0` ，并将区间 `++[++f, l)` 中的元素插入其中。

[horizontal]
要求;; 若使用默认值，则 `hasher` 、 `key++_++equal` 和 `allocator++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 复制构造函数
```c++

unordered_map(unordered_map const& other);

```

复制构造函数。复制其所含的元素、哈希函数、谓词、最大负载因子及分配器。

若 `Allocator::select++_++on++_++container++_++copy++_++construction` 存在且签名正确，则将根据其结果来构造分配器。

[horizontal]
要求;; `value++_++type` 必须满足可复制构造要求

---

==== 移动构造函数
```c++

unordered_map(unordered_map&& other);

```

移动构造函数。

[horizontal]
注意;; 此函数通过 Boost.Move 实现。
要求;; `value++_++type` 必须满足可移动构造的要求。

---

==== 带分配器的迭代器范围构造函数
```c++

template<class InputIterator>
  unordered_map(InputIterator f, InputIterator l, const allocator_type& a);

```

构造一个空容器，使用 `a` 作为分配器、默认的哈希函数和键相等性谓词，并将最大负载因子设为 `1.0` ，然后将 `++[++f, l)` 范围内的元素插入其中。

[horizontal]
要求;; `hasher` 和 `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 分配器构造函数
```c++

explicit unordered_map(Allocator const& a);

```

使用分配器 `a` 构造一个空容器。

---

==== 带分配器的复制构造函数
```c++

unordered_map(unordered_map const& other, Allocator const& a);

```

构造一个容器，复制 `other` 中的元素、哈希函数、谓词及最大负载因子，但使用分配器 `a` 。

---

==== 带分配器的移动构造函数
```c++

unordered_map(unordered_map&& other, Allocator const& a);

```

构造一个容器，移动 `other` 中所包含的元素，并获取其哈希函数、谓词及最大负载因子，但使用分配器 `a` 。

[horizontal]
注意;; 此函数通过 Boost.Move 实现。
要求;; `value++_++type` 需满足可移动插入要求。

---

==== 初始化列表构造函数
[source, c++, subs="+quotes"]
----
unordered_map(std::initializer_list<value_type> il,
              size_type n = _implementation-defined_
              const hasher& hf = hasher(),
              const key_equal& eql = key_equal(),
              const allocator_type& a = allocator_type());
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、 `eql` 作为键相等性谓词、及 `a` 作为分配器，并设置最大负载因子为 `1.0` ，随后将 `il` 中的元素插入该容器。

[horizontal]
要求;; 若使用默认值，则 `hasher` 、 `key++_++equal` 和 `allocator++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带分配器的桶数构造函数
```c++

unordered_map(size_type n, allocator_type const& a);

```

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数（应为默认哈希函数）、默认的键相等性谓词、 `a` 作为分配器，并设置最大负载因子为 `1.0` 。

[horizontal]
后置条件;; `size() == 0`
要求;; `hasher` 和 `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带哈希函数和分配器的桶数构造函数
```c++

unordered_map(size_type n, hasher const& hf, allocator_type const& a);

```

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、默认的键相等性谓词、 `a` 作为分配器，并设置最大负载因子为 `1.0` 。

[horizontal]
后置条件;; `size() == 0`
要求;; `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带桶数和分配器的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  unordered_map(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `a` 作为分配器、默认的哈希函数和键相等性谓词，并设置最大负载因子为 `1.0` ，随后将区间 `++[++f, l)` 中的元素插入该容器。

[horizontal]
要求;; `hasher` 和 `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带桶数和哈希函数的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
    template<class InputIterator>
      unordered_map(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                    const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、默认的键相等性谓词、 `a` 作为分配器，并设置最大负载因子为 `1.0` ，随后将区间 `++[++f, l)` 中的元素插入该容器。

[horizontal]
要求;; `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带分配器的初始化列表构造函数

```c++

unordered_map(std::initializer_list<value_type> il, const allocator_type& a);

```

使用 `a` 作为分配器构造一个空容器，设置最大负载因子为 1.0，并将 `il` 中的元素插入其中。

[horizontal]
要求;; `hasher` 和 `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带桶数和分配器的初始化列表构造函数

```c++

unordered_map(std::initializer_list<value_type> il, size_type n, const allocator_type& a);

```

构造一个至少包含 `n` 个桶的空容器，使用 `a` 作为分配器，并设置最大负载因子为 1.0，随后将 `il` 中的元素插入该容器。

[horizontal]
要求;; `hasher` 和 `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带桶数、哈希函数和分配器的初始化列表构造函数

```c++

unordered_map(std::initializer_list<value_type> il, size_type n, const hasher& hf,
              const allocator_type& a);

```

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、 `a` 作为分配器，设置最大负载因子为 1.0，并将 `il` 中的元素插入其中。

[horizontal]
要求;; `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

=== 析构函数

```c++

~unordered_map();

```

[horizontal]
注意;; 析构函数会作用于每个元素，并释放所有内存

---

=== 赋值操作

==== 复制赋值

```c++

unordered_map& operator=(unordered_map const& other);

```

赋值运算符。该操作会复制容器内的元素、哈希函数、谓词及最大负载因子，但不会复制分配器。

如果 `Alloc::propagate++_++on++_++container++_++copy++_++assignment` 存在且 `Alloc::propagate++_++on++_++container++_++copy++_++assignment::value` 为 `true` ，则覆盖原分配器；否则将使用现有分配器创建被复制的元素。

[horizontal]
要求;; `value++_++type` 必须满足可复制构造要求

---

==== 移动赋值
```c++

unordered_map& operator=(unordered_map&& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
           boost::is_nothrow_move_assignable_v<Hash> &&
           boost::is_nothrow_move_assignable_v<Pred>);

```
移动赋值运算符。

如果 `Alloc::propagate++_++on++_++container++_++move++_++assignment` 存在且 `Alloc::propagate++_++on++_++container++_++move++_++assignment::value` 为 `true` ，则覆盖原分配器；否则将使用现有分配器创建被复制的元素。

[horizontal]
要求;; `value++_++type` 需满足可移动构造要求。

---

==== 初始化列表赋值
```c++

unordered_map& operator=(std::initializer_list<value_type> il);

```

将初始化列表中的值赋给容器。所有已存在的元素将被新元素覆盖或销毁。

[horizontal]
要求;; `value++_++type` 必须满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入] 至容器以及 https://en.cppreference.com/w/cpp/named_req/CopyAssignable[可复制赋值] 的要求。

=== 迭代器

==== begin
```c++

iterator begin() noexcept; const_iterator begin() const noexcept;

```

[horizontal]
返回;; 返回一个指向容器第一个元素的迭代器；若容器为空，则返回容器的结束迭代器。

---

==== end
```c++

iterator end() noexcept; const_iterator end() const noexcept;

```

[horizontal]
返回;; 返回指向容器结束位置的迭代器。

---

==== cbegin
```c++

const_iterator cbegin() const noexcept;

```

[horizontal]
返回;; 返回一个指向容器第一个元素的 `const++_++iterator` （常量迭代器）；若容器为空，则返回容器的结束迭代器。

---

==== cend
```c++

const_iterator cend() const noexcept;

```

[horizontal]
返回;; 返回一个指向容器结束位置的 `const++_++iterator` （常量迭代器）。

---

=== 大小与容量

==== 空

```c++

[[nodiscard]] bool empty() const noexcept;

```

[horizontal]
返回;; `size() == 0`

---

==== 大小

```c++

size_type size() const noexcept;

```

[horizontal]
返回;; `std::distance(begin(), end())`

---

==== max++_++size

```c++

size_type max_size() const noexcept;

```

[horizontal]
返回;; 返回该容器可能容纳的最大值 `size()` 。

---

=== 修改器

==== 原地构造
```c++

template<class... Args> std::pair<iterator, bool> emplace(Args&&... args);

```

当且仅当容器中不存在具有等价键的元素时，插入一个由参数 `args` 构造的对象。

[horizontal]
要求;; `value++_++type` 必须满足从 `args` 参数 https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原位构造] 到 `X` 容器的要求。
返回;; 若插入成功，则返回类型的布尔分量为 true。 +
+
若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
指向元素的指针和引用永远不会失效。 +
+
若 `args…` 的格式为 `k,v` ，该实现会延迟构造完整对象，直到确认需要插入元素时为止，在此期间仅使用参数 `k` 进行检查。当映射的 `key++_++type` 可移动构造，或参数 `k` 的类型为 `key++_++type` 时，此优化生效。

---

==== emplace++_++hint
```c++

template<class... Args> iterator emplace_hint(const_iterator position, Args&&... args);

```

当且仅当容器中不存在具有等价键的元素时，插入一个由参数 `args` 构造的对象。

`position` 是一个关于插入元素位置的建议。

[horizontal]
要求;; `value++_++type` 必须满足从 `args` 参数 https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原位构造] 到 `X` 容器的要求。
返回;; 若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; C{plus}{plus}标准对提示参数含义的规定相当笼统。在实际使用中唯一有效的方式（也是Boost.Unordered唯一支持的用法）是指向具有相同键的现有元素。 +
+
可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
指向元素的指针和引用永远不会失效。 +
+
若 `args…` 的格式为 `k,v` ，该实现会延迟构造完整对象，直到确认需要插入元素时为止，在此期间仅使用参数 `k` 进行检查。当映射的 `key++_++type` 可移动构造，或参数 `k` 的类型为 `key++_++type` 时，此优化生效。

---

==== 复制插入
```c++

std::pair<iterator, bool> insert(const value_type& obj);

```

当且仅当容器中不存在等价键时，将 `obj` 对象插入到容器中。

[horizontal]
要求;; `value++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入] 要求。
返回;; 若插入成功，则返回类型的布尔分量为 true。 +
+
若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
指向元素的指针和引用永远不会失效。

---

==== 移动插入
```c++

std::pair<iterator, bool> insert(value_type&& obj);

```

当且仅当容器中不存在等价键时，将 `obj` 对象插入到容器中。

[horizontal]
要求;; `value++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入] 要求。
返回;; 若插入成功，则返回类型的布尔分量为 true。 +
+
若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
指向元素的指针和引用永远不会失效。

---

==== 原地插入
```c++

template<class P> std::pair<iterator, bool> insert(P&& obj);

```

通过执行 `emplace(std::forward++<++P++>++(value))` 将元素插入容器。

仅当 `std::is++_++constructible++<++value++_++type, P&&++>++::value` 为 `true` 时，才会参与重载决议。

[horizontal]
返回;; 若插入成功，则返回类型的布尔分量为 true。 +
+
若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。

---

==== 带提示的复制插入
```c++

iterator insert(const_iterator hint, const value_type& obj);

``` 当且仅当容器中不存在等价键时，将 `obj` 对象插入到容器中。

`hint` 是插入元素位置的建议。

[horizontal]
要求;; `value++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入] 要求。
返回;; 若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; C{plus}{plus}标准对提示参数含义的规定相当笼统。在实际使用中唯一有效的方式（也是Boost.Unordered唯一支持的用法）是指向具有相同键的现有元素。 +
+
可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
指向元素的指针和引用永远不会失效。

---

==== 带提示的移动插入
```c++

iterator insert(const_iterator hint, value_type&& obj);

```

当且仅当容器中不存在等价键时，将 `obj` 对象插入到容器中。

`hint` 是插入元素位置的建议。

[horizontal]
要求;; `value++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入] 要求。
返回;; 若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; C{plus}{plus}标准对提示参数含义的规定相当笼统。在实际使用中唯一有效的方式（也是Boost.Unordered唯一支持的用法）是指向具有相同键的现有元素。 +
+
可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
指向元素的指针和引用永远不会失效。

---

==== 带提示的原地插入

```c++

template<class P> iterator insert(const_iterator hint, P&& obj);

```

通过执行 `emplace++_++hint(hint, std::forward++<++P++>++(value))` 将元素插入容器。

仅当 `std::is++_++constructible++<++value++_++type, P&&++>++::value` 为 `true` 时，才会参与重载决议。

`hint` 是插入元素位置的建议。

[horizontal]
返回;; 若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
注意;; C{plus}{plus}标准对提示参数含义的规定相当笼统。在实际使用中唯一有效的方式（也是Boost.Unordered唯一支持的用法）是指向具有相同键的现有元素。 +
+
可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
指向元素的指针和引用永远不会失效。

---

==== 迭代器范围插入
```c++

template<class InputIterator> void insert(InputIterator first, InputIterator last);

```

将元素范围插入容器中。仅当容器中不存在等价键的元素时，才会插入相应元素。

[horizontal]
要求;; `value++_++type` 必须能够通过 `++*++first` 进行 https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原地构造] 到 `X` 中。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
指向元素的指针和引用永远不会失效。

---

==== 初始化列表插入
```c++

void insert(std::initializer_list<value_type>);

```

将元素范围插入容器中。仅当容器中不存在等价键的元素时，才会插入相应元素。

[horizontal]
要求;; `value++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入] 到容器中的要求。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
指向元素的指针和引用永远不会失效。

---

==== try++_++emplace
```c++

template<class... Args>
  std::pair<iterator, bool> try_emplace(const key_type& k, Args&&... args);
template<class... Args>
  std::pair<iterator, bool> try_emplace(key_type&& k, Args&&... args);
template<class K, class... Args>
  std::pair<iterator, bool> try_emplace(K&& k, Args&&... args)

```

若容器中不存在键为 `k` 的元素，则插入一个新元素。

若存在键为 `k` 的元素，则此函数不执行任何操作。

[horizontal]
返回;; 若插入成功，则返回类型的布尔分量为 true。 +
+
若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 此函数与 xref:#unordered_map_emplace[emplace] 类似，但 `value++_++type` 的构造方式为： +
+
--
```c++

// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

```

而非 xref:#unordered_map_emplace[emplace] 直接转发所有参数到 ``value_type`` 的构造函数。

可能使迭代器失效，但仅当插入导致负载因子大于或等于最大负载因子时。

指向元素的指针和引用永远不会失效。

仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent` 均为有效的成员类型别名，且 `iterator` 和 `const++_++iterator` 均不能从 `K` 隐式转换时， `template++<++class K, class... Args++>++` 重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。
--

---

==== 带提示的 try++_++emplace
```c++

template<class... Args>
  iterator try_emplace(const_iterator hint, const key_type& k, Args&&... args);
template<class... Args>
  iterator try_emplace(const_iterator hint, key_type&& k, Args&&... args);
template<class K, class... Args>
  iterator try_emplace(const_iterator hint, K&& k, Args&&... args);

```

若容器中不存在键为 `k` 的元素，则插入一个新元素。

若存在键为 `k` 的元素，则此函数不执行任何操作。

`hint` 是插入元素位置的建议。

[horizontal]
返回;; 若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 此函数与 xref:#unordered_map_emplace_hint[emplace++_++hint] 类似，但 `value++_++type` 的构造方式为： +
+
--
```c++

// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

```

而非 xref:#unordered_map_emplace_hint[emplace_hint] 直接转发所有参数到 ``value_type`` 的构造函数。

标准对提示的含义相当模糊。但唯一实用的使用方式（也是 Boost.Unordered 支持的唯一方式）是指向具有相同键的现有元素。

可能使迭代器失效，但仅当插入导致负载因子大于或等于最大负载因子时。

指向元素的指针和引用永远不会失效。

仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent` 均为有效的成员类型别名，且 `iterator` 和 `const++_++iterator` 均不能从 `K` 隐式转换时， `template++<++class K, class... Args++>++` 重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。
--

---

==== insert++_++or++_++assign
```c++

template<class M>
  std::pair<iterator, bool> insert_or_assign(const key_type& k, M&& obj);
template<class M>
  std::pair<iterator, bool> insert_or_assign(key_type&& k, M&& obj);
template<class K, class M>
  std::pair<iterator, bool> insert_or_assign(K&& k, M&& obj);

```

向容器中插入新元素，或通过赋值给已存在的元素值来更新该元素。

如果存在键为 `k` 的元素，则通过赋值 `std::forward++<++M++>++(obj)` 来更新该元素。

若不存在该元素，则将其以如下方式添加到容器中： ```c++

// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))

```

[horizontal]
返回;; 若插入成功，则返回类型的布尔分量为 true。 +
+
若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
指向元素的指针和引用永远不会失效。 +
+
仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K, class M++>++` 才会参与重载决议。标准库假设 `Hash` 可同时被 `K` 与 `Key` 类型调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型对象所需的开销。

---

==== 带提示的 insert++_++or++_++assign
```c++

template<class M>
  iterator insert_or_assign(const_iterator hint, const key_type& k, M&& obj);
template<class M>
  iterator insert_or_assign(const_iterator hint, key_type&& k, M&& obj);
template<class K, class M>
  iterator insert_or_assign(const_iterator hint, K&& k, M&& obj);

```

向容器中插入新元素，或通过赋值给已存在的元素值来更新该元素。

如果存在键为 `k` 的元素，则通过赋值 `std::forward++<++M++>++(obj)` 来更新该元素。

若不存在该元素，则将其以如下方式添加到容器中： ```c++

// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))

```

`hint` 是插入元素位置的建议。

[horizontal]
返回;; 若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; C{plus}{plus}标准对提示参数含义的规定相当笼统。在实际使用中唯一有效的方式（也是Boost.Unordered唯一支持的用法）是指向具有相同键的现有元素。 +
+
可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
指向元素的指针和引用永远不会失效。 +
+
仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K, class M++>++` 才会参与重载决议。标准库假设 `Hash` 可同时被 `K` 与 `Key` 类型调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型对象所需的开销。

---

==== 通过迭代器提取
```c++

node_type extract(const_iterator position);

```

移除由 `position` 指向的元素。

[horizontal]
返回;; 返回一个拥有该元素的 `node++_++type` 对象。
注意;; 通过此方法提取的节点可被插入到兼容的 `unordered++_++multimap` 容器中。

---

==== 通过键提取
```c++

node_type extract(const key_type& k); template<class K> node_type extract(K&& k);

```

移除键等价于 `k` 的元素。

[horizontal]
返回;; 如果找到，则返回一个拥有该元素的 `node++_++type` 对象；否则返回一个空的 `node++_++type` 对象。
抛出;; 仅当 `hasher` 或 `key++_++equal` 抛出异常时，才会抛出异常。
注意;; 通过此方法提取的节点可被插入到兼容的 `unordered++_++multimap` 容器中。 +
+
仅当 `Hash::is++_++transparent` 与 `Pred::is++_++transparent` 均为有效的成员类型别名，且 `iterator` 和 `const++_++iterator` 均不能从 `K` 类型隐式转换时， `template++<++class K++>++` 重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 类型调用，且 `Pred` 为透明谓词。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

==== 通过 `node++_++handle` 插入
```c++

insert_return_type insert(node_type&& nh);

```

若 `nh` 为空节点，则此操作不产生任何效果。

否则，当且仅当容器中不存在等价键的元素时，才会插入 `nh` 所拥有的元素。

[horizontal]
要求;; `nh` 必须是空节点，或其分配器 `nh.get++_++allocator()` 需与容器的分配器相等。
返回;; 如果 `nh` 为空，则返回一个 `insert++_++return++_++type` ，其中： `inserted` 等于 `false` ， `position` 等于 `end()` ，且 `node` 为空。 +
+
否则，如果已存在具有等价键的元素，则返回一个 `insert++_++return++_++type` ，其中： `inserted` 等于 `false` ， `position` 指向匹配的元素，且 `node` 包含来自 `nh` 的节点。 +
+
否则，如果插入操作成功，则返回一个 `insert++_++return++_++type` ，其中： `inserted` 等于 `true` ， `position` 指向新插入的元素，且 `node` 为空。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
指向元素的指针和引用永远不会失效。 +
+
此方法可用于插入从兼容的 `unordered++_++multimap` 容器中提取的节点。

---

==== 带提示和 `node++_++handle` 的插入
```c++

iterator insert(const_iterator hint, node_type&& nh);

```

若 `nh` 为空节点，则此操作不产生任何效果。

否则，当且仅当容器中不存在等价键的元素时，才会插入 `nh` 所拥有的元素。

如果容器中已存在具有等价键的元素，则对 `nh` 不产生任何影响.（即 `nh` 仍持有该节点.）

`hint` 是插入元素位置的建议。

[horizontal]
要求;; `nh` 必须是空节点，或其分配器 `nh.get++_++allocator()` 需与容器的分配器相等。
返回;; 如果 `nh` 为空，则返回 `end()` 。 +
+
若容器中已存在具有等效键的元素，则返回指向该元素的迭代器。 +
+
否则，返回指向新插入元素的迭代器。
抛出;; 若异常由调用 hasher 以外的操作抛出，则此函数不产生任何效果。
注意;; C{plus}{plus}标准对提示参数含义的规定相当笼统。在实际使用中唯一有效的方式（也是Boost.Unordered唯一支持的用法）是指向具有相同键的现有元素。 +
+
可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
指向元素的指针和引用永远不会失效。 +
+
此方法可用于插入从兼容的 `unordered++_++multimap` 容器中提取的节点。

---

==== 通过位置擦除

```c++

iterator erase(iterator position); iterator erase(const_iterator position);

```

擦除由 `position` 指向的元素。

[horizontal]
返回;; 返回擦除操作前紧接在 `position` 之后的迭代器。
抛出;; 仅当 `hasher` 或 `key++_++equal` 抛出异常时，才会抛出异常。
注意;; 在旧版本中，此操作可能效率较低，因为需要遍历多个桶来定位返回迭代器的位置。但数据结构现已优化，不再存在此问题，因此其他擦除方法已被弃用。

---

==== 通过键擦除
```c++

size_type erase(const key_type& k); template<class K> size_type erase(K&& k);

```

擦除所有键等价于 `k` 的元素。

[horizontal]
返回;; 被擦除的元素数量。
抛出;; 仅当 `hasher` 或 `key++_++equal` 抛出异常时，才会抛出异常。
注意;; 仅当 `Hash::is++_++transparent` 与 `Pred::is++_++transparent` 均为有效的成员类型别名，且 `iterator` 和 `const++_++iterator` 均不能从 `K` 类型隐式转换时， `template++<++class K++>++` 重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 类型调用，且 `Pred` 为透明谓词。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

==== 范围擦除

```c++

iterator erase(const_iterator first, const_iterator last);

```

擦除从 `first` 到 `last` 范围内（包含 `first` ，不包含 `last` ）的元素。

[horizontal]
返回;; 返回被擦除元素之后的迭代器——即 `last` 。
抛出;; 仅当 `hasher` 或 `key++_++equal` 抛出异常时，本函数才会抛出异常。 +
+
在此实现中，此重载不会调用任一函数对象的方法，因此不会抛出异常，但在其他实现中可能并非如此。

---

==== quick++_++erase
```c++

void quick_erase(const_iterator position);

```

擦除由 `position` 指向的元素。

[horizontal]
抛出;; 仅当 `hasher` 或 `key++_++equal` 抛出异常时，本函数才会抛出异常。 +
+
在此实现中，此重载不会调用任一函数对象的方法，因此不会抛出异常，但在其他实现中可能并非如此。
注意;; 此方法被实现是因为从擦除操作返回下一个元素的迭代器代价高昂，但容器经过重新设计后该问题已得到解决，因此该方法现已被弃用。

---

==== erase++_++return++_++void
```c++

void erase_return_void(const_iterator position);

```

擦除由 `position` 指向的元素。

[horizontal]
抛出;; 仅当 `hasher` 或 `key++_++equal` 抛出异常时，本函数才会抛出异常。 +
+
在此实现中，此重载不会调用任一函数对象的方法，因此不会抛出异常，但在其他实现中可能并非如此。
注意;; 此方法被实现是因为从擦除操作返回下一个元素的迭代器代价高昂，但容器经过重新设计后该问题已得到解决，因此该方法现已被弃用。

---

==== 交换
```c++

void swap(unordered_map& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
           boost::is_nothrow_swappable_v<Hash> &&
           boost::is_nothrow_swappable_v<Pred>);

```

交换容器与参数的内容。

如果声明了 `Allocator::propagate++_++on++_++container++_++swap` 且 `Allocator::propagate++_++on++_++container++_++swap::value` 为 `true` ，则交换容器的分配器。则，在分配器不相等的情况下进行交换将导致未定义行为。

[horizontal]
抛出;; 除非异常由 `key++_++equal` 或 `hasher` 的复制构造函数或复制赋值运算符抛出，否则本操作不会抛出异常。
注意;; 此处的异常规范与 C{plus}{plus}11 标准不完全一致，因为相等性谓词和哈希函数是通过其复制构造函数完成交换的。

---

==== 清空
```c++

void clear();

```

擦除容器中的所有元素。

[horizontal]
后置条件;; `size() == 0`
抛出;; 从不抛出任何异常。

---

==== 合并
```c++

template<class H2, class P2>
  void merge(unordered_map<Key, T, H2, P2, Allocator>& source);
template<class H2, class P2>
  void merge(unordered_map<Key, T, H2, P2, Allocator>&& source);
template<class H2, class P2>
  void merge(unordered_multimap<Key, T, H2, P2, Allocator>& source);
template<class H2, class P2>
  void merge(unordered_multimap<Key, T, H2, P2, Allocator>&& source);

```

通过遍历 `source` 容器，提取其中所有不包含在 `++*++this` 中的节点，并将其插入到 `++*++this` 中，以此尝试将两个容器"合并"。

由于 `source` 可以有不同的哈希函数和键相等性谓词，因此会使用 `this-++>++hash++_++function()` 操作对 `source` 中每个节点的键进行重哈希，并在需要时使用 `this-++>++key++_++eq()` 进行比较。

如果 `this-++>++get++_++allocator() != source.get++_++allocator()` ，则此函数的行为未定义。

此函数不会复制或移动任何元素，而是直接将节点从 `source` 重新定位到 `++*++this` 中。

[horizontal]
注意;;
+
--
* 指向被转移元素的指针和引用保持有效。
* 使指向被转移元素的迭代器失效。
* 使属于 `++*++this` 的迭代器失效。
* 指向 `source` 中未被转移元素的迭代器保持有效。
--

* ---

=== 观察器

==== get++_++allocator
```

allocator_type get_allocator() const;

```

---

==== 哈希函数
```

hasher hash_function() const;

```

[horizontal]
返回;; 容器的哈希函数。

---

==== key++_++eq
```

key_equal key_eq() const;

```

[horizontal]
返回;; 容器的键相等性谓词

---

=== 查找

==== find
```c++

iterator         find(const key_type& k);
const_iterator   find(const key_type& k) const;
template<class K>
  iterator       find(const K& k);
template<class K>
  const_iterator find(const K& k) const;
template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
  iterator       find(CompatibleKey const& k, CompatibleHash const& hash,
                      CompatiblePredicate const& eq);
template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
  const_iterator find(CompatibleKey const& k, CompatibleHash const& hash,
                      CompatiblePredicate const& eq) const;

```

[horizontal]
返回;; 返回一个指向键等价于 `k` 的元素的迭代器，若不存在这样的元素，则返回 `b.end()` 。
注意;; 包含 `CompatibleKey` 、 `CompatibleHash` 和 `CompatiblePredicate` 的模板化重载是非标准扩展，允许用户使用兼容的哈希函数和相等性谓词来处理不同类型的键，以避免昂贵的类型转换。通常不鼓励使用此扩展，而应改用基于 `K` 的成员函数模板。 +
+
仅当 `Hash::is++_++transparent` 与 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K++>++` 重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 类型调用，且 `Pred` 为透明谓词。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

==== count
```c++

size_type        count(const key_type& k) const;
template<class K>
  size_type      count(const K& k) const;

```

[horizontal]
返回;; 返回键等价于 `k` 的元素数量。
注意;; 仅当 `Hash::is++_++transparent` 与 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K++>++` 重载才会参与重载决议。标准库假设 `Hash` 可同时被 `K` 与 `Key` 类型调用，且 `Pred` 为透明的。这支持异构查找，该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

==== 包含
```c++

bool             contains(const key_type& k) const;
template<class K>
  bool           contains(const K& k) const;

```

[horizontal]
返回;; 返回一个布尔值，来表示容器中是否存在键等于 `key` 的元素
注意;; 仅当 `Hash::is++_++transparent` 与 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K++>++` 重载才会参与重载决议。标准库假设 `Hash` 可同时被 `K` 与 `Key` 类型调用，且 `Pred` 为透明的。这支持异构查找，该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

==== equal++_++range
```c++

std::pair<iterator, iterator>               equal_range(const key_type& k);
std::pair<const_iterator, const_iterator>   equal_range(const key_type& k) const;
template<class K>
  std::pair<iterator, iterator>             equal_range(const K& k);
template<class K>
  std::pair<const_iterator, const_iterator> equal_range(const K& k) const;

```

[horizontal]
返回;; 返回包含所有键等价于 `k`的元素的范围。若容器中不存在此类元素，则返回 `std::make++_++pair(b.end(), b.end())` 。
注意;; 仅当 `Hash::is++_++transparent` 与 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K++>++` 重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 类型调用，且 `Pred` 为透明谓词。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

==== operator++[]++
```c++

mapped_type& operator[](const key_type& k); mapped_type& operator[](key_type&& k); template<class K> mapped_type& operator[](K&& k);

```

[horizontal]
效果;; 若容器中尚不存键等价于 `k` 的元素，则插入值 `std;;pair++<++key++_++type const, mapped++_++type++>++(k, mapped++_++type())` 。
返回;; 返回一个引用，该引用指向容器中已存在的键等于 `k` 的元素 `x` 的 `x.second` 成员；若元素不存在，则指向新插入元素的该成员。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
指向元素的指针和引用永远不会失效。 +
+
仅当 `Hash::is++_++transparent` 与 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K++>++` 重载才会参与重载决议。标准库假设 `Hash` 可同时被 `K` 与 `Key` 类型调用，且 `Pred` 为透明的。这支持异构查找，该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

==== at
```c++

mapped_type& at(const key_type& k); const mapped_type& at(const key_type& k) const; template<class K> mapped_type& at(const K& k); template<class K> const mapped_type& at(const K& k) const;

```

[horizontal]
返回;; 返回一个引用，该引用指向键等价于 `k` 的（唯一）元素 `x` 的 `x.second` 成员。
抛出;; 如果不存在这样的元素，则抛出类型为 `std::out++_++of++_++range` 的异常对象。
注意;; 仅当 `Hash::is++_++transparent` 与 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K++>++` 重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 类型调用，且 `Pred` 为透明谓词。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

=== 桶接口

==== bucket++_++count
```c++

size_type bucket_count() const noexcept;

```

[horizontal]
返回;; 桶的数量。

---

==== max++_++bucket++_++count
```c++

size_type max_bucket_count() const noexcept;

```

[horizontal]
返回;; 桶数量的上限。

---

==== 桶大小
```c++

size_type bucket_size(size_type n) const;

```

[horizontal]
要求;; `n ++<++ bucket++_++count()`
返回;; 返回桶 `n` 中的元素数量。

---

==== 桶
```c++

size_type bucket(const key_type& k) const; template<class K> size_type bucket(const K& k) const;

```

[horizontal]
返回;; 返回键为 `k` 的元素所在桶的索引。
后置条件;; 返回值应小于 `bucket++_++count()` 。
注意;; 仅当 `Hash::is++_++transparent` 与 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K++>++` 重载才会参与重载决议。标准库假设 `Hash` 可同时被 `K` 与 `Key` 类型调用，且 `Pred` 为透明的。这支持异构查找，该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

==== begin

```c++

local_iterator begin(size_type n); const_local_iterator begin(size_type n) const;

```

[horizontal]
要求;; `n` 的取值范围应为 `++[++0, bucket++_++count())` 。
返回;; 返回指向索引为 `n` 的桶中第一个元素的局部迭代器。

---

==== end
```c++

local_iterator end(size_type n); const_local_iterator end(size_type n) const;

```

[horizontal]
要求;; `n` 的取值范围应为 `++[++0, bucket++_++count())` 。
返回;; 返回指向索引为 `n` 的桶中“末尾之后”元素的局部迭代器。

---

==== cbegin
```c++

const_local_iterator cbegin(size_type n) const;

```

[horizontal]
要求;; `n` 的取值范围应为 `++[++0, bucket++_++count())` 。
返回;; 返回指向索引为 `n` 的桶中第一个元素的常量局部迭代器。

---

==== cend
```c++

const_local_iterator cend(size_type n) const;

```

[horizontal]
要求;; `n` 的取值范围应为 `++[++0, bucket++_++count())` 。
返回;; 返回指向索引为 `n` 的桶中“末尾之后”元素的常量局部迭代器。

---

=== 哈希策略

==== 负载因子
```c++

float load_factor() const noexcept;

```

[horizontal]
返回;; 返回每个桶的平均元素数量。

---

==== max++_++load++_++factor（最大负载因子）

```c++

float max_load_factor() const noexcept;

```

[horizontal]
返回;; 返回当前的最大负载因子。

---

==== 设置最大负载因子
```c++

void max_load_factor(float z);

```

[horizontal]
效果;; 使用 `z` 作为提示来更改容器的最大负载因子。

---


==== 重哈希
```c++

void rehash(size_type n);

```

改变桶的数量，使其至少为 `n` 个，并确保负载因子小于或等于最大负载因子。此操作将根据情况增加或减少容器关联的 `bucket++_++count()` 。

当 `size() == 0` 时， `rehash(0)` 将释放底层桶数组。

使迭代器失效，并改变元素顺序。指向元素的指针和引用不会失效。

[horizontal]
抛出;; 若抛出异常（除非异常由容器的哈希函数或比较函数抛出），则该函数不产生任何效果。

---

==== 保留
```c++

void reserve(size_type n);

```

等价于 `a.rehash(ceil(n / a.max++_++load++_++factor()))` ，若 `n ++>++ 0` 且 `a.max++_++load++_++factor() == std::numeric++_++limits++<++float++>++::infinity()` ，则等价于 `a.rehash(1)` 。

与 `rehash` 类似，此函数可用于增加或减少容器中的桶数量。

使迭代器失效，并改变元素顺序。指向元素的指针和引用不会失效。

[horizontal]
抛出;; 若抛出异常（除非异常由容器的哈希函数或比较函数抛出），则该函数不产生任何效果。

=== 推导指引
如果以下任何一条件为真，则推导指引将不参与重载决议：

  - 该推导指引包含 `InputIterator` 模板参数，且为此参数推导出的类型不符合输入迭代器的要求。
  - 该推导指引包含 `Allocator` 模板参数，且为该参数推导出的类型不符合分配器要求。
  - 该推导指引包含 `Hash` 模板参数，且为该参数推导出的类型为整型或符合分配器要求。
  - 该推导指引包含 `Pred` 模板参数，且为该参数推导出的类型符合分配器要求。

推导指引中的 `size++_++type` 参数类型，指向由该推导指引所推导容器类型的 `size++_++type` 成员类型。其默认值与所选构造函数的默认值一致。

==== _iter-value-type_
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-value-type__ =
    typename std::iterator_traits<InputIterator>::value_type; // exposition only
-----

==== __iter-key-type__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-key-type__ = std;;remove_const_t<
    std;;tuple_element_t<0, xref:#unordered_map_iter_value_type[__iter-value-type__]<InputIterator>>>; // exposition only
-----

==== __iter-mapped-type__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-mapped-type__ =
    std;;tuple_element_t<1, xref:#unordered_map_iter_value_type[__iter-value-type__]<InputIterator>>;  // exposition only
-----

==== __iter-to-alloc-type__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-to-alloc-type__ = std;;pair<
    std;;add_const_t<std;;tuple_element_t<0, xref:#unordered_map_iter_value_type[__iter-value-type__]<InputIterator>>>,
    std;;tuple_element_t<1, xref:#unordered_map_iter_value_type[__iter-value-type__]<InputIterator>>>; // exposition only
-----

=== 相等性比较

==== operator==
```c++

template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator==(const unordered_map<Key, T, Hash, Pred, Alloc>& x,
                  const unordered_map<Key, T, Hash, Pred, Alloc>& y);

```

若 `x.size() == y.size()` 且对于 `x` 中的每个元素， `y` 中均存在一个具有相同键和相等值（使用 `operator==` 比较值类型）的元素，则返回 `true` 。

[horizontal]
注意;; 如果两个容器的相等性谓词不等价，则行为未定义。

---

==== operator!=
```c++

template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator!=(const unordered_map<Key, T, Hash, Pred, Alloc>& x,
                  const unordered_map<Key, T, Hash, Pred, Alloc>& y);

```

如果 `x.size() == y.size()` ，且对于 `x` 中的每个元素，在 `y` 中均存在一个具有相同键且值相等的元素（使用 `operator==` 比较值类型），则返回 `false` 。

[horizontal]
注意;; 如果两个容器的相等性谓词不等价，则行为未定义。

=== 交换
```c++

template<class Key, class T, class Hash, class Pred, class Alloc>
  void swap(unordered_map<Key, T, Hash, Pred, Alloc>& x,
            unordered_map<Key, T, Hash, Pred, Alloc>& y)
    noexcept(noexcept(x.swap(y)));

```

交换 `x` 与 `y` 的内容。

如果声明了 `Allocator::propagate++_++on++_++container++_++swap` 且 `Allocator::propagate++_++on++_++container++_++swap::value` 为 `true` ，则交换容器的分配器。则，在分配器不相等的情况下进行交换将导致未定义行为。

[horizontal]
效果;; `x.swap(y)`
抛出;; 除非异常由 `key++_++equal` 或 `hasher` 的复制构造函数或复制赋值运算符抛出，否则本操作不会抛出异常。
注意;; 此处的异常规范与 C{plus}{plus}11 标准不完全一致，因为相等性谓词和哈希函数是通过其复制构造函数完成交换的。

---

=== erase++_++if
```c++

template<class K, class T, class H, class P, class A, class Predicate>
  typename unordered_map<K, T, H, P, A>::size_type
    erase_if(unordered_map<K, T, H, P, A>& c, Predicate pred);

```

遍历容器 `c` ，并删除所有使提供的谓词返回 `true` 的元素。

[horizontal]
返回;; 被擦除的元素数量。
注意;; 等价于： +
+
```c++

auto original_size = c.size();
for (auto i = c.begin(), last = c.end(); i != last; ) {
  if (pred(*i)) {
    i = c.erase(i);
  } else {
    ++i;
  }
}
return original_size - c.size();

```
+
请注意，传递给 `pred` 的引用是非常量的。

=== 序列化

`unordered++_++map` 可通过本组件库提供的 API，借助 link:../../../../../serialization/index.html[Boost.Serialization] 进行归档/检索。支持常规归档与 XML 归档两种格式。

==== 将 unordered++_++map 保存到归档

将 `unordered++_++map` 容器 `x` 的所有元素保存到归档（XML 归档） `ar` 中。

[horizontal]
要求;; `std::remove++_++const++<++key++_++type++>++::type` 和 `std::remove++_++const++<++mapped++_++type++>++::type` 必须满足可序列化要求（XML 可序列化），且需要支持 Boost.Serialization 的 `save++_++construct++_++data` / `load++_++construct++_++data` 协议（该协议自动支持 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求）。

---

==== 从归档加载 unordered++_++map

删除 `unordered++_++map` 容器 `x` 的所有现有元素，并从归档（XML 归档） `ar` 中插入原始 `unordered++_++map` `other` 的元素副本，这些副本是从 `ar` 读取的存储中恢复的。

[horizontal]
要求;; `value++_++type` 必须能够从 `(std::remove++_++const++<++key++_++type++>++::type&&, std::remove++_++const++<++mapped++_++type++>++::type&&)` 进行 https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原地构造] ，且 `x.key++_++equal()` 需要在功能上等价于 `other.key++_++equal()` 。
注意;; 若归档文件是使用 Boost 1.84 之前的版本保存的，则必须全局定义配置宏 `BOOST++_++UNORDERED++_++ENABLE++_++SERIALIZATION++_++COMPATIBILITY++_++V0` 才能成功执行此操作；否则将抛出异常。

---

==== 将迭代器/常量迭代器保存到归档

将 `iterator` （ `const++_++iterator` ）常量迭代器 `it` 的位置信息保存到归档（XML 归档） `ar` 中。 `it` 可以是 `end()` 迭代器。

[horizontal]
要求;; `it` 指向的 `unordered++_++map` `x` 必须先前已保存到 `ar` ，并且在保存 `x` 和保存 `it` 期间不得对 `x` 执行任何修改操作。

---

==== 从归档加载迭代器/常量迭代器

使 `iterator` （ `const++_++iterator` ） `it` 指向原始 `iterator` （ `const++_++iterator` ）所恢复的位置。该原始迭代器已被保存到由归档（XML 归档） `ar` 读取的存储中。

[horizontal]
要求;; 如果 `x` 是 `it` 所指向的 `unordered++_++map` 容器，则在加载 `x` 和加载 `it` 期间不得对 `x` 执行任何修改操作。
