[[header]]

[[content]]
[[unordered_set]]
== 类模板 unordered_set

`boost::unordered_set` — 一种用于存储唯一值的无序关联容器。

[[unordered_set_synopsis]]
=== 概要

....
// #include <boost/unordered/unordered_set.hpp>

namespace boost {
namespace unordered {

  template<class Key,
           class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<Key>>
  class unordered_set {
  public:
    // 类型定义
    using key_type             = Key;
    using value_type           = Key;
    using hasher               = Hash;
    using key_equal            = Pred;
    using allocator_type       = Allocator;
    using pointer              = typename std::allocator_traits<Allocator>::pointer;
    using const_pointer        = typename std::allocator_traits<Allocator>::const_pointer;
    using reference            = value_type&;
    using const_reference      = const value_type&;
    using size_type            = std::size_t;
    using difference_type      = std::ptrdiff_t;

    using iterator             = 由实现定义;
    using const_iterator       = 由实现定义;
    using local_iterator       = 由实现定义;
    using const_local_iterator = 由实现定义;
    using node_type            = 由实现定义;
    using insert_return_type   = 由实现定义;

    // 构造/复制/销毁
    unordered_set();
    explicit unordered_set(size_type n,
                           const hasher& hf = hasher(),
                           const key_equal& eql = key_equal(),
                           const allocator_type& a = allocator_type());
    template<class InputIterator>
      unordered_set(InputIterator f, InputIterator l,
                    size_type n = 由实现定义,
                    const hasher& hf = hasher(),
                    const key_equal& eql = key_equal(),
                    const allocator_type& a = allocator_type());
    unordered_set(const unordered_set& other);
    unordered_set(unordered_set&& other);
    template<class InputIterator>
      unordered_set(InputIterator f, InputIterator l, const allocator_type& a);
    explicit unordered_set(const Allocator& a);
    unordered_set(const unordered_set& other, const Allocator& a);
    unordered_set(unordered_set&& other, const Allocator& a);
    unordered_set(std::initializer_list<value_type> il,
                  size_type n = 由实现定义,
                  const hasher& hf = hasher(),
                  const key_equal& eql = key_equal(),
                  const allocator_type& a = allocator_type());
    unordered_set(size_type n, const allocator_type& a);
    unordered_set(size_type n, const hasher& hf, const allocator_type& a);
    template<class InputIterator>
      unordered_set(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
    template<class InputIterator>
      unordered_set(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                    const allocator_type& a);
    unordered_set(std::initializer_list<value_type> il, const allocator_type& a);
    unordered_set(std::initializer_list<value_type> il, size_type n, const allocator_type& a);
    unordered_set(std::initializer_list<value_type> il, size_type n, const hasher& hf,
                  const allocator_type& a);
    ~unordered_set();
    unordered_set& operator=(const unordered_set& other);
    unordered_set& operator=(unordered_set&& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
               boost::is_nothrow_move_assignable_v<Hash> &&
               boost::is_nothrow_move_assignable_v<Pred>);
    unordered_set& operator=(std::initializer_list<value_type> il);
    allocator_type get_allocator() const noexcept;

    // 迭代器
    iterator       begin() noexcept;
    const_iterator begin() const noexcept;
    iterator       end() noexcept;
    const_iterator end() const noexcept;
    const_iterator cbegin() const noexcept;
    const_iterator cend() const noexcept;

    // 容量
    [[nodiscard]] bool empty() const noexcept;
    size_type size() const noexcept;
    size_type max_size() const noexcept;

    // 修改器
    template<class... Args> std::pair<iterator, bool> emplace(Args&&... args);
    template<class... Args> iterator emplace_hint(const_iterator position, Args&&... args);
    std::pair<iterator, bool> insert(const value_type& obj);
    std::pair<iterator, bool> insert(value_type&& obj);
    template<class K> std::pair<iterator, bool> insert(K&& k);
    iterator insert(const_iterator hint, const value_type& obj);
    iterator insert(const_iterator hint, value_type&& obj);
    template<class K> iterator insert(const_iterator hint, K&& k);
    template<class InputIterator> void insert(InputIterator first, InputIterator last);
    void insert(std::initializer_list<value_type>);

    node_type extract(const_iterator position);
    node_type extract(const key_type& k);
    template<class K> node_type extract(K&& k);
    insert_return_type insert(node_type&& nh);
    iterator           insert(const_iterator hint, node_type&& nh);

    iterator  erase(iterator position);
    iterator  erase(const_iterator position);
    size_type erase(const key_type& k);
    template<class K> size_type erase(K&& k);
    iterator  erase(const_iterator first, const_iterator last);
    void      quick_erase(const_iterator position);
    void      erase_return_void(const_iterator position);
    void      swap(unordered_set& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
               boost::is_nothrow_swappable_v<Hash> &&
               boost::is_nothrow_swappable_v<Pred>);
    void      clear() noexcept;

    template<class H2, class P2>
      void merge(unordered_set<Key, H2, P2, Allocator>& source);
    template<class H2, class P2>
      void merge(unordered_set<Key, H2, P2, Allocator>&& source);
    template<class H2, class P2>
      void merge(unordered_multiset<Key, H2, P2, Allocator>& source);
    template<class H2, class P2>
      void merge(unordered_multiset<Key, H2, P2, Allocator>&& source);

    // 观察器
    hasher hash_function() const;
    key_equal key_eq() const;

    // 集合操作
    iterator         find(const key_type& k);
    const_iterator   find(const key_type& k) const;
    template<class K>
      iterator       find(const K& k);
    template<class K>
      const_iterator find(const K& k) const;
    template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
      iterator       find(CompatibleKey const& k, CompatibleHash const& hash,
                          CompatiblePredicate const& eq);
    template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
      const_iterator find(CompatibleKey const& k, CompatibleHash const& hash,
                          CompatiblePredicate const& eq) const;
    size_type        count(const key_type& k) const;
    template<class K>
      size_type      count(const K& k) const;
    bool             contains(const key_type& k) const;
    template<class K>
      bool           contains(const K& k) const;
    std::pair<iterator, iterator>               equal_range(const key_type& k);
    std::pair<const_iterator, const_iterator>   equal_range(const key_type& k) const;
    template<class K>
      std::pair<iterator, iterator>             equal_range(const K& k);
    template<class K>
      std::pair<const_iterator, const_iterator> equal_range(const K& k) const;

    // 桶接口
    size_type bucket_count() const noexcept;
    size_type max_bucket_count() const noexcept;
    size_type bucket_size(size_type n) const;
    size_type bucket(const key_type& k) const;
    template<class K> size_type bucket(const K& k) const;
    local_iterator begin(size_type n);
    const_local_iterator begin(size_type n) const;
    local_iterator end(size_type n);
    const_local_iterator end(size_type n) const;
    const_local_iterator cbegin(size_type n) const;
    const_local_iterator cend(size_type n) const;

    // 哈希策略
    float load_factor() const noexcept;
    float max_load_factor() const noexcept;
    void max_load_factor(float z);
    void rehash(size_type n);
    void reserve(size_type n);
  };

  // 推导指引
  template<class InputIterator,
           class Hash = boost::hash<迭代器值类型<InputIterator>>,
           class Pred = std::equal_to<迭代器值类型<InputIterator>>,
           class Allocator = std::allocator<迭代器值类型<InputIterator>>>
    unordered_set(InputIterator, InputIterator, typename 见下::size_type = 见下,
                  Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> unordered_set<迭代器值类型<InputIterator>, Hash, Pred, Allocator>;

  template<class T, class Hash = boost::hash<T>, class Pred = std::equal_to<T>,
           class Allocator = std::allocator<T>>
    unordered_set(std::initializer_list<T>, typename 见下::size_type = 见下,
                  Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> unordered_set<T, Hash, Pred, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_set(InputIterator, InputIterator, typename 见下::size_type, Allocator)
      -> unordered_set<迭代器值类型<InputIterator>,
                       boost::hash<迭代器值类型<InputIterator>>,
                       std::equal_to<迭代器值类型<InputIterator>>, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_set(InputIterator, InputIterator, Allocator)
      -> unordered_set<迭代器值类型<InputIterator>,
                       boost::hash<迭代器值类型<InputIterator>>,
                       std::equal_to<迭代器值类型<InputIterator>>, Allocator>;

  template<class InputIterator, class Hash, class Allocator>
    unordered_set(InputIterator, InputIterator, typename 见下::size_type, Hash, Allocator)
      -> unordered_set<迭代器值类型<InputIterator>, Hash,
                       std::equal_to<迭代器值类型<InputIterator>>, Allocator>;

  template<class T, class Allocator>
    unordered_set(std::initializer_list<T>, typename 见下::size_type, Allocator)
      -> unordered_set<T, boost::hash<T>, std::equal_to<T>, Allocator>;

  template<class T, class Allocator>
    unordered_set(std::initializer_list<T>, Allocator)
      -> unordered_set<T, boost::hash<T>, std::equal_to<T>, Allocator>;

  template<class T, class Hash, class Allocator>
    unordered_set(std::initializer_list<T>, typename 见下::size_type, Hash, Allocator)
      -> unordered_set<T, Hash, std::equal_to<T>, Allocator>;

} // namespace unordered
} // namespace boost
....

'''''

[[unordered_set_description]]
=== 描述

*模板参数*

[width="100%",cols="50%,50%",]
|===
|_键_ |`Key`
必须可从容器中https://en.cppreference.com/w/cpp/named_req/Erasable[擦除]
（即 `allocator_traits` 可销毁该类型对象）。

|_Hash_ |一种作为 ``Key``
类型哈希函数的一元函数对象类型。该函数对象接受一个 ``Key``
类型的参数，并返回 ``std::size_t`` 类型的值。

|_Pred_ |二元函数对象，用于实现 `Key`
类型值的等价关系。该函数对象接受两个`Key`
类型参数，并返回一个布尔类型的值。

|_Allocator_
|一个分配器，其值类型与容器的值类型相同。支持使用https://en.cppreference.com/w/cpp/named_req/Allocator#Fancy_pointers[花式指针]的分配器。
|===

元素被组织到多个桶中。具有相同哈希码的键存储在同一个桶内。

桶的数量可通过调用 insert 操作自动增加，也可通过调用 rehash
方法进行调整。

[[unordered_set_configuration_macros]]
=== 配置宏

[[unordered_set_boost_unordered_enable_serialization_compatibility_v0]]
==== `BOOST_UNORDERED_ENABLE_SERIALIZATION_COMPATIBILITY_V0`

全局定义此宏可支持加载 Boost 1.84 之前版本保存至 Boost.Serialization
归档文件的 `unordered_set`数据。

[[unordered_set_typedefs]]
=== 类型定义

[source,highlight]
----
typedef 由实现定义 iterator;
----

一个常量迭代器，其值类型为 `value_type`。

迭代器类别至少为前向迭代器。

可转换为 `const_iterator`。

'''''

[source,highlight]
----
typedef 由实现定义 const_iterator;
----

一个常量迭代器，其值类型为 `value_type`。

迭代器类别至少为前向迭代器。

'''''

[source,highlight]
----
typedef 由实现定义 local_iterator;
----

一个迭代器，其值类型、差类型、指针和引用类型均与 iterator 相同。

`local_iterator` 对象，可用于遍历单个桶内的元素。

'''''

[source,highlight]
----
typedef 由实现定义 const_local_iterator;
----

一个常量迭代器，其值类型、差类型、指针和引用类型均与 const_iterator
相同。

const_local_iterator 对象，可用于遍历单个桶内的元素。

'''''

[source,highlight]
----
typedef 由实现定义 node_type;
----

一个用于保存提取的容器元素的类，建模
https://en.cppreference.com/w/cpp/container/node_handle[NodeHandle]。

'''''

[source,highlight]
----
typedef 由实现定义 insert_return_type;
----

内部类模板的特化：

[source,highlight]
----
template<class Iterator, class NodeType>
struct insert_return_type // 名称仅为说明
{
  Iterator position;
  bool     inserted;
  NodeType node;
};
----

其中 `Iterator` = `iterator`，`NodeType` = `node_type`。

'''''

[[unordered_set_constructors]]
=== 构造函数

[[unordered_set_default_constructor]]
==== 默认构造函数

[source,highlight]
----
unordered_set();
----

构造一个空容器，使用 `hasher()` 作为哈希函数，`key_equal()`
作为键相等性谓词，`allocator_type()` 作为分配器，并设置最大负载因子为
`1.0`。

[cols=",",]
|===
|后置条件： |`size() == 0`

|要求： |若使用默认参数，则 `hasher`、`key_equal` 和 `allocator_type`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[unordered_set_bucket_count_constructor]]
==== 桶数量构造函数

[source,highlight]
----
explicit unordered_set(size_type n,
                       const hasher& hf = hasher(),
                       const key_equal& eql = key_equal(),
                       const allocator_type& a = allocator_type());
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数，`eql`
作为键相等性谓词，`a` 作为分配器，并设置最大负载因子为 `1.0`。

[cols=",",]
|===
|后置条件： |`size() == 0`

|要求： |若使用默认参数，则 `hasher`、`key_equal` 和 `allocator_type`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[unordered_set_iterator_range_constructor]]
==== 迭代器范围构造函数

[source,highlight]
----
template<class InputIterator>
  unordered_set(InputIterator f, InputIterator l,
                size_type n = 由实现定义,
                const hasher& hf = hasher(),
                const key_equal& eql = key_equal(),
                const allocator_type& a = allocator_type());
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数，`eql`
作为键相等性谓词，`a` 作为分配器，并设置最大负载因子为 `1.0`，随后将区间
`[f, l)` 中的元素插入该容器。

[cols=",",]
|===
|要求： |若使用默认参数，则 `hasher`、`key_equal` 和 `allocator_type`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[unordered_set_copy_constructor]]
==== 复制构造函数

[source,highlight]
----
unordered_set(const unordered_set& other);
----

复制构造函数。复制容器内的元素、哈希函数、谓词、最大负载因子以及分配器。

如果 `Allocator::select_on_container_copy_construction`
方法存在且签名正确，则将基于其返回结果构造分配器。

[cols=",",]
|===
|要求： |`value_type` 可复制构造
|===

'''''

[[unordered_set_move_constructor]]
==== 移动构造函数

[source,highlight]
----
unordered_set(unordered_set&& other);
----

移动构造函数。

[cols=",",]
|===
|备注： |此函数通过 Boost.Move 实现。
|要求： |`value_type` 可移动构造。
|===

'''''

[[unordered_set_iterator_range_constructor_with_allocator]]
==== 带分配器的迭代器范围构造函数

[source,highlight]
----
template<class InputIterator>
  unordered_set(InputIterator f, InputIterator l, const allocator_type& a);
----

使用 `a`
作为分配器构造一个空容器，使用默认的哈希函数和键相等性谓词，并设置最大负载因子为
`1.0`，随后将区间 `[f, l)` 中的元素插入该容器。

[cols=",",]
|===
|要求： |`hasher`、`key_equal`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[unordered_set_allocator_constructor]]
==== 分配器构造函数

[source,highlight]
----
explicit unordered_set(const Allocator& a);
----

使用分配器 `a` 构造一个空容器。

'''''

[[unordered_set_copy_constructor_with_allocator]]
==== 带分配器的复制构造函数

[source,highlight]
----
unordered_set(const unordered_set& other, const Allocator& a);
----

构造一个容器，复制 `other`
包含的元素、哈希函数、谓词及最大负载因子，但使用分配器 `a`。

'''''

[[unordered_set_move_constructor_with_allocator]]
==== 带分配器的移动构造函数

[source,highlight]
----
unordered_set(unordered_set&& other, const Allocator& a);
----

构造一个容器，移动 `other`
包含的元素，并获取其哈希函数、谓词和最大负载因子，但使用分配器 `a`。

[cols=",",]
|===
|备注： |此函数通过 Boost.Move 实现。
|要求： |`value_type` 需满足可移动插入要求。
|===

'''''

[[unordered_set_initializer_list_constructor]]
==== 初始化列表构造函数

[source,highlight]
----
unordered_set(std::initializer_list<value_type> il,
              size_type n = 由实现定义,
              const hasher& hf = hasher(),
              const key_equal& eql = key_equal(),
              const allocator_type& a = allocator_type());
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数，`eql`
作为键相等性谓词，`a` 作为分配器，并设置最大负载因子为 `1.0`，随后将
`il` 中的元素插入该容器。

[cols=",",]
|===
|要求： |若使用默认参数，则 `hasher`、`key_equal` 和 `allocator_type`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[unordered_set_bucket_count_constructor_with_allocator]]
==== 带分配器的桶数量构造函数

[source,highlight]
----
unordered_set(size_type n, const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf`
作为哈希函数（应为默认哈希函数）、默认的键相等性谓词，`a`
作为分配器，并设置最大负载因子为 `1.0`。

[cols=",",]
|===
|后置条件： |`size() == 0`

|要求： |`hasher` 与 `key_equal`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[unordered_set_bucket_count_constructor_with_hasher_and_allocator]]
==== 带哈希函数与分配器的桶数量构造函数

[source,highlight]
----
unordered_set(size_type n, const hasher& hf, const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf`
作为哈希函数，默认的键相等性谓词，`a` 作为分配器，并设置最大负载因子为
`1.0`。

[cols=",",]
|===
|后置条件： |`size() == 0`

|要求： |`key_equal`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[unordered_set_iterator_range_constructor_with_bucket_count_and_allocator]]
==== 带桶数量和分配器的迭代器范围构造函数

[source,highlight]
----
template<class InputIterator>
  unordered_set(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `a`
作为分配器，默认的哈希函数和键相等性谓词，并设置最大负载因子为
`1.0`，随后将区间 `[f, l)` 中的元素插入该容器。

[cols=",",]
|===
|要求： |`hasher`、`key_equal`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[unordered_set_iterator_range_constructor_with_bucket_count_and_hasher]]
==== 带桶数量和哈希器的迭代器范围构造函数

[source,highlight]
----
template<class InputIterator>
  unordered_set(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数，`a`
作为分配器，默认的键相等性谓词，并设置最大负载因子为 `1.0`，随后将区间
`[f, l)` 中的元素插入该容器。

[cols=",",]
|===
|要求： |`key_equal`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[unordered_set_initializer_list_constructor_with_allocator]]
==== 带分配器的初始化列表构造函数

[source,highlight]
----
unordered_set(std::initializer_list<value_type> il, const allocator_type& a);
----

使用 `a` 作为分配器构造一个空容器，设置最大负载因子为 1.0，并将 `il`
中的元素插入其中。

[cols=",",]
|===
|要求： |`hasher` 与 `key_equal`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[unordered_set_initializer_list_constructor_with_bucket_count_and_allocator]]
==== 带桶数量和分配器的初始化列表构造函数

[source,highlight]
----
unordered_set(std::initializer_list<value_type> il, size_type n, const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `a`
作为分配器，并设置最大负载因子为 1.0，随后将 `il` 中的元素插入该容器。

[cols=",",]
|===
|要求： |`hasher` 与 `key_equal`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[unordered_set_initializer_list_constructor_with_bucket_count_and_hasher_and_allocator]]
==== 带桶数量、哈希函数与分配器的初始化列表构造函数

[source,highlight]
----
unordered_set(std::initializer_list<value_type> il, size_type n, const hasher& hf,
              const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数，`a`
作为分配器，设置最大负载因子为 1.0，并将 `il` 中的元素插入其中。

[cols=",",]
|===
|要求： |`key_equal`
需满足https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[unordered_set_destructor]]
=== 析构函数

[source,highlight]
----
~unordered_set();
----

[cols=",",]
|===
|备注： |析构函数会作用于每个元素，并释放所有内存。
|===

'''''

[[unordered_set_assignment]]
=== 赋值

[[unordered_set_copy_assignment]]
==== 复制赋值

[source,highlight]
----
unordered_set& operator=(const unordered_set& other);
----

赋值运算符。该操作会复制容器内的元素、哈希函数、谓词及最大负载因子，但不会复制分配器。

如果 `Alloc::propagate_on_container_copy_assignment` 存在且
`Alloc::propagate_on_container_copy_assignment::value` 为
`true`，则覆盖分配器；否则使用现有分配器创建所复制的元素。

[cols=",",]
|===
|要求： |`value_type` 可复制构造
|===

'''''

[[unordered_set_move_assignment]]
==== 移动赋值

[source,highlight]
----
unordered_set& operator=(unordered_set&& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
           boost::is_nothrow_move_assignable_v<Hash> &&
           boost::is_nothrow_move_assignable_v<Pred>);
----

移动赋值运算符。

如果 `Alloc::propagate_on_container_move_assignment` 存在且
`Alloc::propagate_on_container_move_assignment::value` 为
`true`，则覆盖分配器；否则使用现有分配器创建被移动的元素。

[cols=",",]
|===
|要求： |`value_type` 需满足可移动构造要求。
|===

'''''

[[unordered_set_initializer_list_assignment]]
==== 初始化列表赋值

[source,highlight]
----
unordered_set& operator=(std::initializer_list<value_type> il);
----

通过初始化列表中的值进行赋值操作。所有现有元素要么被新元素覆盖，要么被销毁。

[cols=",",]
|===
|要求： |`value_type`
必须满足https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入]至容器以及https://en.cppreference.com/w/cpp/named_req/CopyAssignable[可复制赋值]的要求。
|===

'''''

[[unordered_set_iterators]]
=== 迭代器

[[unordered_set_begin]]
==== begin

[source,highlight]
----
iterator       begin() noexcept;
const_iterator begin() const noexcept;
----

[cols=",",]
|===
|返回值：
|返回指向容器首元素的迭代器；若容器为空，则返回容器的结束迭代器。
|===

'''''

[[unordered_set_end]]
==== end

[source,highlight]
----
iterator       end() noexcept;
const_iterator end() const noexcept;
----

[cols=",",]
|===
|返回值： |返回指向容器结束位置的迭代器。
|===

'''''

[[unordered_set_cbegin]]
==== cbegin

[source,highlight]
----
const_iterator cbegin() const noexcept;
----

[cols=",",]
|===
|返回值：
|`const_iterator`为一种返回指向容器第一个元素的常量迭代器，如果容器为空，则返回容器的结束迭代器。
|===

'''''

[[unordered_set_cend]]
==== cend

[source,highlight]
----
const_iterator cend() const noexcept;
----

[cols=",",]
|===
|返回值： |返回一个指向容器结束位置的 `const_iterator` 常量迭代器。
|===

'''''

[[unordered_set_size_and_capacity]]
=== 大小与容量

[[unordered_set_empty]]
==== empty

[source,highlight]
----
[[nodiscard]] bool empty() const noexcept;
----

[cols=",",]
|===
|返回值： |`size() == 0`
|===

'''''

[[unordered_set_size]]
==== 大小

[source,highlight]
----
size_type size() const noexcept;
----

[cols=",",]
|===
|返回值： |`std::distance(begin(), end())`
|===

'''''

[[unordered_set_max_size]]
==== max_size

[source,highlight]
----
size_type max_size() const noexcept;
----

[cols=",",]
|===
|返回值： |容器最大可能的 `size()`值。
|===

'''''

[[unordered_set_modifiers]]
=== 修改器

[[unordered_set_emplace]]
==== emplace

[source,highlight]
----
template<class... Args> std::pair<iterator, bool> emplace(Args&&... args);
----

当且仅当容器中不存在等价元素时，插入一个由参数 `args` 构造的对象。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type` 必须满足从 `args`
参数https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原位构造]到
`X` 容器的要求。

|返回值： a|
若插入成功，则返回类型的布尔分量为 true。 +

若插入成功，则迭代器指向新插入的元素；否则，指向具有等价值的元素。

|抛出： |若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。

|备注： a|
可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +

指向元素的指针和引用永远不会失效。

|===

'''''

[[unordered_set_emplace_hint]]
==== emplace_hint

[source,highlight]
----
template<class... Args> iterator emplace_hint(const_iterator position, Args&&... args);
----

当且仅当容器中不存在等价元素时，插入一个由参数 `args` 构造的对象。

`position` 是插入元素位置的建议。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type` 必须满足从 `args`
参数https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原位构造]到
`X` 容器的要求。

|返回值：
|若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。

|抛出： |若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。

|备注： a|
C++标准对提示参数含义的规定相当笼统。在实际使用中唯一有效的方式（也是Boost.Unordered唯一支持的用法）是指向具有相同键的现有元素。 +

可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +

指向元素的指针和引用永远不会失效。

|===

'''''

[[unordered_set_copy_insert]]
==== 复制插入

[source,highlight]
----
std::pair<iterator, bool> insert(const value_type& obj);
----

当且仅当容器中不存在等价键时，将 `obj` 对象插入到容器中。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type`
必须满足https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入]要求。

|返回值： a|
若插入成功，则返回类型的布尔分量为 true。 +

若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。

|抛出： |若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。

|备注： a|
可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +

指向元素的指针和引用永远不会失效。

|===

'''''

[[unordered_set_move_insert]]
==== 移动插入

[source,highlight]
----
std::pair<iterator, bool> insert(value_type&& obj);
----

当且仅当容器中不存在等价键时，将 `obj` 对象插入到容器中。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type`
必须满足https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入]要求。

|返回值： a|
若插入成功，则返回类型的布尔分量为 true。 +

若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。

|抛出： |若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。

|备注： a|
可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +

指向元素的指针和引用永远不会失效。

|===

'''''

[[unordered_set_transparent_insert]]
==== 透明插入

[source,highlight]
----
template<class K> std::pair<iterator, bool> insert(K&& k);
----

当且仅当容器中不存在等价键的元素时，插入一个由 `std::forward<K>(k)`
构造的元素。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type` 必须满足从 `k`参数
https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原位构造]的要求。

|返回值： a|
若插入成功，则返回类型的布尔分量为 true。 +

若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。

|抛出： |若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。

|备注： a|
可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +

指向元素的指针和引用永远不会失效。 +

仅当 `Hash::is_transparent` 与 `Pred::is_transparent`
均为有效的成员类型，且 `iterator` 与 `const_iterator` 均不能从 `K`
类型隐式转换时，此重载才参与重载决议。标准库假定`Hash` 可同时被 `K` 和
`Key` 类型调用，且 `Pred` 是透明的。该机制支持异构查找，从而避免实例化
`Key` 类型的开销。

|===

'''''

[[unordered_set_copy_insert_with_hint]]
==== 带提示的复制插入

[source,highlight]
----
iterator insert(const_iterator hint, const value_type& obj);
----

当且仅当容器中不存在等价键时，将 `obj` 对象插入到容器中。

`hint` 是插入元素位置的建议。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type`
必须满足https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入]要求。

|返回值：
|若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。

|抛出： |若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。

|备注： a|
C++标准对提示参数含义的规定相当笼统。在实际使用中唯一有效的方式（也是Boost.Unordered唯一支持的用法）是指向具有相同键的现有元素。 +

可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +

指向元素的指针和引用永远不会失效。

|===

'''''

[[unordered_set_move_insert_with_hint]]
==== 带提示的移动插入

[source,highlight]
----
iterator insert(const_iterator hint, value_type&& obj);
----

当且仅当容器中不存在等价键时，将 `obj` 对象插入到容器中。

`hint` 是插入元素位置的建议。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type`
必须满足https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入]要求。

|返回值：
|若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。

|抛出： |若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。

|备注： a|
C++标准对提示参数含义的规定相当笼统。在实际使用中唯一有效的方式（也是Boost.Unordered唯一支持的用法）是指向具有相同键的现有元素。 +

可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +

指向元素的指针和引用永远不会失效。

|===

'''''

[[unordered_set_transparent_insert_with_hint]]
==== 带提示的透明插入

[source,highlight]
----
template<class K> iterator insert(const_iterator hint, K&& k);
----

当且仅当容器中不存在等价键的元素时，插入一个由 `std::forward<K>(k)`
构造的元素。

`hint` 是插入元素位置的建议。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type` 必须满足从 `k`参数
https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原位构造]的要求。

|返回值：
|若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。

|抛出： |若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。

|备注： a|
C++标准对提示参数含义的规定相当笼统。在实际使用中唯一有效的方式（也是Boost.Unordered唯一支持的用法）是指向具有相同键的现有元素。 +

可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +

指向元素的指针和引用永远不会失效。 +

仅当 `Hash::is_transparent` 与 `Pred::is_transparent`
均为有效的成员类型，且 `iterator` 与 `const_iterator` 均不能从 `K`
类型隐式转换时，此重载才参与重载决议。标准库假定`Hash` 可同时被 `K` 和
`Key` 类型调用，且 `Pred` 是透明的。该机制支持异构查找，从而避免实例化
`Key` 类型的开销。

|===

'''''

[[unordered_set_insert_iterator_range]]
==== 插入迭代器范围

[source,highlight]
----
template<class InputIterator> void insert(InputIterator first, InputIterator last);
----

将元素范围插入容器中。仅当容器中不存在等价键的元素时，才会插入相应元素。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type` 必须满足从 `*first`
参数https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原位构造]到容器
`X`的要求。

|抛出： |若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。

|备注： a|
可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +

指向元素的指针和引用永远不会失效。

|===

'''''

[[unordered_set_insert_initializer_list]]
==== 插入初始化列表

[source,highlight]
----
void insert(std::initializer_list<value_type>);
----

将元素范围插入容器中。仅当容器中不存在等价键的元素时，才会插入相应元素。

[width="100%",cols="50%,50%",]
|===
|要求： |`value_type`
必须满足https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入]到容器中的要求。

|抛出： |若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。

|备注： a|
可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +

指向元素的指针和引用永远不会失效。

|===

'''''

[[unordered_set_extract_by_iterator]]
==== 通过迭代器提取

[source,highlight]
----
node_type extract(const_iterator position);
----

移除由 `position` 指向的元素。

[cols=",",]
|===
|返回值： |返回拥有该元素的 `node_type`节点对象。

|备注： |在 C++17 标准中，通过此方法提取的节点可被插入到兼容的
`unordered_multiset` 中，但该特性暂未获得支持。
|===

'''''

[[unordered_set_extract_by_value]]
==== 通过键值提取元素

[source,highlight]
----
node_type extract(const key_type& k);
template<class K> node_type extract(K&& k);
----

移除键等价于 `k` 的元素。

[width="100%",cols="50%,50%",]
|===
|返回值： |如果找到，则返回拥有该元素的 `node_type`对象；否则返回空的
`node_type`对象。

|抛出： |仅当 `hasher` 或 `key_equal` 抛出异常时，本函数才会抛出异常。

|备注： a|
在 C++17 标准中，通过此方法提取的节点可被插入到兼容的
`unordered_multiset` 中，但该特性暂未获得支持。 +

仅当 `Hash::is_transparent` 与 `Pred::is_transparent`
均为有效的成员类型定义，且 `iterator` 与 `const_iterator` 均不能从 `K`
隐式转换时，此重载才参与重载决议。标准库假定 `Hash` 可同时被 `K` 与
`Key` 类型调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化
`Key` 类型的开销。

|===

'''''

[[unordered_set_insert_with_node_handle]]
==== 通过 `node_handle` 插入

[source,highlight]
----
insert_return_type insert(node_type&& nh);
----

若 `nh` 为空节点，则此操作不产生任何效果。

否则，当且仅当容器中不存在等价键的元素时，才会插入 `nh` 所拥有的元素。

[width="100%",cols="50%,50%",]
|===
|要求： |`nh` 必须是空节点，或其分配器 `nh.get_allocator()`
需与容器的分配器相等。

|返回值： a|
若 `nh` 为空节点，则返回一个 `insert_return_type`
对象，该类对象满足：`inserted` 为 `false`，`position` 等于 `end()`，且
`node` 为空。 +

否则，若容器中已存在等价键的元素，则返回一个
`insert_return_type`对象，该类对象满足：`inserted` 为
`false`，`position` 指向匹配的现有元素，且 `node` 包含来自 `nh`
的节点。 +

否则，如果插入成功，则返回一个
`insert_return_type`对象，该类对象满足：`inserted` 为 `true`，`position`
指向新插入的元素，且 `node` 为空。

|抛出： |若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。

|备注： a|
可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +

指向元素的指针和引用永远不会失效。 +

在 C++17 标准中，此方法可用于插入从兼容的 `unordered_multiset`
中提取的节点，但该功能暂未获得支持。

|===

'''''

[[unordered_set_insert_with_hint_and_node_handle]]
==== 带提示和 `node_handle` 的插入

[source,highlight]
----
iterator insert(const_iterator hint, node_type&& nh);
----

若 `nh` 为空节点，则此操作不产生任何效果。

否则，当且仅当容器中不存在等价键的元素时，才会插入 `nh` 所拥有的元素。

如果容器中已存在等价键的元素，则对 `nh` 不产生任何影响（即 `nh`
仍持有该节点）。

`hint` 是插入元素位置的建议。

[width="100%",cols="50%,50%",]
|===
|要求： |`nh` 必须是空节点，或其分配器 `nh.get_allocator()`
需与容器的分配器相等。

|返回值： a|
如果 `nh` 为空节点，则返回 `end()`。 +

如果容器中已存在等价键的元素，则返回指向该元素的迭代器。 +

否则，返回指向新插入元素的迭代器。

|抛出： |若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。

|备注： a|
C++标准对提示参数含义的规定相当笼统。在实际使用中唯一有效的方式（也是Boost.Unordered唯一支持的用法）是指向具有相同键的现有元素。 +

可能引发迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +

指向元素的指针和引用永远不会失效。 +

此操作用于插入从兼容的 `unordered_multiset` 中提取的节点。

|===

'''''

[[unordered_set_erase_by_position]]
==== 通过位置擦除

[source,highlight]
----
iterator erase(iterator position);
iterator erase(const_iterator position);
----

擦除由 `position` 指向的元素。

[cols=",",]
|===
|返回值： |返回擦除操作前位于 `position` 之后的迭代器。

|抛出： |仅当 `hasher` 或 `key_equal` 抛出异常时，本函数才会抛出异常。

|备注：
|在旧版本中此操作可能效率较低，因为需要遍历多个桶来定位返回迭代器的位置。但是数据结构现已优化，该问题已得到解决，因此原有的替代擦除方法已被弃用。
|===

'''''

[[unordered_set_erase_by_value]]
==== 通过值擦除

[source,highlight]
----
size_type erase(const key_type& k);
template<class K> size_type erase(K&& k);
----

擦除所有键等价于 `k` 的元素。

[cols=",",]
|===
|返回值： |返回被移除的元素数量。

|抛出： |仅当 `hasher` 或 `key_equal` 抛出异常时，本函数才会抛出异常。

|备注： |仅当 `Hash::is_transparent` 与 `Pred::is_transparent`
均为有效的成员类型定义，且 `iterator` 与 `const_iterator` 均不能从 `K`
隐式转换时，此重载才参与重载决议。标准库假定 `Hash` 可同时被 `K` 与
`Key` 类型调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化
`Key` 类型的开销。
|===

'''''

[[unordered_set_erase_range]]
==== 范围擦除

[source,highlight]
----
iterator erase(const_iterator first, const_iterator last);
----

擦除从 `first` 到 `last` 范围内的元素。

[width="100%",cols="50%,50%",]
|===
|返回值： |返回被擦除元素之后的迭代器——即 `last`。

|抛出： a|
仅当 `hasher` 或 `key_equal` 抛出异常时，本函数才会抛出异常。 +

在此实现中，此重载不会调用任一函数对象的方法，因此不会抛出异常，但在其他实现中可能并非如此。

|===

'''''

[[unordered_set_quick_erase]]
==== quick_erase

[source,highlight]
----
void quick_erase(const_iterator position);
----

擦除由 `position` 指向的元素。

[width="100%",cols="50%,50%",]
|===
|抛出： a|
仅当 `hasher` 或 `key_equal` 抛出异常时，本函数才会抛出异常。 +

在此实现中，此重载不会调用任一函数对象的方法，因此不会抛出异常，但在其他实现中可能并非如此。

|备注：
|此方法被实现是因为从擦除操作返回下一个元素的迭代器代价高昂，但容器经过重新设计后该问题已得到解决，因此该方法现已被弃用。
|===

'''''

[[unordered_set_erase_return_void]]
==== erase_return_void

[source,highlight]
----
void erase_return_void(const_iterator position);
----

擦除由 `position` 指向的元素。

[width="100%",cols="50%,50%",]
|===
|抛出： a|
仅当 `hasher` 或 `key_equal` 抛出异常时，本函数才会抛出异常。 +

在此实现中，此重载不会调用任一函数对象的方法，因此不会抛出异常，但在其他实现中可能并非如此。

|备注：
|此方法被实现是因为从擦除操作返回下一个元素的迭代器代价高昂，但容器经过重新设计后该问题已得到解决，因此该方法现已被弃用。
|===

'''''

[[unordered_set_swap]]
==== 交换

[source,highlight]
----
void swap(unordered_set& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
           boost::is_nothrow_swappable_v<Hash> &&
           boost::is_nothrow_swappable_v<Pred>);
----

将容器的内容与参数交换。

如果声明了 `Allocator::propagate_on_container_swap` 且
`Allocator::propagate_on_container_swap::value` 为
`true`，则交换容器的分配器。则，在分配器不相等的情况下进行交换将导致未定义行为。

[cols=",",]
|===
|抛出： |除非异常由 `key_equal` 或 `hasher`
的复制构造函数或复制赋值运算符抛出，否则本操作不会抛出异常。

|备注： |此处的异常规范与 C++11
标准不完全一致，因为相等性谓词和哈希函数是通过其复制构造函数完成交换的。
|===

'''''

[[unordered_set_clear]]
==== 清空

[source,highlight]
----
void clear() noexcept;
----

擦除容器中的所有元素。

[cols=",",]
|===
|后置条件： |`size() == 0`
|抛出： |从不抛出异常。
|===

'''''

[[unordered_set_merge]]
==== 合并

[source,highlight]
----
template<class H2, class P2>
  void merge(unordered_set<Key, H2, P2, Allocator>& source);
template<class H2, class P2>
  void merge(unordered_set<Key, H2, P2, Allocator>&& source);
template<class H2, class P2>
  void merge(unordered_multiset<Key, H2, P2, Allocator>& source);
template<class H2, class P2>
  void merge(unordered_multiset<Key, H2, P2, Allocator>&& source);
----

通过遍历 `source` 容器，提取其中不含在于 `*this`
中的任何节点，并将其插入 `*this`容器，以尝试实现两个容器的“合并”。

由于 `source`
容器可能采用不同的哈希函数与键相等性谓词，因此会使用`this->hash_function()`对
`source` 中每个节点的键进行重哈希，并在需要时通过 `this->key_eq()`
进行键值比较。

如果
`this->get_allocator() != source.get_allocator()`，则此函数的行为未定义。

此函数不会复制或移动任何元素，而是直接将节点从 `source` 重新安置到
`*this` 容器中。

[width="100%",cols="50%,50%",]
|===
|备注： a|
* 指向被转移元素的指针和引用保持有效。
* 使指向被转移元素的迭代器失效。
* 使属于 `*this` 的迭代器失效。
* 指向 `source` 中未被转移元素的迭代器保持有效。

|===

'''''

[[unordered_set_observers]]
=== 观察器

[[unordered_set_get_allocator]]
==== get_allocator

[source,highlight]
----
allocator_type get_allocator() const;
----

'''''

[[unordered_set_hash_function]]
==== hash_function

[source,highlight]
----
hasher hash_function() const;
----

[cols=",",]
|===
|返回值： |容器的哈希函数。
|===

'''''

[[unordered_set_key_eq]]
==== key_eq

[source,highlight]
----
key_equal key_eq() const;
----

[cols=",",]
|===
|返回值： |容器的键相等性谓词。
|===

'''''

[[unordered_set_lookup]]
=== 查找

[[unordered_set_find]]
==== find

[source,highlight]
----
iterator         find(const key_type& k);
const_iterator   find(const key_type& k) const;
template<class K>
  iterator       find(const K& k);
template<class K>
  const_iterator find(const K& k) const;
template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
  iterator       find(CompatibleKey const& k, CompatibleHash const& hash,
                      CompatiblePredicate const& eq);
template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
  const_iterator find(CompatibleKey const& k, CompatibleHash const& hash,
                      CompatiblePredicate const& eq) const;
----

[width="100%",cols="50%,50%",]
|===
|返回值： |返回指向键等价于 `k`
的元素的迭代器，如果不存在这样的元素，则返回 `b.end()`。

|备注： a|
包含 `CompatibleKey`、`CompatibleHash` 与 `CompatiblePredicate`
的模板化重载是非标准扩展，允许用户通过兼容的哈希函数和相等性谓词处理不同类型的键，从而避免昂贵的类型转换。通常不建议使用该扩展，而应优先使用基于
`K` 类型的成员函数模板。 +

仅当 `Hash::is_transparent` 与 `Pred::is_transparent`
均为有效的成员类型定义时，`template<class K>`
重载才参与重载决议。标准库假定 `Hash` 可同时被 `K` 与 `Key` 类型调用，且
`Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

|===

'''''

[[unordered_set_count]]
==== 统计

[source,highlight]
----
size_type        count(const key_type& k) const;
template<class K>
  size_type      count(const K& k) const;
----

[cols=",",]
|===
|返回值： |返回键等价于 `k` 的元素数量。

|备注： |仅当 `Hash::is_transparent` 与 `Pred::is_transparent`
均为有效的成员类型定义时，`template<class K>`
重载才参与重载决议。标准库假定 `Hash` 可同时被 `K` 与 `Key` 类型调用，且
`Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。
|===

'''''

[[unordered_set_contains]]
==== 存在性检查

[source,highlight]
----
bool             contains(const key_type& k) const;
template<class K>
  bool           contains(const K& k) const;
----

[cols=",",]
|===
|返回值： |返回一个布尔值，来表示容器中是否存在键等于 `key` 的元素。

|备注： |仅当 `Hash::is_transparent` 与 `Pred::is_transparent`
均为有效的成员类型定义时，`template<class K>`
重载才参与重载决议。标准库假定 `Hash` 可同时被 `K` 与 `Key` 类型调用，且
`Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。
|===

'''''

[[unordered_set_equal_range]]
==== equal_range

[source,highlight]
----
std::pair<iterator, iterator>               equal_range(const key_type& k);
std::pair<const_iterator, const_iterator>   equal_range(const key_type& k) const;
template<class K>
  std::pair<iterator, iterator>             equal_range(const K& k);
template<class K>
  std::pair<const_iterator, const_iterator> equal_range(const K& k) const;
----

[cols=",",]
|===
|返回值： |返回包含所有键等价于 `k`
的元素的区间。如果容器不包含任何此类元素，则返回
`std::make_pair(b.end(), b.end())`。

|备注： |仅当 `Hash::is_transparent` 与 `Pred::is_transparent`
均为有效的成员类型定义时，`template<class K>`
重载才参与重载决议。标准库假定 `Hash` 可同时被 `K` 与 `Key` 类型调用，且
`Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。
|===

'''''

[[unordered_set_bucket_interface]]
=== 桶接口

[[unordered_set_bucket_count]]
==== bucket_count

[source,highlight]
----
size_type bucket_count() const noexcept;
----

[cols=",",]
|===
|返回值： |桶的数量。
|===

'''''

[[unordered_set_max_bucket_count]]
==== max_bucket_count

[source,highlight]
----
size_type max_bucket_count() const noexcept;
----

[cols=",",]
|===
|返回值： |桶数量的上限值。
|===

'''''

[[unordered_set_bucket_size]]
==== bucket_size

[source,highlight]
----
size_type bucket_size(size_type n) const;
----

[cols=",",]
|===
|要求： |`n < bucket_count()`
|返回值： |返回桶 `n` 中的元素数量。
|===

'''''

[[unordered_set_bucket]]
==== bucket

[source,highlight]
----
size_type bucket(const key_type& k) const;
template<class K> size_type bucket(const K& k) const;
----

[cols=",",]
|===
|返回值： |返回键为 `k` 的元素的桶的索引。

|后置条件： |返回值小于 `bucket_count()`。

|备注： |仅当 `Hash::is_transparent` 与 `Pred::is_transparent`
均为有效的成员类型定义时，`template<class K>`
重载才参与重载决议。标准库假定 `Hash` 可同时被 `K` 与 `Key` 类型调用，且
`Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。
|===

'''''

[[unordered_set_begin_2]]
==== begin

[source,highlight]
----
local_iterator begin(size_type n);
const_local_iterator begin(size_type n) const;
----

[cols=",",]
|===
|要求： |`n` 的取值范围应为 `[0, bucket_count())` 。
|返回值： |指向索引为 `n` 的桶中第一个元素的局部迭代器。
|===

'''''

[[unordered_set_end_2]]
==== end

[source,highlight]
----
local_iterator end(size_type n);
const_local_iterator end(size_type n) const;
----

[cols=",",]
|===
|要求： |`n` 的取值范围应为 `[0, bucket_count())` 。
|返回值： |返回指向索引为 `n` 的桶中“尾后”元素的局部迭代器。
|===

'''''

[[unordered_set_cbegin_2]]
==== cbegin

[source,highlight]
----
const_local_iterator cbegin(size_type n) const;
----

[cols=",",]
|===
|要求： |`n` 的取值范围应为 `[0, bucket_count())` 。
|返回值： |返回指向索引为 `n` 的桶中第一个元素的常量局部迭代器。
|===

'''''

[[unordered_set_cend_2]]
==== cend

[source,highlight]
----
const_local_iterator cend(size_type n) const;
----

[cols=",",]
|===
|要求： |`n` 的取值范围应为 `[0, bucket_count())` 。
|返回值： |返回指向索引为 `n` 的桶中“尾后”元素的常量局部迭代器。
|===

'''''

[[unordered_set_hash_policy]]
=== 哈希策略

[[unordered_set_load_factor]]
==== load_factor

[source,highlight]
----
float load_factor() const noexcept;
----

[cols=",",]
|===
|返回值： |每个桶的平均元素数量。
|===

'''''

[[unordered_set_max_load_factor]]
==== max_load_factor

[source,highlight]
----
float max_load_factor() const noexcept;
----

[cols=",",]
|===
|返回值： |返回当前的最大负载因子。
|===

'''''

[[unordered_set_set_max_load_factor]]
==== 设置最大负载因子

[source,highlight]
----
void max_load_factor(float z);
----

[cols=",",]
|===
|效果： |使用 `z` 作为提示值来更改容器的最大负载因子。
|===

'''''

[[unordered_set_rehash]]
==== 重哈希操作

[source,highlight]
----
void rehash(size_type n);
----

调整桶的数量，使其至少为 `n`
个，并确保负载因子小于或等于最大负载因子。该操作会根据实际情况扩容或缩容容器关联的
`bucket_count()`。

当 `size() == 0` 时，执行`rehash(0)` 将释放底层桶数组的内存。

使迭代器失效，并改变元素顺序。指向元素的指针和引用不会失效。

[cols=",",]
|===
|抛出：
|若抛出异常（除非异常由容器的哈希函数或比较函数抛出），则该函数不产生任何效果。
|===

'''''

[[unordered_set_reserve]]
==== reserve

[source,highlight]
----
void reserve(size_type n);
----

等价于 `a.rehash(ceil(n / a.max_load_factor()))`，或当 `n > 0` 且
`a.max_load_factor() == std::numeric_limits<float>::infinity()` 时等价于
`a.rehash(1)`。

类似于 `rehash`，此函数可用于增加或减少容器中的桶数量。

使迭代器失效，并改变元素顺序。指向元素的指针和引用不会失效。

[cols=",",]
|===
|抛出：
|若抛出异常（除非异常由容器的哈希函数或比较函数抛出），则该函数不产生任何效果。
|===

[[unordered_set_deduction_guides]]
=== 推导指引

如果以下任一条件成立时，则推导指引不参与重载决议：

* 它具有 `InputIterator`
模板参数，且为该参数推导出的类型不符合输入迭代器要求。
* 它具有 `Allocator` 模板参数，且为该参数推导出的类型不符合分配器要求。
* 它具有 `Hash`
模板参数，且为该参数推导出的是整数类型或符合分配器要求的类型。
* 它具有 `Pred` 模板参数，且为该参数推导出的是符合分配器要求的类型。

推导指引中, `size_­type` 参数类型引用由该指南推导出的容器类型的
`size_­type` 成员类型。其默认值与所选构造函数的默认值一致。

[[unordered_set_iter_value_type]]
==== _迭代器值类型_

....
template<class InputIterator>
  using iter-value-type =
    typename std::iterator_traits<InputIterator>::value_type; // 仅为说明
....

[[unordered_set_equality_comparisons]]
=== 相等性比较

[[unordered_set_operator]]
==== operator==

[source,highlight]
----
template<class Key, class Hash, class Pred, class Alloc>
  bool operator==(const unordered_set<Key, Hash, Pred, Alloc>& x,
                  const unordered_set<Key, Hash, Pred, Alloc>& y);
----

如果 `x.size() == y.size()` 且对于 `x` 中的每个元素，在 `y`
中均存在一个具有相同键且值相等的元素（使用 `operator==`
比较值类型），则返回 `true`。

[cols=",",]
|===
|备注： |如果两个容器的相等性谓词不等价，则行为未定义。
|===

'''''

[[unordered_set_operator_2]]
==== operator!=

[source,highlight]
----
template<class Key, class Hash, class Pred, class Alloc>
  bool operator!=(const unordered_set<Key, Hash, Pred, Alloc>& x,
                  const unordered_set<Key, Hash, Pred, Alloc>& y);
----

如果 `x.size() == y.size()` 且对于 `x` 中的每个元素，在 `y`
中均存在相同键的元素，且其值相等（使用 `operator==` 比较值类型），则返回
`false`。

[cols=",",]
|===
|备注： |如果两个容器的相等性谓词不等价，则行为未定义。
|===

'''''

[[unordered_set_swap_2]]
=== 交换

[source,highlight]
----
template<class Key, class Hash, class Pred, class Alloc>
  void swap(unordered_set<Key, Hash, Pred, Alloc>& x,
            unordered_set<Key, Hash, Pred, Alloc>& y)
    noexcept(noexcept(x.swap(y)));
----

交换 `x` 和 `y` 的内容。

如果声明了 `Allocator::propagate_on_container_swap` 且
`Allocator::propagate_on_container_swap::value` 为
`true`，则交换容器的分配器。则，在分配器不相等的情况下进行交换将导致未定义行为。

[cols=",",]
|===
|效果： |`x.swap(y)`

|抛出： |除非异常由 `key_equal` 或 `hasher`
的复制构造函数或复制赋值运算符抛出，否则本操作不会抛出异常。

|备注： |此处的异常规范与 C++11
标准不完全一致，因为相等性谓词和哈希函数是通过其复制构造函数完成交换的。
|===

'''''

[[unordered_set_erase_if]]
=== erase_if

[source,highlight]
----
template<class K, class H, class P, class A, class Predicate>
  typename unordered_set<K, H, P, A>::size_type
    erase_if(unordered_set<K, H, P, A>& c, Predicate pred);
----

遍历容器 `c` 并移除所有满足谓词条件（`pred` 返回 `true`） 的元素。

[width="100%",cols="50%,50%",]
|===
|返回值： |被擦除的元素数量。
|备注： a|
等价于： +

[source,highlight]
----
auto original_size = c.size();
for (auto i = c.begin(), last = c.end(); i != last; ) {
  if (pred(*i)) {
    i = c.erase(i);
  } else {
    ++i;
  }
}
return original_size - c.size();
----

|===

[[unordered_set_serialization]]
=== 序列化

`unordered_set` 可通过本库提供的 API，借助
link:../../../../../serialization/index.html[Boost.Serialization]
实现序列化存档与读取功能。同时支持常规格式与 XML 格式的归档。

[[unordered_set_saving_an_unordered_set_to_an_archive]]
==== 将 unordered_set 保存到归档

将 `unordered_set` 对象`x` 的所有元素保存到归档（XML 归档）`ar` 中。

[cols=",",]
|===
|要求： |`value_type` 必须支持序列化（XML 可序列化），且需兼容
Boost.Serialization 的 `save_construct_data`/`load_construct_data`
协议（该协议由https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]类型自动支持）。
|===

'''''

[[unordered_set_loading_an_unordered_set_from_an_archive]]
==== 从归档加载 unordered_set

删除 `unordered_set` 对象`x` 的所有预先存在的元素，并从归档（XML
归档）`ar` 中读取原始 `unordered_set`对象 `other`
先前保存至存储的元素副本并插入到 `x` 中。

[cols=",",]
|===
|要求： |`value_type`
需满足https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入]要求，且`x.key_equal()`
在功能上需等价于 `other.key_equal()`。

|备注： |如果归档是由 Boost 1.84 之前的版本保存的，则必须全局定义配置宏
`BOOST_UNORDERED_ENABLE_SERIALIZATION_COMPATIBILITY_V0`
才能成功执行此操作；否则，将抛出异常。
|===

'''''

[[unordered_set_saving_an_iteratorconst_iterator_to_an_archive]]
==== 将迭代器/常量迭代器保存到归档

将迭代器 `iterator`（`const_iterator`）`it` 的位置信息保存到归档（XML
归档）`ar` 中。`it` 可以是 `end()` 迭代器。

[cols=",",]
|===
|要求： |迭代器`it` 指向的 `unordered_set` `x` 必须已预先保存至归档
`ar`，且在保存 `x` 和保存 `it` 的时间间隔内 `x` 执行任何修改操作。
|===

'''''

[[unordered_set_loading_an_iteratorconst_iterator_from_an_archive]]
==== 从归档加载迭代器/常量迭代器

使迭代器 `iterator`（`const_iterator`）`it` 指向之前通过 XML 归档（XML
归档）`ar`
保存的原始迭代器（常量迭代器）的恢复位置（从存储数据中还原出来的位置）。

[cols=",",]
|===
|要求： |如果 `x` 是 `it` 指向的 `unordered_set`，则在加载 `x` 与加载
`it` 的时间间隔内，不得对 `x` 执行任何修改操作。
|===

[[footer]]
[[footer-text]]
最后更新于 2025年10月 31日 21:42:55 UTC
