[#unordered_node_map]
== 类模板 unordered++_++node++_++map

:idprefix: unordered_node_map_

`boost::unordered++_++node++_++map` —— 一种基于节点、采用开放寻址法的无序关联容器，用于将唯一键与另一个值关联。

`boost::unordered++_++node++_++map` 采用与 `boost::unordered++_++flat++_++map` 相似的开放寻址布局，但由于其基于节点的特性，该容器提供了指针稳定性和节点处理功能。其性能介于 `boost::unordered++_++map` 与 `boost::unordered++_++flat++_++map` 之间。

由于采用开放寻址法， `boost::unordered++_++node++_++map` 的接口在多个方面与 `boost::unordered++_++map` / `std::unordered++_++map` 存在差异：

  - `begin()` 不是常数时间复杂度操作。
  - 未提供用于桶管理的 API（除 `bucket++_++count` 外）。
  - 容器的最大负载因子由内部管理，用户无法进行设置。

除此之外， `boost::unordered++_++node++_++map` 基本可直接替代标准无序关联容器。

=== 概要

[listing, subs="+macros,+quotes"]
-----
// #include xref:reference/header_unordered_node_map.adoc[`<boost/unordered/unordered_node_map.hpp>`]

namespace boost {
namespace unordered {

  template<class Key,
           class T,
           class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<std::pair<const Key, T>>>
  class unordered_node_map {
  public:
    // 类型定义
    using key_type             = Key;
    using mapped_type          = T;
    using value_type           = std::pair<const Key, T>;
    using init_type            = std::pair<
                                   typename std::remove_const<Key>::type,
                                   typename std::remove_const<T>::type
                                 >;
    using hasher               = Hash;
    using key_equal            = Pred;
    using allocator_type       = Allocator;
    using pointer              = typename std::allocator_traits<Allocator>::pointer;
    using const_pointer        = typename std::allocator_traits<Allocator>::const_pointer;
    using reference            = value_type&;
    using const_reference      = const value_type&;
    using size_type            = std::size_t;
    using difference_type      = std::ptrdiff_t;

    using iterator             = _implementation-defined_;
    using const_iterator       = _implementation-defined_;

    using node_type            = _implementation-defined_;
    using insert_return_type   = _implementation-defined_;

    using stats                = xref:reference/stats.adoc#stats_stats_type[__stats-type__]; // if statistics are xref:unordered_node_map_boost_unordered_enable_stats[enabled]

    // 构造/复制/销毁
    xref:#unordered_node_map_default_constructor[unordered_node_map]();
    explicit xref:#unordered_node_map_bucket_count_constructor[unordered_node_map](size_type n,
                                const hasher& hf = hasher(),
                                const key_equal& eql = key_equal(),
                                const allocator_type& a = allocator_type());
    template<class InputIterator>
      xref:#unordered_node_map_iterator_range_constructor[unordered_node_map](InputIterator f, InputIterator l,
                         size_type n = _implementation-defined_,
                         const hasher& hf = hasher(),
                         const key_equal& eql = key_equal(),
                         const allocator_type& a = allocator_type());
    xref:#unordered_node_map_copy_constructor[unordered_node_map](const unordered_node_map& other);
    xref:#unordered_node_map_move_constructor[unordered_node_map](unordered_node_map&& other);
    template<class InputIterator>
      xref:#unordered_node_map_iterator_range_constructor_with_allocator[unordered_node_map](InputIterator f, InputIterator l, const allocator_type& a);
    explicit xref:#unordered_node_map_allocator_constructor[unordered_node_map](const Allocator& a);
    xref:#unordered_node_map_copy_constructor_with_allocator[unordered_node_map](const unordered_node_map& other, const Allocator& a);
    xref:#unordered_node_map_move_constructor_with_allocator[unordered_node_map](unordered_node_map&& other, const Allocator& a);
    xref:#unordered_node_map_move_constructor_from_concurrent_node_map[unordered_node_map](concurrent_node_map<Key, T, Hash, Pred, Allocator>&& other);
    xref:#unordered_node_map_initializer_list_constructor[unordered_node_map](std::initializer_list<value_type> il,
                       size_type n = _implementation-defined_
                       const hasher& hf = hasher(),
                       const key_equal& eql = key_equal(),
                       const allocator_type& a = allocator_type());
    xref:#unordered_node_map_bucket_count_constructor_with_allocator[unordered_node_map](size_type n, const allocator_type& a);
    xref:#unordered_node_map_bucket_count_constructor_with_hasher_and_allocator[unordered_node_map](size_type n, const hasher& hf, const allocator_type& a);
    template<class InputIterator>
      xref:#unordered_node_map_iterator_range_constructor_with_bucket_count_and_allocator[unordered_node_map](InputIterator f, InputIterator l, size_type n, const allocator_type& a);
    template<class InputIterator>
      xref:#unordered_node_map_iterator_range_constructor_with_bucket_count_and_hasher[unordered_node_map](InputIterator f, InputIterator l, size_type n, const hasher& hf,
                         const allocator_type& a);
    xref:#unordered_node_map_initializer_list_constructor_with_allocator[unordered_node_map](std::initializer_list<value_type> il, const allocator_type& a);
    xref:#unordered_node_map_initializer_list_constructor_with_bucket_count_and_allocator[unordered_node_map](std::initializer_list<value_type> il, size_type n,
                       const allocator_type& a);
    xref:#unordered_node_map_initializer_list_constructor_with_bucket_count_and_hasher_and_allocator[unordered_node_map](std::initializer_list<value_type> il, size_type n, const hasher& hf,
                       const allocator_type& a);
    xref:#unordered_node_map_destructor[~unordered_node_map]();
    unordered_node_map& xref:#unordered_node_map_copy_assignment[operator++=++](const unordered_node_map& other);
    unordered_node_map& xref:#unordered_node_map_move_assignment[operator++=++](unordered_node_map&& other) ++noexcept(
      (boost::allocator_traits<Allocator>::is_always_equal::value ||
       boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value) &&
       std::is_same<pointer, value_type*>::value);++
    unordered_node_map& xref:#unordered_node_map_initializer_list_assignment[operator++=++](std::initializer_list<value_type>);
    allocator_type xref:#unordered_node_map_get_allocator[get_allocator]() const noexcept;

    // 迭代器
    iterator       xref:#unordered_node_map_begin[begin]() noexcept;
    const_iterator xref:#unordered_node_map_begin[begin]() const noexcept;
    iterator       xref:#unordered_node_map_end[end]() noexcept;
    const_iterator xref:#unordered_node_map_end[end]() const noexcept;
    const_iterator xref:#unordered_node_map_cbegin[cbegin]() const noexcept;
    const_iterator xref:#unordered_node_map_cend[cend]() const noexcept;

    // 容量
    ++[[nodiscard]]++ bool xref:#unordered_node_map_empty[empty]() const noexcept;
    size_type xref:#unordered_node_map_size[size]() const noexcept;
    size_type xref:#unordered_node_map_max_size[max_size]() const noexcept;

    // 修改器
    template<class... Args> std::pair<iterator, bool> xref:#unordered_node_map_emplace[emplace](Args&&... args);
    template<class... Args> iterator xref:#unordered_node_map_emplace_hint[emplace_hint](const_iterator position, Args&&... args);
    std::pair<iterator, bool> xref:#unordered_node_map_copy_insert[insert](const value_type& obj);
    std::pair<iterator, bool> xref:#unordered_node_map_copy_insert[insert](const init_type& obj);
    std::pair<iterator, bool> xref:#unordered_node_map_move_insert[insert](value_type&& obj);
    std::pair<iterator, bool> xref:#unordered_node_map_move_insert[insert](init_type&& obj);
    iterator       xref:#unordered_node_map_copy_insert_with_hint[insert](const_iterator hint, const value_type& obj);
    iterator       xref:#unordered_node_map_copy_insert_with_hint[insert](const_iterator hint, const init_type& obj);
    iterator       xref:#unordered_node_map_move_insert_with_hint[insert](const_iterator hint, value_type&& obj);
    iterator       xref:#unordered_node_map_copy_insert_with_hint[insert](const_iterator hint, init_type&& obj);
    template<class InputIterator> void xref:#unordered_node_map_insert_iterator_range[insert](InputIterator first, InputIterator last);
    void xref:#unordered_node_map_insert_initializer_list[insert](std::initializer_list<value_type>);
    insert_return_type xref:#unordered_node_map_insert_node[insert](node_type&& nh);
    iterator xref:#unordered_node_map_insert_node_with_hint[insert](const_iterator hint, node_type&& nh);

    template<class... Args>
      std::pair<iterator, bool> xref:#unordered_node_map_try_emplace[try_emplace](const key_type& k, Args&&... args);
    template<class... Args>
      std::pair<iterator, bool> xref:#unordered_node_map_try_emplace[try_emplace](key_type&& k, Args&&... args);
    template<class K, class... Args>
      std::pair<iterator, bool> xref:#unordered_node_map_try_emplace[try_emplace](K&& k, Args&&... args);
    template<class... Args>
      iterator xref:#unordered_node_map_try_emplace_with_hint[try_emplace](const_iterator hint, const key_type& k, Args&&... args);
    template<class... Args>
      iterator xref:#unordered_node_map_try_emplace_with_hint[try_emplace](const_iterator hint, key_type&& k, Args&&... args);
    template<class K, class... Args>
      iterator xref:#unordered_node_map_try_emplace_with_hint[try_emplace](const_iterator hint, K&& k, Args&&... args);
    template<class M>
      std::pair<iterator, bool> xref:#unordered_node_map_insert_or_assign[insert_or_assign](const key_type& k, M&& obj);
    template<class M>
      std::pair<iterator, bool> xref:#unordered_node_map_insert_or_assign[insert_or_assign](key_type&& k, M&& obj);
    template<class K, class M>
      std::pair<iterator, bool> xref:#unordered_node_map_insert_or_assign[insert_or_assign](K&& k, M&& obj);
    template<class M>
      iterator xref:#unordered_node_map_insert_or_assign_with_hint[insert_or_assign](const_iterator hint, const key_type& k, M&& obj);
    template<class M>
      iterator xref:#unordered_node_map_insert_or_assign_with_hint[insert_or_assign](const_iterator hint, key_type&& k, M&& obj);
    template<class K, class M>
      iterator xref:#unordered_node_map_insert_or_assign_with_hint[insert_or_assign](const_iterator hint, K&& k, M&& obj);

    _convertible-to-iterator_     xref:#unordered_node_map_erase_by_position[erase](iterator position);
    _convertible-to-iterator_     xref:#unordered_node_map_erase_by_position[erase](const_iterator position);
    size_type                   xref:#unordered_node_map_erase_by_key[erase](const key_type& k);
    template<class K> size_type xref:#unordered_node_map_erase_by_key[erase](K&& k);
    iterator  xref:#unordered_node_map_erase_range[erase](const_iterator first, const_iterator last);
    void      xref:#unordered_node_map_swap[swap](unordered_node_map& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
               boost::allocator_traits<Allocator>::propagate_on_container_swap::value);
    node_type xref:#unordered_node_map_extract_by_position[extract](const_iterator position);
    node_type xref:#unordered_node_map_extract_by_key[extract](const key_type& key);
    template<class K> node_type xref:#unordered_node_map_extract_by_key[extract](K&& key);
    init_type xref:#unordered_node_map_pull[pull](const_iterator position);
    void      xref:#unordered_node_map_clear[clear]() noexcept;

    template<class H2, class P2>
      void xref:#unordered_node_map_merge[merge](unordered_node_map<Key, T, H2, P2, Allocator>& source);
    template<class H2, class P2>
      void xref:#unordered_node_map_merge[merge](unordered_node_map<Key, T, H2, P2, Allocator>&& source);

    // 观察器
    hasher xref:#unordered_node_map_hash_function[hash_function]() const;
    key_equal xref:#unordered_node_map_key_eq[key_eq]() const;

    // 映射操作
    iterator         xref:#unordered_node_map_find[find](const key_type& k);
    const_iterator   xref:#unordered_node_map_find[find](const key_type& k) const;
    template<class K>
      iterator       xref:#unordered_node_map_find[find](const K& k);
    template<class K>
      const_iterator xref:#unordered_node_map_find[find](const K& k) const;
    size_type        xref:#unordered_node_map_count[count](const key_type& k) const;
    template<class K>
      size_type      xref:#unordered_node_map_count[count](const K& k) const;
    bool             xref:#unordered_node_map_contains[contains](const key_type& k) const;
    template<class K>
      bool           xref:#unordered_node_map_contains[contains](const K& k) const;
    std::pair<iterator, iterator>               xref:#unordered_node_map_equal_range[equal_range](const key_type& k);
    std::pair<const_iterator, const_iterator>   xref:#unordered_node_map_equal_range[equal_range](const key_type& k) const;
    template<class K>
      std::pair<iterator, iterator>             xref:#unordered_node_map_equal_range[equal_range](const K& k);
    template<class K>
      std::pair<const_iterator, const_iterator> xref:#unordered_node_map_equal_range[equal_range](const K& k) const;

    // 元素访问
    mapped_type& xref:#unordered_node_map_operator[operator[+]+](const key_type& k);
    mapped_type& xref:#unordered_node_map_operator[operator[+]+](key_type&& k);
    template<class K> mapped_type& xref:#unordered_node_map_operator[operator[+]+](K&& k);
    mapped_type& xref:#unordered_node_map_at[at](const key_type& k);
    const mapped_type& xref:#unordered_node_map_at[at](const key_type& k) const;
    template<class K> mapped_type& xref:#unordered_node_map_at[at](const K& k);
    template<class K> const mapped_type& xref:#unordered_node_map_at[at](const K& k) const;

    // 桶接口
    size_type xref:#unordered_node_map_bucket_count[bucket_count]() const noexcept;

    // 哈希策略
    float xref:#unordered_node_map_load_factor[load_factor]() const noexcept;
    float xref:#unordered_node_map_max_load_factor[max_load_factor]() const noexcept;
    void xref:#unordered_node_map_set_max_load_factor[max_load_factor](float z);
    size_type xref:#unordered_node_map_max_load[max_load]() const noexcept;
    void xref:#unordered_node_map_rehash[rehash](size_type n);
    void xref:#unordered_node_map_reserve[reserve](size_type n);

    // 统计（若启用）
    stats xref:#unordered_node_map_get_stats[get_stats]() const;
    void xref:#unordered_node_map_reset_stats[reset_stats]() noexcept;
  };

  // 推导指引
  template<class InputIterator,
           class Hash = boost::hash<xref:#unordered_node_map_iter_key_type[__iter-key-type__]<InputIterator>>,
           class Pred = std::equal_to<xref:#unordered_node_map_iter_key_type[__iter-key-type__]<InputIterator>>,
           class Allocator = std::allocator<xref:#unordered_node_map_iter_to_alloc_type[__iter-to-alloc-type__]<InputIterator>>>
    unordered_node_map(InputIterator, InputIterator, typename xref:#unordered_node_map_deduction_guides[__see below__]::size_type = xref:#unordered_node_map_deduction_guides[__see below__],
                       Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> unordered_node_map<xref:#unordered_node_map_iter_key_type[__iter-key-type__]<InputIterator>, xref:#unordered_node_map_iter_mapped_type[__iter-mapped-type__]<InputIterator>, Hash,
                            Pred, Allocator>;

  template<class Key, class T, class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<std::pair<const Key, T>>>
    unordered_node_map(std::initializer_list<std::pair<Key, T>>,
                       typename xref:#unordered_node_map_deduction_guides[__see below__]::size_type = xref:#unordered_node_map_deduction_guides[__see below__], Hash = Hash(),
                       Pred = Pred(), Allocator = Allocator())
      -> unordered_node_map<Key, T, Hash, Pred, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_node_map(InputIterator, InputIterator, typename xref:#unordered_node_map_deduction_guides[__see below__]::size_type, Allocator)
      -> unordered_node_map<xref:#unordered_node_map_iter_key_type[__iter-key-type__]<InputIterator>, xref:#unordered_node_map_iter_mapped_type[__iter-mapped-type__]<InputIterator>,
                            boost::hash<xref:#unordered_node_map_iter_key_type[__iter-key-type__]<InputIterator>>,
                            std::equal_to<xref:#unordered_node_map_iter_key_type[__iter-key-type__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_node_map(InputIterator, InputIterator, Allocator)
      -> unordered_node_map<xref:#unordered_node_map_iter_key_type[__iter-key-type__]<InputIterator>, xref:#unordered_node_map_iter_mapped_type[__iter-mapped-type__]<InputIterator>,
                            boost::hash<xref:#unordered_node_map_iter_key_type[__iter-key-type__]<InputIterator>>,
                            std::equal_to<xref:#unordered_node_map_iter_key_type[__iter-key-type__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Hash, class Allocator>
    unordered_node_map(InputIterator, InputIterator, typename xref:#unordered_node_map_deduction_guides[__see below__]::size_type, Hash,
                       Allocator)
      -> unordered_node_map<xref:#unordered_node_map_iter_key_type[__iter-key-type__]<InputIterator>, xref:#unordered_node_map_iter_mapped_type[__iter-mapped-type__]<InputIterator>, Hash,
                            std::equal_to<xref:#unordered_node_map_iter_key_type[__iter-key-type__]<InputIterator>>, Allocator>;

  template<class Key, class T, class Allocator>
    unordered_node_map(std::initializer_list<std::pair<Key, T>>, typename xref:#unordered_node_map_deduction_guides[__see below__]::size_type,
                       Allocator)
      -> unordered_node_map<Key, T, boost::hash<Key>, std::equal_to<Key>, Allocator>;

  template<class Key, class T, class Allocator>
    unordered_node_map(std::initializer_list<std::pair<Key, T>>, Allocator)
      -> unordered_node_map<Key, T, boost::hash<Key>, std::equal_to<Key>, Allocator>;

  template<class Key, class T, class Hash, class Allocator>
    unordered_node_map(std::initializer_list<std::pair<Key, T>>, typename xref:#unordered_node_map_deduction_guides[__see below__]::size_type,
                       Hash, Allocator)
      -> unordered_node_map<Key, T, Hash, std::equal_to<Key>, Allocator>;

} // 命名空间 unordered
} // 命名空间 boost
-----

---

=== 描述

*模板参数*

[cols="1,1"]
|===

|_键_
.2+|`std::pair++<++const Key, T++>++` 必须可从任何可转换为它的
`std::pair`
对象 https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原地构造] 到容器中，并且必须可从容器中 https://en.cppreference.com/w/cpp/named_req/Erasable[擦除] 。

|_T_

|_Hash_
|一元函数对象类型，用作 `Key` 的哈希函数。它接受一个类型为 `Key`
的参数，并返回一个 `std::size++_++t` 类型的值。

|_谓词_
|二元函数对象，用于在 `Key`
类型的值上建立等价关系。它接受两个类型为 `Key` 的参数，并返回一个 `bool`
类型的值。

|_分配器_
|一种分配器，其值类型与容器的值类型相同，是一种支持使用 https://en.cppreference.com/w/cpp/named_req/Allocator#Fancy_pointers[花式指针] 的分配器。

|===

容器的元素节点保存在内部的__桶数组__中。节点根据其元素的哈希码被插入到对应的桶中，但如果该桶已被占用（即发生__冲突__），则使用原始位置附近的可用桶。

桶数组的大小可通过调用 `insert` / `emplace` 自动增加，也可通过调用 `rehash` / `reserve` 来调整。容器的__负载因子__（元素数量与桶数量的比值）始终不会超过 `max++_++load++_++factor()` ，但在小规模数据情况下，实现可能允许更高的负载因子。

若 link:../../../../../container_hash/doc/html/hash.html#ref_hash_is_avalanchinghash[`hash++_++is++_++avalanching`]`++<++Hash++>++::value` 为 `true` ，则直接使用哈希函数；否则，会添加一个位混合后处理阶段以提高哈希质量，但会牺牲额外的计算成本。

---

=== 配置宏

==== `BOOST++_++UNORDERED++_++ENABLE++_++STATS`

全局定义此宏，以启用容器的 xref:reference/stats.adoc#stats[统计计算] 功能。请注意，此选项会降低许多操作的总体性能。

---

=== 类型定义

[source, c++, subs=+quotes]
----
typedef _implementation-defined_ iterator;
----

一种迭代器，其值类型为 `value++_++type` 。

迭代器类别至少为前向迭代器。

可转换为 `const++_++iterator` 。

---

[source, c++, subs=+quotes]
----
typedef _implementation-defined_ const_iterator;
----

一个常量迭代器，其值类型为 `value++_++type` 。

迭代器类别至少为前向迭代器。

---

[source, c++, subs=+quotes]
----
typedef _implementation-defined_ node_type;
----

用于保存已提取容器元素的类，其建模自 https://en.cppreference.com/w/cpp/container/node_handle[NodeHandle] 。

---

[source, c++, subs=+quotes]
----
typedef _implementation-defined_ insert_return_type;
----

内部类模板的特化：

[source, c++, subs=+quotes]
----
template<class Iterator, class NodeType>
struct _insert_return_type_ // name is exposition only
{
  Iterator position;
  bool     inserted;
  NodeType node;
};
----

其中 `Iterator` = `iterator` ，且 `NodeType` = `node++_++type` 。

---

=== 构造函数

==== 默认构造函数
```c++

unordered_node_map();

```

构造一个空容器，使用 `hasher()` 作为哈希函数、 `key++_++equal()` 作为键相等性谓词、以及 `allocator++_++type()` 作为分配器。

[horizontal]
后置条件;; `size() == 0`
要求;; 若使用默认值，则 `hasher` 、 `key++_++equal` 和 `allocator++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 桶数构造函数
```c++

explicit unordered_node_map(size_type n,
                            const hasher& hf = hasher(),
                            const key_equal& eql = key_equal(),
                            const allocator_type& a = allocator_type());

```

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、 `eql` 作为键相等性谓词、以及 `a` 作为分配器。

[horizontal]
后置条件;; `size() == 0`
要求;; 若使用默认值，则 `hasher` 、 `key++_++equal` 和 `allocator++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  unordered_node_map(InputIterator f, InputIterator l,
                     size_type n = _implementation-defined_,
                     const hasher& hf = hasher(),
                     const key_equal& eql = key_equal(),
                     const allocator_type& a = allocator_type());
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、 `eql` 作为键相等性谓词、 `a` 作为分配器，并将区间 `++[++f, l)` 中的元素插入其中。

[horizontal]
要求;; 若使用默认值，则 `hasher` 、 `key++_++equal` 和 `allocator++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 复制构造函数
```c++

unordered_node_map(unordered_node_map const& other);

```

复制构造函数。复制其所包含的元素、哈希函数、谓词及分配器。

若 `Allocator::select++_++on++_++container++_++copy++_++construction` 存在且签名正确，则将根据其结果来构造分配器。

---

==== 移动构造函数
```c++

unordered_node_map(unordered_node_map&& other);

```

移动构造函数。将 `other` 的内部桶数组直接转移至新容器。哈希函数、谓词和分配器均从 `other` 移动构造。若统计功能已 xref:#unordered_node_map_boost_unordered_enable_stats[启用] ，则转移 `other` 的内部统计信息，并调用 `other.reset++_++stats()` 。

---

==== 带分配器的迭代器范围构造函数
```c++

template<class InputIterator>
  unordered_node_map(InputIterator f, InputIterator l, const allocator_type& a);

```

构造一个空容器，使用 `a` 作为分配器、以及默认的哈希函数和键相等性谓词，并将 `++[++f, l)` 范围内的元素插入其中。

[horizontal]
要求;; `hasher` 和 `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 分配器构造函数
```c++

explicit unordered_node_map(Allocator const& a);

```

使用分配器 `a` 构造一个空容器。

---

==== 带分配器的复制构造函数
```c++

unordered_node_map(unordered_node_map const& other, Allocator const& a);

```

构造一个容器，复制 `other` 中的元素、哈希函数及谓词，但使用分配器 `a` 。

---

==== 带分配器的移动构造函数
```c++

unordered_node_map(unordered_node_map&& other, Allocator const& a);

```

若 `a == other.get++_++allocator()` ，则将 `other` 的元素节点直接转移至新容器；否则，从 `other` 的元素移动构造。哈希函数和谓词均从 `other` 移动构造，分配器从 `a` 复制构造。若统计功能已 xref:#unordered_node_map_boost_unordered_enable_stats[启用] ，则当 `a == other.get++_++allocator()` 时转移 `other` 的内部统计信息，并始终调用 `other.reset++_++stats()` 。

---

==== 从 concurrent++_++node++_++map 的移动构造函数

```c++

unordered_node_map(concurrent_node_map<Key, T, Hash, Pred, Allocator>&& other);

```

从 #xref:#concurrent_node_map[`concurrent_node_map`][`concurrent++_++node++_++map`] 移动构造。将 `other` 的内部桶数组直接转移至新容器。哈希函数、谓词和分配器均从 `other` 移动构造。若统计功能已 xref:#unordered_node_map_boost_unordered_enable_stats[启用] ，则转移 `other` 的内部统计信息，并调用 `other.reset++_++stats()` 。

[horizontal]
复杂度;; 常数时间复杂度。
并发性;; 阻塞于 `other` 。

---

==== 初始化列表构造函数
[source, c++, subs="+quotes"]
----
unordered_node_map(std::initializer_list<value_type> il,
              size_type n = _implementation-defined_
              const hasher& hf = hasher(),
              const key_equal& eql = key_equal(),
              const allocator_type& a = allocator_type());
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、 `eql` 作为键相等性谓词、以及 `a` 作为分配器，并将 `il` 中的元素插入其中。

[horizontal]
要求;; 若使用默认值，则 `hasher` 、 `key++_++equal` 和 `allocator++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带分配器的桶数构造函数
```c++

unordered_node_map(size_type n, allocator_type const& a);

```

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、默认的键相等性谓词以及 `a` 作为分配器。

[horizontal]
后置条件;; `size() == 0`
要求;; `hasher` 和 `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带哈希函数和分配器的桶数构造函数
```c++

unordered_node_map(size_type n, hasher const& hf, allocator_type const& a);

```

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、默认的键相等性谓词以及 `a` 作为分配器。

[horizontal]
后置条件;; `size() == 0`
要求;; `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带桶数和分配器的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  unordered_node_map(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `a` 作为分配器、以及默认的哈希函数和键相等性谓词，并将 `++[++f, l)` 范围内的元素插入其中。

[horizontal]
要求;; `hasher` 和 `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带桶数和哈希函数的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
    template<class InputIterator>
      unordered_node_map(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                         const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、 `a` 作为分配器以及默认的键相等性谓词，并将 `++[++f, l)` 范围内的元素插入其中。

[horizontal]
要求;; `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带分配器的初始化列表构造函数

```c++

unordered_node_map(std::initializer_list<value_type> il, const allocator_type& a);

```

构造一个空容器，使用 `a` 作为分配器、以及默认的哈希函数和键相等性谓词，并将 `il` 中的元素插入其中。

[horizontal]
要求;; `hasher` 和 `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带桶数和分配器的初始化列表构造函数

```c++

unordered_node_map(std::initializer_list<value_type> il, size_type n, const allocator_type& a);

```

构造一个至少包含 `n` 个桶的空容器，使用 `a` 作为分配器、默认哈希函数和键相等性谓词，并将 `il` 中的元素插入其中。

[horizontal]
要求;; `hasher` 和 `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

==== 带桶数、哈希函数和分配器的初始化列表构造函数

```c++

unordered_node_map(std::initializer_list<value_type> il, size_type n, const hasher& hf,
                   const allocator_type& a);

```

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、 `a` 作为分配器、默认键相等性谓词，并将 `il` 中的元素插入其中。

[horizontal]
要求;; `key++_++equal` 需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求。

---

=== 析构函数

```c++

~unordered_node_map();

```

[horizontal]
注意;; 析构函数会作用于每个元素，并释放所有内存

---

=== 赋值操作

==== 复制赋值

```c++

unordered_node_map& operator=(unordered_node_map const& other);

```

赋值操作符。该操作会销毁容器中原有的元素，并从 `other` 复制赋值哈希函数与键相等性谓词。若 `Alloc::propagate++_++on++_++container++_++copy++_++assignment` 存在，且 `Alloc::propagate++_++on++_++container++_++copy++_++assignment::value` 为 `true` ，则从 `other` 复制赋值分配器，最后插入 `other` 中所有元素的副本。

[horizontal]
要求;; `value++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入] 要求

---

==== 移动赋值
```c++

unordered_node_map& operator=(unordered_node_map&& other)
  noexcept((boost::allocator_traits<Allocator>::is_always_equal::value ||
            boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value) &&
            std::is_same<pointer, value_type*>::value);

```
移动赋值运算符。该操作会销毁容器中原有的元素，交换 `other`
的哈希函数和谓词，若
`Alloc::propagate++_++on++_++container++_++move++_++assignment` 存在且
`Alloc::propagate++_++on++_++container++_++move++_++assignment::value`
为 `true` ，则从 `other` 移动赋值分配器。若此时分配器与
`other.get++_++allocator()` 相等，则直接将 `other`
的内部桶数组转移至当前容器；否则，将插入 `other`
中元素的移动构造副本。若统计功能 xref:#unordered_node_map_boost_unordered_enable_stats[已启用] ，则当且仅当最终分配器与
`other.get++_++allocator()` 相等时，同时转移其内部统计信息，并始终调用
`other.reset++_++stats()` 。

---

==== 初始化列表赋值
```c++

unordered_node_map& operator=(std::initializer_list<value_type> il);

```

从初始化列表中的值赋值。该操作销毁所有原有元素。

[horizontal]
要求;; `value++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入] 要求

=== 迭代器

==== begin
```c++

iterator begin() noexcept; const_iterator begin() const noexcept;

```

[horizontal]
返回;; 返回一个指向容器第一个元素的迭代器；若容器为空，则返回容器的结束迭代器。
复杂度;; O(`bucket++_++count()`)

---

==== end
```c++

iterator end() noexcept; const_iterator end() const noexcept;

```

[horizontal]
返回;; 返回指向容器结束位置的迭代器。

---

==== cbegin
```c++

const_iterator cbegin() const noexcept;

```

[horizontal]
返回;; 返回一个指向容器第一个元素的 `const++_++iterator` （常量迭代器）；若容器为空，则返回容器的结束迭代器。
复杂度;; O(`bucket++_++count()`)

---

==== cend
```c++

const_iterator cend() const noexcept;

```

[horizontal]
返回;; 返回一个指向容器结束位置的 `const++_++iterator` （常量迭代器）。

---

=== 大小与容量

==== 空

```c++

[[nodiscard]] bool empty() const noexcept;

```

[horizontal]
返回;; `size() == 0`

---

==== 大小

```c++

size_type size() const noexcept;

```

[horizontal]
返回;; `std::distance(begin(), end())`

---

==== max++_++size

```c++

size_type max_size() const noexcept;

```

[horizontal]
返回;; 返回该容器可能容纳的最大值 `size()` 。

---

=== 修改器

==== 原地构造
```c++

template<class... Args> std::pair<iterator, bool> emplace(Args&&... args);

```

当且仅当容器中不存在具有等价键的元素时，插入一个由参数 `args` 构造的对象。

[horizontal]
要求;; `value++_++type` 必须能够从 `args` 参数构造。
返回;; 如果插入操作发生，则返回类型的 `bool` 分量为 `true` 。 +
+
若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 可能会导致迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
若 `args…` 的形式为 `k,v` ，该实现会延迟构造完整对象，直到确认需要插入元素时为止，在此期间仅使用参数 `k` 进行检查。当 `key++_++type` 可移动构造，或参数 `k` 的类型为 `key++_++type` 时，此优化生效。

---

==== emplace++_++hint
```c++

template<class... Args> iterator emplace_hint(const_iterator position, Args&&... args);

```

当且仅当容器中不存在具有等价键的元素时，插入一个由参数 `args` 构造的对象。

`position` 是一个关于元素插入位置的提示，本实现将忽略该提示。

[horizontal]
要求;; `value++_++type` 必须能够从 `args` 参数构造。
返回;; 如果插入操作发生，则返回类型的 `bool` 分量为 `true` 。 +
+
若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 可能会导致迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
若 `args…` 的形式为 `k,v` ，该实现会延迟构造完整对象，直到确认需要插入元素时为止，在此期间仅使用参数 `k` 进行检查。当 `key++_++type` 可移动构造，或参数 `k` 的类型为 `key++_++type` 时，此优化生效。

---

==== 复制插入
```c++

std::pair<iterator, bool> insert(const value_type& obj); std::pair<iterator, bool> insert(const init_type& obj);

```

当且仅当容器中不存在等价键时，将 `obj` 对象插入到容器中。

[horizontal]
要求;; `value++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入] 要求。
返回;; 如果插入操作发生，则返回类型的 `bool` 分量为 `true` 。 +
+
若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 可能会导致迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
对于 `insert(x)` 形式的调用（其中 `x` 可同等地转换为 `const value++_++type&` 和 `const init++_++type&` ），该调用不会产生歧义，并选择 `init++_++type` 重载。

---

==== 移动插入
```c++

std::pair<iterator, bool> insert(value_type&& obj); std::pair<iterator, bool> insert(init_type&& obj);

```

当且仅当容器中不存在等价键时，将 `obj` 对象插入到容器中。

[horizontal]
要求;; `value++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入] 要求。
返回;; 如果插入操作发生，则返回类型的 `bool` 分量为 `true` 。 +
+
若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 可能会导致迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
对于 `insert(x)` 形式的调用（其中 `x` 可同等地转换为 `const value++_++type&` 和 `const init++_++type&` ），不会产生歧义，并选择 `init++_++type` 重载。

---

==== 带提示的复制插入
```c++

iterator insert(const_iterator hint, const value_type& obj); iterator insert(const_iterator hint, const init_type& obj);

``` 当且仅当容器中不存在具有等价键的元素时，插入 `obj` 。

`hint` 是一个关于元素插入位置的提示，本实现将忽略该提示。

[horizontal]
要求;; `value++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入] 要求。
返回;; 如果插入操作发生，则返回类型的 `bool` 分量为 `true` 。 +
+
若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 可能会导致迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
对于 `insert(hint, x)` 形式的调用（其中 `x` 可同等地转换为 `const value++_++type&` 和 `const init++_++type&` ），该调用不会产生歧义，并会选择 `init++_++type` 重载版本。

---

==== 带提示的移动插入
```c++

iterator insert(const_iterator hint, value_type&& obj); iterator insert(const_iterator hint, init_type&& obj);

```

当且仅当容器中不存在等价键时，将 `obj` 对象插入到容器中。

`hint` 是一个关于元素插入位置的提示，本实现将忽略该提示。

[horizontal]
要求;; `value++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入] 要求。
返回;; 如果插入操作发生，则返回类型的 `bool` 分量为 `true` 。 +
+
若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 可能会导致迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
对于 `insert(hint, x)` 形式的调用（其中 `x` 可同等地转换为 `value++_++type&&` 和 `init++_++type&&` ），该调用不会产生歧义，并会选择 `init++_++type` 重载版本。

---

==== 迭代器范围插入
```c++

template<class InputIterator> void insert(InputIterator first, InputIterator last);

```

将元素范围插入容器中。仅当容器中不存在等价键的元素时，才会插入相应元素。

[horizontal]
要求;; `value++_++type` 必须能够通过 `++*++first` 在容器中进行 https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原地构造] 。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 可能会导致迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。

---

==== 初始化列表插入
```c++

void insert(std::initializer_list<value_type>);

```

将元素范围插入容器中。仅当容器中不存在等价键的元素时，才会插入相应元素。

[horizontal]
要求;; `value++_++type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入] 到容器中的要求。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 可能会导致迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。

---

==== 节点插入
```c++

insert_return_type insert(node_type&& nh);

```

若 `nh` 非空，则当且仅当容器中不存在键等价于 `nh.key()` 的元素时，插入其关联元素。函数返回时 `nh` 为空。

[horizontal]
返回;; 返回一个从 `position` 、 `inserted` 和 `node` 构造的 `insert++_++return++_++type` 对象： +
* 若 `nh` 为空，则 `inserted` 为 `false` ， `position` 为 `end()` ，且 `node` 为空。
* 否则，若插入操作发生，则 `inserted` 为 `true` ， `position` 指向被插入的元素，且 `node` 为空。
* 若插入操作失败，则 `inserted` 为 `false` ， `node` 保留 `nh` 的原始值，且 `position` 指向与 `nh.key()` 等效的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 如果 `nh` 非空，且 `nh` 与容器的分配器不相等，则行为未定义。

---

==== 带提示的节点插入
```c++

iterator insert(const_iterator hint, node_type&& nh);

```

若 `nh` 非空，则当且仅当容器中不存在键等价于 `nh.key()` 的元素时，插入其关联的元素。若插入操作发生，则 `nh` 变为空；否则 `nh` 保持不变。

`hint` 是一个关于元素插入位置的提示，本实现将忽略该提示。

[horizontal]
返回;; 若 `nh` 为空，则返回的迭代器为 `end()` 。若插入操作发生，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 如果 `nh` 非空，且 `nh` 与容器的分配器不相等，则行为未定义。

---

==== try++_++emplace
```c++

template<class... Args>
  std::pair<iterator, bool> try_emplace(const key_type& k, Args&&... args);
template<class... Args>
  std::pair<iterator, bool> try_emplace(key_type&& k, Args&&... args);
template<class K, class... Args>
  std::pair<iterator, bool> try_emplace(K&& k, Args&&... args);

```

若容器中不存在键为 `k` 的元素，则插入一个新元素。

若存在键为 `k` 的元素，则此函数不执行任何操作。

[horizontal]
返回;; 如果插入操作发生，则返回类型的 `bool` 分量为 `true` 。 +
+
若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 此函数与 xref:#unordered_node_map_emplace[emplace] 类似，区别在于：若已存在具有等价键的元素，则不会构造任何 `value++_++type` 对象；否则，将按以下形式构造： +
+
--
```c++

// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

```

而非像 xref:#unordered_node_map_emplace[emplace] 会简单地将所有参数转发给 `value++_++type` 的构造函数。

可能会导致迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。

仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent` 均为有效的成员类型别名，且 `iterator` 和 `const++_++iterator` 均不能从 `K` 隐式转换时， `template++<++class K, class... Args++>++` 重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

--

---

==== 带提示的 try++_++emplace
```c++

template<class... Args>
  iterator try_emplace(const_iterator hint, const key_type& k, Args&&... args);
template<class... Args>
  iterator try_emplace(const_iterator hint, key_type&& k, Args&&... args);
template<class K, class... Args>
  iterator try_emplace(const_iterator hint, K&& k, Args&&... args);

```

若容器中不存在键为 `k` 的元素，则插入一个新元素。

若存在键为 `k` 的元素，则此函数不执行任何操作。

`hint` 是一个关于元素插入位置的提示，本实现将忽略该提示。

[horizontal]
返回;; 若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 此函数与 xref:#unordered_node_map_emplace_hint[emplace++_++hint] 类似，区别在于：若已存在具有等效键的元素，则不会构造任何 `value++_++type` 对象；否则，将按以下形式构造： +
+
--
```c++

// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

```

而非像 xref:#unordered_node_map_emplace_hint[emplace++_++hint] 会简单地将所有参数转发给 `value++_++type` 的构造函数。

可能会导致迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。

仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent` 均为有效的成员类型别名，且 `iterator` 和 `const++_++iterator` 均不能从 `K` 隐式转换时， `template++<++class K, class... Args++>++` 重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

--

---

==== insert++_++or++_++assign
```c++

template<class M>
  std::pair<iterator, bool> insert_or_assign(const key_type& k, M&& obj);
template<class M>
  std::pair<iterator, bool> insert_or_assign(key_type&& k, M&& obj);
template<class K, class M>
  std::pair<iterator, bool> insert_or_assign(K&& k, M&& obj);

```

向容器中插入新元素，或通过赋值给已存在的元素值来更新该元素。

如果存在键为 `k` 的元素，则通过赋值 `std::forward++<++M++>++(obj)` 来更新该元素。

若不存在该元素，则将其以如下方式添加到容器中： ```c++

// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))

```

[horizontal]
返回;; 如果插入操作发生，则返回类型的 `bool` 分量为 `true` 。 +
+
若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 可能会导致迭代器失效，但仅当插入操作导致负载超过最大负载时才会发生。 +
+
仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K, class M++>++` 才会参与重载决议。标准库假设 `Hash` 可同时被 `K` 与 `Key` 类型调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型对象所需的开销。

---

==== 带提示的 insert++_++or++_++assign
```c++

template<class M>
  iterator insert_or_assign(const_iterator hint, const key_type& k, M&& obj);
template<class M>
  iterator insert_or_assign(const_iterator hint, key_type&& k, M&& obj);
template<class K, class M>
  iterator insert_or_assign(const_iterator hint, K&& k, M&& obj);

```

向容器中插入新元素，或通过赋值给已存在的元素值来更新该元素。

如果存在键为 `k` 的元素，则通过赋值 `std::forward++<++M++>++(obj)` 来更新该元素。

若不存在该元素，则将其以如下方式添加到容器中： ```c++

// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))

```

`hint` 是一个关于元素插入位置的提示，本实现将忽略该提示。

[horizontal]
返回;; 若插入成功，则迭代器指向新插入的元素；否则，指向具有等价键的元素。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 可能会导致迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K, class M++>++` 才会参与重载决议。标准库假设 `Hash` 可同时被 `K` 与 `Key` 类型调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型对象所需的开销。

---


==== 通过位置擦除

[source, c++, subs=+quotes]
----
_convertible-to-iterator_ erase(iterator position);
_convertible-to-iterator_ erase(const_iterator position);
----

擦除由 `position` 指向的元素。

[horizontal]
返回;; 返回一个不透明对象，该对象可隐式转换为擦除前紧接在 `position` 之后的 `iterator` 或 `const++_++iterator` 。
抛出;; 无。
注意;; 返回的不透明对象必须被立即丢弃或转换为 `iterator` 或 `const++_++iterator` 。

---

==== 通过键擦除
```c++

size_type erase(const key_type& k); template<class K> size_type erase(K&& k);

```

擦除所有键等价于 `k` 的元素。

[horizontal]
返回;; 被擦除的元素数量。
抛出;; 仅当 `hasher` 或 `key++_++equal` 抛出异常时，才会抛出异常。
注意;; 仅当 `Hash::is++_++transparent` 与 `Pred::is++_++transparent` 均为有效的成员类型别名，且 `iterator` 和 `const++_++iterator` 均不能从 `K` 类型隐式转换时， `template++<++class K++>++` 重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 类型调用，且 `Pred` 为透明谓词。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

==== 范围擦除

```c++

iterator erase(const_iterator first, const_iterator last);

```

擦除从 `first` 到 `last` 范围内（包含 `first` ，不包含 `last` ）的元素。

[horizontal]
返回;; 返回被擦除元素之后的迭代器——即 `last` 。
抛出;; 在此实现中不抛出任何异常（既不调用 `hasher` ， 也不调用 `key++_++equal` 对象）。

---

==== 交换
```c++

void swap(unordered_node_map& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
           boost::allocator_traits<Allocator>::propagate_on_container_swap::value);

```

交换容器与参数的内容。

如果声明了 `Allocator::propagate++_++on++_++container++_++swap` 且 `Allocator::propagate++_++on++_++container++_++swap::value` 为 `true` ，则交换容器的分配器。则，在分配器不相等的情况下进行交换将导致未定义行为。

[horizontal]
抛出;; 除非异常由 `key++_++equal` 或 `hasher` 在交换时抛出，否则本操作不会抛出任何异常。

---

==== 通过位置提取
```c++

node_type extract(const_iterator position);

```

提取由 `position` 指向的元素。

[horizontal]
返回;; 返回一个包含被提取元素的 `node++_++type` 对象。
抛出;; 无。

---

==== 通过键提取
```c++

node_type extract(const key_type& k); template<class K> node_type extract(K&& k);

```

若存在键等价于 `k` 的元素，则提取该元素。

[horizontal]
返回;; 返回一个包含被提取元素的 `node++_++type` 对象；若未提取到元素，则返回空对象。
抛出;; 仅当 `hasher` 或 `key++_++equal` 抛出异常时，才会抛出异常。
注意;; 仅当 `Hash::is++_++transparent` 与 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K++>++` 重载才会参与重载决议。标准库假设 `Hash` 可同时被 `K` 与 `Key` 类型调用，且 `Pred` 为透明的。这支持异构查找，该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

==== pull
```c++

init_type pull(const_iterator position);

```

从 `position` 指向的元素移动构造一个 `init++_++value` 对象 `x` ，擦除该元素并返回 `x` 。

---

==== 清空
```c++

void clear() noexcept;

```

擦除容器中的所有元素。

[horizontal]
后置条件;; `size() == 0` ， `max++_++load() ++>++= max++_++load++_++factor() ++*++ bucket++_++count()`

---

==== 合并
```c++

template<class H2, class P2>
  void merge(unordered_node_map<Key, T, H2, P2, Allocator>& source);
template<class H2, class P2>
  void merge(unordered_node_map<Key, T, H2, P2, Allocator>&& source);

```

转移 `source` 中所有键不在 `++*++this` 中的元素节点。

[horizontal]
要求;; `this-++>++get++_++allocator() == source.get++_++allocator()` 。
注意;; 指向被转移元素的迭代器将失效。若 `++*++this` 的最终大小大于其原始最大负载，则与 `++*++this` 关联的所有迭代器将失效。

---

=== 观察器

==== get++_++allocator
```

allocator_type get_allocator() const noexcept;

```

[horizontal]
返回;; 容器的分配器。

---

==== 哈希函数
```

hasher hash_function() const;

```

[horizontal]
返回;; 容器的哈希函数。

---

==== key++_++eq
```

key_equal key_eq() const;

```

[horizontal]
返回;; 容器的键相等性谓词

---

=== 查找

==== find
```c++

iterator         find(const key_type& k);
const_iterator   find(const key_type& k) const;
template<class K>
  iterator       find(const K& k);

```

[horizontal]
返回;; 返回一个指向键等价于 `k` 的元素的迭代器；若不存在这样的元素，则返回 `end()` 。
注意;; 仅当 `Hash::is++_++transparent` 与 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K++>++` 重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 类型调用，且 `Pred` 为透明谓词。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

==== count
```c++

size_type        count(const key_type& k) const;
template<class K>
  size_type      count(const K& k) const;

```

[horizontal]
返回;; 返回键等价于 `k` 的元素数量。
注意;; 仅当 `Hash::is++_++transparent` 与 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K++>++` 重载才会参与重载决议。标准库假设 `Hash` 可同时被 `K` 与 `Key` 类型调用，且 `Pred` 为透明的。这支持异构查找，该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

==== 包含
```c++

bool             contains(const key_type& k) const;
template<class K>
  bool           contains(const K& k) const;

```

[horizontal]
返回;; 返回一个布尔值，来表示容器中是否存在键等于 `key` 的元素
注意;; 仅当 `Hash::is++_++transparent` 与 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K++>++` 重载才会参与重载决议。标准库假设 `Hash` 可同时被 `K` 与 `Key` 类型调用，且 `Pred` 为透明的。这支持异构查找，该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

==== equal++_++range
```c++

std::pair<iterator, iterator>               equal_range(const key_type& k);
std::pair<const_iterator, const_iterator>   equal_range(const key_type& k) const;
template<class K>
  std::pair<iterator, iterator>             equal_range(const K& k);
template<class K>
  std::pair<const_iterator, const_iterator> equal_range(const K& k) const;

```

[horizontal]
返回;; 返回包含所有键等价于 `k`的元素的范围。若容器中不存在此类元素，则返回 `std::make++_++pair(b.end(), b.end())` 。
注意;; 仅当 `Hash::is++_++transparent` 与 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K++>++` 重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 类型调用，且 `Pred` 为透明谓词。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

==== operator++[]++
```c++

mapped_type& operator[](const key_type& k); mapped_type& operator[](key_type&& k); template<class K> mapped_type& operator[](K&& k);

```

[horizontal]
效果;; 若容器中尚不存在键等价于 `k` 的元素，则插入值 `std::pair++<++key++_++type const, mapped++_++type++>++(k, mapped++_++type())` 。
返回;; 返回一个引用，该引用指向容器中已存在的键等于 `k` 的元素 `x` 的 `x.second` 成员；若元素不存在，则指向新插入元素的该成员。
抛出;; 若异常由 `hasher` 调用之外的操作引发，则该函数不产生任何效果。
注意;; 可能会导致迭代器失效，但仅当插入操作导致负载因子大于或等于最大负载因子时才会发生。 +
+
仅当 `Hash::is++_++transparent` 与 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K++>++` 重载才会参与重载决议。标准库假设 `Hash` 可同时被 `K` 与 `Key` 类型调用，且 `Pred` 为透明的。这支持异构查找，该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

==== at
```c++

mapped_type& at(const key_type& k); const mapped_type& at(const key_type& k) const; template<class K> mapped_type& at(const K& k); template<class K> const mapped_type& at(const K& k) const;

```

[horizontal]
返回;; 返回一个引用，该引用指向键等价于 `k` 的（唯一）元素 `x` 的 `x.second` 成员。
抛出;; 如果不存在这样的元素，则抛出类型为 `std::out++_++of++_++range` 的异常对象。
注意;; 仅当 `Hash::is++_++transparent` 与 `Pred::is++_++transparent` 均为有效的成员类型别名时， `template++<++class K++>++` 重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 类型调用，且 `Pred` 为透明谓词。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

---

=== 桶接口

==== bucket++_++count
```c++

size_type bucket_count() const noexcept;

```

[horizontal]
返回;; 桶数组的大小。

---

=== 哈希策略

==== 负载因子
```c++

float load_factor() const noexcept;

```

[horizontal]
返回;; 返回 `static++_++cast++<++float++>++(size())/static++_++cast++<++float++>++(bucket++_++count())` ，若 `bucket++_++count() == 0` ， 则返回 `0` 。

---

==== max++_++load++_++factor（最大负载因子）

```c++

float max_load_factor() const noexcept;

```

[horizontal]
返回;; 容器的最大负载因子。

---

==== 设置最大负载因子
```c++

void max_load_factor(float z);

```

[horizontal]
效果;; 不执行任何操作，因为用户不允许修改此参数。保留此接口是为了与 `boost::unordered++_++map` 保持兼容。

---


==== max++_++load（最大负载）

```c++

size_type max_load() const noexcept;

```

[horizontal]
返回;; 返回容器在不重哈希的情况下可容纳的最大元素数（假设不再擦除元素）。
注意;; 在构造、重新哈希或清空操作后，容器的最大负载至少为 `max++_++load++_++factor() ++*++ bucket++_++count()` 。在高负载条件下执行擦除操作时，此数值可能会降低。

---

==== 重哈希
```c++

void rehash(size_type n);

```

如有必要，将改变桶数组的大小，使其至少包含 `n` 个桶，并确保负载因子小于或等于最大负载因子。此操作将根据情况增加或减少容器的 `bucket++_++count()` 。

当 `size() == 0` 时， `rehash(0)` 将释放底层桶数组。若使用的分配器采用花式指针，随后会执行默认分配操作。

使迭代器失效并改变元素顺序。

[horizontal]
抛出;; 若抛出异常（除非异常由容器的哈希函数或比较函数抛出），则该函数不产生任何效果。

---

==== 保留
```c++

void reserve(size_type n);

```

等价于 `a.rehash(ceil(n / a.max++_++load++_++factor()))` 。

与 `rehash` 类似，此函数可用于增加或减少容器中的桶数量。

使迭代器失效并改变元素顺序。

[horizontal]
抛出;; 若抛出异常（除非异常由容器的哈希函数或比较函数抛出），则该函数不产生任何效果。

---

=== 统计信息

==== get++_++stats
```c++

stats get_stats() const;

```

[horizontal]
返回;; 返回容器直到目前已执行插入和查找操作的统计摘要。
注意;; 仅当 xref:reference/stats.adoc#stats[统计计算] 功能 xref:#unordered_node_map_boost_unordered_enable_stats[启用] 时可用。

---

==== reset++_++stats
```c++

void reset_stats() noexcept;

```

[horizontal]
效果;; 将容器维护的内部统计信息清零。
注意;; 仅当 xref:reference/stats.adoc#stats[统计计算] 功能 xref:#unordered_node_map_boost_unordered_enable_stats[启用] 时可用。

---

=== 推导指引
如果以下任何一条件为真，则推导指引将不参与重载决议：

  - 该推导指引包含 `InputIterator` 模板参数，且为此参数推导出的类型不符合输入迭代器的要求。
  - 该推导指引包含 `Allocator` 模板参数，且为该参数推导出的类型不符合分配器要求。
  - 该推导指引包含 `Hash` 模板参数，且为该参数推导出的类型为整型或符合分配器要求。
  - 该推导指引包含 `Pred` 模板参数，且为该参数推导出的类型符合分配器要求。

推导指引中的 `size++_++type` 参数类型，指向由该推导指引所推导容器类型的 `size++_++type` 成员类型。其默认值与所选构造函数的默认值一致。

==== _iter-value-type_
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-value-type__ =
    typename std::iterator_traits<InputIterator>::value_type; // exposition only
-----

==== __iter-key-type__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-key-type__ = std::remove_const_t<
    std::tuple_element_t<0, xref:#unordered_node_map_iter_value_type[__iter-value-type__]<InputIterator>>>; // exposition only
-----

==== __iter-mapped-type__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-mapped-type__ =
    std::tuple_element_t<1, xref:#unordered_node_map_iter_value_type[__iter-value-type__]<InputIterator>>;  // exposition only
-----

==== __iter-to-alloc-type__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-to-alloc-type__ = std::pair<
    std::add_const_t<std::tuple_element_t<0, xref:#unordered_node_map_iter_value_type[__iter-value-type__]<InputIterator>>>,
    std::tuple_element_t<1, xref:#unordered_node_map_iter_value_type[__iter-value-type__]<InputIterator>>>; // exposition only
-----

=== 相等性比较

==== operator==
```c++

template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator==(const unordered_node_map<Key, T, Hash, Pred, Alloc>& x,
                  const unordered_node_map<Key, T, Hash, Pred, Alloc>& y);

```

若 `x.size() == y.size()` 且对于 `x` 中的每个元素， `y` 中均存在一个具有相同键和相等值（使用 `operator==` 比较值类型）的元素，则返回 `true` 。

[horizontal]
注意;; 如果两个容器的相等性谓词不等价，则行为未定义。

---

==== operator!=
```c++

template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator!=(const unordered_node_map<Key, T, Hash, Pred, Alloc>& x,
                  const unordered_node_map<Key, T, Hash, Pred, Alloc>& y);

```

如果 `x.size() == y.size()` ，且对于 `x` 中的每个元素，在 `y` 中均存在一个具有相同键且值相等的元素（使用 `operator==` 比较值类型），则返回 `false` 。

[horizontal]
注意;; 如果两个容器的相等性谓词不等价，则行为未定义。

=== 交换
```c++

template<class Key, class T, class Hash, class Pred, class Alloc>
  void swap(unordered_node_map<Key, T, Hash, Pred, Alloc>& x,
            unordered_node_map<Key, T, Hash, Pred, Alloc>& y)
    noexcept(noexcept(x.swap(y)));

```

交换 `x` 与 `y` 的内容。

如果声明了 `Allocator::propagate++_++on++_++container++_++swap` 且 `Allocator::propagate++_++on++_++container++_++swap::value` 为 `true` ，则交换容器的分配器。则，在分配器不相等的情况下进行交换将导致未定义行为。

[horizontal]
效果;; `x.swap(y)`
抛出;; 除非异常由 `key++_++equal` 或 `hasher` 在交换时抛出，否则本操作不会抛出任何异常。

---

=== erase++_++if
```c++

template<class K, class T, class H, class P, class A, class Predicate>
  typename unordered_node_map<K, T, H, P, A>::size_type
    erase_if(unordered_node_map<K, T, H, P, A>& c, Predicate pred);

```

遍历容器 `c` ，并删除所有使提供的谓词返回 `true` 的元素。

[horizontal]
返回;; 被擦除的元素数量。
注意;; 等价于： +
+
```c++

auto original_size = c.size();
for (auto i = c.begin(), last = c.end(); i != last; ) {
  if (pred(*i)) {
    i = c.erase(i);
  } else {
    ++i;
  }
}
return original_size - c.size();

```
+
请注意，传递给 `pred` 的引用是非常量的。

=== 序列化

`unordered++_++node++_++map` 可通过本组件库提供的 API，借助 link:../../../../../serialization/index.html[Boost.Serialization] 进行归档/检索。支持常规归档与 XML 归档两种格式。

==== 将 unordered++_++node++_++map 保存到归档

将 `unordered++_++node++_++map` `x` 的所有元素保存到归档（XML 归档） `ar` 。

[horizontal]
要求;; `std::remove++_++const++<++key++_++type++>++::type` 和 `std::remove++_++const++<++mapped++_++type++>++::type` 必须满足可序列化要求（XML 可序列化），且需要支持 Boost.Serialization 的 `save++_++construct++_++data` / `load++_++construct++_++data` 协议（该协议自动支持 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造] 要求）。

---

==== 从归档加载 unordered++_++node++_++map

删除 `unordered++_++node++_++map` 容器 `x` 中所有已存在的元素，并从归档（XML 归档） `ar` 中插入原始 `unordered++_++node++_++map` 容器 `other` 的元素副本，这些副本是从 `ar` 所读取的存储中恢复的。

[horizontal]
要求;; `key++_++type` 与 `mapped++_++type` 必须能够分别从 `std::remove++_++const++<++key++_++type++>++::type&&` 和 `std::remove++_++const++<++mapped++_++type++>++::type&&` 构造。且需要 `x.key++_++equal()` 在功能上等价于 `other.key++_++equal()` 。

---

==== 将迭代器/常量迭代器保存到归档

将 `iterator` （ `const++_++iterator` ）常量迭代器 `it` 的位置信息保存到归档（XML 归档） `ar` 中。 `it` 可以是 `end()` 迭代器。

[horizontal]
要求;; `it` 所指向的 `unordered++_++node++_++map` 容器 `x` 必须先前已保存至 `ar` ，且在保存 `x` 与保存 `it` 期间不得对 `x` 执行任何修改操作。

---

==== 从归档加载迭代器/常量迭代器

使 `iterator` （ `const++_++iterator` ） `it` 指向原始 `iterator` （ `const++_++iterator` ）所恢复的位置。该原始迭代器已被保存到由归档（XML 归档） `ar` 读取的存储中。

[horizontal]
要求;; 若 `x` 是 `it` 所指向的 `unordered++_++node++_++map` 容器，则在加载 `x` 与加载 `it` 期间不得对 `x` 执行任何修改操作。
