[#unordered_node_set]
== 类模板 unordered_node_set

:idprefix: unordered_node_set_

`boost::unordered_node_set` —— 一种基于节点、采用开放寻址法的无序关联容器，用于存储唯一值。

`boost::unordered_node_set` 采用类似 `boost::unordered_flat_set` 的开放寻址布局，但作为基于节点的容器，它提供了指针稳定性和节点处理功能。其性能介于 `boost::unordered_set` 和 `boost::unordered_flat_set` 之间。

由于采用开放寻址法，`boost::unordered_node_set` 的接口在多个方面与 `boost::unordered_set`/`std::unordered_set` 存在差异：

  - `begin()` 操作不具备常数时间复杂度。
  - 不提供桶处理 API（除 `bucket_count` 外）。
  - 容器的最大负载因子由内部管理，用户无法设置。

除此之外，`boost::unordered_node_set` 基本可直接替代标准无序关联容器。

=== 概要

[listing, subs="+macros,+quotes"]
-----
// #include xref:reference/header_unordered_node极速赛车开奖直播官网_set.adoc[`<boost/unordered/unordered_node_set.hpp>`]

namespace boost {
namespace unordered {

  template<class Key,
           class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<Key>>
  class unordered_node_set {
  public:
    // 类型定义
    using key_type             = Key;
    using value_type           = Key;
极速赛车开奖直播官网    using init_type            = Key;
    using hasher               = Hash;
    using key_equal            = Pred;
    using allocator_type       = Allocator;
    using pointer              = typename std::allocator_traits<Allocator>::pointer;
    using const_pointer        = typename std::allocator_traits<Allocator>::const_pointer;
    using reference            = value_type&;
    using const_reference      = const value_type&;
    using size_type            = std::size_t;
    using difference_type      = std::ptrdiff_t;

    using iterator             = _由实现定义_;
    using const_iterator       = _由实现定义_;

    using node_type            = _由实现定义_;
    using insert_return_type   = _由实现定义_;

    using stats                = xref:reference/stats.adoc#stats_stats_type[__统计类型__]; // 若启用了统计功能

    // 构造/复制/销毁
    xref:#unordered_node_set_default_constructor[unordered_node_set]();
    explicit xref:#unordered_node_set_bucket_count_constructor[unordered_node_set](size_type n,
                                const hasher& hf = hasher(),
                                const key_equal& eql = key_equal(),
                                const allocator_type& a = allocator_type());
    template<class InputIterator>
      xref:#unordered_node_set_iterator_range_constructor[unordered_node_set](InputIterator f, InputIterator l,
                         size_type n = _由实现定义_,
                         const hasher& h极速赛车开奖直播官网f = hasher(),
                         const key_equal& eql = key_equal(),
                         const allocator_type& a = allocator_type());
    xref:#unordered_node_set_copy_constructor[unordered_node_set](const unordered_node_set& other);
    xref:#unordered_node_set_move_constructor[unordered_node_set](unordered_node_set&& other);
    template<class InputIterator>
      xref:#unordered_node_set_iterator_range_constructor_with_allocator[unordered_node_set](InputIterator f, InputIterator l, const allocator_type& a);
    explicit xref:#unordered_node_set_allocator_constructor[unordered_node_set](const Allocator& a);
    xref:#unordered_node_set_copy_constructor_with_allocator[unordered_node_set](const unordered_node_set& other, const Allocator& a);
    xref:#unordered_node_set_move_constructor_with_allocator[unordered_node_set](unordered_node_set&& other, const Allocator& a);
    xref:#unordered_node_set_move_constructor_from_concurrent_node_set[unordered_node_set](concurrent_node_set<Key, Hash, Pred, Allocator>&& other);
    xref:#unordered_node_set_initializer_list_constructor[unordered_node_set](std::initializer_list<value_type> il,
                       size_type n = _由实现定义_
                       const hasher& hf = hasher(),
                       const key_equal& eql = key_equal(),
                       const allocator_type& a = allocator_type());
    xref:#unordered_node_set_bucket_count_constructor_with_allocator[unordered_node_set](size_type n, const allocator_type& a);
    xref:#unordered_node_set_bucket_count_constructor_with_hasher_and_allocator[unordered_node_set](size_type n, const hasher& hf, const allocator_type& a);
    template<class InputIterator>
      xref:#unordered_node_set_iterator_range_constructor_with_bucket_count_and_allocator[unordered_node_set](InputIterator f, InputIterator l, size_type n, const allocator_type& a);
    template<class InputIterator>
      xref:#unordered_node_set_iterator_range_constructor_with_bucket_count_and_hasher[unordered_node_set](InputIterator f, InputIterator l, size_type n, const hasher& hf,
                         const allocator_type& a);
    xref:#unordered_node_set_initializer_list_constructor_with_allocator[unordered_node_set](std::initializer_list<value_type> il, const allocator_type& a);
    xref:#unordered_node_set_initializer_list_constructor_with_bucket_count_and_allocator[unordered_node_set](std::initializer_list<value_type> il, size_type n,
                       const allocator_type& a);
    xref:#unordered_node_set_initializer_list_constructor_with_bucket_count_and_hasher_and_allocator[unordered_node_set](std::initializer_list<value_type> il, size_type n, const hasher& hf,
                       const allocator_type& a);
    xref:#unordered_node_set_destructor[~unordered_node_set]();
    unordered_node_set& xref:#unordered_node_set_copy_assignment[operator++=++](const unordered_node_set& other);
    unordered_node_set& xref:#unordered_node_set_move_assignment[operator++=++](unordered_node_set&& other) ++noexcept(
      (boost::allocator_traits<Allocator>::is_always_equal::value ||
       boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value) &&
       std::is_same<pointer, value_type*>::value);++
    unordered_node_set& xref:#unordered_node_set_initializer_list_assignment[operator++=++](std::initializer_list<value_type>);
    allocator_type xref:#unordered_node_set_get_allocator[get_allocator]() const noexcept;

    // 迭代器
    iterator       xref:#unordered_node_set_begin[begin]() noexcept;
    const_iterator xref:#unordered_node_set_begin[begin]() const noexcept;
    iterator       xref:#unordered_node_set_end[end]() noexcept;
    const_iterator xref:#unordered_node_set_end[end]() const noexcept;
    const_iterator xref:#unordered_node_set_cbegin[cbegin]() const noexcept;
    const_iterator xref:#unordered_node_set_cend[cend]() const noexcept;

    // 容量
    ++[[nodiscard]]++ bool xref:#unordered_node_set_empty[empty]() const noexcept;
    size_type xref:#unordered_node_set_size[size]() const noexcept;
    size_type xref:#unordered_node_set_max_size[max_size]() const noexcept;

    // 修改器
    template<class... Args> std::pair<iterator, bool> xref:#unordered_node_set_emplace[emplace](Args&&... args);
    template<class... Args> iterator xref:#unordered_node_set_emplace_hint[emplace_hint](const_iterator position, Args&&... args);
    std::pair<iterator, bool> xref:#unordered_node_set_copy_insert[insert](const value_type& obj);
    std::pair<iterator, bool> xref:#unordered_node_set_move_insert[insert](value_type&& obj);
    template<class K> std::pair<iterator, bool> xref:#unordered_node_set_transparent_insert[insert](K&& k);
    iterator xref:#unordered_node_set_copy_insert_with_hint[insert](const_iterator hint, const value_type& obj);
    iterator xref:#unordered_node_set_move_insert_with_hint[insert](const_iterator hint, value_type&& obj);
    template<class K> iterator xref:#unordered_node_set_transparent_insert_with_hint[insert](const_iterator hint, K&& k);
    template<class InputIterator> void xref:#unordered_node_set_insert_iterator_range[insert](InputIterator first, InputIterator last);
    void xref:#unordered_node_set_insert_initializer_list[insert](std::initializer_list<value_type>);
    insert_return_type xref:#unordered_node_set_insert_node[insert](node_type&& nh);
    iterator xref:#unordered_node_set_insert_node_with_hint[insert](const_iterator hint, node_type&& nh);

    _可转换为迭代器的类型_     xref:#unordered_node_set_erase_by_position[erase](iterator position);
    _可转换为迭代器的类型_     xref:#unordered_node_set_erase_by_position[erase](const_iterator position);
    size_type                   xref:#unordered_node_set_erase_by_key[erase](const key_type& k);
    template<class K> size_type xref:#unordered_node_set_erase_by_key[erase](K&& k);
    iterator  xref:#unordered_node_set_erase_range[erase](const_iterator first, const_iterator last);
    void      xref:#unordered_node_set_swap[swap](unordered_node_set& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
               boost::allocator_traits<Allocator>::propagate_on_container_swap::value);
    node_type xref:#unordered_node_set_extract_by_position[extract](const_iterator position);
    node_type xref:#unordered_node_set_extract_by_key[extract](const key_type& key);
    template<class K> node_type xref:#unordered_node_set_extract_by_key[extract](K&& key);
    init_type xref:#unordered_node_set_pull[pull](const_iterator position);
    void      xref:#unordered_node_set_clear[clear]() noexcept;

    template<class H2, class P2>
      void xref:#unordered_node_set_merge[merge](unordered_node_set<Key, T, H2, P2, Allocator>& source);
    template<class H2, class P2>
      void xref:#unordered_node_set_merge[merge](unordered_node_set<Key, T, H2, P2, Allocator>&& source);

    // 观察器
    hasher xref:#unordered_node_set_hash_function[hash_function]() const;
    key_equal xref:#unordered_node_set_key_eq[key_eq]() const;

    // 集合操作
    iterator         xref:#unordered_node_set_find[极速赛车开奖直播官网find](const key_type& k);
    const_iterator   xref:#unordered_node_set_find[find](const key_type& k) const;
    template<class K>
      iterator       xref:#unordered_node_set_find[find](const K& k);
    template<class K>
      const_iterator xref:#unordered_node_set_find[find](const K& k) const;
    size_type        xref:#unordered_node_set_count[count](const key_type& k) const;
    template<class K>
      size_type      xref:#unordered_node_set_count[count](const K& k) const;
    bool             xref:#unordered_node_set_contains[contains](const key_type& k) const;
    template<class K>
      bool           xref:#unordered_node_set_contains[contains](const K& k) const;
    std::pair<iterator, iterator>               xref:#unordered_node_set_equal_range[equal_range](const key_type& k);
    std::pair<const_iterator, const_iterator>   xref:#unordered_node_set_equal_range[equal_range](const key_type& k) const;
    template<class K>
      std::pair<iterator, iterator>             xref:#unordered_node_set_equal_range[equal_range](const K& k);
    template<class K>
      std::pair<const_iterator, const_iterator> xref:#unordered_node_set_equal_range[equal_range](const K& k) const;

    // 桶接口
    size_type xref:#unordered_node_set_bucket_count[bucket_count]() const noexcept;

    // 哈希策略
    float xref:#unordered_node_set_load_factor[load_factor]() const noexcept;
    float xref:#unordered_node_set_max_load_factor[max_load_factor]() const noexcept;
    void xref:#unordered_node_set_set_max_load_factor[max_load_factor](float z);
    size_type xref:#unordered_node_set_max_load[max_load]() const noexcept;
    void xref:#unordered_node_set_rehash[rehash](size_type n);
    void xref:#unordered_node_set_reserve[reserve](size_type n);

    // 统计（若启用）
    stats xref:#unordered_node_set_get_stats[get_stats]() const;
    void xref:#unordered_node_set_reset_stats[reset_stats]() noexcept;
  };

  // 推导指引
  template<class InputIterator,
           class Hash = boost::hash<xref:#unordered_node_set_iter_value_type[__迭代器值类型__]<InputIterator>>,
           class Pred = std::equal_to<xref:#unordered_node_set_iter_value_type[__迭代器值类型__]<InputIterator>>,
           class Allocator = std::allocator<xref:#unordered_node_set_iter_value_type[__迭代器值类型__]<InputIterator>>>
    unordered_node_set(InputIterator, InputIterator, typename xref:#unordered_node_set_deduction_guides[__见下文__]::size_type = xref:#unordered_node_set_deduction_guides[__见下文__],
                       Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> unordered_node_set<xref:#unordered_node_set_iter_value_type[__迭代器值类型__]<InputIterator>, Hash, Pred, Allocator>;

  template<class T, class Hash = boost::hash<T>, class Pred = std::equal_to<T>,
           class Allocator = std::allocator<T>>
    unordered_node_set(std::initializer_list<T>, typename xref:#unordered_node_set_deduction_guides[__见下文__]::size_type = xref:#unordered_node_set_deduction_guides[__见下文__],
                       Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> unordered_node_set<T, Hash, Pred, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_node_set(InputIterator, InputIterator, typename xref:#unordered_node_set_deduction_guides[__见下文__]::size_type, Allocator)
      -> unordered_node_set<xref:#unordered_node_set_iter_value_type[__迭代器值类型__]<InputIterator>,
                            boost::hash<xref:#unordered_node_set_iter_value_type[__迭代器值类型__]<InputIterator>>,
                            std::equal_to<xref:#unordered_node_set_iter_value_type[__迭代器值类型__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_node_set(InputIterator, InputIterator, Allocator)
      -> unordered_node_set<xref:#unordered_node_set_iter_value_type[__迭代器值类型__]<InputIterator>,
                            boost::hash<xref:#unordered_node_set_iter_value_type[__迭代器值类型__]<InputIterator>>,
                            std::equal_to<xref:#unordered_node_set_iter_value_type[__迭代器值类型__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Hash, class Allocator>
    unordered_node_set(InputIterator, InputIterator, typename xref:#unordered_node_set_deduction_guides[__见下文__]::size_type, Hash,
                       Allocator)
      -> unordered_node_set<xref:#unordered_node_set_iter_value_type[__迭代器值类型__]<InputIterator>, Hash,
                            std::equal_to<xref:#unordered_node_set_iter_value_type[__迭代器值类型__]<InputIterator>>, Allocator>;

  template<class T, class Allocator>
    unordered_node_set(std::initializer_list<T>, typename xref:#unordered_node_set_deduction_guides[__见下文__]::size_type, Allocator)
      -> unordered_node_set<T, boost::hash<T>, std::equal_to<T>, Allocator>;

  template<class T, class Allocator>
    unordered_node_set(std::initializer_list<T>, Allocator)
      -> unordered_node_set<T, boost::hash<T>, std::equal_to<T>, Allocator>;

  template<class T, class Hash, class Allocator>
    unordered_node_set(std::initializer_list<T>, typename xref:#unordered_node_set_deduction_guides[__见下文__]::size_type, Hash, Allocator)
      -> unordered_node_set<T, Hash, std::equal_to<T>, Allocator>;

} // namespace unordered
} // namespace boost
-----

---

=== 描述

*模板参数*

[cols="1,1"]
|===

|_Key_
|`Key` 必须满足从容器中可擦除（Erasable）的要求。

|_Hash_
|一元函数对象类型，用作 `Key` 的哈希函数。它接受一个类型为 `Key` 的参数，并返回一个类型为 `std::size_t` 的值。

|_Pred_
|二元函数对象，用于在 `Key` 类型的值上建立等价关系。它接受两个类型为 `Key` 的参数，并返回一个类型为 `bool` 的值。

|_Allocator_
|分配器，其值类型与容器的值类型相同。
支持使用花式指针（fancy pointers）的分配器。

|===

容器的元素节点保存在内部的桶数组（bucket array）中。节点被插入到由其元素哈希码确定的桶中，但如果桶已被占用（发生冲突），则使用原始位置附近的一个可用桶。

桶数组的大小可通过调用 `insert`/`emplace` 或调用 `rehash`/`reserve` 自动增加。容器的负载因子（元素数量除以桶数量）永远不会大于 `max_load_factor()`，除非在小型容器中实现可能允许更高的负载。

如果 `link:../../../../../container_hash/doc/html/hash.html#ref_hash_is_avalanchinghash[hash_is_avalanching]<Hash>::value` 为 `true`，则直接使用哈希函数；否则，会添加一个位混合后处理阶段以提高哈希质量，但会增加额外的计算成本。

---

=== 配置宏

==== `BOOST_UNORDERED_ENABLE_STATS`

全局定义此宏以启用容器的统计计算功能。注意：此选项会降低许多操作的总体性能。

---

=== 类型定义

[source, c++, subs=+quotes]
----
typedef _由实现定义_ iterator;
----

值类型为 `value_type` 的常量迭代器。

迭代器类别至少为前向迭代器。

可转换为 `const_iterator`。

---

[source, c++, subs=+quotes]
----
typedef _由实现定义_ const_iterator;
----

值类型为 `value_type` 的常量迭代器。

迭代器类别至少为前向迭代器。

---

[source, c++, subs=+quotes]
----
typedef _由实现定义_ node_type;
----

用于保存提取的容器元素的类，建模为节点句柄（NodeHandle）。

---

[source, c++, subs=+quotes]
----
typedef _由实现定义_ insert_return_type;
----

内部类模板的特化：

[source, c++, subs=+quotes]
----
template<class Iterator, class NodeType>
struct _插入返回类型_ // 名称仅用于说明
{
  Iterator position;
  bool     inserted;
  NodeType node;
};
----

其中 `Iterator` = `iterator` 且 `NodeType` = `node_type`。

---

=== 构造函数

==== 默认构造函数
```c++

unordered_node_set();

```

使用 `hasher()` 作为哈希函数、`key_equal()` 作为键相等谓词、`allocator_type()` 作为分配器构造空容器。

[horizontal]
后置条件：;; `size() == 0`
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足可默认构造（DefaultConstructible）要求。

---

==== 桶数量构造函数
```c++

explicit unordered_node_set(size_type n,
                            const hasher& hf = hasher(),
                            const key_equal& eql = key_equal(),
                            const allocator_type& a = allocator_type());

```

构造至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、`eql` 作为键相等谓词、`a` 作为分配器。

[horizontal]
后置条件：;; `size() == 0`
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足可默认构造（DefaultConstructible）要求。

---

==== 迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  unordered_node_set(InputIterator f, InputIterator l,
                     size_type n = _由实现定义_,
                     const hasher& hf = hasher(),
                     const key_equal& eql = key_equal(),
                     const allocator极速赛车开奖直播官网_type& a = allocator_type());
----

构造至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、`eql` 作为键相等谓词、`a` 作为分配器，并将 `[f, l)` 范围内的元素插入其中。

[horizontal]
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足可默认构造（DefaultConstructible）要求。

---

==== 复制构造函数
```c++

unordered_node_set(unordered_node_set const& other);

```

复制构造函数。复制所含元素、哈希函数、谓词及分配器。

若 `Allocator::select_on_container_copy_construction` 存在且签名正确，则分配器将由此方法的结果构造。

[horizontal]
要求：;; `value_type` 需满足可复制构造要求

---

==== 移动构造函数
```c++

unordered_node_set(unordered_node_set&& other);

```

移动构造函数。`other` 的内部桶数组直接转移至新容器。哈希函数、谓词和分配器从 `other` 移动构造。若启用了统计功能，则转移 `other` 的内部统计信息并调用 `other.reset_stats()`。

---

==== 带分配器的迭代器范围构造函数
```c++

template<class InputIterator>
  unordered_node_set(InputIterator f, InputIterator l, const allocator_type& a);

```

使用 `a` 作为分配器构造空容器，采用默认哈希函数和键相等谓词，并将 `[f, l)` 范围内的元素插入其中。

[horizontal]
要求：;; `hasher`、`key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

==== 分配器构造函数
```c++

explicit unordered_node_set(Allocator const& a);

```

使用分配器 `a` 构造空容器。

---

==== 带分配器的复制构造函数
```c++

unordered_node_set(unordered_node_set const& other, Allocator const& a);

```

构造容器，复制 `other` 所含元素、哈希函数及谓词，但使用分配器 `a`。

---

==== 带分配器的移动构造函数
```c++

unordered_node_set(unordered_node_set&& other, Allocator const& a);

```

若 `a == other.get_allocator()`，则 `other` 的元素节点直接转移至新容器；否则，元素从 `other` 移动构造。哈希函数和谓词从 `other` 移动构造，分配器从 `a` 复制构造。若启用了统计功能，当且仅当 `a == other.get_allocator()` 时转移 `other` 的内部统计信息，并始终调用 `other.reset_stats()`。

---

==== 从 concurrent_node_set 的移动构造函数

```c++

unordered_node_set(concurrent_node_set<Key, Hash, Pred, Allocator>&& other);

```

从 xref:#concurrent_node_set[`concurrent_node_set`] 移动构造。`other` 的内部桶数组直接转移至新容器。哈希函数、谓词和分配器从 `other` 移动构造。若启用了统计功能，则转移 `other` 的内部统计信息并调用 `other.reset_stats()`。

[horizontal]
复杂度：;; 常数时间。
并发性：;; 在 `other` 上阻塞。

---

==== 初始化列表构造函数
[source, c++, subs="+quotes"]
----
unordered_node_set(std::initializer_list<value_type> il,
              size_type n = _由实现定义_
              const hasher& hf = hasher(),
              const key_equal& eql = key_equal(),
              const allocator_type& a = allocator_type());
----

构造至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、`eql` 作为键相等谓词、`a` 作为分配器，并将 `il` 中的元素插入其中。

[horizontal]
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足可默认构造（DefaultConstructible）要求。

---

==== 带分配器的桶数量构造函数
```c++

unordered_node_set(size_type n, allocator_type const& a);

```

构造至少包含 `n` 个桶的空容器，使用默认哈希函数和键相等谓词，以及 `a` 作为分配器。

[horizontal]
后置条件：;; `size() == 0`
要求：;; `hasher` 和 `key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

==== 带哈希函数和分配器的桶数量构造函数
```c++

unordered_node_set(size_type n, hasher const& hf, allocator_type const&极速赛车开奖直播官网 a);

```

构造至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、默认键相等谓词以及 `a` 作为分配器。

[horizontal]
后置条件：;; `size() == 0`
要求：;; `key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

==== 带桶数量和分配器的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  unordered_node_set(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
----

构造至少包含 `n` 个桶的空容器，使用 `a` 作为分配器及默认哈希函数和键相等谓词，并将 `[f, l)` 范围内的元素插入其中。

[horizontal]
要求：;; `hasher`、`key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

==== 带桶数量和哈希函数的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
    template<class InputIterator>
      unordered_node_set(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                         const allocator_type& a);
----

构造至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、`a` 作为分配器、默认键相等谓词，并将 `[f, l)` 范围内的元素插入其中。

[horizontal]
要求：;; `key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

==== 带分配器的初始化列表构造函数

```c++

unordered_node_set(std::initializer_list<value_type> il, const allocator_type& a);

```

使用 `a` 及默认哈希函数和键相等谓词构造空容器，并将 `il` 中的元素插入其中。

[horizontal]
要求：;; `hasher` 和 `key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

==== 带桶数量和分配器的初始化列表构造函数

```c++

unordered_node_set(std::initializer_list<value_type> il, size_type n, const allocator_type& a);

```

构造至少包含 `n` 个桶的空容器，使用 `a` 及默认哈希函数和键相等谓词，并将 `il` 中的元素插入其中。

[horizontal]
要求：;; `hasher` 和 `key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

==== 带桶数量、哈希函数和分配器的初始化列表构造函数

```c++

unordered_node_set(std::initializer_list<value_type> il, size_type n, const hasher& hf,
                   const allocator_type& a);

```

构造至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、`a` 作为分配器、默认键相等谓词，并将 `il` 中的元素插入其中。

[horizontal]
要求：;; `key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

=== 析构函数

```c++

~unordered_node_set();

```

[horizontal]
注意：;; 析构函数作用于每个元素，并释放所有内存

---

=== 赋值

==== 复制赋值

```c++

unordered_node_set& operator=(unordered_node_set const& other);

```

赋值运算符。销毁先前存在的元素，从 `other` 复制赋值哈希函数和谓词，若 `Alloc::propagate_on_container_copy_assignment` 存在且 `Alloc::propagate_on_container_copy_assignment::value` 为 `true`，则从 `other` 复制赋值分配器，最后插入 `other` 元素的副本。

[horizontal]
要求：;; `value_type` 需满足可复制插入（CopyInsertable）要求

---

==== 移动赋值
```c++

unordered_node_set& operator=(unordered_node_set&& other)
  noexcept((boost::allocator_traits<Allocator>::is_always_equal::value ||
            boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value) &&
            std::is_same<pointer, value_type*>::value);

```
移动赋值运算符。销毁先前存在的元素，交换 `other` 的哈希函数和谓词，
若 `Alloc::propagate_on_container_move_assignment` 存在且 `Alloc::propagate_on_container_move_assignment::value` 为 `true`，则从 `other` 移动赋值分配器。
若此时分配器等于 `other.get_allocator()`，则 `other` 的内部桶数组直接转移至新容器；
否则，插入 `other` 元素的移动构造副本。
若启用了统计功能，当且仅当最终分配器等于 `other.get_allocator()` 时转移 `other` 的内部统计信息，
并始终调用 `other.reset_stats()`。

---

==== 初始化列表赋值
```c++

unordered_node_set& operator=(std::initializer_list<value_type> il);

```

从初始化列表中的值赋值。销毁所有先前存在的元素。

[horizontal]
要求：;; `value_type` 需满足可复制插入（CopyInsertable）要求

=== 迭代器

==== begin
```c++

iterator begin() noexcept; const_iterator begin() const noexcept;

```

[horizontal]
返回：;; 一个指向容器首元素的迭代器；若容器为空，则返回容器的尾后值。
复杂度：;; O(`bucket_count()`)

---

==== end
```c++

iterator end() noexcept; const_iterator end() const noexcept;

```

[horizontal]
返回：;; 一个指向容器尾后值的迭代器。

---

==== cbegin
```c++

const_iterator cbegin() const noexcept;

```

[horizontal]
返回：;; 一个指向容器首元素的 `const_iterator`；若容器为空，则返回容器的尾后值。
复杂度：;; O(`bucket_count()`)

---

==== cend
```c++

const_iterator cend() const noexcept;

```

[horizontal]
返回：;; 一个指向容器尾后值的 `const_iterator`。

---

=== 大小与容量

==== empty

```c++

[[nodiscard]] bool empty() const noexcept;

```

[horizontal]
返回：;; `size() == 0`

---

==== size

```c++

size_type size() const noexcept;

```

[horizontal]
返回：;; `std::distance(begin(), end())`

---

==== max_size

```c++

size_type max_size() const noexcept;

```

[horizontal]
返回：;; 容器可能的最大 `size()`。

---

=== 修改器

==== emplace
```c++

template<class... Args> std::pair<iterator, bool> emplace(Args&&... args);

```

当且仅当容器中不存在等价键时，插入一个由参数 `args` 构造的对象。

[horizontal]
要求：;; `value_type` 需可从 `args` 构造。
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 可能使迭代器失效，但仅当插入导致负载超过最大负载时发生。

---

==== emplace_hint
```c++

template<class... Args> iterator emplace_hint(const_iterator position, Args&&... args);

```

当且仅当容器中不存在等价键时，插入一个由参数 `args` 构造的对象。

`position` 是插入位置的提示。本实现忽略此提示。

[horizontal]
要求：;; `value_type` 需可从 `args` 构造。
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 可能使迭代器失效，但仅当插入导致负载超过最大负载时发生。

---

==== 复制插入
```c++

std::pair极速赛车开奖直播官网<iterator, bool> insert(const value_type& obj);

```

当且仅当容器中不存在等价键时，插入 `obj`。

[horizontal]
要求：;; `value_type` 需满足可复制插入（CopyInsertable）要求。
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 可能使迭代器失效，但仅当插入导致负载超过最大负载时发生。

---

==== 移动插入
```c++

std::pair<iterator, bool> insert(value_type&& obj);

```

当且仅当容器中不存在等价键时，插入 `obj`。

[horizontal]
要求：;; `value_type` 需满足可移动插入（MoveInsertable）要求。
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 可能使迭代器失效，但仅当插入导致负载超过最大负载时发生。

---

==== 透明插入
```c++

template<class K> std::pair<iterator, bool> insert(K&& k);

```

当且仅当容器中不存在等价键时，插入一个由 `std::forward<K>(k)` 构造的元素。

[horizontal]
要求：;; `value_type` 需可从 `k` 原位构造（EmplaceConstructible）。
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 可能使迭代器失效，但仅当插入导致负载超过最大负载时发生。
+
仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义，且 `iterator` 与 `const_iterator` 均不能从 `K` 隐式转换时，此重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== 带提示的复制插入
```c++

iterator insert(const_iterator hint, const value_type& obj);

``` 当且仅当容器中不存在等价键时，插入 `obj`。

`hint` 是插入位置的提示。本实现忽略此提示。

[horizontal]
要求：;; `value_type` 需满足可复制插入（CopyInsertable）要求。
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 可能使迭代器失效，但仅当插入导致负载超过最大负载时发生。

---

==== 带提示的移动插入
```c++

iterator insert(const_iterator hint, value_type&& obj);

```

当且仅当容器中不存在等价键时，插入 `obj`。

`hint` 是插入位置的提示。本实现忽略此提示。

[horizontal]
要求：;; `value_type` 需满足可移动插入（MoveInsertable）要求。
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 可能使迭代器失效，但仅当插入导致负载超过最大负载时发生。

---

==== 带提示的透明插入
```c++

template<class K> std::pair<iterator, bool> insert(const_iterator hint, K&& k);

```

当且仅当容器中不存在等价键时，插入一个由 `std::forward<K>(k)` 构造的元素。

`hint` 是插入位置的提示。本实现忽略此提示。

[horizontal]
要求：;; `value_type` 需可从 `k` 原位构造（EmplaceConstructible）。
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 可能使迭代器失效，但仅当插入导致负载超过最大负载时发生。
+
仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义，且 `iterator` 与 `const_iterator` 均不能从 `K` 隐式转换时，此重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== 插入迭代器范围
```c++

template<class InputIterator> void insert(InputIterator first, InputIterator last);

```

将元素范围插入容器。当且仅当容器中不存在等价键时插入元素。

[horizontal]
要求：;; `value_type` 需可从 `*first` 原位构造（EmplaceConstructible）到容器中。
抛出：;; 插入单个元素时，若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 可能使迭代器失效，但仅当插入导致负载超过最大负载时发生。

---

==== 插入初始化列表
```c++

void insert(std::initializer_list<value_type>);

```

将元素范围插入容器。当且仅当容器中不存在等价键时插入元素。

[horizontal]
要求：;; `value_type` 需满足可复制插入（CopyInsertable）到容器的要求。
抛出：;; 插入单个元素时，若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 可能使迭代器失效，但仅当插入导致负载超过最大负载时发生。

---

==== 插入节点
```c++

insert_return_type insert(node_type&& nh);

```

若 `nh` 非空，当且仅当容器中不存在与 `nh.value()` 等价的键时，插入关联元素。函数返回时 `nh` 为空。

[horizontal]
返回：;; 从 `position`、`inserted` 和 `node` 构造的 `insert_return_type` 对象：
* 若 `nh` 为空，则 `inserted` 为 `false`，`position` 为 `end()`，且 `node` 为空。
* 若插入发生，则 `inserted` 为 `true`，`position` 指向插入的元素，且 `node` 为空。
* 若插入失败，则 `inserted` 为 `false`，`node` 保留 `nh` 的原始值，且 `position` 指向与 `nh.value()` 等价的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 若 `nh` 非空且其分配器与容器分配器不同，则行为未定义。

---

==== 带提示的节点插入
```c++

iterator insert(const_iterator hint, node_type&& nh);

```

若 `nh` 非空，当且仅当容器中不存在与 `nh.value()` 等价的键时，插入关联元素。若插入发生，则 `nh` 变为空；否则不变。

`hint` 是插入位置的提示。本实现忽略此提示。

[horizontal]
返回：;; 若 `nh` 为空，则返回的迭代器为 `end()`。若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 若 `nh` 非空且其分配器与容器分配器不同，则行为未定义。

---

==== 按位置擦除

[source, c++, subs=+quotes]
----
_可转换为迭代器的类型_ erase(iterator position);
_可转换为迭代器的类型_ erase(const_iterator position);
----

擦除 `position` 指向的元素。

[horizontal]
返回：;; 一个不透明对象，可隐式转换为擦除前紧邻 `position` 之后位置的 `iterator` 或 `const_iterator`。
抛出：;; 不抛出异常。
注意：;; 返回的不透明对象必须立即丢弃或转换为 `iterator` 或 `const_iterator`。

---

==== 按键擦除
```c++

size_type erase(const key_type& k); template<class K> size_type erase(K&& k);

```

擦除所有键等价于 `k` 的元素。

[horizontal]
返回：;; 擦除的元素数量。
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才会抛出异常。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义，且 `iterator` 与 `const_iterator` 均不能从 `K` 隐式转换时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== 范围擦除

```c++

iterator erase(const_iterator first, const_iterator last);

```

擦除从 `first` 到 `last` 范围内的元素。

[horizontal]
返回：;; 指向被擦除元素之后位置的迭代器——即 `last`。
抛出：;; 本实现中不抛出异常（既不调用 `hasher` 也不调用 `key_equal` 对象）。

---

==== swap
```c++

void swap(unordered_node_set& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
           boost::allocator_traits<Allocator>::propagate_on_container_swap::value);

```

交换容器与参数的内容。

若声明了 `Allocator::propagate_on_container_swap` 且其值为 `true`，则交换容器的分配器；否则，与不同分配器的容器交换将导致未定义行为。

[horizontal]
抛出：;; 除非 `key_equal` 或 `hasher` 在交换时抛出异常，否则不抛出异常。

---

==== 按位置提取
```c++

node_type extract(const_iterator position);

```

提取 `position` 指向的元素。

[horizontal]
返回：;; 一个包含被提取元素的 `node_type` 对象。
抛出：;; 不抛出异常。

---

==== 按键提取
```c++

node_type extract(const key_type& k); template<class K> node_type extract(K&& k);

```

提取键等价于 `k` 的元素（若存在）。

[horizontal]
返回：;; 包含被提取元素的 `node_type` 对象；若无元素被提取则为空。
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才会抛出异常。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== pull
```c++

init_type pull(const_iterator position);

```

从 `position` 指向的元素移动构造 `init_value` 类型对象 `x`，擦除该元素并返回 `x`。

---

==== clear
```c++

void clear() noexcept;

```

擦除容器中所有元素。

[horizontal]
后置条件：;; `size() == 0`, `max_load() >= max_load_factor() * bucket_count()`

---

==== merge
```c++

template<class H2, class P2>
  void merge(unordered_node_set<Key, T, H2, P2, Allocator>& source);
template<class H2, class P2>
  void merge(unordered_node_set<Key, T, H2, P2, Allocator>&& source);

```

从 `source` 转移所有键在 `*this` 中不存在的元素节点。

[horizontal]
要求：;; `this->get_allocator() == source.get_allocator()`。
注意：;; 使指向被转移元素的迭代器失效。若 `*this` 的最终大小大于其原始最大负载，则使与 `*this` 关联的所有迭代器失效。

---

=== 观察器

==== get_allocator
```

allocator_type get_allocator() const noexcept;

```

[horizontal]
返回：;; 容器的分配器。

---

==== hash_function
```

hasher hash_function() const;

```

[horizontal]
返回：;; 容器的哈希函数。

---

==== key_eq
```

key_equal key_eq() const;

```

[horizontal]
返回：;; 容器的键相等谓词

---

=== 查找

==== find
```c++

iterator         find(const key_type& k);
const_iterator   find(const key_type& k) const;
template<class K>
  iterator       find(const K& k);

```

[horizontal]
返回：;; 指向键等价于 `k` 的元素的迭代器；若无此元素则为 `end()`。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== count
```c++

size_type        count(const key_type& k) const;
template<class K>
  size_type      count(const K&极速赛车开奖直播官网 k) const;

```

[horizontal]
返回：;; 键等价于 `k` 的元素数量。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== contains
```c++

bool             contains(const key_type& k) const;
template<class K>
  bool           contains(const K& k) const;

```

[horizontal]
返回：;; 指示容器中是否存在键等于 `key` 的元素的布尔值
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== equal_range
```c++

std::pair<iterator, iterator>               equal_range(const key_type& k);
std::pair<const_iterator, const_iterator>   equal_range(const key_type& k) const;
template<class K>
  std::pair<iterator, iterator>             equal_range(const K& k);
template<class K>
  std::pair<const_iterator, const_iterator> equal_range(const K& k) const;

```

[horizontal]
返回：;; 包含所有键等价于 `k` 的元素的范围。若容器不包含此类元素，则返回 `std::make_pair(b.end(), b.end())`。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

=== 桶接口

==== bucket_count
```c++

size_type bucket_count() const noexcept;

```

[horizontal]
返回：;; 桶数组的大小。

---

=== 哈希策略

==== load_factor
```c++

float load_factor() const noexcept;

```

[horizontal]
返回：;; `static_cast<float>(size())/static_cast<float>(bucket_count())`，若 `bucket_count() == 0` 则为 `0`。

---

==== max_load_factor

```c++

float max_load_factor() const noexcept;

```

[horizontal]
返回：;; 返回容器的最大负载因子。

---

==== 设置最大负载因子
```c++

void max_load_factor(float z);

```

[horizontal]
效果：;; 无操作（因用户无权更改此参数）。保留此函数以保持与 `boost::unordered_set` 的兼容性。

---


==== max_load

```c++

size_type max_load() const noexcept;

```

[horizontal]
返回：;; 在不再擦除元素的前提下，容器无需重哈希所能容纳的最大元素数量。
注意：;; 构造、重哈希或清空后，容器的最大负载至少为 `max_load_factor() * bucket_count()`。在高负载条件下擦除元素时，此数值可能减少。

---

==== rehash
```c++

void rehash(size_type n);

```

必要时更改桶数组的大小，使桶数量至少为 `n` 且负载因子小于等于最大负载因子。此操作将根据情况增加或减少容器的 `bucket_count()`。

当 `size() == 0` 时，`rehash(0)` 将释放底层桶数组。若提供的分配器使用花式指针，则随后执行默认分配。

使迭代器失效并改变元素顺序。

[horizontal]
抛出：;; 若抛出异常（除非由容器的哈希函数或比较函数抛出），则该函数无任何效果。

---

==== reserve
```c++

void reserve(size_type n);

```

等价于 `a.rehash(ceil(n / a.max_load_factor()))`。

与 `rehash` 类似，此函数可用于增加或减少容器中的桶数量。

使迭代器失效并改变元素顺序。

[horizontal]
抛出：;; 若抛出异常（除非由容器的哈希函数或比较函数抛出），则该函数无任何效果。

---

=== 统计

==== get_stats
```c++

stats get_stats() const;

```

[horizontal]
返回：;; 容器迄今为止执行的插入和查找操作的统计描述。
注意：;; 仅当启用了统计计算功能时可用。

---

==== reset_stats
```c++

void reset_stats() noexcept;

```

[horizontal]
效果：;; 将容器维护的内部统计信息重置为零。
注意：;; 仅当启用了统计计算功能时可用。

---

=== 推导指引
若满足以下任意条件，则推导指引不参与重载决议：

  - 具有 `InputIterator` 模板参数，且推导出该参数的类型不符合输入迭代器要求。
  - 具有 `Allocator` 模板参数，且推导出该参数的类型不符合分配器要求。
  - 具有 `Hash` 模板参数，且推导出该参数的类型为整型或符合分配器要求。
  - 具有 `Pred` 模板参数，且推导出该参数的类型符合分配器要求。

推导指引中的 `size_type` 参数类型指向由推导指引推导出的容器类型的 `size_type` 成员类型。其默认值与所选构造函数的默认值一致。

==== __迭代器值类型__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __迭代器值类型__ =
    typename std::iterator_traits<InputIterator>::value_type; // 仅用于说明
-----

=== 相等比较

==== operator==
```c++

template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator==(const unordered_node_set<Key, T, Hash, Pred, Alloc>& x,
                  const unordered_node_set<Key, T, Hash, Pred, Alloc>& y);

```

若 `x.size() == y.size()` 且对于 `x` 中的每个元素，`y` 中均存在相同键的元素且值相等（使用 `operator==` 比较值类型），则返回 `true`。

[horizontal]
注意：;; 若两个容器的相等谓词不等价，则行为未定义。

---

==== operator!=
```c++

template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator!=(const unordered_node_set<Key, T, Hash, Pred, Alloc>& x,
                  const unordered_node_set<Key, T, Hash, Pred, Alloc>& y);

```

若 `x.size() == y.size()` 且对于 `x` 中的每个元素，`y` 中均存在相同键的元素且值相等（使用 `operator==` 比较值类型），则返回 `false`。

[horizontal]
注意：;; 若两个容器的相等谓词不等价，则行为未定义。

=== Swap
```c++

template<class Key, class T, class Hash, class Pred, class Alloc>
  void swap(unordered_node_set<Key, T, Hash, Pred, Alloc>& x,
            unordered_node_set<Key, T, Hash, Pred, Alloc>& y)
    noexcept(noexcept(x.swap(y)));

```

交换 `x` 和 `y` 的内容。

若声明了 `Allocator::propagate_on_container_swap` 且其值为 `true`，则交换容器的分配器；否则，与不同分配器的容器交换将导致未定义行为。

[horizontal]
效果：;; `x.swap(y)`
抛出：;; 除非 `key_equal` 或 `hasher` 在交换时抛出异常，否则不抛出异常。

---

=== erase_if
```c++

template<class K, class T, class H, class P, class A, class Predicate>
  typename unordered_node_set<K, T, H, P, A>::size_type
    erase_if(unordered_node_set<K, T, H, P, A>& c, Predicate pred);

```

遍历容器 `c` 并移除所有满足谓词 `pred` 返回 `true` 的元素。

[horizontal]
返回：;; 被擦除的元素数量。
注意：;; 等价于：
+
```c++

auto original_size = c.size();
for (auto i = c.begin(), last = c.end(); i != last; ) {
  if (pred(*i)) {
    i = c.erase(i);
  } else {
    ++i;
  }
}
return original_size - c.size();

```

=== 序列化

`unordered_node_set` 可通过 link:../../../../../serialization/index.html[Boost.Serialization^] 使用本库提供的 API 进行归档/检索。支持常规归档和 XML 归档。

==== 将 unordered_node_set 保存到归档

将 `unordered_node_set` `x` 的所有元素保存到归档（XML 归档）`ar` 中。

[horizontal]
要求：;; `value_type` 需可序列化（XML 可序列化），且支持 Boost.Serialization 的 `save_construct_data`/`load_construct_data` 协议（由可默认构造类型自动支持）。

---

==== 从归档加载 unordered_node_set

删除 `unordered_node_set` `x` 的所有预先存在的元素，并从归档（XML 归档）`ar` 插入原始 `unordered_node_set` `other` 元素的还原副本（这些元素已保存到 `ar` 读取的存储中）。

[horizontal]
要求：;; `value_type` 需满足可移动插入（MoveInsertable）要求。`x.key_equal()` 在功能上等价于 `other.key_equal()`。

---

==== 将迭代器/常量迭代器保存到归档

将迭代器（常量迭代器）`it` 的位置信息保存到归档（XML 归档）`ar` 中。`it` 可以是 `end()` 迭代器。

[horizontal]
要求：;; `it` 指向的 `unordered_node_set` `x` 先前已保存到 `ar`，且在保存 `x` 与保存 `it` 之间未对 `x` 执行修改操作。

---

==== 从归档加载迭代器/常量迭代器

使迭代器（常量迭代器）`it` 指向原始迭代器（常量迭代器）的还原位置（该位置已保存到归档（XML 归档）`ar` 读取的存储中）。

[horizontal]
要求：;; 若 `x` 是 `it` 指向的 `unordered_node_set`，则在加载 `x` 与加载 `it` 之间未对 `x` 执行修改操作。
