[#unordered_map]
== 类模板 unordered_map

:idprefix: unordered_map_

`boost::unordered_map` — 一种无序关联容器，将唯一键与另一个值关联。

=== 概要

[listing, subs="+macros,+quotes"]
-----
// #include xref:reference/header_unordered_map.adoc[<boost/unordered/unordered_map.hpp>]

namespace boost {
namespace unordered {

  template<class Key,
           class T,
           class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<std::pair<const Key, T>>>
  class unordered_map {
  public:
    // 类型
    using key_type             = Key;
    using mapped_type          = T;
    using value_type           = std::pair<const Key, T>;
    using hasher               = Hash;
    using key_equal            = Pred;
    using allocator_type       = Allocator;
    using pointer              = typename std::allocator_traits<Allocator>::pointer;
    using const_pointer        = typename std::allocator_traits<Allocator>::const_pointer;
    using reference            = value_type&;
    using const_reference      = const value_type&;
    using size_type            = std::size_t;
    using difference_type      = std::ptrdiff_t;

    using iterator             = _实现定义_;
    using const_iterator       = _实现定义_;
    using local_iterator       = _实现定义_;
    using const_local_iterator = _实现定义_;
    using node_type            = _实现定义_;
    using insert_return_type   = _实现定义_;

    // 构造/复制/销毁
    xref:#unordered_map_default_constructor[unordered_map]();
    explicit xref:#unordered_map_bucket_count_constructor[unordered_map](size_type n,
                           const hasher& hf = hasher(),
                           const key_equal& eql = key_equal(),
                           const allocator_type& a = allocator_type());
    template<class InputIterator>
      xref:#unordered_map_iterator_range_constructor[unordered_map](InputIterator f, InputIterator l,
                    size_type n = _实现定义_,
                    const hasher& hf = hasher(),
                    const key_equal& eql = key_equal(),
                    const allocator_type& a = allocator_type());
    xref:#unordered_map_copy_constructor[unordered_map](const unordered_map& other);
    xref:#unordered_map_move_constructor[unordered_map](unordered_map&& other);
    template<class InputIterator>
      xref:#unordered_map_iterator_range_constructor_with_allocator[unordered_map](InputIterator f, InputIterator l, const allocator_type& a);
    explicit xref:#unordered_map_allocator_constructor[unordered_map](const Allocator& a);
    xref:#unordered_map_copy_constructor_with_allocator[unordered_map](const unordered_map& other, const Allocator& a);
    xref:#unordered_map_move_constructor_with_allocator[unordered_map](unordered_map&& other, const Allocator& a);
    xref:#unordered_map_initializer_list_constructor[unordered_map](std::initializer_list<value_type> il,
                  size_type n = _实现定义_
                  const hasher& hf = hasher(),
                  const key_equal& eql = key_equal(),
                  const allocator_type& a = allocator_type());
    xref:#unordered_map_bucket_count_constructor_with_allocator[unordered_map](size_type n, const allocator_type& a);
    xref:#unordered_map_bucket_count_constructor_with_hasher_and_allocator[unordered_map](size_type n, const hasher& hf, const allocator_type& a);
    template<class InputIterator>
      xref:#unordered_map_iterator_range_constructor_with_bucket_count_and_allocator[unordered_map](InputIterator f, InputIterator l, size_type n, const allocator_type& a);
    template<class InputIterator>
      xref:#unordered_map_iterator_range_constructor_with_bucket_count_and_hasher[unordered_map](InputIterator f, InputIterator l, size_type n, const hasher& hf,
                    const allocator_type& a);
    xref:#unordered_map_initializer_list_constructor_with_allocator[unordered_map](std::initializer_list<value_type> il, const allocator_type& a);
    xref:#unordered_map_initializer_list_constructor_with_bucket_count_and_allocator[unordered_map](std::initializer_list<value_type> il, size_type n, const allocator_type& a);
    xref:#unordered_map_initializer_list_constructor_with_bucket_count_and_hasher_and_allocator[unordered_map](std::initializer_list<value_type> il, size_type n, const hasher& hf,
                  const allocator_type& a);
    xref:#unordered_map_destructor[~unordered_map]();
    unordered_map& xref:#unordered_map_copy_assignment[operator++=++](const unordered_map& other);
    unordered_map& xref:#unordered_map_move_assignment[operator++=++](unordered_map&& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
               boost::is_nothrow_move_assignable_v<Hash> &&
               boost::is_nothrow_move_assignable_v<Pred>);
    unordered_map& xref:#unordered_map_initializer_list_assignment[operator++=++](std::initializer_list<value_type>);
    allocator_type xref:#unordered_map_get_allocator[get_allocator]() const noexcept;

    // 迭代器
    iterator       xref:#unordered_map_begin[begin]() noexcept;
    const_iterator xref:#unordered_map_begin[begin]() const noexcept;
    iterator       xref:#unordered_map_end[end]() noexcept;
    const_iterator xref:#unordered_map_end[end]() const noexcept;
    const_iterator xref:#unordered_map_cbegin[cbegin]() const noexcept;
    const_iterator xref:#unordered_map_cend[cend]() const noexcept;

    // 容量
    ++[[nodiscard]]++ bool xref:#unordered_map_empty[empty]() const noexcept;
    size_type xref:#unordered_map_size[size]() const noexcept;
    size_type xref:#unordered_map_max_size[max_size]() const noexcept;

    // 修改器
    template<class... Args> std::pair<iterator, bool> xref:#unordered_map_emplace[emplace](Args&&... args);
    template<class... Args> iterator xref:#unordered_map_emplace_hint[emplace_hint](const_iterator position, Args&&... args);
    std::pair<iterator, bool> xref:#unordered_map_copy_insert[insert](const value_type& obj);
    std::pair<iterator, bool> xref:#unordered_map_move_insert[insert](value_type&& obj);
    template<class P> std::pair<iterator, bool> xref:#unordered_map_emplace_insert[insert](P&& obj);
    iterator       xref:#unordered_map_copy_insert_with_hint[insert](const_iterator hint, const value_type& obj);
    iterator       xref:#unordered_map_move_insert_with_hint[insert](const_iterator hint, value_type&& obj);
    template<class P> iterator xref:#unordered_map_emplace_insert_with_hint[insert](const_iterator hint, P&& obj);
    template<class InputIterator> void xref:#unordered_map_insert_iterator_range[insert](InputIterator first, InputIterator last);
    void xref:#unordered_map_insert_initializer_list[insert](std::initializer_list<value_type>);

    template<class... Args>
      std::pair<iterator, bool> xref:#unordered_map_try_emplace[try_emplace](const key_type& k, Args&&... args);
    template<class... Args>
      std::pair<iterator, bool> xref:#unordered_map_try_emplace[try_emplace](key_type&& k, Args&&... args);
    template<class K, class... Args>
      std::pair<iterator, bool> xref:#unordered_map_try_emplace[try_emplace](K&& k, Args&&... args);
    template<class... Args>
      iterator xref:#unordered_map_try_emplace_with_hint[try_emplace](const_iterator hint, const key_type& k, Args&&... args);
    template<class... Args>
      iterator xref:#unordered_map_try_emplace_with_hint[try_emplace](const_iterator hint, key_type&& k, Args&&... args);
    template<class K, class... Args>
      iterator xref:#unordered_map_try_emplace_with_hint[try_emplace](const_iterator hint, K&& k, Args&&... args);
    template<class M>
      std::pair<iterator, bool> xref:#unordered_map_insert_or_assign[insert_or_assign](const key_type& k, M&& obj);
    template<class M>
      std::pair<iterator, bool> xref:#unordered_map_insert_or_assign[insert_or_assign](key_type&& k, M&& obj);
    template<class K, class M>
      std::pair<iterator, bool> xref:#unordered_map_insert_or_assign[insert_or_assign](K&& k, M&& obj);
    template<class M>
      iterator xref:#unordered_map_insert_or_assign_with_hint[insert_or_assign](const_iterator hint, const key_type& k, M&& obj);
    template<class M>
      iterator xref:#unordered_map_insert_or_assign_with_hint[insert_or_assign](const_iterator hint, key_type&& k, M&& obj);
    template<class K, class M>
      iterator xref:#unordered_map_insert_or_assign_with_hint[insert_or_assign](const_iterator hint, K&& k, M&& obj);

    node_type xref:#unordered_map_extract_by_iterator[extract](const_iterator position);
    node_type xref:#unordered_map_extract_by_key[extract](const key_type& k);
    template<class K> node_type xref:#unordered_map_extract_by_key[extract](K&& k);
    insert_return_type xref:#unordered_map_insert_with_node_handle[insert](node_type&& nh);
    iterator           xref:#unordered_map_insert_with_hint_and_node_handle[insert](const_iterator hint, node_type&& nh);

    iterator  xref:#unordered_map_erase_by_position[erase](iterator position);
    iterator  xref:#unordered_map_erase_by_position[erase](const_iterator position);
    size_type xref:#unordered_map_erase_by_key[erase](const key_type& k);
    template<class K> size_type xref:#unordered_map_erase_by_key[erase](K&& k);
    iterator  xref:#unordered_map_erase_range[erase](const_iterator first, const_iterator last);
    void      xref:#unordered_map_quick_erase[quick_erase](const_iterator position);
    void      xref:#unordered_map_erase_return_void[erase_return_void](const_iterator position);
    void      xref:#unordered_map_swap[swap](unordered_map& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
               boost::is_nothrow_swappable_v<Hash> &&
               boost::is_nothrow_swappable_v<Pred>);
    void      xref:#unordered_map_clear[clear]() noexcept;

    template<class H2, class P2>
      void xref:#unordered_map_merge[merge](unordered_map<Key, T, H2, P2, Allocator>& source);
    template<class H2, class P2>
      void xref:#unordered_map_merge[merge](unordered_map<Key, T, H2, P2, Allocator>&& source);
    template<class H2, class P2>
      void xref:#unordered_map_merge[merge](unordered_multimap<Key, T, H2, P2, Allocator>& source);
    template<class H2, class P2>
      void xref:#unordered_map_merge[merge](unordered_multimap<Key, T, H2, P2, Allocator>&& source);

    // 观察器
    hasher xref:#unordered_map_hash_function[hash_function]() const;
    key_equal xref:#unordered_map_key_eq[key_eq]() const;

    // 映射操作
    iterator         xref:#unordered_map_find[find](const key_type& k);
    const_iterator   xref:#unordered_map_find[find](const key_type& k) const;
    template<class K>
      iterator       xref:#unordered_map_find[find](const K& k);
    template<class K>
      const_iterator xref:#unordered_map_find[find](const K& k) const;
    template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
      iterator       xref:#unordered_map_find[find](CompatibleKey const& k, CompatibleHash const& hash,
                          CompatiblePredicate const& eq);
    template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
      const_iterator xref:#unordered_map_find[find](CompatibleKey const& k, CompatibleHash const& hash,
                          CompatiblePredicate const& eq) const;
    size_type        xref:#unordered_map_count[count](const key_type& k) const;
    template<class K>
      size_type      xref:#unordered_map_count[count](const K& k) const;
    bool             xref:#unordered_map_contains[contains](const key_type& k) const;
    template<class K>
      bool           xref:#unordered_map_contains[contains](const K& k) const;
    std::pair<iterator, iterator>               xref:#unordered_map_equal_range[equal_range](const key_type& k);
    std::pair<const_iterator, const_iterator>   xref:#unordered_map_equal_range[equal_range](const key_type& k) const;
    template<class K>
      std::pair<iterator, iterator>             xref:#unordered_map_equal_range[equal_range](const K& k);
    template<class K>
      std::pair<const_iterator, const_iterator> xref:#unordered_map_equal_range[equal_range](const K& k) const;

    // 元素访问
    mapped_type& xref:#unordered_map_operator[operator[+]+](const key_type& k);
    mapped_type& xref:#unordered_map_operator[operator[+]+](key_type&& k);
    template<class K> mapped_type& xref:#unordered_map_operator[operator[+]+](K&& k);
    mapped_type& xref:#unordered_map_at[at](const key_type& k);
    const mapped_type& xref:#unordered_map_at[at](const key_type& k) const;
    template<class K> mapped_type& xref:#unordered_map_at[at](const K& k);
    template<class K> const mapped_type& xref:#unordered_map_at[at](const K& k) const;

    // 桶接口
    size_type xref:#unordered_map_bucket_count[bucket_count]() const noexcept;
    size_type xref:#unordered_map_max_bucket_count[max_bucket_count]() const noexcept;
    size_type xref:#unordered_map_bucket_size[bucket_size](size_type n) const;
    size_type xref:#unordered_map_bucket[bucket](const key_type& k) const;
    template<class K> size_type xref:#unordered_map_bucket[bucket](const K& k) const;
    local_iterator xref:#unordered_map_begin_2[begin](size_type n);
    const_local_iterator xref:#unordered_map_begin_2[begin](size_type n) const;
    local_iterator xref:#unordered_map_end_2[end](size_type n);
    const_local_iterator xref:#unordered_map_end_2[end](size_type n) const;
    const_local_iterator xref:#unordered_map_cbegin_2[cbegin](size_type n) const;
    const_local_iterator xref:#unordered_map_cend_2[cend](size_type n) const;

    // 哈希策略
    float xref:#unordered_map_load_factor[load_factor]() const noexcept;
    float xref:#unordered_map_max_load_factor[max_load_factor]() const noexcept;
    void xref:#unordered_map_set_max_load_factor[max_load_factor](float z);
    void xref:#unordered_map_rehash[rehash](size_type n);
    void xref:#unordered_map_reserve[reserve](size_type n);
  };

  // 推导指南
  template<class InputIterator,
           class Hash = boost::hash<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>>,
           class Pred = std::equal_to<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>>,
           class Allocator = std::allocator<xref:#unordered_map_iter_to_alloc_type[__iter-to-alloc-type__]<InputIterator>>>
    unordered_map(InputIterator, InputIterator, typename xref:#unordered_map_deduction_guides[__见下文__]::size_type = xref:#unordered_map_deduction_guides[__见下文__],
                  Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> unordered_map<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>, xref:#unordered_map_iter_mapped_type[__iter-mapped-type__]<InputIterator>, Hash, Pred,
                       Allocator>;

  template<class Key, class T, class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<std::pair<const Key, T>>>
    unordered_map(std::initializer_list<std::pair<Key, T>>,
                  typename xref:#unordered_map_deduction_guides[__见下文__]::size_type = xref:#unordered_map_deduction_guides[__见下文__], Hash = Hash(),
                  Pred = Pred(), Allocator = Allocator())
      -> unordered_map<Key, T, Hash, Pred, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_map(InputIterator, InputIterator, typename xref:#unordered_map_deduction_guides[__见下文__]::size_type, Allocator)
      -> unordered_map<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>, xref:#unordered_map_iter_mapped_type[__iter-mapped-type__]<InputIterator>,
                       boost::hash<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>>,
                       std::equal_to<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_map(InputIterator, InputIterator, Allocator)
      -> unordered_map<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>, xref:#unordered_map_iter_mapped_type[__iter-mapped-type__]<InputIterator>,
                       boost::hash<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>>,
                       std::equal_to<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>>, Allocator>;

  template<class InputIterator, class Hash, class Allocator>
    unordered_map(InputIterator, InputIterator, typename xref:#unordered_map_deduction_guides[__见下文__]::size_type, Hash, Allocator)
      -> unordered_map<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>, xref:#unordered_map_iter_mapped_type[__iter-mapped-type__]<InputIterator>, Hash,
                       std::equal_to<xref:#unordered_map_iter_key_type[__iter-key-type__]<InputIterator>>, Allocator>;

  template<class Key, class T, class Allocator>
    unordered_map(std::initializer_list<std::pair<Key, T>>, typename xref:#unordered_map_deduction_guides[__见下文__]::size_type,
                  Allocator)
      -> unordered_map<Key, T, boost::hash<Key>, std::equal_to<Key>, Allocator>;

  template<class Key, class T, class Allocator>
    unordered_map(std::initializer_list<std::pair<Key, T>>, Allocator)
      -> unordered_map<Key, T, boost::hash<Key>, std::equal_to<Key>, Allocator>;

  template<class Key, class T, class Hash, class Allocator>
    unordered_map(std::initializer_list<std::pair<Key, T>>, typename xref:#unordered_map_deduction_guides[__见下文__]::size_type, Hash,
                  Allocator)
      -> unordered_map<Key, T, Hash, std::equal_to<Key>, Allocator>;

} // namespace unordered
} // namespace boost
-----

---

=== 描述

*模板参数*

[cols="1,1"]
|===

|_Key_
|`Key` 必须可从容器中 https://en.cppreference.com/w/cpp/named_req/Erasable[可擦除^]（即 `allocator_traits` 可以销毁它）。

|_T_
|`T` 必须可从容器中擦除（即 `allocator_traits` 可销毁它）。

|_Hash_
|一元函数对象类型，用作 `Key` 的哈希函数。它接受一个类型为 `Key` 的参数，并返回一个类型为 `std::size_t` 的值。

|_Pred_
|一种二元函数对象，用于在 `Key` 类型的值上实现等价关系。它接受两个 `Key` 类型的参数，并返回一个 bool 类型的值。

|_Allocator_
|分配器，其值类型与容器的值类型相同。
支持使用花式指针（fancy pointers）的分配器。

|===

元素被组织到桶中。具有相同哈希码的键存储在同一个桶中。

桶的数量可以通过调用 insert 自动增加，或作为调用 rehash 的结果而增加。

=== 配置宏

==== `BOOST_UNORDERED_ENABLE_SERIALIZATION_COMPATIBILITY_V0`

全局定义此宏以支持加载使用 Boost 1.84 之前版本保存到 Boost.Serialization 存档的 ``unordered_map``。

=== 类型定义

[source, c++, subs=+quotes]
----
typedef _由实现定义_ iterator;
----

值类型为 `value_type` 的迭代器。

迭代器类别至少为前向迭代器。

可转换为 `const_iterator`。

---

[source, c++, subs=+quotes]
----
typedef _由实现定义_ const_iterator;
----

值类型为 `value_type` 的常量迭代器。

迭代器类别至少为前向迭代器。

---

[source, c++, subs=+quotes]
----
typedef _由实现定义_ local_iterator;
----

一种迭代器，其值类型、差值类型、指针和引用类型与 iterator 相同。

`local_iterator` 对象可用于遍历单个桶。

---

[source, c++, subs=+quotes]
----
typedef _由实现定义_ const_local_iterator;
----

一种常量迭代器，其值类型、差值类型、指针和引用类型与 const_iterator 相同。

`const_local_iterator` 对象可用于遍历单个桶。

---

[source, c++, subs=+quotes]
----
typedef _由实现定义_ node_type;
----

用于保存提取的容器元素的类，建模为节点句柄（NodeHandle）。

---

[source, c++, subs=+quotes]
----
typedef _由实现定义_ insert_return_type;
----

内部类模板的特化：

[source, c++, subs=+quotes]
----
template<class Iterator, class NodeType>
struct _插入返回类型_ // 名称仅用于说明
{
  Iterator position;
  bool     inserted;
  NodeType node;
};
----

其中 `Iterator` = `iterator` 且 `NodeType` = `node_type`。

---

=== 构造函数

==== 默认构造函数
```c++

unordered_map();

```

使用 `hasher()` 作为哈希函数、`key_equal()` 作为键等价谓词、`allocator_type()` 作为分配器以及最大负载因子 `1.0` 构造一个空容器。

[horizontal]
后置条件：;; `size() == 0`
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足可默认构造（DefaultConstructible）要求。

---

==== 桶数量构造函数
```c++

explicit unordered_map(size_type n,
                       const hasher& hf = hasher(),
                       const key_equal& eql = key_equal(),
                       const allocator_type& a = allocator_type());

```

使用至少 `n` 个桶构造一个空容器，其中 `hf` 作为哈希函数、`eql` 作为键等价谓词、`a` 作为分配器，且最大负载因子为 `1.0`。

[horizontal]
后置条件：;; `size() == 0`
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足可默认构造（DefaultConstructible）要求。

---

==== 迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  unordered_map(InputIterator f, InputIterator l,
                size_type n = _实现定义_,
                const hasher& hf = hasher(),
                const key_equal& eql = key_equal(),
                const allocator_type& a = allocator_type());
----

使用至少 `n` 个桶构造一个空容器，其中 `hf` 作为哈希函数、`eql` 作为键等价谓词、`a` 作为分配器，且最大负载因子为 `1.0`，并将 `[f, l)` 范围内的元素插入其中。

[horizontal]
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足可默认构造（DefaultConstructible）要求。

---

==== 复制构造函数
```c++

unordered_map(unordered_map const& other);

```

复制构造函数。复制所含元素、哈希函数、谓词、最大负载因子和分配器。

若 `Allocator::select_on_container_copy_construction` 存在且签名正确，则分配器将由此方法的结果构造。

[horizontal]
要求：;; `value_type` 需满足可复制构造要求

---

==== 移动构造函数
```c++

unordered_map(unordered_map&& other);

```

移动构造函数。

[horizontal]
注意：;; 此函数通过 Boost.Move 实现。
要求：;; `value_type` 需可移动构造。

---

==== 带分配器的迭代器范围构造函数
```c++

template<class InputIterator>
  unordered_map(InputIterator f, InputIterator l, const allocator_type& a);

```

使用 `a` 作为分配器构造一个空容器，其中使用默认哈希函数和键等价谓词，最大负载因子为 `1.0`，并将 `[f, l)` 范围内的元素插入其中。

[horizontal]
要求：;; `hasher`、`key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

==== 分配器构造函数
```c++

explicit unordered_map(Allocator const& a);

```

使用分配器 `a` 构造空容器。

---

==== 带分配器的复制构造函数
```c++

unordered_map(unordered_map const& other, Allocator const& a);

```

构造一个容器，复制 ``other`` 所含元素、哈希函数、谓词、最大负载因子，但使用分配器 `a`。

---

==== 带分配器的移动构造函数
```c++

unordered_map(unordered_map&& other, Allocator const& a);

```

构造一个容器，移动 ``other`` 所含元素，并具有其哈希函数、谓词和最大负载因子，但使用分配器 `a`。

[horizontal]
注意：;; 此函数通过 Boost.Move 实现。
要求：;; `value_type` 需可移动插入。

---

==== 初始化列表构造函数
[source, c++, subs="+quotes"]
----
unordered_map(std::initializer_list<value_type> il,
              size_type n = _实现定义_
              const hasher& hf = hasher(),
              const key_equal& eql = key_equal(),
              const allocator_type& a = allocator_type());
----

使用至少 `n` 个桶构造一个空容器，其中 `极值类型__` 作为哈希函数、`eql` 作为键等价谓词、`a` 作为分配器，且最大负载因子为 `1.0`，并将 `il` 中的元素插入其中。

[horizontal]
要求：;; 若使用默认值，则 `hasher`、`key_equal` 和 `allocator_type` 需满足可默认构造（DefaultConstructible）要求。

---

==== 带分配器的桶数量构造函数
```c++

unordered_map(size_type n, allocator_type const& a);

```

使用至少 `n` 个桶构造一个空容器，其中使用默认哈希函数和键等价谓词，`a` 作为分配器，且最大负载因子为 `1.0`。

[horizontal]
后置条件：;; `size() == 0`
要求：;; `hasher` 和 `key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

==== 带哈希函数和分配器的桶数量构造函数
```c++

unordered_map(size_type n, hasher const& hf, allocator_type const& a);

```

使用至少 `n` 个桶构造一个空容器，其中 `hf` 作为哈希函数，使用默认键等价谓词，`a` 作为分配器，且最大负载因子为 `1.0`。

[horizontal]
后置条件：;; `size() == 0`
要求：;; `key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

==== 带桶数量和分配器的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
template<class InputIterator>
  unordered_map(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
----

使用至少 `n` 个桶构造一个空容器，其中 `a` 作为分配器，使用默认哈希函数和键等价谓词，最大负载因子为 `1.0`，并将 `[f, l)` 范围内的元素插入其中。

[horizontal]
要求：;; `hasher`、`key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

==== 带桶数量和哈希函数的迭代器范围构造函数
[source, c++, subs="+quotes"]
----
    template<class InputIterator>
      unordered_map(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                    const allocator_type& a);
----

使用至少 `n` 个桶构造一个空容器，其中 `hf` 作为哈希函数，`a` 作为分配器，使用默认键等价谓词，最大负载因子为 `1.0`，并将 `[f, l)` 范围内的元素插入其中。

[horizontal]
要求：;; `key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

==== 带分配器的初始化列表构造函数

```c++

unordered_map(std::initializer_list<value_type> il, const allocator_type& a);

```

使用 `a` 作为分配器构造一个空容器，最大负载因子为 1.0，并将 `il` 中的元素插入其中。

[horizontal]
要求：;; `hasher` 和 `key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

==== 带桶数量和分配器的初始化列表构造函数

```c++

unordered_map(std::initializer_list<value_type> il, size_type n, const allocator_type& a);

```

使用至少 `n` 个桶构造一个空容器，其中 `a` 作为分配器，最大负载因子为 1.0，并将 `il` 中的元素插入其中。

[horizontal]
要求：;; `hasher` 和 `key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

==== 带桶数量、哈希函数和分配器的初始化列表构造函数

```c++

unordered_map(std::initializer_list<value_type> il, size_type n, const hasher& hf,
              const allocator_type& a);

```

使用至少 `n` 个桶构造一个空容器，其中 `hf` 作为哈希函数，`a` 作为分配器，最大负载因子为 1.0，并将 `il` 中的元素插入其中。

[horizontal]
要求：;; `key_equal` 需满足可默认构造（DefaultConstructible）要求。

---

=== 析构函数

```c++

~unordered_map();

```

[horizontal]
注意：;; 析构函数作用于每个元素，并释放所有内存

---

=== 赋值

==== 复制赋值

```c++

unordered_map& operator=(unordered_map const& other);

```

赋值运算符。复制所含元素、哈希函数、谓词和最大负载因子，但不复制分配器。

若 `Alloc::propagate_on_container_copy_assignment` 存在且 `Alloc::propagate_on_container_copy_assignment::value` 为 `true`，则覆盖分配器；否则使用现有分配器创建复制元素。

[horizontal]
要求：;; `value_type` 需满足可复制构造要求

---

==== 移动赋值
```c++

unordered_map& operator=(unordered_map&& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
           boost::is_nothrow_move_assignable_v<Hash> &&
           boost::is_nothrow_move_assignable_v<Pred>);

```
移动赋值运算符。

若 `Alloc::propagate_on_container_move_assignment` 存在且 `Alloc::propagate_on_container_move_assignment::value` 为 `true`，则覆盖分配器；否则使用现有分配器创建移动元素。

[horizontal]
要求：;; `value_type` 需可移动构造。

---

==== 初始化列表赋值
```c++

unordered_map& operator=(std::initializer_list<value_type> il);

```

从初始化列表中的值进行赋值。所有现有元素将被新元素覆盖或销毁。

[horizontal]
要求：;; `value_type` 需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入^] 到容器中，且满足 https://en.cppreference.com/w/cpp/named_req/CopyAssignable[可复制赋值^]。

=== 迭代器

==== begin
```c++

iterator begin() noexcept; const_iterator begin() const noexcept;

```

[horizontal]
返回：;; 一个指向容器首元素的迭代器；若容器为空，则返回容器的尾后值。

---

==== end
```c++

iterator end() noexcept; const_iterator end() const noexcept;

```

[horizontal]
返回：;; 一个指向容器尾后值的迭代器。

---

==== cbegin
```c++

const_iterator cbegin() const noexcept;

```

[horizontal]
返回：;; 一个指向容器首元素的 `const_iterator`；若容器为空，则返回容器的尾后值。

---

==== cend
```c++

const_iterator cend() const noexcept;

```

[horizontal]
返回：;; 一个指向容器尾后值的 `const_iterator`。

---

=== 大小与容量

==== empty

```c++

[[nodiscard]] bool empty() const noexcept;

```

[horizontal]
返回：;; `size() == 0`

---

==== size

```c++

size_type size() const noexcept;

```

[horizontal]
返回：;; `std::distance(begin(), end())`

---

==== max_size

```c++

size_type max_size() const noexcept;

```

[horizontal]
返回：;; 容器可能的最大 `size()`。

---

=== 修改器

==== emplace
```c++

template<class... Args> std::pair<iterator, bool> emplace(Args&&... args);

```

当且仅当容器中不存在等价键时，插入一个由参数 `args` 构造的对象。

[horizontal]
要求：;; `value_type` 需满足从 `args` https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原位构造^] 到 `X` 的要求。
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 可能使迭代器失效，但仅当插入导致负载因子大于或等于最大负载因子时发生。
+
指向元素的指针和引用永不失效。
+
若 `args...` 的形式为 `k,v`，则延迟构造整个对象直至确定应插入元素，仅使用 `k` 参数进行检查。此优化在映射的 `key_type` 可移动构造或 `k` 参数为 `key_type` 时发生。

---

==== emplace_hint
```c++

template<class... Args> iterator emplace_hint(const_iterator position, Args&&... args);

```

当且仅当容器中不存在等价键时，插入一个由参数 `args` 构造的对象。

`position` 是插入位置的提示。

[horizontal]
要求：;; `value_type` 需满足从 `args` https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原位构造^] 到 `X` 的要求。
返回：;; 若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 标准对提示的含义相当模糊。但唯一实用的使用方式，也是 Boost.Unordered 支持的唯一方式，是指向具有相同键的现有元素。
+
可能使迭代器失效，但仅当插入导致负载因子大于或等于最大负载因子时发生。
+
指向元素的指针和引用永不失效。
+
若 `args...` 的形式为 `k,v`，则延迟构造整个对象直至确定应插入元素，仅使用 `k` 参数进行检查。此优化在映射的 `key_type` 可移动构造或 `k` 参数为 `key_type` 时发生。

---

==== 复制插入
```c++

std::pair极速赛车开奖直播官网<iterator, bool> insert(const value_type& obj);

```

当且仅当容器中不存在等价键时，插入 `obj`。

[horizontal]
要求：;; `value_type` 需满足可复制插入（CopyInsertable）要求。
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 可能使迭代器失效，但仅当插入导致负载因子大于或等于最大负载因子时发生。
+
指向元素的指针和引用永不失效。

---

==== 移动插入
```c++

std::pair<iterator, bool> insert(value_type&& obj);

```

当且仅当容器中不存在等价键时，插入 `obj`。

[horizontal]
要求：;; `value_type` 需满足可移动插入（MoveInsertable）要求。
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 可能使迭代器失效，但仅当插入导致负载因子大于或等于最大负载因子时发生。
+
指向元素的指针和引用永不失效。

---

==== 就地插入
```c++

template<class P> std::pair<iterator, bool> insert(P&& obj);

```

通过执行 `emplace(std::forward<P>(value))` 将元素插入容器。

仅当 `std::is_constructible<value_type, P&&>::value` 为 `true` 时参与重载决议。

[horizontal]
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。

---

==== 带提示的复制插入
```c++

iterator insert(const_iterator hint, const value_type& obj);

``` 当且仅当容器中不存在等价键时，插入 `obj`。

`hint` 是建议插入元素的位置。

[horizontal]
要求：;; `value_type` 需满足可复制插入（CopyInsertable）要求。
返回：;; 若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 标准对提示的含义相当模糊。但唯一实用的使用方式，也是 Boost.Unordered 支持的唯一方式，是指向具有相同键的现有元素。
+
可能使迭代器失效，但仅当插入导致负载因子大于或等于最大负载因子时发生。
+
指向元素的指针和引用永不失效。

---

==== 带提示的移动插入
```c++

iterator insert(const_iterator hint, value_type&& obj);

```

当且仅当容器中不存在等价键时，插入 `obj`。

`hint` 是建议插入元素的位置。

[horizontal]
要求：;; `value_type` 需满足可移动插入（MoveInsertable）要求。
返回：;; 若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 标准对提示的含义相当模糊。但唯一实用的使用方式，也是 Boost.Unordered 支持的唯一方式，是指向具有相同键的现有元素。
+
可能使迭代器失效，但仅当插入导致负载因子大于或等于最大负载因子时发生。
+
指向元素的指针和引用永不失效。

---

==== 带提示的就地插入

```c++

template<class P> iterator insert(const_iterator hint, P&& obj);

```

通过执行 `emplace_hint(hint, std::forward<P>(value))` 将元素插入容器。

仅当 `std::is_constructible<value_type, P&&>::value` 为 `true` 时参与重载决议。

`hint` 是建议插入元素的位置。

[horizontal]
返回：;; 若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
注意：;; 标准对提示的含义相当模糊。但唯一实用的使用方式，也是 Boost.Unordered 支持的唯一方式，是指向具有相同键的现有元素。
+
可能使迭代器失效，但仅当插入导致负载因子大于或等于最大负载因子时发生。
+
指向元素的指针和引用永不失效。

---

==== 插入迭代器范围
```c++

template<class InputIterator> void insert(InputIterator first, InputIterator last);

```

将元素范围插入容器。当且仅当容器中不存在等价键时插入元素。

[horizontal]
要求：;; `value_type` 需满足从 `*first` https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原位构造^] 到 `X` 的要求。
抛出：;; 插入单个元素时，若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 可能使迭代器失效，但仅当插入导致负载因子大于或等于最大负载因子时发生。
+
指向元素的指针和引用永不失效。

---

==== 插入初始化列表
```c++

void insert(std::initializer_list<value_type>);

```

将元素范围插入容器。当且仅当容器中不存在等价键时插入元素。

[horizontal]
要求：;; `value_type` 需满足可复制插入（CopyInsertable）到容器的要求。
抛出：;; 插入单个元素时，若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 可能使迭代器失效，但仅当插入导致负载因子大于或等于最大负载因子时发生。
+
指向元素的指针和引用永不失效。

---

==== try_emplace
```c++

template<class... Args>
  std::pair<iterator, bool> try_emplace(const key_type& k, Args&&... args);
template<class... Args>
  std::pair<iterator, bool> try_emplace(key_type&& k, Args&&... args);
template<class K, class... Args>
  std::pair<iterator, bool> try_emplace(K&& k, Args&&... args)

```

若容器中不存在键为 `k` 的元素，则插入新元素。

若存在键为 `k` 的元素，则此函数无操作。

[horizontal]
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 此函数类似于 xref:#unordered_map_emplace[emplace]，但 `value_type` 的构造使用：+
+
--
```c++

// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

```

而非 xref:#unordered_map_emplace[emplace] 直接转发所有参数到 ``value_type`` 的构造函数。

可能使迭代器失效，但仅当插入导致负载因子大于或等于最大负载因子时。

指向元素的指针和引用永不失效。

仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义，且 `iterator` 与 `const_iterator` 均不能从 `K` 隐式转换时，`template<class K, class\... Args>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免实例化 `Key` 类型的成本。
--

---

==== 带提示的 try_emplace
```c++

template<class... Args>
  iterator try_emplace(const_iterator hint, const key_type& k, Args&&... args);
template<class... Args>
  iterator try_emplace(const_iterator hint, key_type&& k, Args&&... args);
template<class K, class... Args>
  iterator try_emplace(const_iterator hint, K&& k, Args&&... args);

```

若容器中不存在键为 `k` 的元素，则插入新元素。

若存在键为 `k` 的元素，则此函数无操作。

`hint` 是建议插入元素的位置。

[horizontal]
返回：;; 若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 此函数类似于 xref:#unordered_map_emplace_hint[emplace_hint]，但 `value_type` 的构造使用：+
+
--
```c++

// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

```

而非 xref:#unordered_map_emplace_hint[emplace_hint] 直接转发所有参数到 ``value_type`` 的构造函数。

标准对提示的含义相当模糊。但唯一实用的使用方式（也是 Boost.Unordered 支持的唯一方式）是指向具有相同键的现有元素。

可能使迭代器失效，但仅当插入导致负载因子大于或等于最大负载因子时。

指向元素的指针和引用永不失效。

仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义，且 `iterator` 与 `const_iterator` 均不能从 `K` 隐式转换时，`template<class K, class\... Args>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免实例化 `Key` 类型的成本。
--

---

==== insert_or_assign
```c++

template<class M>
  std::pair<iterator, bool> insert_or_assign(const key_type& k, M&& obj);
template<class M>
  std::pair<iterator, bool> insert_or_assign(key_type&& k, M&& obj);
template<class K, class M>
  std::pair<iterator, bool> insert_or_assign(K&& k, M&& obj);

```

插入新元素到容器中，或通过赋值更新现有元素。

若存在键为 `k` 的元素，则通过赋值 `std::forward<M>(obj)` 更新它。

若不存在此类元素，则按如下形式添加到容器中：```c++

// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))

```

[horizontal]
返回：;; 若插入发生，则返回类型的 `bool` 分量为 `true`。
+
若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 可能使迭代器失效，但仅当插入导致负载因子大于或等于最大负载因子时发生。
+
指向元素的指针和引用永不失效。
+
仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K, class M>` 才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免实例化 `Key` 类型的成本。

---

==== 带提示的 insert_or_assign
```c++

template<class M>
  iterator insert_or_assign(const_iterator hint, const key_type& k, M&& obj);
template<class M>
  iterator insert_or_assign(const_iterator hint, key_type&& k, M&& obj);
template<class K, class M>
  iterator insert_or_assign(const_iterator hint, K&& k, M&& obj);

```

插入新元素到容器中，或通过赋值更新现有元素。

若存在键为 `k` 的元素，则通过赋值 `std::forward<M>(obj)` 更新它。

若不存在此类元素，则按如下形式添加到容器中：```c++

// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))

```

`hint` 是建议插入元素的位置。

[horizontal]
返回：;; 若插入发生，则迭代器指向新插入的元素；否则指向具有等价键的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 标准对提示的含义相当模糊。但唯一实用的使用方式，也是 Boost.Unordered 支持的唯一方式，是指向具有相同键的现有元素。
+
可能使迭代器失效，但仅当插入导致负载因子大于或等于最大负载因子时发生。
+
指向元素的指针和引用永不失效。
+
仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K, class M>` 才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免实例化 `Key` 类型的成本。

---

==== 按迭代器提取
```c++

node_type extract(const_iterator position);

```

移除 `position` 指向的元素。

[horizontal]
返回：;; 拥有该元素的 `node_type`。
注意：;; 使用此方法提取的节点可插入兼容的 `unordered_multimap`。

---

==== 按键提取
```c++

node_type extract(const key_type& k); template<class K> node_type extract(K&& k);

```

移除键等价于 `k` 的元素。

[horizontal]
返回：;; 若找到则返回拥有该元素的 `node_type`，否则返回空 `node_type`。
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才会抛出异常。
注意：;; 使用此方法提取的节点可插入兼容的 `unordered_multimap`。+
+
仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义，且 `iterator` 与 `const_iterator` 均不能从 `K` 隐式转换时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== 使用 `node_handle` 插入
```c++

insert_return_type insert(node_type&& nh);

```

若 `nh` 为空，则无效果。

否则，当且仅当容器中不存在等价键时，插入 `nh` 所拥有的元素。

[horizontal]
要求：;; `nh` 为空或 `nh.get_allocator()` 等于容器的分配器。
返回：;; 若 `nh` 为空，返回的 `insert_return_type` 满足：`inserted` 为 `false`，`position` 等于 `end()`，且 `node` 为空。+
+
否则，若已存在等价键的元素，返回的 `insert_return_type` 满足：`inserted` 为 `false`，`position` 指向匹配元素，且 `node` 包含来自 `nh` 的节点。+
+
否则，若插入成功，返回的 `insert_return_type` 满足：`inserted` 为 `true`，`position` 指向新插入元素，且 `node` 为空。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 可能使迭代器失效，但仅当插入导致负载因子大于或等于最大负载因子时发生。
+
指向元素的指针和引用永不失效。
+
此方法可用于插入从兼容的 `unordered_multimap` 提取的节点。

---

==== 带提示和 `node_handle` 的插入
```c++

iterator insert(const_iterator hint, node_type&& nh);

```

若 `nh` 为空，则无效果。

否则，当且仅当容器中不存在等价键时，插入 `nh` 所拥有的元素。

若容器中已存在等价键的元素，则对 `nh` 无影响（即 `nh` 仍包含该节点）。

`hint` 是建议插入元素的位置。

[horizontal]
要求：;; `nh` 为空或 `nh.get_allocator()` 等于容器的分配器。
返回：;; 若 `nh` 为空，返回 `end()`。+
+
若容器中已存在等价键的元素，返回指向该元素的迭代器。+
+
否则返回指向新插入元素的迭代器。
抛出：;; 若调用 hasher 以外的操作抛出异常，则该函数无效果。
注意：;; 标准对提示的含义相当模糊。但唯一实用的使用方式，也是 Boost.Unordered 支持的唯一方式，是指向具有相同键的现有元素。
+
可能使迭代器失效，但仅当插入导致负载因子大于或等于最大负载因子时发生。
+
指向元素的指针和引用永不失效。
+
此方法可用于插入从兼容的 `unordered_multimap` 提取的节点。

---

==== 按位置擦除

```c++

iterator erase(iterator position); iterator erase(const_iterator position);

```

擦除 `position` 指向的元素。

[horizontal]
返回：;; 擦除前 `position` 的后继迭代器。
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才会抛出异常。
注意：;; 在旧版本中此操作可能低效，因为必须遍历多个桶以定位返回的迭代器位置。数据结构已更改，不再存在此问题，因此其他擦除方法已被弃用。

---

==== 按键擦除
```c++

size_type erase(const key_type& k); template<class K> size_type erase(K&& k);

```

擦除所有键等价于 `k` 的元素。

[horizontal]
返回：;; 擦除的元素数量。
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才会抛出异常。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义，且 `iterator` 与 `const_iterator` 均不能从 `K` 隐式转换时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== 范围擦除

```c++

iterator erase(const_iterator first, const_iterator last);

```

擦除从 `first` 到 `last` 范围内的元素。

[horizontal]
返回：;; 指向被擦除元素之后位置的迭代器——即 `last`。
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才会抛出异常。
+
在此实现中，此重载不调用任何函数对象的方法，因此不会抛出异常，但其他实现可能不成立。

---

==== quick_erase
```c++

void quick_erase(const_iterator position);

```

擦除 `position` 指向的元素。

[horizontal]
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才会抛出异常。
+
在此实现中，此重载不调用任何函数对象的方法，因此不会抛出异常，但其他实现可能不成立。
注意：;; 此方法因从擦除操作返回下一元素的迭代器代价高昂而实现，但容器已重新设计，不再存在此问题。因此该方法现已弃用。

---

==== erase_return_void
```c++

void erase_return_void(const_iterator position);

```

擦除 `position` 指向的元素。

[horizontal]
抛出：;; 仅当 `hasher` 或 `key_equal` 抛出异常时才会抛出异常。
+
在此实现中，此重载不调用任何函数对象的方法，因此不会抛出异常，但其他实现可能不成立。
注意：;; 此方法因从擦除操作返回下一元素的迭代器代价高昂而实现，但容器已重新设计，不再存在此问题。因此该方法现已弃用。

---

==== swap
```c++

void swap(unordered_map& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
           boost::is_nothrow_swappable_v<Hash> &&
           boost::is_nothrow_swappable_v<Pred>);

```

交换容器与参数的内容。

若声明了 `Allocator::propagate_on_container_swap` 且其值为 `true`，则交换容器的分配器；否则，与不同分配器的容器交换将导致未定义行为。

[horizontal]
抛出：;; 除非 `key_equal` 或 `hasher` 的复制构造函数或复制赋值运算符抛出异常，否则不会抛出异常。
注意：;; 异常规范与 C++11 标准不完全相同，因为等价谓词和哈希函数通过其复制构造函数交换。

---

==== clear
```c++

void clear();

```

擦除容器中所有元素。

[horizontal]
后置条件：;; `size() == 0`
抛出：;; 永不抛出异常。

---

==== merge
```c++

template<class H2, class P2>
  void merge(unordered_map<Key, T, H2, P2, Allocator>& source);
template<class H2, class P2>
  void merge(unordered_map<Key, T, H2, P2, Allocator>&& source);
template<class H2, class P2>
  void merge(unordered_multimap<Key, T, H2, P2, Allocator>& source);
template<class H2, class P2>
  void merge(unordered_multimap<Key, T, H2, P2, Allocator>&& source);

```

尝试通过遍历 `source` 并提取 `source` 中不包含在 `*this` 中的任何节点，然后将其插入 `*this` 来“合并”两个容器。

由于 `source` 可能具有不同的哈希函数和键等价谓词，`source` 中每个节点的键将使用 `this->hash_function()` 重新哈希，然后（如有必要）使用 `this->key_eq()` 进行比较。

若 `this->get_allocator() != source.get_allocator()`，则此函数行为未定义。

此函数不复制或移动任何元素，而是简单地将节点从 `source` 重新定位到 `*this` 中。

[horizontal]
注意：;;
+
--
* 指向被转移元素的指针和引用保持有效。
* 使指向被转移元素的迭代器失效。
* 使属于 `*this` 的迭代器失效。
* 指向 `source` 中未转移元素的迭代器保持有效。
--

* ---

=== 观察器

==== get_allocator
```

allocator_type get_allocator() const;

```

---

==== hash_function
```

hasher hash_function() const;

```

[horizontal]
返回：;; 容器的哈希函数。

---

==== key_eq
```

key_equal key_eq() const;

```

[horizontal]
返回：;; 容器的键相等谓词

---

=== 查找

==== find
```c++

iterator         find(const key_type& k);
const_iterator   find(const key_type& k) const;
template<class K>
  iterator       find(const K& k);
template<class极 K>
  const_iterator find(const K& k) const;
template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
  iterator       find(CompatibleKey const& k, CompatibleHash const& hash,
                      CompatiblePredicate const& eq);
template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
  const_iterator find(CompatibleKey const& k, CompatibleHash const& hash,
                      CompatiblePredicate const& eq) const;

```

[horizontal]
返回：;; 指向键等价于 `k` 的元素的迭代器；若不存在则返回 `b.end()`。
注意：;; 包含 `CompatibleKey`、`CompatibleHash` 和 `CompatiblePredicate` 的模板化重载是非标准扩展，允许使用兼容的哈希函数和等价谓词处理不同类型的键，以避免昂贵的类型转换。通常不鼓励使用，而应使用 `K` 成员函数模板。
+
仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== count
```c++

size_type        count(const key_type& k) const;
template<class K>
  size_type      count(const K&极速赛车开奖直播官网 k) const;

```

[horizontal]
返回：;; 键等价于 `k` 的元素数量。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== contains
```c++

bool             contains(const key_type& k) const;
template<class K>
  bool           contains(const K& k) const;

```

[horizontal]
返回：;; 指示容器中是否存在键等于 `key` 的元素的布尔值
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== equal_range
```c++

std::pair<iterator, iterator>               equal_range(const key_type& k);
std::pair<const_iterator, const_iterator>   equal_range(const key_type& k) const;
template<class K>
  std::pair<iterator, iterator>             equal_range(const K& k);
template<class K>
  std::pair<const_iterator, const_iterator> equal_range(const K& k) const;

```

[horizontal]
返回：;; 包含所有键等价于 `k` 的元素的范围。若容器不包含此类元素，则返回 `std::make_pair(b.end(), b.end())`。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== operator[]
```c++

mapped_type& operator[](const key_type& k); mapped_type& operator[](key_type&& k); template<class K> mapped_type& operator[](K&& k);

```

[horizontal]
效果：;; 若容器中尚未包含键等价于 `k` 的元素，则插入值 `std::pair<key_type const, mapped_type>(k, mapped_type())`。
返回：;; 对 `x.second` 的引用，其中 `x` 是容器中已存在的元素或新插入的键等效于 `k` 的元素。
抛出：;; 若非调用 `hasher` 的操作引发异常，则该函数无任何效果。
注意：;; 可能使迭代器失效，但仅当插入导致负载因子大于或等于最大负载因子时发生。
+
指向元素的指针和引用永不失效。
+
仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== at
```c++

mapped_type& at(const key_type& k); const mapped_type& at(const key_type& k) const; template<class K> mapped_type& at(const K& k); template<class K> const mapped_type& at(const K& k) const;

```

[horizontal]
返回：;; 对 `x.second` 的引用，其中 `x` 是键等效于 `k` 的（唯一）元素。
抛出：;; 若不存在此类元素，则抛出 `std::out_of_range` 类型的异常对象。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

=== 桶接口

==== bucket_count
```c++

size_type bucket_count() const noexcept;

```

[horizontal]
返回：;; 桶的数量。

---

==== max_bucket_count
```c++

size_type max_bucket_count() const noexcept;

```

[horizontal]
返回：;; 桶数量的上限。

---

==== bucket_size
```c++

size_type bucket_size(size_type n) const;

```

[horizontal]
要求：;; `n < bucket_count()`
返回：;; 桶 `n` 中的元素数量。

---

==== bucket
```c++

size_type bucket(const key_type& k) const; template<class K> size_type bucket(const K& k) const;

```

[horizontal]
返回：;; 将包含键 `k` 的元素的桶的索引。
后置条件：;; 返回值小于 `bucket_count()`。
注意：;; 仅当 `Hash::is_transparent` 和 `Pred::is_transparent` 是有效的成员类型定义时，`template<class K>` 重载才参与重载决议。库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且 `Pred` 是透明的。这支持异构查找，避免了实例化 `Key` 类型的开销。

---

==== begin

```c++

local_iterator begin(size_type n); const_local_iterator begin(size_type n) const;

```

[horizontal]
要求：;; `n` 应在 `[0, bucket_count())` 范围内。
返回：;; 指向索引为 `n` 的桶中首元素的局部迭代器。

---

==== end
```c++

local_iterator end(size_type n); const_local_iterator end(size_type n) const;

```

[horizontal]
要求：;; `n` 应在 `[0, bucket_count())` 范围内。
返回：;; 指向索引为 `n` 的桶中尾后元素的局部迭代器。

---

==== cbegin
```c++

const_local_iterator cbegin(size_type n) const;

```

[horizontal]
要求：;; `n` 应在 `[0, bucket_count())` 范围内。
返回：;; 指向索引为 `n` 的桶中首元素的常量局部迭代器。

---

==== cend
```c++

const_local_iterator cend(size_type n) const;

```

[horizontal]
要求：;; `n` 应在 `[0, bucket_count())` 范围内。
返回：;; 指向索引为 `n` 的桶中尾后元素的常量局部迭代器。

---

=== 哈希策略

==== load_factor
```c++

float load_factor() const noexcept;

```

[horizontal]
返回：;; 每个桶的平均元素数量。

---

==== max_load_factor

```c++

float max_load_factor() const noexcept;

```

[horizontal]
返回：;; 返回当前最大负载因子。

---

==== 设置最大负载因子
```c++

void max_load_factor(float z);

```

[horizontal]
效果：;; 更改容器的最大负载因子，使用 `z` 作为提示值。

---


==== rehash
```c++

void rehash(size_type n);

```

更改桶的数量，使至少存在 `n` 个桶，且负载因子小于或等于最大负载因子。适用时，此操作将增加或减少与容器关联的 `bucket_count()`。

当 `size() == 0` 时，`rehash(0)` 将释放底层桶数组。

使迭代器失效，并改变元素顺序。指向元素的指针和引用不会失效。

[horizontal]
抛出：;; 若抛出异常（除非由容器的哈希函数或比较函数抛出），则该函数无任何效果。

---

==== reserve
```c++

void reserve(size_type n);

```

等价于 `a.rehash(ceil(n / a.max_load_factor()))`，或当 `n > 0` 且 `a.max_load_factor() == std::numeric_limits<float>::infinity()` 时等价于 `a.rehash(1)`。

与 `rehash` 类似，此函数可用于增加或减少容器中的桶数量。

使迭代器失效，并改变元素顺序。指向元素的指针和引用不会失效。

[horizontal]
抛出：;; 若抛出异常（除非由容器的哈希函数或比较函数抛出），则该函数无任何效果。

=== 推导指引
若满足以下任意条件，则推导指引不参与重载决议：

  - 具有 `InputIterator` 模板参数，且推导出该参数的类型不符合输入迭代器要求。
  - 具有 `Allocator` 模板参数，且推导出该参数的类型不符合分配器要求。
  - 具有 `Hash` 模板参数，且推导出该参数的类型为整型或符合分配器要求。
  - 具有 `Pred` 模板参数，且推导出该参数的类型符合分配器要求。

推导指引中的 `size_type` 参数类型指向由推导指引推导出的容器类型的 `size_type` 成员类型。其默认值与所选构造函数的默认值一致。

==== __迭代器值类型__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __迭代器值类型__ =
    typename std::iterator_traits<InputIterator>::value_type; // 仅用于说明
-----

==== __迭代器键类型__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-key-type__ = std::remove_const_t<
    std::tuple_element_t<0, xref:#unordered_map_iter_value_type[__iter-value-type__]<InputIterator>>>; // 仅用于说明
-----

==== __迭代器映射类型__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-mapped-type__ =
    std::tuple_element_t<1, xref:#unordered_map_iter_value_type[__iter-value-type__]<InputIterator>>;  // 仅用于说明
-----

==== __迭代器到分配类型__
[listings, subs="+macros,+quotes"]
-----
template<class InputIterator>
  using __iter-to-alloc-type__ = std::pair<
    std::add_const_t<std::tuple_element_t<0, xref:#unordered_map_iter_value_type[__iter-value-type__]<InputIterator>>>,
    std::tuple_element_t<1, xref:#unordered_map_iter_value_type[__iter-value-type__]<InputIterator>>>; // 仅用于说明
-----

=== 相等比较

==== operator==
```c++

template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator==(const unordered_map<Key, T, Hash, Pred, Alloc>& x,
                  const unordered_map<Key, T, Hash, Pred, Alloc>& y);

```

若 `x.size() == y.size()` 且对于 `x` 中的每个元素，`y` 中均存在相同键的元素且值相等（使用 `operator==` 比较值类型），则返回 `true`。

[horizontal]
注意：;; 若两个容器的相等谓词不等价，则行为未定义。

---

==== operator!=
```c++

template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator!=(const unordered_map<Key, T, Hash, Pred, Alloc>& x,
                  const unordered_map<Key, T, Hash, Pred, Alloc>& y);

```

若 `x.size() == y.size()` 且对于 `x` 中的每个元素，`y` 中均存在相同键的元素且值相等（使用 `operator==` 比较值类型），则返回 `false`。

[horizontal]
注意：;; 若两个容器的相等谓词不等价，则行为未定义。

=== Swap
```c++

template<class Key, class T, class Hash, class Pred, class Alloc>
  void swap(unordered_map<Key, T, Hash, Pred, Alloc>& x,
            unordered_map<Key, T, Hash, Pred, Alloc>& y)
    noexcept(noexcept(x.swap(y)));

```

交换 `x` 和 `y` 的内容。

若声明了 `Allocator::propagate_on_container_swap` 且其值为 `true`，则交换容器的分配器；否则，与不同分配器的容器交换将导致未定义行为。

[horizontal]
效果：;; `x.swap(y)`
抛出：;; 除非 `key_equal` 或 `hasher` 的复制构造函数或复制赋值运算符抛出异常，否则不会抛出异常。
注意：;; 异常规范与 C++11 标准不完全相同，因为等价谓词和哈希函数通过其复制构造函数交换。

---

=== erase_if
```c++

template<class K, class T, class H, class P, class A, class Predicate>
  typename unordered_map<K, T, H, P, A>::size_type
    erase_if(unordered_map<K, T, H, P, A>& c, Predicate pred);

```

遍历容器 `c` 并移除所有满足谓词 `pred` 返回 `true` 的元素。

[horizontal]
返回：;; 被擦除的元素数量。
注意：;; 等价于：
+
```c++

auto original_size = c.size();
for (auto i = c.begin(), last = c.end(); i != last; ) {
  if (pred(*i)) {
    i = c.erase(i);
  } else {
    ++i;
  }
}
return original_size - c.size();

```
+
注意传递给 `pred` 的引用是非 const 的。

=== 序列化

``unordered_map`` 可通过 link:../../../../../serialization/index.html[Boost.Serialization^] 使用本库提供的 API 进行归档/检索。支持常规归档和 XML 归档。

==== 将 unordered_map 保存到归档

将 `unordered_map` `x` 的所有元素保存到归档（XML 归档）`ar` 中。

[horizontal]
要求：;; `std::remove_const<key_type>::type` 和 `std::remove_const<mapped_type>::type` 可序列化（XML 可序列化），且支持 Boost.Serialization 的 `save_construct_data`/`load_construct_data` 协议（https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造^]类型自动支持）。

---

==== 从归档加载 unordered_map

删除 `unordered_map` `x` 的所有现有元素，并从归档（XML 归档）`ar` 中插入原始 `unordered_map` `other` 的元素副本（这些元素已保存到 `ar` 读取的存储中）。

[horizontal]
要求：;; `value_type` 需满足从 `(std::remove_const<key_type>::type&&, std::remove_const<mapped_type>::type&&)` https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[就地构造^]。`x.key_equal()` 在功能上等价于 `other.key_equal()`。
注意：;; 若归档使用 Boost 1.84 之前的版本保存，则必须全局定义配置宏 `BOOST_UNORDERED_ENABLE_SERIALIZATION_COMPATIBILITY_V0` 才能使此操作成功；否则将抛出异常。

---

==== 将迭代器/常量迭代器保存到归档

将迭代器（常量迭代器）`it` 的位置信息保存到归档（XML 归档）`ar` 中。`it` 可以是 `end()` 迭代器。

[horizontal]
要求：;; `it` 指向的 `unordered_map` `x` 先前已保存到 `ar`，且在保存 `x` 和保存 `it` 之间未对 `x` 执行修改操作。

---

==== 从归档加载迭代器/常量迭代器

使迭代器（常量迭代器）`it` 指向原始迭代器（常量迭代器）的还原位置（该位置已保存到归档（XML 归档）`ar` 读取的存储中）。

[horizontal]
要求：;; 若 `x` 是 `it` 指向的 `unordered_map`，则在加载 `x` 和加载 `it` 之间未对 `x` 执行修改操作。
