[#debuggability]
:idprefix: debuggability_

= 可调试性

== Visual Studio Natvis

所有容器和迭代器在 Natvis 框架中都有自定义可视化效果。

=== 在项目中使用

要在项目中的 Natvis 框架中可视化 Boost.Unordered 容器，只需将文件 link:https://github.com/boostorg/unordered/blob/develop/extra/boost_unordered.natvis[/extra/boost_unordered.natvis] 作为“现有项”添加到 Visual Studio 项目中。

=== 可视化结构

可视化效果与标准无序容器的效果一致。一个容器最多同时显示 100 个元素。每个集合元素的项名称显示为 `[i]`，其中 `i` 是显示中的索引，从 `0` 开始。默认情况下，每个映射元素的项名称显示为 `[\{key-display}]`。例如，如果第一个元素是 `("abc", 1)` 对，则项名称为 `["abc"]`。可以通过使用视图 "ShowElementsByIndex" 来覆盖此行为，该视图将映射的显示行为切换为按索引命名元素。标准无序容器中也使用相同的视图名称。

默认情况下，封闭寻址容器将显示 `[hash_function]` 和 `[key_eq]`，如果适用，还会显示 `[spare_hash_function]` 和 `[spare_key_eq]`，以及 `[allocator]` 和元素。使用视图 "detailed" 会添加 `[bucket_count]` 和 `[max_load_factor]`。相反，使用视图 "simple" 则仅显示元素，没有其他项。

默认情况下，开放寻址容器将显示 `[hash_function]`、`[key_eq]`、`[allocator]` 和元素。使用视图 "simple" 则仅显示元素，没有其他项。SIMD 和非 SIMD 实现均可通过 Natvis 框架查看。

迭代器的显示方式与其标准对应物类似。迭代器显示为其指向的元素。结束迭代器则简单地显示为 `{ end iterator }`。

=== 花式指针

如果分配器中使用花式指针（如 `boost::interprocess::offset_ptr`），容器可视化效果同样适用。虽然这种情况很少见，但 Boost.Unordered 提供了 natvis 定制点以支持任何类型的花式指针。`boost::interprocess::offset_ptr` 的支持已在 Boost.Interprocess 库中定义，您可以通过遵循文件 link:https://github.com/boostorg/unordered/blob/develop/extra/boost_unordered.natvis[/extra/boost_unordered.natvis] 末尾附近的注释中的说明，为自定义类型添加支持。

== GDB 美观打印器

所有容器和迭代器都有自定义的 GDB 美观打印器。

=== 在项目中使用

使用美观打印器时，必须始终按如下方式启用美观打印。这通常是一次性设置。

```plaintext

(gdb) set print pretty on

```

默认情况下，如果编译为 ELF 二进制格式，则二进制文件将包含 Boost.Unordered 美观打印器。要使用嵌入式美观打印器，请确保按如下方式允许自动加载。每次加载 GDB 时都必须执行此操作，或将其添加到 ".gdbinit" 文件中。

```plaintext

(gdb) add-auto-load-safe-path [/path/to/executable]

```

您可以选择通过定义 `BOOST_ALL_NO_EMBEDDED_GDB_SCRIPTS` 来编译二进制文件，_不_嵌入美观打印器，这将为所有具有此功能的 Boost 库禁用嵌入式 GDB 美观打印器。

您可以从非嵌入式 Python 脚本外部加载美观打印器。使用 `source` 命令添加脚本 link:https://github.com/boostorg/unordered/blob/develop/extra/boost_unordered_printers.py[/extra/boost_unordered_printers.py]，如下所示。

```plaintext

(gdb) source [/path/to/boost]/libs/unordered/extra/boost_unordered_printers.py

```

=== 可视化结构

可视化效果与标准无序容器一致。映射容器显示从键到映射值的关联。集合容器显示从索引到值的关联。迭代器要么显示其项，要么显示为结束迭代器。以下是一个示例 `boost::unordered_map`、一个示例 `boost::unordered_set` 及其各自的起始和结束迭代器的显示示例。

```plaintext

(gdb) print example_unordered_map $1 = boost::unordered_map with 3 elements = {["C"] = "c", ["B"] = "b", ["A"] = "a"} (gdb) print example_unordered_map_begin $2 = iterator = { {first = "C", second = "c"} } (gdb) print example_unordered_map_end $3 = iterator = { end iterator } (gdb) print example_unordered_set $4 = boost::unordered_set with 3 elements = {[0] = "c", [1] = "b", [2] = "a"} (gdb) print example_unordered_set_begin $5 = iterator = { "c" } (gdb) print example_unordered_set_end $6 = iterator = { end iterator }

```

其他容器除了在显示容器本身时将 "`boost::unordered_{map|set}`" 替换为适当的模板名称外，其余相同。请注意，每个子元素（即键、映射值或值）都基于其自身的打印设置显示，这些设置可能包括其自身的美观打印器。

SIMD 和非 SIMD 实现均可通过 GDB 美观打印器查看。

对于启用了 xref:hash_quality.adoc#hash_quality_container_statistics[容器统计信息] 的开放寻址容器，您可以在 GDB 中调用容器上的 `get_stats()` 来获取这些统计信息。这在 GDB 中被覆盖为 link:https://sourceware.org/gdb/current/onlinedocs/gdb.html/Xmethod-API.html[xmethod]，因此不会调用任何 C++ 同步代码。请参阅以下打印输出作为预期格式的示例。

```plaintext

(gdb) print example_flat_map.get_stats()
$1 = [stats] = {[insertion] = {[count] = 5, [probe_length] = {avg = 1.0, var = 0.0, dev = 0.0}},
  [successful_lookup] = {[count] = 0, [probe_length] = {avg = 0.0, var = 0.0, dev = 0.0},
    [num_comparisons] = {avg = 0.0, var = 0.0, dev = 0.0}}, [unsuccessful_lookup] = {[count] = 5,
    [probe_length] = {avg = 1.0, var = 0.0, dev = 0.0},
    [num_comparisons] = {avg = 0.0, var = 0.0, dev = 0.0}}}

```

=== 花式指针

如果分配器中使用花式指针（如 `boost::interprocess::offset_ptr`），美观打印器同样适用。虽然这种情况很少见，但 Boost.Unordered 提供了 GDB 美观打印器定制点以支持任何类型的花式指针。`boost::interprocess::offset_ptr` 的支持已在 Boost.Interprocess 库中定义，您可以通过遵循文件 link:https://github.com/boostorg/unordered/blob/develop/extra/boost_unordered_printers.py[/extra/boost_unordered_printers.py] 末尾附近的注释中的说明，为自定义类型添加支持。
