[#hash_equality]

:idprefix: hash_equality_

= 相等谓词与哈希函数

关联容器使用排序关系来指定元素的存储方式，而无序关联容器则使用相等谓词和哈希函数。例如，`xref:reference/unordered_map.adoc[boost::unordered_map]` 的声明如下：

```cpp

template <
    class Key, class Mapped,
    class Hash = boost::hash<Key>,
    class Pred = std::equal_to<Key>,
    class Alloc = std::allocator<std::pair<Key const, Mapped> > >
class unordered_map;

```

哈希函数排在前面，因为您可能希望更改哈希函数但不更改相等谓词。例如，如果您想使用 https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function#FNV-1a_hash[FNV-1a 哈希^]，可以这样写：

```cpp

boost::unordered_map<std::string, int, hash::fnv_1a>
    dictionary;

```

示例目录中提供了 link:../../../examples/fnv1.hpp[FNV-1a 的实现^]。

如果希望使用不同的相等函数，则还需要使用匹配的哈希函数。例如，要实现不区分大小写的字典，需要定义不区分大小写的相等谓词和哈希函数：

```cpp

struct iequal_to
{
    bool operator()(std::string const& x,
        std::string const& y) const
    {
        return boost::algorithm::iequals(x, y, std::locale());
    }
};

struct ihash
{
    std::size_t operator()(std::string const& x) const
    {
        std::size_t seed = 0;
        std::locale locale;

        for(std::string::const_iterator it = x.begin();
            it != x.end(); ++it)
        {
            boost::hash_combine(seed, std::toupper(*it, locale));
        }

        return seed;
    }
};

```

然后可以在不区分大小写的字典中使用：
```cpp

boost::unordered_map<std::string, int, ihash, iequal_to>
    idictionary;

```

这是 link:../../../examples/case_insensitive.hpp[/libs/unordered/examples/case_insensitive.hpp^] 中示例的简化版本，支持其他区域设置和字符串类型。

CAUTION: 使用相等运算符 (`==`) 与自定义相等谓词时要小心，尤其是在使用函数指针时。如果比较两个具有不同相等谓词的容器，结果是未定义的。对于大多数无状态函数对象，这不可能发生——因为只能使用相同相等谓词的对象进行比较，所以您知道相等谓词必须相同。但如果使用函数指针或有状态的相等谓词（例如 `boost::function`），则可能会遇到问题。

== 自定义类型

同样，自定义哈希函数可用于自定义类型：

```cpp

struct point {
    int x;
    int y;
};

bool operator==(point const& p1, point const& p2)
{
    return p1.x == p2.x && p1.y == p2.y;
}

struct point_hash
{
    std::size_t operator()(point const& p) const
    {
        std::size_t seed = 0;
        boost::hash_combine(seed, p.x);
        boost::hash_combine(seed, p.y);
        return seed;
    }
};

boost::unordered_multiset<point, point_hash> points;

```

由于默认哈希函数是 link:../../../../container_hash/index.html[Boost.Hash^]，我们可以扩展它以支持该类型，从而无需显式指定哈希函数：

```cpp

struct point {
    int x;
    int y;
};

bool operator==(point const& p1, point const& p2)
{
    return p1.x == p2.x && p1.y == p2.y;
}

std::size_t hash_value(point const& p) {
    std::size_t seed = 0;
    boost::hash_combine(seed, p.x);
    boost::hash_combine(seed, p.y);
    return seed;
}

// Now the default function objects work.
boost::unordered_multiset<point> points;

```

有关如何执行此操作的更多详细信息，请参阅 link:../../../../container_hash/index.html[Boost.Hash 文档^]。请记住，它依赖于对标准的扩展——因此它不适用于无序关联容器的其他实现，您需要显式使用 Boost.Hash。

[caption="，",  title='Table {counter:table-counter} Methods for accessing the hash and equality functions']
[cols="1,.^1", frame=all,,  grid=rows]
|===
|方法 |描述

|`hasher hash_function() const`
|返回容器的哈希函数。

|`key_equal key_eq() const`
|返回容器的键相等函数。

|===
