[[header]]
== 相等谓词与哈希函数

[[content]]
[[preamble]]
虽然关联容器使用排序关系指定元素的存储方式，但无序关联容器使用相等谓词和哈希函数。例如，link:reference/unordered_map.html[`boost::unordered_map`]
的声明如下：

[source,highlight]
----
template <
    class Key, class Mapped,
    class Hash = boost::hash<Key>,
    class Pred = std::equal_to<Key>,
    class Alloc = std::allocator<std::pair<Key const, Mapped> > >
class unordered_map;
----

哈希函数排在首位，因为您可能希望更改哈希函数而不改变相等谓词。例如，若要使用
https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function#FNV-1a_hash[FNV-1a哈希]，可编写：

[source,highlight]
----
boost::unordered_map<std::string, int, hash::fnv_1a>
    dictionary;
----

示例目录中提供了 link:../../../examples/fnv1.hpp[FNV-1a的实现]。

若需使用不同的相等函数，则必须同时使用匹配的哈希函数。例如，要实现不区分大小写的字典，需定义不区分大小写的相等谓词和哈希函数：

[source,highlight]
----
struct iequal_to
{
    bool operator()(std::string const& x,
        std::string const& y) const
    {
        return boost::algorithm::iequals(x, y, std::locale());
    }
};

struct ihash
{
    std::size_t operator()(std::string const& x) const
    {
        std::size_t seed = 0;
        std::locale locale;

        for(std::string::const_iterator it = x.begin();
            it != x.end(); ++it)
        {
            boost::hash_combine(seed, std::toupper(*it, locale));
        }

        return seed;
    }
};
----

随后可在不区分大小写的字典中使用：

[source,highlight]
----
boost::unordered_map<std::string, int, ihash, iequal_to>
    idictionary;
----

此代码是
link:../../../examples/case_insensitive.hpp[/libs/unordered/examples/case_insensitive.hpp]
示例的简化版本，支持其他区域设置和字符串类型。

[width="100%",cols="50%,50%",]
|===
a|
注意

|使用相等运算符（`==`）与自定义相等谓词时需格外谨慎，尤其在使用函数指针时。若比较两个具有不同相等谓词的容器，结果将未定义。对于多数无状态函数对象，此情况不可能发生——因只能使用相同相等谓词比较对象，故可知谓词必然相同。但若使用函数指针或有状态相等谓词（如
`boost::function`），则可能引发问题。
|===

[[hash_equality_custom_types]]
== 自定义类型

类似地，自定义类型可使用自定义哈希函数：

[source,highlight]
----
struct point {
    int x;
    int y;
};

bool operator==(point const& p1, point const& p2)
{
    return p1.x == p2.x && p1.y == p2.y;
}

struct point_hash
{
    std::size_t operator()(point const& p) const
    {
        std::size_t seed = 0;
        boost::hash_combine(seed, p.x);
        boost::hash_combine(seed, p.y);
        return seed;
    }
};

boost::unordered_multiset<point, point_hash> points;
----

由于默认哈希函数是
link:../../../../container_hash/index.html[Boost.Hash]，可扩展其以支持该类型，从而无需显式指定哈希函数：

[source,highlight]
----
struct point {
    int x;
    int y;
};

bool operator==(point const& p1, point const& p2)
{
    return p1.x == p2.x && p1.y == p2.y;
}

std::size_t hash_value(point const& p) {
    std::size_t seed = 0;
    boost::hash_combine(seed, p.x);
    boost::hash_combine(seed, p.y);
    return seed;
}

// 现在默认函数对象可正常工作
boost::unordered_multiset<point> points;
----

更多扩展方法详见
link:../../../../container_hash/index.html[Boost.Hash文档]。请注意此功能依赖于标准扩展——故不适用于其他无序关联容器实现，需显式使用Boost.Hash。

.表1：访问哈希函数与相等函数的方法
[width="100%",cols="50%,50%",options="header",]
|===
|方法 |描述
|`hasher hash_function() const` |返回容器的哈希函数。
|`key_equal key_eq() const` |返回容器的键相等函数。
|===

[[footer]]
[[footer-text]]
最后更新于2025-10-31 21:31:58 UTC
