[#hash_quality]
= 哈希质量

:idprefix: hash_quality_

为了正常工作，哈希表要求提供的哈希函数具有__良好质量__，大致意思是它应尽可能均匀地使用其 `std::size_t` 输出空间，就像随机数生成器那样——当然，哈希函数的值并非随机，而是由其输入参数严格决定。

Boost.Unordered 中的闭地址容器对质量不理想的哈希函数具有相当的鲁棒性，但开放寻址容器和并发容器对此因素更为敏感，如果哈希函数不合适，其性能可能会急剧下降。通常，如果使用 link:../../../../container_hash/index.html[Boost.Hash^] 提供或生成的函数，质量将足够，但使用替代哈希算法时必须谨慎。

本节其余部分仅适用于开放寻址容器和并发容器。

== 哈希后混合与雪崩特性

即使您提供的哈希函数不符合开放寻址所需的均匀行为，Boost.Unordered 容器的性能也可能可接受，因为库会执行内部__后混合__步骤以改进计算哈希值的统计特性。这会带来额外的计算成本；如果您希望退出后混合，请按如下方式注解哈希函数：

[source, c++]
----
struct my_string_hash_function
{
  using is_avalanching = std::true_type; // 指示 Boost.Unordered 不使用后混合

  std::size_t operator()(const std::string& x) const
  {
    ...
  }
};
----

通过设置 `link:../../../../container_hash/doc/html/hash.html#ref_hash_is_avalanchinghash[hash_is_avalanching]` 特性，我们告知 Boost.Unordered `my_string_hash_function` 具有足够质量，无需任何后混合安全网即可直接使用。但这存在风险：若哈希函数未如声明那样行为良好，性能可能会下降。

== 容器统计信息

若全局定义宏 `BOOST_UNORDERED_ENABLE_STATS`，开放寻址容器和并发容器将计算与哈希函数质量直接相关的内部统计信息：

[source, c++]
----
#define BOOST_UNORDERED_ENABLE_STATS
#include <boost/unordered/unordered_map.hpp>

...

int main()
{
  boost::unordered_flat_map<std::string, int, my_string_hash> m;
  ... // 使用 m

  auto stats = m.get_stats();
  ... // 检查统计信息
}
----

`stats` 对象提供以下信息：

[source, subs=+quotes]
----
stats
     .insertion                                     // *插入操作*
               .count                               // 操作次数
               .probe_length                        // 每次操作的探测长度
                            .average
                            .variance
                            .deviation
	 .successful_lookup                             // *查找操作（找到元素）*
                       .count                       // 操作次数
                       .probe_length                // 每次操作的探测长度
                                    .average
                                    .variance
                                    .deviation
                       .num_comparisons             // 每次操作比较的元素数
			                           .average
                                       .variance
                                       .deviation
	 .unsuccessful_lookup                           // *查找操作（未找到元素）*
                         .count                     // 操作次数
                         .probe_length              // 每次操作的探测长度
                                      .average
                                      .variance
                                      .deviation
                         .num_comparisons           // 每次操作比较的元素数
			                             .average
                                         .variance
                                         .deviation
----

维护了三种内部操作的统计信息：插入（不考虑先前查找以确定键是否存在的操作）、成功查找和未成功查找（包括插入元素时内部发起的查找）。_探测长度_是每次操作访问的 xref:structures.adoc#structures_open_addressing_containers[桶组]数量。若哈希函数行为正确：

* 平均探测长度应接近 1.0。
* 每次成功查找的平均比较次数应接近 1.0（即仅检查找到的元素）。
* 每次未成功查找的平均比较次数应接近 0.0。

提供了 link:../../../benchmark/string_stats.cpp[示例^]，展示 `boost::hash<std::string>`、https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function#FNV-1a_hash[FNV-1a 哈希^] 及两个被错误标记为雪崩的不良自定义哈希函数的容器统计信息：

[listing]
----
                   boost::unordered_flat_map:   319 ms
                                   insertion: probe length 1.08771
                           successful lookup: probe length 1.06206, num comparisons 1.02121
                         unsuccessful lookup: probe length 1.12301, num comparisons 0.0388251

           boost::unordered_flat_map, FNV-1a:   301 ms
                                   insertion: probe length 1.09567
                           successful lookup: probe length 1.06202, num comparisons 1.0227
                         unsuccessful lookup: probe length 1.12195, num comparisons 0.040527

boost::unordered_flat_map, slightly_bad_hash:   654 ms
                                   insertion: probe length 1.03443
                           successful lookup: probe length 1.04137, num comparisons 6.22152
                         unsuccessful lookup: probe length 1.29334, num comparisons 11.0335

         boost::unordered_flat_map, bad_hash: 12216 ms
                                   insertion: probe length 699.218
                           successful lookup: probe length 590.183, num comparisons 43.4886
                         unsuccessful lookup: probe length 1361.65, num comparisons 75.238
----
