[[header]]
== 引言

[[content]]
https://en.wikipedia.org/wiki/Hash_table[哈希表]是一种极其流行的计算机数据结构，几乎在所有编程语言中都能找到其不同形式的存在。红黑树（在
C++ 中被 `std::set` 和 `std::map`
使用）等其他关联结构在插入和查找操作上具有对数时间复杂度，但哈希表若配置得当，这些操作的平均时间复杂度可达到常数级别，并且通常速度更快。

C++11 标准引入了__无序关联容器__
`std::unordered_set`、`std::unordered_map`、`std::unordered_multiset`和`std::unordered_multimap`，但针对哈希表的研究并未止步：CPU架构的进步（如更强大的缓存、https://en.wikipedia.org/wiki/Single_instruction,_multiple_data[SIMD]指令集以及日益普及的https://en.wikipedia.org/wiki/Multi-core_processor[多核处理器]）为改进基于哈希的数据结构创造了新的可能，这些新应用场景已远超
2011 年标准所定义的无序关联容器的能力范围。

Boost.Unordered
提供了一系列哈希容器，它们在标准符合性、性能表现和设计应用场景上各有不同：

.表1. Boost.Unordered容器
[width="100%",cols="34%,33%,33%",]
|===
| |*基于节点* |*扁平*
|*闭寻址法* |`boost::unordered_set` +
`boost::unordered_map` +
`boost::unordered_multiset` +
`boost::unordered_multimap` |
|*开放寻址法* |`boost::unordered_node_set` +
`boost::unordered_node_map` |`boost::unordered_flat_set` +
`boost::unordered_flat_map`
|*并发* |`boost::concurrent_node_set` +
`boost::concurrent_node_map` |`boost::concurrent_flat_set` +
`boost::concurrent_flat_map`
|===

* **闭寻址式容器**完全符合C++无序关联容器规范，并在标准接口的技术约束范围内提供了业界领先的运行性能。
* **开放寻址式容器**采用了更高效的数据结构与算法（典型场景下性能提升2倍以上），同时为了适配实现方案而对标准接口做了细微调整。该类容器包含两种变体：*扁平式*（最快）与**基于节点式**，后者在重新哈希时能保持指针稳定性，但性能会有所下降。
* 最后，**并发容器**专为高性能多线程场景设计实现，其接口与常规C++容器截然不同。提供扁平与基于节点两种变体。

Boost.Unordered中所有集合与映射的实例化方式分别类似于`std::unordered_set`和`std::unordered_map`：

[source,highlight]
----
namespace boost {
    template <
        class Key,
        class Hash = boost::hash<Key>,
        class Pred = std::equal_to<Key>,
        class Alloc = std::allocator<Key> >
    class unordered_set;
    // unordered_multiset, unordered_flat_set, unordered_node_set,
    // concurrent_flat_set 和 concurrent_node_set 同理

    template <
        class Key, class Mapped,
        class Hash = boost::hash<Key>,
        class Pred = std::equal_to<Key>,
        class Alloc = std::allocator<std::pair<Key const, Mapped> > >
    class unordered_map;
    // unordered_multimap, unordered_flat_map, unordered_node_map,
    // concurrent_flat_map 和 concurrent_node_map 同理
}
----

在无序关联容器中存储对象需要键值相等函数和哈希函数。标准容器的默认函数对象支持基础类型（包括整型、浮点型、指针类型及标准字符串）。由于Boost.Unordered使用link:../../../../container_hash/index.html[boost::hash]，它还支持其他类型（包括标准容器）。若需使用不受支持的类型，必须扩展Boost.Hash或自定义相等谓词与哈希函数。详见link:hash_equality.html#hash_equality[相等谓词与哈希函数]章节。

[[footer]]
[[footer-text]]
最后更新于2025年10月31日 21:32:30 UTC
