[[header]]
== 引言

[[content]]
https://en.wikipedia.org/wiki/Hash_table[哈希表]是极其流行的计算机数据结构，几乎在任何编程语言中都能以某种形式找到。而其他关联结构（如C{plus}{plus}中`std::set`和`std::map`使用的红黑树）在插入和查找操作上具有对数时间复杂度，而哈希表如果配置得当，平均能在常数时间内完成这些操作，通常要快得多。

C{plus}{plus}11__无序关联容器__`std::unordered++_++set`、`std::unordered++_++map`、`std::unordered++_++multiset`和`std::unordered++_++multimap`，但哈希表的研究并未止步：CPU架构的进步，如更强大的缓存、https://en.wikipedia.org/wiki/Single_instruction,_multiple_data[SIMD]操作以及日益普及的https://en.wikipedia.org/wiki/Multi-core_processor[多核处理器]，为改进基于哈希的数据结构和新的应用场景开辟了可能，这些是2011年规范的无序关联容器无法企及的。

Boost.Unordered提供了一系列哈希容器，具有不同的标准符合度、性能和预期使用场景：

.表1. Boost.Unordered容器
[width="100%",cols="34%,33%,33%",]
|===
| |*基于节点* |*扁平*

|*闭地址法* |`boost::unordered++_++set` +
`boost::unordered++_++map` +
`boost::unordered++_++multiset` +
`boost::unordered++_++multimap` |

|*开地址法* |`boost::unordered++_++node++_++set` +
`boost::unordered++_++node++_++map`
|`boost::unordered++_++flat++_++set` +
`boost::unordered++_++flat++_++map`

|*并发* |`boost::concurrent++_++node++_++set` +
`boost::concurrent++_++node++_++map`
|`boost::concurrent++_++flat++_++set` +
`boost::concurrent++_++flat++_++map`
|===

* **闭地址法容器**完全符合C{plus}{plus}无序关联容器规范，在标准接口的技术约束下，提供了市场上最快的实现之一。
* **开地址法容器**依赖更快的数据结构和算法（在典型场景下快2倍以上），同时为适应实现而略微偏离标准接口。有两种变体：*扁平*（最快）和**基于节点**，后者在重哈希时提供指针稳定性，但速度较慢。
* 最后，**并发容器**专为高性能多线程场景设计和实现。其接口与常规C{plus}{plus}容器截然不同。提供了扁平与基于节点的变体。

Boost.Unordered中的所有集合和映射的实例化方式分别类似于`std::unordered++_++set`和`std::unordered++_++map`：

[source,highlight]
----
namespace boost {
    template <
        class Key,
        class Hash = boost::hash<Key>,
        class Pred = std::equal_to<Key>,
        class Alloc = std::allocator<Key> >
    class unordered_set;
    // 同样适用于unordered_multiset、unordered_flat_set、unordered_node_set、
    // concurrent_flat_set和concurrent_node_set

    template <
        class Key, class Mapped,
        class Hash = boost::hash<Key>,
        class Pred = std::equal_to<Key>,
        class Alloc = std::allocator<std::pair<Key const, Mapped> > >
    class unordered_map;
    // 同样适用于unordered_multimap、unordered_flat_map、unordered_node_map、
    // concurrent_flat_map和concurrent_node_map
}
----

在无序关联容器中存储对象需要键相等函数和哈希函数。标准容器中的默认函数对象支持一些基本类型，包括整数类型、浮点类型、指针类型和标准字符串。由于Boost.Unordered使用link:../../../../container_hash/index.html[boost::hash]，它还支持其他一些类型，包括标准容器。若要使用这些方法不支持的类型，您必须扩展Boost.Hash以支持该类型，或使用自定义的相等谓词和哈希函数。更多详情请参阅link:hash_equality.html#hash_equality[相等谓词与哈希函数]一节。

[[footer]]
[[footer-text]]
最后更新于2025年11月12日 19:10:45 UTC
