[#rationale]

:idprefix: rationale_

= 实现原理

== 闭址式容器

`boost::unordered_[multi]set` 和 `boost::unordered_[multi]map` 遵循无序关联容器的标准要求，因此接口是固定的。但仍有一些实现决策需要确定。首要考虑的是符合标准和可移植性。

http://en.wikipedia.org/wiki/Hash_table[维基百科关于哈希表的文章^] 对哈希表的一般实现问题有很好的总结。

=== 数据结构

通过指定访问容器桶的接口，标准几乎要求哈希表使用闭地址法。

编写使用其他方法的哈希表是可能的。例如，它可以使用开地址法，并利用查找链充当桶，但这样做存在一些严重问题：

* 标准要求指向元素的指针不能失效，因此元素不能存储在一个数组中，而是需要一层间接寻址——这会损失效率并丧失大部分内存优势，而这两者正是开地址法的主要优点。
* 局部迭代器将非常低效，可能无法满足复杂度要求。
* 还存在关于迭代器何时失效的限制。由于开地址法在碰撞次数高时性能会急剧下降，这些限制可能阻止在真正需要时进行重哈希。可以通过将最大负载因子设置为较低值来解决此问题——但标准要求其初始值设为1.0。
* 而且由于标准是围绕闭地址法编写的，如果性能不符合预期，用户会感到意外。

因此采用闭地址法。

=== 桶的数量

选择哈希表桶的数量有两种常用方法：一种是使用质数数量的桶，另一种是使用2的幂。

使用质数数量的桶，并通过哈希函数结果取模来选择桶，通常能获得良好效果。缺点是所需的取模操作相当昂贵。这是容器在大多数情况下过去采用的方式。

使用2的幂可以更快地选择桶，但代价是丢失哈希值的高位比特。对于某些专门设计的哈希函数，这样做仍能获得良好结果，但由于容器可接受任意哈希函数，因此不能依赖于此。

为避免此问题，可对哈希函数应用转换，例如参见 http://web.archive.org/web/20121102023700/http://www.concentric.net/~Ttwang/tech/inthash.htm[Thomas Wang关于整数哈希函数的文章^]。遗憾的是，类似Wang的转换需要知道哈希值的比特数，因此仅在`size_t`为64位时使用。

自1.79.0版起，改用https://en.wikipedia.org/wiki/Hash_function#Fibonacci_hashing[斐波那契哈希]。在此实现中，桶号通过`(h * m) >> (w - k)`确定，其中`h`是哈希值，`m`是`2^w`除以黄金分割率，`w`是字长（32或64位），`2^k`是桶的数量。这在速度和分布之间提供了良好的折衷。

自1.80.0版起，选择质数作为桶的数量，并辅以复杂的模运算。这消除了1.79.0版中对用户哈希函数结果进行“混合”的需求。

== 开地址容器

C++标准对无序关联容器的规范对允许的实现施加了严格限制，最重要的是隐式假设了闭地址法。稍微放宽此规范为充分利用开地址技术提供容器变体开辟了可能性。

`boost::unordered_flat_set`/`unordered_node_set`和`boost::unordered_flat_map`/`unordered_node_map`的设计遵循Peter Dimov的https://pdimov.github.io/articles/unordered_dev_plan.html[Boost.Unordered开发计划^]。我们在此讨论最相关的原则。

=== 哈希函数

鉴于其丰富的功能和跨平台互操作性，`boost::hash`仍是开地址容器的默认哈希函数。但`boost::hash`对于整型和其他基本类型不具备开地址法所需的统计特性；为此我们实现了一个后混合阶段：

{nbsp}{nbsp}{nbsp}{nbsp} _a_ <- _h_ *mul* _C_, +
{nbsp}{nbsp}{nbsp}{nbsp} _h_ <- *high*(_a_) *xor* *low*(_a_),

其中*mul*是_扩展乘法_（64位架构中为128位，32位环境中为64位），*high*和*low*分别是扩展字的高半部和低半部。在64位架构中，_C_是2^64^&#8725;https://en.wikipedia.org/wiki/Golden_ratio[_&phi;_]的整数部分，而在32位中_C_ = 0xE817FB2Du（取自https://arxiv.org/abs/2001.05304[Steele和Vigna (2021)^]）。

当使用直接适用于开地址法的哈希函数时，可通过专用`link:../../../../container_hash/doc/html/hash.html#ref_hash_is_avalanchinghash[hash_is_avalanching]`特性选择退出后混合。字符串类型的`boost::hash`特化被标记为雪崩式。

=== 平台互操作性

只要不同编译器的``std::size_t``大小相同且用户提供的哈希函数和相等谓词也具有互操作性，`boost::unordered_flat_set`/`unordered_node_set`和`boost::unordered_flat_map`/`unordered_node_map`的可观察行为在不同编译器间是确定性相同的——这包括相同操作序列下元素的顺序完全一致。

尽管实现在内部使用了SIMD技术（如https://en.wikipedia.org/wiki/SSE2[SSE2^]和https://en.wikipedia.org/wiki/ARM_architecture_family#Advanced_SIMD_(NEON)[Neon^]），但这不影响互操作性。例如，在支持SSE2的x64模式Intel CPU上的Visual Studio与不支持任何SIMD技术的IBM s390x上的GCC行为相同。

== 并发容器

Boost.Unordered开地址容器使用的相同数据结构也被选作`boost::concurrent_flat_set`/`boost::concurrent_node_set`和`boost::concurrent_flat_map`/`boost::concurrent_node_map`的基础：

* 开地址法在非并发和并发场景下都比闭地址法替代方案更快。
* 开地址布局非常适合以最小锁实现并发访问和修改。特别是，元数据数组可用于实现查找操作，该操作在最终实际元素比较步骤之前是无锁的。
* 与Boost.Unordered平面容器的布局兼容性允许在并发容器与其非并发对应容器之间xref:concurrent.adoc#concurrent_interoperability_with_non_concurrent_containers[快速转移]所有元素，反之亦然。

=== 哈希函数与平台互操作性

在xref:#rationale_hash_function[哈希函数默认设置]和xref:#rationale_platform_interoperability[平台互操作性]方面，并发容器做出与Boost.Unordered开地址容器相同的决策并提供相同的保证。
